### ISSUE TITLE
Add full file name to file quickinfo

### ISSUE THREAD

**Issue by agaida** [lxqt/pcmanfm-qt#1000]
![](https://i.imgur.com/U6um1sT.jpg)
i would really like to know which file it is.

It works in the other direction nearly well:
![](https://i.imgur.com/d7QrvOb.jpg)

**Comment by tsujan** [comment]
Yes, the tooltip should follow the view setting in this regard.

**Comment by tsujan** [comment]
And the same for the status-bar.

**Comment by tsujan** [comment]
Ah, and the same for Properties dialog. Actually, I found a bug in it; will make an issue.

**Comment by tsujan** [comment]
All done.
