### ISSUE TITLE
[SMB] Can't copy folder with contents

### ISSUE THREAD

**Issue by 4llan** [lxqt/pcmanfm-qt#1004]
##### Expected Behavior
Try to copy samba folder and it's contents and warns me if something goes wrong.

##### Current Behavior
I was trying to copy a folder inside a samba share directly mounted via pcmanfm-qt `smb://` and only the folder, without it's contents, was copied. No warning or error message was triggered (it was running as a daemon).

Launching via command line, everytime I enter or change the samba folder, an error dialog is show: `Operation was cancelled`

The first error message, after mounting the share with pcmanfm-qt is:
```
Error while getting peer-to-peer dbus connection:
Operation was cancelled
```

But I still navigate in the folders and copy it's contents in the top level dir.

The "Copy" action (via menu or `Ctrl + C`) doesn't trigger any warning in console or dialog. Neither "Paste". It's like pcmanfm-qt thinks that I'm copying an empty folder and paste it accordingly. Multiple file copy works without problems.

Error dialog behavior identic to #917, copy/paste behavior identical to #686.

I'm not using Wayland. Bare `startx` with `exec startlxqt` in `~/.xinitrc`

##### Steps to Reproduce (for bugs)
1. `pcmanfm-qt --quit`
2. `pcmanfm-qt smb://[insert samba share here]`
3. Navigate through folders
4. Try to copy a folder with contents

##### Console output example:
```
# pcmanfm-qt smb://192.168.137.1/public
isPrimaryInstance
ask password
operation finished: 0x0
delete MountOperation
file monitor cannot be created: Operation not supported by backend
file monitor cannot be created: Operation not supported by backend
file monitor cannot be created: Operation not supported by backend
file monitor cannot be created: Operation not supported by backend
gvim -f '/run/user/1000/gvfs/smb-share:server=192.168.137.1,share=public/teste/test.txt' 
file monitor cannot be created: Operation not supported by backend
file monitor cannot be created: Operation not supported by backend
aboutToQuit
```

##### System Information
* Distribution & Version: Arch Linux
* Kernel: 5.2.10
* Qt Version: 5.13.0
* libfm-qt Version: 0.14.1-1
* libqtxdg Version: 3.3.1-5
* lxqt-build-tools Version: ?
* Package version: 0.14.1-1
* gvfs 1.40.2-1
* gvfs-smb 1.40.2-1

**Comment by tsujan** [comment]
Fixed a long time ago in git.

You could use the git versions (of libfm-qt and pcmanfm-qt) or wait for the next release (shouldn't tale long).

**Comment by 4llan** [comment]
Thanks! Sorry for bothering you
