### ISSUE TITLE
PCManFm-Qt crashes then renaming a favorite folder with dot in name

### ISSUE THREAD

**Issue by FrederikLauber** [lxqt/pcmanfm-qt#1009]
Hi,

for some reason, pcmanfm-qt seems to crash every time I try to create a favorite folder with a dot in the name. This has worked in the past as I have multiple favorites who have that but does not work anymore.

##### Expected Behavior
A favorite with the name should be created

##### Current Behavior
PCManFM-Qt crashes

##### Steps to Reproduce (for bugs)
1. Right click on a favorite folder
2. Select Rename
3. Enter a Name with a Dot inside
4. Enter

Also, see attached video

##### Context
I have a lot of sftp folders where I want the favorite name to be the domain name.

##### System Information
* Distribution & Version: Arch Linux
* Kernel: 5.2.11-arch1-1-ARCH
* Qt Version: Qt 5.13.0 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 9.1.0) on "xcb" 
* libfm-qt Version: 0.14.1-1
* libqtxdg Version: 3.3.1-5
* lxqt-build-tools Version: 0.6.0-1
* Package version: 0.14.1-1
[foo.zip](https://github.com/lxqt/pcmanfm-qt/files/3586461/foo.zip)

**Comment by tsujan** [comment]
What do you mean by "favorite folder"?

**Comment by tsujan** [comment]
OK, your video shows that you mean bookmark.

Confirmed!

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxqt/libfm-qt/pull/466 . It'll be merged soon.

Thanks for the report!
