### ISSUE TITLE
How to add containing folder context menu to compact and detail views?

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#1013]
Icon and thumbnail views have spaces between their items, so that the user can right click there and see the folder context menu, without selecting any item. But the empty spaces of compact and detail views are at their ends. My questions:

1. Is that a real problem and why? (Please note that we have the File menu.)

2. If yes, where could we add the context menu for the containing folder?

As for the detail view:

I won't agree with this answer: " By right clicking on a column other than the name." That's a design flaw in some other file managers because every row is about a single file.

Pressing `Ctrl` and then right clicking isn't a good idea either because the user can't know about it (unless we could tell him/her in an acceptable way).

**Comment by agaida** [comment]
One Problem i currently see is that we work with full rows. Don't know if we could change it if we want. thunar has an interesting approach for marking, has to test dolphin first before i write more about.

**Comment by tsujan** [comment]
@agaida I forgot that I'd added a feature: Right click the header, uncheck auto-resize, and resize the name column to have a lot of empty space to the right :)

**Comment by tsujan** [comment]
OK. No problem to solve. The compact view also has empty spaces at the bottom.

**Comment by agaida** [comment]
tststs :P - they have a really interesting approach - an maybe we can use this approach

**Comment by tsujan** [comment]
I'll take a look at it as soon as I find the time. Then, I'll tell about my opinion. For now, I think we don't need any change in this regard.

**Comment by PiyushXCoder** [comment]
😐 Really do you think its really interesting approach about empty spaces at bottom. 😅Take my advice. Open you /usr/lib folder. And drag to bottom for your easy approach. And @tsujan 😂😂disabling auto-resize column generates a desagin problem. Its not a solution.

**Comment by tsujan** [comment]
@PiyushXCoder If you have something useful to add, please say it. Otherwise, don't clutter this page with comments that say the same thing with different words (and emojis);  this is an issue tracker, not a Facebook page.

**Comment by tsujan** [comment]
@agaida I installed and checked Thunar: When you right click a column other than "Name" on an *unselected row*, it deselects all items and shows the containing folder context menu. It may be better than what Dolphin does but isn't acceptable to me for the reason I explained in my first comment.

**Comment by tsujan** [comment]
More specifically and for the sake of argument:

You right click a column *that belongs to an item*. Why showing the context menu of the containing folder?!

I like borrowing good ideas from good apps (like Dolphin and Thunar) as much as I don't like their bad ideas — regardless of how many users have accepted them as the status quo.

**Comment by PiyushXCoder** [comment]
I've an idea. You may add it as an function in event listener and a setting regarding this. If the function is enabled then right click on other columns will show parent's sub menu. For those who like "Every row is about a single file" they can disable it. By default keep it disabled so normal users can use it as it is. We can do same for more permission column.

**Comment by PiyushXCoder** [comment]
There is one more way. In path bar, when its set to "Path Button" then right click on each button can show sub menu of that parent folder.

**Comment by tsujan** [comment]
> You may add it as an function in event listener and a setting regarding this

@PiyushXCoder Please be more specific. Tell your idea in terms of GUI and in a way that's easily understood by the average user.

I often implement good ideas -- although not implementing an idea doesn't necessarily mean it isn't good (there may be other reasons).

> There is one more way. In path bar

No! Path bar isn't related to this at all.

**Comment by PiyushXCoder** [comment]
I mean that we can add an option in "Edit > Preferences" regarding enabling and disabling the approach of showing parents menu for right click on any column other than "Name". And Keep it disabled by default. And anyone who want it can enable it. 

And we can also have same approach of hidden permission column. Those who think its ugly will keep it hidden.

**Comment by tsujan** [comment]
> I mean that we can add an option...

It's a good idea. Will think about it.

> And we can also have same approach of hidden permission column.

Adding this or that option that isn't popular/needed is not an option. This page was opened because of a usability question, not because of what a specific user likes/dislikes.

**Comment by PiyushXCoder** [comment]
🙂The application which can be configured as per need for user is more user friendly. Every likes something aur dislikes something but if we can give option to configure asthey want its a better.

**Comment by tsujan** [comment]
We don't add too many options; we don't want LXQt config dialogs to be as frightening as KDE's are. Everything has a limit, beyond which it becomes absurd.

**Comment by PiyushXCoder** [comment]
😊 Its abut a single option. We have only 6 columns right now. Just one more can't be too heavy. Please add it.

**Comment by tsujan** [comment]
In case you didn't have time to read (although you have lots of time to write): "... don't clutter this page with comments that say the same thing with different words." You did it again.

**Comment by agaida** [comment]
@PiyushXCoder - it takes a bit of time to understand the discussion culture here - i'm sorry about. But it works fine :smile: . Now you know what the likes and the dislikes of the people in charge are - in that special area. And now to the normal part: 
* a rights column would be fine for me (at least it would not hurt, if not showed - speedwise). This column would not solve any and far more important problems with file access controls.. That don't mean that we shouldn't think of.
* @tsujan is right most of the time, me too - it is the balance of goodies we can implement versus raw speed and a uncluttered environment. No words without a lawyer here.
* I for myself like to lurk around and (try to) see really good ideas in other desktop environments, even in non linux ones like Windows 10. And yes, I have the qualification to do so. And I'm verbose about it.
* finally, but please don't judge a book by it's cover: I'm a debian kind of guy now, but not inked in the whool, my secret loves still are Arch (first place) and other distributions who are not that political correct - and yes, i can handle them without any problems. Long story short, send a PR and be prepared for a long discussion, it is worth it.

**Comment by tsujan** [comment]
This is my opinion:

An empty column looks weird to me; it would be ugly too, sacrificing elegance and space for something unimportant.

An empty space to the right can already be created by disabling auto-resizing. So, IMO, there's no problem to solve.

Something like Thunar/Dolphin's behavior but *optional and not as the default behavior* might be acceptable: right clicking any column other than "name" shows the folder context menu. It's wrong but acceptable as an option and with a short explanation. However, I don't have the slightest reason to implement it. To me, it's totally useless because auto-resizing can be disabled.

**Comment by agaida** [comment]
erm - it might be that i'm not verbose enough about - but the whole discussion is about non-standard and optional things - really: I'm not able to see that we forget about something essential - no way. But we might be in a situation where it is possile to implement some wanted goodies. Ok, i would judge the permission things as more as a goodie. And please be patient until i'm able to record  the screencasts about functionality that i miss in pcmanfm-qt and that are available partly in some other file managers (has worked before really fine after some discussions). And please take out ignorant guru's space-fm out of discussion. Nice on a technical level that i don't want to discuss - but he is a person non grata to me, so take what you want in case, i didn't want to know it.

**Comment by tsujan** [comment]
I have an idea. As said above, the ways Thunar and Dolphin do it aren't self-consistent. But this may make sense:

Adding an option *for all views*, so that if it's checked, `Ctr + right click` shows the context menu of the containing folder. The existence of an option solves the problem of informing users. In this way, users of the icon/thumbnail views won't need to search for an empty space either.

**Comment by tsujan** [comment]
Update:

It was easy to implement and works fine:

![ctrl+right_click](https://user-images.githubusercontent.com/981076/65697841-81d67380-e088-11e9-8c9d-a5c80e03f2cc.png)

Two small patches are needed for libfm-qt and pcmanfm-qt.

**Comment by tsujan** [comment]
> And please take out ignorant guru's space-fm out of discussion.

I missed this part; it was quite pertinent. I haven't seen anything useful in space-fm. Nautilus has nothing to offer either; following Gnome's tradition, it has become an obstacle to file management. On the contrary, Dolphin has been a source of inspiration; Thunar too.
