### ISSUE TITLE
No auto-refresh on NAS

### ISSUE THREAD

**Issue by BRenaudier** [lxqt/pcmanfm-qt#1025]
Summary : When adding, removing, renaming a file on a distant folder (NAS), PCManFM-QT not automatically refresh.
I have to refresh manually (F5) to see the changes.

##### Expected Behavior
When renaming a file, name should change. When adding a file, file should appear. When removing a file, file should be remove.

##### Current Behavior
Screen isnt refresh automatically

##### Steps to Reproduce (for bugs)
On a NAS :
1. Add a file to a folder
2. Rename a file
3. Remove a file

##### System Information
* Distribution & Version: Lubuntu 19.04
* Kernel: 5.0.0-27-generic
* Qt Version: 0.14.1
* libfm-qt Version: 0.14.1-0ubuntu2.1
* libqtxdg Version: Not installed
* lxqt-build-tools Version: Not installed
* Package version:

**Comment by tsujan** [comment]
Fixed 6 months ago in https://github.com/lxqt/libfm-qt/commit/62a815038a2339d85a5cb21f31af9df898191588

Please note that there are so many commits after 0.14.1.
