### ISSUE TITLE
Version 0.14.1 – Issues with Places and Bookmarks

### ISSUE THREAD

**Issue by Russell-S-Harper** [lxqt/pcmanfm-qt#1027]
##### Expected Behavior

Should be possible to add folders to left hand navigation pane.
Should not be a distinction between Places or Bookmarks, just a list of folders.
The phrase "Places" should not be duplicated, especially when so closely positioned.

##### Current Behavior

Cannot add folders to either Places or Bookmarks.
Separate sections in Places and Bookmarks is confusing.
The phrase "Places" is duplicated, causing confusion, with bizarre alignment, giving an unprofessional look to the product.

##### Possible Solution

* Places and Directory Tree dropdown is okay, keep as-is.
* Remove Places and Bookmark headings from listing, just a plain list like this:
> Desktop
Downloads
Computer
Music
Pictures
Video
* Remove hardcoding in config file desktop-items-0.conf (e.g. PlacesApplications, PlacesComputer, PlacesDesktop, ...), and unify Places with Bookmarks.
* Allow drag and drop of folders into this pane.
* Use drag & drop to show and delete to hide as primary methods to update this pane.
* Special folders, such as Trash, can have a checkbox interface to show, but should still allow delete to hide.
* Remove +/− from folders, they don't do anything, easy to accidentally click, and the − looks like a rendering artifact. 

##### Steps to Reproduce (for bugs)

1. Open pcmanfm-qt
2. Get confused by "Places" appearing twice
3. Try to add Downloads under Places or Bookmarks, won't be able to
4. Check if there is a backdoor way to do it, note the hard coding in the config file means likely not possible

##### Context

The pcmanfm-qt application is significantly flawed as-is, especially that it's the primary application, that is, typically the first opened to begin any task. Not customizable in ways most users would like, confusing in parts, and non-functional.

If I'm doing some file restructuring, I'm finding I have to open up other file manager windows to keep one or more destinations open, because Places/Bookmarks doesn't work.

##### System Information

* Distribution & Version: Ubuntu 19.04
* Kernel: 5.0.0-31-generic
* Qt Version: 5.12.2
* libfm-qt Version: 0.14.1
* libqtxdg Version: 
* lxqt-build-tools Version: 
* Package version:

**Comment by tsujan** [comment]
You can add/remove bookmarks. The other items are hard-coded.

Your report was a description of your personal opinions about how a file manager should be. Your opinions are respected but the original author of pcmanfm-qt, its developers and so many users don't think as you do.

> The pcmanfm-qt application is significantly flawed as-is

It isn't.
