### ISSUE TITLE
PCMAnFM-QT doesn't open as root

### ISSUE THREAD

**Issue by Darklink999999** [lxqt/pcmanfm-qt#1028]
Hello, I just installed Manjaro LXQT and trying to run `pcmanfm-qt` as root. After an exhausting search I managed to make sudo keep the environment variables. Now I'm at the point where I get this error when running "sudo pcmanfm-qt`:

`QStandardPaths: wrong ownership on runtime directory /run/user/1000, 1000 instead of 0`

I asked on the Manjaro forums and got told to write a report here. Has anyone else had this problem before?

##### Expected Behavior
PCManFM-QT should open as root.

##### Current Behavior
I got the error mentioned above.

##### Steps to Reproduce (for bugs)
1. Install Manjaro LXQT
2. Try running "sudo pcmanfm-qt"

##### Context
I want to be able to paste files in root filesystem

##### System Information

```
System:
  Host: qushy-pc Kernel: 5.2.21-1-MANJARO x86_64 bits: 64 compiler: gcc v: 9.2.0 
  Desktop: LXQt 0.14.1 Distro: Manjaro Linux 
Machine:
  Type: Laptop System: Dell product: Inspiron 7577 v: N/A serial: <filter> 
  Mobo: Dell model: 0J8HMF v: A00 serial: <filter> UEFI: Dell v: 1.6.1 
  date: 08/16/2018 
Battery:
  ID-1: BAT0 charge: 26.1 Wh condition: 26.1/56.0 Wh (47%) 
  model: Samsung SDI DELL W7NKD77 status: Full 
CPU:
  Topology: Quad Core model: Intel Core i7-7700HQ bits: 64 type: MT MCP 
  arch: Kaby Lake rev: 9 L2 cache: 6144 KiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 44944 
  Speed: 3714 MHz min/max: 800/3800 MHz Core speeds (MHz): 1: 3694 2: 3694 3: 3639 
  4: 3712 5: 3640 6: 3704 7: 3524 8: 3742 
Graphics:
  Device-1: Intel HD Graphics 630 vendor: Dell driver: i915 v: kernel bus ID: 00:02.0 
  Device-2: NVIDIA GP106M [GeForce GTX 1060 Mobile] vendor: Dell driver: nvidia 
  v: 418.88 bus ID: 01:00.0 
  Display: x11 server: X.org 1.20.5 driver: modesetting,nvidia 
  resolution: <xdpyinfo missing> 
  OpenGL: renderer: GeForce GTX 1060 with Max-Q Design/PCIe/SSE2 
  v: 4.6.0 NVIDIA 418.88 direct render: Yes 
Audio:
  Device-1: Intel CM238 HD Audio vendor: Dell driver: snd_hda_intel v: kernel 
  bus ID: 00:1f.3 
  Sound Server: ALSA v: k5.2.21-1-MANJARO 
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Dell 
  driver: r8169 v: kernel port: d000 bus ID: 3b:00.0 
  IF: enp59s0 state: down mac: <filter> 
  Device-2: Intel Wireless 8265 / 8275 driver: iwlwifi v: kernel port: d000 
  bus ID: 3c:00.0 
  IF: wlp60s0 state: up mac: <filter> 
Drives:
  Local Storage: total: 1.38 TiB used: 234.88 GiB (16.7%) 
  ID-1: /dev/nvme0n1 vendor: Toshiba model: KXG50ZNV512G NVMe 512GB size: 476.94 GiB 
  ID-2: /dev/sda vendor: Seagate model: ST1000LM035-1RK172 size: 931.51 GiB 
Partition:
  ID-1: / size: 468.16 GiB used: 173.28 GiB (37.0%) fs: ext4 dev: /dev/nvme0n1p2 
Sensors:
  System Temperatures: cpu: 64.0 C mobo: 63.0 C sodimm: 50.0 C gpu: nvidia temp: 67 C 
  Fan Speeds (RPM): cpu: 5159 
Info:
  Processes: 246 Uptime: 9h 26m Memory: 15.53 GiB used: 2.87 GiB (18.5%) 
  Init: systemd Compilers: gcc: 9.2.0 Shell: zsh v: 5.7.1 inxi: 3.0.36 
```

**Comment by agaida** [comment]
@tsujan - your part - i don't know manjaro :D

**Comment by tsujan** [comment]
@Darklink999999 
You should never ever use `sudo` with `pcmanfm-qt` (you may have changed the permissions of its config directory by doing so; check the permissions of `~/.config/pcmanfm-qt` and its contents).

Go to Preferences → Advanced and set "Switch user command" to:

```
lxsudo dbus-run-session -- %s
```

This should be the default. I have the latest Manjaro testing and pcmanfm-qt runs as root without problem.

**Comment by tsujan** [comment]
And after that, open the root instance from Tool → Open as root; no terminal is needed.

**Comment by tsujan** [comment]
@agaida Manjaro = Arch + some things that make its installation a piece of cake + a few things that make its usage easier + a little more security ;)

Although it's relation to Arch is compared to that of Ubuntu to Debian, that's not true: Manjaro is loyal to Arch; Ubuntu isn't to Debian.

**Comment by agaida** [comment]
:D - good explanation - but i guess i will stay with my old love Arch :D

**Comment by tsujan** [comment]
> but i guess i will stay with my old love Arch :D

Arch didn't love me; Debian and Manjaro did.

Anyhow, every man has his loves.
