### ISSUE TITLE
Allow one wallpaper per screen on multihead setups

### ISSUE THREAD

**Issue by jleclanche** [lxqt/pcmanfm-qt#103]
Right now, the "screen" is actually the sum of all screens.

**Comment by Justinzobel** [comment]
Are we able to get an update on this @PCMan ?

**Comment by jubalh** [comment]
Mentioning the workaround here so people don't keep asking the same question again and again:
Go into lxqt-config -> session -> basic settings -> LXQt Modules. And disable desktop. Like this pcman-fm will not take care of the wallpaper (but also no icons on desktop). Now use the third party program `nitrogen` to set the wallpaper.

**Comment by Justinzobel** [comment]
No proper fix after 4.5 years?

**Comment by jubalh** [comment]
That's 4.5 years that you could have been working on it ;)

**Comment by Justinzobel** [comment]
I only commented 14 days ago. Is this not a feature that LXQt plans to support?

**Comment by jubalh** [comment]
We plan to support it. But noone had the time or inclination to work on it yet.

**Comment by Justinzobel** [comment]
A second-hand monitor would be extremely cheap to pick up. Multi-monitor setups are quite common these days.

Is it possible to re-open this task then and mark it as Wishlist?

**Comment by jubalh** [comment]
> Multi-monitor setups are quite common these days.

True.

> Is it possible to re-open this task then and mark it as Wishlist?

Actually this task is still open. 983 was closed as duplicate.
And it's also added to wishlist, which you can see at the top right under "Projects".

I also think it would be good to have this, but have no idea how much work/knowledge it involves.

**Comment by Justinzobel** [comment]
Sorry, saw the closed symbol for the linked issue.

**Comment by tsujan** [comment]
Done in https://github.com/lxqt/pcmanfm-qt/commit/dfdf1fa0db00330d927e664c8e6829c0835adfa7 (and fixed after it).

Different wallpapers for different screens isn't an option because we/I want to keep the code manageable and maintainable, avoiding overcomplications.

**Comment by Justinzobel** [comment]
Thanks!

**Comment by audas** [comment]
Sorry - so is there the ability to have different wall papers for each screen ? If so how do we set it ?

**Comment by tsujan** [comment]
No, there isn't.

**Comment by audas** [comment]
I edited the config files and set the wallpaper to be different on each - rebooted and the wallpaper was different on each screen?
I can now no longer drag any windows around, the maximise, minimise and close buttons no longer work.

**Comment by tsujan** [comment]
> I edited the config files and set the wallpaper to be different on each

There's no key for that in pcmanfm-qt's config file. You probably edited the config file of another program.

> I can now no longer drag any windows around

pcmanfm-qt has nothing to do with window dragging,...
