### ISSUE TITLE
Views?

### ISSUE THREAD

**Issue by SafaAlfulaij** [lxqt/pcmanfm-qt#104]
What about adding views? Each tab has views splitted horizontally and virtually, Exactly like QTerminal.
Also what about a view for QTerminal in the bottom of the Files/Folders view? ;)
![qterminalviews](https://cloud.githubusercontent.com/assets/3509617/4921708/35b4f730-650c-11e4-95aa-dbebe6fcae15.png)

**Comment by stefonarch** [comment]
Split view with drop+drag for me is a must-have, too.

**Comment by tsujan** [comment]
Years have passed and I've seen many people who liked a split view. Now that filtering is tab-specific, an obstacle is removed. Theoretically speaking, this shouldn't be difficult but when it comes to practice, problems might come out of their hiding places. I'll look into it: this or its simpler form https://github.com/lxqt/pcmanfm-qt/issues/644

**Comment by agaida** [comment]
@tsujan - but you are aware of the app here - it's qterminal

**Comment by tsujan** [comment]
> @tsujan - but you are aware of the app here - it's qterminal

I know :) A simple idea came to mind and I think it can be implemented -- I can't resist the temptation ;) The major obstacle was the global filter-bar; now there isn't any: each tab page has its own filter-bar.

At least, I should get my hands dirty to know what's what.

**Comment by tsujan** [comment]
Update:

I started to play with the code and saw that it's possible. File DND worked out of box. Each view responded to forward/backward/up buttons only when "activated". But there are lots of details to be considered and dealt with. One of them is the path-bar. When there are 2 views, there should be 2 path-bars and the best place for each of them is at the bottom of its corresponding tab-bar. When there's only one view, the current path-bar should be used (unlike in Dolphin) for saving the vertical space.

As far as I see, this feature won't add to pcmanfm-qt's weight because the default is a single view and no extra widget is created in that case. A double-view mode should be light too if implemented correctly. But it might take a long time to be completed; I can do it only little by little.

**Comment by agaida** [comment]
but it would be cool to have - i know people who make heavy use of dual panes - dunno exactly why :)

**Comment by tsujan** [comment]
> i know people who make heavy use of dual panes - dunno exactly why :)

It's one of those things you'll get addicted to if you use it for a while. I do the same jobs by detaching a tab and tiling 2 pcmanfm-qt windows beside each other but a single window with 2 views will be much more comfortable.

**Comment by Chiitoo** [comment]
Split view is something I still miss from my time spent in Dolphin, so I'm definitely looking forward to this.  :]

**Comment by tsujan** [comment]
> Split view is something I still miss from...

Good! The more it's missed, the more it'll be tested when ready ;)

**Comment by tsujan** [comment]
I have a habit of not sharing a work in progress ;) After I finish it (in the reasonable sense of the word "finish"), I'll test it for a short time and then make a PR. Then, your tests will be very appreciated.

**Comment by tsujan** [comment]
This screenshot, which is intentionally taken with Fusion, isn't correct because the path-bar is still shared (there should be two path-bars) but I wanted to know whether it's obvious which view is active and which not:

![test](https://user-images.githubusercontent.com/981076/44463503-2d62f800-a62d-11e8-8c4b-3ecbf37ca7d3.png)

Is it obvious?

**Comment by agaida** [comment]
for me: yes

**Comment by tsujan** [comment]
> for me: yes

I updated the screenshot before your reply; you might say "no" before the changes :)

On second thought, I think a single path-bar is enough. Its contents can be easily updated when the active view frame (as I called it in the code) changes. In this way, no extra space is taken vertically. I also think it's better than Dolphin but should wait for @stefonarch's and @Chiitoo's opinions when it's finished. A lot of work should still be done....

**Comment by agaida** [comment]
ok, the pro would be - one can see exactly the target of the pane - con - a bit more space is used
![](https://pb.5id.eu/wmGA.jpg)

**Comment by tsujan** [comment]
I'll come back to this when other problems are solved.

**Comment by tsujan** [comment]
For now, I can see at least 5 issues, some of which are visible in Dolphin too. For example, how does Dolphin switch between views *with keyboard*? `Tab` doesn't work for it. For pcmanfm-qt, `Tab` works but the `Shift+Tab` should be pressed twice (or `Tab` should be pressed 3 times) for going back.

**Comment by tsujan** [comment]
OK, I agree that a little extra space (16 or 22 px, depending on the style) is worth it. 2 path-bars for 2 view frames, which means more difficulty....

**Comment by agaida** [comment]
fyi - a siduction user told me that switching panes in dolphin can set in the dolphin shortcuts

**Comment by tsujan** [comment]
> fyi - a siduction user told me that switching panes with tab can set in the dolphin shortcuts

I didn't know that -- which means it isn't obvious ;)

`Tab` is the best key for such things. Krusader does it very well. I'll see if it's possible to imitate Krusader; if not, a shortcut should be added for it as the last resort.

**Comment by tsujan** [comment]
A path-bar (or path-entry) above each view frame (the screenshot is taken with Fusion again):

![pathbar](https://user-images.githubusercontent.com/981076/44508830-f4766200-a6c4-11e8-9f50-8d7655e9712a.png)

Path-bars below tab-bars seemed weird and untidy.

BTW, the "full-width tab bar" (for simple views) should be sacrificed. Keeping it would require a lot of ugly codes.

**Comment by agaida** [comment]
+1

**Comment by tsujan** [comment]
FYI, the remaining steps:

 * Add an action to toggle the split mode. Right now, it's either simple or split. This isn't easy because of path-bars.
 * Remember the split mode -- a piece of cake.
 * Read `mainwindow.cpp` line by line. Boring!
 * Test it for a few days and fix probable bugs.
 * Make a PR :)

**Comment by stefonarch** [comment]
I'm for  2 separate path bars on top, search bar in the bottom is always open on my machine. Looks good IMHO

**Comment by tsujan** [comment]
> search bar in the bottom is always open on my machine

You mean the filter-bar. If you use the latest git pcmanfm-qt+libfm-qt, you won't need a permanent filter-bar; it'll show up once you type inside the view and disappears with `Ctrl+K` or when its text is empty.

Each view frame has its own filter-bar, of course.

**Comment by tsujan** [comment]
Everyone on this page: I need your opinions about this:

I implemented `Tab` for switching between view frames when the focus is inside the split view -- like in Krusader. It's handy but there may be a drawback: if `Tab` is used in this way, the focus couldn't be given to anything else (outside the split view, for example) *only by using keyboard*.

Is that OK? Or should `Ctrl+,` and `Ctrl+.` or something else be used for that job?

**Comment by stefonarch** [comment]
Isn't using `tab` conflicting with` tab+alt`? If I had open pcmanfm with split view and would like to change window?

**Comment by tsujan** [comment]
> Isn't using tab conflicting withtab+alt?

No, only `Tab` is used, without any modifier.

> btw I cannot see this "typing" feature with showing up the filter bar automatically

Uncheck `View` → `Toolbars` → `Permanent filter bar` (Ctrl+B). I guess most users won't discover it soon.

**Comment by tsujan** [comment]
Compensation for the elementary screenshots I attached above: the split view with 2 view modes, styled by Kvantum plus its modified hacking key for pcmanfm-qt:

![kv](https://user-images.githubusercontent.com/981076/44611441-64483200-a816-11e8-9965-ee8a70abd8d9.png)

Almost finished, except for code reading and polishing.

**Comment by tsujan** [comment]
The PR is here: https://github.com/lxqt/pcmanfm-qt/pull/760 . Comprehensive tests would be very appreciated.

Please note that https://github.com/lxqt/libfm-qt/issues/260 is needed for better performance but isn't necessary for tests.

**Comment by tsujan** [comment]
A very small thing I might change by adding a commit to the PR: Currently, the background color of the inactive view is made by making the base color a little darker or lighter but it may be better to use the "alternate base" color instead. I should see which color Dolphin or Krusader uses.
