### ISSUE TITLE
[Feature request] Enhanced copying/moving

### ISSUE THREAD

**Issue by ceever** [lxqt/pcmanfm-qt#1050]
##### Expected Behavior
When copying/moving and a file already exists in the destination, besides "Overwrite", "Ignore", "Rename", and "Cancel" (for one or all files), the following options should be included:
* Update ... i.e. overwrite older file with newer file (if applicable)
* If size differs ... i.e. overwrite existing file if both file sizes differ
* Append ... i.e. append (see "cat") incoming file to existing file (This would even make sense for several incoming files if they are sorted properly.)

These options exist in mc (Midnight Commander) and I reckon they were introduced there for a reason. They are quite useful to me sometimes. And especially the "Append" option would be very useful to Linux newbies that do not want to dive into the terminal right away.

See attached screenshot of the mc interaction.

##### Current Behavior
When copying/moving and a file already exists in the destination, the options "Overwrite", "Ignore", "Rename", and "Cancel" (for one or all files) are provided.

##### Possible Solution
Enhance interaction window and more complex moving/copying process.

##### Steps to Reproduce (for bugs)
1. Open pcmanfm-qt 
2. Select a file
3. Press CTRL+C
4. Press CTRL+V

##### Context
I believe this would make LXQT a more useful desktop environment and more efficient for every days work, especially when it comes to file operations and in particular for newbies to LXQT and Linux.

##### System Information
* Distribution & Version: Ubuntu Focal 19.10
* Kernel: 5.3.0.1003.4
* Qt Version: 5.12.4+dfsg-1
* libfm-qt Version: 0.14.1-9ubuntu3
* libqtxdg Version: 3.3.1-0ubuntu3
* lxqt-build-tools Version: 0.6.0-2ubuntu1
* Package version: 0.14.1-0ubuntu2

![20191224 191527_rectangle_419x240](https://user-images.githubusercontent.com/40247591/71475928-d9e55900-27e2-11ea-897e-5ec30e4152eb.png)

**Comment by tsujan** [comment]
That's why there is an "mc" for users who like such features. I see no reason to clutter the copy menu with unpopular options like these.

@agaida?

**Comment by ceever** [comment]
Well, according to this argument, the whole pcmanfm-qt is unnecessary, because there are already enough file managers out there. Why create another one then, which is not better than Thunar, etc.?

Nevertheless, such a feature could be hidden under an expand arrow.

On a related thought:
Wouldn't a user driven enhancement of lxqt be a more meaningful approach to development. I know someone has to program all that stuff and I am thankful that there are people doing that. However, when just the developer decides on features, then development is bound by these developers imagination.

I often wondered why Windows was sometimes implemented so awfully. Well, I reckon it was because decisions were made by a small number of developers and management people without the feedback of any of the millions of users.

Why not have a regular poll on which direction the desktop environment and its applications should head to? At least this would also be a way for you to point people like me to when they come up with such enhancement ideas. Of course, in the end it is your decision, but I would be much more convinced that an enhancement is indeed beyond scope if it is not just you declaring it "unpopular". ;-)

Cheers

**Comment by tsujan** [comment]
> Well, according to this argument, the whole pcmanfm-qt is unnecessary

Don't use it if you think it isn't needed.

And please avoid long-winded comments -- I read only a few lines of them.
