### ISSUE TITLE
Set desktop background option when right click on image

### ISSUE THREAD

**Issue by glpzzz** [lxqt/pcmanfm-qt#1053]
It's not a personal requirement but two people have complained to me about this. I think it is subjective because depends on pcmanfm-qt handling the desktop (and it's not always the case), and if not, this will be unusable. I just left this here looking for opinions.

##### Expected Behavior
Right click on image and be able to set it as desktop background

##### Current Behavior
You need to right click on desktop in order to do this.

##### Possible Solution
Its already implemented with parameters for the pcmanfm-qt executable

**Comment by tsujan** [comment]
This can be done by making a custom action, using the `--set-wallpaper` option.

Closing because we don't add duplicate functionalities.

**Comment by tsujan** [comment]
For how to make a custom action, see the example in https://github.com/lxqt/pcmanfm-qt/issues/40#issuecomment-567558269 and also https://github.com/lxqt/pcmanfm-qt/issues/550#issuecomment-500636799
