### ISSUE TITLE
Bookmark of samba share shows "/" instead of name

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1057]
Creating a bookmark of a samba share it will be created with just "/" as  name.

##### Expected Behavior

Adding a bookmark of smb://host/share-name should display by default  the share's name (as in ftp:// it saves it as "www.site.xyz"

##### Current Behavior

It just shows a trailing slash

##### Steps to Reproduce (for bugs)

1. In pcman open a samba share or just use type in the address bar smb://foo/boo
2. From the menu > bookmarks click "add to bookmarks"
3. It appears as /

##### System Information

* Distribution & Version:  up-to-date arch, git checkout

**Comment by tsujan** [comment]
Ah, I thought we'd got rid of all SMB problems! Will investigate it.
