### ISSUE TITLE
Cannot open directories with sharp (#) character in name on samba share

### ISSUE THREAD

**Issue by aakumykov** [lxqt/pcmanfm-qt#1060]
PCManFM-qt (v0.14.1) cannot enter inside directory with sharp character in it's name (for example, #qwerty, qwerty#, qwe#rty) on samba share. I test it on two linux distributions (deb- and rpm-based): result the same. Original PCManFM from LXDE is free of this problem.

##### Expected Behavior
Open (enter inside it) directories with sharp character in it's name.

##### Current Behavior
File manager cannot open such dirs. Results:
1) #qwerty - shows busy mouse cursor, appends '#qwerty' to pathbar, nothing opens;
2) qwe#rty - appends 'qwe#rty' to pathbar, shows empty dir and error "No such file or directory";
3) qwerty# - same as previous.

##### Steps to Reproduce (for bugs)
1. Create samba share with #qwerty, qwerty# and qwe#rty directories inside it. (Exact variant: smb://192.168.0.20/share);
2. Go to smb://192.168.0.20 with PCManFM;
3. Open "share" resource and connect to it as guest;
4. Try to open named directories inside with samba share.

##### Context
In Windows world directories with leading sharp character are created to place it at beginning of alphabetically sorted list.

##### System Information
* Distribution & Version: ALT Linux nighly (https://mirror.yandex.ru/altlinux-nightly/flavours/lxde/)
* Kernel: 4.19.95-std-def-alt1
* Qt Version: 5.12.6
* libfm-qt Version: 0.14.1
* libqtxdg Version: 3.3.1
* lxqt-build-tools Version: 
* Package version: 0.14.1

Also bug exists in Debian Live 10.2.0 amd64.

**Comment by tsujan** [comment]
Thanks for reporting the problems you encounter but this isn't reproducible with the latest git libfm-qt+pcmanfm-qt, as the following screenshot shows:

![smb](https://user-images.githubusercontent.com/981076/72708982-1e151080-3b79-11ea-8fe0-55f064e4120e.png)

There have been so many changes after 0.14.1. One of them should have fixed the issue.
