### ISSUE TITLE
temporary desktop file appears on desktop (seems #944 recurred)

### ISSUE THREAD

**Issue by pcmagno** [lxqt/pcmanfm-qt#1063]
##### Expected Behavior
Temporary desktop file should not be displayed on the desktop

##### Current Behavior
Temporary desktop file is displayed on the desktop.

##### Possible Solution
The workaround as mentioned in #944 is to open the file manager. Go to desktop and press F5 (refresh).

##### Steps to Reproduce (for bugs)
1. After booting the system, the said file is on the desktop.

##### Context
#944 seems to have returned

##### System Information
* Distribution & Version: Fedora 31
* Kernel: 5.4.13-201.fc31.x86_64
* Qt Version: 0.14.1
* libfm-qt Version: 0.14.1
* libqtxdg Version: 3.3.1
* lxqt-build-tools Version: not installed
* Package version: libfm-qt-0.14.1-8.fc31.src.rpm

**Comment by tsujan** [comment]
> #944 seems to have returned

It hasn't returned; you don't have the fix. The fix was merged after 0.14.1.
