### ISSUE TITLE
Random blocking on file copy

### ISSUE THREAD

**Issue by alphaonex86** [lxqt/pcmanfm-qt#1068]
##### Expected Behavior
Copy a folder

##### Current Behavior
Randomly block during the copy

##### Steps to Reproduce (for bugs)

1. just copy a folder into PCmanFM-Qt
2. during the copy do heavy IO task to slow down the copy (more problem in this context)

##### Context
I use BTRFS volume, maybe linked

##### System Information
* Distribution & Version: Gentoo
* Kernel: 4.191.20, 5.3.7, 5.4.8
* Qt Version: 5.13.2-r1
* libfm-qt Version: 0.14.1
* libqtxdg Version: 3.3.1
* lxqt-build-tools Version: 0.6.0
* Package version: 0.14.1

**Comment by tsujan** [comment]
Not reproducible.

But I don't have BTRFS (I tried it on VirtualBox with OpenSUSE+KDE and it was extremely slow). We use GLib for file management. Please try Nautilus and tell me if happens with it too!

**Comment by alphaonex86** [comment]
Nautilus, what do you need, a backtrace of which attached process?

**Comment by tsujan** [comment]
I just need to know if it happens with another GLib-based file manager. Nautilus is based on GLib.

backtrace isn't relevant here.

**Comment by alphaonex86** [comment]
All seamn work with Nautilus.

**Comment by tsujan** [comment]
I don't have a clue about your problem. Maybe, you could answer these questions:

 1. What do you mean by "slow down" exactly?
  2. Do you copy a heavy folder? How heavy is it (number of files in it) and how slow is copying?
  3. Does it happen without BTRFS too (could you test that)?

**Comment by alphaonex86** [comment]
1) Where a simple open(), or opendir() readdir() take more than 20s
2) 2000 files into 30 subfolder
3) I don't know

**Comment by tsujan** [comment]
Fortunately, I hadn't removed OpenSUSE from VirtualBox — all of its volumes are btrfs and its boot takes more than 2 minutes.

I upgraded it, installed pcmanfm-qt 0.14.1 on it, and copied a folder with 129 subfolders and a total amount of 1565 files. Copying took about 5 seconds (because it was VirtualBox on HDD) and the folder opened almost immediately.

So, your problem can't be in pcmanfm-qt/libfm-qt.
