### ISSUE TITLE
Request: KDE Edition...

### ISSUE THREAD

**Issue by tenplus1** [lxqt/pcmanfm-qt#1069]
Would it be possible to have a KDE edition of PcManFm-Qt that uses the kio libs instead of gvfs and could possibly be a faster/smaller replacement for Dolphin :)

**Comment by tsujan** [comment]
The core of pcmanfm-qt — or more precisely, libfm-qt — is based on GLib/GIO, which is more feature-rich and, in some areas, more efficient than KIO. There is no plan to change that.

You could use pcmanfm-qt under KDE without problem.
