### ISSUE TITLE
Shortcuts and command-keys don't work

### ISSUE THREAD

**Issue by TrueCat17** [lxqt/pcmanfm-qt#1071]
PCManFM-Qt don't take pressing Alt+[Left/Right] (but Alt+Up and Backspace works fine)
It's special uncomfortably after File-Searching (F3), when need to return back

As well, on enter to dir keys Right, Down and Home selects first item (it's ok),
**BUT** Left, Up and End does it also (need - select last item)
PageDown must select first item on second "page"
PageUp - first item on last "page"
(Now last 2 keys as Home)

* Distribution & Version: Debian 11 (Bullseye, unstable, Sid)
* Kernel: 5.2
* Qt Version: 5.12.5
* libfm-qt Version: libfm-qt6 ver. 0.14.1-12
* libqtxdg Version: Not found (?)
* lxqt-build-tools Version: in repo 0.6.0-2
* Package version: lxqt-core 29, pcmanfm-qt 0.14.1-3+b1 (is it?)

**Comment by agaida** [comment]
i will not argue against - the only question is: How did you install LXQt?

**Comment by tsujan** [comment]
Make sure that another running app -- especially a window manager -- hasn't consumed the shortcuts.

**Comment by TrueCat17** [comment]
> Make sure that another running app -- especially a window manager -- hasn't consumed the shortcuts.

Browsers takes Alt+Left (for example) correctly

**Comment by TrueCat17** [comment]
> i will not argue against - the only question is: How did you install LXQt?

Chose "task-lxqt-desktop" (only this DE) on installing

**Comment by tsujan** [comment]
> Browsers takes Alt+Left (for example) correctly

A browser is an ordinary app that takes a shortcut only when its window is focused. That's why I mentioned WM...

**Comment by TrueCat17** [comment]
> A browser is an ordinary app that takes a shortcut only when its window is focused. That's why I mentioned WM...

But I use shortcuts in pcmanfm-qt only when it's has focus, of cource...
Ok, how I can check that my WM (OpenBox) hasn't consumed shortcuts?

**Comment by tsujan** [comment]
> Ok, how I can check that my WM (OpenBox) hasn't consumed shortcuts?

Every app that runs in the background and supports shortcuts can also  consume them. Each WM has a config file for its shortcuts. For example, if you use Openbox, check the file `~/.config/openbox/lxqt-rc.xml` and make sure that `A-Right` and `A-Left` aren't defined in it.

**Comment by TrueCat17** [comment]
I found it:
```
<context name="Frame">
  <mousebind button="A-Left" action="Press">
    <action name="Focus"/>
    <action name="Raise"/>
  </mousebind>
  <mousebind button="A-Left" action="Click">
    <action name="Unshade"/>
  </mousebind>
  <mousebind button="A-Left" action="Drag">
    <action name="Move"/>
  </mousebind>
  <mousebind button="A-Right" action="Press">
    <action name="Focus"/>
    <action name="Raise"/>
    <action name="Unshade"/>
  </mousebind>
  <mousebind button="A-Right" action="Drag">
    <action name="Resize"/>
  </mousebind>
```
What I should to do now? Delete this?
Also I found "A-Middle" under, what is this? It's weird, seem on mouse buttons

**Comment by tsujan** [comment]
I don't use openbox but, as far as I remember, "Press" means key press.

So, to test it, first backup `~/.config/openbox/lxqt-rc.xml` and then remove the blocks that contain "A-Left" and "A-Right" and also `action="Press"`. You should remove the whole blocks; otherwise, the config file will be considered corrupted. Then log out and log in and see if pcmanfm-qt's shortcuts work.

Please notes that those shortcuts *work* here; so, the problem cannot be in pcmanfm-qt's code.

**Comment by tsujan** [comment]
> Also I found "A-Middle" under, what is this?

"A-Middle" should mean alt + mouse middle click.

**Comment by tsujan** [comment]
Oh, I'm very sorry! `A-Right` may mean Alt + right mouse button. Someone who uses openbox should tell you. Don't change them...

**Comment by TrueCat17** [comment]
If I right understand, it's because tag <mousebind>, then I should A-Left in <keybind>, but I found it only with prefixes (+ Ctrl, Shift...)
Then, config OpenBox correct, right?

Btw, why FileManager can't work with keyboard in usual mode, as browsers?
They has windows too, and WindowManager don't corrupt them

**Comment by tsujan** [comment]
As someone who doesn't use Openbox (I use KWin), I shouldn't have commented on Openbox's shortcut (and I'm sorry about that). You could search the Internet to know their exact meanings.

What I can say with certainty:

  1. Shortcuts of pcmanfm-qt are OK.
  2. If the same shortcuts are used by other apps *that work in the background* (window manager is such an app but browser isn't), they might not work properly in pcmanfm-qt or any app that uses them.
  3. Sometimes, the code is OK but translations ruin shortcuts.

**Comment by TrueCat17** [comment]
>Sometimes, the code is OK but translations ruin shortcuts.
Check, if I remove i10n-package, shortcuts work (but Alt+Up work always...)
I'm russian, if it info help to make fix

What about 2 part of topic?

**Comment by tsujan** [comment]
> What about 2 part of topic?

When nothing is selected and *no item has keyboard focus*, PgUp, PgDn, Home, End, Up, Down, Right and Left select the first item and give it focus (because there should be a start point). If nothing is selected but *an item has focus*, those keys behave as if the focused item is selected.

Some widget styles (like gtk2) may not show which item has focus but most do (Fusion, Breeze, Kvantum...).

**Comment by agaida** [comment]
Well, it works in german too - so maybe it is really translation relateed- @TrueCat17 - just have a look into https://weblate.lxqt.org (and change it if you find something wrong)

**Comment by TrueCat17** [comment]
It behaviour is unexpected and very weird
If I press End, I want to select (and focus) last item, NOT first
Same with other keys
FileManager must be logical and intuitive

**Comment by tsujan** [comment]
> It behaviour is unexpected

The "problem", if any, is that, in pcmanfm-qt's view, item focus can be missing *at first* -- nothing more. Years ago, I saw that but didn't do anything about it because no one complained.

I might open a clean report and "fix" it when I find the time.

**Comment by TrueCat17** [comment]
File: https://github.com/lxqt/pcmanfm-qt/blob/master/pcmanfm/translations/pcmanfm-qt_ru.ts
Alt+Left has translate (line 1016) - don't work
Alt+Up hasn't translate (line 594) - work

Alt+Right hasn't too and work (sorry for false before, it was not easy to check without Alt+Left)

**Comment by TrueCat17** [comment]
>I might open a clean report and "fix" it when I find the time.
Please, I would be very happy
I’ve been suffering for a long time because of this, but only now I reported it

**Comment by agaida** [comment]
@TrueCat17 - now you know the joy of translations :D - TBH, this is not the only fun, it is sad that translators translate the funniest things and don't test it

@tsujan, @palinek, @luis-pereira  - do we have any chance to mark these things as not translatable?

**Comment by TrueCat17** [comment]
I found this translation: https://weblate.lxqt.org/translate/lxqt/pcmanfm-qt/ru/?&offset=189
But I can't find button to delete it (I'm not sure, that all would ok, if I set origin text, and I can't set empty text)

**Comment by agaida** [comment]
Well, i'm far more mighty - maybe i can do it - just let's test it

**Comment by agaida** [comment]
oha - bad application design, just delete the translation string and commit it :smile:

**Comment by agaida** [comment]
@tsujan @TrueCat17 - if you find a good headline for it, please file a bug in lxqt - and mark it as Blocker, we should go through all the translations if my last change helps.

**Comment by TrueCat17** [comment]
What is mean "if you find a good headline for it"?

**Comment by tsujan** [comment]
> @tsujan, @palinek, @luis-pereira - do we have any chance to mark these things as not translatable?

No, because, for example, "Shift" isn't "Shift" in all languages. I think you know these things better than I do (in German). Unfortunately, bad translations can do harm.

> @tsujan @TrueCat17 - if you find a good headline for it, please file a bug in lxqt - and mark it as Blocker, we should go through all the translations if my last change helps.

The headline can be "Translation ruined shortcuts" or something like it.

> Please, I would be very happy. I’ve been suffering for a long time because of this, but only now I reported it

@TrueCat17 I'll look into it soon; will tell you here when I do.

BTW, you don't need to wait a long time before reporting problems ;)

**Comment by agaida** [comment]
@TrueCat17 - for normal text there is a "no-tr" tag if i remember right - ok, i set up weblate, but i cared only about the technical part - how to set up the reverse proxy, how to set up weblate and the database and make it maint, friendly. The results was fine, but until now i didn't dig deeper in the source code part - the other side of the medal was enough for me ;)

**Comment by tsujan** [comment]
@agaida I have a case in FeatherPad, where two shortcuts don't work with the Dutch translation. Sadly, bad translations can interfere with shortcuts, although they may have been done by good translators.

There is a way to make shortcuts immune to bad translations but it isn't worth the amount of the extra codes. I've had no problem to add lots of extra codes to my own apps (not to LXQt) but in this case, I haven't done so because they're really not worth the effort.

**Comment by tsujan** [comment]
@TrueCat17 
The new report is [here](https://github.com/lxqt/pcmanfm-qt/issues/1072) and the fix is [here](https://github.com/lxqt/pcmanfm-qt/pull/1073).

The fix was quite simple but not as trivial as I thought.
