### ISSUE TITLE
Drag and Drop issue

### ISSUE THREAD

**Issue by jfk88** [lxqt/pcmanfm-qt#1074]
Hi,

I still have trouble drag-and-dropping in the panel since I've installed the package one year ago. 

I'm now in Qt 5.14.1-2  with your 0.14.1-1. 

Apparently it's been solved but I should have missed something.

Thank you.

**Comment by tsujan** [comment]
If you take a look at https://github.com/lxqt/pcmanfm-qt/releases/tag/0.14.1, you'll see that 0.14.1 is too old.

If you want to have the latest fixes/features as soon as possible, use the latest git; otherwise, you'll have to wait for the next release.

**Comment by jfk88** [comment]
Thanks for your quick reply.

**Comment by tsujan** [comment]
You'e welcome.

If you use the latest git LXQt (or libfm-qt+pcmanfm-qt), you could also help us find and fix problems faster -- the git is quite stable most of the time -- although your distro determines how easy/hard that might be.
