### ISSUE TITLE
about thumbnails on Archlinux

### ISSUE THREAD

**Issue by ljgdasfhk** [lxqt/pcmanfm-qt#1080]
##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: Archlinux
* Kernel: 5.5.5
* Qt Version: 5.14.1
* libfm-qt Version: 0.14.1
* libqtxdg Version: 3.4.0
* lxqt-build-tools Version: not installed
* Package version: 

How to enable PDF and DJVU files thumbnails ?
I have installed `poppler-glib` and `tumbler` but nothing happened

**Comment by tsujan** [comment]
You need an app that makes thumbnails. For PDF, install `graphicsmagick` and create `~/.local/share/thumbnailers/graphicsmagick-pdf.thumbnailer` as:

```
[Thumbnailer Entry]
Exec=gm convert -quality 100 -thumbnail %s -flatten %i\[0\] %o
MimeType=application/pdf;application/x-pdf;image/pdf;application/x-gzpostscript;application/postscript;
```
And restart pcmanfm-qt.

For DjVu, tell me if you find a good thumbnailer.

BTW, please ask your questions at the forum instead.

**Comment by tsujan** [comment]
For the record, creating DjVu thumbnails is as simple as this (I don't know how I missed it):

Install `djvulibre`, create `~/.local/share/thumbnailers/djvu.thumbnailer` as follows, and restart pcmanfm-qt:

```
[Thumbnailer Entry]
Exec=ddjvu -format=tiff -page=1 -size=%sx%s %i %o
MimeType=image/vnd.djvu+multipage;image/vnd.djvu;
```
