### ISSUE TITLE
sftp, "file monitor cannot be created", dialog popup on every folder

### ISSUE THREAD

**Issue by flower1024** [lxqt/pcmanfm-qt#1085]
##### Current Behavior
whenever i open an sftp location on my arch plasma-shell pcmanfm-qt-0.14.1-1 install a dialog pops up "Vorgang wurde abgebrochen" (english: operation has been cancelled).
if i open pcmanfm-qt through console it prints: file monitor cannot be created: Vorgang wird nicht unterstützt (english: operation is not supported).

this kinda makes sense. i am fine with that changes are not monitored, but the dialog which pops up after any directory switch is very annoying and makes pcmanfm-qt unusable on remote locations.

##### Possible Solution
just dont show that dialog or print a small note on statusbar showing that dynamic refresh is not working for this location

##### Steps to Reproduce (for bugs)
install arch with plasma
install current pcmanfm-qt
open a sftp location and navigate through folders

##### System Information
* Distribution & Version: arch
* Kernel: Linux samson 5.5.7-arch1-1 #1 SMP PREEMPT Sat, 29 Feb 2020 19:06:02 +0000 x86_64 GNU/Linux
* Qt Version: qt5-base-5.14.1-3
* libfm-qt Version: libfm-qt-0.14.1-3
* libqtxdg Version: libqtxdg-3.4.0-3
* lxqt-build-tools Version: lxqt-build-tools-0.6.0-1 (not installed)
* Package version: pcmanfm-qt-0.14.1-1

**Comment by tsujan** [comment]
Thanks but this issue was reported and fixed a long time ago.

Please note that libfm-qt 0.14.1 and pcmanfm-qt 0.14.1 are VERY OLD now -- although, paradoxically,, they're still the latest releases. If you want to have the latest fixes/features, please upgrade to git packages, which are available in AUR.
