### ISSUE TITLE
Add info about Drag+Shift/Ctrl — and a minor Qt bug

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#1086]
Only recently, I found out that Qt's views have a default feature that exists in Nautilus too. Having closed a few reports like https://github.com/lxqt/pcmanfm-qt/issues/993, https://github.com/lxqt/pcmanfm-qt/issues/986 and https://github.com/lxqt/pcmanfm-qt/issues/220, I think many users may not know about it, as I didn't.

If a file is dragged, then:

 1. If `Shift` is pressed and the file is dropped, the file will be moved;
 2. If `Ctrl` (or `Meta`) is pressed and the file is dropped, the file will be copied;
 3. If `Shift+Ctrl` is pressed and the file is dropped, a symlink will be created.

And that happens without asking the user for action because we don't show the prompt menu when a modifier is pressed.

I'll add the info to the new Hidden Shortcuts dialog.

There's a small problem though: If, after a drag, Shift/Ctrl is pressed, the user should move the cursor a little to see that its shape changes and shows the kind of drop action. That's a Qt bug. The cursor's shape is changed by Qt → `qsimpledrag.cpp` only when it starts to move. I couldn't find a workaround for it because, when DND is in progress, the view doesn't receive key-press event and starting a timer during DND isn't a good idea.

**Comment by trmdi** [comment]
> That's a Qt bug. The cursor's shape is changed by Qt → qsimpledrag.cpp only when it starts to move...

Could you help me to report it to Qt devs [here](https://bugreports.qt.io/browse/QTBUG-82934), I'm not very good to describe it.
Thanks. :)

**Comment by tsujan** [comment]
@trmdi 
What I dislike about reporting at Qt bug tracker is that they always want a sample code. In this case, who has time to write a DND code just as a sample?

But you could tell them that the bug is visible in any Qt text editor: Qt Creator, Kate, FeatherPad...: Drag a text to another place inside the editor's view and press `Ctrl`, then you should move the mouse cursor to see a change in its shape.

**Comment by trmdi** [comment]
You could use this sample code: https://bugreports.qt.io/browse/QTBUG-75744

**Comment by tsujan** [comment]
Yes, I'd seen it but it doesn't show the problem you found and I mentioned here. That problem is *visible* in `QPlainTextEdit`.

**Comment by trmdi** [comment]
@tsujan 
I've added the sample code there because they require it. You could help me by adding any extra info to that report.
Thank you ! ;-)

**Comment by tsujan** [comment]
@trmdi 
Right now, I added a comment to https://bugreports.qt.io/browse/QTBUG-82934. I think anyone should understand the problem by reading it.

**Comment by trmdi** [comment]
Just play with `QSimpleDrag`: https://build.opensuse.org/package/view_file/home:trmdi/libqt5-qtbase/test-patch.diff?expand=1 :D

**Comment by tsujan** [comment]
I'm glad that you've found a solution :) Recompiling Qt is beyond my time *for now* but if I were you, I'd test the patch with various apps for a while, make it better if needed, and propose it to Qt (I don't know which term they use for "PR").

**Comment by trmdi** [comment]
> I'm glad that you've found a solution :) Recompiling Qt is beyond my time _for now_ but if I were you, I'd test the patch with various apps for a while, make it better if needed, and propose it to Qt (I don't know which term they use for "PR").

Yeah, I tried compiling it on my system but I gave up because it takes too much time.
Luckily we have openSUSE's OBS.

I could try send the patch, but I want to listen your advice first. Do you have any suggestion about the code style? :D

**Comment by tsujan** [comment]
> Yeah, I tried compiling it on my system but I gave up because it takes too much time

Last year, it took me ~25 min. on RAM (/tmp) and with all CPU cores but I didn't repeat it because I was worried about the laptop's CPUs. I think it'll take more than 1 hour with 3 cores.

> Do you have any suggestion about the code style?

The codes style seems to me like that of `qsimpledrag.cpp`; I think it's good.

@palinek has experience in working with Qt devs on the coding level; I don't.

**Comment by tsujan** [comment]
@trmdi, they started to pay attention to [your report](https://bugreports.qt.io/browse/QTBUG-82934) -- "P3: Somewhat important" :)

**Comment by trmdi** [comment]
Nice. I hope it will be fixed soon. 😊

**Comment by trmdi** [comment]
> @trmdi, they started to pay attention to [your report](https://bugreports.qt.io/browse/QTBUG-82934) -- "P3: Somewhat important" :)

Finally they have sent a patch for it: https://codereview.qt-project.org/c/qt/qtbase/+/298921 :)

**Comment by tsujan** [comment]
Good but now, everything seems to be a little shaky about Qt: https://www.phoronix.com/scan.php?page=news_item&px=Qt-Might-Restrict-New-Releases
