### ISSUE TITLE
Can't set custom location for .thumbnails directory.

### ISSUE THREAD

**Issue by aleksozolins** [lxqt/pcmanfm-qt#1089]
I'd like to be able to move ~/.thumbnails/ to another place to de-clutter my home director... ~/.cache/pcmanfm/thumbnails would be a suggestion.

##### Possible Solution

An environment variable can be used to set the location of the .thumbnail directory.

##### Context

de-clutter my home directory.
##### System Information

* Distribution & Version: pcmanfm-gtk3
* Kernel: 5.5.13 Arch Linux
* Qt Version: 
* libfm-qt Version:
* libqtxdg Version: 
* lxqt-build-tools Version: 
* Package version: 1.3.1

**Comment by tsujan** [comment]
Thumbnails are in `$XDG_CACHE_HOME/thumbnails/`. If you have them in another place, they aren't created/used by `libfm-qt`/LXQt.
