### ISSUE TITLE
detailed list view improvements

### ISSUE THREAD

**Issue by pmattern** [lxqt/pcmanfm-qt#109]
PCManFM's detailed list view lacks some rather important features, imho:

Sorting should be configurable by clicking the columns' headers. This affects both choosing the column that's used to do the sorting and the order in terms of ascending vs. descending.

Some columns are just missing, in practice group names, permissions and targets of symbolic links.

The choice which columns are displayed should be configurable.

**Comment by nesnera** [comment]
Missing sorting by clicking the columns' headers - it is a bug. I think.

**Comment by pmattern** [comment]
Sorting got fixed. Thanks.

But the other problems persist: columns as stated in first post are still missing, a selection of columns to be displayed isn't possible.

So I'm sorry but I really think this should be re-opened.
(If you should prefer to transfer the remaining topics into an issue on their own, let me know.)

**Comment by pmattern** [comment]
Reopening.

**Comment by pmattern** [comment]
Reopening

**Comment by pmattern** [comment]
Sorting is basically working now. But whenever PCManFM-Qt starts over, e. g. new session or reboot, the sorting is now set to "Ascending" whatever was set when quitting before.

Also, the other problems persist: columns stated in first post are still missing, selecting columns to be displayed isn't possible.

Thus reopening.

**Comment by tsujan** [comment]
For a long time, sorting is correct and preserved; group and owner columns are present too.

IMO, a link target column wouldn't have practical value and would just clutter the view, especially when the target can be seen on the status-bar when the link is selected.

There is another [report](https://github.com/lxqt/pcmanfm-qt/issues/787) about customization.
