### ISSUE TITLE
<Tab> should complete folders with a trailing slash ("/") for ease of use

### ISSUE THREAD

**Issue by multiheaded** [lxqt/pcmanfm-qt#1090]
Hi, I really like your work. This is a feature request to enhance ease of use during keyboard control.
After switching to the path input line/bar (either by clicking or by using Ctrl+L), autocompletion for folder/directory names works nicely when hitting <Tab>.

Unfortunately, it is not possible to conveniently continue typing after the <Tabbing>, because the trailing slash needs to be appended manually. This behavior is different to how other tools like terminals behave.
I see no use-case where appending a trailing slash wouldn't be beneficial. In any case, by providing this feature as configurable option should satisfy everybody.

**Comment by tsujan** [comment]
Implemented in Jul, 2019. You might need to upgrade your installation to the latest git LXQt.

**Comment by multiheaded** [comment]
I looked up the commit and the changes haven't been included in any release so far (I'm on 0.14.1). Will now built on master and wait for the next release, thanks for the hint anyways.

**Comment by tsujan** [comment]
LXQt releases become old quickly. To have latest features/fixes, you need a distro that provides you with a reliable installation of the latest git LXQt — like Arch/Manjaro, Debian sid, OpenSUSE Tumbleweed,…
