### ISSUE TITLE
<Esc> or timeout should abort in-directory quick search

### ISSUE THREAD

**Issue by multiheaded** [lxqt/pcmanfm-qt#1091]
Hi again, this is another feature request.
Currently, when using the in-directory "quick search" feature (typing the first characters of a file or directory) to quickly find something you know the name of, but don't want to use the mouse to search for, opens a new input containing the typed characters at the bottom of the directory view.
This input however does not close unless I remove all the characters using the backspace key.
Is see two behavioral enhancements:
Remove all characters and close the input field
1. when hitting <Esc> key
2. after a definable timeout.

Both could either be implemented by introducing configurable application settings (enable/disable (boolean) and integer [in seconds]), or by hard-coding sane defaults (e.g. true and 1 second).

**Comment by tsujan** [comment]
Implemented a long time ago. Upgrade your LXQt installation to the latest git.
