### ISSUE TITLE
Display bug related to file association 

### ISSUE THREAD

**Issue by jfk88** [lxqt/pcmanfm-qt#1093]
**LxQt 0.14.1 with pcmanfm-qt-git 0.14.1.132.gb78376d-1**

`$ xdg-mime query filetype ~/.xinitrc` gives me `plain/text` but I got another file type displayed in pcmanfm-qt-git:

![Capture d'écran Deepin_zone de sélection _20200412211932](https://user-images.githubusercontent.com/25780374/79077674-8c461b00-7d03-11ea-934d-61086480f67c.png)

Apparently `.xi` is linked to Amiga but either pcman or the file association manager interprets (hidden) xinit as being itself a .xi file.

**Comment by tsujan** [comment]
Not reproducible.

pcmanfm-qt gets the mimetype from libfm-qt, which gets it from GLib. Something should be wrong about mimetype handling in your system.

I remember that, years ago, such problems appeared and disappeared with updates.

**Comment by tsujan** [comment]
BTW, `.xinitrc` is a shell script (`application/x-shellscript`), not just a plain text document.

**Comment by jfk88** [comment]
OK thanks for the reply.

> BTW, `.xinitrc` is a shell script (`application/x-shellscript`), not just a plain text document.

I had this discussion with a moderator on Arch forum and apparently plain/text is correct. But I'm not expert enough in X to continue the debate.

**Comment by tsujan** [comment]
> I had this discussion with a moderator on Arch forum and apparently plain/text is correct

Here:
```sh
$ xdg-mime query filetype ~/.xinitrc
application/x-shellscript
```

Have you installed `perl-file-mimeinfo`?

**Comment by jfk88** [comment]
Interesting so without `perl-file-mimeinfo` I get 

```
$ xdg-mime query filetype ~/.xinitrc
text/plain
```

But after installing `perl-file-mimeinfo` 

```
$ xdg-mime query filetype ~/.xinitrc
audio/x-mod
```

**Comment by tsujan** [comment]
LOL! I have no idea why you get that.

`perl-file-mimeinfo` is an important package and, IMHO, it should have been among pcmanfm-qt's optional dependencies. https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/pcmanfm-qt:
```sh
optdepends=(
	"gvfs: for trash support, mounting with udisks and remote filesystems"
	"gvfs-mtp: MTP support (Media Transfer Protocol)"
	"xarchiver: archive management"
	"qt5-translations: allow keyboard shortcuts to function in some languages (e.g. German)"
)
```
I also think `xarchiver` can be removed (it should be replaced by `lxqt-archiver` later, when the latter is released).

**Comment by jfk88** [comment]
Found the root of the issue here: https://github.com/mbeijen/File-MimeInfo/issues/39

It was actually due to the content of my xinitrc:

```
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

exec startlxqt
```
Very strange bug

**Comment by tsujan** [comment]
> Found the root of the issue here

Yes, I made a file with those contents and it was seen as `audio/x-mod`.

You could add `#!/bin/sh` as the first line.
