### ISSUE TITLE
Can't submit password in address bar

### ISSUE THREAD

**Issue by robschi** [lxqt/pcmanfm-qt#1095]
If I try to open a smb:// or ssh:// URL with for example "smb://<USER>:<PASS>@<URL>" the password is ignored and I have to type in the password in the pop up window with the title "Mount" again.

I think the "Password:" box in the window "Mount" should be in this case at least prefilled.

##### System Information
* Distribution & Version: 
Debian testing
* Kernel: 
5.5.13-2
* Qt Version: 
* libfm-qt Version:
0.14.1-12
* libqtxdg Version: 
-
* lxqt-build-tools Version: 
-
* Package version: 
0.14.1

**Comment by tsujan** [comment]
Passwords should be typed in the password dialog, which supports saving with gnome-keyring (only in the latest git version of libfm-qt and pcmanfm-qt).

**Comment by robschi** [comment]
Yes but sometimes it's pretty convenient  if you can someone just send a link which he can open without the need to fill out an extra  box, and this should be a legit syntax.

But it's of course not an essential feature.
