### ISSUE TITLE
Gnome-keyring integration with ftp is buggy

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1100]
1) The passwd is not really stored when checking "for session" or "for always"
2) gnome-keyring-daemon doesn't get terminated on logout.

##### Expected Behavior

ftp passwd is stored and after restarting the session gnome-keyring should ask again.
##### Current Behavior

Apparently the passwd is stored for the session and even after restarting it, but rebooting or killing gnome-keyring-daemon the pcmanfm passwd dialog pops up but is not compiled and empty.
##### Steps to Reproduce (for bugs)

1. Install gnome-keyring, open an ftp location in pcmanfm-qt, give the gnome-keyring passwd, choose "remember always" in pcmanfm's passwd dialog.
2. Unmount it and remount it, it will work without passwd prompt.
3. Restart session, still the same without passwd.
4. Kill gnome-keyring-daemon or reboot, no passwd is saved.

##### System Information

* Distribution & Version: up to date arch and git checkout.

**Comment by tsujan** [comment]
> The passwd is not really stored when checking "for session" or "for always"

It does here -- used it multiple times, before and after reboot. @McThump also confirmed that (https://github.com/lxqt/libfm-qt/pull/535#issuecomment-612288935).

> gnome-keyring-daemon doesn't get terminated on logout.

That's not LXQt's job but systemd's. Check whether you have `KillUserProcesses=yes` in `/etc/systemd/logind.conf`.

**Comment by tsujan** [comment]
> Kill gnome-keyring-daemon or reboot, no passwd is saved.

Killing a process may not allow it to save its configuration. You should terminate it.

**Comment by tsujan** [comment]
More info (in case similar reports appear):

What is considered by GLib/gnome-keyring to be a "session" is their own business (see https://developer.gnome.org/gio/stable/GMountOperation.html#GPasswordSave). libfm-qt just asks GLib to save passwords. How GLib does it is out of libfm-qt's control.

Also, the display manager may have a role. I have SDDM and see this process:
```
gnome-keyring-daemon --start --foreground --components=secrets
```

In short, there can be no bug at all in our simple implementation:
```
Drear Glib,

Please save my passwords permanently or for this session,
whichever I request for!

Sincerely Yours,
libfm-qt
```

**Comment by stefonarch** [comment]
logind.conf was missing this, but actually the behavior didn't change at all, I can logout (and  now gnome-keyring-daemon is not running anymore, checked in tty), after login I find the ftp  still under  "devices" in pcmanfm-qt and can access it without  any passwd dialog and no gnome-keyring-daemon is running.

After reboot  no passwd is saved. No idea where to look.

**Comment by tsujan** [comment]
> after login I find the ftp still under "devices" in pcmanfm-qt and can access it without any passwd dialog

I'm not sure but I *may* have seen a similar thing with Skype: after logging out and in, Skype might haven't needed password. If so, it's about how gnome-keyring works. But, in both cases (Skype and pcmanfm-qt), the permanently saved passwords exist after reboot. Moreover, I can see them with `seahorse`: for pcmanfm-qt+SFTP, it's under Passwords → login → Network password.

SMB isn't different either.

> No idea where to look.

This might help, although I didn't need it: https://wiki.archlinux.org/index.php/GNOME/Keyring

Or maybe you need to install a package?

**Comment by tsujan** [comment]
Oh, I found my old note from years ago, when I installed gnome-keyring for Skype; I hope it helps:
```
Installed seahorse, logged out and in
(for gnome-keyring-daemon to start),
added a new key to seahorse with the name "login",
and signed into Skype. Apparently, the key name
should be "login", otherwise it wouldn't work.
```

**Comment by McThump** [comment]
FTP clients and servers cache passwords to improve performance--typically for about 15 minutes for one's I have used.

**Comment by tsujan** [comment]
@McThump Thanks for the info.

I think @stefonarch's main problem may be the lack of `login` key.

**Comment by stefonarch** [comment]
Hm first time I didn't see gnome-keyring-daemon process in tty after logout, now it's there again.
In seahorse I see the passwd.
Terminating the process in qps and restarting pcmanfm and access ftp keyring opens, and after that I get the passwd prompt empty.
Restarting pcmanfm-qt from session settings and retrying to access ftp it opens fine.

Have to test reboot but my guess is that it will be similar. First attempt fails.

**Comment by tsujan** [comment]
> Hm first time I didn't see gnome-keyring-daemon process in tty after logout, now it's there again.

@McThump's comment is a possible explanation.

> will be similar. First attempt fails.

It shouldn't.

**Comment by stefonarch** [comment]
> It shouldn't.

Retested. Compiled v0.15. 
Reboot, keyring opens fine, pcmanfm-qt shows again the empty dialog, closing window and reopening and re-access ftp (which is bookmarked) works. So no need to restart the desktop.
But now once unmounted it won't access it again from bookmarks or adress  bar, needs desktop restart or pressing F5, which is another bug (here...).

**Comment by tsujan** [comment]
> But now once unmounted it won't access it again from bookmarks or adress bar, needs desktop restart or pressing F5, which is another bug (here...).

I didn't understand this. Please open another issue and tell me how to reproduce it.

**Comment by stefonarch** [comment]
https://github.com/lxqt/pcmanfm-qt/issues/1103

**Comment by stefonarch** [comment]
Just FYI: same behaviuor on a fresh clean user.

**Comment by tsujan** [comment]
> Just FYI: same behavior on a fresh clean user.

This one is really related to gnome-keyring and how it works/should be set up.

**Comment by stefonarch** [comment]
Never used it on this user, I saw that it uses the user passwd. 
I will  try with "include" it in /etc/pam.d/sddm, now it's
`-session                optional        pam_gnome_keyring.so auto_start
`

**Comment by tsujan** [comment]
> now it's `-session optional pam_gnome_keyring.so auto_start`

Mine is so too but I never touched it (Manjaro's optimization?):
```
#%PAM-1.0

auth		include		system-login
-auth		optional	pam_gnome_keyring.so
-auth   optional  pam_kwallet5.so

account		include		system-login

password	include		system-login
-password	optional	pam_gnome_keyring.so use_authtok

session		optional	pam_keyinit.so force revoke
session		include		system-login
-session		optional	pam_gnome_keyring.so auto_start
-session  optional  pam_kwallet5.so auto_start
```

**Comment by stefonarch** [comment]
Same here. I changed
`-password	optional	pam_gnome_keyring.so use_authtok
`

to "include", only change is that I don't have to give the gnome-keyring passwd (which is different from login passwd), but at first attempt it still opens pcmanfm dialog, F5 and then it connects well.
