### ISSUE TITLE
Unable to find Audio/Video Tab in Properties

### ISSUE THREAD

**Issue by Adityashaw** [lxqt/pcmanfm-qt#1104]
When I right-click on any audio/video file and click `Properties`, I expect to see a **Audio/Video** Tab.
##### Expected Behavior
It should show 

- Duration
- Video Bit-rate
- Audio Bit-rate
- Container
- Codec
- Frame Rate

##### Current Behavior
There is no such tab when opening `Properties`. 

##### Possible Solution
This is exactly what I want to know. If it cannot be done in the app itself. Manually doing via some script or so will also work. I would like to know -- _how_.

##### Context
I have to check the duration and other info. I recently shifted from Debian to Arch. In Debian, it used to work by default. The FM was probably `nautilus`.
 
##### System Information

* Distribution & Version: 0.14.1-1
* Kernel: `Linux archlinux 5.6.6-arch1-1 #1 SMP PREEMPT Tue, 21 Apr 2020 10:35:16 +0000 x86_64 GNU/Linux`

* Qt Version:  0.14.1-1
* libfm-qt Version: 0.14.1-4
* libqtxdg Version: 3.4.0-4
* lxqt-build-tools Version: 0.6.0-1
* Package version: _what's that?_

**Comment by tsujan** [comment]
> It should show...

It shouldn't. This isn't a multimedia app.

Use custom actions + `mediainfo` (make a script with `mediainfo` and use it with a custom action of your choice).

**Comment by tsujan** [comment]
BTW, your installation is outdated but it isn't related to this.

**Comment by Adityashaw** [comment]
> Use custom actions + `mediainfo` (make a script with `mediainfo` and use it with a custom action of your choice).

Thanks a lot for the suggestion!
Where should this custom action file ( `.desktop`) reside? `/usr/share/file-manager/actions`, `~/.local/share/file-manager/actions` or some other directory?

**Comment by tsujan** [comment]
`~/.local/share/file-manager/actions` is the place.

Unfortunately, we haven't had time to make a complete documentation about it and `lxqt.org` is down but we might make and add it somewhere on GitHub. Until then, you could download and read the attachment to this comment: https://github.com/lxqt/pcmanfm-qt/issues/550#issuecomment-500636799
