### ISSUE TITLE
Un-minimize with single window mode

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1109]
When pcmanfm-qt window is minimized it does not get focus when clicking a folder on the desktop,   nothing visible happens.
Window open in background gets activated but the tab is opened in background.
Tested with kwin and openbox.

##### Expected Behavior

It should activate the window always. with the new tab in focus.
##### Current Behavior

it opens the tab but in background and does not raise the window.
 

##### Steps to Reproduce (for bugs)

1. Activate single mode in Preferences
2. Test as above
 
##### System Information

* Distribution & Version: arch and git, kwin or openbox

**Comment by tsujan** [comment]
Yes, I didn't want the single-window mode to be too intrusive. After all, if a window is minimized, it has been minimized by the user.

Adding a separate option for this will clutter the Preferences dialog. So, I need to know whether the requested behavior is desirable to many or, conversely, many users will find it annoying.

**Comment by tsujan** [comment]
FeatherPad follows the middle way: open a window if the current window is minimized (don't un-minimize a window). Maybe, that's the best way for pcmanfm-qt's single-window mode too.

**Comment by tsujan** [comment]
BTW, I changed the title because:

 1. When a tab is opened in a NON-minimized window, the window *is* activated. The rest depends on WM's "focus stealing prevention".
 2. The active tab shouldn't change unless, in general, an option is added for it (like in browsers). That isn't related to the single-window mode.

**Comment by stefonarch** [comment]
Hm, I expect the same behavior as with my browser:   if it's minimized or not or on the same desktop or not - when  I click some link somewhere it opens me the window with the tab of the link.

Maybe an option then as in browser?

**Comment by tsujan** [comment]
I explained it in https://github.com/lxqt/pcmanfm-qt/issues/1109#issuecomment-622310101

Browsers have the following option; we don't and it isn't related to single-window mode (the subject of this report):

![browser](https://user-images.githubusercontent.com/981076/80829723-e9473980-8bfc-11ea-997b-bd5f183c1dbe.png)

**Comment by tsujan** [comment]
After https://github.com/lxqt/pcmanfm-qt/pull/1166 is merged, unminimizing will be logical — without an extra option and when switching to the new tab is enabled by the user because, in that case, the user doesn't want the new tab to be in the background.

Self-assigning...
