### ISSUE TITLE
Too big pop-up on mouse over with redundant information in files list

### ISSUE THREAD

**Issue by r3n3647** [lxqt/pcmanfm-qt#1111]
Since pcmanfm-qt ver. 0.15.0 a really big yellow pop-up appears on mouse over a file or directory showing all information about the particular entry.
With viewing options set to 'details' this information is redundant and annoying as all the information in the pop-up is already visible in the headers of the list.
This pop-up makes it complicated to mark several entries with the mouse as it overlays the following entries in the files list.
I searched and did not find any option in settings to disable or configure this new feature.

##### Expected Behavior
The additional information pop-up should not appear when viewing options for the file list is set to details as it is redundant.

##### Possible Solution
There should be an option to disable or configure these pop-ups.

##### System Information
* Distribution & Version: ArchLinux 
* Kernel: 5.6.8
* Qt Version: 5.14.2-1
* libfm-qt Version: 0.15.0-1
* libqtxdg Version: 0.15.0-1

**Comment by tsujan** [comment]
Fortunately, item tooltips can be disabled in pcmafm-qt's code; otherwise, ABI and SONAME bump would be needed for libfm-qt.

I'll add an option for disabling item tooltips. The detailed list mode isn't very different from other modes because columns can be made hidden by right clicking.
