### ISSUE TITLE
Any chance to bring back OpenBox context menu or edit LXQT context menu on desktop?

### ISSUE THREAD

**Issue by aginiewicz** [lxqt/pcmanfm-qt#1112]
After #931 I can no longer use my open-box context menu. I'm long time OpenBox user and this change means loosing functionality. I always remove icons from my desktops and put useful applications into context menu, which for me means faster navigation than looking where currently is icon "X".

It would be cool if there was any way to show my OpenBox menu (at least using middle click) or edit context menu on desktop. For me, editing context menu on desktop is important part of workflow I'm used to for ages.

**Comment by tsujan** [comment]
Dead codes won't be restored. See https://github.com/lxqt/pcmanfm-qt/pull/937

**Comment by aginiewicz** [comment]
Then how about second part – adding ability to edit your own context menu on desktop? Not possible as well?

**Comment by tsujan** [comment]
No.

**Comment by ito32bit** [comment]
Screenshot:  
![openbox_right_click_Mark_screen-2020-05-17_19-39-38](https://user-images.githubusercontent.com/52656419/82271427-b3eb6b80-99b2-11ea-9c21-8fc91fdc3a3a.png)

I use Openbox.
If I use WM menu, I stop "Desktop" module.

> It would be cool if there was any way to show my OpenBox menu (at least using middle click) or edit context menu on desktop.

@aginiewicz  you can uncheck/stop "Desktop" module.

**Comment by aginiewicz** [comment]
This is exactly what I needed! Turned off Desktop module and enabled nitrogen to setup the wallpaper. Thank you! My desktop is again tuned to my needs! :)
