### ISSUE TITLE
Wrong popup menu position

### ISSUE THREAD

**Issue by MaxKh** [lxqt/pcmanfm-qt#1118]
Right-click popup menu appears in a wrong position when using i3 window manager.

Works fine with xfce4. Menus in lxqt-archiver and other qt applications work fine with i3

##### Expected Behavior

Popup menu appears near the mouse cursor.

##### Current Behavior

There are unexpected horizontal and vertical offsets when clicking an item in the bottom or right part of the window.

##### Steps to Reproduce (for bugs)

![menu](https://user-images.githubusercontent.com/4003147/81804911-a0f41980-9522-11ea-8c3c-bd40017550d3.gif)

##### System Information

* Distribution & Version: Archlinux inside VirtualBox in Win10
* Kernel: 5.6.11-arch1-1
* Qt Version: 5.14.2-2
* libfm-qt Version: 0.15.0-1
* libqtxdg Version: 
* lxqt-build-tools Version: 
* Package version: 0.15.0-2

**Comment by tsujan** [comment]
I'd recommend you report such problems to i3 -- its developers might appreciate bug reports about their window manager.

**Comment by MaxKh** [comment]
The problem introduced with 0.15 version and does not exists in 0.14.
Also I have no problems with any other app.

**Comment by MaxKh** [comment]
Ok - some additional findings:
The problem appears if pcmanfm-qt was started in daemon mode and after that the screen resizing was performed. In such case the menu is placed at the wrong positions. Looks like the deamon instance caches screen resolution and does not handle resize events.

**Comment by MaxKh** [comment]
@tsujan It looks like the problem of pcmanfm-qt not i3wm

**Comment by tsujan** [comment]
@MaxKh If there was a chance of that, I'd reopen the issue -- because I appreciate reports.

In this case, you're wasting your time by attributing the problem to pcmanfm-qt.
