### ISSUE TITLE
Why something is accessing network-drives right after boot?

### ISSUE THREAD

**Issue by Triu999** [lxqt/pcmanfm-qt#1119]
I think this is not really a bug but perhaps someone can give me 
some technical hints about that behaviour.

I mounted my network drives earlier with autofs and pcmanfm (on Lubuntu 18.04 LTS), 
everything worked fine.
To stop it from mounting the shares right after boot, i worked with subfolders
`/media/SHARE/SHARE`
(/media/SHARE would have mounted it on boot)

Since Lubuntu 19.04 when i used the pcmanfm-qt the first time, 
i see that the shares are mounted right after boot.
pcmanfm-qt seems to access these folders in some way right after boot.

Also the setting in pcmanfm-qt under (sorry i have not the exact english words for) 
"automatic mount" 
"automatic mount discs on program start"
seem not to change anything.

Another thing i don't understand, 
i can fire up this PC 20 times a day, everytime it is mounting the shares,
but only once a day the discs are spinning up.
Does pcmanfm-qt remember folder content for 24 hours (as long as i don't go deeper in structure)?

I would expect that these mountpoints will not be mounted after boot 
nor when i open pcmanfm-qt.
They should only be mounted when i access these folders.

I hope someone can push me into the right direction.

**Comment by tsujan** [comment]
Please ask these questions in Ubuntu forums. LXQt isn't an Ubuntu project.

BTW, Ubuntu's LXQt is outdated.
