### ISSUE TITLE
pcmanfm-qt becomes unresponsive on deleted wallpaper

### ISSUE THREAD

**Issue by guiverc** [lxqt/pcmanfm-qt#1120]
If the wallpaper image is deleted, on subsequent session(s) or if a change is made to Wallpaper display mode pcmanfm-qt seems to loop at near 100% of cpu and is no longer usable.

##### Expected Behavior
I would expect operating would continue as normal, the background can be black (fair enough given user has deleted the image), but pcmanfm-qt shouldn't loop wasting cpu cycles & fail to respond.

##### Current Behavior
This was noticed by a user request at 
https://askubuntu.com/questions/1238736/the-pcmanfm-qt-is-dead-on-my-lubuntu-20-04
and was then raised as a bug at
https://bugs.launchpad.net/ubuntu/+source/lubuntu-default-settings/+bug/1878336

I confirmed the issue on Lubuntu 20.10, then using Debian Testing which I've documented on the same bug report. On Debian using pcmanfm-qt package 0.14.2~166-g74a6f4d-1 I was at first unable to re-produce, I switched to 0.14.1-3+b1 and could re-produce if I logged out and started a new session (I likely didn't test that with agaida's package).

##### Steps to Reproduce (for bugs)
 1. I right-click on desktop and choose desktop properties to change the background image
 2. choose the background image and close all opened windows
 3. permanently delete the set image from my PC
 4. re-open the desktop properties to change the Wallpaper mode
 5. suddenly the desktop properties crashed and a black tiny window alert me

Those steps the original reporter listed. On Debian I didn't notice the issue following OPs step 5, needing to logout, login again before effect was noticeable. On Ubuntu 20.10 the response is close to OPs, except I found absolutely no evidence of a program crash, just 100% utilization of a thread and pcmanfm-qt no longer responding to user requests.

(I just turned on debian box again & got on login a Crash Report "Desktop crashed too many times. It's autostart has been disabled until next login" which may have been Crash OP meant by crash)

##### System Information

* Distribution & Version: Lubuntu 20.10 & Debian Testing
* Kernel: 5.4.0-29-generic & 5.6.0-1-amd64
* Qt Version: 5.12.8 & 5.12.5
* libfm-qt Version: 
* libqtxdg Version: 
* lxqt-build-tools Version: 0.6.0-2ubuntu1 & 0.6.0-2
* Package version: 0.14.1-0ubuntu3 & 0.14.1-3+b1

**Comment by tsujan** [comment]
Not reproducible. There's no crash or hang or hight CPU usage; just the background color is shown.

Both Debian and Ubuntu has outdated versions of LXQt. Debian may have an excuse: its LXQt maintainer disappeared.

**Comment by tsujan** [comment]
The irony is that if you had the latest version and used a new option for multi-screen wallpapers, you might see a crash. I'll fix that today -- 0.15.1 will be released in a few days -- but it can't be related to your report.

**Comment by guiverc** [comment]
I get the same effect in Fedora 32 workstation using LXQt desktop.

Steps
1. cp -pv wallpapers/[wallpaper.jpg] ~/wall_rm.jpg
2. make ~/wall_rm.jpg the default wallpaper
3. in terminal delete ~/wall_rm.jpg
4. change desktop preference "Wallpaper mode" to something else
5. '/usr/bin/pcmanfm-qt --desktop --profile=lxqt' is now 100% CPU, dragging the window around the screen now leaves trails (as it did in Lubuntu 20.10, but not Debian Testing)

This box was clean installed today; updated & LXQt desktop added.
liblxqt 0.14.1
Qt 5.13.2
kernel 5.6.6-300.fc32.x86_64

**Comment by tsujan** [comment]
liblxqt 0.14.1 belongs to LXQt 0.14.1, which is outdated. We don't support old versions of LXQt.

When you upgrade to libfm-qt/pcmanfm-qt 0.15.1, leave a comment here if the problem persists (although I can't reproduce it with a patch that will be in 0.15.1).
