### ISSUE TITLE
drag-and-drop crashes pcmanfm-qt

### ISSUE THREAD

**Issue by Javeree** [lxqt/pcmanfm-qt#1123]
When I drag a file from a mounted drive to a different directory or to the desktop, pcmanfm closes when I drop the file. There is no error message.

##### Expected Behavior
Drag and drop of files between directories should work. 

##### Current Behavior
Dragging a file pcmanfm-qt when the file is dropped, without warning.
Cut/Copy and paste of a file using the right-click menus allows moving/copying of the files

##### Possible Indication about error
I think it is related, but running openshot-qt, I get a stack trace originating from libfm-qt.so when I drag and drop a file within openshot. When I run openshot-qt in mate instead of lxqt, drag and drop in openshot-qt works. See the stack trace at the end of the report

##### Steps to Reproduce (for bugs)
1. Start lxqt
2. Start pcmanfm-qt (from a command line window so that I can check console output)
3. select any file from 'Desktop', and drag it to 'Documents'
4. Release the mouse button
5. => pcmanfm-qt closes. there is no output on the console.

##### Context
This is a problem since drag and drop is a thing that is expected on a filemanager
gentoo works with ebuilds, so this is compiled locally

##### System Information
* Distribution & Version: Gentoo
* Kernel: 5.5.8
* gcc-config -l: x86_64-pc-linux-gnu-9.2.0
* compiled with cpu flags "aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3"
* Qt Version: 5.14.1
* libfm-qt Version: 0.14.1
* libqtxdg Version: 3.4.0
* lxqt-build-tools Version: 0.6.0
* Package version: 

STACK TRACE WITH OPENSHOT
===========================
---- Unhandled Exception: Stack Trace ----
  /usr/lib64/libfm-qt.so         (                                           + 0x111528)  [0x7f0884dc5528]
  /usr/lib64/libQt5Core.so.5     ( QAbstractEventDispatcher::filterNativeEvent(QByteArray const&, void*, long*)  + 0x64  )  [0x7f08a573fec4]
  /usr/lib64/libQt5XcbQpa.so.5   ( QXcbConnection::handleXcbEvent(xcb_generic_event_t*)  + 0x61  )  [0x7f0896c9d061]
  /usr/lib64/libQt5XcbQpa.so.5   ( QXcbConnection::processXcbEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x76  )  [0x7f0896c9ddb6]
  /usr/lib64/libQt5XcbQpa.so.5   (                                           + 0x67f73)  [0x7f0896cc5f73]
  /usr/lib64/libglib-2.0.so.0    ( g_main_context_dispatch                   + 0x267 )  [0x7f08a4c331f7]
  /usr/lib64/libglib-2.0.so.0    (                                           + 0x50480)  [0x7f08a4c33480]
  /usr/lib64/libglib-2.0.so.0    ( g_main_context_iteration                  + 0x2f  )  [0x7f08a4c3350f]
  /usr/lib64/libQt5Core.so.5     ( QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x6d  )  [0x7f08a5796a4d]
  /usr/lib64/libQt5Core.so.5     ( QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x12b )  [0x7f08a574156b]
  /usr/lib64/libQt5Gui.so.5      ( QBasicDrag::drag(QDrag*)                  + 0x43  )  [0x7f08a18e0ea3]
  /usr/lib64/libQt5Gui.so.5      ( QDragManager::drag(QDrag*)                + 0x11b )  [0x7f08a18de69b]
  /usr/lib64/libQt5Gui.so.5      ( QDrag::exec(QFlags<Qt::DropAction>, Qt::DropAction)  + 0x73  )  [0x7f08a18de9d3]
  /usr/lib/python3.7/site-packages/PyQt5/QtGui.so (                                           + 0xecbf9)  [0x7f08a1332bf9]
  /usr/lib64/libpython3.7m.so.1.0 ( _PyMethodDef_RawFastCallKeywords          + 0x2db )  [0x7f08a71b668b]
  /usr/lib64/libpython3.7m.so.1.0 ( _PyCFunction_FastCallKeywords             + 0x28  )  [0x7f08a71b6738]
  /usr/lib64/libpython3.7m.so.1.0 (                                           + 0x6897e)  [0x7f08a719197e]
  /usr/lib64/libpython3.7m.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x5ad0)  [0x7f08a7197530]
  /usr/lib64/libpython3.7m.so.1.0 (                                           + 0x67549)  [0x7f08a7190549]
  /usr/lib64/libpython3.7m.so.1.0 ( _PyFunction_FastCallDict                  + 0x2e8 )  [0x7f08a71b60d8]
  /usr/lib64/libpython3.7m.so.1.0 ( _PyObject_Call_Prepend                    + 0xed  )  [0x7f08a71b725d]
  /usr/lib64/libpython3.7m.so.1.0 ( PyObject_Call                             + 0x64  )  [0x7f08a71b8394]
  /usr/lib/python3.7/site-packages/PyQt5/sip.so (                                           + 0xb8ec)  [0x7f08a5a428ec]
  /usr/lib/python3.7/site-packages/PyQt5/sip.so (                                           + 0xb9d7)  [0x7f08a5a429d7]
  /usr/lib/python3.7/site-packages/PyQt5/QtWidgets.so (                                           + 0x3bc94b)  [0x7f08a277994b]
  /usr/lib/python3.7/site-packages/PyQt5/QtWidgets.so (                                           + 0x28cc8f)  [0x7f08a2649c8f]
  /usr/lib64/libQt5Widgets.so.5  ( QAbstractItemView::mouseMoveEvent(QMouseEvent*)  + 0x529 )  [0x7f08a20feed9]
  /usr/lib64/libQt5Widgets.so.5  ( QListView::mouseMoveEvent(QMouseEvent*)   + 0x57  )  [0x7f08a213bf47]
  /usr/lib/python3.7/site-packages/PyQt5/QtWidgets.so (                                           + 0x288863)  [0x7f08a2645863]
  /usr/lib64/libQt5Widgets.so.5  ( QWidget::event(QEvent*)                   + 0x278 )  [0x7f08a1ed13d8]
  /usr/lib64/libQt5Widgets.so.5  ( QFrame::event(QEvent*)                    + 0x1e  )  [0x7f08a1f7eb3e]
  /usr/lib64/libQt5Widgets.so.5  ( QAbstractItemView::viewportEvent(QEvent*)  + 0x6e  )  [0x7f08a20ff6fe]
  /usr/lib/python3.7/site-packages/PyQt5/QtWidgets.so (                                           + 0x286ba3)  [0x7f08a2643ba3]
  /usr/lib64/libQt5Core.so.5     ( QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*)  + 0x9e  )  [0x7f08a574252e]
  /usr/lib64/libQt5Widgets.so.5  ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x6e  )  [0x7f08a1e8ecbe]
  /usr/lib64/libQt5Widgets.so.5  ( QApplication::notify(QObject*, QEvent*)   + 0x57f )  [0x7f08a1e9805f]
  /usr/lib/python3.7/site-packages/PyQt5/QtWidgets.so (                                           + 0x1678ee)  [0x7f08a25248ee]
  /usr/lib64/libQt5Core.so.5     ( QCoreApplication::notifyInternal2(QObject*, QEvent*)  + 0x7f  )  [0x7f08a57426df]
  /usr/lib64/libQt5Widgets.so.5  ( QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool)  + 0x1c4 )  [0x7f08a1e970e4]
  /usr/lib64/libQt5Widgets.so.5  (                                           + 0x1c12ad)  [0x7f08a1eec2ad]
  /usr/lib64/libQt5Widgets.so.5  (                                           + 0x1c4184)  [0x7f08a1eef184]
  /usr/lib64/libQt5Widgets.so.5  ( QApplicationPrivate::notify_helper(QObject*, QEvent*)  + 0x7f  )  [0x7f08a1e8eccf]
  /usr/lib64/libQt5Widgets.so.5  ( QApplication::notify(QObject*, QEvent*)   + 0x330 )  [0x7f08a1e97e10]
  /usr/lib/python3.7/site-packages/PyQt5/QtWidgets.so (                                           + 0x1678ee)  [0x7f08a25248ee]
  /usr/lib64/libQt5Core.so.5     ( QCoreApplication::notifyInternal2(QObject*, QEvent*)  + 0x7f  )  [0x7f08a57426df]
  /usr/lib64/libQt5Gui.so.5      ( QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*)  + 0x740 )  [0x7f08a18aac40]
  /usr/lib64/libQt5Gui.so.5      ( QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*)  + 0x265 )  [0x7f08a18ac445]
  /usr/lib64/libQt5Gui.so.5      ( QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0xba  )  [0x7f08a1887aba]
  /usr/lib64/libQt5XcbQpa.so.5   (                                           + 0x67f7a)  [0x7f0896cc5f7a]
  /usr/lib64/libglib-2.0.so.0    ( g_main_context_dispatch                   + 0x267 )  [0x7f08a4c331f7]
  /usr/lib64/libglib-2.0.so.0    (                                           + 0x50480)  [0x7f08a4c33480]
  /usr/lib64/libglib-2.0.so.0    ( g_main_context_iteration                  + 0x2f  )  [0x7f08a4c3350f]
  /usr/lib64/libQt5Core.so.5     ( QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x6d  )  [0x7f08a5796a4d]
  /usr/lib64/libQt5Core.so.5     ( QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>)  + 0x12b )  [0x7f08a574156b]
  /usr/lib64/libQt5Core.so.5     ( QCoreApplication::exec()                  + 0x92  )  [0x7f08a5749342]
  /usr/lib/python3.7/site-packages/PyQt5/QtWidgets.so (                                           + 0x1663dd)  [0x7f08a25233dd]
  /usr/lib64/libpython3.7m.so.1.0 ( _PyMethodDef_RawFastCallKeywords          + 0x2c9 )  [0x7f08a71b6679]
  /usr/lib64/libpython3.7m.so.1.0 ( _PyCFunction_FastCallKeywords             + 0x28  )  [0x7f08a71b6738]
  /usr/lib64/libpython3.7m.so.1.0 (                                           + 0x6897e)  [0x7f08a719197e]
  /usr/lib64/libpython3.7m.so.1.0 ( _PyEval_EvalFrameDefault                  + 0x5ad0)  [0x7f08a7197530]
---- End of Stack Trace ----

**Comment by Chiitoo** [comment]
Please try recompiling 'x11-libs/libfm-qt'.

I've been lagging with fixing this in 0.14.1 due to other stuff (including 0.15.0 bump), so apologies for that!

See also: https://bugs.gentoo.org/708972

**Comment by tsujan** [comment]
Your libfm-qt installation is outdated.

**Comment by tsujan** [comment]
@Chiitoo

Do you support/patch LXQt 0.14.X in Gentoo? The reporter's Qt version is 5.14.1; so, I see no reason why LXQt 0.14.X should still be maintained in Gentoo.

Anyway, as you may already know, LXQt only supports the latest release.

**Comment by Chiitoo** [comment]
> Do you support/patch LXQt 0.14.X in Gentoo? The reporter's Qt version is 5.14.1; so, I see no reason why LXQt 0.14.X should still be maintained in Gentoo.

Yes, for the time being, as it's the only version that is available (aside from 'git master', which isn't recommended for normal use especially on the "stable arch" of Gentoo; 0.15.0 will be there very soon, just a bit delayed as I had been waiting for the few points releases so as to avoid some backporting, and well, I knew they were just around the corner so it made sense to wait).

> Anyway, as you may already know, LXQt only supports the latest release.

Yep.  :]

**Comment by tsujan** [comment]
> just a bit delayed as I had been waiting for the few points releases so as to avoid some backporting

Also Panel will have a point release soon. Apart from that and the current point releases, I don't think there will be important point releases until 0.16.0.

**Comment by Chiitoo** [comment]
Indeed, noticed that one issue.  How soon do you think that will be?

Currently I'm backporting the kbindicator change for it (not pushed to the repos yet so if it's very soon, I might just wait for that still).

**Comment by tsujan** [comment]
> How soon do you think that will be?

Should update translations and changelog. So, tomorrow or the day after it, at most.

**Comment by Chiitoo** [comment]
Cool.

Thanks!
