### ISSUE TITLE
Is there a way to disable marking?

### ISSUE THREAD

**Issue by torben656** [lxqt/pcmanfm-qt#1125]
#166 ### Expected Behavior
I fiddled through the options but couldn't find how to disable marking,
my main "issue" is with the '+' and '-' signs beside files, I know its a small thing,
but I prefer to not have them, on KDE there's a option to disable it.

##### Current Behavior
There is no option to disable the marks, or as of I know.

##### Possible Solution
Create an option for it.

##### Steps to Reproduce (for bugs)
Just open pcmanfm-qt

##### Context
It's just my personal preference to not have marking.

##### System Information
* Distribution & Version: Arch Linux
* Kernel: 5.6.13.arch1-1
* Qt Version: 0.15.0
* libfm-qt Version: 0.15.1-1
* libqtxdg Version: 3.5.0-1
* lxqt-build-tools Version: Not installed
* Package version: 0.15.1-1

**Comment by tsujan** [comment]
Sorry, we can't add an option for each users' personal preference.

> on KDE there's a option to disable it.

LXQt doesn't follow KDE, especially when it comes to the latter's cluttered config dialogs.

**Comment by torben656** [comment]
Ah I understand, I was just asking if there was an option. It is okay though, thank you!
