### ISSUE TITLE
No thumbnails with mcomix/comicthumb

### ISSUE THREAD

**Issue by rtentser** [lxqt/pcmanfm-qt#1128]
Arch Linux, lxqt, pcmanfm-qt 0.15.1.

I've installed mcomix which provides comicthumb for thumbnails generation for cbz, cbr (and some other formats). I've checked it in command line, works all right.

And there is a /usr/share/thumbnailers/comicthumb.thumbnailer. It's content:
```
[Thumbnailer Entry]
TryExec=comicthumb
Exec=comicthumb %u %o %s
MimeType=application/x-cb7;application/x-cbr;application/x-cbt;application/x-cbz;application/x-ext-cb7;application/x-ext-cbr;application/x-ext-cbt;application/x-ext-cbz;
```

But no thumbnails in file manager/on desktop. What's wrong?

**Comment by tsujan** [comment]
The `Exec` line may be incorrect (I don't have cbz, cbr,.. to test). What's `%u`? We need `%s` `%i` and `%o`, as in:
```
Exec=gm convert -quality 100 -thumbnail %s -flatten %i\[0\] %o
```
or
```
Exec=ddjvu -format=tiff -page=1 -size=%sx%s %i %o
```

**Comment by rtentser** [comment]
> What's %u?
Url. I've change it to %i, no difference.

**Comment by tsujan** [comment]
Out of curiosity, I installed mcomix. Now, I need an x-cbz,  x-cbr or x-cbt file to check its `comicthumb` by using command-line (as explained in `man comicthumb`) but I haven't found any. Can you attach one?

**Comment by rtentser** [comment]
> I don't have cbz, cbr

Cbz and cbr are just zip & rar [archives with pictures](https://en.wikipedia.org/wiki/Comic_book_archive). You can archive jpg or png files to zip (for example) and just rename the extension to cbz.

**Comment by tsujan** [comment]
Thanks for the info.

This works with `cbz` without problem:

Make `~/.local/share/thumbnailers/cbz.thumbnailer` as
```
[Thumbnailer Entry]
Exec=comicthumb %i %o %s
MimeType=application/vnd.comicbook+zip;

```
and then, restart Desktop  from LXQt Session Settings.

The problem was in both `Exec` and `MimeType`. Do the same with other supported formats.

**Comment by rtentser** [comment]
Yes, this works like magic, thanks a lot!
Strange thing: when i've changed original .thumbnailer, it doesn't work.
Stranger thing: [.thumbnailer file](https://github.com/multiSnow/mcomix3/blob/gtk3/mime/comicthumb.thumbnailer) in mcomix repository. You can see, it's already implement fixes.
So it's Arch's problem — mcomix package is a little old. I'll report it.
Thanks again!

**Comment by tsujan** [comment]
> Stranger thing: .thumbnailer file in mcomix repository.

Yes, they've fixed it. I also installed the older version from Arch's repository.

**Comment by rtentser** [comment]
Yes, this works like magic, thanks a lot!
Strange thing: when i've changed original .thumbnailer, it doesn't work.
Stranger thing: [.thumbnailer file](https://github.com/multiSnow/mcomix3/blob/gtk3/mime/comicthumb.thumbnailer) in mcomix repository. You can see, it's already implement fixes.
So it's Arch's problem — mcomix package is a little old. I'll report it.
Thanks again!

**Comment by tsujan** [comment]
> Strange thing: when i've changed original .thumbnailer, it doesn't work.

It should work if (1) you made exactly the same changes and restarted Desktop and (2) `/usr/share` is among `XDG_DATA_DIRS` on your system. Here, `echo $XDG_DATA_DIRS` gives:
```sh
~/.local/share:/usr/local/share:/usr/share
```

User files always have priority over system files.

**Comment by rtentser** [comment]
I've replaced old .thumbnailer file with fixed version and restarted Desktop. It works. Maybe i've did a mistake first time.

**Comment by tsujan** [comment]
> I've replaced old .thumbnailer file with fixed version and restarted Desktop. It works.

Good to know that. Meanwhile, I looked into the code and saw that everything is OK :)
