### ISSUE TITLE
Deleting trash can leak a lot of memory from pcmanfm-qt

### ISSUE THREAD

**Issue by Filip98** [lxqt/pcmanfm-qt#1129]
I'm sometimes deleting a large amount of files from the trash and pcmanfm-qt's memory usage keeps rising until it lags my entire system,
I cancel it somewhere midway and gvfsd-trash still uses CPU and pcmanfm-qt stays on e.g 1.5GB RSS.
I have to nuke pcmanfm-qt to release the ram and even gvfsd-trash
##### System Information
* Distribution & Version: Manjaro 20.0.1-1
* Kernel: 5.6.14-lqx1-1-lqx
* Qt Version: 5.14.2
* libfm-qt Version: 0.15.0-1
* libqtxdg Version: 3.5.0-1
* Package version: 0.15.0-2?

**Comment by tsujan** [comment]
> I'm sometimes deleting a large amount of files from the trash and pcmanfm-qt's memory usage keeps rising

Nothing unusual. Memory leak and using more memory are very different from each other.

**Comment by tsujan** [comment]
There's a myth about memory, according to which, if the memory is correctly freed by the app, the memory usage of the app should decrease. In reality, that doesn't happen: the memory is freed but is also ready to be used by the app again.

Most of the time, memory leaks aren't detected by checking the memory usage but by tools like Valgrind.

**Comment by Filip98** [comment]
Okay the problem isn't that it's using more memory but that it keeps using it endlessly, and it only happens in this case

**Comment by tsujan** [comment]
> but that it keeps using it endlessly

"endlessly" isn't precise. Cancelling may not work immediately, depending on the number of trashed files, their sizes and their parent folders. gvfsd-trash's CPU usage shows it's still working.

While I appreciate your report, it isn't specific enough to show that there is a problem in libfm-qt or pcmanfm-qt.

**Comment by Filip98** [comment]
Well thanks for reading through it, I resolved to rm -rf on the trash folder
