### ISSUE TITLE
Disable scroll animation in thumbnail view

### ISSUE THREAD

**Issue by kargaroc** [lxqt/pcmanfm-qt#1132]
##### Expected Behavior

When scrolling in the thumbnail view, the number of pixels scrolled per mouse wheel rotation would be fixed, and would occur instantaneously when the mouse wheel is rotated.
There would be a setting in the preferences to disable this and use the previous behavior.

##### Current Behavior

Currently when scrolling in thumbnail view, the scrolling is animated, and it takes time for the animation to play after I've already scrolled the mouse.
It scrolls past three rows of pictures per scroll, so if I'm looking for something specific, I'll likely miss it while scrolling, *especially* with a small window size.
As far as I'm aware, there's no way to disable this.

##### Possible Solution

The number of pixels scrolled per wheel rotation could be based on the size of the thumbnails

##### Context

Animations for mouse actions take time, and thus slow down the user.
So the ability to disable them allows the user to do things faster.
In this case, it also allows for more precision when scrolling through a directory full of pictures, as the current animation is quite long.

##### System Information

pcmanfm-qt 0.15.1

**Comment by tsujan** [comment]
Use Shift+Wheel to scroll line by line.

> the number of pixels...

Qt works based on the number of *lines*, not pixels. It's configurable in LXQt settings.
