### ISSUE TITLE
After renaming a file it gets unselected

### ISSUE THREAD

**Issue by fulalas** [lxqt/pcmanfm-qt#1135]
After renaming a file pcmanfm-qt selects the file above instead of the one you have just renamed.

**Comment by tsujan** [comment]
Preferences → Behavior → Select newly created files.

**Comment by fulalas** [comment]
It's not a new file, so the option has a wrong name. I'm just wondering why this is not set by default?

**Comment by tsujan** [comment]
> so the option has a wrong name.

Its name is correct. It isn't only for renaming = removing + creating.

**Comment by fulalas** [comment]
If the option name is just 'Select newly created files' and it changes the behavior of files being renamed, then it's obviously incorrect. Whatever...
