### ISSUE TITLE
Keyboard navigation and directories with one entry only

### ISSUE THREAD

**Issue by thenktor** [lxqt/pcmanfm-qt#1136]
##### Expected Behavior
When navigating through directories with keyboard and entering a directory with only one entry (a single file or subdir) hitting one of the arrow keys should select this dir. This is, what all file manager do that I use, including Windows Explorer, KDE Dolphin, Xfce Thunar or old PCManFM.

##### Current Behavior
When entering a directory with only one entry (a single file or subdir) you have to hit space to select that single entry.

##### System Information

* Distribution & Version: Void Linux
* Kernel: 5.4.45
* Qt Version: 5.14.2
* libfm-qt Version: 0.15.1
* Package version: 0.15.1

**Comment by tsujan** [comment]
In Qt, arrow keys go to the next/previous/... item of a view.

In pcmanfm-qt, it's guaranteed that the current item exists. Select the current item by pressing Space, which is the default behavior in Qt and GTK alike.

**Comment by thenktor** [comment]
Hi! Not sure waht you mean with "default behavior in Qt and GTK alike", but in Dolphin (Qt), Thunar (Gtk) and PCManFM (Gtk) the default behaviour is to select the single item, when pressing an arrow key.
Pressing space of course also works, but is cumbersome :(

**Comment by tsujan** [comment]
Making arrow keys select the already existing current item is at odds with the behavior of item views, to say nothing of other widgets.

I don't think Qt developers would agree with such an inconsistency either if you told them. KDE isn't a good model to follow when it comes to consistency. File managers like Nautilus don't have a current item at all.

I guess you may be among those users who select the first item by using an arrow key and then its opposite on opening a folder with Dolphin. Well, *that* is odd, not hitting Space.

Previously, pcmanfm-qt's main view [might not have a current item](https://github.com/lxqt/pcmanfm-qt/issues/1072) and so, arrow keys (as well as `End` and `PgDn`) might select the first item at first. It wasn't a big deal but wasn't good either; so, the existence of the current item was guaranteed in a patch later.

> Pressing space of course also works, but is cumbersome

In case you aren't joking, maybe you shouldn't use a keyboard at all.

**Comment by tsujan** [comment]
For the record (and to use the link of this comment later if needed):

1. Like Nautilus, Thunar doesn't have any current item. GTK supports the concept of "current item" but, perhaps, all GTK file managers followed Nautilus in not using it.

2. Dolphin always has a current item -- like pcmanfm-qt -- and if not selected, it'll be selected when `Space` is pressed. But, at the cost of an inconsistency with Qt, it selects a single current item with arrow keys.

3. Nowhere in Qt, a single current item is selected with arrow keys. It's easy to see that by making a list widget with a single item in Qt Designer. `Space` is the key to select/activate the current item/widget, whether it's single or not. pcmanfm-qt is self-consistent.
