### ISSUE TITLE
Crash  pcmanfm-qt with 120 partitions

### ISSUE THREAD

**Issue by alphaonex86** [lxqt/pcmanfm-qt#1143]
##### Steps to Reproduce (for bugs)

1. Do on uSD GPT:
echo 'mkdir /tmp/emmc/'."\n";
$index=0;
while($index<120)
{
    echo 'parted -a none -s /dev/sdd mkpart btrfs '.(5+$index).'000M '.(6+$index).'000M'."\n";
    echo 'mkfs.btrfs -f /dev/sdd'.(3+$index).''."\n";
    echo 'mount /dev/sdd'.(3+$index).' /tmp/emmc/'."\n";
    echo 'mkdir -p /tmp/emmc/saas'.(480+$index).'/rootfs/'."\n";
    echo 'mkdir -p /tmp/emmc/saas'.(480+$index).'/diff'."\n";
    echo 'mkdir -p /tmp/emmc/saas'.(480+$index).'/.work'."\n";
    echo 'umount /tmp/emmc/'."\n";
    $index++;
}
2. After lot of artifact (as show non existant volume, show the uSD volume after disconnection, ...)
3. I'm not able any more to open pcmanfm-qt
4. Using host libthread_db library "/lib64/libthread_db.so.1".
0x00007fc8d34467ed in __GI___poll (fds=0x55c593ddf6e0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
29      ../sysdeps/unix/sysv/linux/poll.c: No such file or directory.
(gdb) bt
#0  0x00007fc8d34467ed in __GI___poll (fds=0x55c593ddf6e0, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007fc8d3bcfe7e in g_main_context_iterate.isra () at /usr/lib64/libglib-2.0.so.0
#2  0x00007fc8d3bd01e3 in g_main_loop_run () at /usr/lib64/libglib-2.0.so.0
#3  0x00007fc8d3ab9a75 in g_dbus_connection_send_message_with_reply_sync () at /usr/lib64/libgio-2.0.so.0
#4  0x00007fc8d3ab9e6f in g_dbus_connection_call_sync_internal () at /usr/lib64/libgio-2.0.so.0
#5  0x00007fc8d3ac63d6 in g_dbus_proxy_call_sync_internal () at /usr/lib64/libgio-2.0.so.0
#6  0x00007fc8d3ac7774 in g_dbus_proxy_call_sync () at /usr/lib64/libgio-2.0.so.0
#7  0x00007fc8cf957538 in gvfs_dbus_mount_call_query_info_sync () at /usr/lib64/gvfs/libgvfscommon.so
#8  0x00007fc8cf98c7de in g_daemon_file_query_info () at /usr/lib64/gio/modules/libgvfsdbus.so
#9  0x00007fc8d3a196ab in g_file_query_exists () at /usr/lib64/libgio-2.0.so.0
#10 0x00007fc8d4f6870a in Fm::PlacesModel::createTrashItem() () at /usr/lib64/libfm-qt.so.6
#11 0x00007fc8d4f69143 in Fm::PlacesModel::PlacesModel(QObject*) () at /usr/lib64/libfm-qt.so.6
#12 0x00007fc8d4f69ef9 in Fm::PlacesModel::globalInstance() () at /usr/lib64/libfm-qt.so.6
#13 0x00007fc8d4f62c8a in Fm::PlacesView::PlacesView(QWidget*) () at /usr/lib64/libfm-qt.so.6
#14 0x00007fc8d4f37787 in Fm::SidePane::setMode(Fm::SidePane::Mode) () at /usr/lib64/libfm-qt.so.6
#15 0x000055c591d8248c in PCManFM::MainWindow::MainWindow(Fm::FilePath) ()
#16 0x000055c591d98b5a in PCManFM::Launcher::openFolder(_GAppLaunchContext*, Fm::FileInfoList const&, Fm::GErrorPtr&) ()
#17 0x00007fc8d4f222c6 in Fm::BasicFileLauncher::launchFiles(Fm::FileInfoList const&, _GAppLaunchContext*) () at /usr/lib64/libfm-qt.so.6
#18 0x00007fc8d4f21a66 in Fm::BasicFileLauncher::launchPaths(std::vector<Fm::FilePath, std::allocator<Fm::FilePath> >, _GAppLaunchContext*) () at /usr/lib64/libfm-qt.so.6
#19 0x00007fc8d4f38115 in Fm::FileLauncher::launchPaths(QWidget*, std::vector<Fm::FilePath, std::allocator<Fm::FilePath> > const&) () at /usr/lib64/libfm-qt.so.6
#20 0x000055c591d76db2 in PCManFM::Application::launchFiles(QString, QStringList, bool) ()
#21 0x000055c591dc7902 in ApplicationAdaptor::launchFiles(QString const&, QStringList const&, bool) ()
#22 0x000055c591dc7ce9 in ApplicationAdaptor::qt_metacall(QMetaObject::Call, int, void**) ()
#23 0x00007fc8d51b37db in QDBusConnectionPrivate::deliverCall(QObject*, int, QDBusMessage const&, QVector<int> const&, int) () at /usr/lib64/libQt5DBus.so.5
#24 0x00007fc8d51b8e0f in QDBusConnectionPrivate::activateCall(QObject*, int, QDBusMessage const&) [clone .part.0] () at /usr/lib64/libQt5DBus.so.5
#25 0x00007fc8d51b94be in QDBusConnectionPrivate::activateObject(QDBusConnectionPrivate::ObjectTreeNode&, QDBusMessage const&, int) () at /usr/lib64/libQt5DBus.so.5
#26 0x00007fc8d51bc1e8 in QDBusActivateObjectEvent::placeMetaCall(QObject*) () at /usr/lib64/libQt5DBus.so.5
#27 0x00007fc8d3f4b92a in QObject::event(QEvent*) (this=this@entry=0x7ffc39692ca0, e=e@entry=0x7fc8a408b600) at kernel/qobject.cpp:1339
#28 0x00007fc8d3f2638c in QCoreApplication::event(QEvent*) (this=this@entry=0x7ffc39692ca0, e=e@entry=0x7fc8a408b600) at kernel/qcoreapplication.cpp:1964
#29 0x00007fc8d43147bf in QGuiApplication::event(QEvent*) (this=this@entry=0x7ffc39692ca0, e=e@entry=0x7fc8a408b600) at kernel/qguiapplication.cpp:1901
#30 0x00007fc8d49562c2 in QApplication::event(QEvent*) (this=0x7ffc39692ca0, e=0x7fc8a408b600) at kernel/qapplication.cpp:1929
#31 0x00007fc8d494ed92 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x55c592b456c0, receiver=receiver@entry=0x7ffc39692ca0, e=e@entry=0x7fc8a408b600)
    at kernel/qapplication.cpp:3684
#32 0x00007fc8d4958042 in QApplication::notify(QObject*, QEvent*) (this=0x7ffc39692ca0, receiver=0x7ffc39692ca0, e=0x7fc8a408b600) at kernel/qapplication.cpp:3430
#33 0x00007fc8d3f1f5be in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x7ffc39692ca0, event=0x7fc8a408b600) at kernel/qcoreapplication.cpp:1092
#34 0x00007fc8d3f22184 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=0x0, event_type=0, data=0x55c592b40d80) at kernel/qcoreapplication.cpp:1832
#35 0x00007fc8d3f7509b in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x55c592b4f5a0) at kernel/qeventdispatcher_glib.cpp:277
#36 0x00007fc8d3bcfc8d in g_main_context_dispatch () at /usr/lib64/libglib-2.0.so.0
#37 0x00007fc8d3bcff10 in g_main_context_iterate.isra () at /usr/lib64/libglib-2.0.so.0
#38 0x00007fc8d3bcff9f in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0
#39 0x00007fc8d3f74e22 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x55c592b47d00, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#40 0x00007fc8d3f1e41b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7ffc39692c30, flags=..., flags@entry=...)
    at ../../include/QtCore/../../src/corelib/global/qflags.h:136
#41 0x00007fc8d3f26437 in QCoreApplication::exec() () at ../../include/QtCore/../../src/corelib/global/qflags.h:118
#42 0x000055c591d6ec24 in main ()

##### System Information

* Distribution & Version: Gentoo
* Kernel: Linux amber 5.4.8
* Qt Version: 5.14.1-r1
* libfm-qt Version: 0.14.1-r2
* libqtxdg Version: 3.4.0
* lxqt-build-tools Version: 0.6.0

**Comment by tsujan** [comment]
First, please don't report a bug against an outdated version.

Second, if it happens with 0.15.1, find a practical way of reproducing it. I, for one, can't and won't try to mount 120 partitions.

**Comment by alphaonex86** [comment]
Same with version 0.15.1 ;)
It's the base of the problem, 120 partitions, some code part was not designed for this.

**Comment by tsujan** [comment]
> some code part was not designed for this.

Then the problem should show up somewhere else too.

However, we accept patches and PRs will be reviewed.
