### ISSUE TITLE
Daemon mode not working

### ISSUE THREAD

**Issue by ellenkampguus** [lxqt/pcmanfm-qt#1144]
It seems daemon mode is not working. When I start pcmanfm-qt with -d or --daemon-mode it just opens a window instead of running in the background.

##### Expected Behavior

Daemon process in the background, not an open window.

##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: 
* Kernel: 4.15.0-106
* Qt Version: 
* libfm-qt Version:
* libqtxdg Version: 
* lxqt-build-tools Version: 
* Package version: pcmanfm-t 0.12.0

**Comment by tsujan** [comment]
Not reproducible.

Probably you've started another instance of pcmanfm-qt before `pcmanfm-qt -d` (Desktop, for example), in which case `pcmanfm-qt -d` should only start a window.

NOTE: Please always add the versions requested by the issue template. If by "Package version: pcmanfm-t 0.12.0" you really mean 0.12.0, it's so old that I wonder how you can still have it. We only support the latest version -- even 0.14.X is considered outdated.

**Comment by ellenkampguus** [comment]
Thanks for the explanation. A desktop process seems to be indeed running. I didn't check that this time.

An error message when there is already a process running might be useful to prevent confusion.
