### ISSUE TITLE
Button Beauty

### ISSUE THREAD

**Issue by jfk88** [lxqt/pcmanfm-qt#1151]
I love your work guys but this icon ?!? Why? 

![Capture d'écran Deepin_zone de sélection _20200706202158](https://user-images.githubusercontent.com/25780374/86626062-71afd500-bfc6-11ea-9e73-e34f28a06596.png)

**Comment by tsujan** [comment]
You either have an old version or haven't installed a good enough icon set (Breeze icons or another complete set).

**Comment by jfk88** [comment]
Pardon my amateurishness in that area. For those who use the Arc theme (or would like the following result) I updated those navigation icons [here](https://github.com/rtlewis88/rtl88-Themes/issues/33#issue-653668581).

![Capture d'écran Deepin_zone de sélection _20200709014914](https://user-images.githubusercontent.com/25780374/86982243-1843d380-c189-11ea-9d5c-139c1398074c.png)

**Comment by tsujan** [comment]
@jfk88 

Those icons aren't as simple as they may seem. First, the app searches for `view-list-icons`, `view-preview`, `view-list-text` and `view-list-details`. If it didn't find them, it uses QStyle's parameters `SP_FileDialogContentsView`, `SP_FileDialogInfoView`, `SP_FileDialogListView` and `SP_FileDialogDetailedView`. The icons corresponding to those parameters depend on the Qt widget style you use. Fusion may resort to hard-coded Qt icons for some of them.

So, we've done our best to provide those buttons with appropriate icons. The rest should be done by icon sets.
