### ISSUE TITLE
end-key does not work properly

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1156]
open a file, with a lot of documents inside;
then press the end-key on the keyboard

##### Expected Behavior
the last document should be marked

##### Current Behavior
the first document will be marked

(because of that issue,I have always to press 2 times the end-key,
so that the last document is marked)

##### System Information
* Distribution & Version:  Lubuntu 20.04
* Qt Version: 0.14.1

**Comment by tsujan** [comment]
Reported and fixed a long time ago. V0.14.1 is outdated.
