### ISSUE TITLE
shortcut Alt+Enter (file properties) does not work

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1157]
select a document and press Alt+Enter

##### Expected Behavior
the properties window should appear

##### Current Behavior
nothing happens

##### Context
it was already mentioned on
https://github.com/lxqt/pcmanfm-qt/issues/969
but it was closed; maybe it was solved to that time, but now it does not work (again)

##### System Information
Distribution & Version: Lubuntu 20.04
Qt Version: 0.14.1

**Comment by tsujan** [comment]
Not reproducible,.

Please don't report against an outdated version.

**Comment by tsujan** [comment]
BTW, Qt version isn't so important. Please mention the version of the app, against which you report a bug. By chance I knew that Lubuntu 20.04 has an old LXQt version.

**Comment by ralf3u** [comment]
shortcut Alt+Enter (file properties) **still** does not work;
it works on the live-version of the new Lubuntu 20.10, so in English, but in German it does not work; see description above

Lubuntu 20.10 (German language)
LXQt: 0.15.0
pcmanfm-qt: 015.0

**Comment by tsujan** [comment]
> but it does not work in German

Can be about a mistake in the German translation.

@stefonarch, I think you know German. Would you please check it?

**Comment by tsujan** [comment]
@ralf3u, also check if you've installed qt5-translations (or whatever its name is in Ubuntu).

**Comment by ralf3u** [comment]
@tsujan, I don't know how to check; should I give one order in the terminal?

**Comment by ralf3u** [comment]
in main menu>About LXQt, I found this, but I don't know if that helps:
LXQt Desktop Toolbox - Technical Info<p>
  LXQt About Version:     0.15.0
  LXQt Version:           0.15.0
  Qt:                     5.14.2
  Build type:             Release
  System Configuration:   /etc/xdg
  Share Directory:        /usr/share/lxqt
  Translations:           /usr/share/Lubuntu/lxqt/translations<br>
/usr/local/share/lxqt/translations<br>
/usr/share/lxqt/translations<br>
/var/lib/snapd/desktop/lxqt/translations

**Comment by tsujan** [comment]
> I don't know how to check; should I give one order in the terminal?

I don't know either ;) haven't used Ubuntu for 12 years. But you need to use your package manager.

**Comment by ralf3u** [comment]
I have no idea how to use a package manager

**Comment by tsujan** [comment]
Wait until @stefonarch checks the German translation....

**Comment by stefonarch** [comment]
```
 <message>
        <location filename="../main-win.ui" line="654"/>
        <source>Alt+Return</source>
        <translation>Alt+Enter</translation>
    </message>
```
in the actual .ts file in weblate. 
In debian (LXQt 0.14.1) it works in italian ( translated as "invio" ) but not in german. "Enter" is often used, not sure if _Eingabe_ or _Eingabetaste_  will work.

Will test tomorrow with those translations.

**Comment by tsujan** [comment]
@stefonarch, thanks! So, it's a translation issue.

Why should `Return` be translated to `Enter`?! Please also consider this tomorrow: What happens if you change it to `Return`?

**Comment by stefonarch** [comment]
"Enter" for this key has entered German language as "Computer" and else.
Only thing working is translating to "return" (not transating) I see, this still in debian.
`qttranslations5-l10n` is installed.
Will test on arch, but don't think it will change.

**Comment by stefonarch** [comment]
Changed this in weblate for dutch and german, there may be others...

**Comment by tsujan** [comment]
@stefonarch, since `Return` and `Enter` are different keys in English, translating the first to the second was a mistake.

**Comment by stefonarch** [comment]
That's confusing a lot, because "return" for a key isn't used mostly, only "enter".
Google tells me that only Mac's have separate keys for this, on a windows keyboard which key  creates an "enter" ?

**Comment by ito32bit** [comment]
> Changed this in weblate for dutch and german, there may be others...

"Alt+Enter" list: https://translate.lxqt-project.org/search/lxqt-desktop/pcmanfm-qt/?q=target%3AAlt%2BEnter

I changed "Alt+Enter" to "Alt+Return" in weblate for Japanese.

**Comment by tsujan** [comment]
@stefonarch 
I don't have `Return` in my laptop but the keyboards I used with my old desktop computers all had both `Return` and `Enter`.

In addition, I've treated `Return` and `Enter` equally in the code (see https://github.com/lxqt/pcmanfm-qt/commit/03db08cf4a9e1b5f0d7d23857eecbdbfa9a5a1e0).

Anyway, `Return` and `Enter` are two different keys. @ito32bit, I think they shouldn't be swapped in translations.

**Comment by ito32bit** [comment]
> Anyway, `Return` and `Enter` are two different keys. @ito32bit, I think they shouldn't be swapped in translations.

I understand.

My keyboard:
```bash
$ xev
...
    state 0x0, keycode 36 (keysym 0xff0d, Return), same_screen YES,
...
    state 0x10, keycode 104 (keysym 0xff8d, KP_Enter), same_screen YES,
...
```
There are `Return` and `KP_Enter`.

**Comment by stefonarch** [comment]
I see that in 0.14.1 it's not even  displayed in the GUI, in git checkout it's in the "file" menu visible.
On my italian  keyboard is even written "Invio" on the return key.

I'll change the translations for all in the list of @ito32bit (thanks!) and add a label and an explanation in weblate.

**Comment by tsujan** [comment]
> I see that in 0.14.1 

Yes, Alf found it (https://github.com/lxqt/pcmanfm-qt/issues/969#issuecomment-511988621) but forgot to correct it.

> I'll change the translations for all

Thanks!

**Comment by stefonarch** [comment]
https://translate.lxqt-project.org/translate/lxqt-desktop/pcmanfm-qt/de/?offset=1&q=return&sort_by=-priority%2Cposition&checksum=

**Comment by ralf3u** [comment]
In the properties in the tab "General" I can see the bytes.
Sometimes I need to copy the numbers on a paper, but this kind of number is really hard to read:
86166816397

It would be much better to read, if it would be shown like this:
86,166,816,397

For example in Windows XP it is shown like this: 86,166,816,397

**Comment by tsujan** [comment]
> but this kind of number is really hard to read

It isn't for reading but for copy-pasting into calculations. The human readable size is outside parentheses.

**Comment by stefonarch** [comment]
> shortcut Alt+Enter (file properties) does not work in the French version; LXQt 0.17.0; Lubuntu 22.04

Thanks, `Alt+Return` was translated with` Alt+Entrée`, leaving it empty Qt translates to  `Alt+Retour` will fix it.
