### ISSUE TITLE
File dialog doesn't remember ordering

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1164]
When opening files from an Qt application like Falkon or VLC the dialog window remembers well view mode but never list order and other view settings, it always will fall back to ordering by name at next opening.

##### Expected Behavior

If it remembers view mode it should also remember other display settings.
##### Current Behavior

It doesn't.

##### Steps to Reproduce (for bugs)

1. Hit cltr+o in VLC or Falkon
2. Set to icon view and  right click > sorting > by modification time
3. Press esc
4. Hit cltr+0 again, only icon view is remembered.

##### System Information

* Distribution & Version: arch and git checkout

**Comment by tsujan** [comment]
You can't have the latest git because the feature was added in https://github.com/lxqt/libfm-qt/pull/548 and works fine.

**Comment by tsujan** [comment]
Also, https://github.com/lxqt/libfm-qt/pull/554 will be merged soon. With them, every important setting will be remembered by LXQt file dialog *after it is closed.*

**Comment by stefonarch** [comment]
> You can't have the latest git because the feature was added in [lxqt/libfm-qt#548](https://github.com/lxqt/libfm-qt/pull/548) and works fine.

I recompiled today, but forgot to restart pcmanfm-qt, but I see no change.

**Comment by stefonarch** [comment]
> You can't have the latest git because the feature was added in [lxqt/libfm-qt#548](https://github.com/lxqt/libfm-qt/pull/548) and works fine.

I compiled today, but forgot to restart pcmanfm-qt, but I see no change, also not for hidden files.

**Comment by tsujan** [comment]
> I compiled today

Something may have gone wrong during the recompilation. All settings related to hidden files and the "Sorting" menu are remembered here.

Also, check the permissions of `~/.config/lxqt/filedialog.conf`.

**Comment by tsujan** [comment]
Also, a logout+login is worth the try.

**Comment by stefonarch** [comment]
The file is writeable and refers only to Sizes and Mode=
```
[Sizes]
SplitterPos=200
WindowSize=@Size(953 644)

[View]
Mode=Compact
```

Did restart session.

**Comment by tsujan** [comment]
You said you forgot to restart pcmanfm-qt. But this isn't related to pcmanfm-qt. The only explanation that comes to my mind is that you don't have the latest git libfm-qt.

If there can be another cause, it isn't known to me and doesn't exist here.

**Comment by stefonarch** [comment]
Ok, found out by testing my clean user, where it worked.
If the file `~/.config/lxqt/filedialog.conf` exists in the old mode as posted above the bug is present. 
Deleting the file or adding the missing sections

```
SortColumn=mtime
SortFolderFirst=true
SortOrder=ascending
```
it start remembering. 
I tested it twice, so it looks like the old file inhibits the adding of the other settings, missing new line. Adding a new empty line it will update.

**Comment by tsujan** [comment]
> If the file ~/.config/lxqt/filedialog.conf exists in the old mode as posted above the bug is present.

Before writing my previous comment, I copied and pasted the contents of your `filedialog.conf` to mine and everything was OK.

**Comment by tsujan** [comment]
> missing new line. Adding a new empty line it will update.

All Qt's config files have empty lines at their ends. You may have edited the file manually and removed the last empty line.

Whether Qt accepted a config file without an empty end line before but that behavior has changed with Qt 5.15, I don't know.

**Comment by tsujan** [comment]
To prevent confusion for future readers of this page, I tested by removing the last empty line from the config file and using the same contents as in https://github.com/lxqt/pcmanfm-qt/issues/1164#issuecomment-660640681. Again, the settings were remembered correctly. Moreover, Qt added the last empty line. Qt 5.15 and 5.14 had the same behavior.

So, Qt correctly reads and writes to a config file whose last empty line is removed manually.

What happened in @stefonarch's case, I 'm not sure. A wild guess can be that the file was somehow corrupted — the lack of the last empty line is very suspicious.
