### ISSUE TITLE
annoying popup-information when moving with the mouse over files

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1167]
keyboard-navigation
when I navigate with the arrow-keys of the keyboard in the file manager, then the current file is highlighted; that‘s perfect; there is no annoying popup-information

mouse-navigation
when I navigate with the mouse and if I click on a file, then it is highlighted; then if I go with the mouse over other files, then the files are highlighted in a different color then the marked file; that‘s perfect
the issue: there is an annoying popup-information where the name appears a second time; I don‘t need this information because the name is already highlighted; the popup-information is annoying because I can‘t see the name of the next file

if you like the popup-information, at least it would be good if there would be in the preferences the option to disable it, for example with a checkbox (disable popup-information when moving with the mouse over files)

system information:
Lubuntu 20.04
LXQt: 0.14.1

**Comment by tsujan** [comment]
Those popups are called tooltips and "annoying" is a subjective word. They can already be disabled in Preferences with the latest git LXQt.

Please,
 1. Search in closed/open issues before opening a new one.
 2. Don't report an issue if you have an outdated LXQt version (like 0.14.1) unless you're sure that the issue exists in the latest version too.
