### ISSUE TITLE
disable/enable: title bar (or rather window bar)

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1175]
the title bar in pcmanfm-qt is not useful because one can recognize pcmanfm-qt by its design;
in firefox there is the possibility to disable/enable the title bar;
so my suggestion for improvement in pcmanfm-qt:

- disable/enable the title bar in the menu View with a checkbox
- when disable the three icons (minimize, maximize and close) should move in the tab bar like in firefox; that is also a reason why the tab bar should be above the symbol bar and not below the symbol bar; then one would have the same look and feel like in firefox or in the chromium-browser; for the eyes it is much easier when the tabs are on top

with openbox there is the possibility to disable/enable the title bar, but it is a process:
- open in the userfile .config/openbox/lxqt-rc.xml in an editor
- look in the document for &lt;applications>
- add these lines right under &lt;applications>:
    &lt;application class="pcmanfm-qt">
      &lt;decor>no&lt;/decor>
    &lt;/application>
- save the document
- close the editor and close pcmanfm-qt
- open terminal and add this line:
openbox --restart
- press enter

I think that this possibility from above will not exist when Lubuntu will move from openbox to Wayland

please don‘t close this issue and put it in the enhancement-label

**Comment by tsujan** [comment]
1. Titlebar is managed by WM, not by LXQt or Qt. The user is free to use any WM with LXQt. Openbox is just an old and simple choice that still works but it doesn't belong to LXQt and isn't the best choice for all.

2. What you described isn't related to pcmanfm-qt or its design. It's called CSD. GTK has CSD (and many users want to get rid of it); Qt doesn't.

**Comment by tsujan** [comment]
> please don‘t close this issue and put it in the enhancement-label

This is the second time you tell me that. An issue may be closed or left open based on reasons that are explained as clearly as possible. Also, labels (like "enhancement") may be added *for a reason*, not just because we like to add them.
