### ISSUE TITLE
pcmanfm-qt 0.15.1: shortcuts

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1176]
alt+home: does not work
alt+enter: does not work
ctrl+m: does not work (although it should work according to the popup-window)
ctrl+w: (close tab) does not work
ctrl+n or t: (for a new tab): does not work

ctrl+l, ctrl+a and ctrl+f:
maybe it would be good if you press it again the feature disappears; for example:
ctrl+l: the address of the location bar is marked
again ctrl+l: the focus is again on the content of the tab

maybe it would be good to add to the preferences the point 'shortcuts' on the right, so that everyone can choose the own shortcuts; this would be my choice:
ctrl+h: user-file (instead of the common use alt+home)
ctrl+a: mark all files/don‘t mark all files
ctrl+p: show/hide properties
ctrl+b: show/hide Side Pane (b like in Firefox for the bookmark bar) (instead of F9)
ctrl+n: new tab (instead of the common use of t)
ctrl+t: show/hide hidden files (t for transparency)
ctrl+f: show/hide the search bar
ctrl+w: close tab
ctrl+m: create a new file (m for make new file)
ctrl+l: mark/don't mark location bar
ctrl+s: show/hide settings
ctrl+r: show root files
ctrl+shift+n: new window
ctrl+shift+m: show/hide menu

tested on
Manjero LXQt
pcmanfm-qt 0.15.1

**Comment by ralf3u** [comment]
ah, ...  and as my choice: ctrl+d for divide view (instead of F6)

**Comment by ralf3u** [comment]
maybe it would be good to add to the preferences the point 'shortcuts' on the right, like in ScreenGrab 2.0.0

**Comment by ralf3u** [comment]
as comparison: that works in pcmanfm-qt 0.14.1:
alt+home: works
ctrl+m: works
ctrl+t: works
ctrl+w: works

**Comment by tsujan** [comment]
Please stop opening invalid reports!

**Comment by tsujan** [comment]
GitHub will have a section called "Discussion" and we will add it to LXQt when it's ready. You could ask for help (like, "Why don't alt+home, alt+enter,... work for me?") or tell about your opinions there.

There can be various reasons why a shortcut may not work in an app. The most frequent reason is that WMs like Openbox may "consume" some shortcuts in their settings. Bad translation/localization is another reason but you didn't give any info about your localization.

We very appreciate valid bug reports and feature requests.

**Comment by tsujan** [comment]
Last but not least, see here for an example of a good report that was made at the same time: https://github.com/lxqt/lxqt-notificationd/issues/208
