### ISSUE TITLE
Lexical inconsistency

### ISSUE THREAD

**Issue by Bydo-Spore** [lxqt/pcmanfm-qt#1183]
Minor issue in 0.15.1:

Regardless of whether I am deleting one file or more than one file I am asked:
`Do you want to delete the selected file**s**?`
and yet in the status bar it says:
`37 item(s)`

Ideally both would check how many files are selected/present and print 'file'/'files' and 'item'/items' accordingly. Failing that, 'files' should be changed to 'file(s)' so that it's consistent with 'item(s)' and technically not incorrect when only one file is selected.

**Comment by tsujan** [comment]
True. Also, the trashing prompt and another confirmation dialog have always been so.

Will change them later -- or, perhaps, another contributor will do it.
