### ISSUE TITLE
Impossible to prevent thumbnails & tooltips in Open/Save dialogs

### ISSUE THREAD

**Issue by Bydo-Spore** [lxqt/pcmanfm-qt#1184]
0.15.1

In PCManFM-Qt preferences, `Show thumbnails of files` is set to false and `Do not show file tooltips` is set to true.

These cause the expected behaviour in the file manager itself, but not in the Open/Save dialogs, which ignore these settings and still read every image file and video (if `ffmpegthumbnailer` is installed). There seems to be no option to enable/disable these for Open/Save dialogs.

**Comment by tsujan** [comment]
File manager has no relation to file dialog. Also see https://github.com/lxqt/libfm-qt/issues/349, https://github.com/lxqt/libfm-qt/commit/928a85a173ab889e584a43df1eef54c37ee37322 and https://github.com/lxqt/libfm-qt/commit/6b82edd42810b5717f8db98fd8bf26003866e662

A preferences dialog for LXQt file dialog would probably be an overkill. So, no plan for adding it.

**Comment by Bydo-Spore** [comment]
The two main reasons people are going to want to disable thumbnail creation are 1. privacy, and 2. to decrease system resources use.

Regarding privacy, there's absolutely no point in disabling thumbnail creation in the file manager if it's still done whenever a file is opened or saved.

Really, it seems bizarre to be able to disable them in the file manager, but be unable to disable them anywhere else.

A global option to disable thumbnails like Tumbler has in Xfce would make much more sense.

**Comment by tsujan** [comment]
> Really, it seems bizarre to be able to disable them in the file manager, but be unable to disable them anywhere else.

It would be "bizarre" -- actually a bug -- if they were disabled everywhere. lbfm-qt is a library that can be used by any app. An app like lximage-qt always needs thumbnails, while another app may not. Different apps/GUIs need their separate settings.

> A global option to disable thumbnails like Tumbler has in Xfce...

Irrelevant to LXQt, for the above reason (at least).

**Comment by Bydo-Spore** [comment]
I'm interested: why's there an option to disable thumbnail creation in the File Manager, given that thumbnails will be still be created anyway?

**Comment by Bydo-Spore** [comment]
That's what I mean by bizarre.

**Comment by Bydo-Spore** [comment]
It must be for users that think: "I like thumbnails, but only if they're created by Open and Save dialogs. I don't like the thumbnails that the file manager creates."
