### ISSUE TITLE
"Show folder context menu with Ctrl + right click" option is superfluous

### ISSUE THREAD

**Issue by Bydo-Spore** [lxqt/pcmanfm-qt#1186]
All the functionality of this menu is repeated elsewhere and is easily accessible:

**Create New** is already in the File menu
**Paste** is already in the Edit menu
**Select All** is already in the Edit menu
**Invert Selection** is already in the Edit menu
**Sorting** is already in the View menu
**Show Hidden** is already in the View menu
**Open Folder as Root** is already in the standard right-click menu
**Folder Properties** is already in the File menu

You have espressed ([here](https://github.com/lxqt/libfm-qt/issues/349), for example) your reluctance to "clutter the GUI" with "yet another button", but with this extra right-click menu, not only have you done just that, but it's also duplicating already-existing functionality, rendering it a waste of space. And yet you still felt that it was more worthy of inclusion than numerous feature requests you have denied on the grounds that they would 'clutter the GUI'. On these occasions your explanations cannot seem anything other than disingenuous.

**Comment by tsujan** [comment]
> You have espressed (here, for example) your reluctance to "clutter the GUI" with "yet another button".

There's no other button in the case of Ctrl+right-click.

> it's also duplicating already-existing functionality

If it was, I wouldn't add it.  Custom actions aren't covered by window menus. You may not use them but others do.

> rendering it a waste of space

You've mistaken app's GUI with preferences GUI.

> On these occasions your explanations cannot seem anything other than disingenuous.

I have no problem with labels ("disingenuous"); after all, they're just labels.

If you have a problem with me being in control here, try to replace me.But, as long as I'm here, please stop wasting my time by opening senseless issues.

**Comment by Bydo-Spore** [comment]
> Custom actions aren't covered by window menus. You may not use them but others do.
What?
I'm talking about superfluous **folder** context menus and you're saying that they're necessary because people have custom actions that are in **file** context menus only. Seriously? That's the only rationale you could think of: one that isn't even based on fact and is instead some spurious thing that you seem to have made up on the spot?

Surely you didn't actually make that mistake and you're just obfusticating?

> You've mistaken app's GUI with preferences GUI.
So you're happy to clutter preferences GUIs with superfluous widgets whose entire functionality is duplicated?

**Comment by Bydo-Spore** [comment]
> You've mistaken app's GUI with preferences GUI.

More obfustication.
You've stated [here](https://github.com/lxqt/pcmanfm-qt/issues/1125) that you don't want LXQt's **config** dialogs to be cluttered.

**Comment by Bydo-Spore** [comment]
To be honest, I knew you were going to dismiss this report even before I made it. I was testing you, and now I know the truth.

You don't really care that this issue is 100% valid. You're on an ego trip having assumed the role of 'leader' of this project; and as such there's no way you'll ever renege on any of your decisions regarding it, no matter how ill-advised they were. This behaviour has been demonstated time and again in many of the numerous issue reports that you have dismissed.

It is very disheartening to read these reports. These people are only trying to help the project, but you treat them like annoying idiots that are getting in the way of your 'vision'.

When genuinely ridiculous design decisions on your part are pointed out to you, like in this issue report, you dismiss them with spurious arguments that don't even make sense. This isn't the behaviour of a rational person; it is the behaviour of someone with an inflated sense of his own importance who considers himself beyond reproach.

Good day.
