### ISSUE TITLE
Remove plus/minus symbols when hovering over icons

### ISSUE THREAD

**Issue by probonopd** [lxqt/pcmanfm-qt#1187]
##### Expected Behavior

Like on macOS, Windows, Xfce: no plus/minus icons are shown when the mouse hovers over icons

##### Current Behavior

Irritating plus/minus icons are shown when the mouse hovers over icons.

![image](https://user-images.githubusercontent.com/2480569/91662285-af6e3d00-eae1-11ea-95d7-528eeefa10ef.png)

![image](https://user-images.githubusercontent.com/2480569/91662428-a29e1900-eae2-11ea-906f-5cab00c1b146.png)

##### Possible Solution

* Remove those irritating, extraneous + and - icons
* If not desired, at least make it possible to configure them away

##### Context

These icons are irritating for users coming from most other environments like macOS, Windows, Xfce.

I could not figure out what these are good for. Someone in the KDE project where they have similar icons told me they are meant to select multiple files on touchscreen devices. But that does not make a whole lot of sense to me:

* PCManFM-Qt is overall not designed for touch screen devices
* With the mouse or the trackpad, multiple files can be selected using Shift-click, Ctrl-click, mouse drag.

##### System Information

* Distribution & Version: FreeBSD
* libfm-qt Version: 0.15.0

**Comment by tsujan** [comment]
Sorry but coding based on users' "feelings" would be a mess because, among other things, different users have different "feelings".

> I could not figure out what these are good for.

Sarcasm: They're good for nothing; that's the reason why they're added.

**Comment by probonopd** [comment]
Thanks @tsujan for looking at this issue. I appreciate you making opinionated decisions, but did you consider my suggestion to at least make it possible to configure them away? (A config file based solution would be sufficient for me.)

**Comment by probonopd** [comment]
For the benefit of those who might come across this ticket through search, the extraneous icons do not appear in https://github.com/probonopd/filer:

![image](https://user-images.githubusercontent.com/2480569/92018367-5dcde880-ed55-11ea-82b7-98007bea388d.png)
