### ISSUE TITLE
Show the localiized name of trusted desktop files

### ISSUE THREAD

**Issue by probonopd** [lxqt/pcmanfm-qt#1188]
##### Expected Behavior

Desktop files (launchers) show the localized, readable name of the application, e.g., "Chromium", "OBS Studio", "Fenstereffekte"

##### Current Behavior

![image](https://user-images.githubusercontent.com/2480569/91662480-f7419400-eae2-11ea-9d72-144f900689ed.png)

##### Possible Solution

Parse and use the `Name=` value of the desktop file (and its localized counterparts).

##### Steps to Reproduce (for bugs)

Navigate to `/usr/local/share/applications` (on FreeBSD) or /usr/share/applications (on most Linux distributions) using pcmanfm-qt.

##### Context

I prefer to launch applications using their desktop files through the file manager rather than using a Start menu or similar launcher.

##### System Information

* Distribution & Version: FreeBSD
* libfm-qt Version: 0.15.0

**Comment by tsujan** [comment]
Preferences → Display → Always show real file names.

**Comment by probonopd** [comment]
It is checked - bug?

**Comment by probonopd** [comment]
Thanks @tsujan, this worked. Need to make sure that this is __not__ checked.

Could it be considered to make "unchecked" the default?

**Comment by tsujan** [comment]
> Could it be considered to make "unchecked" the default?

No. There's a long discussion behind it. I really have no time to explain it here or find the pages.
