### ISSUE TITLE
Nothing should be selected when nothing is selected

### ISSUE THREAD

**Issue by probonopd** [lxqt/pcmanfm-qt#1191]
##### Expected Behavior

No object is selected visually when no object has been selected by clicking on it.

##### Current Behavior

![image](https://user-images.githubusercontent.com/2480569/91663229-ee06f600-eae7-11ea-98a7-d99c71ca724f.png)

Note that even clicking into the white space does not make that "fake selection" go away. I want nothing to be selected, yet why is there always something visually selected?

##### Possible Solution

![image](https://user-images.githubusercontent.com/2480569/91663244-04ad4d00-eae8-11ea-9b25-64e8f2a4aef9.png)

##### Steps to Reproduce (for bugs)

Open a window that contains some files or directories and activate the pcmanfm-qt window.

##### Context

This confuses the user, and is counterintuitive. Unlike Windows, macOS, and Xfce.

The original non-Qt pcmanfm behaves correctly.

##### System Information

* Distribution & Version: FreeBSD
* libfm-qt Version: 0.15.0

**Comment by tsujan** [comment]
Wow! "Fake selection"? Really?

**Comment by probonopd** [comment]
> Wow! "Fake selection"? Really?

Yes. See that blue background behind `AdressManager.app`? I did not select that item, yet it is displayed differently from the rest. 

Why?

**Comment by tsujan** [comment]
> Why?

Keyboard exists.

**Comment by probonopd** [comment]
A selection could appear as soon as the user uses any of the arrow keys. But not when the keyboard is not used at all (probably 99.9% of the time)

**Comment by tsujan** [comment]
Select an item → Deselect it → Press space.

Advanced toolkits have the concept of "current item/widget" and a way of distinguishing it visually.

**Comment by tsujan** [comment]
> not when the keyboard is not used at all (probably 99.9% of the time)

Oh, I didn't see this but can't ignore it now. *You* may not use your keyboard "99.9% of the time" but there are users that do. An option for those who don't use their keyboards "99.9% of the time"? Never!

**Comment by probonopd** [comment]
Wouldn't have to be an option. This light blue selection could appear once the keyboard user touches the keyboard, using one of the arrow keys... hence no disadvantage for the keyboard user while the mouse user is not confused.

**Comment by tsujan** [comment]
> This light blue selection could appear once the keyboard user touches the keyboard

Unfortunately, most arrow keys don't send a signal when they're touched. The same is true for the Space key.

**Comment by probonopd** [comment]
I meant "pressed" :100:

**Comment by tsujan** [comment]
> I meant "pressed"

Then it's too late, for obvious reasons.

**Comment by probonopd** [comment]
This is what happens in other systems (will be appended to):

 __OS X 10.9__:

* Opening a window does not "half-select" anything

In Icon view:
* Pressing Arrow-right selects the leftmost item in the first row of icons
* Pressing Arrow-left selects the rigthmost item in the first row of icons
* Pressing Arrow-down selects the leftmost item in the first row of icons
* Pressing Arrow-up selects the leftmost item in the last row of icons

In list view:
* Pressing Arrow-right has no function
* Pressing Arrow-left has no function
* Pressing Arrow-down selects the item in the first line
* Pressing Arrow-up selects the item in the last line

I think this is very sensible.

Will check other systems, too.

**Comment by tsujan** [comment]
You didn't (or didn't want to) understand a word of what I said. Enough is enough.

**Comment by probonopd** [comment]
Would you say Non-Qt pcmanfm is _worse_ in this regard then?
