### ISSUE TITLE
Unmount/eject missing in context menu for the items in "Computer"

### ISSUE THREAD

**Issue by probonopd** [lxqt/pcmanfm-qt#1193]
##### Expected Behavior

Context menu for the items in "Computer" lets me unmount/eject disks/volumes in exactly the same way as the icons under "Devices" in the "Lists" view work

##### Current Behavior

![image](https://user-images.githubusercontent.com/2480569/92159481-c4263a00-ee2d-11ea-96cc-0d32e0984457.png)

##### System Information
* Distribution & Version: FreeBSD 12.1-RELEASE-p8
* Kernel: FreeBSD 12.1-RELEASE-p8
* pcmanfm-qt Version: 0.15.0

**Comment by tsujan** [comment]
This is a valid feature request but not useful. Why should we add extra code to do something that can already be done in the side pane?!

If you agree with that, please close this page. If not, you don't need to convince me; just make a PR with a *clean and concise* code and I'll review it happily.

**Comment by probonopd** [comment]
> Why should we add extra code to do something that can already be done in the side pane?!

Thanks for sharing your opinion but I don't think this reasoning is consistent with having a desktop in the first place. Applying this reasoning one could say:

Why should we have a desktop then at all, when everything can be done in the file manager window?

**Comment by tsujan** [comment]
This isn't about desktop but the item view.

Anyway, as I said, you don't need to try to convince me; I won't be convinced by words but only by seeing a clean and concise code.

**Comment by tsujan** [comment]
→ https://github.com/lxqt/libfm-qt/issues/658
