### ISSUE TITLE
[Feature request] Implement org.freedesktop.FileManager1 DBus interface

### ISSUE THREAD

**Issue by probonopd** [lxqt/pcmanfm-qt#1194]
##### Expected Behavior

When I select "show in folder" for a download in a browser, the Downloads folder should be opened and the downloaded file should be selected.

##### Current Behavior

When I select "show in folder" for a download in a browser, then only the Downloads folder opens but I have to search for the downloaded file manually, which can be quite annoying if I don't sort by date.

##### Possible Solution

Looks like GNOME and KDE use https://www.freedesktop.org/wiki/Specifications/file-manager-interface/, `org.freedesktop.FileManager1` DBus name and the `/org/freedesktop/FileManager1` object path. 

Looking at https://github.com/linuxdeepin/dde-file-manager/search?q=dbusfilemanager1 the implementation seems to be relatively straightforward.

And e.g., Chromium implements it:
https://chromium.googlesource.com/chromium/src/+/master/chrome/browser/platform_util_linux.cc

Since pcmanfm-qt is all about XDG standards, I'd ask for consideration to implement this feature.

##### Context

My downloads folder is always full and it is annoying that pcmanfm-qt cannot do what other file managers do in this regard.

**Comment by tsujan** [comment]
This feature request looks valid to me.

PRs would be appreciated.

**Comment by tsujan** [comment]
@probonopd, can I assign it to you?

**Comment by probonopd** [comment]
I will answer here once I am ready to work on it. Maybe someone else can do it faster than me.

**Comment by tsujan** [comment]
OK. 

I don't think I'll have time to work on it soon but I hope you'll do it. However, there's no rush. Take your time!

**Comment by probonopd** [comment]
Started to work on this at

https://github.com/helloSystem/Filer/commit/4c1f261220f9d0993b219c32f57a929aec753b80

but am stuck at

https://github.com/helloSystem/Filer/issues/15#issuecomment-882081950.

Maybe someone has some ideas.

**Comment by probonopd** [comment]
It is implemented in Filer now.

Chromium:

https://user-images.githubusercontent.com/2480569/133944490-a0e28017-79b0-4fd0-9e9d-7661f905cde7.mp4

* https://github.com/helloSystem/Filer/commit/191826b3f46870288ce69f8ee3ad365845c526f8
* https://github.com/helloSystem/Filer/commit/7070369ff815b4de0fd38e017962cebc3515d80f

**Comment by ahsand97** [comment]
is anyone working on this by PcManFM? or are PRs welcome?

**Comment by tsujan** [comment]
PRs are always welcome.

**Comment by probonopd** [comment]
@ahsand97 while I am not working on PRs for PCManFM, you could have a look at what we did in Filer (a fork of PCManFM) and backport that to PCManFM if you like.

**Comment by probonopd** [comment]
Thank you @ahsand97 and @tsujan. Nice to see this implemented!
