### ISSUE TITLE
The Applications menu is empty

### ISSUE THREAD

**Issue by itaranto** [lxqt/pcmanfm-qt#1198]
The Applications menu is empty.

From the console I see the following error upon clicking the "Applications" menu.

```
file monitor cannot be created: FmMenuVFileMonitor: folder '(null)' not found in menu cache
```

I already created  the files **~/.config/mimeapps.list** and **~/.local/share/applications/mimeapps.list**.

I'm not using the LXQt desktop evironment, I'm using i3.

##### Expected Behavior
The appplications menu is not empty.

##### Current Behavior
The Applications menu is empty,

##### Steps to Reproduce (for bugs)
1. Open pcmanfm-qt
2. Click on "Applications"

##### System Information
* Distribution & Version: openSUSE Tumbleweed 20200910
* Kernel: 20200910
* Qt Version: 5.15.0
* libfm-qt Version: 0.15.1-1.4
* libqtxdg Version: 
* lxqt-build-tools Version: 
* Package version: 0.15.1-2.4

**Comment by tsujan** [comment]
I'm not familiar with OpenSUSE packages; @jubalh may know the answer. But do you have `lxmenu-data` and `menu-cache`?

Anyway, most probably, this is a downstream issue. Will be reopened if proven otherwise.

**Comment by itaranto** [comment]
>  But do you have lxmenu-data and menu-cache

I didn't have lxmenu-data installed. Now it works!

> BTW, I assumed that by "application menu" you meant the "Applications" item on the side-pane of pcmanfm-qt. pcmanfm-qt creates no applications menu.

I meant the "Applications" menu from the "Places" panel.

> Anyway, most probably, this is a downstream issue. Will be reopened if proven otherwise.
I'll file a bug in the openSUSE tracker since lxmenu-data should be a recommended package at least.

Thank you.

**Comment by tsujan** [comment]
> lxmenu-data should be a recommended package at least.

Yes, `lxmenu-data` is a run-time dependency, as is mentioned in [pcmanfm-qt's `README.md`](https://github.com/lxqt/pcmanfm-qt#compiling-source-code).
