### ISSUE TITLE
[feature request] 'next wallpaper'

### ISSUE THREAD

**Issue by victor03303** [lxqt/pcmanfm-qt#1202]
When right clicking on the desktop or wallpaper
I'd like an option 'next wallpaper'
just like one would have in Windows

**Comment by tsujan** [comment]
The slide show has a timer. You could choose the minimum interval of 5 minutes if you want your wallpaper to change often. I don't see any reason to clutter the right-click menu — whether Windows has an item or not is irrelevant.
