### ISSUE TITLE
PCManFM removes symlinked ~/.config/mimeapps.list

### ISSUE THREAD

**Issue by itaranto** [lxqt/pcmanfm-qt#1226]
I have a symlinked `~/.config/mimeapps.list` file, when I set new associations via PCManFM the symlink gets removed and replaced with a non-link `mimeapps.list` file.

##### System Information
* Distribution & Version: Arch Linux
* Kernel: 5.9.2-arch1-1
* Qt Version: 5.15.1-3
* libfm-qt Version: 0.15.1-3
* libqtxdg Version: Not installed 
* lxqt-build-tools Version: Not installed
* Package version:

**Comment by tsujan** [comment]
A symlink will and should be replaced by all mimetype setting tools if changes are needed. Don't use a symlink there.
