### ISSUE TITLE
double use of shortcut: undo

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1228]
for some shortcuts there should be a kind of OFF

##### Expected Behavior
press 2x ctrl+a or ctrl+l, ctrl+f or ctrl+i or F3: the effect should disappear

##### Current Behavior
press 2x ctrl+a or ctrl+l, ctrl+f or ctrl+i or F3: there is no undo

##### Possible Solution
F6, F9, ctrl+h and ctrl+m: undo works
example: press 2xF9: undo works

##### Steps to Reproduce (for bugs)
press 1x ctrl+a: all files are marked
press again 1x ctrl+a: all files are still marked

##### Context
example: sometimes I want to search a file, so I press ctrl+f, but then suddenly I have a better idea,
so I would like to undo; instead of the esc-key I would like to press again ctrl+f;
with 2x ctrl+f I would be faster then ctrl+f and esc
(in portable OpenOffice 2.4.0 it works, so by pressing with 2x ctrl+f the search window disappears)

##### System Information
* Distribution & Version: lubuntu 20.10
* Kernel: 5.8.0-25-generic
* Qt Version: 0.15.0

**Comment by tsujan** [comment]
> press 2x ctrl+a or ctrl+l, ctrl+f or ctrl+i or F3: the effect should disappear

They shouldn't. As for ctrl+a, what you request is so unusual in file managers and text editors. As for others, press Esc.

> so I would like to undo; instead of the esc-key... with 2x ctrl+f I would be faster then ctrl+f and esc

Too personal. Liking/disliking isn't relevant.
