### ISSUE TITLE
Item tooltips don't disappear immediately when directory is changed by shortcut

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1229]
infobox does not disappear immediately when directory is changed

##### Expected Behavior
infobox should disappear immediately when directory is changed

##### Current Behavior
infobox does not disappear immediately when directory is changed

##### Possible Solution
infobox should disappear immediately when directory is changed

##### Steps to Reproduce (for bugs)
example:
open the home-file
open the image-file
go with mouse over an image
infobox will appear (some kind of property-window)
press alt+arrow-left or backspace to go back to the home-file
the infobox will still stay for about 17 seconds (although the image is not more on the screen)

##### Context
the infobox is annoying because there is no image any more on the screen

##### System Information
* Distribution & Version:  Lubuntu 20.10
* Kernel: 5.8.0-25-generic
* Qt Version: 0.15.0

**Comment by ralf3u** [comment]
what I forgot to mention: to see this mistake even better:
- pcmanfm should be maximized
- compact view
- the image should be somewhere on the bottom right of pcmanfm

**Comment by ralf3u** [comment]
what I also forgot to mention: to see this mistake even better:
- in the home-file there should be just some files and documents (so that there is emptiness on the bottom right of the screen)

**Comment by tsujan** [comment]
There's nothing called "infobox". OK, you may mean "tooltip". That makes your fist comment valid and I'll change the title accordingly.

I can't understand your second and third comments, let alone their relation to the main topic. Which image should be on the bottom right? Which "emptiness?...

**Comment by tsujan** [comment]
Please also add the version of your installed pcmanfm-qt to your report.

**Comment by ralf3u** [comment]
pcmanfm-qt version: 0.15.0

**Comment by ralf3u** [comment]
to my comments 2 and 3:
it is just about less or more attention

the mistake becomes even more visible when there are just some files and documents in the home-file, and when in the image-file there are many many pictures; by going with the mouse on the picture that is in the right bottom corner the tooltip will appear there; by going back to the home-file with just some files and documents, there is some kind of emptiness in the right bottom corner, so that the tooltip will be more dominant;
if in the home-file there would be many many documents and files, then the tooltip will probably not get that much attention

**Comment by tsujan** [comment]
OK. The problem will be fixed by hiding the tooltip on changing the directory. I already accepted this as a valid report.

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxqt/pcmanfm-qt/pull/1231. it'll be in 0.17.0

BTW, your installed version (0.15.0) is old. If 0.16.0 comes your distro, you could remove tooltips in Preferences.

Thanks for the report.

**Comment by ralf3u** [comment]
this issue proves that pcmanfm-qt is not keyboard-friendly designed; visit for example <a href="https://github.com/lxqt/pcmanfm-qt/issues/1228">#1228</a>, <a href="https://github.com/lxqt/pcmanfm-qt/issues/1234">#1234</a> and <a href="https://github.com/lxqt/pcmanfm-qt/issues/1235">#1235</a>
