### ISSUE TITLE
home-key does not work properly, part 2

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1234]
this is just for documentation:
in the report <a href="https://github.com/lxqt/pcmanfm-qt/issues/1169">#1169</a> it is mentioned that the problem also exists in Dolphin, so I reported the problem also on <a href="https://bugs.kde.org/show_bug.cgi?id=427871">bugs.kde.org</a>;
maybe this will have an impact on the default behavior of Qt's item views

**Comment by tsujan** [comment]
> in the report #1169 it is mentioned that the problem also exists in Dolphin

Who said it's a "problem"?! When you are at home, you don't go home.

If there is a problem, it's that some users don't want to learn or read explanations like https://github.com/lxqt/pcmanfm-qt/issues/1169#issuecomment-664177471.
