### ISSUE TITLE
possibility of dis-activating the popup-box (before menu bar will disappear)

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1235]
it would be good to have a checkbox in the popup-box before menu bar will disappear

##### Expected Behavior
there should be the possibility to dis-activate the popup-box

##### Current Behavior
popup-box always appears before menu bar will disappear

##### Possible Solution
in the popup-box there could be a checkbox, like: don't show this information again

independent of that, in my opinion there should be also this kind of text in the popup-box, so that the users know how to find quickly the menu: when menu bar is hidden, a menu symbol is located in the right up corner

##### Steps to Reproduce (for bugs)
press ctrl+m
press ctrl+m
press ctrl+m

##### Context
the frequently use of show/hide the menu bar makes the popup-box unpleasant after a while

##### System Information
*  Distribution & Version: Lubuntu 20.10
*  Kernel: 5.8.0-25-generic
*  Qt Version: 0.15.0
*  pcmanfm-qt version: 0.15.0

**Comment by tsujan** [comment]
Such a checkbox would be useful only if something happened frequently. If a user toggles the menu bar 10 times a day — or even once a day — the problem is not in the message box.
