### ISSUE TITLE
the rename process is not smooth; solved in Dolphin

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1239]
##### Steps to Reproduce
1. choose a directory where there are so many documents and files that the scrollbar apppears
2. press end
3. press F2
4. give an other name to the document by adding some letters at the end of the name
5. press enter

##### Expected Behavior
because just before to rename, the document is marked, I expect after pressing enter:
- the document is marked, and
- the document is in visible area (for a quick check, so without the need, to look for it again)

##### Current Behavior
- not the renamed document is marked but an other document is in focus;
in other words:
	a)	different document (visit also <a href="1135">#1135</a>), and
	b)	different style (instead of marked, it is in focus);
- after the rename, the very first file of the directory is shown top left (maybe it is due to a reload), so the renamed file is not in the visible area, because it is at the end of the list

so at the moment 3 behavior are confusing after a rename:
1) different document
2) different style
3) not visible

##### Possible Solution
all those 3 problems do not exist in Dolphin Version 19.12.3

##### System Information
* Distribution & Version: Lubuntu 20.10
* Kernel: 5.8.0-25-generic
* Qt Version: 0.15.0
* pcmanfm-qt version: 0.15.0

**Comment by tsujan** [comment]
> not the renamed document is marked but an other document is in focus;

Before reporting false problems, please get familiar with the app by checking its preferences.
