### ISSUE TITLE
smooth rename process should be default behavior; default behavior in Dolphin

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1240]
this issue is based on <a href="https://github.com/lxqt/pcmanfm-qt/issues/1239">#1239</a>;
renaming is a frequently used process, nearly a daily routine job, and that is why smooth rename process should be a default behavior

##### Expected Behavior
Preferences → Behavior → Select newly created files
should be activated by default to have a smooth rename process

##### Current Behavior
Preferences → Behavior → Select newly created files
is not activated

##### Possible Solution
smooth rename process should be a default behavior; it is default behavior in Dolphin Version 19.12.3

##### Context
the smooth rename process is a cool feature and quite impressive;
it is a pity to hide this feature in the preferences; it should work right away

normal users could be confused when the smooth rename process does not work by default;
they could be frustrated and disappointed by the software; this could cause them to turn away from the software because renaming is important;
normal users are used to have this feature by default behavior;
I think that many users don't know that it is available in the preferences;
I also think that only advanced users can imagine that "Select newly created files" has something to to with renaming (the evidence: this was also already a subject in <a href="https://github.com/lxqt/pcmanfm-qt/issues/1135">#1135</a>)

##### System Information
* Distribution & Version: Lubuntu 20.10
* Kernel: 5.8.0-25-generic
* Qt Version: 0.15.0
* pcmanfm-qt version: 0.15.0

**Comment by ralf3u** [comment]
to tsujan:
if the feature will not be activated by default, could you please notice all arguments (or at least some important arguments) here down with a good explication (also for beginners), so users can try to understand why it is not default behavior

**Comment by tsujan** [comment]
@ralf3u 
I appreciate it when someone wants to make the app better by reporting real bugs or requesting real features. Sadly, you don't do that; you make noise instead.
