### ISSUE TITLE
layout problem when F6 is pressed

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1242]
when F6 is pressed the symbol bar is moving upwards; this is disturbing

##### Expected Behavior
symbol bar and Side Pane should not move

##### Current Behavior
symbol bar is moving upwards;
issue appears also when menu bar is hidden;
issue appears also without Side Pane;
also Side Pane is moving upwards (maybe because the symbol bar is moving upwards)

##### Possible Solution
a) the symbol bar could have some kind of fixed height
b) trick: a transparent symbol in the symbol bar, so that the height will not change

##### Steps to Reproduce (for bugs)
press F3

##### System Information
Lubuntu 20.10; pcmanfm-qt version: 0.15.0

**Comment by ralf3u** [comment]
@tsujan:  Because this issue has no comment: Can't the issue not be fixed?

**Comment by tsujan** [comment]
> Can't the issue not be fixed?

There's no issue to fix. Also, read https://github.com/lxqt/pcmanfm-qt/issues/1250#issuecomment-732788866.

**Comment by ralf3u** [comment]
when F6 is pressed to split the screen, the toolbar and the side panel are still going upwards	

my 0.16.0 in my Lubuntu 21.04 is old, but I still don’t know how to install the latest version;
if the issue does not appear in 0.17.0 any more, then I’m sorry for this report

**Comment by tsujan** [comment]
As said above, there is no issue to fix. The layout changes and, depending on the widget style, sizes may also change.
