### ISSUE TITLE
xterm is used instead of user's set terminal

### ISSUE THREAD

**Issue by itaranto** [lxqt/pcmanfm-qt#1249]
PCManFM-Qt attempts to use `xterm` instead of the user's set terminal.

My current default text editor is Neovim:
```
$ xdg-mime query default text/plain
nvim.desktop
```

I can see from the logs: 
```
$ pcmanfm-qt
isPrimaryInstance
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
sh: line 0: exec: xterm: not found
```

My terminal is set to `alacritty`.

I'm attaching PCManFM-Qt's configuration as well the default `neovim.desktop` file:
[pcmanfm-qt.tar.gz](https://github.com/lxqt/pcmanfm-qt/files/5584495/pcmanfm-qt.tar.gz)

##### Expected Behavior
User's set terminal is used for applications with `Terminal=true`

##### Current Behavior
`xterm` is used for applications with `Terminal=true`

##### Steps to Reproduce (for bugs)
1. Install Neovim
3. Set the default terminal in _Preferences->Advanced_
3. Open a plain text file from _PCManFM-Qt_

##### System Information
* Distribution & Version: Arch Linux
* Kernel: 5.9.2-arch1-1
* Qt Version: 5.15.1-3
* libfm-qt Version: 0.15.1-3
* libqtxdg Version: Not installed 
* lxqt-build-tools Version: Not installed
* Package version:

**Comment by tsujan** [comment]
> My terminal is set to alacritty

No, it's set to "alacrity", which doesn't exist; hence launching xterm.

**Comment by itaranto** [comment]
You are right I made that a mistake the second time  I attempted to reproduce this.  
I changed to the correct value `alacritty` and it still tries to use `xterm`.

**Comment by itaranto** [comment]
Anyway, aside from the issue itself, it would be nice to have a better error message. If I set the terminal to `foobar` I would expect something like `'foobar' not found`.

**Comment by tsujan** [comment]
> I changed it to the correct value: alacritty and it still tries to use xterm.

Oh, this time it was my mistake. Alacritty isn't supported by libfm-qt yet; it will after https://github.com/lxqt/libfm-qt/pull/591 is merged.

For now, you could add these lines to `/usr/share/libfm-qt/terminals.list` as root and then restart pcmanfm-qt:

```

[alacritty]
open_arg=-e
noclose_arg=--hold -e
desktop_id=Alacritty.desktop
```

Please note that the file will be overwritten if you upgrade libfm-qt/pcmanfm-qt to 0.16.0; the Alacritty support will be added to 0.17.0 officially.

**Comment by itaranto** [comment]
> Oh, this time it was my mistake. Alacritty isn't supported by libfm-qt yet; it will after lxqt/libfm-qt#591 is merged.

Cool! Nice to know :)

>For now, you could add these lines to /usr/share/libfm-qt/terminals.list as root and then restart pcmanfm-qt
I'll do that. It seems to be better than my previous workaround which was editing nvim.desktop with: `Exec=alacritty -e nvim %F`.

Thanks!

**Comment by tsujan** [comment]
You're welcome.

BTW, I tried it here and it worked. I'm merging the PR. So, the Alacritty support will be in 0.16.1, which will be released soon.

**Comment by Mrfiregem** [comment]
Looking forward to it

**Comment by itaranto** [comment]
Hello again,

I'm using **pcmanfm-qt 0.17.0-1** and **libfm-qt 0.17.1-1** and it seems pcmanfm-qt still tries to open a terminal application (Neovim in this case) with xterm:

```
[N] ~ $ pcmanfm-qt
isPrimaryInstance
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
sh: line 1: exec: xterm: not found
...
```

The terminal is set to `alacritty` in pcmanfm-qt and I also see the `alacritty` entry in `/usr/share/libfm-qt/terminals.list`:

```
[alacritty]
open_arg=-e
noclose_arg=--hold -e
desktop_id=Alacritty.desktop
```

**Comment by itaranto** [comment]
Alright, could you give me some hints about how can I debug this further?

I'm sure plenty of people with an environment like mine will be able to reproduce it.

I'm using Arch Linux + Sway.

**Comment by tsujan** [comment]
> could you give me some hints about how can I debug this further?

This question is too general. Since there's no crash, there's no coredump for the user to attach a backtrace. You need to be familiar with C++ for examining the code.

> I'm sure plenty of people with an environment like mine will be able to reproduce it.

Good. Then they may be able to provide us with a step by step way of reproducing it.

> I'm using Arch Linux + Sway.

Neither is relevant.
