### ISSUE TITLE
open/save-dialog of some software: files and documents are mixed without separation

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1250]
open/save-dialog of some software: files and documents are mixed without separation

##### Expected Behavior
in open/save-dialog: when Name is pressed in the column header:
first come the files, then come the documents (or other way around), each in an alphabetical order (alphabetical order: top-bottom or bottom-top)

##### Current Behavior
files and documents are in an alphabetical order, but without separation

##### Possible Solution
in libreoffice: open/save-dialog is perfect, so this issue does not appear there

##### Steps to Reproduce (for bugs)
open firefox
press ctrl+O
in the column header: press Name 

##### Context
the problem appears not only in firefox, but also in other software, like geany and audacity

##### Annotation
I don't know if the open/save-dialog in some software is an issue that concerns pcmanfm-qt. If not, where should I post this issue?
Or maybe, I just missed a setting in the settings?

##### System Information
* Distribution & Version: Lubuntu 20.10
* Qt Version: 0.15.0
* pcmanfm-qt: 0.15.0

**Comment by tsujan** [comment]
You've mistaken GTK for Qt. Firefox doesn't use LXQt File Dialog. LXQt File Dialog is for Qt apps.

**Comment by tsujan** [comment]
@ralf3u 
I beg you! Please get familiar with basic terms and concepts before opening an issue! Always hesitate before doing it!

I've had to close so many reports by you and, believe me, it's BORING.

**Comment by ralf3u** [comment]
the solution and explication for GTK is here:
https://gitlab.gnome.org/GNOME/gtk/-/issues/3400
