### ISSUE TITLE
localization issue

### ISSUE THREAD

**Issue by mkkDr2010** [lxqt/pcmanfm-qt#1254]
Hello, 
I'm working on Bulgarian localization for lxqt. The core utilities are almost translated.  So far  lxqt -admin -config  -globalkeys -panel -nitificationd -openssh -policykit -runner -session and libfm-qt, liblxqt, qterminal, qtermwidget and pcmanfm-qt. I'am doing it with Qt linguist and Designer to find some missing tags in .ts files. In test system I notice a problem with the complete localization. 
 Instances of file manager from panel widgets and some applications (for example featherpad, qt creator, designer  linguist) escape the localization, but not in lx-image. 
The system is actual archlinux updated and latest source of  lxqt from git. 
Second question: where can upload the translated ts files. 
With regards

**Comment by tsujan** [comment]
> Second question: where can upload the translated ts files.

If you don't want to use Weblate, you'll need to make a PR (→ GitHub documentation) but working with Weblate is easier.

What was the first question? If you mean some translations aren't complete, translators are very welcome to complete them.

**Comment by stefonarch** [comment]
>  Second question: where can upload the translated ts files.

Translation are done  in https://translate.lxqt-project.org/

> Instances of file manager from panel widgets and some applications (for example featherpad, qt creator, designer linguist) escape the localization, but not in lx-image.

This I didn't understand. But as said, use weblate as link, and your translations will be fastly in git.

**Comment by tsujan** [comment]
> (for example featherpad, qt creator, designer linguist) 

Neither of them belongs to LXQt. LXQt can't translate qt creator, for example. You also need to install `qt5-translations`.

I close this but feel free to add comments; they'll be read.

**Comment by mkkDr2010** [comment]
[I thought that it is technical issue. Here examples: 
Screen-1 present lx-image with opened dialog open file. All items in window with instance of file manager are complete and correct translated. Note that lx-image is even not yet localized.
Screen-2 is file manager window opened from configuration menu of panel widget mainmenu. Here is only Close button correct localized. ]
![screen-1](https://user-images.githubusercontent.com/75447241/101087313-59aea280-35b2-11eb-851f-55e3c430ae95.jpg)
![screen-2](https://user-images.githubusercontent.com/75447241/101087318-5a473900-35b2-11eb-9b28-d6d46cc2c14e.jpg)

**Comment by stefonarch** [comment]
I see now. Opening file dialog  with ctrl+o from  lximage-qt or featherpad translations are present, opening from mainmenu settings dialog (for menu files), vlc or falkon not.

 In 0.14.1 only lximage-qt fle dialog provides translations.

**Comment by tsujan** [comment]
@stefonarch
Except for once, when I wanted to fix an issue in Qterminal, I compile LXQt sources without translations. So, please help me understand the problem:

You mean that, with the Italian localization and all Italian translations (`qt5-translations` included), LXQt file dialog is sometimes translated into Italian, sometimes not?

**Comment by stefonarch** [comment]
I tested in some hurry, but yes, looks like that, as described here. Afaik vlc is in qt now. The dialog windows looks the same, except for translations.

**Comment by tsujan** [comment]
I recompiled libfm-qt with its translations on another machine and saw this pattern: LXQt file dialog would be translated only if the app was based on libfm-qt. lximage-qt and lxqt-archiver are both based on libfm-qt and so, LXQt file dialog is translated with them. VLC and FeatherPad aren't.

We've made a basic mistake somewhere. The problem may be in `lxqt-qtplugin`, which replaces Qt's default file dialog with LXQt file dialog for all Qt apps. I'll investigate it and open an issue later.

@mkkDr2010, thanks for mentioning the problem!

**Comment by stefonarch** [comment]
> FeatherPad aren't.

Featherpad cltr+o opens translated dialog here.

**Comment by tsujan** [comment]
> Featherpad cltr+o opens translated dialog here.

It doesn't here, with `LANGUAGE=it fpad`. Only the file type row is translated and it isn't from LXQt file dialog.

**Comment by tsujan** [comment]
@stefonarch 
I found the issue and its fix. See https://github.com/lxqt/libfm-qt/issues/596. Will make a PR after some checks. The fix works here will all translations and all Qt apps.

**Comment by tsujan** [comment]
@stefonarch 
BTW, I'm sure you told about this problem when LXQt file dialog was made, years ago (I can't find your comment). I just assumed that it was fixed because you didn't mention it anymore.

**Comment by stefonarch** [comment]
I found an closed issue https://github.com/lxqt/lxqt/issues/1338, but I never noticed recently because I use the filemanager for opening files and hardly never cltr+o

Featherpad:
![featherpad](https://user-images.githubusercontent.com/10681413/101133479-1895ad00-3609-11eb-99c7-109f0140d8d6.jpg)

**Comment by tsujan** [comment]
> I found an closed issue...

Yes, that's it, plus you told about it in a comment.

Today, I just need a little time to test whether the fix is fine *without* translations too.

**Comment by tsujan** [comment]
The simple PR: https://github.com/lxqt/libfm-qt/pull/597
