### ISSUE TITLE
Desktop file information weird in detailed view

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1261]
A screen capture explains all:

![schermata-09-13-26](https://user-images.githubusercontent.com/10681413/102591008-a8f7e580-4111-11eb-96dd-4caf8470ce27.png)

##### Steps to Reproduce (for bugs)

1.  Open applications in pcmanfm-qt left panel
2.  Switch to "detailed view.

Not this big issue though.

**Comment by tsujan** [comment]
That's expected because they aren't real files.

`menu://` depends on menu-cache and should be rewritten (→ https://github.com/lxqt/libfm-qt/issues/417).

I close this because nothing can be done about it.
