### ISSUE TITLE
pcmanfm-qt slow opening folders with many files

### ISSUE THREAD

**Issue by tlhpray** [lxqt/pcmanfm-qt#127]
On hdd whenever I try to open folder with many files (opening photo folders or /bin /lib takes forever) I must wait for files several seconds. There isn't much change with thumbnails turned on or off so I think it's unrelated. Dolphin had the same problem but now it is the fastest file manager in this field (longest I have to wait on dolphin is 1 sec). I think natural sorting was the culprit then https://freininghaus.wordpress.com/2012/11/27/on-the-way-to-dolphin-2-2/ but asking dolphin devs will probably be fastest way in finding a solution. I am using latest git version on Arch Linux.

**Comment by PCMan** [comment]
It delays mime-type sniffing so initial load can be faster.
We did not do that. The gtk+ version of pcmanfm has partial support of it, but it's not yet ported to Qt.
This requires much work due to some limitations and bugs of Qt ListView widget.

**Comment by tsujan** [comment]
Related to https://github.com/lxde/pcmanfm-qt/issues/462.

**Comment by tsujan** [comment]
Please see https://github.com/lxqt/pcmanfm-qt/issues/462#issuecomment-458921464
