### ISSUE TITLE
pcmanfm-qt  after "Open as Root" action doesn't change home, config target location

### ISSUE THREAD

**Issue by tlhpray** [lxqt/pcmanfm-qt#128]
Problem with this is after I click Open as Root my config files in my /home/user directory change ownership to root as I open anything from pcmanfm-qt in this root state. Example:
1. start pcmanfm-qt and click Open as Root
2. click Open Terminal in Tool menu
3. close qterminal (my terminal choice)
4. /home/user/.config/qterminal.org/qterminal.ini owner is now root
same thing happens whenever I open files with any other application (notepadqq, kate, etc.) and this makes their config files unaccessible for user and program just start with defaults.  
I am using git version on Arch Linux, switch user command is gksu %s

**Comment by tsujan** [comment]
Not an issue for years.

There was a related bug in lxqt-sudo that was fixed months ago.
