### ISSUE TITLE
language pack breaks some shortcut for dutch

### ISSUE THREAD

**Issue by arjanarcheologie** [lxqt/pcmanfm-qt#1283]
I'm using a fresh install lubuntu 20.04.01 and Dutch language settings.
Shortcuts 'Del' [DELETE], 'up' [ALT+arrow up], 'back' [ALT+arrow left], 'forward' [ALT+arrow right] are not working. The corresponding menu items don't show shortcut keys. 

Removing the language pack (pcmanfm-qt-l10n), and logout-login, changes the menu into English and resolves the issue: the shortcut keys are working, and are shown in the menus.

So, there might be something wrong with the pack for the dutch settings. 
                                                                                                                                                                                          
Ubuntu 20.04.1 LTS
pcmanfm-qt      0.14.1-0ubuntu3 amd64   
pcmanfm-qt-l10n 0.14.1-0ubuntu3 all       
Locale, region: Nederland - Nederlands (nl_NL)

**Comment by tsujan** [comment]
0.14 isn't supported.

Also, see https://github.com/lxqt/pcmanfm-qt/issues/916 for the cause (bad translation).

**Comment by stefonarch** [comment]
Will have a look in the actual translations if it is fixed or not, could well be not.

**Comment by stefonarch** [comment]
Thanks @arjanarcheologie for reporting, DEL was marked for edit in Dutch  but we were not aware of the 3 others, some are broken in many other languages.
 I fixed it in nl and de. 

Donwloading pcmanfm-qt_nl.ts in some days, release it in qt5-linguist and copy the .qm file to ` /usr/share/pcmanfm-qt/translations/pcmanfm-qt could solve it.
`

**Comment by tsujan** [comment]
> Not sure how to contact translators about it,some are in GH some not.

We may need to wait for more reports and ask the reporters about the their localizations. Checking every shortcut for every localization is next to impossible.

**Comment by stefonarch** [comment]
> Checking every shortcut for every localization is next to impossible.

It's quite easy to see in weblate, just a [search in pcmanfm-qt](https://translate.lxqt-project.org/search/lxqt-desktop/pcmanfm-qt/?offset=1&q=alt%2Bup&sort_by=-priority%2Cposition&checksum=) for` Alt+Up` or `Alt+Right|Left` will display all.
Specially "minor" languages like dutch here do not accept any translations for Up or Right or Left. 

I'll wait but before the next release I'll just remove the wrong ones.

**Comment by stefonarch** [comment]
Just found out that `Alt+Home` is another one. Added screens and explanations in weblate for all.
"alt+home" should probably never be translated, in italian it displayes this (and was wrong too first):


![schermata-5-1-18:52](https://user-images.githubusercontent.com/10681413/103758964-48264380-5013-11eb-893c-33eb23a8299e.png)

![schermata-5-1-18:38](https://user-images.githubusercontent.com/10681413/103758967-49577080-5013-11eb-9feb-5ea03fa02dca.png)
