### ISSUE TITLE
pcmanfm-qt close by itself when xorg dpms suspend off.

### ISSUE THREAD

**Issue by queenmedley** [lxqt/pcmanfm-qt#1287]
I am not using xscreensaver, just xorg dpms.
It goes into "standbytime" and it's okay when it comes out.
But when it comes out after entering "suspendtime", "pcmanfm-qt closes by itself.
it has not happen to pcmanfm and other file manager, but only pcmanfm-qt.

os : archlinux, 
desktop : lxqt
pcmanfm-qt version : 0.16.0

**Comment by tsujan** [comment]
pcmanfm-qt has no relation to screensaver or dpms and it definitely doesn't close by itself.

Please follow the issue template and be as specific as possible when reporting a problem.
