### ISSUE TITLE
Impossible open file

### ISSUE THREAD

**Issue by TrueCat17** [lxqt/pcmanfm-qt#1294]
Impossible open file without mouse, if current directory contains only 1 file
On open directory, this file selected, but "not naturally" - <Enter> doesn't open it, key for context menu on keyboard disabled
But weird "Selection" exists, and keys Left/Right/Up/Down/Home/End/etc don't changes selection to normal
Work only selection Ctrl+A or name-filter

##### Expected Behavior

On open directory selected item must be selected normally

##### Current Behavior

On open directory first item has weird type of selection

##### Steps to Reproduce (for bugs)

1. Open directory with only 1 file
2. Press <Enter> - no result
3. Press Left/Right/etc - no result
4. Press key for context menu on keyboard - no result

##### System Information

* Distribution & Version: Debian Unstable
* Kernel: 5.10
* Qt Version: 5.15.2
* libfm-qt Version: 0.16
* libqtxdg Version:  - (?)
* lxqt-build-tools Version: ?
* Package version: ?

**Comment by tsujan** [comment]
`Space` selects the current item and `Ctrl+Space` deselects it everywhere in Qt.
