### ISSUE TITLE
Unmount button disappears on window close

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1295]
When accessing a samba share or a ftp folder the unmount icon right to the item name disappears when window is closed and reopened.

##### Expected Behavior

Button always visible and usable:

![schermata-20-1-21:58](https://user-images.githubusercontent.com/10681413/105233820-a4887780-5b6a-11eb-87b0-f2cbc5756781.png)

##### Current Behavior

No button after reopen window, unmount only by right click possible:

![schermata-20-1-21:51-01](https://user-images.githubusercontent.com/10681413/105233500-3774e200-5b6a-11eb-9ec8-1737a2834848.png)

##### Steps to Reproduce (for bugs)

1. Access samba share or ftp server
2. Close pcmanfm-qt window
3. Reopen it.

##### System Information

* Distribution & Version:debian, arch, git checkout

**Comment by tsujan** [comment]
Will check it.

**Comment by tsujan** [comment]
Yes, I can see it too. It'll happen only if all windows are closed and then a window is opened. The reason is simple: the code doesn't add the eject button in this case. I'm making a PR...
