### ISSUE TITLE
"Preserve settings for this folder" option does not work

### ISSUE THREAD

**Issue by ferronrsmith** [lxqt/pcmanfm-qt#1298]
##### Current Behavior

"Preserve settings for this folder" menu option does not work, at least not when it come to preserving the view. Each time I navigate into a folder then back out the view changes back to the default "icon view"

##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: ubuntu 21.04
* Kernel: 5.8.0-34-generic
* Qt Version: 
* libfm-qt Version:
* libqtxdg Version: 
* lxqt-build-tools Version: 
* Package version: 0.16.0

**Comment by ferronrsmith** [comment]
https://user-images.githubusercontent.com/159764/105759401-ce54ec00-5f26-11eb-8a96-9228425686a1.mp4

**Comment by tsujan** [comment]
Not reproducible. Your video shows these steps:

 1. Check the Preserve box.
 2. Change the view mode.
 3. Uncheck the Preserve box.
 4. Check it again.
 5. Go to a subfolder
 6. Go back again.
 7. See that the Preserve box isn't checked and the mode is reset. (Not true; see below.)
 8. … 


7 isn't true: the Preserve box is actually checked and the mode is changed.

The rest isn't relevant.

Please follow the template when reporting a bug. It's not my job to write a report for you.

**Comment by ferronrsmith** [comment]
As usual you close issues without actually addressing the problem. It's fine, I'll stop using this crappy software, freedom of choice exist. 

This has been a bug for more than a year and it's annoying.

**Comment by ferronrsmith** [comment]
It's clear from the video that the settings weren't preserved, but if it works for you then it ain't a bug for anybody else 👍🏾

**Comment by tsujan** [comment]
> This has been a bug...

We don't have telepathy. I described your video in a step-by-step way (did your job for you). It simply wasn't reproducible at step 7.

You may want to consult a magician instead.

**Comment by stefonarch** [comment]
Am I wrong or did you have more tabs of the same folder open? 
In this case it's possible to have in one tab the box checked and in the other not.

**Comment by tsujan** [comment]
@stefonarch 
Thanks for your comment! It isn't related to this report though (the folder the reporter is apparently concerned about is opened in only one tab). I'll test multiple tabs of the same folder with the Preserve checkbox and open an issue if I find one.

**Comment by ferronrsmith** [comment]
1. Check the Preserve box.
1. Change the view mode.
1. Go to a subfolder
1. Go back again.
1. See that the Preserve box isn't checked and the mode is reset. (Not true; see below.
1. Also the folder resets to the default view layout (icons)

**Comment by ferronrsmith** [comment]
Does matter if I have multiple tabs or 1 or 100. Settings should be preserved. The feature is not working. It's fine, I'll use something else. Thanks 👍🏾

**Comment by tsujan** [comment]
> 1. Check the Preserve box....

This is what actually happens in git:

 1. Check the Preserve box.
 2. Change the view mode.
 3. Go to a subfolder.
 4. Go back again.
 5. The preserve button *is* checked and the view mode is really preserved.

It should happen with 0.16.0 too because there's no commit related to it in git (but that's not the point).

**Comment by ferronrsmith** [comment]
Let's drop the issue. I know it doesn't work. I'm not going to waste another second trying to prove anything. I've already switched to a file manager that "preserve my settings" correctly. Thanks and have a wonderful day.

**Comment by tsujan** [comment]
You're free to use anything you like but that's beside the point.

BTW, Ubuntu Hirsute doesn't have 0.16.0. I searched for Ubuntu's pcmanfm-qt 0.16.0 to check if they've cherry-picked patches again but found nothing.

**Comment by ferronrsmith** [comment]
I built directly from the source. I was running bleeding edge. The fact is it doesn't work


Yet another attempt


https://user-images.githubusercontent.com/159764/105770458-9e611500-5f35-11eb-873c-3feb388c02df.mp4

**Comment by tsujan** [comment]
@ferronrsmith 

As I said clearly, it doesn't happen here. The mode is preserved.

Something may be wrong with your compilation.

**Comment by ferronrsmith** [comment]
👍🏾
