### ISSUE TITLE
Open multiple selected files with different extensions in the same window.

### ISSUE THREAD

**Issue by nudnyzjeb** [lxqt/pcmanfm-qt#1299]
##### Expected Behavior
Open multiple selected files that have different extensions in the same window.

##### Current Behavior
This #149 works fine when opening images/videos in sxiv/mpv, as long as files selected have the same extension. However, if you try selecting, for example, two files - a .mkv and a .mp4 and press enter, then it opens up two mpv windows instead of just one.

**Comment by tsujan** [comment]
The opening app determines how to open multiple files (or not to open them), not pcmanfm-qt. With your example, SMPlayer adds the mkv and mp4 files to its queue and plays them one after the other.

**Comment by nudnyzjeb** [comment]
Could someone check what happens if you select and open together a .jpg and a .png through pcmanfm-qt with default image viewer set to lximage-qt?
I was curious and checked how thunar, dolphin, nemo and nautilus behave. After i select an .mkv file together with an .mp4 file and press enter, dolphin, thunar and nemo launch mpv in the desired way - one single window with a two-element playlist. Nautilus (Files on Gn*me), however, does what pcmanfm-qt does.
This behaviour is also not limited to mpv. On my machine, opening .jpg + .png with default application (xdg-open) for image/png image/jpg set as either sxiv or lximage-qt results in two open windows.

**Comment by stefonarch** [comment]
> Could someone check what happens if you select and open together a .jpg and a .png through pcmanfm-qt with default image viewer set to lximage-qt?

It opens 2 windows, what else could it do? It's not a single instance program.
 2 *.pdf files open in 2 tabs in qpdfview  and 2 different video files open a playlist in VLC here.

**Comment by nudnyzjeb** [comment]
I want to reiterate two things:
1. The number of windows of an application (sxiv, feh, mpv, vlc) opened is only dictated by the number of mimetypes (as interpreted by gio) selected, e.g. 10 files of which 9 are video/mp4 and another is video/x-matroska will open two windows of mpv (provided mpv.desktop is the default)
2. Nemo and the gang work perfectly, though Gnome+Nautilus doesn't belong to the cool FMs club and in its behaviour is identical to pcmanfm-qt.

@stefonarch 
We must forget about lximage-qt then (I assumed that it worked that way, but it looks like not even Nemo can make lximage-qt open everything in one window.)

**Comment by tsujan** [comment]
This report had a valid point, that was described in an incorrect way and in terms of "windows" (not the reporter's fault — sometimes, it isn't easy to know where the problem is).

The real problem isn't related to the app's windows — that's determined by the app itself, as mentioned before — but to how libfm-qt launches files. I opened a report at https://github.com/lxqt/libfm-qt/issues/623 and will fix the issue soon

**Comment by tsujan** [comment]
The PR is here: https://github.com/lxqt/libfm-qt/pull/624. Unlike its appearance, its logic is simple.
