### ISSUE TITLE
Add menu-item to open mixed file selection with default apps

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#1301]
After https://github.com/lxqt/libfm-qt/pull/624, pcmanfm-qt could correctly open multiple files with different mimetypes by pressing `Enter`/`Return`. However, if the files are right clicked, the "Open With..." sub-menu will have only one item: "Other Applications". That item isn't very helpful because it leaves the user with only one poor choice for the launching app.

My suggestion is adding another menu-item, with "Default Applications" as its text, *when multiple files with different mimetypes are right clicked*, so that, if it's triggered, the selected files will be opened by their default apps, exactly like when `Enter` is pressed.

A screenshot:

![default_app](https://user-images.githubusercontent.com/981076/106632899-7e63ce00-6593-11eb-8be6-13699d50707b.png)

Dolphin has a similar menu-item, although at a different position.

Any objection to adding this menu-item?

**Comment by stefonarch** [comment]
> Any objection to adding this menu-item?

Not at all!

**Comment by tsujan** [comment]
Added in https://github.com/lxqt/libfm-qt/pull/625, which relies on the other PR.
