### ISSUE TITLE
Recognize ".tar.zst" as a file format you can extract

### ISSUE THREAD

**Issue by es20490446e** [lxqt/pcmanfm-qt#1304]
When you right click on a compressed file, pcmanfm allows you to extract it. Except for ".tar.zst".

**Comment by tsujan** [comment]
It isn't related to pcmanfm-qt but to the archive app that's used with it: it should support extracting `application/x-zstd-compressed-tar`. lxqt-archiver  and Arqiver both support it; so, `application/x-zstd-compressed-tar` can be added for them to libfm-qt's `archivers.list`.

**Comment by es20490446e** [comment]
I'm using file-roller.
