### ISSUE TITLE
ScrollLines=3 issue  in thumbnail view

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1308]
3 lines scroll is fine everywhere, but in folders with pictures, thumbnail view and 256x256 thumbnail size it can  lead to nasty behavior, depending on screen height.

##### Expected Behavior

Usable scroll with max size thumbnails 256x256
##### Current Behavior

Scroll is like PgDwn with 3 lines of pictures in a pcmanfm-qt window.
##### Possible Solution

Can be hard I think, making scroll lines depending on thumbnail size.
 
 
##### System Information

* Distribution & Version: all

**Comment by tsujan** [comment]
That's the correct behavior -- Qt's behavior -- and isn't limited to pcmanfm-qt. You can see it in all item-views

> it can lead to nasty behavior, depending on screen height.

I have lots of folders with big thumbnails and don't see any problem. Of course, if you make the window height too small, a single PgUp/Dn is too much but there's no usability issue: you have 2 good options: (1) use up/down arrows instead, or (2) press Shift and turn the mouse wheel one step inside the view.

**Comment by tsujan** [comment]
Wait a minute... I thought you were talking about 3-line scroll step (which can be configured in LXQt settings and is global) A second reading of your comment confused me a little ;)

PgUp/Dn doesn't scroll 3 items but a "page".

**Comment by tsujan** [comment]
Apparently unrelated to this (or, maybe, you saw it too) but found when I tested with a too small window height: https://github.com/lxqt/pcmanfm-qt/issues/1310
