### ISSUE TITLE
File/Copy Information

### ISSUE THREAD

**Issue by tenplus1** [lxqt/pcmanfm-qt#1314]
Would it be possible to have the file/copy requestor show proper information while copying files to and from, e.g. copying a 1gb file to usb flash drive fills requester up to 99% straight away and time left sits at 00:00, why show a window if it doesnt give relevant information.

**Comment by tsujan** [comment]
The info is provided by GLib/GIO; we just show it. How much delay a device may add (e.g. due to journaling or other tasks) is out of our control and GLib provides to info on it.
