### ISSUE TITLE
Change the long description of thumbnail limit in Preferences

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#1316]
It says, "Do not generate thumbnails for images..." but, after https://github.com/lxqt/libfm-qt/pull/634, the limit will be for all files that support thumbnails (images, videos, PDF,...), with a maximum of 1 GiB.

A better description could just be "No thumbnail for files greater than:".

This report is just a reminder.

**Comment by stefonarch** [comment]
1 GB for videos could be a little low?

**Comment by tsujan** [comment]
> 1 GB for videos could be a little low?

It can be changed to 2 GB. Is that enough?

**Comment by stefonarch** [comment]
I think so.

**Comment by tsujan** [comment]
OK. libfm-qt imposes no limitation — after all, the limit was ∞ before. We could just change the spin-box in pcmanfm-qt.
