### ISSUE TITLE
Support access time and change time

### ISSUE THREAD

**Issue by vanessa794h** [lxqt/pcmanfm-qt#1317]
Hi,

thank you for supporting creation time.

https://github.com/lxqt/pcmanfm-qt/commit/cf1a2caf162c8c80d03ab8e3f9c3b275caeeddee

Please add the same for access time (`atime`) and change time (`ctime`).

Then I can show all 4 timestamps on my Linux system just like under `stat` command.

**Comment by tsujan** [comment]
All of them are supported, plus deletion time.

**Comment by vanessa794h** [comment]
> All of them are supported, plus deletion time.

That is good also with nanoseconds exactly as in `stat` command?

**Comment by tsujan** [comment]
> also with nanoseconds exactly as in stat command?

You're kidding?!

>  If not can I create a report for support nanoseconds?

Please don't; otherwise, I'll have to close it.
