### ISSUE TITLE
Add delete action in Trash context menu

### ISSUE THREAD

**Issue by umuluto** [lxqt/pcmanfm-qt#1319]
Right now the only way I know is to select the files and use the Del key.

**Comment by tsujan** [comment]
Done in https://github.com/lxqt/libfm-qt/pull/635 — its icon is really "edit-delete", which is the same as "user-trash" in the icon set of this screenshot:

![delete](https://user-images.githubusercontent.com/981076/109389385-83613680-7921-11eb-8e10-829c8afea7e3.png)

**Comment by tsujan** [comment]
BTW, "Open" and "Open With..." should be removed for non-folder files in Trash — trashed files aren't for opening and can't be opened. Also, the "Compress" item is redundant (the other items in the above screenshot are custom actions). Will open an issue and make a PR for them.
