### ISSUE TITLE
enhancement of single click support

### ISSUE THREAD

**Issue by tlhpray** [lxqt/pcmanfm-qt#132]
Current single click solution is really clunky. Time delayed selection can mess up so many things and without it I must use keyboard for selection. The best way to do it right is dolphin way of adding on mouse hover neutral icon or space (should be much easier to implement than dolphin changing icons), preferably in upper left corner of file/directory, which should act as ctrl+click. This also makes single click much more reliable in no keyboard environment. I know I am basically asking for copy of dolphin function and it's probably not lightweight/simplest method in eyes of many but it's the best option for single click support and in my opinion the fastest way of handling files/directories.

On mouse hover something like this
![example](https://cloud.githubusercontent.com/assets/10777982/5985162/1daddc3a-a8df-11e4-841c-8e4c7fb7bb74.png)
.

**Comment by tsujan** [comment]
This seems like a good (old) idea to me.

**Comment by tsujan** [comment]
Tonight, this old report caught my attention again. Its implementation became possible with an elementary trick: https://www.dropbox.com/s/t74l65t6fwusamj/selection.mkv?dl=0

But it was so simple that I should test it for a while to see if any drawback is also possible ;)
