### ISSUE TITLE
Unresponsive Desktop when Trash contains a lot files

### ISSUE THREAD

**Issue by umuluto** [lxqt/pcmanfm-qt#1320]
##### Expected Behavior

Normal, responsive Desktop
##### Current Behavior

Everything works normally except that the Desktop is all black. I can launch and use apps, but when their windows is minimized, the desktop doesn't get redraw (maybe a compositor would help?). I think it is because the Trash tries to show the number of files inside (26000+ in my case) and take a while to respond. After a while the icons in Desktop show up but the wallpaper doesn't.

##### Steps to Reproduce (for bugs)

1. Put a lot of files in the Trash
2. Reboot

##### System Information

* Distribution & Version: Lubuntu 20.10
* Kernel: 5.8.0-44-generic
* Qt Version: 5.14.2
* Package version: 0.15.0-0ubuntu1

**Comment by tsujan** [comment]
Good point. I'll check if that can be caused by counting files in Trash and, if so, will set a limit (with a text like "Many items: or "> 1000 items") or...

**Comment by tsujan** [comment]
OK, I investigated it. A detailed explanation:

I tested with 28,500 files in Trash on a spinning disk. After the boot, it took about a minute for the desktop to appear but it appeared correctly (I tested several times).

However, it isn't limited to desktop: I disabled desktop, rebooted and just opened a single `pcmanfm-qt` window without the desktop module. It took the same time to show up.

Then I checked the codes of `pcmanfm-qt` and `libfm-qt`. First, `GIO/GVFS` apparently doesn't have an option to check the number and stop counting after reaching a limit. Therefore, counting should be finished. Second, the trash item count is done asynchronously in both `libfm-qt` and `pcmanfm-qt`, which is the correct approach. So, the code had no problem.

To make sure that it isn't our fault:

 1. I moved the count to a separate Qt thread in three different ways — one of which was by adding a "trash count job" inside `libfm-qt`'s core — but there was no change.
 2. At last, I tried Thunar and Nautilus with those 28,500 files in Trash and after a boot. They showed exactly the same behavior.

My conclusion is that this is a "problem" in `GVFS` (shared by Thunar, Nautilus and PCManFM-Qt). To avoid it, don't leave an HDD Trash with so many files in it before a reboot or shutdown — although, if you do, everything will work fine after the trash item count is finished.

**Comment by umuluto** [comment]
If it's not the files counting, it must be something else being done synchronously that the Desktop can't redraw itself in time, right? Can you take another look at this?

**Comment by tsujan** [comment]
> If it's not the files counting

Not by us.

> it must be something else being done synchronously

Yes, a synchronous enumeration is done by `GVFS` once it's called; we do it only asynchronously and with a low priority.

> Can you take another look at this?

If something totally new comes to my mind — checked everything in my 2-hour investigation — but Nautilus, Thunar, etc. show that, most probably, this is caused by `GVFS`.
