### ISSUE TITLE
"Open Terminal": terminator does not open with directory selected if another terminator is running

### ISSUE THREAD

**Issue by madmanxxx** [lxqt/pcmanfm-qt#1322]
##### Expected Behavior
Pressing F4 in PCManFM-Qt should open terminator with currently opened directory as working directory

##### Current Behavior
- If no terminator is running, the behaviour is as-expected.
- If another instance is already running which was **not** started by pressing F4, terminator will open with home directory, not the one opened in PCManFM-Qt
- If another instance is already running which was **started** by pressing F4, terminator will open with working dir from another terminator window, not the one opened in PCManFM-Qt

##### Possible Solution
Tried setting `/usr/bin/terminator --working-directory %s`, but that didn't work. Peeking the process tree showed that every new terminator window is actually a child of the first terminator process spawned.

##### Steps to Reproduce (for bugs)
1. Install terminator terminal emulator
2. Set it in PCManFM-Qt preferences (does not matter whether it is selected or its path is entered manually)
3. Open terminator, note its `cwd`
4. Browse to a directory different than the one above, press F4 and `cwd`.

##### Context
This is probably a duplicate of https://github.com/lxqt/pcmanfm-qt/issues/231
Also, I am almost certain this used to work until recently.

##### System Information
* Distribution & Version: Arch Linux, updated Jan 2021
* Kernel: 5.10.4-arch2-1
* Qt Version: 5.15.2
* libqtxdg Version: 3.6.0 
* Package version: 0.16.0-1

**Comment by tsujan** [comment]
Not reproducible -- not with git, at least.

**Comment by stefonarch** [comment]
Here too - works as expected.

**Comment by madmanxxx** [comment]
OK, upgrading terminator (2.0.1-1 -> 2.1.0-2) fixed the problem. Works with 0.16.0 and with git version.
