### ISSUE TITLE
Shortcuts for views (thumbnail view, detailed list view, ...)

### ISSUE THREAD

**Issue by nudnyzjeb** [lxqt/pcmanfm-qt#1324]
At the moment, there is no shortcut to change view mode aside from [ alt+v v <another key that's tied to the specific view mode> ], which is not ideal. It seems that there was an issue just like this one in 2017, but it was closed because iicons for switching view modes were introduced. But it would be extremely unfortunate if a fm as perfect with keyboard-only navigation as pcmanfm-qt does not get the feature i the title.

There needs to be a better shortcut for changing view mode. Interestingly, both alt+2 and ctrl+2 do the same thing - switch focus to the 2nd tab - even though these are both god-tier key combinations for shotcuts.

**Comment by tsujan** [comment]
> But it would be extremely unfortunate ...

That's an exaggeration.

I think I've explained why they have no shortcut but, since I don't have time to find the link:
 * There are toolbar buttons.
 * The view mode isn't something the user wants to change frequently when he/she works with keyboard inside one and the same folder.
 * There's no good shortcut.

**Comment by nudnyzjeb** [comment]
>There's no good shortcut.
But what about the alt+2 and ctrl+2.

**Comment by tsujan** [comment]
> But what about the alt+2

Used for tab switching.

> for example, thumbnails until you've reached your destination.

That's another topic. You could add a comment to https://github.com/lxqt/pcmanfm-qt/issues/799 but please read its 6-7 first comments.

**Comment by nudnyzjeb** [comment]
... and ctrl+2? It does the same thing alt+2 on my machine. It shouldn't.

**Comment by tsujan** [comment]
Likewise.

> It shouldn't.

It's for the user's convenience -- tab switching is much more practical/important that view switching.

**Comment by tsujan** [comment]
At some point -- maybe, after 0.17 -- I'll add a shortcut editor to pcmanfm-qt, so that the user could define his/her own shortcuts and, of course, take responsibility for the ambiguous ones.

**Comment by nudnyzjeb** [comment]
Keeping track of your open tabs is a good advice. Thanks!

> > But it would be extremely unfortunate ...
> 
> That's an exaggeration.
Mice are humanity's greatest foe since ancient times (Touchpads too), one should only resort to Mice when it's absolutely needed.
Pcmanfm-qt is one of the only fms with the filter thingie and one of the few fms that has separate bind for going backwards (alt+left) and going up in a directory tree (backspace).

**Comment by tsujan** [comment]
> Mice are humanity's greatest foe

I love those little creatures ;)

The original author and I have tried our best to make pcmanfm-qt comfortable for the keyboard-only use. There are several commits for that, old and new. Personally, I sometimes like to not use the mouse either.

I think the remaining issues will be solved when a shortcut editor is added. Thanks for the reminder!

**Comment by tsujan** [comment]
I opened https://github.com/lxqt/pcmanfm-qt/issues/1325
