### ISSUE TITLE
PCManFM should restore tabs for each split.

### ISSUE THREAD

**Issue by hetraeus** [lxqt/pcmanfm-qt#1329]
##### Expected Behavior
After a restart PCManFM should restore tabs for each split.

##### Current Behavior
After a restart PCManFM moves the tabs to the left panel.

##### Possible Solution
If the current behavior is intended maybe state it near the "Reopen last window tabs in a new window" setting. But it's odd that I see PCManFM in a state then it gets mixed after a restart. Maybe new tabs could be added directly on the left panel and the right should have only one.

##### Steps to Reproduce (for bugs)
* Open a clean PCManFM (no configuration).
* Browse the settings: Edit -> Preferences -> User Interface -> Check "Reopen last window tabs in a new window". "OK".
* Press F6 to open split panel. In the split panel on the right mousewheel click a directory. Now the right panel has two tabs while the left has one.
* Close PCManFM.
* Open PCManFM.
* Now PCManFM should restore both the left panel tabs and the right panel tabs.

Instead:
* Now the left panel has all the tabs while the right panel only tab path is reseted to the home directory.

##### Context
I'm trying to continue from what I left. I may have for example few download directories on a panel and few directory to organize content on the right and they should restore like the previous session.

##### System Information
* Distribution & Version: Arch Linux
* Kernel: 5.10.20-1-lts
* Qt Version: 5.15.2-5
* libfm-qt Version: 0.16.0-2
* libqtxdg Version: 3.6.0-2
* lxqt-build-tools Version: not installed
* Package version: 0.16.0-1

**Comment by tsujan** [comment]
> Now PCManFM should restore both the left panel tabs and the right panel tabs.

We accepts patches.
