### ISSUE TITLE
Right click menu goes out of screen on Wayland.

### ISSUE THREAD

**Issue by bernharl** [lxqt/pcmanfm-qt#1331]
##### Expected Behavior

I right click close to the bottom right. The menu detects this and opens to the upper left of my mouse instead of going out of the screen.

##### Current Behavior

The menu goes out of the screen.

##### Possible Solution

I think this is related to the fact that Wayland clients cannot know their absolute position. Therefore I think it would be beneficial to base the placement of the right click menu on the relative position of the mouse inside the client window instead. This is beneficial even for X11 as right now the menu overlaps with other windows and only turns the other way when close to the screen edge.

##### System Information

* Distribution & Version: Arch Linux, fully updated as of March the 7th 2021.
* Kernel: 5.11.2-arch
* Qt Version: 5.15.2
* libfm-qt Version: 0.16.0
* libqtxdg Version: Not installed
* lxqt-build-tools Version: Not installed
* Package version: 0.16.0

**Comment by tsujan** [comment]
Absolutely not related to pcmanfm-qt.

**Comment by bernharl** [comment]
Where is the handling of the placement of the right click menu done then? Should i report it to QT?

**Comment by tsujan** [comment]
> Should i report it to QT?

To the Wayland compositor you use.

**Comment by bernharl** [comment]
Firefox handles this just fine while running in Wayland, so I was pretty sure this wasn't and inherent problem with Sway. I could try asking about it there though :)

I am, however, convinced that this must be related to Wayland not giving applications their absolute position. This isn't a bug, but a feature of Wayland (the discussion on whether that is a good feature or not is another topic...)

**Comment by tsujan** [comment]
> so I was pretty sure this wasn't and inherent problem with Sway...

Not reproducible under Weston, Plasma-Wayland, Wayfire and, if I correctly remember, Enlightenment's Wayland session.

> This isn't a bug, but a feature of Wayland

Then you could enjoy it, instead of reporting it.

Anyway, since it has nothing to do with pcmanfm-qt or LXQt, here is not the place for discussing it.
