### ISSUE TITLE
In Trash, sorting on "deleted" is ordered lexically, not chronologically

### ISSUE THREAD

**Issue by LdBarthel** [lxqt/pcmanfm-qt#1332]
##### Expected Behavior

While viewing the Trash in detail view, click on "Deleted" to sort by the date deleted. The list should be sorted by date.

##### Current Behavior

The list is sorted lexically: 1/1/21, 1/31/21, 1/6/21, 12/25/20, 3/11/21

##### Possible Solution

Use the same sorting algorithm as for the Modified field, which does sort correctly.

##### Steps to Reproduce (for bugs)

1. Over a period of months, deleted files to the Trash
2. View the Trash folder
3. Change to Detailed List view
4. Click on Deleted, scroll through the list - the dates are not in chronological sequence

##### Context

I wanted to purge the oldest items in my trash, but leave the more recent items for a few more weeks for paranoia purposes. 

##### System Information

* Distribution & Version: Arch (last updated Feb 28)
* Kernel: 5.11.2-arch1-1
* Qt Version: 5.15.2-5
* libfm-qt Version: 0.16.0-2
* libqtxdg Version: 3.6.0-2
* lxqt-build-tools Version: 0.8.0-1 (current in Arch, but not installed)
* Package version:

**Comment by tsujan** [comment]
Thanks for reporting this! The deletion time may have not been added to the sorting code and so, the string sorting is used for it. I'll check the code and fix it if that's the case.

**Comment by tsujan** [comment]
Yes, that was the case and the fix is here: https://github.com/lxqt/libfm-qt/pull/651 (will be in 0.17.0 soon).
