### ISSUE TITLE
Cannot trash folders or files on other drives

### ISSUE THREAD

**Issue by LuxLucian** [lxqt/pcmanfm-qt#1336]
##### Expected Behavior
Files should be deleted or moved to trash.

##### Current Behavior
When trashing folders on the main drive ( / ), Pcmanfm-qt gives the error 'Trash portal failed on (folder path)" and does not touch the contents of that folder. Files not in a folder get moved to the trash as expected.
When trying to delete files on an automounted drive, the error "Failed to open (file path)" is given, and the file is not trashed or deleted. When trashing on an external drive the prompt to delete instead is shown, as expected.
Deleting folders and files work as expected. 
This occurs with the AUR version and the one in the community repo.

##### Steps to Reproduce (for bugs)
1. find a folder
2. try to trash it 

1. find a file on an automounted drive 
2.  try to trash it

##### System Information
I am running Wayland, and using the Wayfire DE. I don't know if Pcmanfm-qt supports Wayland, so this may be a Wayland specific bug.
* Distribution & Version: Arch Linux 
* Kernel: 5.11.7-arch1-1
* Qt Version: 5.15.2-5
* libfm-qt Version: 0.16.0.54.g920c7bd-1
* libqtxdg Version: 3.6.0-2
* lxqt-build-tools Version: 0.8.0.6.g17d975c-1
* Package version: 0.16.0.58.g2f27179-1

**Comment by tsujan** [comment]
Not reproducible, of course.

**Comment by tsujan** [comment]
>  I don't know if Pcmanfm-qt supports Wayland

pcmanfm-qt supports Wayland and can be used under Wayfire or any other Wayland session. Particularly, I'd used it with Wayfire when testing the latter.

For finding the cause of your problem, more info is needed.

**Comment by LuxLucian** [comment]
> > I don't know if Pcmanfm-qt supports Wayland
> 
> pcmanfm-qt supports Wayland and can be used under Wayfire or any other Wayland session. Particularly, I'd used it with Wayfire when testing the latter.
> 
> For finding the cause of your problem, more info is needed.

Do you have any idea what information should be given, or what I should look into to fix this issue?

**Comment by tsujan** [comment]
> Do you have any idea what information should be given, or what I should look into to fix this issue?

If you don't have GVFS packages, there should be no Trash in the first place. So, I don't know what the cause may be.

Double check that, after you upgraded libfm-qt to the latest git, you did the same thing for pcmanfm-qt.

**Comment by LuxLucian** [comment]
So I solved the issue by removing GTK_USE_PORTAL=1 from my /etc/environments. Setting this variable fixed this issue for another person however.

**Comment by tsujan** [comment]
`GTK_USE_PORTAL` has nothing to do with pcmanfm-qt or libfm-qt. LXQt doesn't use a single line of GTK code.

**Comment by tsujan** [comment]
I tried the latest git version of Wayfire and trash worked without problem, while I don't have `GTK_USE_PORTAL` (I won't try Wayfire again for a while because it has become extremely unstable; it made everything freeze).

Maybe `xdg-desktop-portal` does something that it shouldn't do. I don't have it here.

**Comment by LuxLucian** [comment]
Strange stuff. Trying to delete folders with nautilus or gio gave the same error, which was also solved by removing the GTK_USE_PORTAL. It could be that the env variable is messing with whatever is supposed to handle trashing folders. Thanks for the help.
