### ISSUE TITLE
Drop down menus for Owner and Group fields

### ISSUE THREAD

**Issue by tlhpray** [lxqt/pcmanfm-qt#134]
Drop down menus on ownership fields would really save some time if we don't remember user or group name. It will also completely negate any possible errors changing file(s) owner or group.

For normal users Owner should be grayed out and in Group menu there should be result of 'groups'
For root, Owner menu should have 'cut -d: -f1 /etc/passwd' and Group menu 'cut -d: -f1 /etc/group'

**Comment by tsujan** [comment]
Please follow https://github.com/lxqt/pcmanfm-qt/issues/886 -- it's fixed in a patch, yet to be merged.

**Comment by tsujan** [comment]
And if you want to see Owner/Group, use the detailed list view.
