### ISSUE TITLE
Add "Create Launcher" to Tools menu

### ISSUE THREAD

**Issue by Val6789** [lxqt/pcmanfm-qt#1340]
Currently one can create launchers (.desktop files) by right clicking on the desktop and sleecting the "create launcher" option in the context menu.

However, this is only possible on the desktop and not in the pcmanfm-qt windows.

##### Possible Solution
Add the option of creating .desktop files in any pcmanfm-qt window. This could be done by moving the "Create launcher" to the "Create new" submenu in the context menu as such:

![example](https://user-images.githubusercontent.com/11796016/113400973-f3d8f880-93a2-11eb-84c7-8ab24f6543ea.png)

##### Steps to Reproduce (for bugs)
1. Right click on any pcmanfm-qt window or use the file menu

##### System Information
* Package version: 0.16.0

**Comment by tsujan** [comment]
> However, this is only possible on the desktop and not in the pcmanfm-qt windows.

Not true. Drag and drop a menu item wherever you want.

> Add the option of creating .desktop files in any pcmanfm-qt window

Only Desktop is a special place. If you want shortcuts inside other folders, there are different ways (DND from main menu or copy-paste from Desktop). Cluttering the right click menu with redundant items isn't a good idea.

**Comment by tsujan** [comment]
There is an acceptable possibility: adding Create Launcher to the Tools menu of pcmanfm-qt *and not to the context menu*. A simple code refactoring will do it.

Reopening and changing the title....

**Comment by Val6789** [comment]
My proposal is to add the create launcher option to the "Create new" submenu. This way, it will not clutter the main context menu et imo it fits well with the rest of the file creation (new folder/now empty file) menu choices.

**Comment by tsujan** [comment]
> My proposal is to add the create launcher option to the "Create new" submenu

Yes, I know. There can be several template menu-items there; hence not cluttering it. But thanks for the general idea!

I implemented it here and will make a PR soon. I'd like to have it in 0.17 (which will be released soon) but should ask other LXQt members whether they have no objection.

**Comment by tsujan** [comment]
The PR: https://github.com/lxqt/pcmanfm-qt/pull/1341
