### ISSUE TITLE
Bash history filled by `change directory`

### ISSUE THREAD

**Issue by redtide** [lxqt/pcmanfm-qt#1348]
It seems that after navigating some directories I find the terminal history filled with
all CD commands I did by navigating using pcmanfm-qt.

##### Expected Behavior

It would be nice, if needed and as optional, to save the changed directories in
a different log, leaving the shell history only with the commands used from the terminal.

##### Current Behavior

See above.

##### Possible Solution

Not logging the changed directories or optionally save them by enabling the feature
in settings in a different log.

##### Steps to Reproduce (for bugs)

1. Open PCMandFM-Qt and enter some directories
2. Open the terminal and use the arrows to navigate history,
you find some if not all the changed directories from the file browser

##### Context

I never faced such behavior from any filemanager before, including PCManFM
itself which I use from many years (was GTK, now Qt using LXQt).

##### System Information

* Distribution & Version: Archlinux 5.11.11-arch1-1
* Kernel: SMP PREEMPT Tue, 30 Mar 2021
* Qt Version: 5.15.2
* libfm-qt Version: 0.16.0-2
* libqtxdg Version: 3.6.0
* lxqt-build-tools Version: 0.8.0
* Package version: 0.16.0

**Comment by stefonarch** [comment]
Not reproducible here with git sources. neither on debian neither on arch.
Opening qterminal by F4?
I also would remember such thing I guess.

You could try `HISTIGNORE='ll*:la*:cd*' in your ~/.bashrc (I disabled this line before testing).
`

**Comment by redtide** [comment]
So might be something wrong here then, It happened also yesterday making a test before to submit this issue, but now doesn't happens again. I only tried by closing other terminals, open PCMan and navigate and then open a terminal from lxpanel, not using F4. I'll let you know and eventually close this issue if I can't get some precise reproducible behavior. Intanto grazie per la dritta su `HISTIGNORE` :)

**Comment by tsujan** [comment]
The code of libfm-qt/pcmanfm-qt has nothing to do with bash history.

**Comment by redtide** [comment]
Sorry, I often use the file manager together with the editor and I have reported the wrong one. :(
