### ISSUE TITLE
[Feature Request] Different view mode for different directories

### ISSUE THREAD

**Issue by sujay1844** [lxqt/pcmanfm-qt#1349]
This may be a duplicate request. Or there may be a plugin for it.

##### Expected Behavior

It will be helpful if pcmanfm-qt could remember the view modes and sorting order of different directories.
Example: 
- ~/Pictures: Thumbnail view, Sorted in descending by date of creation
- ~/Downloads: Detailed view, Sorted in descending by modification date
- All other directories: Icon view, Sorted in ascending by Alphabetical order

##### Current Behavior

If I change the view mode in the settings, it changes for all folders.

##### System Information

* Distribution & Version: Arch Linux x86_64
* Kernel: 5.10.29-1-lts
* Qt Version: 5.15.2
* libfm-qt Version: 0.16.0-2
* libqtxdg Version: 3.6.0-2
* Package version: 0.16.0-1

**Comment by tsujan** [comment]
Implemented ages ago. View → Preserve Settings for This Folder.

**Comment by sujay1844** [comment]
oops srry my bad @tsujan

**Comment by tsujan** [comment]
That's OK.

My Trash is sorted by deletion time in the detailed list mode; my Download folder by modification time in the icon view mode; etc .Folder icons can also be changed.
