### ISSUE TITLE
Navigation history dropdown menu

### ISSUE THREAD

**Issue by redtide** [lxqt/pcmanfm-qt#1352]
In the GTK version of PCManFM the history navigation has a dropdown menu near the go back/forward buttons to view and access quickly the last 10 visited directories; should be nice having that feature on PCManFM-Qt as well other than right clicking the navigation buttons.
I'm now using PCManFM-Qt 0.16.0 on Archlinux.
![immagine](https://user-images.githubusercontent.com/1171962/114979924-f6038280-9e8b-11eb-988f-959ea3063ef9.png)

**Comment by tsujan** [comment]
Right click the back/forward button to see it.

**Comment by stefonarch** [comment]
> Right click the back/forward button to see it.

Also this needs to be in the wiki/help, didn't know.

**Comment by tsujan** [comment]
> Also this needs to be in the wiki/help, didn't know.

Will include it.

**Comment by redtide** [comment]
I edited the OP few minutes after, I saw the right click but a dropdown could be better (quick and avoid wrong clicks for some people)

**Comment by tsujan** [comment]
Right click is as valid as left click (we don't follow Gnome) and isn't different from it with regard to quickness. In addition, a compact GUI is always better than a cluttered one.
