### ISSUE TITLE
Localisation issue

### ISSUE THREAD

**Issue by Carmina16** [lxqt/pcmanfm-qt#1355]
https://github.com/lxqt/pcmanfm-qt/blob/4659da4f7428abb43326b794a9983006dbead3a3/pcmanfm/application.cpp#L314-L321

This method is obsolete. Please use the Qt5 method, which takes the `QLocale` object instead of the system locale name.

**Comment by tsujan** [comment]
> This method is obsolete

Which method is obsolete? If you mean `QTranslator::load()`, see https://doc.qt.io/qt-5/qtranslator.html#load

**Comment by Carmina16** [comment]
`bool QTranslator::load(const QLocale &locale,...` is more modern, and allow user to better customize UI languages. `bool QTranslator::load(const QString &filename,` is Qt4 legacy.

**Comment by tsujan** [comment]
"Obsolete" and "deprecated" have specific meanings in Qt; "more modern" doesn't. That method isn't marked as obsolete in [Qt6](https://doc-snapshots.qt.io/qt6-dev/qtranslator.html#load) either.
