### ISSUE TITLE
regex search thing doesn't care about capitalization of cyrillic script

### ISSUE THREAD

**Issue by nudnyzjeb** [lxqt/pcmanfm-qt#1358]
##### Current Behavior
For cyrillic script, the regex search thing (ctrl+f) doesn't make a case-insensitive search even if the checkbox is ticked.
There are two files in a directory: "гоРод.txt" and "goRod.txt". If I try and search for "горо" in the regex search thing (not the fuzzy search thing, that actually works fine with cyrillic), search returns nothing. If I try and search for "goro" with the same search settings, search returns the goRod.txt file as expected.  

##### System Information
latest package from arch repo

**Comment by tsujan** [comment]
We use GLib's regular expressions and its flags; see https://developer.gnome.org/glib/stable/glib-Perl-compatible-regular-expressions.html#GRegexCompileFlags. Apparently, `G_REGEX_CASELESS` doesn't recognize Cyrillic letter cases.

I leave this report open in case someone finds a workaround.

**Comment by nudnyzjeb** [comment]
upstream is scary

**Comment by tsujan** [comment]
I Found a working solution by distinguishing between searching in UTF-8 and non-UTF-8 strings. Will make a PR soon.

Long story short, GLib's case-insensitive regex search works with Cyrillic letters only when the search is explicitly limited to UTF-8 strings. That isn't a bug in GLib — it can be expected in regex searches everywhere — the GLib bug is related to a crash, that was avoided in the code. However, the way of avoiding it caused this trouble with Cyrillic *UTF-8* strings.

**Comment by tsujan** [comment]
BTW, Cyrillic was probably not alone. https://github.com/lxqt/libfm-qt/pull/715 should fix all cases of this problem.
