### ISSUE TITLE
Compact view may jump to first item after deleting last item

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1360]
##### Steps to Reproduce (for bugs)
- compact view
- very long list of document, so one need to scroll to be at the end of the list
- mark the third last document
- now press shift+delete and click on "Yes" to delete the document

##### Current Behavior
- top left document will be shown
- no document is marked
- the previous document is in focus

##### Expected Behavior
the previous document should be shown and marked

##### Possible Solution
in Dolphin 20.12.3 it does not jump to the top left file
disadvantage of Dolphin: the NEXT document is shown and marked
I would prefer when the PREVIOUS document is shown and marked

##### System Information
* Distribution & Version: Lubuntu 21.04
* pcmanfm-qt: 0.16.0

my 0.16.0 is old, but I still don’t know how to install the latest version
if the issue does not appear in 0.17.0 any more, then I’m sorry for this report

**Comment by tsujan** [comment]
Yes, it's a bug.

> the previous document should be shown and marked

The previous item should have focus (which already does) and made visible. No item should be selected.

**Comment by tsujan** [comment]
The bug wasn't in our code but in Qt. A workaround is included in this PR: https://github.com/lxqt/libfm-qt/pull/680

Thanks for reporting!
