### ISSUE TITLE
I would like Romanian to be added to Weblate so that I can start translating

### ISSUE THREAD

**Issue by iamthesenate1** [lxqt/pcmanfm-qt#1362]
The title

**Comment by stefonarch** [comment]
I upgraded your permissions, you should be able to add it where missing.

For some reason nobody reads the  message in weblate about contacting admins for that...

**Comment by iamthesenate1** [comment]
Thank You and sorry for not paying attention

**Comment by stefonarch** [comment]
Not your fault, it looks like the announcement has expired, will rewrite it.
