### ISSUE TITLE
[Feature Request] Make a new List-like mode (or adapt the current one) so that clicking outsde of the file or folder name doesn't select it

### ISSUE THREAD

**Issue by iamthesenate1** [lxqt/pcmanfm-qt#1364]
##### Expected Behavior

When right-clicking outside of the file/folder name you shouldn't select it but rather a menu should appear in wich there would be options to paste,create new, sorting,etc. 
##### Current Behavior

When right-clicking you select the file/folder which makesit very hard to paste a file, it pasteing in the selected folder instead of the folder you are in. 
##### Possible Solution

Make an new mode or adapt the current one
##### Context

[RANT] 
This issue is very annoying for someone who likes the list mode but hates to have to scroll down to find empty space so that he can paste a file in the respective folder not in a random folder that was selected.
With it`s many flaws, the Windows File Manager sadly is doing a better job about this than any linux file manager I know.
##### System Information
Any Version or Linux File Manager that I know for that matter.

**Comment by tsujan** [comment]
Preferences → Behavior → Browsing → Show folder context menu with Ctrl + right click

**Comment by iamthesenate1** [comment]
Still I would like an option for this to be permanent, not needing to press Ctrl

**Comment by iamthesenate1** [comment]
Still Thanks very much.
This info is very helpful.

**Comment by tsujan** [comment]
> Still I would like...

What's important is the functionality. Please understand that we can't code based on likes/dislikes; people may like/dislike opposite things.

**Comment by iamthesenate1** [comment]
Ok. Sorry If I offended you. I respect and understand the big effort to make such a great app. I just wanted to give my opinion about how I think it could be improved.

**Comment by tsujan** [comment]
No need to be sorry. Your taste is respected. It's just that tastes differ and so, they can't be a basis for coding. But functionality and reasonable minimalism can because they aren't subjective.

**Comment by iamthesenate1** [comment]
I understand.
