### ISSUE TITLE
Allow selecting Places panel background color

### ISSUE THREAD

**Issue by ssokolow** [lxqt/pcmanfm-qt#1367]
Feature Request: Allow users to select a more PCManFM-like background color for the places panel in PCManFM-Qt.

##### Expected Behavior

The Places panel should look like the list widget that it is, with a background that either matches the main widget it sits beside, or matches the lighter of the colors if the main widget is zebra-striped.

(If I could, I'd change this in the KDE Open/Save dialogs too, but at least their layout and font choices make it a bit easier to ignore.)

##### Current Behavior

The Places panel looks like a bunch of loose icons and text widgets sitting directly on the QWidget background fill.

##### Possible Solution

According to #696, this was an intentional change, but I consider it a massive regression, so maybe one of the following?

1. A checkbox for switching between the two behaviours (preferred)
2. A button which invokes QColorDialog to let the user pick an arbitrary color
3. If possible without crippling PCManFM-Qt, copy the rest of the design decisions which make the look work in KDE's dialogs.

##### Steps to Reproduce (for bugs)

1. Just open PCManFM-Qt

##### Context

Ever since I migrated back from LXDE to KDE, I've continued to use PCManFM because I just feel more comfortable with it than Dolphin.

However, I'm still on PCManFM (GTK+ 2.x) because of several look-and-feel regressions that leave me feeling vaguely uncomfortable if I look at PCManFM-Qt in isolation and jump out at me if I compare them side-by-side.

Here's a detailed exploration of *all* the usability regressions I've noticed, plus a comparison to the KDE dialogs you have stated your intent to harmonize it with.

![pcmanfm-qt-problems](https://user-images.githubusercontent.com/46915/116787494-d8d9d100-aa93-11eb-9133-422f7f39a732.png)

##### System Information

**NOTE:** I'm filing this despite being on Kubuntu LTS because it's a request to reconsider an intentional design change, not a bug.

* Distribution & Version: Kubuntu 20.04.2 LTS
* Kernel: 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Qt Version: 5.12.8
* libfm-qt Version: 0.14.1-12ubuntu3
* libqtxdg Version: 3.4.0-1build2
* lxqt-build-tools Version: 0.6.0-2ubuntu1
* Package version: 0.14.1-0ubuntu3

**Comment by tsujan** [comment]
As has been mentioned for tens of times, users' like/dislikes can't be a basis for coding. Moreover, we don't add this or that option just to satisfy a taste.

**Comment by ssokolow** [comment]
OK then, where do I submit the image to argue that PCManFM-Qt's middle-ground between PCManFM and KDE Open/Save dialogs is *objectively* worse and how much digging into HCI literature will I have to do  to convince of the objectivity of that claim?

**Comment by tsujan** [comment]
Please stop mistaking your preferences for objective facts and using words like "regression" arbitrarily. Talking about a real bug doesn't need a big image with long-winded comments.

Your aesthetic preferences are respected but not followed.

**Comment by ssokolow** [comment]
It's a proven fact that zebra striping improves a user's ability to follow a row from a short filename to the adjacent columns. PCManFM-Qt removed the zebra striping. That's an objective example from the diagram I drew.

**Comment by tsujan** [comment]
I know you have good intentions and appreciate that but please.... Most of what you consider as"problems" have already been discussed and one of your comments is about an outdated version.

The only valid feature request is the alternating colors for the list view. That's acceptable but should be agreed upon.

**Comment by ssokolow** [comment]
Fair, I suppose.

Is the excess right-side padding on the Eject icon the one that was fixed in a newer version?

**Comment by tsujan** [comment]
Yes.

**Comment by tsujan** [comment]
I opened https://github.com/lxqt/pcmanfm-qt/issues/1368

**Comment by ssokolow** [comment]
Ahh. That's a relief.

I'm curious what the discussion was around deciding to keep the separate Places and Bookmarks sections, but I can guess it was probably to do with it being too important to keep Devices high on the list and Home above them.

Anyway, I think we're both probably feeling a bit frustrated at those who have come before, so thanks for keeping a clear head.

I guess I'm now off to search up or hack together tooling for taking as much of the drudgework as possible out of re-applying a PCManFM-Qt patchset and making new builds as security updates arrive in the \*buntu repos for the un-patched version.

**Comment by tsujan** [comment]
You're very welcome to make reports about problems or feature requests — they'll be read and discussed — but please:
 * Make each report only about one problem/feature;
 * Don't report against an outdated version; and
 * Don't mistake taste for feature/problem.

What you called "zebra-striped" caught my attention because it was practical. That's a valid feature.

Patching an old version could easily create bad bugs that don't exist in the latest version. If you have at least Qt 5.12, libfm-qt+pcmanfm-qt 0.17 can be compiled against it but making installable packages is always preferable.

As for Ubuntu updates, yoi might want to ask it from Ubuntu.

**Comment by ssokolow** [comment]
> You're very welcome to make reports about problems or feature requests — they'll be read and discussed — but please:
>
> * Make each report only about one problem/feature;
> * Don't report against an outdated version; and
> * Don't mistake taste for feature/problem.
>
> What you called "zebra-striped" caught my attention because it was practical. That's a valid feature.

Perhaps, when I've finished catching up on backlogged stuff and can afford taking some time to install the newest sources in a VM and do my "don't report already-closed stuff" due diligence.

It'll be interesting to see where you draw the "this is taste" line, given that not-purely-aesthetic arguments can be made for things like the full-width tab bar too.

(Aside from granting more space for a larger number of tabs before scrolling kicks in (a problem I have, even with the GTK+ version's wider tab bar), it can be argued that putting the Places sidebar below the tab bar is a stronger reinforcement that the sidebar affects only the current tab.)

It's similar to how the GNOME HIG has forgotten that "Preferences" wasn't supposed to go in the "Edit" menu because the original conventions that established those menu names also established Edit as an intuitively "document-scoped" menu while "Preferences" is an "application-scoped" operation. That's one of the reasons KDE applications have a separate Settings menu and why things like LyX and Windows builds of Firefox with the menu bar un-hidden put application settings in the Tools menu.

> Patching an old version could easily create bad bugs that don't exist in the latest version. If you have at least Qt 5.12, libfm-qt+pcmanfm-qt 0.17 can be compiled against it but making installable packages is always preferable.
>
> As for Ubuntu updates, you might want to ask them from Ubuntu.

Actually, my intent is to stay on the GTK+ 2.x version of PCManFM until it's no longer offered... so I'll be on it until at least Kubuntu 22.04 LTS. (Aside from a libmtp bug that got introduced some time after Kubuntu 16.04 LTS and is still around in 20.04 LTS, it's comfortable and meets my needs.)

My interest in patching PCManFM-Qt *now* is purely about getting some practice so that, when the GTK+ 2.x version goes away, and fixes and features being discussed now have made it into what Lubuntu is packaging, it won't be too onerous to start writing and maintaining my own patches to apply whatever design decisions you've chosen not to accept.

**Comment by tsujan** [comment]
> It'll be interesting to see where you draw the "this is taste" line

It's simple: a practical feature doesn't need convincing (unless it's misunderstood — that sometimes happen) and a real bug is reproducible.

On the contrary, when something is just a matter of taste, you see long arguments and you can imagine someone else stating long counterarguments ;) — that may be desirable in the humanities but wastes time in coding.

**Comment by ssokolow** [comment]
Doesn't that definition run the risk of stumbling over situations where one person sees a practical benefit but others don't acknowledge the benefit and insist on arguing based on their personal taste instead?

(eg. The full-width tab bar allows me to fit an extra tab or two before the bar begins scrolling, but I can imagine plenty of arguments about that being too niche to unseat existing aesthetic preferences.)

**Comment by tsujan** [comment]
> Doesn't that definition run the risk of stumbling over situations where...

Yes. Rationally, some risk-taking is always needed for avoiding indecision.
