### ISSUE TITLE
Alternating row colors for list view?

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#1368]
It was suggested at https://github.com/lxqt/pcmanfm-qt/issues/1367 and seems acceptable to me but *without any option to add/remove it*. A Qt parameter can do it.

Is it acceptable to you too?

**Comment by ssokolow** [comment]
Also bear in mind that it's part of the KDE look that PCManFM-Qt seems to be moving toward with commits like  lxqt/libfm-qt@6803d32a9e904f55ccaa42540952e101b76d18bf, being something that both DolphinPart and the KDE Open/Save dialogs do.

**Comment by tsujan** [comment]
I saw no reason why it shouldn't be acceptable and made https://github.com/lxqt/libfm-qt/pull/685

**Comment by tsujan** [comment]
> it's part of the KDE look that PCManFM-Qt seems to be moving toward...

Just to be clear, pcmanfm-qt may incorporate useful features of some file managers but isn't moving toward any. It's good to use others' experiences if they're practical. However, some mistakes may also be copied repeatedly by various programs.

**Comment by ssokolow** [comment]
Fair in theory, but I'd argue that the whole flat design aesthetic is "mistakes may also be copied repeatedly by various programs".

For example, that commit I referenced removed a grouping cue and reduced the foreground-background contrast of the Places sidebar.

**Comment by tsujan** [comment]
> but I'd argue that the whole flat design aesthetic is...

And a counterargument may say the opposite. In these cases, the developers make the final decision.

**Comment by ssokolow** [comment]
[Flat UI Elements Attract Less Attention and Cause Uncertainty](https://www.nngroup.com/articles/flat-ui-less-attention-cause-uncertainty/) - Nielsen Norman Group

> * The average amount of time was significantly higher on the weak-signifier versions than the strong-signifier versions. On average participants spent 22% more time (i.e., slower task performance) looking at the pages with weak signifiers.
> * The average number of fixations was significantly higher on the weak-signifier versions than the strong-signifier versions. On average, people had 25% more fixations on the pages with weak signifiers.

While the test in question was for websites, rather than apps you use day-in, day-out, the point remains.

**Comment by tsujan** [comment]
Sorry, I don't participate in discussions that are endless by their very nature. They may be good in other areas but not in programming.

**Comment by ssokolow** [comment]
Endless how? You implied that both positions had equal validity, and I linked and excerpted a professionally-conducted HCI study that found significantly poorer user performance on sites using flat design.

**Comment by tsujan** [comment]
As someone used to say, "this isn't a democracy." We should *do* things in the limited free times we have (compare the lengths of my comments with those of yours). I think I've been clear and self-consistent from the start. If not, sorry!

**Comment by ssokolow** [comment]
From your definitions on #1367, I got the impression that you were open to having your aesthetic opinions changed by empirical evidence, so that's what I linked.
