### ISSUE TITLE
Files or folders in detailed list view do not get selected when typing with keyboard

### ISSUE THREAD

**Issue by drzisga** [lxqt/pcmanfm-qt#137]
As it is stated in the title, a file or a folder does not get selected when typing the first few letters of it with the keyboard. This only does not work in the "Detailed List" view mode, so I think it has something to do with the FolderViewListView class. It might even be an issue with the underlying QListView, since this [commit](https://qt.gitorious.org/qt/qt/commit/cd1a5d421d214005bbbbb57150df85b80cf0a973) from 4 years go seems to fix this issue, but I do not know if it has been merged.

**Comment by tsujan** [comment]
With filter-bar, this can't be an issue anymore. However, since other views has this (Qt) property, it's better to implement it for detailed list view too.

**Comment by agaida** [comment]
implemented and working

**Comment by tsujan** [comment]
@agaida It doesn't work for a long time. I forgot this one; will look into it.

**Comment by agaida** [comment]
hmm - i just tested it - works for me™

**Comment by tsujan** [comment]
I change my home to the detailed list view and type "d"; "Desktop" won't be selected but will just be made the current item. In other views, if I type "d", "Desktop" will be selected. Do you see a different behavior?

**Comment by tsujan** [comment]
OK, not selecting by typing is the default behavior of treeviews when they have "extended selection" (which means, multiple rows can be selected) and the detailed list view is so.

I still don't know if the default behavior can be changed easily -- I don't know why such a default is chosen either.

**Comment by agaida** [comment]
hmm - in the other views the filter appears auto-magically - in listview it must be activated

**Comment by tsujan** [comment]
Here, there's no difference between the detailed list view and other views regarding auto-filtering.

**Comment by agaida** [comment]
hmm - one should not activate settings per folder - if possible we should add a marker for ...

now all the things are filtered but not selected

**Comment by tsujan** [comment]
The reason is in Qt → `QTreeView::keyboardSearch`:
```c++
    if (index.isValid()) {
        QItemSelectionModel::SelectionFlags flags = (d->selectionMode == SingleSelection
                                                     ? QItemSelectionModel::SelectionFlags(
                                                         QItemSelectionModel::ClearAndSelect
                                                         |d->selectionBehaviorFlags())
                                                     : QItemSelectionModel::SelectionFlags(
                                                         QItemSelectionModel::NoUpdate));
        selectionModel()->setCurrentIndex(index, flags);
    }
```
Should `keyboardSearch` be rewritten or a simple trick will be found, I don't know yet.

**Comment by tsujan** [comment]
I love simple tricks: https://github.com/lxqt/libfm-qt/pull/287
