### ISSUE TITLE
Constantly hitting the new tab button instead of back

### ISSUE THREAD

**Issue by pushqrdx** [lxqt/pcmanfm-qt#1370]
##### Context
I constantly find myself hitting new tab button instead of back, i think that another place for the new tab button would improve usability

##### Possible Solution
perhaps utilizing the space on the right of the location bar is an option, it maybe in this order
back, forward, up, refresh, location bar, view settings, new tab button

**Comment by tsujan** [comment]
That's a personal problem.

**Comment by pushqrdx** [comment]
> That's a personal problem.

@tsujan having a button that opens a new tab just before a button that goes back _which most UIs on any system put on the far left as it goes.. left_ is just unnecessarily screwing with muscle memory for absolutely zero gain

**Comment by tsujan** [comment]
> ... is just unnecessarily screwing with muscle memory

The "muscle memory" of those who used PCManFM — the predecessor pf PCManFM-Qt — for several years should be different from yours.

**Comment by pushqrdx** [comment]
@tsujan and i completely understand this, and think that you should've probably replied with that instead, but can we get at least an option to move it? perhaps through reorderable tool buttons, but i understand if the intent is less customizability
