### ISSUE TITLE
Inconsistent context menu positioning when using wayland display positions

### ISSUE THREAD

**Issue by mikesbytes** [lxqt/pcmanfm-qt#1371]
##### Expected Behavior

Right click/context menus always show up in the right location

##### Current Behavior

When using monitor positioning in Wayland, context menus do not show up at the mouse cursor's position consistently. Sometimes it can make the menu unclickable by positioning the menu outside the window.

##### Possible Solution

There is information about this bug occuring with other programs in Sway WM. [Here](https://github.com/swaywm/sway/issues/3135#issuecomment-459217564) is a link to a comment with relevant info about the cause of this in Qt applications

To fix this, it will be necessary to find all instances where menus are used, and give them a parent widget and a position when using the popup function. If I have time in the next week or two I can try to put together a PR.

##### Steps to Reproduce (for bugs)

While there are probably other ways to reproduce this issue, here's how I experience it.

1. Use sway
2. Set up monitors side by side with the position parameters such that the primary monitor is not at 0,0
3. Open pcmanfm-qt
4. Right click stuff around the window, in my case it seems to be dependent on where on the window I'm clicking, some areas show the menu in the right spot and some do not.

##### Context

This makes pcmanfm mildly annoying to use in wayland, as I often have to screw around with the window positioning to be able to right click a file and actually access the menu.

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 5.12.1-zen2-1-zen
* Qt Version: 5.15.2-1
* libfm-qt Version: 0.17.1-1
* libqtxdg Version: 3.7.1-1
* lxqt-build-tools Version: 0.9.0-1
* Package version: 0.17.0-1

**Comment by tsujan** [comment]
pcmanfm-qt doesn't position its menus. The problem you see is a bug in the Wayland compositors you use.

**Comment by mikesbytes** [comment]
This is decidedly not a bug in the compositor. Read the thread that I linked, in fact it says to report this to any projects you find with that bug, and the recommendations on the Qt wayland porting page [here](https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes). I am working on a PR to fix this right now, although it will also require patching libfm-qt.

**Comment by tsujan** [comment]
Adding codes for positioning menus of a Qt app under a Wayland compositor is absolutely out of question. Either Wayland compositors need to do it correctly (as KWin-Wayland does, more or less — I recommend you try it and see for yourself) or Qt should do it somehow.

This mess belongs to Wayland and should be resolved by it. As we don't add X11-specific codes to apps like pcmanfm-qt, we don't add Wayland-specific ones either.

**Comment by mikesbytes** [comment]
This ball would most likely be in Qt's court, as the GTK variant of this bug was cause by the use of a deprecated function, but given their track record I doubt we'll see a drop in fix from them. I'm pretty sure using the wayland friendly method of context menu creation should be compatible with X, so it should not require any special case handling. I'll make sure whatever fix I come up with works fine with X, although worst case I can maintain a fork.

Also, this bug is not sway/wlroots specific, it is reproducible under any Wayland compositor when the top left monitor is not positioned at 0,0.

**Comment by tsujan** [comment]
> I'll make sure whatever fix I come up with works fine with X

That might be acceptable, provided that there's no side effect whatsoever.

However, contrary to what your report suggested. it is NOT a *bug* in pcmanfm-qt or any Qt app. Wayland is problematic by its very nature. It's the job of Qt to adapt itself to it if possible. Coders shouldn't need to add this or that workaround to compensate for Wayland drawbacks.

**Comment by mikesbytes** [comment]
I agree, this is something that Qt should have at least tried to make seamless, although given how Qt is designed making a solution that allows the old method to work without a dirty hack would be quite difficult, and given that their recommended fix is "change your code" I doubt they'll ever do anything about it.

As a sidenote, if anyone is looking for a temporary workaround, running pcmanfm-qt with xwayland by setting QT_QPA_PLATFORM=xcb appears to work

**Comment by tsujan** [comment]
BTW, for a very different reason, yesterday, I worked under Plasma-Wayland for a whole day. Under KDE, my file manager is pcmanfm-qt, not Dolphin. I also use FeatherPad as the text editor, QTerminal as the terminal emulator and lxqt-archiver as the archive manager. I had to tolerate several flaws of Plasma-Wayland before returning to the comfort of LXQt but, ironically, all of them were in Plasma or KDE apps, not in pcmanfm-qt, lxqt-archiver, FeatherPad or QTerminal.

**Comment by tsujan** [comment]
Apparently, this issue is fixed in Qt6. I can't reproduce it (under Wayfire) with Qt6-based LXQt file dialog (→ https://github.com/lxqt/libfm-qt/pull/778) called by Qt6-based FeatherPad, although it's present in Qt5-based file dialog.

In this screenshot, the left dialog is Qt5-based, while the right dialog is Qt6-based. Both are near the bottom of the screen:

![Qt6-vs-Qt5](https://user-images.githubusercontent.com/981076/190520381-41f3a1e4-f9a0-4d89-9178-5400954c738d.jpg)

**Comment by stefonarch** [comment]
As it is a similar issue I write here instead of opening another issue: 

When using split view under wayland the "copy | move | link|"  dialog opens in the original view besides the selected file(s) and not under the mouse cursor in the destination view. With some luck this is also worked around in Qt6 here?

**Comment by tsujan** [comment]
> When using split view under wayland the "copy | move | link" dialog opens in the original view

I've seen it. DND is terrible under Wayland and, in some cases, can result in crashes. Qt6 isn't better in this regard.

**Comment by tsujan** [comment]
Minutes ago, I did a simple DND inside pcmanfm-qt and Wayfire crashed! This shows that the DND problem isn't only in Qt.

I got tired of such issues and logged back into LXQt.

**Comment by tsujan** [comment]
Actually, the position of drop menu can be fixed under Wayland. It isn't related to Qt's DND bug(s). I'll make a PR.

The rule of thumb is: *For now, avoid DND between apps/windows under Wayland!*

Some DNDs may be safe, especially those inside the same window, but others may cause crashes, not only in the app but also in the Wayland compositor.

**Comment by stefonarch** [comment]
![screen_sab_08:44:43_](https://user-images.githubusercontent.com/10681413/190844534-f01f285d-1fce-46f3-ad1d-a2b6ce9ba6b2.png)

**Comment by tsujan** [comment]
@stefonarch 
Did you mean a problem with the above screenshot?

**Comment by stefonarch** [comment]
I thought it was self-explained sorry. No, just to show that the menu now isn't out of screen.

**Comment by tsujan** [comment]
Qt5 tooltips and menus can be off-screen with Wayland, but yes, Qt6 menus/tooltips are "fixed".
