### ISSUE TITLE
Slow on deleting folders

### ISSUE THREAD

**Issue by es20490446e** [lxqt/pcmanfm-qt#1375]
##### Expected Behavior
When deleting a folder, it to be instant. At least when the Trash is disabled.

##### Current Behavior
The more files a folder contains, the longer it takes.

##### Root cause
The file manager processes all the individual contents, instead of the folder.

##### Steps to Reproduce
1. Duplicate a big folder.
2. Delete it.

##### Context
I'm rather using the terminal for deleting big folders.

##### System Information
* Distribution: Manjaro Linux Stable (rolling, two weeks delay from edge)
* Package version: 0.17.0

**Comment by tsujan** [comment]
Sorry, I don't have time to repeat previous replies.

**Comment by es20490446e** [comment]
@tsujan I guess you mean this [conversation](https://github.com/lxqt/pcmanfm-qt/issues/538).

Sorry. About that this issue is minimal, or has nothing to do with pcmanfm code, I shall digress.

**Comment by tsujan** [comment]
> @tsujan I guess you mean this and that.

There were more, but yes.

**Comment by es20490446e** [comment]
I discovered that file copying was slowed down on my system due to having the storage encrypted under a CPU that doesn't support AES instructions.

So this small inefficiency in pcmanfm was highly exacerbated by that. After removing encryption operations that took a minute did in a second.

**Comment by tsujan** [comment]
> ...  After removing encryption operations that took a minute did in a second.

Good.

However, deleting nested folders with many files in them with GLib takes much longer than expected because files should be checked one by one and GLib/GVFS is very slow in that regard. Frankly, after https://github.com/lxqt/pcmanfm-qt/issues/462#issuecomment-753602825, I got disappointed and didn't try to find a workaround for deletion.
