### ISSUE TITLE
Dmesg indicates possible pcmanfm-qt bad behavior - - which results in a hung graphics subsystem

### ISSUE THREAD

**Issue by dabeegmon** [lxqt/pcmanfm-qt#1377]
##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### Context
  Something caused a graphics freeze - - - needs a reboot to clear 
  Come to the system and the graphics subsystem is frozen
   Before adding a 4k monitor and also doing the updates presented in Debian testing subsequently I was having system uptimes in multiple months (4 to 6). Presently have the 4k monitor unplugged. With it on I was using 1 to 3 x/day for reboots. With it off had about 3 weeks uptime to this graphics subsystem freeze with the included dmesg tail (most likely referring to the possible issue. 

##### System Information

* Distribution & Version:        Debian testing
* Kernel:        5.10.0-6-amd64
* Qt Version:   Using Qt version 5.14.2 in /usr/lib/x86_64-linux-gnu
* libfm-qt Version:  libfm-qt-l10n   0.16.0-3      libfm-qt6:amd64         0.14.1-12.2
* libqtxdg Version:    libqt5xdg3:amd64      3.4.0-1+b1 
* lxqt-build-tools Version:   not installed 
* Package version: 

`[Tue May 11 07:41:22 2021] traps: lxqt-globalkeys[1872] general protection fault ip:7efd223044a6 sp:7ffc014175e0 error:0 in libc-2.31.so[7efd222eb000+14b000]
[Tue May 11 07:41:24 2021] pcmanfm-qt[1871]: segfault at 30 ip 00007f038e86e925 sp 00007fff7ee3c700 error 4 in libQt5Core.so.5.14.2[7f038e65c000+2ef000]
[Tue May 11 07:41:24 2021] Code: 53 48 83 ec 28 8b 05 f2 ec 28 00 83 f8 ff 7c 16 0f b6 05 8e ec 28 00 84 c0 0f 84 c6 00 00 00 48 8d 0d 9f ec 28 00 4c 8d 71 30 <41> 8b 2e 41 89 ec 41 89 ef 41 81 e4 ff ff ff 00 41 81 e7 c0 ff ff`

Any further information needed please advise. 
(The included 'help' files serve more to confuse and obfuscate than assist in giving information.)

**Comment by tsujan** [comment]
libfm-qt 0.14.0 was outdated last year; I don't know what it can be called now.

**Comment by dabeegmon** [comment]
On Thu, May 13, 2021 at 7:11 PM tsujan ***@***.***> wrote:

> Closed #1377 <https://github.com/lxqt/pcmanfm-qt/issues/1377>.
>
>
> Are the Debian maintainers aware that this not very old version of lxqt
- - - 30 - - is throwing problems?

I would suggest that the code in version 30 be updated so that these kind
of problems are not happening - - - please and thank you.

Regards

**Comment by tsujan** [comment]
> I would suggest that the code in version 30 be updated so that these kind of problems are not happening

We don't have a version of 30 of anything and that kind of problem is related to the downstream.

**Comment by dabeegmon** [comment]
On Fri, May 14, 2021 at 8:06 AM tsujan ***@***.***> wrote:

> I would suggest that the code in version 30 be updated so that these kind
> of problems are not happening
>
> We don't have a version of 30 of anything and that kind of problem is
> related to the downstream.
>
>
> Hmmmmm - - - - seems like the expectation is that the user work from
git-hub and not use customary
OS tools.

Please advise

**Comment by tsujan** [comment]
@dabeegmon
I didn't understand a single word of your comment. What is "git-hub and not use customary" supposed to mean?!

**Comment by dabeegmon** [comment]
On Fri, May 14, 2021 at 8:59 AM tsujan ***@***.***> wrote:

> @dabeegmon <https://github.com/dabeegmon>
> I didn't understand a single word of your comment. What is "git-hub and
> not use customary" supposed to mean?!
>
>
> Ok - - - none of this is in my previous normal!
Git-hub - - - should read github.
Distros, like Debian, suggest to update tools using their system, apt in
this case.
Debian, even in testing or sid or experimental,  has any listing of lxqt
17.

So are you suggesting that I should be working directly from the github
repositories rather
than the distro?

Please advise

**Comment by tsujan** [comment]
> So are you suggesting that I should be working directly from the github repositories rather than the distro?

Not. The LXQt maintainers of your distro are responsible for providing you with the latest stable version of LXQt, which is 0.17 for now. If your distro doesn't have an up-to-date version, you could report the problem to its maintainers, not here.
