### ISSUE TITLE
Cannot connect to smb

### ISSUE THREAD

**Issue by myxo** [lxqt/pcmanfm-qt#1379]
Hello.

I am writing a minimal distro based on ubuntu-base 20.04 and running in some trouble with pcmanfm-qt. I can't connect to samba server

![2010](https://user-images.githubusercontent.com/2719353/119101427-a59aba00-ba21-11eb-9a06-c45e764ce23e.png)

I get pcmanfm-qt with `apt install lxqt --no-install-recommends`
Nautilus can connect to smb on the same image, so samba client should work fine.

Well this is not actually a bug report (if I install lxqt on full size ubuntu, it's works fine), more of a question of how can I find the real error? I assume "Operation is not supported" is some general error message? Is there some logging written by pcmanfm? Or can I turn it on somehow? Googling around "pcmanfm Operation is not supported" wasn't helpful. 

pcmanfm-qt version is 0.14.1

**Comment by tsujan** [comment]
First, 0.14.1 is outdated (read the issue template). Second, when you use `--no-install-recommends`, you're responsible for what you get. Third, ask Ubuntu questions from Ubuntu.

**Comment by myxo** [comment]
This is not an Ubuntu question. This is question "How can I troubleshoot problems with pcmanfm?"

**Comment by stefonarch** [comment]
Do you have gvfs-smb installed?

**Comment by myxo** [comment]
Not sure how to confirm that (Ubuntu does not have packet with this name).
gvfs and gvfs-backends packets are installed. Also I have /usr/lib/gvfs/gvfsd-smb binary.

**Comment by stefonarch** [comment]
> if I install lxqt on full size ubuntu, it's works fine)

So you have to find the missing packages,  check the recommended packages.
