### ISSUE TITLE
`dir-settings.conf` may contain lots of dead entries

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#1382]
`dir-settings.conf` is used by pcmanfm-qt for saving per-folder settings. If you delete/rename a folder, it's entry won't be removed from `dir-settings.conf`.

Too many dead entries may have a negative effect on the speed of reading/writing. I have no real proof because I use a patch that cleans that file on exiting but I don't think it's a good idea to leave dead entries inside it forever.

**Comment by stefonarch** [comment]
As I mentioned: there could be saved views for external resources (like usb backup disk, shared smb folders ecc) which could be preserved? It's maybe a rare case though.

**Comment by tsujan** [comment]
If the config file is cleared on exiting and if you customize a USB disk and disconnect it, its customization will remain intact until you exit the session (= exit pcmanfm-qt and its desktop). After exiting, its customization will be lost.

I'm not sure that an exception could be made for such cases but I'll look into it.

**Comment by tsujan** [comment]
As I mentioned elsewhere, there are 2 ways of customizing folders: (1) From a central config file, as pcmanfm-qt does it; or (2) by creating `.directory` files inside folders.

(1) has two advantages over (2): It works with root folders too and it doesn't create extra files inside folders. On the other hand, (2) has this advantage that, when it works (= when the folder is writable), it's permanent.

I think a compromise can be made: we can add an action for removing dead entries, instead of automatically removing them on exiting. Its text can read, "Remove Settings of Nonexistent Folders".

@stefonarch, what do you think?

**Comment by stefonarch** [comment]
Initially I thought of something like that, a button to click. 
"Exiting" means closing it's windows or also the desktop (logout or stop module)?

**Comment by tsujan** [comment]
> it's windows or also the desktop (logout or stop module)?

The desktop, not the window.

But I think users will complain about losing customization of usb folders and things like that if we clean the confg file on exiting. An action (with a prompt) seems a better solution because the user should take responsibility.

**Comment by stefonarch** [comment]
I agree, but where adding this action? In the same menu?

**Comment by tsujan** [comment]
To the new "Customized View Settings" submenu, after a separator.

**Comment by stefonarch** [comment]
Perfect :)
