### ISSUE TITLE
The positions and spacing of icons on the desktop get lost

### ISSUE THREAD

**Issue by Katarn** [lxqt/pcmanfm-qt#1391]
##### Expected Behavior
The desktop icons must remain in the same place and spacing where they were before the screen resolution and refresh rate was changed.

##### Current Behavior
After changing the screen resolution to another (with refresh rate), and then switching to the original resolution, the positions and spacing of the icons are lost. At the same time, if you kill the `pcmandm-qt` process and start it again without moving the icons, they are restored to their original places.

##### Possible Solution
First of all, do not change the spacing between the icons when changing the screen resolution and refresh rate.

Additionally (IMHO), it may make sense to remember the arrangement of icons for different screen resolutions separately - how it works in Windows. This will reduce the number of cases when icon positions are lost when changing the screen resolution (for various reasons - for example, testing a new video driver). For now, as I see in `~/.config/pcmanfm-qt/lxqt/desktop-items-0.conf`: icons are not tied to screen resolution.

##### Steps to Reproduce (for bugs)
1. Place icons from top to bottom in 1 or more rows on both sides of the screen - left and right.

![1](https://user-images.githubusercontent.com/6339978/121683849-9bbb2280-cac6-11eb-956a-c4bfe47c8f73.png)

2. Launch a game under Wine that switches the screen resolution and refresh rate (for example, NFS3 - my usual resolution is 1280x1024@75, the game switches it to 640x480@60). The screenshot above shows which icon I am launch, is are focused.

3. Exit the game.

![2](https://user-images.githubusercontent.com/6339978/121683873-a4abf400-cac6-11eb-8511-9811af961ed4.png)

In the screenshot above, you can see how the icons got lost. You can see that the icon with which I was launching went off-screen. In addition, the spacing between the icons has changed.

##### Context
I have a lot of icons on my desktop, I arrange them carefully. And I often run games. In games, switching screen resolutions is the rule rather than the exception. Almost always, the positions of the icons are lost. This creates a lot of pain.

I associate these problems with Wine, because this does not happen with native games (for example, [SuperTux](https://www.supertux.org/)), but I cannot argue that this is a fact, perhaps the bug is floating and applies to native games as well. It's just that with Wine I catch it regularly.

##### System Information
* Distribution & Version: Gentoo with latest updates
* Kernel: 5.4.97-gentoo
* Qt Version: 5.15.2
* libfm-qt Version: 0.17.1
* libqtxdg Version: 3.6.0
* lxqt-build-tools Version: 0.9.0
* Package version: 0.17.0

**Comment by tsujan** [comment]
No icon goes offscreen with KWin as the window manager. Of course, when the resolution is made smaller, the icons should be re-positioned inside the available space, which is smaller than before.

Please note that some WMs, like Openbox, have bugs with regard to changing the screen resolution and size. We can't do anything about them. Particularly, Openbox isn't developed anymore and its bugs will remain with it indefinitely.

**Comment by Katarn** [comment]
I am using Xfwm, do you think the problem might be with it? Can you write down what the problem might be? I will write issue in bug tracker for them, but I have no idea what to provide them with as evidence. They will just as well send me here, because it reproduces in pcmanfm-qt.

**Comment by Katarn** [comment]
I just discovered that if you move any of the icons, the spacing is restored back to the same as it was originally, and the icon that goes off-screen returns to its place.

Is it possible to somehow react to this? For example, when changing the screen geometry, execute the same code that is executed when moving icons.

**Comment by tsujan** [comment]
The code prevents items from going offscreen. As I said above, the rest is out of our control.

**Comment by Katarn** [comment]
> Additionally (IMHO), it may make sense to remember the arrangement of icons for different screen resolutions separately - how it works in Windows. This will reduce the number of cases when icon positions are lost when changing the screen resolution (for various reasons - for example, testing a new video driver). For now, as I see in `~/.config/pcmanfm-qt/lxqt/desktop-items-0.conf`: icons are not tied to screen resolution.

Interesting article, the author also came to the same conclusion and implemented it in KDE Plasma:
https://akselmo.dev/posts/plasma-desktop-icons-positioning-refactor/

https://invent.kde.org/plasma/plasma-desktop/-/merge_requests/2607/diffs#5e4bff0fe5ef04e842313078615e83d38901d4a2_948_984
