### ISSUE TITLE
An option to make desktop items sticky by default

### ISSUE THREAD

**Issue by Katarn** [lxqt/pcmanfm-qt#1392]
##### Expected Behavior
A new file in the `~/Desktop` directory, when it appears there, must immediately stored its position in the desktop icons configuration file.

##### Current Behavior
Now, if you create a new file in the `~/Desktop` directory, it appears on the desktop in an free place. And its position is not saved in the config file. If you move the icons that are in before of it, then the new file jumps to its place.

##### Possible Solution
I described it in the "Expected Behavior" section.

##### Steps to Reproduce (for bugs)
1. Place icons from top to bottom in 1 or more rows on both sides of the screen - left and right.

![1](https://user-images.githubusercontent.com/6339978/121687104-9eb81200-caca-11eb-9408-bac909c72e1d.png)

2. Create a new file in the `~/Desktop` directory.

![2](https://user-images.githubusercontent.com/6339978/121687356-ed65ac00-caca-11eb-9f7d-3ae80ef29536.png)

3. Move any icon before of this file to a different place.

![3](https://user-images.githubusercontent.com/6339978/121687447-08d0b700-cacb-11eb-9a0b-f88b730b5273.png)

4. As you can see in the screenshot above, the new file jumped to the place of the one that was moved in step 3.

##### Context
This behavior is confusing because the user expects the icons on the desktop to always be tied to where they originally appeared. Until they are manually moved to another desktop position.

##### System Information
* Distribution & Version: Gentoo with latest updates
* Kernel: 5.4.97-gentoo
* Qt Version: 5.15.2
* libfm-qt Version: 0.17.1
* libqtxdg Version: 3.6.0
* lxqt-build-tools Version: 0.9.0
* Package version: 0.17.0

**Comment by tsujan** [comment]
> ... must immediately stored its position in the desktop icons configuration file.

No. It's put at the first free position that's available. If you want to store its position, right click it and check "Stick to Current Position".

**Comment by Katarn** [comment]
My suggestion is to make this the default behavior. Possibly via a toggle checkbox in desktop settings.

Because it's strange: I save something to the desktop, after a month or two I move one of the icons... And then many others are rearranged in a completely incomprehensible sequence.

**Comment by tsujan** [comment]
> My suggestion is to make this the default behavior.

Acceptable as an option, with the default being the current behavior.

Changed the title.

**Comment by tsujan** [comment]
> And then many others are rearranged in a completely incomprehensible sequence.

BTW, their arrangement follows a rule; it isn't random, although the user may not see the rule. However, that isn't related to our goal here.

**Comment by tsujan** [comment]
The implementation is finished here. Will make a PR after testing it for a while and, of course, after https://github.com/lxqt/pcmanfm-qt/pull/1396 is merged.

When all files are sticky, I also:
 * Removed the menu item "Stick to Current Position"; and
 * Made new files *that are created from the context menu* stick to the right click positions.

A new file that isn't created from the context menu goes to the first empty space and sticks to it.

**Comment by tsujan** [comment]
The PR is here: https://github.com/lxqt/pcmanfm-qt/pull/1408

It needs the latest git `libfm-qt`. The new option is in `Desktop Preferences` → `General` → `Make all items stick to their positions`.

On a side note, the project of creating items at right clicked positions was a failure. What I'd done in my experiments had a side effect. `libfm-qt` has no way of making it possible because files are created independently of the view.

**Comment by probonopd** [comment]
Can this also be done for the icons in windows, not just for the icons on the desktop?

**Comment by tsujan** [comment]
> Can this also be done for the icons in windows, not just for the icons on the desktop?

In our (LXQt's) programs, absolutely not. But it's theoretically possible: one can make enormous changes to `libfm-qt` or write another program from scratch to achieve it.

**Comment by probonopd** [comment]
> In our (LXQt's) programs, absolutely not. 

Why? It would be nice if the items inside "icon view" windows would remember their coordinates.

>  One can make enormous changes to libfm-qt or write another program from scratch to achieve it.

Have you seen "Spatial mode" in [Filer](https://github.com/helloSystem/Filer/) yet? ;-)

**Comment by tsujan** [comment]
> Why?

I mentioned the reason in the second sentence of my comment ;)
