### ISSUE TITLE
Don't save/read custom positions of desktop items constantly

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#1394]
pcmanfm-qt reads its window and custom folders settings on starting and saves them on exiting. That's good because each writing/reading operation has a cost.

But the custom positions of desktop items are saved and read whenever sticky items are removed, created, moved or dropped. That may not be a problem in itself because those operations aren't performed constantly.

However, if we want to add an option for making all items sticky (see https://github.com/lxqt/pcmanfm-qt/issues/1392), the removal or addition of **any** desktop item will require writing to the config file and reading from it, which won't be acceptable.

Therefore, IMO, it's better to change the code structure so that custom positions are remembered during a session without being saved to the disk and are saved only when the application exits.

If there's no objection, I have a patch.

**Comment by Katarn** [comment]
As another idea, a [debouncing](https://www.freecodecamp.org/news/javascript-debounce-example/) technique can be proposed. Save settings once a 10 seconds after they were last changed.

**Comment by tsujan** [comment]
> Save settings once a 10 seconds after they were last changed

There's no need to that. Custom positions aren't different from other settings, which are already saved when the app is about to exit.

All this is only for implementing https://github.com/lxqt/pcmanfm-qt/issues/1392; the implementation will be a piece of cake with it. As a byproduct, it'll also improve performance with slow spinning drives (although most users don't have them nowadays).
