### ISSUE TITLE
Inconsistent choose of terminal for cli-based utilities

### ISSUE THREAD

**Issue by pepper-jelly** [lxqt/pcmanfm-qt#1399]
##### Current Behavior
Reading #1249 I can confirm opening text file with Enter or Open(right click menu) launches xterm. But "Open With..." launches alacritty. 

##### System Information

Distribution: Artix Linux
PCManFM-Qt 0.17.0
Qt Version: 5.15.2+kde+r196-1
libfm-qt Version: 0.17.1-1

**Comment by tsujan** [comment]
Confirming the discrepancy between `Enter` and `Open With...` in this case.

It isn't related to alacritty or xterm though. Here, when I give `text/plain` to `nvim.desktop`, pressing `Enter` opens a selected text file with Konsole, while `Open With...` opens it with QTerminal, which is the default terminal.

Thanks for the report!

**Comment by tsujan** [comment]
This is related to GLib's hard-coded terminal list (see https://github.com/lxqt/libfm-qt/pull/310). The workaround of that commit may solve the problem but I should first see whether there's no side effect...

**Comment by tsujan** [comment]
The workaround is here: https://github.com/lxqt/libfm-qt/pull/694

I saw no side effect but more and longer tests are needed.
