### ISSUE TITLE
Pcmanfm-qt freeze at opening "Applications".

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1401]
Fresh compilation on debian bullseye, removed lxqt and compiled all (correct order, no missing dependencies). 
Not sure if related but both xfwm4 config tools are missing in the menu (only those, the rest is ok).
The window just freezes and the WM notifies it asking to kill it. 
Desktop is not affected, no message in terminal window.
Tested on my old laptop and it's the same there, I didn't notice before.

##### Expected Behavior

It opens application overview
##### Current Behavior

It freezes.

##### System Information

* Distribution & Version: debian bullseye, both 64/32 bit, latest git
* Qt Version: 5.15.2

**Comment by tsujan** [comment]
The same here. I have no idea what causes it.

**Comment by tsujan** [comment]
Found the cause :) it's the new recursive customization. Should see why it makes Applications hang...

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxqt/pcmanfm-qt/pull/1402

If you didn't find it, I'd never encounter it because I don't use Applications.

`menu://applications/` doesn't obey recursive customization because it isn't a real folder. Later I might try to enforce recursive customization on it but, for now, let's not have a hang :)

**Comment by stefonarch** [comment]
Just tested on arch, same. I'd never found it too, it was just that I didn't find xfwm4 configs anymore in the menu, and it was installed, so I wanted to see the .desktop files there.

Will test the fix now.

**Comment by stefonarch** [comment]
Looks working fine, included customization.

**Comment by tsujan** [comment]
Thanks!
