### ISSUE TITLE
PCManFM-Qt doesn't minimize when pressing the "show desktop" button

### ISSUE THREAD

**Issue by iamthesenate1** [lxqt/pcmanfm-qt#1411]
##### Expected Behavior 

It should minimize too, so that the desktop is shown.
##### Current Behavior

It doesn't.

##### Steps to Reproduce (for bugs)

1. Have PCManFM-Qt open.
2. Press the "show desktop" button.

##### System Information

* Distribution & Version: Arch Linux, LXQt-git from the archlinuxcn repo.
* Kernel: 5.13
* Qt Version: 5.15.2
* libfm-qt Version: git
* libqtxdg Version: git
* lxqt-build-tools Version: git
* Package version: git

**Comment by stefonarch** [comment]
Not reproducible, using git version on 2 machines (arch|debian).
Probably due some compiling errors?

**Comment by iamthesenate1** [comment]
No, installed from the archlinuxcn repo

**Comment by stefonarch** [comment]
So this should be reported to the maintainers https://wiki.archlinux.org/title/Unofficial_user_repositories#archlinuxcn.
Make sure that you have no mixed installation, so everything should be from this repo.

**Comment by iamthesenate1** [comment]
This might not be a packaging problem or pcmanfm-qt's, but because of my WM (KwinFT)

**Comment by iamthesenate1** [comment]
Can confirm. Openbox works fine.

**Comment by tsujan** [comment]
@iamthesenate1 
Minimizing windows and showing Desktop is the job of WM; it isn't related to pcmanfm-qt or other apps.

Some WMs may see that LXQt's Desktop is drawn by pcmanfm-qt and treat all its windows as "desktop". KWin has that bug. There may be a workaround for KWin because it has so many settings but I'm not sure.

**Comment by iamthesenate1** [comment]
> @iamthesenate1
> Minimizing windows and showing Desktop is the job of WM; it isn't related to pcmanfm-qt or other apps.
> 
> Some WMs may see that LXQt's Desktop is drawn by pcmanfm-qt and treat all its windows as "desktop". KWin has that bug. There may be a workaround for KWin because it has so many settings but I'm not sure.

I understand now. Thanks for the information.

**Comment by antis81** [comment]
@tsujan It's a bug :lady_beetle: in pcmanfm-qt (and it can reproduced)!

Basically openbox cannot handle a virtual desktop well. So `pcmanfm-qt --desktop` steps in and provides the functionality of a desktop manager. This isn't a problem with KWin(FT). However `systemsettings` package depends on `plasma-workspace` - a second desktop manager :tada:. Now we have 2 desktop managers and the responsibility is unclear! :boom:

Currently the only way to resolve this is to uninstall `systemsettings` and configure everything(!) KDE related manually via config files!

**Comment by tsujan** [comment]
> It's a bug lady_beetle in pcmanfm-qt

No, it isn't a bug in pcmanfm-qt. Its KWin's job to recognize what window has `_NET_WM_WINDOW_TYPE_DESKTOP` in its X11 window property `NET_WM_WINDOW_TYPE` and what doesn't. Openbox distinguishes between them. We set that property for the desktop by adding the attribute `Qt::WA_X11NetWmWindowTypeDesktop`.

> See KCM discussion

Not relevant to this.

**Comment by antis81** [comment]
@tsujan Why does it work when starting pcmanfm-qt without the `--desktop` option? (see `/etc/xdg/autostart/lxqt-desktop.desktop`)

**Comment by tsujan** [comment]
> Why does it work when starting pcmanfm-qt without the --desktop option? 

Because KWin doesn't mistake it with desktop anymore. Not distinguishing between windows that have the above-mentioned X11 property and those that don't, KWin sees that property in the desktop and then treats all pcmanfm-qt windows as if they were all "desktops". Openbox doesn't make that mistake.

**Comment by antis81** [comment]
@tsujan Okay since I haven't found anything in that direction in KDE's bug tracker, I will file a bug there (10 year old account surprisingly still works - wee :tada:!)

**Comment by tsujan** [comment]
That's a good idea.

**Comment by antis81** [comment]
For reference: https://bugs.kde.org/show_bug.cgi?id=442044

**Comment by antis81** [comment]
@tsujan Finally I understand the full problem! We can actually solve this by using smart-pointers instead of parenting the QMainWindow to the (single) pcmanfm QApplication instance (works also on openbox)!

Would you provide the dbus call please so I can debug it (e.g. map a shortcut)?

**Comment by stefonarch** [comment]
> (works also on openbox)!

make sure it works also with xfwm4

**Comment by antis81** [comment]
@stefonarch This is going to be WM agnostic -> works with any WM! :smiley_cat:

**Comment by tsujan** [comment]
@antis81 
I don't understand what you're talking about. pcmanfm-qt is a single-instance app. We don't change that just because KWin can't handle it in this special case.

**Comment by tsujan** [comment]
Also see https://github.com/lxqt/lxqt-panel/issues/1477 (especially, https://github.com/lxqt/lxqt-panel/issues/1477#issuecomment-906518898). If it doesn't exist for you, you need a more complete KDE installation.

**Comment by antis81** [comment]
@stefonarch This will also work in xfwm4 (it will work in any WM practically!)

@tsujan Do you understand how Qt's "garbage collection" works (QObject parenting)? (I have written similar architectures before and it can solve quite some problems here.) **In the end we both want to stay independent from KDE don't we?**

Draft:

```c++

// file: libfm-qt/filedialog.cpp
namespace Fm {

QList<QWidget*> floatingWindows;

constexpr QWidget* parentWindow(QWidget* parent, QWidget* thiz) {
    if (parent->testAttribute(Qt::WA_X11NetWmWindowTypeDesktop)) {
        floatingWindows << thiz;
        return nullptr;
    }

    return parent;
}


FileDialog::FileDialog(QWidget* parent, FilePath path) :
    QDialog(parentWindow(parent, this)),
//…
{
     //…
}

FileDialog::~FileDialog() {
    floatingWindows.removeAll(this);
    //…
}

}
```

Note: As a QDialog is also a window this should work right away! For floating QWidget's we might wrap that into a `QMainWindow()` or `QDialog()`.

Are we good now? :heart: :slightly_smiling_face:

**Comment by antis81** [comment]
@tsujan Even the assumption of NET_WM flags is wrong! Actually PCManFM windows are plain, unparented QMainWindow's. I also had a look into kwin's code. Actually they do cycle windows (search for "mainclients"). However somehow their "transient" logic filters those out. Maybe I can create a little test application simulating that.

**Comment by antis81** [comment]
FYI: Wrote a little [test application](https://gitlab.com/antis81/kwindesktopwindow) that cleanly reproduces this for KDE!

**Comment by antis81** [comment]
@tsujan We have actually located the bug -> https://invent.kde.org/plasma/kwin/-/blob/master/src/layers.cpp#L736

The `belongsToDesktop` function cycles all of an application's "top-level" windows and as soon as one of those has the `_NET_WM_WINDOW_TYPE_DESKTOP` makes the false assumption, that every window belongs to the desktop. Now for the fixing… :coffee: :slightly_smiling_face:

**Comment by tsujan** [comment]
Very good. Hopefully, it'll be fixed in the next version.

**Comment by antis81** [comment]
@tsujan https://invent.kde.org/plasma/kwin/-/merge_requests/1441

**Comment by tsujan** [comment]
Well done.

**Comment by antis81** [comment]
Not sure if it will work with plasma's "panel" (couldn't find the code). It likely doesn't set one of those flags (LXQt uses `Qt::WA_X11NetWmWindowTypeDock` for the panel).

**Comment by tsujan** [comment]
They'll review the code.
