### ISSUE TITLE
Set SplitterPos by config file

### ISSUE THREAD

**Issue by qurious-pixel** [lxqt/pcmanfm-qt#1412]
##### Expected Behavior
Setting the configuration file for pcmanqt-fm should respect the width submitted for the left pane splitter. Instead it requires manual adjustment to retain the settings. (drag and release).

##### Current Behavior

Default ignores configuration width
![splitter_pos1](https://user-images.githubusercontent.com/62252937/124162738-a7f62800-da53-11eb-94a5-fea71d0ff4e6.png)

Desired: custom width.
![splitter_pos2](https://user-images.githubusercontent.com/62252937/124162819-c2300600-da53-11eb-9174-63397c95d8db.png)

##### Steps to Reproduce (for bugs)

1. set `SpliterPos=` in `filedialog.conf`  and/or pcmanfm-qt `settings.conf`
2. open pcmanfm-qt
3. 
4. 

##### Context

Mounted drive names are cutoff from the left pane. Attempting to set a custom width to accomodate is ignored at the config file level. 
##### System Information

* Distribution & Version: lubuntu 20.04.2 LTS
* Kernel: 5.12.0-12.1-liquorix-amd64
* Qt Version: 5.12.8
* libfm-qt Version: 0.17.0
* libqtxdg Version: 3.7.1
* lxqt-build-tools Version: 
* Package version: 

![abount](https://user-images.githubusercontent.com/62252937/124162452-4e8df900-da53-11eb-8836-fcfee98ac8ac.png)

**Comment by tsujan** [comment]
Config files aren't for manual editing. If you edit them manually, you need to know more about the codes of the apps and how they save their settings.

**Comment by qurious-pixel** [comment]
This might be an invalid issue, but is there a way to set this?
GUI, config or any other way so that I can set the `/etc/skel` file to have the proper widths?

**Comment by tsujan** [comment]
> is there a way to set this?

Yes. You should set it when the app isn't running; otherwise, it's be overwritten by the app. Also, it'll be overwritten if the splitter handle is moved after starting the app.

Note that, by chance, the value of `SplitterPos` is just an integer. It's quite possible that a value isn't human-readable.

**Comment by qurious-pixel** [comment]
Thanks. That is what I want. New default setting, overwritten by user-interaction.

I change "150" to "400" ; but it still opens at 150.

https://github.com/lxqt/pcmanfm-qt/blob/642b01109f65e3400dd35fbb5de52976a062ae8c/config/pcmanfm-qt/lxqt/settings.conf.in#L47

**Comment by tsujan** [comment]
You may have edited the wrong file or pcmanfm-qt's process may have been running when you edited it.
