### ISSUE TITLE
4 more options in "Reopen last window tabs"

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1415]
it would be good to have 4 sub-check-boxes in "Reopen last window tabs in a new window" (in Preferences in "User interface"):
- Show the first tab
- Show the last tab
- Show the last viewed tab
- Show the last viewed tab and the last view within the tab

a user could then select only one of those check-boxes
<br>
<b>remarks</b>
1
"Switch to newly opened tab" (in Preferences in "User interface")
should be changed to:
"Switch to newly opened tab when a new tab is created",
else "Switch to newly opened tab" is in conflict with some of the upper sub-check-boxes

2
it should have also consequences on split view
<br>
##### System Information

* Distribution & Version: Lubuntu 21.04
* LXQt: 0.16.0
* PCManFM-Qt : 0.16.0

**Comment by tsujan** [comment]
Sorry, we don't add extra options just because they can be added. There are other criteria too.
