### ISSUE TITLE
[feature request] add "empty trash" menu entry or button

### ISSUE THREAD

**Issue by bsduck** [lxqt/pcmanfm-qt#1418]
##### Expected Behavior
When the current folder is the trash, it would be nice to have either a right-click menu entry to empty the trash, or a toolbar button with similar functionality.

##### Current Behavior
To empty the trash you have to either right-click on the trash in the sidebar (not an option if you don't use the sidebar or use the directory tree instead of the bookmarks) or select everything in the trash and right-click -> delete (less convenient).

**Comment by stefonarch** [comment]
Working fine.

**Comment by tsujan** [comment]
Let's have it in git; it's simple.

**Comment by bsduck** [comment]
I've never seen a requested feature implemented in such a ridiculous amount of time. Thank you @tsujan!

**Comment by tsujan** [comment]
You're welcome. It was a good idea and also easy to implement.
