### ISSUE TITLE
When creating a new file or folder, focus it

### ISSUE THREAD

**Issue by goetzc** [lxqt/pcmanfm-qt#142]
When creating a new file or folder via `Create New -> Folder` or `Blank File`, giving it focus automatically can improve the user experience.  This way, it can easily be opened with `Enter` or renamed with `F2`.

This also applies when just renaming existing files & folders.

**Comment by jleclanche** [comment]
Accepted

**Comment by npmiller** [comment]
This is easy to implement but unfortunately it requires a change in the `libfm-qt` API as we are relying on the `libfm-qt` function `createFileOrFolder` which doesn't give any information back to the caller about the file it created, ideally it should return a boolean to indicate if the creation was successful and pass back to the caller the file name.

**Comment by tsujan** [comment]
My rejected PR, https://github.com/lxde/pcmanfm-qt/pull/223, does it and more. I use it since then without any problem. Now, it consists of two patches, one for libfm-qt and the other for pcmanfm-qt.

**Comment by tsujan** [comment]
Implemented as an option but needs a fix, which I'll make after https://github.com/lxqt/libfm-qt/pull/218 iis merged.
