### ISSUE TITLE
show automatically the content of a mounted volume

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1420]
##### Steps to Reproduce
1: in the Preferences in Volume: activate "Mount removable media automatically when they are inserted"
2: in the Preferences in Volume: deactivate "Show available options for removable media when they are inserted"
3: insert a device (like an USB-stick) in the computer

##### Current Behavior
the volume will be mounted

##### Expected Behavior
the content of the device should appear

##### Possible Solution
in the Preferences, in Volume, in "Mount removable media automatically when they are inserted": two sub-checkbox

- "show content of the mounted volume in the current tab"
- "show content of the mounted volume in a new tab"

remark: for the two options above: if the file-manager is open, then take the current file-manager, else open file-manager

##### System Information
* Distribution & Version: Lubuntu 21.04
* pcmanfm-qt: 0.16.0

my 0.16.0 is old, but I still don’t know how to install the latest version;
if the issue does not appear in 0.17.0 any more, then I’m sorry for this report

**Comment by ralf3u** [comment]
@tsujan

What did I make wrong?

**Comment by tsujan** [comment]
> What did I make wrong?

Nothing.

We don't add an option just for the sake of having yet another option. I've said that in several places.

**Comment by ralf3u** [comment]
@tsujan

OK, in future I will not make reports to ask for options.

**Comment by stefonarch** [comment]
To discuss ideas you can use https://github.com/lxqt/lxqt/discussions

**Comment by ralf3u** [comment]
@stefonarch

> To discuss ideas you can use https://github.com/lxqt/lxqt/discussions

Thank you for this hint. I did not know that.

Is there a kind of tutorial to know how that works, a kind of introduction?
