### ISSUE TITLE
SHIFT selection doesn't always give a correct selection order

### ISSUE THREAD

**Issue by nojusr** [lxqt/pcmanfm-qt#1421]
##### Expected Behavior
When opening multiple files for a specific application via the "open with..." submenu, the order of the selected files should follow either the sorting setting of the file manager, or the order in which the files were selected(highlighted).

##### Current Behavior

When opening multiple files for a specific application, the order of the opened files seems to be random or independent of the current sorting selection/order of highlight.

##### Possible Solution

Re-implement old behaviour from pcmanfm (the GTK based version)

##### Steps to Reproduce (for bugs)

1. Install a program which can handle opening multiple files, (in my case, mpv)
2. Procure a folder of incrementally-numbered files
3. Shift-select every file
4. Open with the application mentioned in step 1

##### Context

Was trying to load the whole season of a TV show into mpv, usually i sort files by "Last modified", but since each episode is labeled in an incremental manner, i could re-sort the files by name, shift-select the whole folder, open with mpv, and have the whole season pre-loaded in the video player. This used to be possible in pcmanfm, but isn't possible in pcmanfm-qt

##### System Information

* Distribution & Version: Artix Linux
* Kernel: Linux 5.12.14-artix1-1
* Qt Version: 5.15.2
* libfm-qt Version: Unknown
* libqtxdg Version: Unknown
* lxqt-build-tools Version: Unknown 
* Package version: 0.17.0

**Comment by nojusr** [comment]
Update:
upon further testing, it seems that when using CTRL-click selection, the order of file selection is followed. This behaviour only seems to apply when shift-selecting files.

**Comment by tsujan** [comment]
`Shift` selects files according to their current sorting and they're opened in the same order. `Ctrl` makes it possible to select files freely and they're opened in the order they've been selected. So, not only there's no bug but, if there order was different, we'd have a bug to fix.

**Comment by nojusr** [comment]
Okay, this had me stumped for a bit.
The day after your comment, I decided to test it out myself, opened the file manager and realized that everything worked as-described. Both `Shift` select and `Ctrl` select worked exactly as you described, and i seriously considered going for a mental health checkup.

Later today though, the same issue began cropping up, and i decided to test this further. The issue i experienced seems to stem directly from the `Shift`-click behaviour, not the `Ctrl`-click behaviour.
To put it shortly, the file loading order issue, as described above, only affects `Shift`-selection, and only seems to crop up when the file layout grid (a.k.a `Icon View`) contains more files that can be displayed without requiring scrolling. Also, the first `n` elements will always be in order, where `n` seems to be dependant on window width.

Update on how to reproduce:
1. Install a program which can handle opening multiple files, (in my case, mpv)
2. Procure a folder of incrementally-numbered files
3. Set pcmanfm to icon view (other views untested)
4. Scale pcmanfm's window down so that the main grid view has to handle vertically overflowed elements (i.e scroll)
5. Shift-select every file in the folder, first to last, sorting seems to not be an issue
6. Open with the application mentioned in step 1

If that doesn't end up displaying unintended behaviour, then I have either failed to properly convey the issue, or it is exclusive to my setup.

**Comment by tsujan** [comment]
Files that are selected by pressing `Shift` are given to their associated apps in the order of their current sorting — and that isn't related to the existence or absence of scroll-bars. Whether they're opened by those apps in the same order or not depends on the apps in question. Most video players (if not all) enqueue files in the order, in which they're given to them; text/image editors may not.

Although I knew what the code did, I tested with SMPlayer (which uses mpv) a few times: scroll-bars had no effect.

**Comment by tsujan** [comment]
> or it is exclusive to my setup.

No, it doesn't depend on a certain setup.

**Comment by nojusr** [comment]
Here's a video of me reproducing the bug(?) with SMPlayer.
[link](https://kelp.ml/u/ayy2.mkv)

**Comment by tsujan** [comment]
Thanks for the attached video. I tested 3 times and still couldn't reproduce it as in your video (couldn't do it with the exact file names but used "01", "02", "03",...). However, the video shows a problem. Reopening for further investigation...

**Comment by tsujan** [comment]
OK. On my 2nd laptop, I added `qDebug()` to the source to see the order in a terminal and tested with 13 empty files with names "01" to "12". The order changed in the case of `Shift` when I resized the window in a certain way but it didn't depend on the existence or absence of the scroll-bar. `Ctrl+A` didn't have a problem either.

There's a needle in the haystack. Whether it's in our code or in Qt's, I don't know yet.

**Comment by tsujan** [comment]
I examined our code and, for the sake of testing, simplified it to use Qt's original methods as far as possible but the issue persisted. My conclusion is that it should be a problem in Qt, especially somewhere in `QListView::setSelection()`.

However, I found a simple workaround; should make sure that it doesn't have any side effect before making a PR.

**Comment by tsujan** [comment]
The solution (= workaround) is here: https://github.com/lxqt/libfm-qt/pull/710
