### ISSUE TITLE
Copy "pcmanfm" config to "pcmanfm-qt"?

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [lxqt/pcmanfm-qt#1422]
Can I simply copy/move the config files from "pcmanfm" (1.3.1 from Debian 10.10) to "pcmanfm-qt" (0.14.1 from Debian 10.10)?

Or are there any known issues?

**Comment by tsujan** [comment]
Please don't use the bug tracker for questions. → [Discussions](https://github.com/lxqt/lxqt/discussions)

The answer is "no". pcmanfm and pcmanfm-qt don't have shared config files; they're totally different apps.

**Comment by stefonarch** [comment]
I still think mention this in the issue template would be useful.

**Comment by tsujan** [comment]
> I still think mention this in the issue template would be useful.

Feel free to add it but please keep the template as short as possible. For example, IMO, this line can be reemoved:

```
<!--- should not delete relevant sections and/or questions in your report  --->
```

Or this is logically redundant:

```
This is esp. true for Ubuntu LTS.
```

The more concise the template is, the more probably users will read it.

**Comment by stefonarch** [comment]
When trying to modify it I get this info:

 You are using an old version of issue templates. Please update to the new issue template workflow. Learn more_

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

maybe we should look into this more in detail.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
> Please don't use the bug tracker for questions. → [Discussions](https://github.com/lxqt/lxqt/discussions)

Your link goes to another project. So you need to mention this link in your README.md of that project here. I was looking into the readme for a discusson-area.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
> > I still think mention this in the issue template would be useful.
> 
> Feel free to add it but please keep the template as short as possible. For example, IMO, this line can be removed:
> 
> ```
> 
> ```
> 
> Or this is logically redundant:
> 
> ```
> This is esp. true for Ubuntu LTS.
> ```
> 
> The more concise the template is, the more probably users will read it.

I would suggest not to use a **real** issue template like this examle here

https://github.com/Codeberg-AsGithubAlternative-buhtz/spielwiese/issues/new/choose
