### ISSUE TITLE
[Feature Request] Add the ability of PCManFM-Qt to be able to opened in other sessions

### ISSUE THREAD

**Issue by iamthesenate1** [lxqt/pcmanfm-qt#1429]
##### Expected Behavior

pcmanfm-qt should open in every session.
##### Current Behavior

When switching from the current sesion to another (with Ctrl+Alt+F2, for example) and starting pccmanfm-qt, it openes in the first session.

##### Steps to Reproduce (for bugs)

1. Have pcmafm-qt open in a session.
2.  Open another session.
3.  Start pcmanfm-qt
4. It will open in the first session.

##### Context

Sometimes I use more sessions and it is a PITA to have to use other file managers .
##### System Information

Irrelevant.

**Comment by tsujan** [comment]
pcmanfm-qt is a single-instance app: there's only one process. When you open the second window, it's just a window, not a new process.

That's the case with all single-instance apps, as far as I know.
