### ISSUE TITLE
First launch wakes hard drive from standby

### ISSUE THREAD

**Issue by Markus00000** [lxqt/pcmanfm-qt#1432]
##### Expected Behavior

I did not expect PCManFM-Qt to wake up my idle hard drive from standby when first launched. This drive contains one non-root partition that is mounted at boot. I have disabled all auto mount options in PCManFM-Qt and no directories on the drive are opened in PCManFM-Qt.

##### Current Behavior

Launching PCManFM-Qt for the first time after booting wakes up the drive from standby.

##### Steps to Reproduce (for bugs)

1. Boot
2. Wait until non-root drive enters standby
3. Launch PCManFM-Qt for the first time
4. Check if drive is still in standby

##### Context

I would prefer the drive to stay in standby mode to:

* Reduce noise
* Save battery
* Reduce its cycle count

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 5.13.9
* Qt Version: 5.15.2+kde+r211
* libfm-qt Version: 0.17.1
* libqtxdg Version: 3.7.1
* lxqt-build-tools Version: 
* Package version: 0.17.0

**Comment by tsujan** [comment]
pcmanfm-qt or libfm-qt doesn't read/write when there's nothing to read /write. GLib/GVFS may need to do it.
