### ISSUE TITLE
SFTP: forget a connection which was set to 'Remember forever'

### ISSUE THREAD

**Issue by linuxissuper** [lxqt/pcmanfm-qt#1433]
When I navigate to a sftp url and set the inserted credentials to remember forever, I cannot change the username for this connection.    
Example:   
![image](https://user-images.githubusercontent.com/74221543/128859408-160bd8a8-c4e0-4e73-ba8e-16fd311c523f.png)

The username has changed for this hostname and I want to 'forget' this connection

**Comment by tsujan** [comment]
Please see https://github.com/lxqt/pcmanfm-qt/issues/108. pcmanfm-qt doesn't control SFTP, SMB, etc.; it just mounts them.

In spite of what was written at https://github.com/lxqt/pcmanfm-qt/issues/108 several years ago, I don't see this as a bug but if someone makes a PR, it'll be reviewed.

**Comment by linuxissuper** [comment]
Sorry for commenting on this closed issue.
I also don't see this as a bug. 
More like a feature request.

I only just now realized I just have to delete the entry from the keyring.
Maybe some info/hint text in pcmanfm-qt that this is stored in the keyring would be helpful? 
Especially for inexperienced users (like myself 😅)

**Comment by tsujan** [comment]
> Sorry for commenting on this closed issue.

It's OK.

> I only just now realized I just have to delete the entry from the keyring.

Yes.

I don't think pcmanfm-qt/libfm-qt should control special cases like this — hence my lack of interest in making a patch — but a small patch that is guaranteed to work with all systems would be welcome.

**Comment by tsujan** [comment]
BTW, you can always add comments to a closed issue. GitHub allows it and it might be useful in some way.
