### ISSUE TITLE
add "open with" for current folder's context menu

### ISSUE THREAD

**Issue by mardab** [lxqt/pcmanfm-qt#1434]
##### Expected Behavior
Upon right-clicking in free space in folder (or perhaps in one of the taskbar menus, for cases like no free space in detailed list view) there should be a submenu "open with...", but for current directory.

##### Current Behavior
To achieve same result I have to go up and right click folder I came from.

##### Possible Solution
I doubt that such context menu addition requires more work beside referencing currently used code for "open with..." menu.

##### Context
This is a feature I used surprisingly often with Dolphin, to jump from current directory to VSCodium, run a lookup of disk usage of folder I'm in right now, etc. Going up and looking back at same folder is an annoyance and takes some time when working with 5400RPM HDDs or networked storage.

##### System Information
* Distribution & Version: Funtoo 
* Kernel: 5.10.46_p2-debian-sources
* Qt Version: 5.15.2
* libfm-qt Version: 0.17.1
* libqtxdg Version: 3.7.1
* lxqt-build-tools Version: 0.9.0

**Comment by tsujan** [comment]
> I doubt that such context menu addition requires more work...

The amount of work isn't the problem; cluttering the folder context menu for a special use case is.

You could easily add a custom action for it. See https://github.com/lxqt/pcmanfm-qt/wiki/custom_actions
