### ISSUE TITLE
Trash: Default behaviour with files from other devices/partitions

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [lxqt/pcmanfm-qt#1438]
I am sorry for asking via Issue but I could not find a mailinglist or forum.
Before I open a "real" Bug Report I would like to understand some things.

I read #1336 but did not fully understand.

Is it correct hat pcmanfm-qt should be able to handle deleting files from other partitions/devices?

Can you please describe the exact behaviour.

Is it done by default? Or is there a setting checkbox somewhere?

**Comment by tsujan** [comment]
Trash is controlled by GVFS, not by pcmanfm-qt. The latter just calls the former.

> I could not find a mailinglist or forum.

Please use [Discussions](https://github.com/lxqt/lxqt/discussions).

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
> Please use [Discussions](https://github.com/lxqt/lxqt/discussions).

Then please point to that discussion group in your README.md.

**Comment by stefonarch** [comment]
I adapted the [template already for  qterminal ](https://github.com/lxqt/qterminal/issues/new/choose)too, will do it here and in panel (probably the most used).
