### ISSUE TITLE
Make "Do you want to open these <n> files?" dialog optional

### ISSUE THREAD

**Issue by toscompliantname** [lxqt/pcmanfm-qt#1444]
Title.

##### Current Behavior
To get the dialog, navigate to a folder with too many files (>20 ?),  select them all and press Enter. 
##### Expected Behavior
...is to have an option in edit-->settings to disable the dialog, so that when you press Enter it just opens them, silently.

I suspect this is not a bug so no sys info for now.

**Comment by tsujan** [comment]
Thanks for your suggestion but selecting > 20 files and hitting Enter and getting annoyed by a prompt dialog isn't something that happens to users constantly. Adding an option for the sake of having yet another option would result in a mess like that of KDE config dialogs.

**Comment by toscompliantname** [comment]
So the dialog is only giving me trouble when I search&filter directories recursively for pictures that have certain filenames, and then press Ctrl+A and enter (and Y, because of the dialog) to open all of them from the search results.  
If adding it to the ui is not a good idea, then what about adding it as a super sekrit option to modify in the conf file only?

**Comment by tsujan** [comment]
Let's wait to see whether what you want is popular or not. It hasn't been until now but if the opposite is proven, the number could be made configurable.

That being said, I really don't like the direction our config dialogs are going in.
