### ISSUE TITLE
Hidden Files Are Always Visible For MTP Mounts

### ISSUE THREAD

**Issue by antis81** [lxqt/pcmanfm-qt#1446]
##### Expected Behavior
Hidden files are visible dependent on the "show hidden files" option.

##### Current Behavior
When an MTP device is mounted, hIdden files/folders are always visible:

![mtp_hidden_files](https://user-images.githubusercontent.com/440517/133150454-f85068f9-1f10-4c7c-b040-e2222bd3d2aa.png)

Changing the flag has no effect.

##### Possible Solution
<TBD>

##### Steps to Reproduce (for bugs)
Mount an MTP device (Fairphone 2 + SailfishOS 4.1 in this case).

##### Context
Mounted MTP device over USB.

##### System Information
```
LXQt Desktop Toolbox - Technical Info<p>
  LXQt About Version:     0.17.0
  LXQt Version:           0.17.0
  Qt:                     5.15.2
  Build type:             Release
  System Configuration:   /etc/xdg
  Share Directory:        /usr/share/lxqt
  Translations:           /home/nils/.local/share/flatpak/exports/share/lxqt/translations<br>
/var/lib/flatpak/exports/share/lxqt/translations<br>
/usr/local/share/lxqt/translations<br>
/usr/share/lxqt/translations<br>
/var/lib/snapd/desktop/lxqt/translations


User Directories
  Xdg Data Home:          /home/nils/.local/share
  Xdg Config Home:        /home/nils/.config
  Xdg Data Dirs:          /home/nils/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop
  Xdg Cache Home:         /home/nils/.cache
  Xdg Runtime Home:       /run/user/1000
  Xdg Autostart Dirs:     /etc/autostart<br>
/etc/xdg/autostart<br>
/usr/share/autostart
  Xdg Autostart Home:     /home/nils/.config/autostart
```

**Comment by tsujan** [comment]
We don't control which files are considered hidden with which protocols. We use `g_file_info_get_is_hidden()`; the rest is done by `GLib` and `GVFS`.

**Comment by antis81** [comment]
So it's a GVFS bug?

**Comment by tsujan** [comment]
I can't say it's a bug but yes, GVFS is responsible.
