### ISSUE TITLE
Desktop mode, root menu and 3rd party window managers

### ISSUE THREAD

**Issue by NsCDE** [lxqt/pcmanfm-qt#1447]
Dear PcmanFM-qt authors and developers,

I Like PCmanFM(-qt) as semi-lightweight, yet powerfull and nice file manager. When I found it years ago, it was just what I needed. I'm one of those who like to build their own semi-DE environments with good stand alone bits and components. I know PCmanFM-qt is primary for LxQt DE, but as your README.md stands, it can be used independently. So I'm using it.

After the update of the Debian distro, I can see new PcmanFM-qt 0.16.0. Old one was 0.14.0. To my unpleasant surprise, option "Show menus provided by window managers when desktop is clicked" is no more. While I see the issue #931 and reasoning behind it, please allow me to express some throughts on this.

Beeing a very good file manager, PCmanFM's lightweight desktop management function, notably providing desktop icons, was  a really flexible feature to build hybrid environments that can serve more demanding users. Even it's background setter capability was not so important here, because it can be achieved by external means. Passtrough to WM of click on root window was just that bit which made all that to fit perfectly for me. I'm using FVWM and now new FVWM3 which is now in current development.

Please consider adding this relatively small piece of code from PR 937 back and visible only when detected FM is running on X11. For us, weird build-your-own-DE freaks. I don't think it will pollute code cleanliness too much. Moreover, maybe sometimes, to get good features, one must dig some dirt. Otherwise, we may get really sterile desktop environments (not LxQt, not KDE ...).

Sorry for bothering and begging here .., but I at least have to try. This update really ruined my day. :-\

**Comment by tsujan** [comment]
> I can see new PcmanFM-qt 0.16.0

0.16 is outdated, although there's no difference in this regard.

**Comment by NsCDE** [comment]
Hello,

Difference towards what? I don't understand. I thought I deserve at least some short comment here.

**Comment by tsujan** [comment]
> Difference towards what?

With regard to the topic of your comment.

> I thought I deserve at least some short comment here.

You said, " I see the issue #931 and reasoning behind it...".

**Comment by NsCDE** [comment]
Never mind.
