### ISSUE TITLE
removable media: unmounting single medium may trigger closing all PCManFM windows

### ISSUE THREAD

**Issue by pmattern** [lxqt/pcmanfm-qt#145]
Unmounting a single removable medium may trigger closing all PCManFM windows which isn't convenient but rather confusing.
In http://sourceforge.net/p/pcmanfm/bugs/546/ (PCManFM GTK, which behaves the same) it was even erroneously considered a crash.

In practice it happens if "Close tab containing removable medium" is set in Preferences - Volume and the device to get unmounted is displayed in all open tabs.
This in turn may affect several open windows where it's rather unlikely. But it also applies if only a single PCManFM-Qt window is open and an arbitrary number of tabs in that window is displaying the device in question. So in particular it affects a single tab in a single window which is the actual use case that for sure occurs frequently.

So I think it should be assured that at least one window remains open.

**Comment by q4a** [comment]
I think it's not related to removable media. PCManFM-Qt closing when you trying to access non existing folder. For example type /ereferfer in address bar. You don't have folder "ereferfer" and PCManFM-Qt will close all your tabs.
And I think that it's bug. User should get error message, but not closing all tabs.

**Comment by pmattern** [comment]
Closing windows upon entering invalid paths could be due to the downstream issue that was discussed in #200 and that still exists.
At least I can't reproduce it running PCManFM-Qt from recent VCS checkout which rather shows the warning message mentioned in #200 as well.
To further track you may want to toggle the settings in Preferences - Volume - "When removable medium unmounted" as the problem discussed in this issue can only be seen when "Close tab containing..." is checked.

**Comment by PCMan** [comment]
The latest code in git already
1. fix a crash related to this.
2. provide an option to turn off this behavior.
So I'm closing the issue.

**Comment by pmattern** [comment]
I don't like to say but I have to disagree here.

By "turning off" you mean checking "Change folder in the tab..." in Preferences - Volume, right?
But avoiding a problem by avoiding the option that makes it visible isn't a solution.

PCManFM-Qt shouldn't disappear completely due to unounting a single device, IMO. Edited the first comment, maybe the actual problem wasn't clear so far.

(The crash is fixed indeed but it turned out to be an unrelated downstream issue anyway.)

**Comment by PCMan** [comment]
OK, reopen the issue.

**Comment by tsujan** [comment]
IMO, the current options are acceptable. They're much better than Dolphin, which keeps showing an unmounted, nonexistent folder.
