### ISSUE TITLE
removable media: incorrect display in tab remaining after unmounting

### ISSUE THREAD

**Issue by pmattern** [lxqt/pcmanfm-qt#146]
After unmounting a removable medium the display in a possible remaining tab within the same window isn't quite correct.

If "Close tab containing removable medium" is set in Preferences - Volume and there's more than one tab per window two objects will have blue background in the tab that's displayed next after another tab was closed by unmounting. These are the object that had been displayed before and another one adjacent to the removable medium's former location.
E. g. this screenshot shows a remaining tab itself displaying folder "Applications" after another tab had been closed by unmounting an SFTP share the icon of of which had been below the ODD ("ARCH_...").

![pcmanfm removable media](https://cloud.githubusercontent.com/assets/9860801/6428713/9edb70a0-bfab-11e4-8373-65c9028b6e65.png)

If "Change folder in the tab to home folder" is set as stated above $HOME will be displayed in right pane but in the left pane an adjacent object as described in previous paragraph gets blue background.

**Comment by tsujan** [comment]
Not reproducible (now).
