### ISSUE TITLE
Do not put files to recycle bin on network shares

### ISSUE THREAD

**Issue by thenktor** [lxqt/pcmanfm-qt#1460]
##### Expected Behavior
If directories on network shares (CIFS) are viewed there should be a "delete" option only, not "put to recycle bin".

##### Current Behavior
Currently files are put to the recycle bin, which in turn creates a folder named ".Trash-1000" on the top level of the network share. This is really weird in heterogeneous environments, because Windows users will also see these files.

##### System Information

* PcManFm-qt version: 0.17.0
* Distribution & Version: Void Linux
* Qt Version: 5.15.3
* liblxqt Version: 0.17.0

**Comment by tsujan** [comment]
You may want to make a report against GVFS.

As has been mentioned several times here and there, we depend on GVFS for the trash. Neither pcmanfm-qt nor libfm-qt creates ".Trash-1000". If, *according to GVFS*, trashing is impossible, the "Move to Trash" item will *not* create any trash folder but will show an appropriate prompt dialog for deleting.
