### ISSUE TITLE
Inline rename

### ISSUE THREAD

**Issue by sajadspeed** [lxqt/pcmanfm-qt#1465]
Please add inline rename option.
Rename by clicking on a file or folder and waiting for a while. Like Windows.

**Comment by sajadspeed** [comment]
I do not understand why it is dangerous?
Well, this option really speeds up the renaming process.
For example, now that I have to get the fn key with the F keys

**Comment by isf63** [comment]
I think this is a good idea. F2 is obscure and hard to remember, so I'm almost always using the context menu.
With a delay it isn't very dangerous, or by having it as an option disabled by default.

**Comment by Divinux** [comment]
+1, I quite miss this.
