### ISSUE TITLE
Cant mount an hdd partition,

### ISSUE THREAD

**Issue by chomwitt** [lxqt/pcmanfm-qt#1473]
##### Expected Behavior
After boot PCManFM-Qt recognizes three partitions in a secondary HDD. And clicking in one of them it will ask me password and mount it.

##### Current Behavior
But some times i get 'an operation is already pending'. It happens if i recall correctly if i click the partition icon more that one times fast.

##### Possible Solution
$ sudo mount -t ext4 /dev/sda1 /media/user/Books/       // worked.

##### System Information
* PcManFm-qt version: 0.16.0
* Distribution & Version:Devuan GNU/Linux 4 (chimaera) 
* Qt Version: LXQt 0.16.1 
* liblxqt Version:

**Comment by tsujan** [comment]
I'm afraid 0.16 is outdated. Many things have changed in the codes of libfm-qt and pcmanfm-qt. Please use the latest release!

**Comment by tsujan** [comment]
There have been important fixes about mounting and password after 0.17. They'll be in LXQt 1.0.0, which will be released in a week or so. I don't know how fast your distro will package it for you.

**Comment by chomwitt** [comment]
Thanks for the reply.
