### ISSUE TITLE
[Feature] Unmounting from "Computer" 

### ISSUE THREAD

**Issue by es20490446e** [lxqt/pcmanfm-qt#1479]
Just an idea.

Probably it could be quite useful being able to unmount external drives from the place "Computer".

This way you no longer have to depend on having the side pane at view for having such feature. And you can truly choose if to keep the pane hidden, which I believe is cleaner.

**Comment by stefonarch** [comment]
![schermata-11-08-08-27](https://user-images.githubusercontent.com/10681413/140700647-f9a61335-cffd-4e46-8c48-585aaab146c6.png)

It's implemented in 1.0.0

**Comment by es20490446e** [comment]
Oh thanks.
