### ISSUE TITLE
Option to increase ThumbnailIconSize at least to 512

### ISSUE THREAD

**Issue by terremoth** [lxqt/pcmanfm-qt#1481]
**Is your feature request related to a problem? Please describe.**
It would be nice to give the user the option to increase `ThumbnailIconSize` higher than 256, like to 512.   
Even though I change the file `~/.config/pcmanfm-qt/lxqt/settings.conf` and increase there and restart PCManFM, it changes all the config to default again, and I don't know how I can increase it. This will be very usefull for **videos directories**! It could have the option in the select menu to at least set to 512

![image](https://user-images.githubusercontent.com/11032344/140808626-56648776-13e3-4e1e-b3a5-159bb98aa13b.png)

at `Edit > Preferences > Display` when PCManFM is open

![image](https://user-images.githubusercontent.com/11032344/140809709-43993fa7-9ca8-426b-9b91-2e04871d16ee.png)

**Comment by terremoth** [comment]
I also think several people will benefit from this feature

**Comment by tsujan** [comment]
512 is too big for a "thumbnail". Users with HDPI screens can (or should) use a scale factor > 1. We don't want to make an image viewer out of the thumbnail functionality or fake the scale factor.

**Comment by terremoth** [comment]
I understand. It was a suggestion. Windows Explorer, for example, let you increase the file thumbs to something like 512.  
I just thought it would be nice to also have this feature on PCManFM, mainly for Windows users who just came from a low-end hardware, and would like to experience an even better File Manager

**Comment by tsujan** [comment]
A pre-HDPI screen may have a resolution near 1920x1080 or a little larger (of course, the actual screen size also matters), which is too small for 512-px icons/thumbnails plus their texts. With a true HDPI screen, a scale factor of 2 will give sharp 512-pix thumbnails in the latest release (1.0.0) if a thumbnail size of 256 is selected. In between, one can also use a scale factor of 1.5, 1.4, etc.

So, IMO, 256 is a good upper limit everywhere.

**Comment by terremoth** [comment]
Yeah, thinking more about this, you're right. 
I was measuring here in my screen, It will become horrible, I guess,

**Comment by tsujan** [comment]
> If you don't want to include this feature, at least can you guide me what should I do to accomplish that?

It isn't in one file but the main codes are inside `libfm-qt`. You need to get familiar with the folder model and the thumbnail generator, especially the files `thumbnailer.cpp`, `thumbnailjob.cpp`, `foldermodel.cpp` and `foldermodelitem.cpp`.

**Comment by gsantner** [comment]
please don't blame display scaling or other system/environment configuration on it.  
pcmanfm-qt's thumbnail options are lacking and even the biggest thumbnail size option is too small to properly recognize whats in the thumbnails - like browsing wallpapers or videos. to me it's to the point I cannot use pcmanfm-qt at all due this issue.

for comparision pcmanfm-qt's highest thumbnail option .. vs nautilus default ... vs nautilus biggest scale

![thumbnail-issue](https://user-images.githubusercontent.com/6735650/159364332-e3d5255b-8577-4a0c-a83d-c665760f01de.png)

please add more options for thumbnail sizes, thanks

**Comment by gsantner** [comment]
Even the biggest thumbnail size option is too small to properly recognize whats in the thumbnails - like browsing wallpapers or videos. to me it's to the point I cannot use pcmanfm-qt at all.

for comparision pcmanfm-qt's highest thumbnail option .. vs nautilus default ... vs nautilus biggest scale

![thumbnail-issue](https://user-images.githubusercontent.com/6735650/159364332-e3d5255b-8577-4a0c-a83d-c665760f01de.png)

please add more options for thumbnail sizes, thanks

---> hm, or are thumbnails generally broken? it looks a bit very small for a 256px cell. And yes, I've applied and restarted pcmanfm-qt


pcmanfm-qt v0.16

**Comment by tsujan** [comment]
> it looks a bit very small for a 256px cell.

You don't have any thumbnail view in your screenshot.

> .. vs nautilus default ... vs nautilus biggest scale

Irrelevant.

> pcmanfm-qt v0.16

Outdated.

**Comment by gsantner** [comment]
> You don't have any thumbnail view in your screenshot.

What do I have then?

**Comment by stefonarch** [comment]
Your icon set is misleading IMO, the lense and the info is inverted.
![schermata-03-21-22-27](https://user-images.githubusercontent.com/10681413/159366864-84c4b270-e572-49cc-aa44-7dfd6d76f55f.png)

**Comment by tsujan** [comment]
> What do I have then?

Icon view.

**Comment by gsantner** [comment]
OK I see, you have a separate small thumbnail "icon mode" and a big thumbnail "thumbnail mode". This is the first file manager I have seen two thumbnail modes.

thanks for the hint

**Comment by terremoth** [comment]
@gsantner  You choose the wrong way to view man... You need to select the THUMBNAIL view instead of ICON view in the menu as pointed from @tsujan

Icon View (like yours now):
![image](https://user-images.githubusercontent.com/11032344/159367973-0e42942e-8e59-479b-8fcb-1c3cc3d9f040.png)

This is the THUMBNAIL view (this is what you want - configured on menu):

![image](https://user-images.githubusercontent.com/11032344/159368051-39ecd943-0891-4055-a985-b526f10f7c7f.png)

**Comment by terremoth** [comment]
The thumbnail view size set to 256x256 is far big enough. I think even bigger than the nautilus could generate

**Comment by gsantner** [comment]
It's a matter of user expectation, but it is off topic - to this issue of thumbnail size settings. pcmanfm-qt has a unique implementation here, I didn't expect that.  

I expected there is one view with thumbnails, like everything else  I used. In other filemanagers I just use ctrl+zoom wheel to change thumbnail/image/icon whatever size currently is needed and that's it. I don't see any benefits or need here for different view modes. 

![screenrecord](https://user-images.githubusercontent.com/6735650/159376539-4a0a1b46-8875-438f-84cf-77f8a7d51c13.gif)

**Comment by gsantner** [comment]
It's a matter of user expectation, but it is off topic - to this issue of thumbnail size settings. pcmanfm-qt has a unique implementation here, I didn't expect that.  

I expected there is one view with thumbnail/image/icon/whatever grid view, like everything else  I used. In other filemanagers I just use ctrl+zoom wheel to change the size to what's currently needed and that's it. I don't see any benefits or need here for different grid view modes. 

![screenrecord](https://user-images.githubusercontent.com/6735650/159376539-4a0a1b46-8875-438f-84cf-77f8a7d51c13.gif)

> The thumbnail view size set to 256x256 is far big enough. I think even bigger than the nautilus could generate

For sure at least 256 as stated in documentation, but seems like depending on some configuration up to 1024. <https://gitlab.gnome.org/GNOME/gnome-desktop/-/blob/master/libgnome-desktop/gnome-desktop-thumbnail.c#L324>

**Comment by stefonarch** [comment]
As you see in the preferences: small icons, (list, detailed list), big icons (grid) and thumbnails.
It's some time now you can save view modes per folder and/or subfolders, including sorting etc,

**Comment by Lew-Rockwell-Fan** [comment]
Amazing how dismissive people, presumably people with good eyesight, are of a feature request FOR AN OPTION. Just another choice on a menu they'd be free to ignore.  THEY don't have a use for it, so it's a bad idea.  I got to this page because I'm specifically searching for a GUI file browser that supports huge thumbnails. Guess I'll move along.
