### ISSUE TITLE
Class Settings has some uninitialized members

### ISSUE THREAD

**Issue by cepamoi** [lxqt/pcmanfm-qt#1488]
##### Expected Behavior
Class Settings should initialize all its members.

##### Current Behavior
The following members of class Settings are not initialized in the constructor (while all the other members are):
```
    bool onlyUserTemplates_;
    bool templateTypeOnce_;
    bool templateRunApp_;
```
##### Possible Solution
Init the 3 missing members in the constructor of class Settings.

##### System Information
* PcManFm-qt version: 1.0.0
* Distribution & Version: CentOS 7
* Qt Version: 5.15.2
* liblxqt Version: 1.0.0

**Comment by tsujan** [comment]
Right. Thanks!
