### ISSUE TITLE
Selecting multiple files to open with Enter

### ISSUE THREAD

**Issue by goetzc** [lxqt/pcmanfm-qt#149]
When selecting multiple files to open with `Enter`, only the last one selected is opened.

To avoid accidentally opening to many files, a confirmation dialog could appear when opening more than ~6 files.

**Comment by tsujan** [comment]
This is a cool feature requested a long time ago. Its implementation is easy (I'm using it) but I should test it for a while to see whether it causes any problem.

IMO, an additional confirmation dialog would be annoying. The user should know when he/she presses `Enter`. Moreover, we don't show a confirmation dialog when hundreds of files are selected and the user wants to open them by right clicking.
