### ISSUE TITLE
Enhance detailed list view

### ISSUE THREAD

**Issue by wups** [lxqt/pcmanfm-qt#1493]
**Problem**
The detailed list view has some visual problems, which make it difficult to read:
1. The file sizes are unaligned (e.g. 20 KiB doesn't align properly with 100 KiB)
2. The fields - especially the dates - are too close to each other
3. The line height might be a bit too small
<img width="202" alt="detail-list" src="https://user-images.githubusercontent.com/82526/142775729-fda855c0-076e-483f-99f0-490d16ac3cdc.png">

**Suggestions**
1. I think the file sizes should be right-aligned. That way, the numbers should align better.
2. The default width of the fields should be greater, or the fields need some padding. That way, readability could be enhanced greatly.
3. Maybe increase the line height a bit.

**Additional information**
Using a different font didn't solve the problem.
Using a different Qt theme made it a bit better, but not by much.
I'm using a monitor with higher dpi, so scaling might play a role in my problem.

**Comment by tsujan** [comment]
> The file sizes are unaligned 

They're aligned to left. (It was explained elsewhere why they aren't aligned to right.)

> The fields - especially the dates - are too close to each other

Calculated by Qt (`QTreeView::sizeHintForColumn`) and appropriate.

> The line height might be a bit too small

That's determined by the widget style you use.

**Comment by tsujan** [comment]
> I'm using a monitor with higher dpi,

You could use a scale factor > 1 (set `QT_SCALE_FACTOR` in LXQt Session Settings → Environment).

**Comment by wups** [comment]
Thank you for the answer.
