### ISSUE TITLE
Text related to deleting files to trash or from device

### ISSUE THREAD

**Issue by goetzc** [lxqt/pcmanfm-qt#150]
If `Move deleted files to "trash bin" instead of erasing from disk` is active in Preferences, and when right clicking above a file and pressing `Shift`, the context-menu text should change from `Move to trash` to `Delete` or `Delete from device`.

The same with the menu text, which is a bit weird right now. If the mentioned option in Preferences is active, the text is "Delete", but should be "Move to Trash". It changes only temporary after activating the referred option in Preferences, but is not remembered after program restart.

**Comment by tsujan** [comment]
Not an issue anymore.

There was a problem in applying settings for the Edit menu, which was fixed in https://github.com/lxqt/pcmanfm-qt/commit/2eb38d416a26b666cb5c86a6c596afdbe667c57c
