### ISSUE TITLE
Unable to move down bookmarks from context menu

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1506]
Tested also in Manjaro VM.

Moving bookmarks up from context menu  works, down doesn't.
DND works.
 
EDIT: sometimes "down" disappears even from the menu. Have to investigate.

##### Steps to Reproduce (for bugs)

1. Add some bookmarks
2. Try to reorder them by context menu > move up| down
3. Up works, down doesn't

##### Context

Found by case, no idea how long it's present.
##### System Information

* PcManFm-qt version: 1.0.0 and git
* Distribution & Version: Manjaro

**Comment by tsujan** [comment]
I'd always used DND — I think most users do so. This bug should be old. As you said, "Move Bookmark Down" doesn't appear on some bookmarks.

Will look into it. thanks!
