### ISSUE TITLE
Custom actions don't work with basenames

### ISSUE THREAD

**Issue by flexid2000** [lxqt/pcmanfm-qt#1509]
##### Current Behavior
Custom actions using the execution parameter `%B` don't execute.

##### Possible Solution
Not yet succeeded.

##### Steps to Reproduce (for bugs)
1. Write a custom action, e.g.
```
[Desktop Entry]
Type=Action
Tooltip=
Name=Slugify
Profiles=profile-zero;
Icon=slack

[X-Action-Profile profile-zero]
MimeTypes=all/allfiles;
Exec=perl-rename 's/ /-/g;s/-{2,}/-/g;y/A-Z/a-z/' '%B'
ExecutionMode=Terminal
Name=Default profile
```
2. Execute it on a file.
3. Nothing happens.
4. Executing the same code in a terminal performs the action.

##### Context
Execution parameters like `%f` or `%F` seem to work but not `%b` or `%B`.

##### System Information

* PcManFm-qt version: 1.0.0
* Distribution & Version: ArchLinux
* Qt Version: 5.15.2
* liblxqt Version: 1.0.0-1

**Comment by tsujan** [comment]
`%b/%B` is just the basename. It doesn't contain the info about the work directory. When you use `perl-rename -v 'WHATEVER' %B` in a custom action, your work directory is always your home, not the file(s) directory.

To see that `%b` works, put the file `ha ha` in your home and use this problematic action with it (`%b` shouldn't be single quoted):

```
Exec=perl-rename -v 's/ /-/g;s/-{2,}/-/g;y/A-Z/a-z/' %b
```

However, the correct action is:
```
Exec=perl-rename -v 's/ /-/g;s/-{2,}/-/g;y/A-Z/a-z/' %F
```

NOTE: Don't put `%F` inside single quotes.

**Comment by tsujan** [comment]
BTW, if you want to only change the base-names (and not whole path-names), you could either change the regex or, more simply, use `%d` plus `%b` as:

```
Exec=bash -c "cd %d && perl-rename 's/ /-/g;s/-{2,}/-/g;y/A-Z/a-z/' %b"
```

**Comment by flexid2000** [comment]
Thanx tsujan, that worked.
