### ISSUE TITLE
Cannot open files in terminal applications with kitty integration

### ISSUE THREAD

**Issue by BowDown097** [lxqt/pcmanfm-qt#1520]
##### Expected Behavior
Terminal application (ie. Neovim) runs as intended.

##### Current Behavior
Kitty gives error "Failed to launch child: (null) With error: No such file or directory"

##### Possible Solution
Some extra, null argument is given to kitty for some reason before the actual thing to execute, as you can see here:
![image](https://user-images.githubusercontent.com/42720004/150680368-f6a95bb9-98d1-4605-aee9-5eae266fb75e.png)
Taking the command and removing the null argument makes everything work as intended.

##### Steps to Reproduce (for bugs)
1. Set terminal integration to kitty
2. Open file with a terminal application, for example, Neovim
3. A wild bug appeared!

##### Context
Neovim is my go-to text editor, and kitty is my go-to terminal emulator, and not being able to run things in this context means that I am forced to use another text editor that's not terminal based, switch to another terminal emulator, switch to another file manager, or open things in Neovim in kitty myself manually, which is rather inconvenient.

##### System Information
* PcManFm-qt version: 1.0.0
* Distribution & Version: Artix Linux 5.16.2
* Qt Version: 6.2.2
* liblxqt Version: 1.0.0
* Kitty Version: 0.24.1

**Comment by tsujan** [comment]
Yes, `kitty` has no special option for execution and that isn't considered by `libfm-qt`. I'll fix it soon. Thanks!

To circumvent the problem for yourself, you could open `/usr/share/libfm-qt/terminals.list` as root and add `open_arg=` under `[kitty]`, like this
```
[kitty]
open_arg=
desktop_id=kitty.desktop
```
