### ISSUE TITLE
"Extract Here" does not ensure a containing directory with xarchiver

### ISSUE THREAD

**Issue by Partmedia** [lxqt/pcmanfm-qt#1523]
The structure of an example archive is:

```
$ tar -tf test.tar
test.txt
test2.txt
```

That is, two files without a containing directory.

##### Expected Behavior

When archiver interegration is set to xarchiver, extracting *test.tar* should ensure a containing directory; i.e. creates a *test/* folder, then extract the files inside that folder.

This the behavior when using *lxqt-archiver* in the archiver integration.

##### Current Behavior

Extracting *test.tar* puts the two new files in the current directory, which allows tar-bombing.

##### Steps to Reproduce (for bugs)
1. Create *test.tar* as shown above
2. Set archiver integration to *xarchiver*
3. Use right click, "Extract Here"

##### Context
Tar-bombing is unpleasant. Work-around of "Extract to..." is annoying because the default destination is not the current working directory, and "Ensure a containing directory" starts unchecked.

##### System Information
* PcManFm-qt version: 1.0.0
* Distribution & Version: FreeBSD 13.0-RELEASE-p6
* Qt Version:qt5-gui-5.15.2p263
* liblxqt Version: 1.0.0

**Comment by tsujan** [comment]
The archive manager in question should ensure a containing directory. pcmanfm-qt isn't responsible for its behavior.

LXQt's archive manager is `lxqt-archiver`. If you see a similar problem in it, please open a report at its repository.
