### ISSUE TITLE
Ignoring tildes when shorting

### ISSUE THREAD

**Issue by es20490446e** [lxqt/pcmanfm-qt#1526]
### System
- pcmanfm-qt 1.0.0
- qt 5.15.2
- liblxqt 1.0.0
- Manjaro

### Steps to reproduce
- Create dirs "alpha" "álpha" "beta"

### Result
- Dirs are shorted like: "alpha" "beta" "álpha"
- It should be: "alpha" "álpha" "beta"

**Comment by tsujan** [comment]
Not reproducible. Here, the order is alpha → álpha → beta when sorting by file name.

**Comment by es20490446e** [comment]
This is what I'm seeing:
![Screenshot_20220206_225941](https://user-images.githubusercontent.com/9594332/152703129-7a42419a-02b3-4221-8d4b-3d949b24df02.png)

Maybe related with the combination of upper and lowercase too.

**Comment by tsujan** [comment]
Which actions are checked in the right-click menu → Sorting submenu inside that folder?

**Comment by es20490446e** [comment]
https://youtu.be/TqCkCxPf6rQ

**Comment by es20490446e** [comment]
It's seems that the menu doesn't appear in the recording, but I'm changing all the options.

**Comment by tsujan** [comment]
Magnified screenshot:

![sorting](https://user-images.githubusercontent.com/981076/152706362-7cf0d03b-988d-4155-90fb-f8dc74df5695.png)

**Comment by tsujan** [comment]
Locale is also a factor. Here it's US English. Different locales may result in different sortings for á/À/.... That's handled by Qt.

**Comment by es20490446e** [comment]
Ah, true true. It was the "collation and shorting" property.

Thanka.
