### ISSUE TITLE
[UI] About dialog ignores link text colour

### ISSUE THREAD

**Issue by libalis** [lxqt/pcmanfm-qt#1533]
![PCManFM-Qt](https://user-images.githubusercontent.com/45124869/154369166-0c836805-e561-43e0-9fc9-a77b63674faf.png)

As you can see on the right side of the screenshot, I have set the link text colour in lxqt to pink, but this has no effect on PCManFM-Qt.

##### System Information
PCManFM-Qt version: 1.0.0
Distribution & Version: openSUSE Tumbleweed
Qt Version: 5.15
liblxqt Version: 1.0.0

**Comment by tsujan** [comment]
Already fixed in https://github.com/lxqt/pcmanfm-qt/commit/6ce631228d4f12ac5411766468ba8448bc579809

**Comment by libalis** [comment]
Please excuse me, didn't see that, thank you for everything.

**Comment by tsujan** [comment]
Only by chance I noticed (and fixed) this minor problem before your report. Bug reports are welcome, especially against the latest release.
