### ISSUE TITLE
pcmanfm-qt --desktop-pref <NAME> is counterintuitive

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1535]
Small issue but` pcmanfm-qt --help` states

```
  --desktop-pref <NAME>       Open desktop preference dialog on the page with
                              the specified name
```
Names I found are bgPage, slidePage etc but none of them seem to work. Same for ` pcmanfm-qt --show-pref displayPage.

Didn't test -p <profile> option yet.
`

##### Expected Behavior

cli options  listed should work.
                                   

##### System Information

* PcManFm-qt version: 1.0.0

**Comment by stefonarch** [comment]
Ok, by case I found out: only the name without <Page> is required.
`pcmanfm-qt --show-pref display`
`pcmanfm-qt --desktop-pref slide`

**Comment by tsujan** [comment]
Actually, I tested it (as well as `--show-pref <NAME>`)  recently, The names are those in the ui file(s). It isn't very helpful because the user can't be sure about `<NAME>`. I wanted to make it case-insensitive but that wasn't useful either because there are apparent names with spaces, while `<NAME>` can't contain space.

So, I left it as it was.

**Comment by tsujan** [comment]
I think we should do something about these two options. They're counterintuitive. Perhaps we should use the apparent names case-insensitively, but I don't know what we could do about names that contain spaces.

**Comment by tsujan** [comment]
What makes it worse is translation: how should a user know that he should type "general" when he doesn't see the English GUI?

**Comment by tsujan** [comment]
OK, there are two ways: either (1) add two other options that list the page names or (2) give the pages by their numbers (starting from 0), not their names.

(1) isn't practical, IMO. Why should the user first type an option to find names and then put them in front of another option?!

@stefonarch, is (2) acceptable?

**Comment by stefonarch** [comment]
In the mean time I thought something like this:
` --show-pref  [general|bg|slide|advanced]        Open Preferences dialog on the specified tab

`

**Comment by tsujan** [comment]
Yes, that's the best solution. Thanks!

**Comment by tsujan** [comment]
Did it in https://github.com/lxqt/pcmanfm-qt/pull/1536 without changing translatable strings; translations just need to be updated.
