### ISSUE TITLE
[Feature request] set font size in settings

### ISSUE THREAD

**Issue by bobblkabb** [lxqt/pcmanfm-qt#1541]
Running pcmanfm-qt on void linux/wayfire. Can't set fonts size. Think this should be a configuration setting.

**Comment by tsujan** [comment]
An app's font (size, type, etc.) should follow the DE's font. Setting a separate font (or style) for an app is bad practice.

> Running pcmanfm-qt on void linux/wayfire. Can't set fonts size.

That should be reported to wayfire.

**Comment by DreamMaoMao** [comment]
The pcmanfm-qt font is so small that the qt5ct Settings do not take effect on it, the other wayland sizes on the platform are normal, and changing the system font to make it larger will make the other fonts on the system very lar
