### ISSUE TITLE
Command line to change things in LXQt's appearance

### ISSUE THREAD

**Issue by cleversonlira** [lxqt/pcmanfm-qt#1543]
**Command Line to hide shortcut icons in desktop**

**The following command changes the background image: pcmanfm-qt --set-wallpaper=/usr/share/lubuntu/wallpapers/hipcom_wallpaper.jpg --wallpaper-mode=fit
It would be helpful if we had more commands to change other things like hiding desktop icons and changing panel icons**

**Comment by BertolotoLucas** [comment]
I had the same idea yesterday, thanks to share it!

**Comment by tsujan** [comment]
I'm afraid we have no plan to add commands/options for everything.

Neither LXQt's appearance nor Panel is a part of pcmanfm-qt.
