### ISSUE TITLE
[Feature request] Cannot write inside Windows HDD after mount

### ISSUE THREAD

**Issue by terremoth** [lxqt/pcmanfm-qt#1544]
When I enter in a mounted drive (example: the 320gb volume that is a Windows 10 whole hdd)

![image](https://user-images.githubusercontent.com/11032344/156929306-2b6f60ae-9310-482b-9a23-2805be20a330.png)

I cannot enter on it and write files in my Windows Desktop or any other folder. I NEED and I HAVE to write files on those NTFS disks.

Sorry if "there is a way to enable that" and I don't know. If not, this is just a feature request.

**Comment by tsujan** [comment]
Not an issue in pcmanfm-qt. Install GVFS completely.

**Comment by terremoth** [comment]
@tsujan but I already have it all installed

![image](https://user-images.githubusercontent.com/11032344/156931496-f4ea4351-68b8-4c09-8edb-2587094773b0.png)

If there is something I should do more, Idk

**Comment by tsujan** [comment]
This is pcmanfm-qt's bug tracker. There may be various reasons why an NTFS partition is mounted read-only. I'm not an expert on Windows but I know that your problem isn't related to pcmanfm-qt (like many other file managers, it just uses GVFS); hence closing the report.

You could use https://github.com/lxqt/lxqt/discussions for asking general questions but, before that, please search in the forums of your distro. Also, lots of similar questions can be found by googling.
