### ISSUE TITLE
some screenshots with screengrab may have a big horizontal gray beam in all views if they are located on a external device

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1548]
steps to reproduce
it does not happen for all screenshots, but with some screenshots the last weeks:
1: open Firefox and maximize Firefox
2: open ScreenGrab
3: make a screenshot of the the full-screen
4: save the screenshot on a external device like a SD-card

actual result in PCManFM-qt in all views
- some screenshots with ScreenGrab have big horizontal gray beam (although if I mark a picture, and then I press enter, I don't see a big horizontal gray beam, so the picture is fine)
- the beams have all the same size
- the beams do not appear any more when I cut out the images and paste them on the SSD
- the beams do not appear any more when I cut out the images and paste them on the SSD, and then from the SSD back on the SD-card

my 0.17.0 is old (in Lubuntu 21.10), but I still don’t know how to install the latest version;
if the issue does not appear in 1.0.0 any more, then I’m sorry for this report

![gray_horizontal_beam](https://user-images.githubusercontent.com/68117017/158076495-72bb42c3-b335-49ee-9fe3-a836ca438ab4.jpg)

**Comment by ralf3u** [comment]
I can't reproduce the issue on a microSD-card, so maybe the SD-card is damaged?

**Comment by stefonarch** [comment]
It looks like a damaged file, sure no issue of screengrab.

**Comment by tsujan** [comment]
> ... a big horizontal gray beam...

It isn't a beam. The file is being created slowly and its thumbnail is being updated. For some reason, the update stops and the result is an incomplete image.

It rarely happened in old times with slow drives but was fixed. If I see it with the latest git, I'll open an issue.
