### ISSUE TITLE
Thumbnails not used in file properties dialog

### ISSUE THREAD

**Issue by probonopd** [lxqt/pcmanfm-qt#1549]
##### Expected Behavior

Thumbnails should be used in the file properties dialog.

##### Current Behavior

Thumbnails are not used in the file properties dialog.

![image](https://user-images.githubusercontent.com/2480569/158079788-bd5a0af4-814b-47cd-8d01-db11ffd08d5a.png)

##### Steps to Reproduce (for bugs)

1. Install a thumbnailer
2. View a file that has a thumbnail. In the files view it works
3. Richt click, select "Properties"
4. See the wrong icon (not using the thumbnail

##### Context

Reference: https://github.com/helloSystem/Filer/issues/146

##### System Information

* PcManFm-qt version: 1.0.0
* Distribution & Version: FreeBSD 13.0-RELEASE
* Qt Version: 5.15.2
* liblxqt Version: 1.0.0

**Comment by tsujan** [comment]
> Thumbnails should be used in the file properties dialog

No. Only the icon should be used there.

**Comment by probonopd** [comment]
> No. Only the icon should be used there.

Why?

**Comment by tsujan** [comment]
> Why?

Thumbnail isn't a file property but a FM feature. (The question is deleted by the reporter.)

**Comment by probonopd** [comment]
Yes, got it. Thanks!

**Comment by tsujan** [comment]
The question was valid. Answered it in case others have the same question.
