### ISSUE TITLE
Rare and random issue in sticky desktop items

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#1556]
With `Desktop Preferences → Make all items stick to their positions` checked, very rarely, a newly created item may move without a good reason, although the Desktop geometry hasn't changed (the screen size and the space taken by panels aren't changed) and nothing has been dragged and dropped on Desktop.

I know that this isn't a good description of the problem but it happens so rarely that I haven't been able to find a way of reproducing it. I've just seen that a recently created item (especially a folder) may jump into the next grid rectangle without a DND and push the next items forward. I still haven't found a line of code that could do that.

Opened for further investigation.

**Comment by tsujan** [comment]
Ah, at last found the cause! It was about DND into folders on Desktop (before creating a new folder on Desktop). Because of precautions that were added to other parts of the code, the bug only appeared with a special icon arrangement as well as a special order of DND and file creation; that was the reason why most users didn't see it.

Will make a PR.

**Comment by tsujan** [comment]
For the sake of completeness, this is a way of reproducing the bug:

 1. Check `Desktop Preferences → Make all items stick to their positions`.
 2. Add at least as many items to Desktop as needed for creating two columns at the left.
 3. Remove the bottom items, so that an empty row is created at the bottom of Desktop.
 4. Create a new folder on Desktop. It'll appear in the leftmost cell of the empty row, as it should.
 5. Drop a file from pcmanfm-qt's window into that folder by DND.
 6. Create another folder on Desktop.

Then, the magic happens: the second folder takes the place of the first one and pushes it to the top of the second column, pushing that column downward — *as if it was dragged and dropped there* (while it's just created, not dropped).

**Comment by stefonarch** [comment]
Here the folder or files switch place in the bottom row.

**Comment by tsujan** [comment]
Yes, the apparent behavior depends on several factors, but the bug is fixed in https://github.com/lxqt/pcmanfm-qt/pull/1557 for all situations.
