### ISSUE TITLE
Custom item positions on desktop are never saved

### ISSUE THREAD

**Issue by BowDown097** [lxqt/pcmanfm-qt#1558]
##### Expected Behavior
Custom item positions should be saved to the respective desktop-items-X.conf file.

##### Current Behavior
The "saveItemPositions" method seems to be called in the onAboutToQuit event for the desktop, but as far as I know it does nothing, or at least all the ways I quit the desktop (shutting down my PC, sending signals) either don't fire the method or cause some kind of breakage.

##### Possible Solution
The only way I could see a fix for this issue is making item positions save every time they change rather than just when the application detects it's exiting. I don't see why this wasn't done in the first place, considering the only issue I can think might crop up is the UI thread being blocked, which could just be solved by simple threading anyway, and other desktops do this just fine. Was this tried before and some other problem(s) came up?

##### Steps to Reproduce (for bugs)
1. Move some icons around
2. Reboot, send kill signal, do anything like that
3. No save :(

##### Context
This is a very annoying issue for me. I'm big on desktop organization, and this makes doing so effectively impossible without manually modifying the configuration file (which I had to resort to). I do not recall having such an issue when I used PCManFM's desktop.

##### System Information
* PcManFm-qt version: 1.0.0
* Distribution & Version: Artix Linux OpenRC 5.16.16
* Qt Version: 6.2.4 (5.15.3 for Qt5, if that's what's used)
* liblxqt Version: 1.0.0

**Comment by tsujan** [comment]
Not reproducible.

Perhaps you don't use an LXQt session and, in the session you use, the app isn't terminated cleanly when you log out or reboot.

**Comment by tsujan** [comment]
> send kill signal

That's the reason. You kill the app (`SIGKILL`), instead of terminating it (`SIGTERM`).
