### ISSUE TITLE
File manager actions for toolbar

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/pcmanfm-qt#156]
I assume file manager actions with TargetToolbar=true and TargetLocation=true are not supported?
I do not see my test custom action anywhere.
If not on toolbar, it should at least be in Tool menu?

**Comment by PCMan** [comment]
TargetToolbar is not supported. Yes, it might be a good idea to put it in the tool menu.

**Comment by tsujan** [comment]
Custom file manager actions are shown by the context menu. It isn't a good idea to clutter the tool-bar with them; the tool-bar has no extra space for them.
