### ISSUE TITLE
[Feature request] Show AppImage Icon

### ISSUE THREAD

**Issue by ahsand97** [lxqt/pcmanfm-qt#1560]
Based on this [issue](https://github.com/AppImage/AppImageKit/issues/346) where they're asking to how to set the icon to a .AppImage file itself I can see that it was implemented for type 1 AppImages but that feature was replaced for the daemon [appimaged](https://github.com/probonopd/go-appimage)

What I would like to see (Corebird AppImage):
![image](https://user-images.githubusercontent.com/32344641/160752293-f5938b0a-5309-4714-8ef6-5cc7f9489cce.png)

The appImaged daemon works great, it scans for specific locations to check .AppImage files, copy them to a specific location, extract their icons and create .desktop files so you can see the applications as if they were "installed" on the menu, but...again, is not what I'm asking cuz if you open a file manager and go to the "AppImages" folder you'd see that all of them have the generic AppImage icon still.

Also based on the description provided [here](https://appimage.org/) for AppImages: 
**"As a user, I want to download an application from the original author, and run it on my Linux desktop system just like I would do with a Windows or Mac application."**

I think it would be nice if pcmanfm-qt had the ability to display the .AppImage icon to the file itself whenever you open any folder that contains AppImages (just like portable .exe files on Windows) and if you really want to integrate those AppImages then you can use the appimaged daemon to create menu entries of them.

Based on this [comment](https://github.com/AppImage/AppImageKit/issues/346#issuecomment-1060008016) it seems like the correct way is to implement that feature on the file manager, so, would that be possible?

**Comment by tsujan** [comment]
This isn't related to pcmanfm-qt at all. You need an icon set with a separate icon for `application-vnd.appimage`.

**Comment by tsujan** [comment]
And if you want pcmanfm-qt to have specific codes for AppImages, then sorry, it's out of question.

**Comment by ahsand97** [comment]
> This isn't related to pcmanfm-qt at all. You need an icon set with a separate icon for `application-vnd.appimage`.

How would yo do that?? what I was asking for if for example you create an .AppImage and I download it and open the download folders with pcmanfm-qt I want to see the icon of the application for that app, and if I create an .AppImage I want to see the icon I chose for the app.


I created this AppImage and the .AppImage file with pcmanfm-qt shows the same icon for all .AppImages and what I want is to have the pink icon (the one in the task bar) just for the .AppImage file (not for all .AppImages), just like many porrtable .exe on windows have their specific app icon
![image](https://user-images.githubusercontent.com/32344641/160759212-f3957ed2-eb8d-486c-aaac-de6f00f08ff4.png)

**Comment by tsujan** [comment]
If there's a command that can extract icons from AppImages, you could make a thumbnailer with it. See https://github.com/lxqt/pcmanfm-qt/wiki#thumbnails

If there's no command, it isn't pcmanfm-qt's job to have a special handling for AppImages.

**Comment by ahsand97** [comment]
> If there's a command that can extract icons from AppImages, you could make a thumbnailer with it. See https://github.com/lxqt/pcmanfm-qt/wiki#thumbnails
> 
> If there's no command, it isn't pcmanfm-qt's job to have a special handling for AppImages.

As always, thank you so much!

**Comment by tsujan** [comment]
You're welcome.

If you have a command that can create an image with a specific size out of an AppImage file, you could share it with others here.

**Comment by stefonarch** [comment]
Just tested github.com/realmazharhussain/appimage-thumbnailer.git and it works, after restart of Desktop module  (pcmanfm-qt):

**Comment by ahsand97** [comment]
There's also this other thumbnailer I just found out and it has support for appimages too
[xapp-thumbnailers](https://github.com/linuxmint/xapp-thumbnailers)
