### ISSUE TITLE
[Feature request] Resize icons on desktop and file manager by pressing CTRL + mouse wheel rolling

### ISSUE THREAD

**Issue by phantomcraft** [lxqt/pcmanfm-qt#1574]
This is possible on PCManFM with GTK2, but not in PCManFm-qt.

**Comment by tsujan** [comment]
Because of the possibility of customizing views and several other things, pcmanfm-qt is very different from pcmanfm. See https://github.com/lxqt/pcmanfm-qt/wiki#view-modes and https://github.com/lxqt/pcmanfm-qt/wiki#customizing-view-settings
