### ISSUE TITLE
[Feature request] Smaller icons on file manager icon view.

### ISSUE THREAD

**Issue by phantomcraft** [lxqt/pcmanfm-qt#1575]
The minimal size of big icons in PCManFm-QT is 32, in PCManFm-GTK2 is 20.

I used to deal with folders with lots of files, implementing this would be a good idea.

**Comment by tsujan** [comment]
You could use a view mode that supports smaller icons.

Apart from that, no icon set has 20-px icons; it was a bad idea in the GTK-based pcmanfm.
