### ISSUE TITLE
[Feature request] Diff/hash files in Confirm File Replacing

### ISSUE THREAD

**Issue by alansams** [lxqt/pcmanfm-qt#1577]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I try to move a file, and the Confirm File Replacing window comes up showing what appears to be an identical size.  Often, what I care about is if the file has actually changed.  If the size and time are identical, they're probably identical, but it's not a guarantee.  If size is identical but time isn't, their contents could still be identical.
I hope you feel this is lightweight enough and worth adding, but I respect the desire to keep features low.

**Describe the solution you'd like**

On the Confirm File Replacing dialog, it would be so nice to be able to have an option to diff the files.

**Describe eventual alternatives you've considered**

Instead of diffing, an option to show the hash of both files would work too.  I don't really care which -- sha256sum or anything else decent would be fine.

##### Context

It really sucks to have to go to a terminal and run a diff with the full paths.  I can right click and select Copy Path in the non-qt version, which doesn't exist in the qt version, and paste it in a terminal within quotes to handle spaces.  But, it would be so much nicer to be able to see in the Confirm File Replacing dialog to handle it right there.

**Comment by tsujan** [comment]
pcmanfm-qt isn't a diff tool, but you can use a [custom action](https://github.com/lxqt/pcmanfm-qt/wiki/custom_actions) for that.

**Comment by tsujan** [comment]
With appropriate scripts, you could make something like this:

![compare](https://user-images.githubusercontent.com/981076/166159563-c291c211-0c79-4a04-a8f7-8da3130ff414.png)
