### ISSUE TITLE
[Feature request] Custom terminal command

### ISSUE THREAD

**Issue by mizzunet** [lxqt/pcmanfm-qt#1578]
**Is your feature request related to a problem? Please describe.**

I use `foot` terminal, but pcman-qt's terminal list doesn't have foot. 
![image](https://user-images.githubusercontent.com/10193999/167145472-b3c746d2-9561-415f-b182-c6d14ab105ab.png)

**Describe the solution you'd like**

Rather than adding terminal commands to the list, can't let user choose custom command for terminal? Wouldn't that work for every  possible terminals?
That is, if Custom Command is there, I can simply let it use `foot`.

Another solution maybe, I think that, the list of terminals be the terminal emulator programs installed on the system. 
I guess, the installed programs can be discovered by looking desktop entries where `Category` is of `TerminalEmulator`.
  
**Describe eventual alternatives you've considered**

Choosing one from the list and make symbolic link to `foot` at ~/.local/bin`

##### Context

I was trying to open a text file in `nvim.desktop`

Edit:

It seems, I can edit the field to my liking,
![image](https://user-images.githubusercontent.com/10193999/167147437-7a540a83-6bbe-46e6-8e4c-0f26b722b703.png)

But the still looks for `xterm` which was previous selection
![image](https://user-images.githubusercontent.com/10193999/167147578-19bf3ec0-2759-4070-a01c-3742f6d63b2e.png)

**Comment by tsujan** [comment]
You can add any terminal command there. I tried `foot` and it worked fine under Wayland (`foot` doesn't work under X11).

**Comment by Kagukara** [comment]
Just putting `foot` doesn't work (I use footclient so its `footclient` for me). To get this working properly I had to added:

`[footclient]`
`open_arg=-e`
`desktop_id=org.codeberg.dnkl.footclient.desktop`

At the bottom of `/usr/share/libfm-qt/terminals.list`.

Doing this now allows you to open files with `footclient`, unlike before which it didn't allow you to. All you could do with putting `foot`/`footclient` in the Terminal emulator text box was Tools > Open Terminal.
