### ISSUE TITLE
(Open In Terminal) doesn't open Qterminal

### ISSUE THREAD

**Issue by YousefSaber** [lxqt/pcmanfm-qt#1579]
in the latest release of LXQT 1.1.0 
(Open in Termianl) can't open the terminal using QTerminal can you enable that in a future update? 
![image](https://user-images.githubusercontent.com/33742499/167267156-10e7686f-90c8-4405-a281-07b2e600b846.png)

**Comment by tsujan** [comment]
"Open in Terminal" opens the terminal you've set in Preferences.
