### ISSUE TITLE
[Feature request] Save/Load Search Query (in F3 dialog) or record Search History automatically

### ISSUE THREAD

**Issue by SjoerdV** [lxqt/pcmanfm-qt#1580]
**Is your feature request related to a problem? Please describe.**
I use more complex search queries quite frequently (using regex file/name patterns), filtering file type and date. It would be nice to have the history of these queries visible under a single button so I won't have to retype everything to make a small change to the regex for example.

**Describe the solution you'd like**
I would like to have the option to turn on Search History (should be off by default, because of privacy/security), which will automatically save the last x queries and have the ability to navigate to one of these saved queries from withing the Search box (F3), make a small adjustment and then run the query

**Describe eventual alternatives you've considered**
Also nice would be to have the option to save current Search Settings (everything in the F3 box) manually and have the ability to load those settings through the same 'F3' UI, make a small adjustment and then run the query.

##### Context
Regex sometimes needs some repeated 'tweaking' on my part, but I do not want to redo all other settings.

BTW: Really love all the work that's being put in on this file manager as its fast, responsive and overall very pleasant to work with.

**Comment by tsujan** [comment]
Yes, a kind of search history is needed.

**Comment by tsujan** [comment]
Didn't find a better place for the new option:

![search](https://user-images.githubusercontent.com/981076/167313395-297a807d-5eda-4931-a1e9-a57427434e49.png)

Will make two PRs for `libfm-qt` and `pcmanfm-qt` soon, after some tests.

**Comment by SjoerdV** [comment]
Cool, maybe add a checkbox to enable/disable the Search History feature as well?

**Comment by tsujan** [comment]
"0" means "disabled".

**Comment by SjoerdV** [comment]
Ah, OK that's a solution as well. 0 could also mean 'infinite', I can imagine. Something for the man page or a 'mouse over context'.

**Comment by stefonarch** [comment]
> BTW, auto-completion is given to us by Qt automatically.

I see. Nice feature to have: both file pattern and content are saved.

Any idea why my desktop remains visible ( but dead) for ~15 secs when stopping desktop module?

**Comment by tsujan** [comment]
> Any idea why my desktop remains visible ( but dead) for ~15 secs when stopping desktop module?

Yes :) You use KWin, which started to do this magic recently. The desktop module is stopped correctly but KWin doesn't forget the wallpaper for 15-30 seconds (for me, it's more than 15). If you start the module in less than 10 seconds, you might see more magic, especially if you use a slide-show for the background.

**Comment by stefonarch** [comment]
I thought instead  it was caused by another of my wild compiling miracles.

**Comment by tsujan** [comment]
It started a few months ago. When I switched to compiz-reloaded, the desktop became blank as soon as its module was stopped. When I switched back to KWin, it took ~20 seconds.

Another KWin problem, which started a year ago, is about waking up the monitor: bad artifacts may appear. The workaround is switch to the next desktop and switch back.

**Comment by stefonarch** [comment]
> Another KWin problem, which started a year ago, is about waking up the monitor: bad artifacts may appear. The workaround is switch to the next desktop and switch back.

Those happen also with openbox/picom, flickering issues. My workaround is forcing monitor off before and forcing it on after suspend.
`xset dpms force off|on
`

**Comment by tsujan** [comment]
> My workaround is forcing monitor off before and forcing it on after suspend.

I didn't mean resuming from suspend — have no problem with it.

I set the idleness watcher to turn off the monitor. When the monitor is turned on (e.g., by a mouse movement), there may be artifacts with KWin, and only since a version of it. It's a regression.

They say KWin 5.25 will include important fixes but, apparently, most of them will be about Wayland.

**Comment by tsujan** [comment]
Today I found out that KWinFT doesn't have those regressions.

**Comment by stefonarch** [comment]
I tried it some  months ago,  I don't remember the issues but they make me switch back to Kwin.

**Comment by tsujan** [comment]
Fortunately, with Arch/Manjaro, switching back and forth between them is just a matter of `pacman -S ...` and logging out and in.

**Comment by stefonarch** [comment]
In arch it's in AUR, so to compile, manjaro has packaged it?

**Comment by tsujan** [comment]
Logged into plasma-wayland to check pcmanfm-qt and some other apps under Wayland. KWinFT crashed. Back to KWin...

**Comment by tsujan** [comment]
I've used search history and auto-completion for 2 days and found them very useful. This report was the best feature request in recent months :)

**Comment by SjoerdV** [comment]
Great stuff! I'm looking forward to the release

**Comment by SjoerdV** [comment]
@tsujan, just wondering if there is a way to get the latest version on a Debian-based 20.04 LTS distro? I seem to be stuck at 0.14.1 there. Same goes for the entire lxqt stack btw

**Comment by stefonarch** [comment]
> just wondering if there is a way to get the latest version on a Debian-based 20.04 LTS distro?

You can't , qt version is 5.12 but 5.15 is required.

For 22.04 there is a ppa https://lxqt-project.org/blog/2022/05/06/latest-lxqt-debian-ubuntu/

**Comment by tsujan** [comment]
> qt version is 5.12

Oh, my bad, didn't paid attention to "LTS".

LTS distros aren't for having latest releases, let alone latest commits.

**Comment by stefonarch** [comment]
Well, the recent LTS is quite a decent thing now thanks to the ppa.
https://twitter.com/staempunk/status/1520669060492525570

**Comment by SjoerdV** [comment]
@tsujan, thanks so much for the great guidance on this!

> > qt version is 5.12
> 
> Oh, my bad, didn't pay attention to "LTS".
> 
> LTS distros aren't for having latest releases, let alone latest commits.

Ah, I noticed that as well for oldered LTS 20.04 I couldn't use the PPA or the custom repo. I ended up doing:
* the full QT515 side-by-side install from https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.15.2-focal
  * fiddling around with the LD_LIBRARY_PATH on Ubuntu is quite a hassle btw
* the scripted build from source https://github.com/lxqt/lxqt/wiki/Building-from-source
  * I did change the 'make install' commands inside the 'build_all_cmake_projects.sh' script to 'checkinstall --install=no', to create deb packages without immediate installation for my distro and installing those in order (for easier troubleshooting)

I now have search history! ;-)

**Comment by tsujan** [comment]
> I now have search history! ;-)

You seem an advanced user. Why limiting yourself to LTS?

**Comment by SjoerdV** [comment]
> > I now have search history! ;-)
> 
> 
> 
> You seem an advanced user. Why limiting yourself to LTS?

I only switched from Windows a couple of months ago, so playing it a little safe felt like a good move. Maybe I'll go full 'rolling release' later this year. It's all about the journey right 😉. Again, thanks for your help here, much appreciated.

**Comment by tsujan** [comment]
> It's all about the journey right

Yes, there are so many possibilities in Linux.

LTS is for those who, for whatever reason, don't want important updates for long periods of time. By its nature, it doesn't let the user have the latest software (easily).

Distros like Ubuntu or Fedora are for those who want important updates only every six months or so — the updates will be big and, ironically, might be outdated (soon) in some cases.

Rolling distros are for those who want the latest software, with continuous updates.
