### ISSUE TITLE
[Feature request] 'Duplicate file' in same folder

### ISSUE THREAD

**Issue by SjoerdV** [lxqt/pcmanfm-qt#1581]
**Is your feature request related to a problem? Please describe.**
At the moment you can not copy a file/folder to the same location,
At the moment pcmanfm-qt asks to overwrite the same file/folder its copying... Haven't tried answering 'yes' to that, I didn't dare ;-)

**Describe the solution you'd like**
I would like a "Duplicate" command in the context menu of a file or folder (like in Nemo), preferably *all* selected files/folders

![image](https://user-images.githubusercontent.com/13275320/167292139-90fa6d4c-6113-4180-8792-ea5e16054c48.png)

The resulting file(s)/folder(s) would be a copy with the text ' copy' appended (note the space) to the file/foldername (in the case of files without the extension) in the same location as the original files/folders. No dashes, underscores or other signs, as it would hinder renaming afterwards. even better would be if the text that is appended is a user setting, maybe '-copy' is better for some.

**Describe eventual alternatives you've considered**
A shortcut key combination on a single selected file/folder would be fine too as first implementation, if that is easier to create.

##### Context
Duplicating a file is something that becomes second nature at some point it is sorely missed.

**Comment by tsujan** [comment]
Whether another file manager does it isn't relevant. This isn't a really useful feature. You can DND a file and add a string to its name, or you can make a [custom action](https://github.com/lxqt/pcmanfm-qt/wiki/custom_actions) for it.

**Comment by tsujan** [comment]
@SjoerdV 
Thanks! The more examples of custom actions we provide, the more users get familiar with this flexible feature.

Personally, I can't use a file manager without it — having > 30 custom actions.
