### ISSUE TITLE
[Feature request]Can we have ability to lock down desktop settings?

### ISSUE THREAD

**Issue by jointri** [lxqt/pcmanfm-qt#1582]
One thing that lxqt lacks compared to other desktop environments such as GNOME, KDE, MATE, and so on is ability to lock down settings you don't want people to change such as the desktop wallpaper or the icon theme. Can an option to lock the wallpaper from being changed be implemented? I hope I'm asking in the right repository, if not, please redirect me to where I should be asking.

**Comment by stefonarch** [comment]
The panel can be locked, and there it's really necessary. IMO  blocking pcmanfm-qt's settings is an overkill, as it's hard to change them  by accident.

**Comment by tsujan** [comment]
> The panel can be locked

That's because the user may move/delete its many widgets by mistake. Desktop isn't so.

**Comment by tsujan** [comment]
> ability to lock down settings you don't want people to change

You need a screen locker for that.
