### ISSUE TITLE
PCManFM-qt not ready for --desktop mode in plasma

### ISSUE THREAD

**Issue by ulliperk** [lxqt/pcmanfm-qt#1590]
Compared to Dolphin PcManFM-QT is lighter and faster, and it can render the KDE Desktop.
Unfortunately under Plasma5 PCManFM-QT would not expose it's menu to Global-Menu while running in --desktop mode.
Can this be fixed?

**Comment by tsujan** [comment]
@ulliperk 
You'd already opened https://github.com/lxqt/pcmanfm-qt/issues/1589. It was closed because the problem didn't belong to pcmanfm-qt.
