### ISSUE TITLE
Poor visual quality of wallpaper when QT_SCALE_FACTOR > 1

### ISSUE THREAD

**Issue by hirayaku** [lxqt/pcmanfm-qt#1595]
##### Issues

I am using lxqt with a 4K monitor. In order to have a satisfactory experience I set QT_SCALE_FACTOR to be larger than 1(following lxqt/lxqt-config#401; currently 1.5 for me). The sizes of icons, menu bar, etc. look appropriate now, but I notice that the image quality of the wallpaper becomes much poorer after the change. I cropped the same part of the screen before and after the change as below:

<img src="https://user-images.githubusercontent.com/10558628/171352667-02ca5390-b862-4b20-a3ff-043ec1918910.png" width="360" height="360"> <img src="https://user-images.githubusercontent.com/10558628/171354761-d652f3e3-4ce4-440d-8b5e-f6522f3410cd.png" width="360" height="360">
(Left: before. Right: after.)

##### Steps to Reproduce (for bugs)

1. Set a picture (preferably with rich texture and the same native resolution as the monitor) as the background
2. Unset or reset QT_SCALE_FACTOR to 1, don't set QT_AUTO_SCREEN_SCALE_FACTOR, take a screenshot
3. Set QT_SCALE_FACTOR to some value, 2 is sufficient to demo the issue. Take another screenshot and compare with Step 2.

##### Possible Solution

I have a patch here (12d0efb09d6102ccb1d175ec60f5bb926270ba8d) that seems to at least work for me. I am guided by this article from Qt which talks about drawing images properly in HiDPI devices: https://doc.qt.io/qt-5/qpainter.html#drawing-high-resolution-versions-of-pixmaps-and-images. However, the patch only works for a single monitor. I don't have multi-monitor setup and not familiar with pcmanfm-qt enough to have a general solution now.

##### System Information

* PcManFm-qt version: 1.1.0 (I am using pcmanfm-qt from the latest commit, not from the distribution-provided package)
* Distribution & Version: Debian 11
* Qt Version: 5.15.2
* liblxqt Version: 0.16.0-1

**Comment by tsujan** [comment]
Thanks for the report!

**Comment by tsujan** [comment]
The fix: https://github.com/lxqt/pcmanfm-qt/pull/1596

**Comment by hirayaku** [comment]
Thanks for the full solution!
However, I noticed a new issue caused by the patch (in both mine and yours) today: when I drag on the wallpaper background to create a selection rectangle, it will trigger `paintEvent` of DesktopWindow which redraws the wallpaper but only inside the selection rectangle. If QT_SCALE_FACTOR is an integer it's okay, but if it's a fractional number (like 1.5 in my case), due to the rounding error, the redrawn section doesn't perfectly match the original one, causing some dithering effect:
<img src="https://user-images.githubusercontent.com/10558628/171548494-4116f51a-15b0-4c78-8bbd-e7db5f896b4e.gif" height="320" width="320">

Why does dragging trigger the redraw of background at all?

**Comment by tsujan** [comment]
> If QT_SCALE_FACTOR is an integer it's okay, but if it's a fractional number...

It's not limited to this case. Fractional scale factors may show this kind of problem anywhere (especially if there's some kind of translucency).

**Comment by tsujan** [comment]
@hirayaku 
Please test by changing `DesktopWindow::paintBackground` in https://github.com/lxqt/pcmanfm-qt/pull/1596 to:

```c++
void DesktopWindow::paintBackground(QPaintEvent* event) {
    // This is to workaround Qt bug 54384 which affects Qt >= 5.6
    // https://bugreports.qt.io/browse/QTBUG-54384
    QPainter painter(this);
    if(wallpaperMode_ == WallpaperNone || wallpaperPixmap_.isNull()) {
        painter.fillRect(event->rect(), QBrush(bgColor_));
    }
    else {
        QRectF r(QPointF(event->rect().topLeft()) * wallpaperPixmap_.devicePixelRatio(),
                 QSizeF(event->rect().size()) * wallpaperPixmap_.devicePixelRatio());
        painter.drawPixmap(event->rect(), wallpaperPixmap_, r.toRect());
    }
}
```

It worked here but that may be pure luck (specific screen dimensions).

**Comment by hirayaku** [comment]
I can confirm the fix also works for my monitor. Looks great now!

**Comment by tsujan** [comment]
Thanks for testing!

**Comment by hirayaku** [comment]
I can't reproduce #1597 on my side. I am using xfwm.

**Comment by tsujan** [comment]
It turned out that the problem was in Qt and had nothing to do with wallpaper painting. Some may see it with a scale factor of 1.5, some with another fractional factor — and in any Qt app.
