### ISSUE TITLE
"Single window mode" is not respected

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1598]
Conditions:
PCManFM-Qt-window is open
in Preferences, in Behavior, "Single window mode" is activated
in Preferences, in Volume, "Show available options for removable media when they are inserted" is activated

Steps to reproduce
open Firefox
insert one SD-Card (result: a window will appear)
click on OK

Result
a new PCManFM-Qt-window will appear, so that there are now two PCManFM-Qt-windows, although "Single window mode" is activated

Expectation
the existing PCManFM-Qt-window should appear, so that there is only one PCManFM-Qt-window
a new tab in PCManFM-Qt should appear with the content of the SD-Card

my 0.17.0 is old (although I use Lubuntu 22.04), but I still don’t know how to install the latest version;
if the issue does not appear in 1.1.0 any more, then I’m sorry for this report

**Comment by tsujan** [comment]
0.17.0 is too old.

I didn't understand the relation of SD-Card to Firefox. With the latest release, Firefox and other browsers show files by opening tabs in the exiting window when the single-window mode is activated. Also, with [LXQt's patch for `xdg-utils`](https://gitlab.freedesktop.org/xdg/xdg-utils/-/merge_requests/48), Panel's mount plugin opens the volume in a new tab of the same window. There's no problem to fix.

**Comment by ralf3u** [comment]
>I didn't understand the relation of SD-Card to Firefox.

I just mentioned Firefox to put an other program in focus than PCManFM-Qt. The reported issue itself has nothing to do with Firefox.

> Also, with [LXQt's patch for xdg-utils](https://gitlab.freedesktop.org/xdg/xdg-utils/-/merge_requests/48), Panel's mount plugin opens the volume in a new tab of the same window. There's no problem to fix.

OK, so issue was fixed with that patch.

**Comment by tsujan** [comment]
> OK, so issue was fixed with that patch.

That patch isn't directly related to pcmanfm-qt but opens volumes in it under LXQt. It fixes mimetype handling, so that volumes aren't opened by irrelevant apps.

As for issues, there have been so many changes and fixes since 0.17.0. We'd appreciate it if reports aren't made against very old versions.

**Comment by stefonarch** [comment]
> my 0.17.0 is old (although I use Lubuntu 22.04), but I still don’t know how to install the latest version;

https://lxqt-project.org/blog/2022/05/06/latest-lxqt-debian-ubuntu/
