### ISSUE TITLE
network browsing does not work at all

### ISSUE THREAD

**Issue by pvanek** [lxqt/pcmanfm-qt#16]
Location: Network. There I have many icons of correctly discovered network devices.

When I click to any of icon, new window with local filesystem root (/) is opened.

It does not matter if network device is FTP, SMB, AFP, or SSH (probably) device.

**Comment by pmattern** [comment]
Running latest Git code of all LXQt components on Arch Linux i686 or x86_64 some problems like #108 still exist but basically everything works pretty well.
Tests performed using FTP, SFTP or SMB, the latter in a pretty rudimentary way only.

So actually I think this one can be closed.

@pvanek Any chance to verify?

**Comment by agaida** [comment]
it can now be closed - the very most important bugs should be fixed.
