### ISSUE TITLE
automatic screenrotation adaption for convertibles or tablets

### ISSUE THREAD

**Issue by ulliperk** [lxqt/pcmanfm-qt#1602]
Strange behaviour of PcManFm-qt if being used on a tablet pc or convertible.
if pcmanfm is running in --desktop mode  it can not adapt to the changing screen orientation when the screen is rotating.

**Comment by tsujan** [comment]
Which version of pcmanfm-qt?

**Comment by tsujan** [comment]
Please also describe the problem more specifically (what's the current behavior and what's the expected behavior?) and follow the issue template when reporting.

**Comment by ulliperk** [comment]
Version: Pcmanfm-qt version 0.17.0 ubuntu1 impish

I tried PCManFM-Qt File Manager For A Spin In KDE Plasma like mentioned in article below: 
https://www.kdedigest.com/2018/03/taking-pcmanfm-qt-file-manager-for-spin.html
and came across several inconveniences. 

System: KDE Plasma 5.24.4, kubuntu 22.04 
Pcmanfm-qt version 0.17.0 ubuntu1 impish

Esperiences:

1)   In an X11 plasma session:
1-1) When Pcmanfm-qt renders the desktop with "--desktop" it would prevent the user from logging out. 
1-2) Pcmanfm-qt does not expose it's menu to plasma global Menu (Global Menu 2.0) while rendering the desktop.

2)   In a plasma Wayland session:
2-1) Pcmanfm-qt desktop is freely moveable by a mouse click. 
2-2) when rotating the screen Pcmanfm-qt desktop behaves unpredictable, cuts its desktop into half or quarter of screen size..
2-3) Pcmanfm does not expose it's menu to plasma global Menu (Global Menu 2.0)  while rendering the desktop.
       (same as in 1-2)

What i suggest:
1)  working with plasma global menu:
     Pcmanfm-qt is light and fast and on plasma could be a serious alternative to Dolphin.
     Other than dolphin it can render the desktop and with some changes in code
     it could even be used like 'MacOS's filemanager 'Finder' if it could expose its menu while desktop mode is active. 
2)  For work with tablets and convertibles it could  be an advantage if the wayland rotation issue could be fixed.

**Comment by tsujan** [comment]
> In an X11 plasma session.... When Pcmanfm-qt renders the desktop with "--desktop" it would prevent the user from logging out.

KDE is responsible for logout under KDE. If it can't log out under certain circumstances, it needs a fix.

> Pcmanfm-qt does not expose it's menu to plasma global Menu

Apps aren't responsible for "exposing" their menus.

> In a plasma Wayland session...

pcmanfm-qt's desktop may work fine with a Wayland compositor like Wayfire by chance (as reported by users — I saw problems under Wayfire), but there's no guarantee that it works with others. Wayland itself is the problem. Codes that work with Wayland should be compositor-specific, while pcmanfm-qt's code is independent of all compositors.

**Comment by tsujan** [comment]
BTW, pcmanfm-qt 0.17 is outdated. The latest release is 1.1.0. However, the version makes no different in this case.
