### ISSUE TITLE
[Feature request] Allow distributions to add "permanent" desktop entries

### ISSUE THREAD

**Issue by tsimonq2** [lxqt/pcmanfm-qt#1603]
The Lubuntu project has [a manual](https://manual.lubuntu.me/) which we would like to ship as a desktop entry. [This patch](https://github.com/lxqt/pcmanfm-qt/files/8924327/patch.txt) exists downstream in Lubuntu to just manually add it.

In the spirit of collaboration, I wanted to submit this upstream for some eyes and potentially some ideas on how such an idea should be properly implemented. I am open to any ideas.

Thanks for your time.

**Comment by tsujan** [comment]
Thanks for telling LXQt about that!

I'm afraid, distro-specific patches are not recommended. If accumulated, they might invalidate the bug reports by users of the distros in question. The developers don't have extra time and energy to keep track of them or investigate how they may affect performance.

Personally, I've found that Ubuntu users' reports have recently become much more acceptable than they were a few years ago. I beg you not to change that by applying extra patches.
