### ISSUE TITLE
[Feature request] Insert "Categories="  in  Tools > Create Launcher

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1605]
**Is your feature request related to a problem? Please describe.**

To create menu entries in `~/.local/share/applications` it's quite perfect, but the line  `Categories=` has to be entered using a text editor afterwards.

**Describe the solution you'd like**

A field with a dropdown    containing allowed categories would be nice.

**Comment by tsujan** [comment]
The purpose of that action is the easy creation of a launcher that can be clicked and launched inside pcmanfm-qt. ` Categories` doesn't have an impact on that.

Of course, the created desktop entry can be edited and used for other purposes, but that's not pcmanfm-qt's job. Moreover, there are several other keys, like `NoDisplay`, `OnlyShowIn`, `StartupNotify`, `MimeType`, ...

To remain self-consistent, I think we shouldn't add extra keys here.
