### ISSUE TITLE
[bug] Hangs(freezes) forever if tried to mount another encrypted disk while the first one is being mounted

### ISSUE THREAD

**Issue by gornvan** [lxqt/pcmanfm-qt#1608]
I'm sorry I must say I'm reporting for version 0.16.0. I've read the release notes and didn't find such fix between that version and the latest release. Much love to you guys for maintaining this awesome file manager!

##### Expected Behavior
Allow to start mounting the second encrypted disk in parallel while the first is being mounted.

##### Current Behavior
If the second disk gets clicked while the first one is being mounter (right after password gets entered and submitted), The Application hangs until it gets restarted.

##### Possible Solution
I guess the memory for awaited job status is re-used by the new job awaiting process, instead of a new data structure initialization.

##### Steps to Reproduce

1. Have at least two encrypted volumes
  1.0 create two volumes as you like;
  1.1 encrypt them both, for example(as it is in my setup), with `cryptsetup luksFormat <volume> --verify-passphrase`;
  1.2 "open" them both **via CLI** via `cryptsetup luksOpen <volume> <alias>`;
  1.2 format them with something, e.g. `mkfs.fat /dev/mapper/<alias>`;
  1.3 "close" them both via `cryptsetup close <alias>`
  1.3. (do not try to mount them one by one via GUI, otherwise the App will remember the key and we'll have to reboot... or something);
2. Click on the first one in the left panel, input whatever required(e.g. password) and submit;
3. Without waiting for the mounting to complete and for the volume directory to open, click on the second disk.
4. Observe the frozen, hanging dead app - have to close it forcefully.

Frankly, I'm not sure it's required to have the volumes encrypted. Might be that clicking fast enough on two ordinary mountable volumes would cause the same. But I can tell that the Application remembers the password(or whatever) and doesn't freeze if i mount the things without being prompted for password, so the bug is probably somewhere in the interactions with the sub-window. Or not.

##### Context
`How has this issue affected you? What are you trying to accomplish?`
Just being me and trying to click things faster. Thus using one of the lightweight distros. ;)
I suppose the mounting happens via cryptsetup luskOpen. At least that's how I do it when not in GUI.

##### System Information
- **PcManFm-qt version:** 0.16.0 with LXQt 0.16.0
- **Distribution & Version:** Lubuntu dunno how to get the version, qtdiag says it's Ubuntu 21.04
- **Qt Version:** 5.15.2 (from output of `qtdiag`)
- **liblxqt Version:** 0.16.0-1ubuntu2

**Comment by tsujan** [comment]
→ https://github.com/lxqt/libfm-qt/commit/1b734eccc3e53da0422573341c840ff925d8d06d and related commits.

V0.16 isn't old; it's ancient ;) LXQt is released twice a year.
