### ISSUE TITLE
[Feature request] Wayland support in Desktop manager via Layer Shell Qt

### ISSUE THREAD

**Issue by Sunderland93** [lxqt/pcmanfm-qt#1614]
**Is your feature request related to a problem? Please describe.**

Currently, pcmanfm-qt's desktop manager has no Wayland support, so it impossible to place any icons or files on a desktop

**Describe the solution you'd like**

This support may be added via [layer-shell-qt](https://invent.kde.org/plasma/layer-shell-qt), which is Qt wrapper for [wlr-layer-shell](https://github.com/swaywm/wlr-protocols/blob/master/unstable/wlr-layer-shell-unstable-v1.xml) Wayland protocol. It supported by all Wlroots-based compositors, Kwin and Mir. PcManFM (GTK version) have [this PR](https://github.com/lxde/pcmanfm/pull/4) to implement such functionality (but via gtk-layer-shell)

**Describe eventual alternatives you've considered**

Maybe custom desktop shell protocol

##### Context

I like to use pcmanfm-qt with LabWC wayland compositor, to create lightweight Wayland desktop

**Comment by tsujan** [comment]
Thanks, but It isn't likely that LXQt can decide on a Wayland compositor soon. Until then, we can't add any wayland-specific code.

Search in https://github.com/lxqt/lxqt/issues/10 for good explanations — sadly, there are many unrelated comments there, and you might need to find the needle in the haystack.

**Comment by stefonarch** [comment]
OT: this default text "closed as completed" appears now for some time, is there any way to change it? Sometimes it's really out of place.

**Comment by stefonarch** [comment]
https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue

**Comment by tsujan** [comment]
@stefonarch 
Thanks! Either that menu is a new addition or I haven't seen it before.

It has 3 problems: (1) it's redundant (labels exist), (2) it's limited to two options, and (3) it can't be changed. Labels don't have these problems.

**Comment by stefonarch** [comment]
I noticed that some weeks ago. The options should be more and/or allow custom text.

**Comment by stefonarch** [comment]
> It isn't likely that LXQt can decide on a Wayland compositor soon

If I understand this correctly it's compatible with many compositors. My idea is that LXQt should remain "compositor agnostic" as far as possible.

**Comment by tsujan** [comment]
> My idea is that LXQt should remain "compositor agnostic" as far as possible.

I agree completely. Also, → https://github.com/lxqt/lxqt/issues/10#issuecomment-1267000696
