### ISSUE TITLE
Dialog doesn't quit and high CPU usage when linking files in some condition

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1618]
![screen-25 lug_14:34](https://user-images.githubusercontent.com/10681413/180780581-f2072214-ba2d-40f4-8b9b-934ef84c9a37.jpg)

![screen-24 lug_22:35](https://user-images.githubusercontent.com/10681413/180780587-e7b2f951-97ed-4e43-ba16-42c0a347d51a.jpg)
##### Steps to Reproduce (for bugs)

1. Split view in pcmanfm-qt, with 2 different folders, one empty
2. copy one folder from the first view to the empty one
3. mark more folders and drag them over
4. select "link here"
5. the pop-up ask to overwrite or not: overwrite to all
6. see screens attached, action is completed but the window doesn't close.

It looks like overwriting symbolic links when copying isn't working too.
##### Context

Working on themes, 
##### System Information

* PcManFm-qt version: 1.1.0
* Distribution & Version: debian testing
* Qt Version: 5.15.4-2
* liblxqt Version: 1.1.0

**Comment by tsujan** [comment]
Thanks!

More easily:

 1. Make a folder with a file in it.
 2. Copy it to another directory.
 3. Drag and drop the first folder to that directory and select "Create symlink here".
 
Then an infinite loop starts. It stops only when cancel the operation (soon).

**Comment by stefonarch** [comment]
I thought there are easier ways, but I was fighting other battles. It's also the other way round, overwriting copies with symlinks,

**Comment by tsujan** [comment]
Will look into it soon; it's a bad bug.

**Comment by tsujan** [comment]
Ok, GLib doesn't overwrite a directory with a symlink (to a directory or file) — it gives an error message. So, there's a code in `libfm-qt` that tries to circumvent that to no avail. I'm looking into it...
