### ISSUE TITLE
Unable to "Open With..." the "Choose an Application" dialog is empty

### ISSUE THREAD

**Issue by mapsedge** [lxqt/pcmanfm-qt#1624]
##### Expected Behavior
When choosing "Open With..." the "Choose an Application" dialog should list applications on the system.

##### Current Behavior
When choosing "Open With..." the "Choose an Application" dialog DOES NOT list applications on the system. The dialog stays blank.

##### Steps to Reproduce (for bugs)
1. In PCManFM-QT, select a file whose type is unknown to the OS, or for which you want to change the file association.
2. Select "Open With..." from the context menu
3. Select "Other Applications" from the sub-menu
4. Behold the vast expanse of space remaining determinedly empty of other applications

![Screenshot_20220805_160938](https://user-images.githubusercontent.com/41483625/183200857-3ccda8b6-bf67-44c7-b873-276bd9c8f118.png)

##### Context
The issue affects productivity, interrupting the task at and and throwing off the emporers' groove.

##### System Information

* PcManFm-qt version: 0.17.0
* Distribution & Version: Kubuntu 22.04LTS
* Qt Version: 5.15.3
* liblxqt Version: no idea how to check

**Comment by tsujan** [comment]
Not reproducible:

![unknown](https://user-images.githubusercontent.com/981076/183206445-a11d0bc7-b042-492e-950d-211e2164dac1.png)

> PcManFm-qt version: 0.17.0

Outdated.
