### ISSUE TITLE
enhance creating new folders

### ISSUE THREAD

**Issue by pmattern** [lxqt/pcmanfm-qt#163]
New folders can be created by accessing the context menu available over blank space in right pane only. This menu can't be accessed if e. g. in Directory Tree view a folder is opened the content of which is filling all vertical space and the horizontal space available is limited.
Within the left pane folders can't get created at all.
So I'd suggest to add an item to create new folders to the context menu of folders both in right pane and in left pane's Directory Tree view.

The regular menu as accessed from the menu bar doesn't comprise an item to add new folders either.
I think this should be added, too.

**Comment by excalibur1234** [comment]
in dolphin and thunar you can press CTRL + SHIFT + N to create a new folder. it even works in windows. it is like a quasi-standard. but this keyboard shortcut does not work in pcmanfm-qt.

is there already another keyboard shortcut to create a new folder in pcmanfm-qt or can you add this keyboard shortcut?
it is not comfortable to keep switching between the mouse and keyboard just to create a new folder.

**Comment by pmattern** [comment]
The commit proposed in lxde/pcmanfm-qt#173 works as expected, both on i686 and x86_64 and including the keyboard shortcut.
So thanks, @ufleisch.

Yet a context menu of folders is still missing completely in tree view's left pane, the one in right pane doesn't offer creating new folders.
This may be a matter of taste but I still think at least a context menu in tree view's left pane is something pretty good to have. If feasible I think it would be good if an eventual context menu allowed for creating new folders, renaming and deleting / moving to trash.
FWIW something similar is implemented in Thunar.

(So actually I wouldn't quite agree that lxde/pcmanfm-qt#173 fixes this issue as a whole.)

**Comment by pmattern** [comment]
The last commit is just the re-factored flavour of the one proposed in #173 on May, 15.

Hence reopening for the reasons stated in my previous post.

**Comment by ufleisch** [comment]
I have just created a new pull request which should address the remaining issues.

**Comment by pmattern** [comment]
Regarding #187:

The side pane's mode is safed per session only. After login out and in again PCManFM-Qt keeps using places view upon launch.
Actually this behaviour is addressed in #157.

A context menu featuring an item "Create New Folder" was introduced in left pane. The context menu *of folders* in right pane still lacks an item like this, though.

**Comment by ufleisch** [comment]
I have added another commit which factors the "Create New" menu out to be used in both the folder and the file menu. This commit also fixes a crash which happens when the default side pane is set to the directory tree and "Open in New Window" is triggered from the folder menu of the right pane. It was caused by the context menu action accessing the menu which was already deleted (when the context menu is hidden, which is apparently too early).

Regarding the keeping of the places view after logging out and in again: A workaround is opening the preferences dialog and clicking OK, thereby saving the settings. I would consider this a bug because the settings should be saved when PCManFM-Qt is terminated in the process of logging out. I could investigate this further.

**Comment by pmattern** [comment]
If a new folder or blank file is created in the right pane by selecting a folder (left-click) and invoking 'Create New' - { Folder , Blank File } from the context menu the new object isn't created in the selected folder but in its parent folder.
The problem doesn't exist in left pane, creating new objects from the context menu over files or blank space in right pane works as expected, too.

As for saving the mode in use I can confirm the workaround you state.
Bug again I'd like to ask to go on discussing this in #157 besides it may appear a bit inconvenient so as to avoid confusion: if another user runs into the same problem and searches the tracker he'll end up in that issue and think nothing happened yet.

**Comment by ufleisch** [comment]
I have added another commit so that new files or folder are now created in the selected folder.

**Comment by pmattern** [comment]
Everything is working as expected now. Thanks for looking into this.

There's one one polish thing that *could* be considered: in submenu "Create New" in menu file there's an icon next to folder, aside from this there isn't an icon in any of the other locations ("Blank File" in menu file - "Create New", "Create New" in context menus of left and right pane altogether).
It could be considered to have this consistent somehow.

Otherwise this issue can be closed by applying recent ufleisch/pcmanfm-qt@78ba7ae.

**Comment by ufleisch** [comment]
I have added a commit for an icon in the "Create New Folder" context menu.

**Comment by pmattern** [comment]
In my last statement I wasn't referring to the inconsistencies regarding the different locations of menu "Create New" only but also regarding "Folder" vs. "Blank File".
But as also said above, just some minor polish, of course.

**Comment by ufleisch** [comment]
I have rebased my branch on master and reorganized the commits for the two referenced issues.

**Comment by pmattern** [comment]
All features discussed in this issue implemented pretty good now.
No problems introduced by rebasing.

**Comment by pmattern** [comment]
If I'm not mistaken the strings additionally introduced aren't subject to translation yet.

**Comment by PCMan** [comment]
The UPDATE_TRANSLATIONS option in CMakeLists is turned off by default.
We can update the translations manually at once later when the UI strings are frozen.

**Comment by tsujan** [comment]
This should have been closed a long time ago.
