### ISSUE TITLE
[Feature request] Mouse drag item selection in Detailed view

### ISSUE THREAD

**Issue by akinokonomi** [lxqt/pcmanfm-qt#1633]
**Is your feature request related to a problem? Please describe.**

Hello. 

Yes, it is related. 
 I like the detailed view a lot, and the problem is that it's very difficult for me to select files/dirs using mouse there.  
(Except for Ctrl/Shift+LMB-click (cannot drag though).)

Nothing describes it better than a screencast:

<details><summary>A GIF sample</summary>

![pcman-qt-select](https://user-images.githubusercontent.com/91767492/184429640-4a919a75-4226-4b5a-91de-5101bae7f9ce.gif)

</details>

**Describe the solution you'd like**

I'd like for Pcmanfm-qt to behave like Pcmanfm (without -Qt suffix).
That is, to be able to use mouse drag for selection on every column other than the Name.

Nothing describes it better than a screencast:

<details><summary>A GIF sample</summary>

![pcmanfm-select](https://user-images.githubusercontent.com/91767492/184429655-3883bacb-096f-42ff-87b7-4759658c5351.gif)

</details>

It would also be great to see some improvements on that, like Ctrl+LMB-drag to unselect some of already selected items.

**Describe eventual alternatives you've considered**

No alternatives really. I guess I'll use Pcmanfm then. It's really good!

##### Context

I only want to have better UX, that's all.

---

Thank you very much!

**Comment by tsujan** [comment]
Uncheck Header → Right click menu → Auto-resize columns. Then make the first column smaller or the window wider.

> I'd like for Pcmanfm-qt to behave like Pcmanfm

pcmanfm-qt is a separate app. It doesn't follow pcmanfm's GUI.

**Comment by tsujan** [comment]
As you correctly said, a screencast is better (for others with the same question too):

https://user-images.githubusercontent.com/981076/184450192-d4e23f34-88c5-428c-b700-1c1135c1f130.mp4

**Comment by akinokonomi** [comment]
> Then make the first column smaller or the window wider.

Yeah, I already knew about that.

> pcmanfm-qt is a separate app. It doesn't follow pcmanfm's GUI.

Certainly, but there is nothing wrong with copying some behaviour/features  from other, similar applications. 

---

Okay, I see. Thanks for quick response.

**Comment by tsujan** [comment]
> but there is nothing wrong with copying some behaviour/features from other, similar applications.

Correct. That has been done many times. But when some job can already be done in one way, adding lots of codes for doing it in another way could make the source hard to maintain.

That being said, I'll keep your suggestion in mind. If it can be done by adding a few lines of code, why not? For now, I think the opposite is true.

**Comment by tsujan** [comment]
I checked the code. The following behavior can be implemented easily:

 1. The items are still opened by clicking any column.
 2. If the user starts a drag from a column other than the name column, the rubber-band selection will start, instead of item DND.
 3. Starting a drag from the name column starts a DND, like before.

My concern is that the GUI can't tell the user about 2 (which is unexpected in Qt); he should try it and see for himself.

I'm neither sure that there's no side effect. It needs more investigation.

**Comment by akinokonomi** [comment]
Thank you for looking into it!

> 3. Starting a drag from the name column starts a DND, like before.
>
> My concern is that the GUI can't tell the user about 2 (which is unexpected in Qt)

Some file managers, like Dolphin and Nemo IIRC, instead of whole Name column, have it defined on just file/dir *name*, so the file/dir name gets underlined when hovered.

Or maybe it'd make sense to underline file name, when Name column is hovered?

**Comment by akinokonomi** [comment]
> Some file managers, like Dolphin and Nemo IIRC, instead of whole Name column, have it defined to just file/dir *name*, so the file/dir name gets underlined when hovered.

Nope. Please forget what I've said.  
Dolphin has changed its UI real bad now, and Nemo underlines the file name regardless of which column is hovered.

**Comment by tsujan** [comment]
I don't think my concern will be serious in practice. I'll add a section to https://github.com/lxqt/pcmanfm-qt/wiki — we might also find a simple way of giving a hint in the GUI later — after the feature is implemented. The important thing is that (1) it's useful and (2) contrary to my first estimation, it doesn't need extra codes — actually, I removed some lines of code here ;)

I'm reopening the issue... Will make a PR after a little more testing. Thanks a lot for the idea!

**Comment by akinokonomi** [comment]
> I don't think my concern will be serious in practice. 

For what it's worth, Thunar never indicated it, but behaved like that since forever.

> Will make a PR after a little more testing.

Can't wait to check it out.

> Thanks a lot for the idea!

Idea is nothing without the implementation. Thank you, too!

**Comment by tsujan** [comment]
The PR: https://github.com/lxqt/libfm-qt/pull/830

**Comment by akinokonomi** [comment]
When mouse button is pressed, dragged, and released on the same item and the same column, the item is still opened. But I think you already know it.                                                                                           

Other than that, seems to work just fine.

**Comment by tsujan** [comment]
Thanks for testing!

> When mouse button is pressed, dragged, and released on the same item... But I think you already know it.

Yes, I was going to add some code for not clicking after dragging but preferred to keep this patch as simple as possible. Will do it in a separate PR (after this one is merged) and will tell you about it when it's ready.

**Comment by tsujan** [comment]
Or now, that I know you can try git patches, I can give it to you before the PR:

```diff
diff -ruNp libfm-qt-orig/src/folderview.cpp libfm-qt/src/folderview.cpp
--- libfm-qt-orig/src/folderview.cpp
+++ libfm-qt/src/folderview.cpp
@@ -807,7 +807,10 @@ void FolderViewTreeView::queueLayoutColu
 
 void FolderViewTreeView::mouseReleaseEvent(QMouseEvent* event) {
     bool activationWasAllowed = activationAllowed_;
-    if((!style()->styleHint(QStyle::SH_ItemView_ActivateItemOnSingleClick, nullptr, this)) || (event->button() != Qt::LeftButton)) {
+    if(!style()->styleHint(QStyle::SH_ItemView_ActivateItemOnSingleClick, nullptr, this)
+       || event->button() != Qt::LeftButton
+       // also, prevent activation if rubberband selection is greater than dragging distance
+       || rubberBandRect_.width() + rubberBandRect_.height() > QApplication::startDragDistance()) {
         activationAllowed_ = false;
     }
 

```

**Comment by akinokonomi** [comment]
> Thanks for testing!

No problem.

> Or now, that I know you can try git patches, I can give it to you before the PR:

Works like a charm.
