### ISSUE TITLE
[Feature request] Don't open file/folder when clicking column other than Name in single-click mode

### ISSUE THREAD

**Issue by akinokonomi** [lxqt/pcmanfm-qt#1634]
**Is your feature request related to a problem? Please describe.**

As a heavy single-click mode user (and not a single-click mode with delay user), I think Pcmanfm (no -Qt) provides one of the best experiences.  
So much for the way it behaves when clicking column other than the Name.  
Instead of opening the item, single click simply selects it, while double click opens it.

This is very different from Ctrl+LMB click, because in this case items keep stacking up for as long as I click them with Ctrl pressed.

**Describe the solution you'd like**

Can't think of anything, save for a screencast comparison:

<details><summary>A GIF samples</summary>

#### Pcmanfm

![pcmanfm-single-click](https://user-images.githubusercontent.com/91767492/184434719-728308d6-11a2-4117-ba51-196ad6b3a7a9.gif)

#### Pcmanfm-qt

![pcman-qt-single-click](https://user-images.githubusercontent.com/91767492/184434733-2eb352a7-3045-4d00-a0cf-cc34b6b646e9.gif)

</details>

**Describe eventual alternatives you've considered**

My best bet would be to change my habits.

##### Context

Like in case with #1633, this is only to have a better user experience.

**Comment by tsujan** [comment]
Please don't ask for copying pcmanfm's GUI in pcmanfm-qt; see the end of  https://github.com/lxqt/pcmanfm-qt/issues/1633#issuecomment-1213534158

**Comment by tsujan** [comment]
Since I reopened https://github.com/lxqt/pcmanfm-qt/issues/1633, a short explanation may be needed as to why this one doesn't need to be reopened.

 * The feature request at https://github.com/lxqt/pcmanfm-qt/issues/1633 will be implemented without requiring this one.
 * Under some circumstances, and especially in LXQt file dialog, the name column may not be (completely) visible without horizontal scrolling. That can easily become annoying.
 * Clicking in the single-click mode and not opening the file is so inconsistent with everything else that it can be seen like a bug.

**Comment by akinokonomi** [comment]
> The feature request at #1633 will be implemented without requiring this one.

Yes, I was almost confident that Qt can distinguish drag vs. click event.

I opened this as a separate feature request because considered it different feature.

> Moreover, after #1633 is implemented, the user could press the left mouse button inside a non-name column and drag the mouse horizontally to its left or right column to select an item without opening it.

That's exactly the way Thunar does it, by the way.

Okay, I think I must elaborate a bit as to why I believe it important: 

In situation when File1, File2, File3, File4, etc. are selected, it is very difficult to unselect all except File2.  
For example, to rename it, to see properties, to *reset* selection.  Foe me it's to reset selection, mainly.

Imagine the situation where folder has 100+ files, so the whole window is packed up (and there is no space at the bottom),
so the only way to reset the selection would be to disable Auto-resizing of columns and click on the right, or re-drag some file in the middle.  
But I really like Auto-resize columns, so it's only latter for me.

I've also spent some time with Thunar, and still found the way Pcmanfm implemented it much more pleasant to deal with. 
Honestly, most of the times I did that (drag the item in the middle of existing selection), I ended up missing a file and selecting two instead.

---

Though if it's already decided, there is nothing to be done.

**Comment by tsujan** [comment]
> ... or re-drag some file in the middle.

First a horizontal drag from a non-name column to another and then Ctrl+Click (after the implementation, of course):

https://user-images.githubusercontent.com/981076/184520253-c601473c-1e84-47fe-b5c7-41204f089748.mp4

This special case caught my attention too. I though about a "Deselect all" item in the selection context menu of the detailed list mode (or, perhaps, all view modes).

**Comment by akinokonomi** [comment]
Well, for me small vertical drag is way more natural than horizontal. And single mouse click is way faster than even a smallest drag.  
Mouse drag also requires more attention, so click is simpler, too.

> I thought about a "Deselect all" item in the selection context menu of the detailed list mode (or, perhaps, all view modes).

Then it should be the topmost. But I'm not sure how practical it would be.

**Comment by tsujan** [comment]
> Then it should be the topmost. But I'm not sure how practical it would be.

The top items are reserved for file opening. Anyway, I'm not sure that cluttering the selection menu for this special case is a good idea; should think more...

**Comment by tsujan** [comment]
A cleaner solution for deselecting all files is adding a "Deselect All" only to the Edit menu of pcmanfm-qt, with `Ctrl+D` as its shortcut.

LXQt file dialog can also have `Ctrl+D` (without an extra item, as it has `Ctr+A` when the extended selection is possible).

Since `Ctrl+D` is used by shell too, it shouldn't be used as a global shortcut. So, I think it's appropriate.

@stefonarch, I'd also like to know your opinion about it (no need to read the whole page; just this comment).

**Comment by stefonarch** [comment]
I'm ok with the shortcut, for the rest I've to admit that I didn't follow and understand the needs, but you're the master of Pcmanfm-qt ;)

**Comment by tsujan** [comment]
Thanks! I'll implement it.

> for the rest I've to admit that I didn't follow and understand the needs

If you think I won't involve you in https://github.com/lxqt/libfm-qt/pull/830, you're wrong ;) Your tests will be needed, although there's no rush.

**Comment by tsujan** [comment]
The PRs are made: https://github.com/lxqt/pcmanfm-qt/pull/1638 and https://github.com/lxqt/libfm-qt/pull/832

**Comment by stefonarch** [comment]
> If you think I won't involve you in [lxqt/libfm-qt#830](https://github.com/lxqt/libfm-qt/pull/830)

Ok, compiled that branch, I see the benefits ;)

**Comment by tsujan** [comment]
Item selection becomes a piece of cake in the detailed list mode: start from any column other than the name column and drag the mouse while pressing its left button.

**Comment by akinokonomi** [comment]
So you've settled with the key binding instead.

If so, maybe just the Escape, rather than Ctrl-D, to keep it simpler?

**Comment by tsujan** [comment]
Escape is for focusing the main view from any place. That's important for those who mostly use keyboard. It also closes the transient search-bar.

**Comment by akinokonomi** [comment]
> Escape is for focusing the main view from any place. ... It also closes the transient search-bar.

Why not to add the "deselect all" action to this list?

The main window must remain/get focused when items in main window are deselected, isn't it?

**Comment by tsujan** [comment]
> Why not to add the "deselect all" action to this list?

There's more than one reason as to why that would be annoying. I type something → some items are filtered and one of them is selected → I press Escape to close the transient search-bar and see all items. The selected item should remain selected and scrolled to.

**Comment by akinokonomi** [comment]
Yeah, sounds reasonable. Okay.
