### ISSUE TITLE
touch doesn't work

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1637]
On a convertible the touch doesn't work for example for those three actions:
- scrolling with the scrollbar,
- to mark a file or a document, and
- tab-browsing.

But the three actions work in the browser Firefox and in the editor Geany.

My 0.17.0 is old although I use the latest version of Lubuntu (22.04). If the issue does not appear in 1.1.0 any more, then I’m sorry for this report.

**Comment by tsujan** [comment]
There's nothing in pcmanfm-qt's code to treat any device differently.

Anyway, this will be reopened if someone with a touch device and a recent version confirms it.

**Comment by ralf3u** [comment]
I don't know what happened. I didn't make an update. But all the three actions from the report above work today in PCManFM-Qt.

**Comment by tsujan** [comment]
Thanks for your comment.

Sometimes, it isn't easy to know what has changed; there are so many factors in a system. But pcmanfm-qt doesn't control how touch devices work.
