### ISSUE TITLE
Terminal key-values inside `settings.conf.in`

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#1647]
I hadn't checked `config/pcmanfm-qt/lxqt/settings.conf.in` inside the source before, but there are three keys that don't exist in the code, namely, `TerminalCommand`, `TerminalDirCommand` and `TerminalExecCommand`. Were those keys used by a very old version of pcmanfm-qt?

That's while `Terminal` — which does exist — is missing.

Since that config file is for use under LXQt (it's installed under `/usr/share/pcmanfm-qt/lxqt/`), I suggest the removal of those keys and setting `Terminal=qterminal`. Those who install pcmanfm-qt independently and use it under other DEs won't see a change. But QTerminal belongs to LXQt. If it isn't installed under LXQt, the user will see a message and either install it or change the terminal in Preferences.

@stefonarch, would you please look into it?

**Comment by stefonarch** [comment]
```
TerminalCommand=
TerminalDirCommand=xterm
TerminalExecCommand=xterm -e %s
```
Those settings results on a clean install (after at least changing one setting) to
```
[System]
...
Terminal=xterm
```
In fact I remember that.  But that's because none of them work actually - removing all still xterm will be set.

So having `Terminal=qterminal` in `settings.conf.in` solves that, but maybe having xterm as default when using it outside of a LXQt session could be an option.

**Comment by tsujan** [comment]
> maybe having xterm as default when using it outside of a LXQt session could be an option.

`xterm` is the default in the code. It doesn't need to be set.

**Comment by tsujan** [comment]
Oh, I found where those redundant keys come from: they belong to old times, when we didn't have `/usr/share/libfm-qt/terminals.list`. We forgot to remove them afterward.

**Comment by tsujan** [comment]
Damn! There's a problem — and I think this is a déjà vu: https://github.com/lxqt/pcmanfm-qt/pull/1649 has no effect in the case of terminal if `~/.config/pcmanfm-qt/lxqt/settings.conf` is removed before starting pcmanfm-qt in the desktop mode under LXQt.

The code needs a fix.

**Comment by stefonarch** [comment]
I guess it's not like that, I tested in Vbox modifying` /usr/share/pcmanfm-qt/lxqt/settings.conf` and found it will be read.

**Comment by tsujan** [comment]
Since we load the config file path in the code, the system config file won't be read if the user config folder exists. If the config file path isn't set in a code (like that of FeatherPad), even the missing keys will be read from the system config file (although FeatherPad doesn't come with one).

But, in the case of pcmanfm-qt, we want to distinguish between when it's used under LXQt and when not. That's why we need paths. I'm not saying that the current code structure was inevitable, but any change to it will be backward incompatible.

> But it's hard to find a situation where an empty folder exists.

You're right. There are no folders on the first login. So, in practice, there's no problem.

I come to the same conclusion, as when Alf and I discussed it: this isn't worth making backward-incompatible changes.
