### ISSUE TITLE
pcmanfm-qt doesn't work from cron

### ISSUE THREAD

**Issue by thedoctar** [lxqt/pcmanfm-qt#1648]
See last comment of https://github.com/lxqt/pcmanfm-qt/issues/1645

##### Expected Behavior
pcmanfm-qt -w $wallpaper should change the wallpaper

##### Current Behavior
Running this command from a cron job does nothing

**Comment by tsujan** [comment]
Please don't this again! You can add comments to a closed issue.

**Comment by thedoctar** [comment]
Sorry, I thought you wouldn't get a notification! Any I couldn't pm you.
