### ISSUE TITLE
pcmanfm-qt randomly stops listing content

### ISSUE THREAD

**Issue by carnager** [lxqt/pcmanfm-qt#1653]
##### Expected Behavior
pcmanfm-qt works great, as long as it shows actual files/directories. 

##### Current Behavior
When changing directories pcmanfm-qt often suddenly stops listing directories/files. The statusbar still shows the amount of files in current directory, but the list/icon view is empty.

##### Possible Solution
Sadly I haven't found out yet, what triggers this behavior, help to debug this would be welcome, since I can't find an option to get debug output.

##### Steps to Reproduce (for bugs)
Apart from changing directories I haven't done anything special... 

##### Screenshot
![image](https://user-images.githubusercontent.com/3321178/188303482-8e820463-b7df-4849-9c80-def1dc742509.png)

##### System Information

* PcManFm-qt version: 1.1.0
* Distribution & Version: Arch Linux, up to date
* Qt Version: 5.15.5
* liblxqt Version: Not installed (Maybe part of the issue?)

**Comment by tsujan** [comment]
> liblxqt Version: Not installed (Maybe part of the issue?)

No, it isn't related.

This isn't reproducible, of course. I'm afraid you need to find the necessary conditions of reproducing it. If you do, the report could be reopened.

**Comment by tsujan** [comment]
* How did you install pcmanfm-qt? From Arch's repository or by compiling it yourself?
 * When did the problem start to happen? After a specific upgrade?
 * Under which DE do you use it?

**Comment by carnager** [comment]
> * How did you install pcmanfm-qt? From Arch's repository or by compiling it yourself?

Yeah from repositories
>     * When did the problem start to happen? After a specific upgrade?

I installed it pretty recently, so can't say for sure
>     * Under which DE do you use it?

Sway

I have a few sshfs mounts, maybe those cause some issues. I will try a few hours via ssh:// protocol to see if that makes a difference

**Comment by tsujan** [comment]
Thanks for the reply!

> I have a few sshfs mounts

Does it happen only with the mounted folders?
