### ISSUE TITLE
when open a smb share pcmanfm fail because use smb:///[host][shared] instead smb://[host][shared]

### ISSUE THREAD

**Issue by edefranco** [lxqt/pcmanfm-qt#1656]
##### Expected Behavior

clicking on the icon of the discovered network shared directory it should be open it 
##### Current Behavior

opening pcmanfm-qt network on desktop, it show correctly the share but clicking on it failed to open. If you type manually the path in address bar with smb://host/share/ it open regularly the network directory. The icon of the shared point to dnssd-domain-[shared name]._smb._tcp instead smb://host/shared name/
##### Possible Solution

correct the errate behaviour as described with the correct string smb://host/shared name discovered/
##### Steps to Reproduce (for bugs)

1. click on network icon on the lxqt desktop
2. click on one host name discovered
3.
4.

##### Context

I searched solution on google but not found.
##### System Information

system are Lubuntu 22.04 LTS and pcmanfm-qt is version 0.17.0 from official lubuntu install

* PcManFm-qt version: 0.17.0
* Distribution & Version: Lubuntu 22.04.1 LTS amd64
* Qt Version: original of distro
* liblxqt Version: original of distro

**Comment by tsujan** [comment]
> PcManFm-qt version: 0.17.0

It's outdated.
