### ISSUE TITLE
 LibreOffice: no USB-key any more in the sidebar of the open/save-dialog 

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1666]
In the open/save-dialog of LibreOffice there’s no USB-key any more in the sidebar (so, on the left side), no matter if in the `Options`, in `LibreOffice`, in `General` this is checked or unchecked:
`Use LibreOffice dialogs`.

I know, that the USB-key is somewhere in `/media/…`, but it would be better if the external device would be visible in the sidebar of the open/save-dialog, like it was before in some past releases of Lubuntu, like Lubuntu 20.04.

I reported it at launchpad some months ago, but there's no move (https://bugs.launchpad.net/ubuntu/+source/libreoffice/+bug/1979116). So, maybe LXQt is the problem.

I use LXQt 0.17 in Lubuntu 22.04, but I still don’t know how to install the latest version of LXQt.
If the issue does not appear in LXQt 1.1.0 any more, then I’m sorry for this report.

**Comment by tsujan** [comment]
LibreOffice uses a patched version of Qt's default file dialog with its Qt5 skin. It isn't related to LXQt.

**Comment by stefonarch** [comment]
> but I still don’t know how to install the latest version of LXQt.

https://ubuntuhandbook.org/index.php/2022/09/install-lxqt-1-10-lubuntu-22-04/
