### ISSUE TITLE
Open with single-click

### ISSUE THREAD

**Issue by Esclapion** [lxqt/pcmanfm-qt#167]
If I enable it, the desktop applications are also launched by a single click and it's good.
But, generally, what does a double-click in this case ?
A user who has the habit to do a double-click and has the current problem of the shortcuts in the taskbar (who can need one or two) will have his applications launched twice.

I propose to redirect double-click to single-click in this case, if it's no to complicate to do.

**Comment by tsujan** [comment]
Habits should change. This is an old story: single vs double click
