### ISSUE TITLE
delete the asterisk in the search-dialog

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1679]
When I open the search dialog with Ctrl+F, then there is in the tab "Name/Location" in "File Name Patterns" an asterisk. I never understood why it is there. I always delete it before I type words. I find the asterisk quite disturbing. In the search field of google there is no asterisk. And there is no asterisk in the address bar in the browser Firefox.

Lubuntu 22.10
LXQt 1.1.0

**Comment by tsujan** [comment]
It suggests that a pattern can be put there. Since it's selected, you don't need to delete it first.

> I always delete it before I type words.

Change your habit.

**Comment by ralf3u** [comment]
A blinking vertical line would be better, like in the address bar of Firefox or like on google, or like in the search dialog in the tab "Content".

>Change your habit.

I can change my habits. But it still disturbs me.

Why there is no asterisk in the tab "Content" but an asterisk in the tab "Name/Location"? That is for me an in-consequent attitude.

**Comment by stefonarch** [comment]
An 

> Why there is no asterisk in the tab "Content" but an asterisk in the tab "Name/Location"? That is for me an in-consequent attitude.

An asterisk there would mean "anything":
https://listerinfo.com/engines-info/what-does-asterisk-mean-in-search-engine.html

**Comment by tsujan** [comment]
> An asterisk there would mean "anything":

In Regex (which is supported here), it means any *number* of what comes before it. For example, `a*` matches an empty string, `a`, `aa`, `aaa`, and so on.

Regex is much more advanced and flexible than Bash patterns (which aren't supported here).

**Comment by ralf3u** [comment]
>An asterisk there would mean "anything"

I know that it is standing for a wildcard. But that does not mean to put it by default in the field. I think that it would be better to mention it somewhere else. What about to write something like this just above "Places to search":

`(an asterisk can be used in the search field as wildcard)`

**Comment by tsujan** [comment]
> I know that it is standing for a wildcard.

It isn't.

**Comment by ralf3u** [comment]
>>I know that it is standing for a wildcard.
>
>It isn't.

OK, so write an explication of the asterisk-symbol, just above "Places to search", by leaving the search field empty.

**Comment by tsujan** [comment]
The user needs to learn Regex in order to use it. `*` is just one Regex metacharacter among many.

And, as it has been said repeatedly, changes aren't made based on what a user may like or dislike.

**Comment by ralf3u** [comment]
OK, fine, so just write `(the Regex-rules are used in the search field)`, for example above "Places to search", by leaving the search field empty.

In the end I think that the asterisk-symbol in the search field is not user friendly.
