### ISSUE TITLE
Desktop preferences shouldn't be visible in other DEs

### ISSUE THREAD

**Issue by Dejweed** [lxqt/pcmanfm-qt#1686]
The Desktop menu entry has been distracting me in KDE. As far as I know it's only used for LXQt, so I think it would be better to only display it there, or make it hidden for desktop environments like Gnome, KDE...

##### Possible Solution
Add "OnlyShowIn=LXQt" to pcmanfm-qt-desktop-pref.desktop

##### System Information

* PcManFm-qt version: 1.2.0

**Comment by tsujan** [comment]
> As far as I know it's only used for LXQt

PCManFM-Qt's desktop module can be used anywhere.

**Comment by stefonarch** [comment]
> Add "OnlyShowIn=LXQt" to pcmanfm-qt-desktop-pref.desktop

copy it to ~/.local/share/applications/ and add that line

**Comment by Dejweed** [comment]
Will do, thank you :)
