### ISSUE TITLE
Xwayland apps won't start (getting a wrong DISPLAY value)

### ISSUE THREAD

**Issue by YHNdnzj** [lxqt/pcmanfm-qt#1687]
##### Expected Behavior

Xwayland apps get the correct `DISPLAY` value from env and start fine

##### Current Behavior

They get random garbage `DISPLAY` values, preventing them from starting

##### Steps to Reproduce (for bugs)

1. Start pcmanfm-qt under Wayland
2. Use it to start any Xwayland app

![photo_2022-11-28_15-25-51](https://user-images.githubusercontent.com/29118423/204218238-76c10c0b-8b58-4e96-b099-3d7f118cd55e.jpg)

##### Context

I've checked `pcmanfm-qt`'s envvar, and confirmed that it holds the correct value.

##### System Information

* PcManFm-qt version: 1.2.0
* Distribution & Version: Arch Linux
* Qt Version: 5.15.7
* liblxqt Version: _not installed_

**Comment by tsujan** [comment]
Thanks for the report!

This problem doesn't exist in the Qt6 branch of `libfm-qt` (see https://github.com/lxqt/libfm-qt/pull/778 — there will be a Qt6 branch for `pcmanfm-qt` soon). I'll also fix it in the current git master, but I'm not sure we'll have another Qt5 release for `libfm-qt/pcmanfm-qt` (unless we make a point release).
