### ISSUE TITLE
Bookmarks from the Side Pane have different behavior than bookmarks from the menu

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1689]
Condition
in `Preferences` in `Behavior`: `Bookmarks menu` is set to `Open in new tab`

Result
Only bookmarks from the menu will open in a new tab, but not bookmarks of the Side Pane.

Expectation
If I click on bookmarks of the Side Pane, then the bookmarks should open also in a new tab.
If this would be possible, then the Preferences could be changed from `Bookmarks menu` to `Bookmarks`.

Remark
A same behavior of Side Pane and menu would makes sense, specially when the menu-bar is disabled.

System
Lubuntu 22.04.1
PCManFM-Qt 1.1.0

**Comment by tsujan** [comment]
As its text says, that option is for Bookmarks *menu*.

The side-pane items should behave consistently, regardless of their grouping. And they do: left click opens them in the current tab, middle click in new tab.

**Comment by ralf3u** [comment]
>The side-pane items should behave consistently, regardless of their grouping.

OK, I can understand it.

But what about to open side-pane items with Ctrl+click, to have the same behavior like the items in the vertical bookmark-bar in Firefox?
