### ISSUE TITLE
Only the Name column narrows in Auto-resize Detailed List to accommodate narrower window

### ISSUE THREAD

**Issue by gwhitney** [lxqt/pcmanfm-qt#1697]
##### Expected Behavior
When the overall window is too narrow to accommodate all columns in Auto-resize Detailed List mode, all columns should share the burden of becoming narrower/ellipsizing to conform to the available space, perhaps especially the less important ones like Type and Created.

##### Current Behavior
All of the column widths except Name are fixed at their "natural" widths, which are large enough to accommodate all of their contents, or in some cases like Owner and Group, even wider than is strictly necessary to show their contents. All of the width reduction is taken from the Name column. This causes the most important column to be the _first_ one to be obscured and difficult to read as the window is narrowed.

##### Possible Solution
Distribute the stretchiness more fairly among the other columns, allowing them to ellipsize, perhaps especially less important ones, or perhaps equally.

##### Steps to Reproduce (for bugs)
1. Open directory view in Auto-resize Detailed list mode.
2. Narrow the overall application window to the point that not all of the columns will fit in the available space.

##### Context
Trying to keep my pcmanfm-qt windows to a modest width so as not to take up too much space on screen, but then they become difficult to read because the file names are all truncated. I would rather other columns become narrower.

I believe this is the more important underlying mechanism of the problem first reported in #1696 but as the focus of that issue has shifted to another point I felt I ought to open a separate issue, with this concern stated clearly (and hopefully briefly enough, sorry I have been verbose!)

##### System Information
* PcManFm-qt version: 1.2.0
* Distribution & Version: OpenSUSE Tumbleweed
* Qt Version: 5.15.7

**Comment by tsujan** [comment]
> Distribute the stretchiness more fairly among the other columns

That would be a bad design and would damage UX.

**Comment by gwhitney** [comment]
I am curious as to why you think so; the current design puts all of the "penalty" of a narrower window on the Name field, which is the most important one to be visible.  As examples of UIs that distribute "stretchiness" not all to the first column: The default of an HTML flexbox is to shrink all columns proportionally. The Google Drive list view shrinks the Owner column before the Name column, as you narrow the browser. What is the benefit to the UX of only allowing the Name column to change width in response to the overall window changing width? It seems to be hurting the UX, not helping it.

**Comment by gwhitney** [comment]
Another example: Thunderbird email, "Subject" and "Correspondent" in the email list shrink proportionally as you narrow the overall window size. In fact, UIs in which multiple columns narrow as the overall window narrows appear to more common than assigning all of the stretchiness to a single column. Thanks for considering.

**Comment by tsujan** [comment]
All columns have limited widths except for the name column, whose texts can be arbitrarily long. That's why the name column should be elided if needed. Eliding more than one column is bad for UX (although it's still possible with folders containing huge amounts of files).

https://github.com/lxqt/pcmanfm-qt/issues/1696 will be fixed practically when its corresponding PR is merged. As mentioned there, your report was quite valid. Thanks!

**Comment by gwhitney** [comment]
As always, thanks for considering the following (and so you don't worry, I don't expect to post further here after this, but I hope you will change your mind). I also don't mean to be argumentative; I just think, as a user, there are some special user experience considerations  for a file manager here: 

- The content of the Name column is far more important than any other column.
- The items in the Type column typically vary quite a bit in width, e.g., from 'folder' to 'Microsoft Publisher document' (>4x as wide). It doesn't actually have any particular low limit on its width, and often has content items much longer than the file name.  Because of the variation in item width, it currently often leads to a lot of non-helpful whitespace. Finally, often you can see what the type is from just the beginning of the type name, so it works quite well to ellipsize. 
- The Owner and Group columns already are sizing much wider than they actually need. (Maybe they are allowing for the longest user name and group name known to the system, even if it doesn't occur in this directory?)
- The timestamps could  abbreviate to just dates when they need to be narrow. 

So there are lots of places to save horizontal width that will preserve the usefulness of the Name column. The asymmetry of salience to the user argues for putting the burden of a narrower window (at least partly) on other columns, not the Name column. I appreciate your time, consideration, and your efforts on pcmanfm-qt.

**Comment by tsujan** [comment]
> The content of the Name column is far more important than any other column.

I understand that. But a 500-character text isn't something a user usually reads from start to end. It should be elided. The user could resize the column temporarily if he/she wants to see very long texts completely. 40-50 characters are more than enough.

> The items in the Type column typically vary quite a bit in width

Yes, but it's limited, because it doesn't contain arbitrary texts.

> The Owner and Group columns already are sizing much wider than they actually need

They don't. If you scroll the view, you'll see why.

Last but not least, you could always hide the columns you don't need.

**Comment by tsujan** [comment]
> I also don't mean to be argumentative

It's OK — and sometimes useful — to be argumentative here. I never meant you shouldn't argue more. What I meant (on the other page) was only that concise comments are really preferable.

In this case, I won't change my mind ;)

**Comment by gwhitney** [comment]
Since you're crystal clear that you're not considering this I will limit to: I don't understand what you mean about "Group" and "Owner". In my home directory, all files are owned by `glen` so every single entry is just `glen` (and there is nothing to scroll, every item appears on screen at once) but the column is roughly twice the width of `glen`. Cheers. Maybe I will make a personal fork and "fix" this on my own branch when I have time.

**Comment by tsujan** [comment]
> In my home directory, all files are owned by glen so every single entry is just glen

Then it's because of words "Group" and "Owner" plus an empty space for the sorting indicator. I assure you that the sizes are correct.

The scroll would be needed if you had a user like "aUserWithAVeryVeryVeryLongName".

**Comment by gwhitney** [comment]
Well, all I can say is that it sure doesn't look like it (see attached). Thanks again for all the time you have spent on my behalf today, I really appreciate it.
![Screenshot_2022-12-12_19-08-01](https://user-images.githubusercontent.com/3825429/207190067-22d40689-f91c-4ef9-b893-0c58dbb46882.png)

**Comment by tsujan** [comment]
> Well, all I can say is that it sure doesn't look like it (see attached).

It's exactly like that ;) The Qt style you use (Fusion), gives more space to the sorting indicators with big fonts but, for some reason, it doesn't draw it bigger (actually, it does here).

**Comment by gwhitney** [comment]
Oh, is there a more compact Qt style that I could switch to? How do I switch Qt styles? I guess I don't use many Qt apps. If you don't want to take more time to answer I will do an internet search now on "select Qt style". Thanks!

**Comment by tsujan** [comment]
> Oh, is there a more compact Qt style that I could switch to?

Oh, your style doesn't seem to be Fusion (see my screenshot). Fusion is compact enough. It's Qt's default style.

**Comment by tsujan** [comment]
If you don't use LXQt (for example, if you use GNOME), you might want to install and enable `qt5ct` to change the Qt style. Under LXQt, go to "Appearance"; under KDE, to "System Settings".
