### ISSUE TITLE
Small regression in Desktop after Wayland-DND changes to `libfm-qt`

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#1706]
With the recent changes in `libfm-qt`, the DND menu is shown after finishing Qt's DND. That's necessary under Wayland because, otherwise, a crash could happen and other issues would exist too. But it has a side-effect on Desktop, whether under X11 or Wayland.

If a file is dropped on Desktop from another place (a window, for example), we reserve the drop position for it before finishing Qt's DND. Therefore, if the DND is cancelled, we'll have reserved a position for a nonexistent file.

Under usual circumstances, the user will see no difference. However, a small issue can happen. This is a way of reproducing it:

 1. Drop a file from a window into a place on Desktop. The DND menu will be shown.
 2. Cancel the drop in the DND menu.
 3. Copy the same file and paste it on Desktop.

Then, the file will appear at the cancelled drop position, quite counter-intuitively,

Although it isn't a big problem, I think it's better to fix it before the next point release. Will make two PRs, one for `libfm-qt` and the other for `pcmanfm-qt`.

##### System Information
Latest git

**Comment by stefonarch** [comment]
I see, better fix it also it won't be noticed by most people.

**Comment by tsujan** [comment]
> it won't be noticed by most people.

Right.

Since the fix consists of small changes to `libfm-qt` and `pcmanfm-qt`, I think it can be included in the next point release.
