### ISSUE TITLE
Not show title in Task Manager KDE Plasma

### ISSUE THREAD

**Issue by sajadspeed** [lxqt/pcmanfm-qt#1710]
The picture below explains everything:
![image](https://user-images.githubusercontent.com/43334402/211086899-6e42f868-bdff-4e2e-a4e1-dd6e45ee48ae.png)

**Comment by tsujan** [comment]
That popup window (at the bottom left of the screen) doesn't belong to LXQt.

**Comment by tsujan** [comment]
BTW, if I were you, I'd report the problem to KDE. Apparently, KDE can't handle titles of windows that belong to the same app process — just a guess.
