### ISSUE TITLE
[Feature request] Make 'lists' menu hideable

### ISSUE THREAD

**Issue by Zeioth** [lxqt/pcmanfm-qt#1712]
**Is your feature request related to a problem? Please describe.**
Add an option to hide the menu under edit > preferences → User interface

![screenshot_2023-01-07_07-58-19_553672168](https://user-images.githubusercontent.com/3357792/211135532-b534edc4-f4b4-47f5-b6d8-4ef3691ea404.png)

**Comment by tsujan** [comment]
As it has been said repeatedly, we don't add options just for the sake of adding options.

**Comment by Zeioth** [comment]
No problem, should be easy enough to add later through a fork. Thank you for working on the project.
