### ISSUE TITLE
[Feature request] Make the select view menu hideable

### ISSUE THREAD

**Issue by Zeioth** [lxqt/pcmanfm-qt#1713]
**Is your feature request related to a problem? Please describe.**

Make it hideable under edit → properties → user interface

![screenshot_2023-01-07_07-59-41_647476087](https://user-images.githubusercontent.com/3357792/211135861-e0263135-fcd0-4b48-8d24-ceca203058a3.png)

**Comment by tsujan** [comment]
→ https://github.com/lxqt/pcmanfm-qt/issues/1712#issuecomment-1374431732
