### ISSUE TITLE
No shortcuts for views buttons

### ISSUE THREAD

**Issue by sergeytol** [lxqt/pcmanfm-qt#1715]
Hello! Could you please implement shortcuts for Views (Icon view, list view, etc.)? In LXDE I could use Ctrl+[number] for view switching but now it's impossible to use a keyboard for that

**Comment by tsujan** [comment]
Tool-bar buttons are easy to access, users don't change the view mode continuously, and pcmanfm-qt supports per-folder view customization (→ https://github.com/lxqt/pcmanfm-qt/wiki#customizing-view-settings). So, there's no real need for shortcuts here.

Moreover, there's a shortage of keys for new, simple shortcuts. Ctr+Number is for tab switching, and other good combinations are already reserved.

**Comment by tsujan** [comment]
Duplicate of https://github.com/lxqt/pcmanfm-qt/issues/1324

**Comment by lobaluna** [comment]
Hi, @tsujan
Shortcuts are greatly needed and appreciated. Consider them as an accessibilty issue. Not everyone is keen with the mouse. Besides, it's sometimes needed to change view node temporarily to search a file (last file modified, for example) and then go back to thumbnail view for easy inspection. With shortcuts, this is done in a breeze.

You said there is a a shortage of shortcut. But you have repetition: Alt+number goes to open tab number; and Ctrl-number ALSO goes to open tab number.

So we can use either Ctrl or Alt to change views.

**Comment by tsujan** [comment]
> So we can use either Ctrl or Alt to change views.

No, we don't break UX. As mentioned elsewhere, tab switching is much more important than view switching, and its current shortcuts are very comfortable.

Adding shortcuts is a piece of cake; finding them is not. Alt+Ctrl+NUMBER is used by most WMs, X11 or Wayland. Maybe ALT+SHIFT+NUMBER?

**Comment by tsujan** [comment]
Done in https://github.com/lxqt/pcmanfm-qt/pull/2038:

![Image](https://github.com/user-attachments/assets/d13dbf86-9140-45ac-b698-897bf808e2f0)

**Comment by lobaluna** [comment]
Thank you very much. Really, very much!
