### ISSUE TITLE
Unexpected and inconsistent TAB behaviour on file renaming

### ISSUE THREAD

**Issue by ceever** [lxqt/pcmanfm-qt#1719]
##### Expected Behavior
Whenever one edits the filename (either in icon or list view) pushing TAB on the keyboard should save the current (modified) filename and go to the next file in renaming mode.

##### Current Behavior
I) In list view editing a filename, TAB causes to the loss of any changes to the filename and moves to the next file in renaming mode.
II) In icon view editing a filename. TAB causes the insertion of a tab character (\t) in the filename.

![20230125 161009_rectangle_294x170](https://user-images.githubusercontent.com/40247591/214617875-19111497-855f-41f0-9c55-c7cd64dff10e.png)

##### Possible Solution
Since it is rather useless to have a tab character in a filename, the best behaviour of TAB would be to save the current modicication and move to the next file. This way, renaming could be enhanced, especially for the case of many files. 

##### Steps to Reproduce (for bugs)
I)
1. Choose list view
2. Right click on a file and select "Rename"
3. Modify the filename and push TAB
4. See that the modification is lost and the renaming moves to the next file

II)
1. Choose icon view
2. Right click on a file and select "Rename"
3. Modify the filename and push TAB
4. See how a tab character is inserted instead of moving to the next file

##### System Information

* PcManFm-qt version: 1.1.0
* Distribution & Version: Ubuntu 22.10
* Qt Version: 5.15.6
* liblxqt Version: ?

**Comment by tsujan** [comment]
Yes, there is an inconsistency.

In all cases, TAB should insert a tab character, because we shouldn't remove a valid use case, a focus change on renaming can be confusing, the user can change the focus after renaming, and multiple files can already be renamed together.

**Comment by ceever** [comment]
Probably.

**Comment by tsujan** [comment]
Done in https://github.com/lxqt/libfm-qt/pull/872. It was Qt's default behavior, which is overridden by the patch.

**Comment by ceever** [comment]
Just another thought on the "discussion". <ENTER> on the opposite does not introduce a "\n" character, even though that is an even more likely use case than TAB and "\t".

In addition, maybe the whole next file with TAB behaviour could overcome the weirdly duplicate bulk rename window. Generally, why would you have two different renaming behaviours anyhow, inline and popup?

Not to diminish your effort or work, which is really great (!), I am just trying to imagine a better world. 😇

**Comment by tsujan** [comment]
> Just another thought on the "discussion". <ENTER> on the opposite does not introduce a "\n" character, even though that is an even more likely use case than TAB and "\t".

Yes, newline is also a valid character in file names, but allowing Enter/Return to insert a newline would damage the UX. There should be a balance.

> In addition, maybe the whole next file with TAB behaviour could overcome the weirdly duplicate bulk rename window.

Apart from the extra features bulk renaming has, it can be used with any selection, not just successive items.

> ...I am just trying to imagine a better world.

That's very appreciated. Not accepting a suggestion doesn't mean that the good intention behind it isn't appreciated.

**Comment by ceever** [comment]
> That's very appreciated. Not accepting a suggestion doesn't mean that the good intention behind it isn't appreciated.

👍

> Apart from the extra features bulk renaming has, it can be used with any selection, not just successive items.

Inline bulk renaming could just wonder through the selected files with TAB. It does not have to be successive.
