### ISSUE TITLE
Unable to set the font size for root

### ISSUE THREAD

**Issue by ghost** [lxqt/pcmanfm-qt#172]
I think I tried everything to no avail:
lxappearance executed as root
lxqt-config-appearance executed as root
obconf(-qt) executed as root
qt5ct executed as root
Copying Trolltech.conf to root
Changing config files under /etc/xdg
The size stays at 10

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Found the solution by myself:
QT_STYLE_OVERRIDE=gtk written in /etc/environment
(maybe also XDG_CURRENT_DESKTOP=LXQt)

**Comment by ThebestwaytodesignJoinGitHub** [comment]
Just realized this works only using pkexec
