### ISSUE TITLE
Thumbnail preview distorts list view

### ISSUE THREAD

**Issue by ceever** [lxqt/pcmanfm-qt#1720]
##### Expected Behavior
Text in (both) list view aligns consistently, so the list can be of use.

##### Current Behavior
Whenever the thumbnail preview is activated, the filename alignment/intend depends on the content of the thumbnail.
![20210529 183702_rectangle_271x161](https://user-images.githubusercontent.com/40247591/215100294-0df031b7-0826-4ffe-8d57-598b48ce5b9f.png)

##### Possible Solution
Make the thumbnail a static square, either by cropping or canvasing the thumbnail content. 

##### Steps to Reproduce (for bugs)
1. Create two pictures with extreme rectancled pictures, one horizontally, one vertically.
2. Activate thumbnail preview in pcmanfm
3. Choose list view
4. See how both filenames are aligned differently

##### System Information
* PcManFm-qt version: 1.1.0
* Distribution & Version: Ubuntu 22.10
* Qt Version: 5.15.6
* liblxqt Version: ?

**Comment by tsujan** [comment]
This is especially bad when there's an emblem, like on the first item of this screenshot:

![icon_size](https://user-images.githubusercontent.com/981076/215117313-61a20c9b-8f67-45ef-a9ae-405e78fb73c6.png)

I wonder how I missed it. Thanks for the report!

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxqt/libfm-qt/pull/873. Like with https://github.com/lxqt/pcmanfm-qt/issues/1719#issuecomment-1404103986, it was what Qt did by default.
