### ISSUE TITLE
Thumbnail view leaves much space in the right under certain window sizes

### ISSUE THREAD

**Issue by q234rty** [lxqt/pcmanfm-qt#1721]
Currently if the window size doesn't fit, say, 5 files in a row, but is too much for 4 files in a row, then all the excessive space seems to go to the right. 

##### Expected Behavior
Excessive space should be spread evenly between all margins, or at least between the left and the right.

##### Current Behavior
Excessive space only goes to the right.

##### Steps to Reproduce (for bugs)
1. Switch to thumbnail view.
2. Adjust the window size so that it doesn't fit 5 files in a row, but is too much for 4 files in a row.
3. Observe that excessive space only goes to the left.

##### Context
When the window is maximized, it is hard to adjust window sizes.

##### System Information
* PcManFm-qt version: 1.2.1-1
* Distribution & Version: Arch Linux 
* Qt Version: 5.15.8, with the KDE Qt5PatchCollection.

**Comment by tsujan** [comment]
The space between items shouldn't depend on the window size, and it doesn't.

**Comment by q234rty** [comment]
> The space between items shouldn't depend on the window size.

Care to elaborate? Dolphin and nautilus seems to both disagree.

Even if that is the case, the excessive space could still be spread over the left and the right.

**Comment by tsujan** [comment]
> Dolphin and nautilus both seem to disagree.

pcmanfm-qt isn't another nautilus or dolphin; it doesn't waste CPU time on such things. Only on desktop, which can't be resized, items are spread to prevent an extra space at the bottom.
