### ISSUE TITLE
The default column 'size' should show the total size of its content

### ISSUE THREAD

**Issue by victor03303** [lxqt/pcmanfm-qt#1728]
# Opening the file manager
The default <i>extended list</i> view adds the usefull 'size' column. However the row of folders remains empty in the size column. I know this is because a folder doesn't have a size. But I think it should show the total size of its content.

# A small paradox
However if you click on properties of a folder <i>it does show a file size</i>. A bit inconsistant, isn't it? 
Why not use the empty space in 'size' for the folder row and fill it up?

# advantages
- We don't have to right-click the folder anymore to know its size
- We don't have to pull up a terminal anymore to know its size
- Easier to keep track of the used space on a disk
- Easier to compare the folders size with each other

# request
Please add the size (as marked in the attached file) to the column 'size'.

# attachement
![FolderSize](https://user-images.githubusercontent.com/55033363/217658700-69dc8c88-f739-49f8-b1bd-51090aa30c85.jpg)

**Comment by tsujan** [comment]
Finding folder sizes can be extremely slow and requires a lot of I/O. It's simply impractical.
