### ISSUE TITLE
Home/End keys are per-line for renaming files on Desktop, Icon view, Thumbnail view

### ISSUE THREAD

**Issue by isf63** [lxqt/pcmanfm-qt#1730]
When you press the Home or End keys when renaming a file, the cursor moves only on current line

##### Expected Behavior
Home key and End key presses set the cursor to the very first and last position

##### Current Behavior
Home key / End key go to the first and last position of the line

##### System Information

* PcManFm-qt version: pcmanfm-qt 1.2.1
* Distribution & Version: Arch Linux
* Qt Version: 5.15.8
* liblxqt Version: 1.2.0

**Comment by tsujan** [comment]
Thanks for the report.

This is what Qt does with an editable `QTextEdit`. Qt's behavior can be overridden, but I'm not sure it'll be worth the extra code. Anyway I'll look into it.

**Comment by tsujan** [comment]
Done in https://github.com/lxqt/libfm-qt/commit/5d155a24ac64f7fa6375bd41cf5f02917e8f9eca

**Comment by isf63** [comment]
I appreciate it.

I wonder if Qt will eventually have this by default.
