### ISSUE TITLE
"Open with other application" categories sometimes automatically collapse when you expand them

### ISSUE THREAD

**Issue by glu8716** [lxqt/pcmanfm-qt#1733]
##### Current Behavior
In the "open with other application" selection menu if I open a category it automatically collapses in a few seconds. When I select it for the second time it doesn't, which is how it should be in the first place. 
![output](https://user-images.githubusercontent.com/33501455/219140778-49cd0ad0-8cc6-494a-870e-419191810cf2.gif)
It has to be noted that this seems to always happen with some files, but only sometimes with others, at least in my environment.

##### Expected Behavior
A category shouldn't collapse by itself.

##### Steps to Reproduce (for bugs)
1. Right click on a file > Open With... > Other Application
2. Expand a category
3. The category will collapse in a few seconds

##### System Information
* Distribution & Version: Artix Linux
* Kernel: 6.1.10-zen1-1-zen
* Qt Version: 5.15.8
* libfm-qt Version: 1.2.1-2
* libqtxdg Version: 3.10.0-2
* lxqt-build-tools Version: 0.12.0-1
* pcmanfm-qt Version: 1.2.1-1.1

**Comment by stefonarch** [comment]
Confirming.

**Comment by tsujan** [comment]
Yes, it's a known side effect of using menu-cache in libfm-qt; see https://github.com/lxqt/libfm-qt/issues/417. The real solution is get rid of menu-cache, instead of adding yet another piece to the patchwork.

**Comment by tsujan** [comment]
Let's continue the patchwork for now — I won't have time for https://github.com/lxqt/libfm-qt/issues/417 soon.
