### ISSUE TITLE
Tab names in locations only partially translated

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1736]
![screen_area_gio_19:07:45_](https://user-images.githubusercontent.com/10681413/222514315-0ee5c1d7-bf56-4391-8e2c-c74a8fd01027.png)

Only `network` looks translated in the tab because of its `.desktop` file, see with `LANG=de´

![screen_area_gio_19:13:27_](https://user-images.githubusercontent.com/10681413/222516806-bbf107de-0f97-4d7f-b0ac-1223cb8103ed.png)

##### Expected Behavior

Location names should be the same ones as in the left pane.
##### Current Behavior

They are always in english.

##### System Information

* PcManFm-qt version: 2.0 and 1.2
* Distribution & Version: arch, debian

**Comment by tsujan** [comment]
Would you please tell me which locations are affected (their English names)?

**Comment by stefonarch** [comment]
All 3, Computer, Network, Applications.

**Comment by tsujan** [comment]
> All 3, Computer, Network, Applications.

In your screenshot, Network is "Rete"; isn't it?

Never mind; I install translations only for a few components, and libfm-qt and pcmanfm-qt are among them. I'll check them later.

**Comment by tsujan** [comment]
Ok, the tab names are created by GLib's function `g_file_info_get_display_name()`. I don't know if it can be localized by GLib at all, but what we get in our Qt app can't be localized.

So, the only way is to add translations of those locations. The translations are already in libfm-qt (the side-pane isn't made by pcmanfm-qt), but I don't think they can be seen by pcmanfm-qt without ugly codes. If impossible, we'll need to duplicate those translatable strings in pcmanfm-qt.
