### ISSUE TITLE
Desktop items momentarily reset during certain actions

### ISSUE THREAD

**Issue by isf63** [lxqt/pcmanfm-qt#1741]
During certain actions, desktop icons are momentarily reset to a default position (for a few milliseconds). The default position that appears is 1) all sticky states removed, 2) work area margins set to (0,0,0,0).

##### Possible Solution
Hide the temporary default state.

##### Expected Behavior
Desktop items do not momentarily flash to a default position during certain actions.

##### Current Behavior
Desktop icons are momentarily set to no sticky items and margins set to (0,0,0,0) during certain actions.

##### Steps to Reproduce (for bugs)
1. Make a desktop item sticky, and/or set "Margins of work area" under Desktop Preferences > General to something other than (0,0,0,0).
2. Right-click on desktop and change an option under Sorting, or repeatedly click Reset in `lxqt-config-appearance` or `lxqt-config-input`.

##### System Information
* Distribution & Version: Arch Linux
* Kernel: Linux 6.2.2-arch1-1
* Qt Version: 5.15.8+kde+r181-1
* liblxqt Version: latest Git
* lxqt-build-tools Version: latest Git
* lxqt-config Version: latest Git
* pcmanfm-qt Version: latest Git

**Comment by tsujan** [comment]
Although it may not be possible to remove all such flickers, I'll look into it.

The rest of this comment explains what happens.

After each change, calculating of the new layout is done with a delay. That delay is needed for minimizing the CPU usage when multiple changes happen within a short interval. In most cases, updating of the desktop is prevented during this delay, so that the user only sees the final layout. But, in some cases, the desktop may be updated before the final layout is set; hence the flickering.

**Comment by tsujan** [comment]
@isf63
Could you please test the fix at https://github.com/lxqt/pcmanfm-qt/pull/1743?

**Comment by isf63** [comment]
Works great!

Right-click > Sorting changes no longer produce flickering, as well as the issue disappearing from `lxqt-config-appearance` and `lxqt-config-input`'s Reset button. Tested with sticky items and non-zero margins.

**Comment by tsujan** [comment]
Thanks a lot for testing!

**Comment by isf63** [comment]
There is another case where all desktop icons "flash" when doing a DnD reposition on the Desktop. This happens randomly, but fairly often. Because it only happens some of the time it makes me think it's a timing/delay issue as well.


https://github.com/user-attachments/assets/80aa98b8-e8f9-42bc-b999-6e00e1201f79

**Comment by tsujan** [comment]
I'm aware of it; it isn't limited to DND and depends on the system's state/spec. After https://github.com/lxqt/pcmanfm-qt/pull/1743, updating of the desktop is prevented during all delays, such that icons don't shake.

I didn't find anything that could be done in our code to prevent that flashing but will think about it again.

**Comment by tsujan** [comment]
@isf63 
In the meanwhile, if you find a way of avoiding them, please feel free to make a PR — I might not find time to have a second look at it soon.
