### ISSUE TITLE
[Feature request] Symlinks to user directories have the same icon

### ISSUE THREAD

**Issue by isf63** [lxqt/pcmanfm-qt#1746]
##### Is your feature request related to a problem? Please describe.
In `lxqt-config-session`, XDG user directories can be specified, and PCManFM-Qt applies special icons to these folders in `$HOME` and under Bookmarks. Symlinks to user directories have a default folder icon, in contrast with symlinks to files having the icon of the source file.

##### Describe the solution you'd like
Symlinks to user directories have the special icons (`folder-documents`, `folder-pictures`...) applied.

An alternative solution is to add user directories to Desktop Preferences → Visible Shortcuts.

##### Current Behavior
Symlinks to user directories have the default folder (`folder`) icon.

##### Context
Some users may want to put symlinks to user directories in the desktop folder to see the special icons for easy access. There may be other uses. A workaround is to use `.directory` files.

##### System Information
* Distribution & Version: Arch Linux
* Kernel: Linux 6.2.6-arch1
* Qt Version: 5.15.8+kde+r182
* liblxqt Version: latest git
* libfm-qt Version: latest git
* pcmanfm-qt Version: latest git

**Comment by tsujan** [comment]
> PCManFM-Qt applies special icons to these folders

The icons of special folders are handled by `GLib`, not by us.

> .... in contrast with symlinks to files

All folders have the same mime type: `inode/directory`. The symlink icon is correct.

Forcing separate icons for symlinks of special folders would require dirty codes for no good reason.

**Comment by isf63** [comment]
Okay. `.directory` files (created by Properties → icon button) and emblems work well.
