### ISSUE TITLE
the path bar colors are not behaving right

### ISSUE THREAD

**Issue by Aneeqasif** [lxqt/pcmanfm-qt#1755]
### Expected colors
![image](https://user-images.githubusercontent.com/78728701/229361600-5d8ad703-ea94-4882-bd27-e86aecb8047f.png)

### Actual
![image](https://user-images.githubusercontent.com/78728701/229361626-bdb0355c-d83f-495f-b513-916a321e1f0c.png)

* PcManFm-qt version: 1.2.1
* Distribution & Version: arco
* Qt Version: 5.15.8
* liblxqt Version:1.2.0

**Comment by tsujan** [comment]
The code doesn't force any color. What you see is what your Qt theme provides.

**Comment by tsujan** [comment]
For reference:

By default, Qt scroll-areas have "auto-filled" backgrounds. Most Qt styles (like Fusion and Breeze) don't change that. The path-bar is a scroll-area; hence, the background.

Some Qt styles (like Kvantum) remove the backgrounds of scroll areas under certain circumstances. The path-bar doesn't have any background with those styles.

All in all, it's up to the Qt style.

**Comment by tsujan** [comment]
Made https://github.com/lxqt/libfm-qt/pull/896 to prevent auto-filling by all styles.

**Comment by Aneeqasif** [comment]
> Made [lxqt/libfm-qt#896](https://github.com/lxqt/libfm-qt/pull/896) to prevent auto-filling by all styles.

thank you so much

**Comment by tsujan** [comment]
You're welcome.

The change will be in 1.3.0, which will be released soon.
