### ISSUE TITLE
[Feature request] Use polkit instead of lxqt-sudo

### ISSUE THREAD

**Issue by ItsDrike** [lxqt/pcmanfm-qt#1759]
#### Is your feature request related to a problem? Please describe.

I'm using pcmanfm-qt outside of LXDE, and I'm using `polkit-gnome`. However currently, pcmanfm-qt wants me to use `lxqt-sudo` when trying to go to the admin mode, which has a dependency on `polkit-qt5`, which I don't want to have installed in my system.

I'm aware that there is a way to change this command in the advanced settings, however the `"Important: Please use lxsudo, sudo alone will wreck permissions of the settings file"` message is discouraging me from attempting that.

#### Describe the solution you'd like

As many other applications, you should just be able to make a polkit request directly, opening a password prompt with whatever polkit agent is being used, without forcing any specific one. 

This would make the applications much more viable for cross-DE usage, rather than being dependent on a very specific sudo wrapper. It would also make it more viable for people that don't even use sudo, and prefer `doas` instead.

#### Describe eventual alternatives you've considered

Make it possible to use regular `sudo` or another command for user switching, or rather, it's technically already possible, but apparently there are issues with it, considering the presence of that Important note. Cover those issues.

**Comment by tsujan** [comment]
The [admin mode](https://github.com/lxqt/pcmanfm-qt/wiki#admin-mode-vs-root-instance) doesn't need lxqt-sudo; it needs GVFS.

If you mean root instance, it doesn't depend on `lxqt-sudo`. That message means you shouldn't use `sudo` but a root privilege program for GUI apps. Of course, we recommend `lxqt-sudo`.

**Comment by tsujan** [comment]
> As many other applications, you should just be able to make a polkit request directly

That's what the admin mode does. It uses GVFS' admin backend, which can do privileged file operations through Polkit.

Doing more than that requires apps that support the admin mode — which, of course, is outside pcmanfm-qt's control. That's why the root instance exists. However, it has no real advantage over the admin mode (except for the timeout of the latter, which could be annoying with large file transfers) because apps that need to do privileged operations (like text editors) should be able to handle it themselves.

**Comment by ItsDrike** [comment]
> If you mean root instance, it doesn't depend on `lxqt-sudo`. That message means you shouldn't use `sudo` but a root privilege program for GUI apps. Of course, we recommend `lxqt-sudo`.

Ah, I did mean root instance then, sorry for the confusion there. I figured I needed to use a GUI program for the escalation, but from your response, it seems that just using normal sudo with `-A`, and having `SUDO_ASKPASS` configured to use something like `dmenu` should work. But the message there says that you shouldn't use sudo, because it would "wreck permissions of the settings file".

Because of that, I assumed that `lxqt-sudo` does something extra to preserve permissions, which sudo doesn't do. If that's not the case, what does this message mean exactly?

**Comment by tsujan** [comment]
> I assumed that lxqt-sudo does something extra to preserve permissions, which sudo doesn't do

Yes! `lxqt-sudo` takes care of environment variables, including those related to Qt. That's why it is highly recommended. `sudo` alone could easily change the permissions of config files/folders and cause serious troubles.

**Comment by ItsDrike** [comment]
So, could you provide an alternative command, that uses `sudo`, and also sets the env. variables necessary to avoid this?

**Comment by tsujan** [comment]
I can't give you a command, but you could **unset** 

```
DBUS_SESSION_BUS_ADDRESS
XDG_CONFIG_HOME
XDG_DATA_HOME
XDG_CACHE_HOME
XDG_DATA_DIRS
XDG_RUNTIME_DIR`
```

and **set** `HOME` to "/root" when using `sudo`. If I correctly remember, that's safe, but *do it at your own risk*.

`lxqt-sudo` is more cautious though. In https://github.com/lxqt/lxqt-sudo/blob/master/sudo.cpp, it unsets everything except for the following EVs:

```c++
    //Note: array must be sorted to allow usage of binary search
    static constexpr char const * const ALLOWED_VARS[] = {
        "DISPLAY"
            , "LANG", "LANGUAGE", "LC_ADDRESS", "LC_ALL", "LC_COLLATE", "LC_CTYPE", "LC_IDENTIFICATION", "LC_MEASUREMENT"
            , "LC_MESSAGES", "LC_MONETARY", "LC_NAME", "LC_NUMERIC", "LC_PAPER", "LC_TELEPHONE", "LC_TIME"
            , "PATH", "QT_PLATFORM_PLUGIN", "QT_QPA_PLATFORMTHEME", "TERM", "WAYLAND_DISPLAY", "XAUTHLOCALHOSTNAME", "XAUTHORITY"
    };
```
