### ISSUE TITLE
Freezes if window height is larger than desktop

### ISSUE THREAD

**Issue by es20490446e** [lxqt/pcmanfm-qt#1761]
### System
* pcmanfm-qt  1.2.1
* liblxqt 1.2.0
* qt 5.15.8
* Manjaro KDE Minimal

### Steps to reproduce
1. At `~/.config/pcmanfm-qt/default/settings.conf` increase the value of `LastWindowHeight`
2. Launch the file manager.

### Result
* The file manager hangs.
* This is relevant because if you launch the file manager with less resolution on the screen than on previous launch the file manager hangs.

**Comment by tsujan** [comment]
Not reproducible with `kwin_x11`. If it happens with another WM, the bug could be reported to its devs(s).

**Comment by es20490446e** [comment]
Actually I'm using kwin_x11...

**Comment by tsujan** [comment]
> Actually I'm using kwin_x11...

Then the problem you've encountered should be caused by something else.

**Comment by es20490446e** [comment]
Are you using display scaling?

**Comment by tsujan** [comment]
> Are you using display scaling?

No.

**Comment by es20490446e** [comment]
Okay, so I figured out the issue.

You have to both set `LastWindowHeight` and `LastWindowWidth` to a big number.

Then if you launch `pcmanfm-qt` from the terminal you get:

```
qt.qpa.xcb: xcb_shm_create_segment() can't be called for size 4491125888, maximumallowed size is 4294967295
Segmentation fault (core dumped)
```

Then it freezes.

So it looks like `pcmanfm-qt` is who shall be in charge of ensuring that size doesn't exceed a certain threshold.

**Comment by tsujan** [comment]
> You have to both set LastWindowHeight and LastWindowWidth to a big number.

No difference; the window is maximized (actually, I'd tested it before). If only the width is hight, the window is maximized horizontally.

None of this has any special relation to pcmanfm-qt. It's related to Qt, X11 and WM.
