### ISSUE TITLE
Disable autostart by default

### ISSUE THREAD

**Issue by GPery** [lxqt/pcmanfm-qt#1767]
Not sure if it's quite a bug report, but I don't think PCManFM should assume it'll be used as the desktop as well.

##### Expected Behavior
Install with CMake without automatically starting PCManFM as desktop.  
I use the pacman package with i3wm and would rather not add a hook to delete the file from `/etc/xdg/autostart` every update.

**Comment by tsujan** [comment]
> Disable autostart by default

The desktop entry has `OnlyShowIn=LXQt;`, which means it's only for an LXQt session. Of course, LXQt components *should* be auto-started under LXQt.

It doesn't auto-start under other sessions, and even in an LXQt session, it can be disabled in Session Settings.
