### ISSUE TITLE
[Feature request] Add sidebar' separator items 

### ISSUE THREAD

**Issue by redtide** [lxqt/pcmanfm-qt#1769]
**Is your feature request related to a problem? Please describe.**

Not really a problem but for a need of better readability,
to distinguish different contexts.

**Describe the solution you'd like**

Like in pcmanfm GTK2. below the disks:
![immagine](https://user-images.githubusercontent.com/1171962/235643983-9baa1bd7-e42d-4f74-9927-7d7f15e065cf.png)

**Describe eventual alternatives you've considered**

None, except the current workaround with a random folder named `---`.
Just like a vertical toolbar' separator.

##### Context

For example I have different type of favorite folders:

network drives

---
software development projects

---
web projects

---
...

**Comment by tsujan** [comment]
Are you sure you have pcmanfm-qt?!

![sidepane](https://user-images.githubusercontent.com/981076/235687689-57891ab7-1db5-4536-8533-c8ee24906383.png)

**Comment by redtide** [comment]
Yes, as in "Describe the solution you'd like" the image was from pcmanfm-gtk which I installed to show as example of what I was requesting, a simple "Add separator" feature to add separators on the sidebar, but NVM, yet another discarded idea.

**Comment by tsujan** [comment]
> the image was from pcmanfm-gtk

In that case, my screenshot shows that the side-pane of pcmanfm-qt is much tidier.

> a simple "Add separator" feature

`QTreeView` doesn't support separators because it's already ordered like a tree. A "simple" Add-separator feature would need rewriting `QTreeView` from bottom to top: just a few thousands lines of code.

**Comment by tsujan** [comment]
> [Subclassing](https://forum.qt.io/post/164440), though I see it might be too much replace it

Almost everything is done by subclassing. It doesn't make a magic by itself. You have to estimate how deep you need to subclass. Sometimes you find yourself rewriting whole classes, and that could be good if your goal is worth the effort.

> But I wonder why to close this so quickly

Because it would mean doing a huge job for something small, which isn't needed BTW..
