### ISSUE TITLE
Create new file from template, prompt should select only base name

### ISSUE THREAD

**Issue by isf63** [lxqt/pcmanfm-qt#1777]
When going to 'File manager/desktop → Create new → \<template\> → Enter name' it would be nice if the file extension (if any) wasn't selected.

![screenshot02](https://github.com/lxqt/pcmanfm-qt/assets/121320947/f5847cf7-efc9-4328-b470-35af4a42ea8b)

**Describe the solution you'd like**
If and only if there is a file extension, exclude that from the initial selection.

**Comment by tsujan** [comment]
This makes perfect sense. Will look into it.

**Comment by isf63** [comment]
Tested and works great, thanks! Couldn't find any changes other than the selection.
