### ISSUE TITLE
[Feature request] Option for "Open in Terminal" to open directory in QTerminal dropdown

### ISSUE THREAD

**Issue by isf63** [lxqt/pcmanfm-qt#1790]
**Is your feature request related to a problem? Please describe.**
For those who use QTerminal dropdown, one reason they do is to manage terminals in one location.

Currently with "Open in Terminal" that opens a regular QTerminal window, it can become confusing to manage all these terminals (for those who use QTerminal dropdown).

**Describe the solution you'd like**
An option to select "QTerminal dropdown" in Preferences → Advanced → Terminal emulator.

Selecting such, "Open in Terminal"/F4 would open the directory in a new tab in the dropdown if QTerminal dropdown is running. If it isn't running, it would start `qterminal -d -w <dir>` 

##### Context
I find it hard to keep track of terminals when I use QTerminal dropdown and also have QTerminal windows opened.

**Comment by tsujan** [comment]
→ https://github.com/lxqt/pcmanfm-qt/wiki/custom_actions

**Comment by isf63** [comment]
That is neat, I never messed with those until now.

Seems like to accomplish this QTerminal needs more command-line options. I have in `~/.local/share/file-manager/actions/qterminal-dropdown.desktop` :
```
[Desktop Entry]
Type=Action
Icon=utilities-terminal
Name=Open in QTerminal dropdown
Profiles=profile-zero;

[X-Action-Profile profile-zero]
MimeTypes=inode/directory;
Exec=qterminal -d -w %D
Name=Default profile
```

This creates a new inaccessible instance of the QTerminal dropdown, whereas `-d` should probably open a new tab if an instance is already running. Anyway this is an elegant solution.

**Comment by tsujan** [comment]
> Seems like to accomplish this QTerminal needs more command-line options

Maybe.

However, such things aren't related to pcmanfm-qt, because there's no generic way of calling a terminal in drop-down mode (which isn't a generic mode either).

In contrast, and for example, the generic method of "file manager DBus Interface" exists — and pcmanfm-qt supports it.
