### ISSUE TITLE
Open With ... > Other Applications Choose Application > Installed Applications Displays a blank box.

### ISSUE THREAD

**Issue by cwhii** [lxqt/pcmanfm-qt#1791]
WHAT I DO:

PCManFM-Qt > Open With ... > Other Applications Choose Application > Installed Applications

WHAT IT DOES:

Displays a blank box.
![image](https://github.com/lxqt/pcmanfm-qt/assets/1233816/3379d4d7-e10d-4f43-89b8-ea1d2c9eab8b)

I expect to see a tree of applications grouped by type.

When I use Dolphin it works as expected.
![image](https://github.com/lxqt/pcmanfm-qt/assets/1233816/313956bd-da50-4acd-bcde-ec82f991922e)

1.  PCManFM-Qt 
2.  Open With ..
3.  Other Applications Choose Application
4. Installed Applications

##### System Information

System has been upgraded using existing user files, /home, from a previous version, thus the request for help in debugging by posting "Where is the grouping & list of applications defined for PCManFM-Qt?" to stackexcahnge, https://unix.stackexchange.com/questions/750722/where-is-the-grouping-list-of-applications-defined-for-pcmanfm-qt

Previous completely clean install's of various ubunutu like including kubuntu have has flakely behavior in the same area but never a completely blank list of apps.  There would be categories and when expanding the sub lists the apps would not display or something like that. This happened over a number of system & PCManFM-Qt versions. I presumed the issue would be caught and fixed.

* PcManFm-qt version: 1.2.1
* Distribution & Version:  kubuntu 23.04
* Qt Version:
* liblxqt Version:

**Comment by stefonarch** [comment]
Do you have `lxmenu-data' installed?

**Comment by tsujan** [comment]
Not reproducible. Most probably, you haven't installed `lxmenu-data`.

**Comment by cwhii** [comment]
Should  `lxmenu-data` be a dependency for installing pcmanfm-qt?

![image](https://github.com/lxqt/pcmanfm-qt/assets/1233816/c90b189e-d3f4-40d4-a2e1-acffcbf23c47)

**Comment by cwhii** [comment]
> Do you have `lxmenu-data` installed?

No.

`sudo apt install lxmenu-data pcmanfm-qt`

and reboot corrected the problem.

**Comment by tsujan** [comment]
> Should lxmenu-data be a dependency for installing pcmanfm-qt?

It isn't a build dependency; it'll be used if installed. But distros usually make it an optional dependency of their packages (Debian-based distros call it Recommended).

However, in git, we've replaced `lxmenu-data` with  `lxqt-menu-data` and made the latter a dependency of `libfm-qt`, such that user's won't encounter a blank list anymore.
