### ISSUE TITLE
thank you for new bugs!

### ISSUE THREAD

**Issue by 221V** [lxqt/pcmanfm-qt#1795]
lubuntu 22.04 LTS, Asus TUF Gaming F15

##### Expected Behavior
file explorer not freezes all system, not freezes mouse+keyboard input 

##### Current Behavior

sometimes this file explorer freezes all system, freezes mouse+keyboard input 

##### Possible Solution

maybe to use C++ is root of problem? i do not know

##### Steps to Reproduce (for bugs)

1.
2.
3.
4.

##### Context

there are next bug, that freezes the system, freezes mouse and keyboard input,
nothing helps, only hard reset with data losses --

1 -- install Gnokii / XGnokii, connect nokia by usb, connected, open folder -- lubuntu frozen .. ((

2 -- the same, connect nokia -- all ok, nokia connected, try to create new dir onto PC disc (not nokia) -- lubuntu frozen .. ((

3 -- want to record screen video by silentcast - https://github.com/colinkeenan/silentcast/issues/8 -

```
compton -b
```

and lubuntu frozen ..((
but with config not freezes --

```
compton --config ~/.config/compton.conf -b
```

4 -- also usb stick can be damaged with it --
you can click Unmount, but not see that pcmanfm-qt eats the glue, and usb will be damaged ((

5 -- also there was other case for get frozen lubuntu, but i forget now some details, cannot describe now

this list the bug occurs will be updated, thank you ...

P.S. lubuntu 14.04 LTS , 16.04 LTS and 18.04 LTS was not so freeze-bugy, like 22.04 LTS ..
just install earlyoom for prevent browser eat all RAM, and all ok, not like now...

looks like in last version you make something not true((

##### System Information

* PcManFm-qt version:
* Distribution & Version:
* Qt Version:
* liblxqt Version:

screenshots https://imgur.com/a/22bQlmT

lubuntu 22.04 LTS, Asus TUF Gaming F15

**Comment by palinek** [comment]
Maybe I'm alone with this, but I think, that with such an attitude you probably won't get much attention.

**Comment by 221V** [comment]
> Maybe I'm alone with this, but I think, that with such an attitude you probably won't get much attention.

hey, You thinking, i must be happy for data loses with this bug?

was no that bug in previous LTS Lubuntu, and i was happy,
but now i have this bug with data losses -- an improvement indeed, i "like" this "improvement" ... ((

**Comment by tsujan** [comment]
Read the template before filling it:

```
Dear users of stable and LTS (Long Term Service) distributions:...
```
