### ISSUE TITLE
[Feature request] List files in delete confirmation dialog

### ISSUE THREAD

**Issue by redtide** [lxqt/pcmanfm-qt#1797]
**Is your feature request related to a problem? Please describe.**

When deleting permanently files, the confirmation dialog doesn't give any clue about
the files is going to delete and I'm often worried that I selected some other file I don't want
to delete.
To name some well known applications having this features:
years ago, before switching to LXQt, I was using PCManFm (GTK2) and I recall it had this feature, and I see now how much useful it was.
To name another one there is VSCode.

**Describe the solution you'd like**

To add something like a QListWidget that lists the files/directories selected for
permanent deletion.
Maybe it should have a limit when too many files were selected,
I'm not sure how the best implementation would be.

**Describe eventual alternatives you've considered**

No idea.

##### Context

When deleting files. See above.
(I'm starting to wonder what this "Context" info is about, there are already 3 sections asking what is the problem and how to solve it and even alternatives.
People must be really lazy with no empathy for the readers at describing things to need this.)

**Comment by tsujan** [comment]
I'm sure this is a duplicate. Instead of finding the original report, which can be time-consuming, I answer separately:

The files are already selected. A list doesn't add more info, and we avoid cluttering the app with duplicated functionalities. Moreover, a list would be useless with a great enough number of files.

**Comment by tsujan** [comment]
Oh, I forgot to add that, a list would take the CPU time with a huge number of files.

**Comment by redtide** [comment]
> I'm sure this is a duplicate. Instead of finding the original report, which can be time-consuming

I did a search with the filter `is:issue in:title delete` but haven't found any.

> The files are already selected. A list doesn't add more info, and we avoid cluttering the app with duplicated functionalities.

It is not, in a big directory it's difficult to read the list with the unselected files, a report like that is clear because lists only the files selected. I don't believe it's a big effort nor useless as feature and if other apps have it there is a reason. Anyway, Amen to it.

> Oh, I forgot to add that a list would take the CPU time with a huge number of files.

I said, if huge can be limited.

**Comment by tsujan** [comment]
I'm afraid I strongly disagree. Add this or that duplication just because it seems small and "useful", and after a while, you'll see the app will be cluttered like a KDE app is.

**Comment by cunlem** [comment]
File manager showing which files it's about to delete from disk is considered bloat? Even `/bin/rm` has this feature.
