### ISSUE TITLE
[Feature request] Side Padding in Detailed List view

### ISSUE THREAD

**Issue by tim78245** [lxqt/pcmanfm-qt#1805]
Add 10 pixels at the start of the column in detail list view so you can select items by clicking and dragging. This is based on KDE's Dolphin feature (right click columns, check "Side Padding")

Video of the feature:
![Peek 2023-08-25 19-47](https://github.com/lxqt/pcmanfm-qt/assets/111637211/255eabe4-f938-4478-a355-86e78987eedd)
At the end of the video you can also see KDE's dolphin has the ability that selecting blank spaces in columns allows you to do the same, but this is probably more complicated to implement than side padding.

Without this feature, so far as I can tell, you are limited to clicking and shift/control clicking. Which is fine, but this is rather nice to have too.

**Comment by tsujan** [comment]
→ https://github.com/lxqt/libfm-qt/commit/1b2dd01ddc0797cdecb89eda13435be726f20bc6

You may have an old version.
