### ISSUE TITLE
DJVU thumbnails.

### ISSUE THREAD

**Issue by emerajid** [lxqt/pcmanfm-qt#1809]
Not really an issue, but I do not know where else I should post this, so sorry if I'm a nuisance.

https://github.com/lxqt/pcmanfm-qt/issues/1080
Above thread goes about explaining how to get PDF thumbnails to work and the last comment also explains how to get DJVU thumbnails.

It doesn't work in Debian 12, possibly because pcmanfm-qt cannot read TIFF files. I'm not into QT desktop environments, so maybe I just miss some packages (just a few days ago I discovered I need lxmenu-data for some things to show up), but so far working solution is
```
/usr/local/bin/djvu-thumbnail.sh:
#!/bin/sh
set -eu
in="$1"
size="$2"
out="$3"

ddjvu -format=ppm -page=1 -size="${size}x${size}" "$in" - |
	convert ppm:- png:"$out"
```
and
```
/usr/local/share/thumbnailers/djvu.thumbnailer:
[Thumbnailer Entry]
Exec=djvu-thumbnail.sh %i %s %o
MimeType=image/vnd.djvu+multipage;image/vnd.djvu;
```

**Comment by tsujan** [comment]
> possibly because pcmanfm-qt cannot read TIFF files

Install `qt5-imageformats` and `kimageformats` (find their package names for Debian) to cover more image formats. They're also recommended for [LXImage-Qt](https://github.com/lxqt/lximage-qt) — I think some Debian LXQt package(s) should include them under "Recommends" .

The Wiki: https://github.com/lxqt/pcmanfm-qt/wiki#thumbnails

Please use https://github.com/lxqt/lxqt/discussions for asking questions.
