### ISSUE TITLE
Sorting case sensitive does not work

### ISSUE THREAD

**Issue by ufleisch** [lxqt/pcmanfm-qt#181]
Switching "Sorting/Case Sensitive" on and off does not seem to change anything - sorting is always case-insensitive. Besides this, the setting is not stored persistently.

**Comment by tsujan** [comment]
There's still no mechanism for remembering that setting in pcmanfm-qt but it should have a temporary effect for the folder it's set in. Definitely a bug to be fixed.

**Comment by tsujan** [comment]
Another point: when sorting is case insensitive, Qt sorts files with the same name (ab, Ab) randomly but USUALLY in a case sensitive order. So when you switch to the case sensitive sorting, nothing might happen.

**Comment by tsujan** [comment]
> that should depend on the used locale

Maybe. I remember I read about the randomness in an old Qt doc though. Will check it in the new one later.

**Comment by tsujan** [comment]
In the case-sensitive mode, aB comes before Ab but, in the case-insensitive mode, it's Ab and then aB. So, it works. The rest is related to https://github.com/lxqt/pcmanfm-qt/issues/887, which is more general.
