### ISSUE TITLE
Unable to disable alternate row colors

### ISSUE THREAD

**Issue by SjoerdV** [lxqt/pcmanfm-qt#1813]
I checked the only other discussion in this repo on the subject, and I fell asleep...

##### Expected Behavior
There should be an option to disable alternating row colors (globally, not for a certain view, specifically), for peeps (like me) who really hate that 'feature'.

##### Current Behavior
No option to disable a very prominent 'in your face' visual 'feature' is not really Linux/FOSS. That's one of the reasons I am not on Mac/Windows...

##### Possible Solution
Just add a checkmark in 'User Interface' settings to disable it **globally** please

##### Steps to Reproduce (for bugs)
N/A

##### Context
Stripes on the screen give me epileptic tendencies ;-) and it gives me nightmares of the interlaced PAL/NTSC TV from 20 years ago, retro gaming is a choice, you know.

##### System Information

* PcManFm-qt version: 1.2.1
* Distribution & Version: LMDE6
* Qt Version: 1.2
* liblxqt Version: 1.2.0

**Comment by tsujan** [comment]
As has been mentioned on several occasions, options aren't added for everything users may like or dislike.
