### ISSUE TITLE
no eject option on context menu for USB external hard drives

### ISSUE THREAD

**Issue by thingswelostinthefire** [lxqt/pcmanfm-qt#1820]
##### Expected Behavior
Right clicking on a Device (USB external hard drive) there should it be both the "Unmount" and "Eject" options.

##### Current Behavior
Right clicking on a Device (USB external hard drive) there is just the "Unmount" option.
Right clicking on a Device (USB external hard drive) there are both the "Unmount" and "Eject" options.

##### Possible Solution
To safely remove my USB external hard drive I have to use the command line (udisksctl power-off -b /dev/sda).

##### Steps to Reproduce (for bugs)
1. Insert a USB external hard drive
2. Check the left menu for the device in PcManFm-qt

##### System Information
* PcManFm-qt version: 1.3.0
* Distribution & Version: Lubuntu 22.04
* Qt Version: 5.15.3
* liblxqt Version: 1.3.0

![no-eject-on-context-menu-4](https://github.com/lxqt/pcmanfm-qt/assets/42820982/437649bd-3caa-4951-8a61-4868f3cc52a5)
![no-eject-on-context-menu-3](https://github.com/lxqt/pcmanfm-qt/assets/42820982/242d96d0-c9ee-49d9-b8d1-f6b8de5302a2)
![no-eject-on-context-menu-2](https://github.com/lxqt/pcmanfm-qt/assets/42820982/c1436358-dcf7-479e-bac8-d979ee7ec7a0)
![no-eject-on-context-menu-1](https://github.com/lxqt/pcmanfm-qt/assets/42820982/2171cf66-5ec1-4d44-88b1-b31bf270e6b7)

**Comment by tsujan** [comment]
What can be there isn't arbitrary but determined by GLib, based on `G_FILE_ATTRIBUTE_MOUNTABLE_CAN_MOUNT`, `G_FILE_ATTRIBUTE_MOUNTABLE_CAN_UNMOUNT`, `G_FILE_ATTRIBUTE_MOUNTABLE_CAN_EJECT`.

**Comment by tsujan** [comment]
> To safely remove my USB external hard drive I have to use the command line

No, you don't.

**Comment by thingswelostinthefire** [comment]
> What can be there isn't arbitrary but determined by GLib, based on G_FILE_ATTRIBUTE_MOUNTABLE_CAN_MOUNT, 
> G_FILE_ATTRIBUTE_MOUNTABLE_CAN_UNMOUNT, G_FILE_ATTRIBUTE_MOUNTABLE_CAN_EJECT.

Ok, I give up: too complicated :-D

> > To safely remove my USB external hard drive I have to use the command line
> 
> No, you don't.

Clicking on just the "Umount" my USB external hard drive keeps spinning...

Sorry for wastring your time and thanks for the beautiful file manager!

**Comment by tsujan** [comment]
> Ok, I give up: too complicated

It wasn't my intention :) I just wanted to explain that it's what GLib gives us (GLib is the file management library PCManFM-Qt and many other FMs use); we just follow it.

> Clicking on just the "Umount" my USB external hard drive keeps spinning...

Wherever there's no "eject" option, GLib developers should think that unmounting is enough for disconnecting. I'd trust them.
