### ISSUE TITLE
wallpaper-mode=zoom does not work

### ISSUE THREAD

**Issue by pjw91** [lxqt/pcmanfm-qt#1821]
##### Expected Behavior

The command `pcmanfm-qt --set-wallpaper=a.png --wallpaper-mode=zoom` should set the wallpaper image and corresponding wallpaper mode.
##### Current Behavior

Nothing happens.
##### Possible Solution

I saw a dbus method `setWallpaper("/path/to/png", "zoom")` is called. Howeverm nothing happens.

It seems that the `DesktopWindow::WallpaperMode::WallpaperZoom` is not declared in the `valid_wallpaper_modes` (`Application::setWallpaper`) and is ignored.

##### Steps to Reproduce (for bugs)

1. pcmanfm-qt --set-wallpaper=a.png --wallpaper-mode=zoom
2.
3.
4.

##### System Information

* PcManFm-qt version:1.3.0
* Distribution & Version:archlinux/endeavouros
* Qt Version:5
* liblxqt Version:

**Comment by tsujan** [comment]
Thanks for reporting! The command-line option `--wallpaper-mode` seems like a mess.

**Comment by tsujan** [comment]
The fix is here and will be in 1.4.0 (coming soon): https://github.com/lxqt/pcmanfm-qt/pull/1822

The problem was that many things were changed version after version, but that function remained as it was because, apparently, no LXQt member changed wallpaper mode through command-line (neither I did).

**Comment by stefonarch** [comment]
> The command `pcmanfm-qt --set-wallpaper=a.png --wallpaper-mode=zoom` should set the wallpaper image and corresponding wallpaper mode.

´-set wallpaper=file.png' works only in home dir if the file is there and doesn't take pathes, the correct syntax is `-set-wallpaper /path/to/file` .

**Comment by tsujan** [comment]
@pjw91, please check `pcmanfm-qt --help`; that `=` shouldn't be included.
