### ISSUE TITLE
Window is resizing on start

### ISSUE THREAD

**Issue by GrabbenD** [lxqt/pcmanfm-qt#1823]
##### Expected Behavior

The window should be initialized with the correct size when starting pcmanfm-qt and not resize whilst rendering.

##### Current Behavior

When starting pcmanfm-qt (`1.3.0`) and pcmanfm-qt6 (`wip_qt6` branch) there is a noticeable resize happening from a small window to a larger in Sway 1.9-dev with Arch Linux

This behavior cannot be observed with pcmanfm-gtk (`1.3.2`) and it's mostly **noticeable with resolution greater than 960x400**

##### Possible Solution
Determinate the window size before drawing contents/DOM

##### Steps to Reproduce (for bugs)
1. `$ pcmanfm-qt`

##### Context
I'm looking for a alternative to Thunar since it sometimes wont start and found pcmanfm but unfortunately the -gtk version rarely gets updated and -qt has problems with resizing which isn't visually appealing even though it starts slightly faster than Thunar.

##### System Information
* PcManFm-qt version: `1.3.0.34.gb6290df2-1`
* Distribution & Version: `Arch Linux`
* Qt Version: `6.6.0-2.1`
* liblxqt Version: N/A

**Comment by stefonarch** [comment]
Do you use it floating or tiled?

**Comment by tsujan** [comment]
Not caused by pcmanfm-qt, and not seen here under KWin-X11, KWin-Wayland, Wayfire or LabWC (which I'm using now).

**Comment by stefonarch** [comment]
I tested sway and hyprland with different settings, couldn't reproduce again but I'm wondering what could cause it.

**Comment by tsujan** [comment]
I didn't know you had Sway too! Is there any WM you haven't covered for testing LXQt? ;)  I guess it's GNOME, which I cover — have its latest version on my old laptop.

**Comment by stefonarch** [comment]
I've all 5 sessions [here](https://github.com/stefonarch/LXQt-Wayland-files) configured in sddm (to be honest sway and hyprland I can't really use  as I don't remember the shortcuts anymore). In plus some "blank" default session, labwc default, wayfire default. So switching between them or x11  is just a matter of a session restart.

**Comment by tsujan** [comment]
> Oh, and I don't have river

Hadn't heard of it, but found it after you mentioned it: https://github.com/riverwm/river

**Comment by GrabbenD** [comment]
Thanks a ton for taking a look guys
I found a solution for the QT version
Let me know if something is still missing/could be improved!

# QT FIX

My environment was using XWayland before I added the right configuration.
Here's my current setup:

First I configured XDG by installing:
- `xdg-desktop-portal-gtk` (most of my primary apps are GTK)
- `xdg-desktop-portal-wlr` (screensharing/screenshot support in Sway)
- `xdg-desktop-portal-lxqt` (for PCManFM)
- `~/.config/xdg-desktop-portal/sway-portals.conf`
   ```ini
   # Override /usr/share/xdg-desktop-portal/portals/
   [preferred]
   # Use xdg-desktop-portal-gtk for every portal interface
   default=gtk
   # Except for the xdg-desktop-portal-wlr supplied interfaces (https://github.com/flameshot-org/flameshot/issues/3363#issuecomment-1749382501)
   org.freedesktop.impl.portal.Screencast=wlr
   org.freedesktop.impl.portal.Screenshot=wlr
   # PCManFM QT
   org.freedesktop.impl.portal.FileChooser=lxqt
   ```

Then I installed pcmanfm:
- `pcmanfm-qt6` package (`wip_qt6` branch since it launches twice as fast as QT5 and faster than Thunar)
- `qt6-wayland` package
- `export QT_QPA_PLATFORM="wayland;xcb" # QT6 Wayland (OBS/PCManFM) with X11 fallback (Zoom)` (in my `start.sh` script since I don't use a Display Manager)

This fixed the startup resizing in Sway and Hyprland 🙂 !

# GTK

I don't experience this issue in Sway but I noticed that in Hyprland the original version of PCManFM (GTK) resizes!
Haven't found a solution yet

**Comment by tsujan** [comment]
PCManFM-Qt doesn't need `xdg-desktop-portal-lxqt`, although it can be installed. Please see https://github.com/lxqt/lxqt/discussions/2487#discussioncomment-7422862

**Comment by GrabbenD** [comment]
> PCManFM-Qt doesn't need xdg-desktop-portal-lxqt

Is this correct even if you're using Sway/Hyprland @tsujan? (How would Chromium/Brave know which Filepicker to use)?

**Comment by tsujan** [comment]
It's good to install `xdg-desktop-portal-lxqt` because apps that aren't based on Qt (like Firefox, Chromium,...) will use the advanced file dialog of LXQt with it. I just wanted to say that your main problem was the lack of Qt6 plugins -- otherwise, keep `xdg-desktop-portal-lxqt`.

**Comment by GrabbenD** [comment]
You're quick, thanks!

Regarding the GTK version. I'm not planning to use it but I got really curious why it resizes in Hyprland (with [animations disabled](https://wiki.hyprland.org/Configuring/Uncommon-tips--tricks/#toggle-animationsbluretc-hotkey)), does anyone know what could be culprit?

**Comment by tsujan** [comment]
The GTK version isn't developed by LXQt. You might want to ask your question where it's developed (although I don't know whether it's developed actively).

**Comment by stefonarch** [comment]
Just a note: `xdg-desktop-portal-lxqt` doesn't work under wayland yet.

**Comment by tsujan** [comment]
> they have some issues like not closing menus if moving window by dragging the titlebar

I wanted to say, "at least somewhere Qt is ahead of GTK regarding Wayland," but if you drag a Qt window by using Alt+Drag under LibWC (provided that you've enabled Alt+Drag or something similar), you'll see its menu isn't closed either. So, it may be a general Wayland issue.

**Comment by stefonarch** [comment]
True :/
But dragging by title bar works better with Qt  :)

**Comment by tsujan** [comment]
> But dragging by title bar works better with Qt :)

Yes, it's normal.
