### ISSUE TITLE
Consider removing backspace shortcut as Alt+Left alternative

### ISSUE THREAD

**Issue by pols12** [lxqt/pcmanfm-qt#1827]
**Context**
Pressing down Backspace key currently allows to visit previous page in history. This shortcut has been introduced for external consistency with other file managers and web browsers. Historically, that seems to be introduced by Internet Explorer.

However:
* The matching Shift+Backspace shortcut to go forward in history has not been introduced.
* Web browsers have removed this issuing shortcut for similar accidental triggering (there are much less accidental use cases for file browser, though): [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1041377), [Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=413395).
* According to [that 2006 bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=325541), the platform convention for Linux (or GNOME?) used to scroll a page up while pressing backspace, rather than go back in history.

**Problem**
That shortcut is accidentally triggered while using Filter bar ([anticipated by tsujan](https://github.com/lxqt/pcmanfm-qt/issues/744#issuecomment-410927036), [experienced by manaskerekar](https://github.com/lxqt/pcmanfm-qt/issues/744#issuecomment-485222517)), so we have to avoid keeping pressed backspace down to benefit from automatic key repeating, yet a pretty common pattern while typing text.

**Solution**
Disabling backspace shortcut: users will use Alt+Left arrow to visit previous folder, as they probably already do on the web.

**Eventual alternative**
Allows a preference or a configuration, similar to `browser.backspace_action` in Firefox.

**Comment by tsujan** [comment]
As a user, I agree with you; I don't like what backspace does here either, exactly for the same reason as you explained.

As a dev, I can't agree about a change that might break the workflow of many users.

> Allows a preference or a configuration,

No. The Preferences dialog shouldn't be cluttered; it already has too many options.

**Comment by pols12** [comment]
>I can't agree about a change that might break the workflow of many users.

Given nobody has requested support for Shift+Backspace to go forward, I think there are not *many* users which actually use Backspace shortcut. But I absolutely understand your position.

> The Preferences dialog shouldn't be cluttered; it already has too many options.

I agree with you we should not include another option in preference dialog. However, we could still support a configuration file, similar to Firefox’s about:config database which allows advanced users to change some config without integrating them in the preference GUI.

**Comment by tsujan** [comment]
> I think there are not many users which actually use Backspace 

I've been "attacked" by some users for breaking their *habits*, while I haven't broken workflows as far as I remember ;)

> However, we could still support a configuration file

Config files already exist; the user should just quit pcmanfm-qt before editing them manually — and, of course, he needs a sort of advanced knowledge.

What you mean is adding an option without adding it to the GUI. While it's a possibility (a good one, actually), we haven't done it elsewhere. Conversely, we've discouraged manual editing for obvious reasons.

The reasons you've provided sound quite convincing to me. Maybe we should disable Backspace only when the transient search-bar is active? Although that might still make some users angry, we can't make everyone happy at the cost of a UX problem.

**Comment by andrei-korshikov** [comment]
Has something been changed? On 1.4.1 I see this behavior:
- press "left" on mouse wheel - go to previous folder in history (like in web browsers)
- press "backspace" - go to parent folder (and I like this behavior), not "previous folder in history"
- press "backspace" in transient filter-bar - remove the last character (as expected; folder is not changed)

If it matters, I use KDE on Arch Linux.

**Comment by tsujan** [comment]
> Has something been changed?

No. LXQt doesn't like backward incompatible changes.

**Comment by andrei-korshikov** [comment]
Very interesting! So, backspace behavior depends on desktop environment, am I right? I mean, I see the very opposite from what OP says.

**Comment by tsujan** [comment]
Help → Hidden Shortcuts → Backspace = Go up. It has nothing to do with history.

**Comment by tsujan** [comment]
I kept this report open only because of what was described under "Problem" in the reporter's comment, without paying attention to his his mistake.

Closing to avoid more misunderstanding....

**Comment by pols12** [comment]
Indeed: backspace is not an alternative of Alt+Left, but an alternative of Alt+Up. My bad. This is still an issue, though.

**Comment by tsujan** [comment]
> This is still an issue

I wouldn't call it an issue, especially when there are already 3 ways of clearing the entry, by pressing `Escape`, `Ctrl+K,` and `Ctrl+U` (Qt's default).

Anyway, a backward incompatible change isn't an option.
