### ISSUE TITLE
enable/disable background painting in desktop mode

### ISSUE THREAD

**Issue by oouuppss** [lxqt/pcmanfm-qt#183]
Desktop GUI option should have a check box to let user choose or not if pcmanfm-qt define background. 
This will let them use another program, or script with they specific need or wish.
I'am currently using feh script to print random background at startup, and after some time; i must delete pcmanfm-qt from startup to let my script working.
Thanks

**Comment by tsujan** [comment]
pcmanfm-qt supports slides for a long time. If you don't like pcmanfm-qt's desktop bg, disable the desktop daemon.
