### ISSUE TITLE
[Feature request] Add Image Metadata in properties if possible

### ISSUE THREAD

**Issue by bps86** [lxqt/pcmanfm-qt#1831]
**Is your feature request related to a problem? Please describe.**

Currently, image properties only show permission and general properties such as filetype, last modified, etc. Since the file manager doesn't provide those feature, I have to use workaround to check Image resolution such as using krita on every single image which can be quite a chore. I also haven't see a solution/feature request about this on issue so I figured I might need to send one.

**Describe the solution you'd like**

The solution would be adding metadata section from right side of permission section in file properties. Metadata not only useful for Images, but also applicable for Video and Audio, if you are will to apply the feature/possible to be applied inside pcmanfm-qt

##### Context

I usually check resolution on file manager because it's faster especially when I'm working with multiple assets. Sometimes it is faster to check several metadata on file properties from file manager. It will be faster than opening those metadata files with editor/art software like krita one by one which can cost time and performance. I think this will be very useful for general user of pcmanfm-qt

**Comment by tsujan** [comment]
PCManFM-Qt supports [custom actions](https://github.com/lxqt/pcmanfm-qt/wiki/custom_actions), which can be used to get any info on any MIME type. It's not the job of the main code to give specific info on specific MIME types (image, audio, video, text,…),; that should be done by apps made for those purposes.

**Comment by bps86** [comment]
Hmm, understandable. Thank you for the respond,
