### ISSUE TITLE
Single click activation

### ISSUE THREAD

**Issue by gfgit** [lxqt/pcmanfm-qt#1835]
##### Expected Behavior

Setting item about using single click to open files and folders should be tristate.

1. Use double click to open files
2. Use single click to open files
3. Use system defaults (provided by Qt platform plugin, like `lxqt-qtplugin`)

##### Current Behavior

Now there is only a checkbox to use single click. If it's not checked it may seem it uses double click but instead it's using system default which could again be single click activation. This turns the checkbox into a no-op and misleads the user.

##### Possible Solution

Use 3 radio buttons, so it's very clear what is happening.

##### Steps to Reproduce (for bugs)

1. Use `lxqt-qtplugin` for QPA
2. Set single click option in `lxqt.conf`
3. Disable single click inside PCMan-FM
4. It's still using single click because of step 2

##### Context

Single click is useful for tablets but when using convertibles and plugging a mouse, double click behavior should be restored.

##### System Information

* PcManFm-qt version: master
* Distribution & Version: PostmarketOS edge
* Qt Version: 5.15
* liblxqt Version: 1.4.0

**Comment by gfgit** [comment]
[application.cpp#L74](https://github.com/lxqt/pcmanfm-qt/blob/b224e0c1f912acb759cefa64aa564e337bd8ffc7/pcmanfm/application.cpp#L74) for reference.

**Comment by tsujan** [comment]
It has a tooltip.

**Comment by gfgit** [comment]
Ok but I think it's less intuitive. Also why forcing single click over global default and not allowing to force double click over global single click?

**Comment by tsujan** [comment]
The text is clearly about single clicking, which means the box enforces it (to enable auto-selection). The tooltip wasn't needed but confirms that.

Also, cluttered config GUIs should be avoided.

> why forcing single click

→ auto-selection
