### ISSUE TITLE
Oxygen-icons could be marked as a dependency

### ISSUE THREAD

**Issue by developer1105** [lxqt/pcmanfm-qt#1838]
Having installed pcmanfm-qt in Arch Linux, I faced the problem of no icons showing in the application.

The solution was to install the oxygen icon theme. (```sudo pacman -S oxygen-icons```)

Wondering about the experience of other users, I think oxygen icon theme could be marked as a dependency of pcmanfm-qt in Arch Linux.

This would make pcmanfm-qt work out of the box in Arch and all the other Arch derived distros.

This would also allow users to use any Window Manager he/she likes while having the benefit of using pcmanfm-qt.

**Comment by tsujan** [comment]
pcmanfm-qt doesn't depends on a specific icon set. Of course, you need to install a set that has common icons, but that's not limited to pcmanfm-qt.

A icon set as complete as Oxygen or Breeze is recommended by LXQt in general.

**Comment by tsujan** [comment]
>  faced the problem of no icons showing in the application

If you'd already installed a minimal icon set, then your problem should have been the lack of a Qt platform plugin. If you're outside LXQt or KDE,  you could use `qt5ct` for Qt5 apps or `qt6ct` for Qt6 apps. LXQt and KDE have their own plugins.

Oxygen and Breeze have extra dependencies, which may have provided you with a plugin, but there are good icon sets without those dependencies.

**Comment by isf63** [comment]
Some GUI programs on Arch Linux have a dependency on "ttf-font" which isn't a real package but is provided by various ttf-* packages. (`Provides        : ttf-font`). If there was something like that for icons, a dependency for it could work possibly. But I'm pretty Arch doesn't provide that for icon sets.
