### ISSUE TITLE
Programs launched from pcmanfm-qt have extra XCURSOR_SIZE and XCURSOR_THEME environment vars

### ISSUE THREAD

**Issue by jinliu** [lxqt/pcmanfm-qt#1840]
When I open a terminal (kitty) or a video file (with VLC) from pcmanfm-qt, these programs have XCURSOR_SIZE and XCURSOR_THEME set in their environment. Under Wayland and HiDPI, this makes the cursor very small in VLC. Those vars are not present in pcmanfm-qt's environment, so looks like they are added when launching programs.

##### Expected Behavior
Don't add XCURSOR_* environment vars when launching programs.

##### Steps to Reproduce (for bugs)
1. Launch pcmanfm-qt.
2. Launch htop. Press 'e' on the pcmanfm-qt line to show its environment. Verify that no XCURSOR_* here.
3. In pcmanfm-qt, "Open in terminal".
4. In terminal, "env|grep XCURSOR". XCURSOR_SIZE and XCURSOR_THEME are set.

##### System Information
* PcManFm-qt version: 1.4.0
* Distribution & Version: archlinux
* Qt Version: 5.15.11
* liblxqt Version: 1.4.0

DE: KDE Plasma 6.0beta1, Wayland

**Comment by tsujan** [comment]
Not reproducible under LabWC (Wayland).

Neither pcmanfm-qt nor libfm-qt sets those EVs. The cause should be somewhere else.

**Comment by jinliu** [comment]
I printed the content of `environ` global variable in `Application::openFolderInTerminal`. It has these vars. But /proc/*/environ hasn't. So it seems that something inserted the two vars into the `environ` global variable after pcmanfm-qt starts, probably during its initialization. Any idea what could that be?

**Comment by tsujan** [comment]
> Any idea what could that be?

No, but since it doesn't happen in LabWC, it may be related to KDE.

**Comment by jinliu** [comment]
You are right. Found out that it's added by KDE's QT5 platformtheme plugin.
