### ISSUE TITLE
"Valid key file could not be found in search dirs" when trying to "Open With..." Neovim wrapper

### ISSUE THREAD

**Issue by javier-fuentes** [lxqt/pcmanfm-qt#1841]
Not a big issue but when trying to open a text file in pcmanfm-qt using the contextual option "Open with..." I get this error **Valid key file could not be found in search dirs**

##### Expected Behavior
Open text file with Neovim in terminal emulator

##### Current Behavior
Pop up: "Valid key file could not be found in search dirs"
Console: `GLib-CRITICAL **: unquote_string_inplace: assertion 'err == NULL || *err == NULL' failed`

##### Steps to Reproduce (for bugs)

1. `pcmanfm-qt`
2. Right click on a text file for contextual menu > "Open With..." > Neovim wrapper

##### Context
It worked until last system upgrade, now it fails with two different terminal emulators at least (alacritty and foot)

##### System Information

* PcManFm-qt version: 1.4.0
* Distribution & Version: Nixos 23.11 with Sway 1.8.1
* Qt Version: 6.6.1
* liblxqt Version: Not listed as a dependency using...
`nix-store --query --references $(which pcmanfm-qt)`

**Comment by tsujan** [comment]
Not reproducible.

That error message doesn't exist in libfm-qt or pcmanfm-qt.
