### ISSUE TITLE
[Feature request] Add blank space when in "Detailed List" view mode.

### ISSUE THREAD

**Issue by userse31** [lxqt/pcmanfm-qt#1845]
You know how in Windows Explorer there is "blank space" on the right side of the file view?

Can that be added to PCManFM? When the file view is long enough there is no "blank space" where you can right click on "not a file" and do stuff like create directories. You can only right click on files. You have to use the menu bar to create new folders and files.

Not a big deal, but it would be nice to see this addressed!

**Comment by tsujan** [comment]
> where you can right click

Preferences → Behavior → Show folder context menu with Ctrl + right click

Or if you insist on having a blank space: List view header → unckeck auto-resize.
