### ISSUE TITLE
An idea to simplify item margins on the desktop

### ISSUE THREAD

**Issue by isf63** [lxqt/pcmanfm-qt#1854]
Currently there are two settings for desktop item margins on the desktop:
1) **Minimum item margins** - Effectively when multiplied by two, this is the minimum (and also maximum) spacing between two adjacent desktop items. (Set for X/Y independently)
2) **Margins of work area** - This is space reserved at each end of the desktop where desktop items are not allowed into.

![pref](https://github.com/lxqt/pcmanfm-qt/assets/121320947/813d48a5-ff08-49a4-ba1d-4774d8244f2a)

----

These settings can be simplified with the basic idea being to make the spacing as "even as possible, automatically". Here is a picture as it's difficult to describe in words (Only for X, same goes for Y):

![pict](https://github.com/lxqt/pcmanfm-qt/assets/121320947/a6a4baf6-2276-4a8f-916a-050292a033c6)

**Comment by tsujan** [comment]
Item margins and margins of the work area are very different concepts and have two different functionalities. The latter is useful when additional "things" are put on Desktop — like Conky,, or when a panel is used which doesn't reserve space but auto-hides on overlapping, etc.

Vertical Item margins are calculated in `DesktopWindow::removeBottomGap` with care. That method has worked as expected for a very long time and shouldn't be changed. The horizontal item margin doesn't need an extra treatment.

So, frankly, I have no clue what you're talking about.

**Comment by tsujan** [comment]
Please use https://github.com/lxqt/lxqt/discussions for ideas. Closing this only because here is the bug tracker, not because I'm against any idea...
