### ISSUE TITLE
[Feature request] Persisting selection after traversing directory

### ISSUE THREAD

**Issue by avidseeker** [lxqt/pcmanfm-qt#1861]
After entering a directory and exiting out of it, pcmanfm reset back the selection to the first file in the original directory.

For example, say you selected *Downloads* directory, entered it, then exited out of it (`Enter, Alt+Up`).
```
Desktop
Documents
Downloads <--
Music
Pictures
Public
```
Now pcmanfm assumes previous selection is `Desktop` (try hitting `ArrowDown`). It should still assume selection is `Downloads`. This is how many file managers do it (Dolphin, Nautilus, even Windows File Explorer). Which makes it easier to check the contents of directories one by one (with `Enter, Alt+Up, Down` combos).

**Comment by avidseeker** [comment]
Demonstration gif:
![](http://i.imgur.com/Qa7can8.gif)

**Comment by tsujan** [comment]
That was implemented many years ago. Either you have a VERY old version, or something's wrong with your installation.

Actually, it was me who proposed a patch to Dolphin's devs for implementing it there too. They made their own patch after a year or so.

**Comment by avidseeker** [comment]
I installed pcmanfm on Fedora and double checked with `pcmanfm-gtk3` on Arch.

```
Name            : pcmanfm-gtk3
Version         : 1.3.2-1
```

https://koji.fedoraproject.org/koji/buildinfo?buildID=2293195

**Comment by avidseeker** [comment]
Sorry about the misunderstanding.

**Comment by tsujan** [comment]
It's OK.

pcmanfm is based on GTK and isn't developed by LXQt — actually, it doesn't seem to be developed (actively).

pcmanfm-qt started as a rewrite of pcmanfm in Qt many years ago, but soon, it found its own path and direction. It's a completely different app and is being developed actively.
