### ISSUE TITLE
[Feature request] better thumbnail management

### ISSUE THREAD

**Issue by Rabcor** [lxqt/pcmanfm-qt#1862]
**Is your feature request related to a problem? Please describe.**

Thumbnails often seem to be generated slowly and inconsistently, for instance I frequently run into an issue where i scroll through a folder, and there are like a good  9 images with thumbs below and above a set of 6 that have no thumbs.

Going further with the same example, to generate those missing thumbs i have to let the file manager sit there looking at those specific images for a while (like a minute) before they all pop in at once, whereas, ideally, they shuold just be instantly start generating and showing up when I am looking at them (notably qimgv folder view had the behavior i am expecting here, sure the thumbnail generation speed was the same, but it handled them FAR better; so it actually felt like it was much faster)

On top of all that, pcmanfm-qt seems quite bad at remembering thumbnails as well, everytime I re-enter a folder that has images with generated thumbnails it needs to reload the thumbnails. I understand that in theory this should be done to save on ram, but in practice... no ram is saved and we just get shit performance on thumbnails for seemingly nor reason. (Meanwhile, using qimgv folder view as an example again, even between restarts of the application the thumbnails load practically instantly after they've been generated the first time, and it uses considerably less ram to do it too; screenshot shows example, exact same folder open, all the thumbnails loaded, pcmanfm ram use is double that of qimgv)

![image](https://github.com/lxqt/pcmanfm-qt/assets/5684325/c3c0eeb8-9240-40f6-bceb-fda223d72a62)

**Describe the solution you'd like**

Thumbnails should be generated with a couple rows buffer above and below the currently visible zone of the folder, and thumbnails for the visible zone should be **instantly** prioritized for thumb generation always, and should also be instantly loaded as soon as it is generated.

An option to not unload the thumbs from pcmanfm's memory (especially considering it doesn't even free up any ram, just shits over it's performance instead) so after they are loaded first time around, they aren't unloaded until pcmanfm is fully closed.

An option to fully generate thumbs for any folder you are currently in, even if you haven't looked at the files in question, and an option to similarly fully load all the thumbs while a folder is open without having to look directly at the files.

Existing thumbnails should be loaded faster than they are, if other file managers and indeed image viewers can do it, surely pcmanfm-qt can too.

##### Context

I have a folder with many images, thousands, it's incredibly annoying to have to look at generic image icons instead of thumbnails. I never had an issue with this in dolphin, and indeed not in thunar either, it's been a bit since i used dolphin, but thunar seems to just straight up instantly load any already generated thumbnail when i open a folder (the problem with thunar, and reason why i'm now using pcmanfm instead, is that thunar also straight up crashes half the time i open folders with that many files; ram use is in a similar ballpark as pcmanfm-qt as well, tho i bet dolphin uses more ram), thunar behaves about how i expected pcmanfm-qt to.

**Comment by tsujan** [comment]
Thumbnails are generated only if needed; otherwise, they're written to and found in `~/.cache/thumbnails`. There is no memory leak either.

If you have a better code that can create or find thumbnails faster, please make a PR. Otherwise, this report seems to be only about your feelings (using the word "shits" twice is a sign of that).

**Comment by Rabcor** [comment]
> Thumbnails are generated only if needed; otherwise, they're written to and found in `~/.cache/thumbnails`. There is no memory leak either.
> 
> If you have a better code that can create or find thumbnails faster, please make a PR. Otherwise, this report seems to be only about your feelings (using the word "shit" twice is a sign of that).

It also forgets thumbnails between restarts.... well i made a separate issue for that.

Anyhow wow, what a reaction, sounds like you took particular offense to the way i speak and closed it because of that huh? Well yeah, as a matter of fact, i am annoyed by shit performance, so i call it what it is.

You're just gonna ignore the entire thing because of that? pcmanfm will never have good thumbnail maangement, not planned because i said a bad word huh?

Very cool.

**Comment by tsujan** [comment]
> what a reaction....

Your long-winded comment was as good as "I want faster thumbnails". The answer is, this is the best way we know of with GLib; if you know of a beter way, make a PR.

Whether another file manager shows thumbnails instantly but "crashes half the time" or "uses more RAM"… is irrelevant.

**Comment by Rabcor** [comment]
> > what a reaction....
> 
> Your long-winded comment was as good as "I want faster thumbnails". The answer is, this is the best way we know of with GLib; if you know of a beter way, make a PR.
> 
> Whether another file manager shows thumbnails instantly but "crashes half the time" or "uses more RAM"… is irrelevant.

Well yes, i want faster thumbnails, hence feature request. I pointed at other software that does it faster so that you'd have something to go on if what you're already doing is the fastest you know of, i'm not really much of a programmer myself, I dabble, I code, but i've never actually worked on a proper program like this; but even if I was, pcmanfm-qt is not my software, I only just started using it and honestly if it's not good enough for me I'd probably just be better off finding another file manager that suits me better or fixing those crashes in thunar since that seems it might be easier (thunar already has all the functionality, it just crashes, i'm probably gonna report that issue to them as well.)

If I was you'd be getting a commit to go with this, not just a feature request. Although I'm sure there are higher quality feature requests on the regular this is the best I could do. Qimgv seemed like an extremely good hint towards a better way of doing this, considering it is a really small and lightweight software and also happens to use Qt.

And although I can't find the pcmanfm-qt code for thumbnail management, the one in qimgv was quite easy to find.

https://github.com/easymodo/qimgv/blob/master/qimgv/components/thumbnailer/thumbnailer.cpp

At a glance I would guess it might be the multithreading and asynchronous thumbnail loading and generation that's giving it such a massive edge over pcmanfm-qt, since I cannot imagine pcmanfm-qt does that considering how slow going this all is on it.

**Comment by tsujan** [comment]
I usually don't have time to explain codes in English but make an exception this time. 

In a separate thread, libfm-qt

 1. Gets the (encoded) thumbnail name based on the image URI and requested size;
 2. Tries to load it from the standard thumbnails directory as `QImage`;
 3. Generates an appropriate thumbnail ("appropriate" means several things) and puts it in the standard dir **only if** it doesn't exist, is corrupted, or its `Thumb::MTime` key is outdated; and
 4. Shows it.

How fast the whole procedure is done depends on many factors, like the number of files, SSD vs. HDD. CPU, I/O, RAM, kernel's memory management,….

When a thumbnail is found, the system (not the app) will "remember" it, depending on many factors and up to some point. Rebooting makes the system "forget" about everything.

If you've found a real bug, you're welcome to report it. Saying that it isn't fast enough for you is neither a bug report nor a feature request. The main code is in https://github.com/lxqt/libfm-qt/blob/master/src/core/thumbnailjob.cpp.

Some apps may skip this or that stage — like checking `mtime`, or creating appropriate thumbnails. Some others may pretend that they've found thumbnails instantaneously while actually doing heavy jobs which may interfere with other jobs (like scrolling) or even cause crashes; etc.

**Comment by Rabcor** [comment]
> I usually don't have time to explain codes in English but make an exception this time.
> 
> In a separate thread, libfm-qt
> 
> 1. Gets the (encoded) thumbnail name based on the image URI and requested size;
> 2. Tries to load it from the standard thumbnails directory as `QImage`;
> 3. Generates an appropriate thumbnail ("appropriate" means several things) and puts it in the standard dir **only if** it doesn't exist, is corrupted, or its `Thumb::MTime` key is outdated; and
> 4. Shows it.
> 
> How fast the whole procedure is done depends on many factors, like the number of files, SSD vs. HDD. CPU, I/O, RAM, kernel's memory management,….
> 
> When a thumbnail is found, the system (not the app) will "remember" it, depending on many factors and up to some point. Rebooting makes the system "forget" about everything.
> 
> If you've found a real bug, you're welcome to report it. Saying that it isn't fast enough for you is neither a bug report nor a feature request. The main code is in https://github.com/lxqt/libfm-qt/blob/master/src/core/thumbnailjob.cpp.
> 
> Some apps may skip this or that stage — like checking `mtime`, or creating appropriate thumbnails. Some others may pretend that they've found thumbnails instantaneously while actually doing heavy jobs which may interfere with other jobs (like scrolling) or even cause crashes; etc.

Sorry it's taken me so long to respond to this, thanks for explaining this to me, I'm probably going to look and see if i can do anything to improve this myself later, thank you for pointing out the relevant code for me.
