### ISSUE TITLE
forgets thumbnails between restarts

### ISSUE THREAD

**Issue by Rabcor** [lxqt/pcmanfm-qt#1863]
##### Expected Behavior

Remember thumbnails and not generate new ones after restart

##### Current Behavior

Remembers only some thumbnails after restarts (if i restart, and then enter a folder that i had fully generated thumbnails for, it seems to remember about half of them and re-generate the rest)

##### Steps to Reproduce (for bugs)

1. Enter a folder with many images (say 1000)
2. Generate all thumbnails
3. Restart PC (I think a full system restart is required, possibly even cold bootmwhich is where i encountered the issue)
4. Enter folder again, see how many thumbnails it remembered and how many it re-generates

##### Context

Wastes resources, there's unnecessary cpu usage at least, if not disk space and ram also...

Also it gives the impression of bad performance in pcmanfm-qt.

##### System Information

* PcManFm-qt version: 1.4.0
* Distribution & Version: EndeavourOS 6.6.16-lts
* Qt Version: 5 and 6 installed, unsure which pcmanfm is using
* liblxqt Version: None

**Comment by tsujan** [comment]
pcmanfm-qt (actually, libfm-qt) does not — and should not — remember any thumbnail. Thumbnails are generated once by any app that may generate them first and put in `~/.cache/thumbnails`. Then they're found and used by any app that may need them, including pcmanfm-qt.

**Comment by Rabcor** [comment]
> pcmanfm-qt (actually, libfm-qt) does not — and should not — remember any thumbnail. Thumbnails are generated once by any app that may generate them first and put in `~/.cache/thumbnails`. Then they're found and used by any app that may need them, including pcmanfm-qt.

I think you're misunderstanding maybe, what I mean is that the already generated thumbnails in ~/.cache/thumbnails are forgotten by pcmanfm-qt after I reboot.

Of course this might be some kind of misunderstanding if there's some limit for how many thumbnails can be in ~/.cache/thumbnails and they just get automatically deleted or something, but as far as I know there isn't.
