### ISSUE TITLE
Arguments not saved for terminal, plus more.

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/pcmanfm-qt#1870]
##### Expected Behavior

Command line set in Preferences/Advanced/Terminal emulator is saved and executed as is

##### Current Behavior

Arguments are dropped when saving preferences, only works if edited directly in config file.

##### Possible Solution

First, split "Terminal emulator"  option into command line and execution argument (`-e` for xterm). Always use command line as is, add execution argument (if not empty) when executing something in terminal.

Consider supporting [proposed](https://gitlab.freedesktop.org/terminal-wg/specifications/-/merge_requests/3#note_2193993) [xdg-terminal-exec](https://github.com/Vladimir-csp/xdg-terminal-exec) spec.

##### Steps to Reproduce (for bugs)

1. Add arguments to Preferences/Advanced/Terminal emulator command
2. Save preferences
3. Open Preferences/Advanced/ again

##### Context

I want to use `uwsm-app -T` or `uwsm-app -t scope -T` command as terminal emulator. Have to edit pcmanfm-qt config file for it to work.

##### System Information

* PcManFm-qt version: 1.4.0
* Distribution & Version: Debian Sid
* Qt Version: 5.15.10
* liblxqt Version: 1.4.0

**Comment by stefonarch** [comment]
Did you use a custom list? Just type in the dropdown?
https://github.com/lxqt/pcmanfm-qt/pull/1810

**Comment by tsujan** [comment]
Yes, the GUI/code has been kept minimal but effective.

**Comment by Vladimir-csp** [comment]
Wow, that is pretty obscure. And it opens a text file with no comments as to what parameters can be used.
Had to look in libfm-qt `terminal.cpp` and tried to add `custom_args=-T`, but it does not seem to be working, argument is not passed.

**Comment by tsujan** [comment]
Only `open_arg` may be relevant is special cases, and it is saved; there's no `%s` or `custom_args` or.... (see https://github.com/lxqt/pcmanfm-qt/pull/1810#issue-1899755791). So, the GUI doesn't add anything obscure, although the user can.

**Comment by Vladimir-csp** [comment]
It's disabled. So, no way to add an argument?
```
#if 0 // FIXME: what's this?
    if(custom_args) {
        cmd = g_strdup_printf("%s %s", cmd, custom_args);
        g_free(_cmd);
        _cmd = (char*)cmd;
    }
```

**Comment by Vladimir-csp** [comment]
If I follow the GUI, the argument goes to `open_arg`. I'll file a bug to libfm-qt then.

**Comment by stefonarch** [comment]
`~/bin/myterminal`:

```
#!/bin/bash
#
qterminal -p qterm.small
```
`terminals.list`
```

[myterminal]
open_arg=
```

**Comment by Vladimir-csp** [comment]
Yes, I thought about it. I would do it with `sh`, `exec` and `$@` though. And in case of `uwsm-app` specifically, probably by adding `$0` processing to it. Maybe I will do just that. But still, specifying arguments to terminal should be trivial imho.
