### ISSUE TITLE
Only seven tabs can be remembered after rebooting the computer

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1873]
**Steps to reproduce**
open 8 different tabs, so tab-titles are different
close PCManFM-Qt
reboot the computer
open PCManFM-Qt

**Result**
there are only 7 tabs

**Expectation**
there should be still 8 tabs

**System**
Lubuntu 23.10
PCManFM-Qt 1.3.0

if this issue does not exist in PCManFM-Qt 1.4.1, then I'm sorry for this report

**Comment by tsujan** [comment]
Not reproducible.

**Comment by ralf3u** [comment]
I don't know what happened, but today, after restarting the computer, there were eight tabs.
