### ISSUE TITLE
Cursor is moved away from the renamed item

### ISSUE THREAD

**Issue by andrei-korshikov** [lxqt/pcmanfm-qt#1874]
##### Expected Behavior

- cursor (selection) should stay on the same item after renaming
- renamed item should be selected, not just underlined

##### Current Behavior

- selection is cleared (blue rectangle is replaced with blue line)
- this blue line is appeared under the previous item, not under the edited item

##### Steps to Reproduce

1. There are three folders, and I'm going to rename the third one: 
![image](https://github.com/lxqt/pcmanfm-qt/assets/15959858/e42bae6b-ece6-41c7-a1dc-35463efad2fd)
2. Now, you see that selection is moved away from "New folder 3 edited", and "New folder 2" is underlined: 
![image](https://github.com/lxqt/pcmanfm-qt/assets/15959858/3225b9e3-95a0-47d4-bdcf-d3175910bac5)

##### Context

I am trying to rename a folder, and then go into this folder. In the example above the order of folders is not changed, so I have to press "down" (would like to get rid of it), and then "Enter" to go into "New folder 3 edited".

If the item to be renamed is the only item, after renaming it is underlined, but not selected. So, I have to press "Control-Space" to select it (would like to get rid of this step), and then "Enter" to go into.

If the order of items is changed after renaming, I have to use transient filter-bar to find renamed item (basically, type the same characters twice - at first while renaming, and at second while searching).

##### System Information

* PcManFm-qt version: 1.4.1
* Distribution & Version: Arch Linux, KDE
* Qt Version: qt5-base 5.15.12+kde+r151-1
* liblxqt Version: ---

**Comment by tsujan** [comment]
Preferences → Behavior → Select newly created files

**Comment by andrei-korshikov** [comment]
Thank you! I have overlooked tooltip ("Renamed files will also be selected") for this option, it was my fault.

Maybe it would be better for newcomers if this option has name like "Select newly created and renamed files".
