### ISSUE TITLE
Tab that is in focus is not remembered after a restart of PCManFM-Qt

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1875]
**Steps to reproduce**
open many tabs
put the second tab in focus
close the PCManFM-Qt
restart PCManFM-Qt

**Result**
the last tab (on the right side) is in focus, but not the second tab

**Expectation**
the second tab should be in focus

**Remark**
the issue does not in exist in the file-manager Dolphin 23.08.1

**System**
Lubuntu 23.10
PCManFM-Qt 1.3.0

if this issue does not exist in PCManFM-Qt 1.4.1, then I'm sorry for this report

**Comment by tsujan** [comment]
There's no issue. pcmanfm-qt isn't supposed to remember anything other than the last window tabs. If you want a tab to remain active after reopening, drag and drop it to the first place.

**Comment by ralf3u** [comment]
>[...] closed [..] as not planned

That's a pity, because I like this feature.

**Comment by tsujan** [comment]
The behavior is completely self-consistent, considering the option "Switch to newly opened tab".

**Comment by ralf3u** [comment]
>The behavior is completely self-consistent, considering the option "Switch to newly opened tab".

I use "Switch to newly opened tab". I expect from this option that it works only as long as the file-manager is open.

After a restart of the file manager I expect of course that I get the same order of tabs and that the same tab is in focus, without the need to move around a tab before closing the file manager.  I would call this behavior an intuitive behavior.

I don't want to be educated by a program, that I have to change my behavior in that way, that I have always to place the visible tab at the end of the tabs before closing the file manager, so that the tab will be right away in focus after a restart.

It is at the moment the most important feature that I miss in PCManFM-Qt.

**Comment by tsujan** [comment]
> it works only as long as the file-manager is open.

?!  The file manager should be open to show tabs, and the last tab is always the newest tab.
