### ISSUE TITLE
[Feature request] Allow static text on window title

### ISSUE THREAD

**Issue by developer1105** [lxqt/pcmanfm-qt#1877]
In QTerminal, following the menu ```File|Preferences...|Appearance```, there is the option ```Change window title based on current terminal```.

When the option is on, the current directory appears on window title, otherwise, only the string ```QTerminal``` appears. I would like to see something similar on PcManFm-qt. 

With, maybe the bonus of letting the user choose any string he would like to set, like "File Manager", "My Data", or whatever.

**Comment by tsujan** [comment]
The window title is the name of the current folder.

As mentioned several times in various places, LXQt avoids useless config options.
