### ISSUE TITLE
[Feature request] Permit to organize the actions in submenus

### ISSUE THREAD

**Issue by cfgnunes** [lxqt/pcmanfm-qt#1886]
**Is your feature request related to a problem? Please describe.**
Currently, in PCManFM-Qt file manager, all installed actions/scripts are displayed at the same level, making it difficult to manage and navigate through many scripts. This lack of organization can lead to cluttered menus and difficulties in finding specific actions/scripts.

**Describe the solution you'd like**
I would like PCManFM-Qt to permit organizing the installed actions/scripts into submenus, similar to the functionality found in other file managers such as Nautilus, Caja, Thunar, and Dolphin. This would involve allowing users to create subdirectories/submenus where they can organize their scripts. These submenus should be reflected in the context menu of PCManFM-Qt, providing users with a more organized and intuitive way to access their scripts.

**Describe eventual alternatives you've considered**
One alternative solution would be to continue using the current flat structure for organizing actions/scripts. However, this approach becomes impractical when dealing with many scripts, as it leads to cluttered menus and difficulties in finding specific actions. Another alternative would be to manually edit the context menu configuration files to create custom submenus, but this would be cumbersome and error-prone for users.

##### Context
Organizing actions/scripts into submenus would greatly improve the usability and user experience of PCManFM-Qt, especially for users who rely heavily on custom scripts for file management tasks. This feature would make it easier to navigate through and access many scripts, ultimately enhancing productivity and efficiency when using the file manager.

An example of use is the project:
https://github.com/cfgnunes/nautilus-scripts

![screenshot](https://raw.githubusercontent.com/cfgnunes/nautilus-scripts/main/.assets/screenshot.png)

**Comment by tsujan** [comment]
Please read the [Wiki](https://github.com/lxqt/pcmanfm-qt/wiki/custom_actions), especially [Menu Definition]( https://github.com/lxqt/pcmanfm-qt/wiki/custom_actions#menu-definition) and [Order of Actions](https://github.com/lxqt/pcmanfm-qt/wiki/custom_actions#order-of-actions).
