### ISSUE TITLE
Pcmanfm-qt is invisble. lxqt plus i3 minus i3-bar

### ISSUE THREAD

**Issue by franzmondlichtmann** [lxqt/pcmanfm-qt#1890]
##### Expected Behavior

Pcmanfm-qt should be present.

##### Current Behavior

pcmanfm-qt is an invisible window upon startup of lxqt with i3 set as a window manager and i3-bar section removed from the i3-config file, otherwise nearly default i3-config file(because lxqt comes with its own bar)

##### Possible Solution

kill pcmanfm-qt and reopen pcmanfm-qt "makes" the program visible

##### Steps to Reproduce (for bugs)

will try later to reproduce the bug

##### Context

Upon startup of lxqt it looks like this, when I open another or multiple windows.
![image](https://github.com/lxqt/pcmanfm-qt/assets/105480088/2e0c27ff-59e3-4e4e-af02-2573e3af68c5)
![image](https://github.com/lxqt/pcmanfm-qt/assets/105480088/ae752880-4a65-4406-92d9-34bedac013a7)
![image](https://github.com/lxqt/pcmanfm-qt/assets/105480088/b4d9c451-43bb-4e20-b29d-fc98cca88d08)

##### System Information

* PcManFm-qt version: 1.4.1
* Distribution & Version: Arch Linux Rolling Newest Update
* Qt Version: 6.6.3-1
* liblxqt Version: 1.4.0-1
* Using with Nvidia 4060 Mobile and switchable gpu (:Intel i7)
But with X11, no other glitches.

**Comment by tsujan** [comment]
I really doubt that pcmanfm-qt can be responsible for what you see because it's a just a Qt app and doesn't determine how its window is drawn. The problem can be in the WM. However,

 1. Do you see a crash in pcmanfm-qt? If yes, please attach its backtrace. If not,
 2. Is there a freeze, or a hang? High CPU usage?

**Comment by franzmondlichtmann** [comment]
1. I see no crash, pcmanfm-qt is running, occasionally using a tiny bit cpu power
2. It does not freeze and not crash.
- pcmanfm-qt is running in --desktop mode, while in its invisible form. Meanwhile it's possible to open new instances of pcmanfm-qt gui.

**Comment by franzmondlichtmann** [comment]
Now I deactivated the desktop checkbox in sessions settings. This removes the problem entirely.

**Comment by tsujan** [comment]
> It does not freeze and not crash... Meanwhile it's possible to open new instances of pcmanfm-qt gui.

Good. Then we can be sure that there's no problem in pcmanfm-qt, although that's not a surprise theoretically.

This can show a problem in i3. Perhaps  i3 tries to tile the desktop!?

> Maybe a desktop is not needed with i3?

You could disable the desktop module anywhere.

**Comment by stefonarch** [comment]
I think tiling WM do not use a classical desktop, I never used i3  with LXQt but sway  yes, there it works when no app is open.

**Comment by tsujan** [comment]
It's different on Wayland because layer shell is used there.
