### ISSUE TITLE
Strange file type selection

### ISSUE THREAD

**Issue by Fabioamd87** [lxqt/pcmanfm-qt#1898]
Hello,
When I try to save an Image with Firefox on Lubuntu 24.04 I get a strange file type selection field (see attachment)

##### Expected Behavior

- JPEG image (.jpeg)
- all files (*)

##### Current Behavior
- JPEG Image (*.[jJ][pP][gG] *.[jJ][pP][eE][gG] *.[jJ][pP][eE] *.[jJ][fF][iI][fF] ........................
- all files (*)

##### Possible Solution
change the string to what present in expected behaviour

##### Steps to Reproduce (for bugs)

1. right click on an image
2. save as

##### System Information

* PcManFm-qt version: 1.4.1
* Distribution & Version: Lubuntu 24.04
* Qt Version: 5.15.13
* liblxqt Version: 1.4.0

Thank you!
![pcmanfm filename](https://github.com/lxqt/pcmanfm-qt/assets/284733/58825cae-f0d5-4646-b82d-8c42b5c2d047)

![Uploading pcmanfm filename.png…]()

**Comment by tsujan** [comment]
They are valid, although not added by us. → https://github.com/lxqt/libfm-qt/issues/879

**Comment by Fabioamd87** [comment]
thanks, I didn't understand if it's an issue or not, but I see there is a fix.

**Comment by tsujan** [comment]
> but I see there is a fix.

The fix should already be in 1.4.1. So, if you have encountered a real problem, please describe the steps to reproduce it; if we can reproduce it with the latest stable LXQt (2.0.0), we'll reopen this report (what you added under `Steps to Reproduce (for bugs)` didn't cause any problem here).
