### ISSUE TITLE
Sorting issue on file started with Numeric

### ISSUE THREAD

**Issue by tugoese** [lxqt/pcmanfm-qt#1899]
##### Expected Behavior
Sort sequentially

##### Current Behavior
Not using natural sorting, which considers the numeric value rather than sorting numbers lexicographically.

##### Possible Solution
Adjusting `LC_COLLATE=C` environment variable

##### Steps to Reproduce (for bugs)
![image](https://github.com/lxqt/pcmanfm-qt/assets/145205607/e6fe5ccd-1f70-4182-9ec3-f271d72b19d8)

##### Context
Organizing especially when there's lot of files, which kinda annoying

##### System Information
* PcManFm-qt version: 1.4.1-1
* Distribution & Version: Arch Linux 6.8.8-zen1-1-zen
* Qt Version: qt6-base 6.7.0-3
* liblxqt Version: 1.4.0-1

**Comment by tsujan** [comment]
Not reproducible:

![sorting](https://github.com/lxqt/pcmanfm-qt/assets/981076/87cce1f9-b599-4a47-8070-4d999d442e34)
