### ISSUE TITLE
[Feature request] filter bar tweak

### ISSUE THREAD

**Issue by 3hg4hj** [lxqt/pcmanfm-qt#1901]
when focused on the filter bar, enter should return you to the current active pane (esc wipes the filtering criteria and tab key shuffling is awkward). it would also be nice to be able to rebind it, i use filtering far more often than search

**Comment by tsujan** [comment]
Filter-bar isn't a search bar. `Enter` has nothing to do with it.

Either use a transient filter-bar (which is the default and is made to keep the focus on the main view), or use backtab.

> i use filtering far more often than search

More reason to use a transient filter-bar.

**Comment by 3hg4hj** [comment]
i guess backtab works but then i'm suggesting that enter should double as backtab which would be more intuitive (pcmanfm-qt is already the only viable keyboard-driven file manager)

**Comment by tsujan** [comment]
With a search bar, `Enter/Return` starts the search. With a file-bar, filtering is started as soon as the user types in it. I wouldn't call `Enter` in a filter-bar more intuitive but perhaps confusing.

**Comment by 3hg4hj** [comment]
in both cases it would be accessing the results of your query lol

**Comment by tsujan** [comment]
`Enter/Return` is responsible for *activating* something, while Tab/Backtab is for changing the focus.

> pcmanfm-qt is already the only viable keyboard-driven file manager

And, as mentioned above, the transient filter-bar is made for that.
