### ISSUE TITLE
Option to change drag-and-drop actions to "move" only

### ISSUE THREAD

**Issue by antipodes5** [lxqt/pcmanfm-qt#1906]
**Is your feature request related to a problem? Please describe.**
I really want to be able to quickly and simply drag a file into a folder as a "move" action. Only that.

The current menu is a real pain. It slows me down and interrupts workflow/focus.

**Describe the solution you'd like**
A configuration option for drag-and-drop behavior in Settings that allows me to specify default action.

**Describe eventual alternatives you've considered**
I know there are ctl+X and ctl+V but that involves mixing it up between keyboard and mouse, which is a really inefficient user action. 

This is mouse-based only interaction. If I want to copy - not often - there is right click menu or ctl+C.

At this point, I think I am going to look to other file manager systems that don't have this *unmodifiable* feature.

##### Context

Just manage my files and folders. 

~90+% of the time, I just want to *move* things, not copy them. I want to do that with multiple files and this menu is just a killer - a speed bump on the way to getting the job done.

Just like the physical origin of the drag-and-drop metaphor, if I drag something to a box and drop it in there, I expect to drop into the box. Job done. I don't expect for it to hover in mid-air and ask if I want that or a duplicate.

I think you should also consider that this behavior, as currently configured, is quite different to *all* the other file managers I have come across in other distros. I think its retrograde if it becomes a barrier to adoption of e.g. Lubuntu.

Its a shame, because PcManFm-qt is a nice snappy little thing otherwise. And I quite like Lubuntu.

EDIT: 24.04 LTS (Noble Numbat), LXQt Version: 1.4.0

**Comment by stefonarch** [comment]
>is quite different to all the other file managers

afaik it's in Dolphin the same and no setting to disable it too. To me an option sounds reasonable, although I really like this feature and miss it in other file managers.

**Comment by antipodes5** [comment]
I take your point. I just tried and discarded Krusader and it is the same (although I suspect you *can* configure everything on that fm if you know what you're doing).

I have switched to Thunar. (I can't get it to list in the start/applications menu, though. Frustrating.) 

I would prefer the native `pcmanfm-qt` with this modification.

**Comment by tsujan** [comment]
→ https://github.com/lxqt/pcmanfm-qt/issues/993

**Comment by antipodes5** [comment]
Meh. Left Lunbuntu.

**Comment by antipodes5** [comment]
>    LXQt has nothing to do with Lubuntu.

But yes it does. It uses it. Its right slap bang in the middle of it. It uses whatever uses pcmanfm-qt.

I found your response somewhat tyrannical. It reminds me of why I left Windows: here's what you're going to be using, learn to like it.

I read your response on #993. I think its awful and inadequate. 

In particular, I think an action so fundamental to a file manager - drag and drop - should be considered a core function of the application's behavior, and so its not the same as some of the other preferences you cited. Its much more important. Make it configurable. I'm not asking you to remove it.

The nice thing about Linux is you aren't locked in. So I left Lubuntu and whatever packages its decided to use, because of the packages its decided to use.

**Comment by tsujan** [comment]
> But yes it does. It uses it.

LXQt doesn't use Lubuntu; it's Lubuntu that uses LXQt. LXQt is agnostic toward distros.

> I found your response somewhat tyrannical.

Sorry, this is a bug tracker, not a democracy.

**Comment by antipodes5** [comment]
And based on that ^, I don't want to be involved in anything you're involved in.

I'm not continuing this discussion.
