### ISSUE TITLE
[Feature request] Option to disable archiver integration

### ISSUE THREAD

**Issue by Rabcor** [lxqt/pcmanfm-qt#1907]
It would be nice if the archiver integration had a 'none' option to disable it entirely (I just use custom actions for it anyway because I don't like the unpredictability of the 'extract here' function, so i use my own extraction script that doesn't rely on any archivers, just the common commandline tools those archivers tend to rely on instead.)

Or perhaps, if the selected archiver's binaries are not found, the option would not appear in context menus (since it'd be broken anyways).

**Comment by tsujan** [comment]
We don't add options for everything.

**Comment by Rabcor** [comment]
> We don't add options for everything.

Either i'm misunderstanding your reply or you're misunderstanding my request...


I?m not asking for support for another archiver, i'm asking for support for no archiver at all, or just detecting if the selected archiver is not installed and hiding the context menu options to extract based on those conditions being met...

**Comment by tsujan** [comment]
No misunderstanding. → https://github.com/lxqt/pcmanfm-qt/issues/993#issuecomment-520967397

**Comment by Rabcor** [comment]
> No misunderstanding. → [#993 (comment)](https://github.com/lxqt/pcmanfm-qt/issues/993#issuecomment-520967397)

Ok... so why does that mean hiding the 'extract here' button when the selected archiver is not installed on the host system should not be implemented? That isn't "unlimited customization" that is extremely basic and logical functionality to have.

It prevents you from having a pointless context menu item that doesn't even work if the app determines that it wouldn't work, and it's like i said, literally one simple if statement.

**Comment by tsujan** [comment]
First, it would hide the functionality from users who want it (= most users) but haven't installed an archive manager yet. Second, it's inefficient to search for apps each time a menu is shown.

**Comment by Rabcor** [comment]
> First, it would hide the functionality from users who want it (= most users) but haven't installed an archive manager yet. Second, it's inefficient to search for apps each time a menu is shown.

It wouldn't hide anything from anyone, the setting is right there in preferences, there aren't a lot of settings in the first place.

And you don't have to check everytime a menu is shown (and it wouldn't be inefficient, you're literally just checking if one file exists under /usr/bin/; but even if it was, you can literally just check it once on launch, and again if the archiver option is changed.
