### ISSUE TITLE
"Extract here" option won't show with .rar archives when the archiver integration is set to lxqt-archiver

### ISSUE THREAD

**Issue by glu8716** [lxqt/pcmanfm-qt#1909]
##### Expected Behavior

Right-clicking a `.rar` archive should show the "Extrac here" option.

##### Current Behavior

Right-clicking a `.rar` archive doesn't show the "Extrac here" option.

##### Steps to Reproduce (for bugs)

1. In the preferences set `lxqt-archiver` for the archiver integration;
2. Right click a `.rar` archive;
3. No "Extract here" option.

##### System Information

* PcManFm-qt version: 2.0.0
* Distribution & Version: Artix
* Qt Version: 6.7.0
* liblxqt Version: 2.0.0

**Comment by tsujan** [comment]
Confirmed. The reason is that the desktop entry of lxqt-archiver still uses the old strings for rar in its mimetype list, which is copied to the archive list of libfm-qt. I'll update them soon.

Thanks for reporting!

**Comment by tsujan** [comment]
Done.

In the meanwhile, you could add `application/vnd.rar` to `/usr/share/libfm-qt6/archivers.list` → `[lxqt-archiver]` → `mime_types` manually (please note that the strings should be semicolon separated) and restart pcmanfm-qt from Session Settings.
