### ISSUE TITLE
Having english and spanish installed can create issues

### ISSUE THREAD

**Issue by icf20** [lxqt/pcmanfm-qt#1916]
![image](https://github.com/lxqt/pcmanfm-qt/assets/17784575/ea3b3fdb-fce5-44bf-be8f-475bcd070cde)

##### Expected Behavior

/home/-user-/Desktop/ and /home/-user-/Escritorio need to land into the same folder

##### Current Behavior

while in english mode the desktop shortcut want to take me to spanish version of desktop
##### Steps to Reproduce (for bugs)

1. install english
2. install spanish
3. run english as display language with spanish locale formats
4.

##### System Information

* PcManFm-qt version:2
* Distribution & Version: arch
* Qt Version: 6
* liblxqt Version:2

**Comment by tsujan** [comment]
> /home/-user-/Desktop/ and /home/-user-/Escritorio need to land into the same folder

You set a folder as your desktop — e.g., through LXQt Session Settings → User Directories. It has nothing to do with Spanish or English.
