### ISSUE TITLE
Network page is no longer populated

### ISSUE THREAD

**Issue by StarTroop** [lxqt/pcmanfm-qt#1917]
##### Expected Behavior
The Network page (network:///) used to be populated by various shares on my network (e.g. samba, ssh).

##### Current Behavior
The page is no longer showing any results, but I can still manually connect to any of the same shares.

##### Context
It's been this way for a few weeks at least, possibly starting after updating to the latest release (2.0.0), but I can't be sure if updating another package was the cause of the issue.

##### System Information
PcManFm-qt version: 2.0.0-1
Distribution & Version: Arch Linux, official repo
libfm-qt version: 2.0.2-2
gvfs version: 1.54.0-3
Not sure what other dependencies may be relevant. If someone can tell me what other package relates to searching the network I can check that version too.

**Comment by tsujan** [comment]
We haven't changed anything regarding `network:///`. Most probably, that's a side effect of another upgrade, like `gvfs` or `smb`.

Does it work with another GLib-based file manager, like Thunar?

**Comment by stefonarch** [comment]
Here I never saw items listed  in `network:///` for a long time now, but not sure if I'm missing something, network setup isn't my thing.
I don't see any listing neither in nautilus  nor in thunar also. I think the problem lies in some other area, like `gvfs-smb`.

**Comment by stefonarch** [comment]
I remember visibility changed when changing `client max protocol`. 
https://bugzilla.gnome.org/show_bug.cgi?id=780958

**Comment by tsujan** [comment]
I found this page: https://gitlab.archlinux.org/archlinux/packaging/packages/gvfs/-/issues/3. It says `gvfs-dnssd` should be installed now.

Since pcmanfm-qt (actually, libfm-qt) shows what GVFS gives it, we can't do anything about this. Hence, closing. But please add comments if you find what has changed.

**Comment by StarTroop** [comment]
`gvfs-dnssd` is only for those needing its provided filesystem support, it doesn't help in my case (only need sftp, included in gvfs, and samba, for which I have the gvfs-smb plugin). I'm not getting anything showing up in the network page, even though sftp and samba still work manually.  
Still, it seems this isn't related to pcmanfm-qt (I also tried Thunar to no success) so I will try poking elsewhere.
I would appreciate if anyone not using Arch but on the same version of pcmanfm and gvfs could chime in whether or not they have the same issue. Thanks!

**Comment by tsujan** [comment]
What about `gvfs-wsdd`?

**Comment by stefonarch** [comment]
>What about gvfs-wsdd?

Not sure if it's needed. I managed now to show my shares enabling avahi-daemon (which is running also on the server):
`sudo systemctl start avahi-daemon.service `

**Comment by tsujan** [comment]
@stefonarch 
Thanks a lot for solving this mystery!

**Comment by StarTroop** [comment]
I already had avahi running and working before, and it running `avah-browse -a` showed it was still working. I don't know exactly how these file browsers search for network shares, but I don't believe avahi is necessary.
In any case, I returned to `gvfs-dnssd` and `gvfs-wssd`, installed them both and rebooted. After opening pcmanfm-qt I noticed the network page was working again, but there was a delay before the shares showed up again. The entries seemed to be cached though as they show up faster on subsequent logins.  
So my issue is solved now, whether or not anyone else needs both, just one, or neither of those packages probably depends on what kind of shares you have. I'm also looking into whether systemd-resolved was causing any interference. I have it configured as the arch wiki recommends to have it play nice with avahi, so if anyone still has further issues and systemd-resolved enabled I would recommend looking there.

**Comment by tsujan** [comment]
> So my issue is solved now

Good to know that. It should have been solved with all FMs that are based on GLib and use GVFS.

> The entries seemed to be cached though as they show up faster on subsequent logins.

That's what GLib does, independently of the FM that may use it.
