### ISSUE TITLE
[Feature request] Better titling of windows

### ISSUE THREAD

**Issue by Kommynct** [lxqt/pcmanfm-qt#1925]
**Is your feature request related to a problem? Please describe.**

Currently, as it stands, when using a class/title system on a window manager, if i set, for example:

windowrulev2 = float,class:(pcmanfm-qt),title:(File Properties)

and then create a folder named "File Properties", that folder will always activate the rule, same goes for Preferences, and many of the other important window titles.

**Describe the solution you'd like**

Simply add "— pcmanfm-qt" to the title on the main window, but not on preferences/file properties, and this issue would go away.

##### Context
It'd be useful simply because sometimes folders are named "preferences" and other such things, and that ends up matching my window rules.

This would also let me use workspace renamers such as sworkstyle and hyprland-autoname-workspaces to have different icons per folder, and for preferences/properties.

**Comment by stefonarch** [comment]
My idea is that it's not really our job to fix tiling WM issues.

**Comment by Kommynct** [comment]
Would you reject a pr? This is a completely harmless fix with no downsides and would bring uniformity to the app, furthermore a bunch of scripting things use window titles. I just see no reason to be against this change

**Comment by tsujan** [comment]
A mess can consist of several small, seemingly harmless, unrelated things. If we added workarounds for problems in other apps, our code would be a mess.

**Comment by Kommynct** [comment]
I would agree if this was not a simple change of how titles are written. This is code that will never be touched again, and adds uniformity with many other apps, Firefox, thunderbird, Element, Telegram, and many others use a title structure like this. I could even make it less burdensome by changing the preferences/find/etc windows to be the ones with — pcmanfm-qt, which would be an incredibly minor change.

**Comment by tsujan** [comment]
Sorry, I'm not only against adding codes for other apps (the main reason) but also adding an ugly ` - pcmanfm-qt`, which may create elided texts on taks-bars or other places. What some other apps may do isn't relevant.
