### ISSUE TITLE
[Feature request] Thumbnails size, in v2.0 limited to square ratio and range 64 to 256 -- BUG or translation issue?

### ISSUE THREAD

**Issue by artofit** [lxqt/pcmanfm-qt#1926]
**Is your feature request related to a problem? Please describe.**
v2.0.0
Edit>Preferences>Display
Thumbnails are of square ratio and range from 64 to 256 px

**Describe the solution you'd like**
have either:
A/ fix width(range [64-512]), but variable ratios, for instance:
A1/ img & videos: 16:9
A2/ rest, aka  documents:  A4 ratio() 

B/ fix ratio for all thumbs, but variable size

Thanks, waiting for Wayland support release to test it all, but already very good job.

P.S. Tried v2.0.0 under Manjaro XFCE 24.0.4, except if there is error in translation(French) **there is a mix up between thumbnails and big icons behaviour**, didn't report a separe bug.

**Comment by tsujan** [comment]
Aspect ratios of thumbnails depend on thumbnailers, but thumbnails replace icons if existing and enabled, and icons are square.

Please use https://github.com/lxqt/lxqt/discussions for questions.
