### ISSUE TITLE
[Feature request]detail list, date format as iso yyyy-mm-dd hh:mm(:ss) --- v2.0.0

### ISSUE THREAD

**Issue by artofit** [lxqt/pcmanfm-qt#1927]
**Is your feature request related to a problem? Please describe.**
View list detail list files.
dates are according to some locals

**Describe the solution you'd like**
wish to view iso date format aka (yy)yy-mm-dd hh:mm(:ss)

for instance I see
15/07/24 05:46
I wish to see
2024-07-15 05:46
or
24-07-15 05:46

Thanks

P.S. tested v2.0.0 under Manjaro XFCE latest(24.0.4)

**Comment by stefonarch** [comment]
This is depending on your language settings afaik, you can configure it there:

![immagine](https://github.com/user-attachments/assets/2a5da6f2-5a4f-4603-ba80-bda0bddb6f8a)

**Comment by artofit** [comment]
I'm running on XFCE, so I installed lxqt-config as well.

Now, I do not see how I specify iso format, **there is no iso format in the list.**

P.S. Thunar 4.18.10 has its standalone ability date formats
![Thunar date formatting](https://github.com/user-attachments/assets/4097c87a-9381-4469-9666-174b1fc86640)

**Comment by stefonarch** [comment]
lxqt-config is for an LXQt session. Under XFCE probably the language format settings from the DE are applied.

>Thunar 4.18.10 has its standalone ability date formats (self contained app)

Not all apps have what others do.

**Comment by artofit** [comment]
Still do not understand how I will get dates in the requested format:
2024-07-23 17:11

Thanks

**Comment by stefonarch** [comment]
I don't know if any language setting will display the date like that, I'm afraid not, and I've no idea if you can change system settings in that way for all apps in XFCE.

**Comment by artofit** [comment]
>I've no idea if you can change system settings in that way for all apps in XFCE.
You don't

But here a Thunar view and the ability to sort on dates
![Thunar](https://github.com/user-attachments/assets/ec79b343-21c3-4df1-838c-cbc2fcc5e178)

Now in PCmanFM
![PCmanFM](https://github.com/user-attachments/assets/d64a994d-499f-42ff-a481-37a9e21c3913)


So now you have a new feature request :)

**Comment by tsujan** [comment]
@artofit 
The date format is that of your locale. pcmanfm-qt doesn't (and shouldn't) set the locale; that's not it job. Also, it doesn't (and shouldn't) use an arbitrary format.

**Comment by artofit** [comment]
>I've no idea if you can change system settings in that way for all apps in XFCE.
You don't

Thunar with  view **iso date format**
![Thunar iso](https://github.com/user-attachments/assets/6c0aa2e4-9e51-4e38-a729-eaaf7fd45611)

Thunar with date in today personalized as iso
![Thunar today personalized](https://github.com/user-attachments/assets/2b2289ab-d21e-49fa-9f1f-c046b5d9555c)


Thunar with date according to **regional language**
![Thunar locale](https://github.com/user-attachments/assets/7eedaf5e-e1bf-4a3f-b4b8-d325d71ab193)

On list of dates, I personally find that iso date format is way more convenient.
So I think it'll be a nice feature for PCmanFM to have such as well.

**Comment by artofit** [comment]
@tsujan 
>pcmanfm-qt doesn't (and shouldn't) set the locale; that's not its job. Also, it doesn't (and shouldn't) use an arbitrary format.
Indeed, and so does Thunar, but Thunar has the ability to let you choose(Edit>Preferences) which format you want your date to be displayed.

**Comment by tsujan** [comment]
Thunar is a different app and has no relation to pcmanfm-qt. Your problem is that you want to make one app like the other.

We have a policy on options: enough but not too many.

**Comment by morfikov** [comment]
> @artofit The date format is that of your locale. pcmanfm-qt doesn't (and shouldn't) set the locale; that's not its job. Also, it doesn't (and shouldn't) use an arbitrary format.

I disagree on this. ISO date/time format is an universal thing, which was introduced to assure that the date/time you look at will be the same no matter which place of the world you're are or living in or what locales you've set. That's why they call it [the ISO 8601 standard](https://en.wikipedia.org/wiki/ISO_8601). So in my opinion there's should be a setting allowing a user to choose between their locale date/time or this ISO standard. I'm in the favor of the ISO standard because when you see something like  2025-01-12 13:12:32, you know when the file was created/modified, and you're not wondering whether it's a January or December. :smile:

**Comment by stefonarch** [comment]
> when you see something like 2025-01-12 13:12:32, you know when the file was created/modified, and you're not wondering whether it's a January or December. :]

I still do...

**Comment by morfikov** [comment]
I know, we all do, unless we use the ISO standard. :smile:

**Comment by morfikov** [comment]
> I don't know if any language setting will display the date like that, I'm afraid not, and I've no idea if you can change system settings in that way for all apps in XFCE.

Actually there's a way to do it. In the past some countries were using the ISO standard, for instance en_DK, but they switched to some other format. Many people were using this in the LC_TIME env variable. But there's no need for doing it. Instead you can just use your own locale, for instance I use the following:
`
LC_TIME=en_US_custom.UTF-8`

You can do whatever you want with the date/time format, for instance you can change the first day of the week, etc. But date formats are here:

```
$  cat /usr/share/i18n/locales/en_US_custom | grep fmt
d_t_fmt  "%Y-%m-%d %T %Z"
date_fmt "%Y-%m-%d %T %Z"
d_fmt    "%Y-%m-%d"
t_fmt    "%T"
t_fmt_ampm  ""
```

As you can see it's configured to use the ISO standard. But it seems pcmanfm-qt ignores this setting altogether. and it shows me the English format which is 1/12/25 9:54 AM., and I have no idea where this comes from. So it looks like even when you have the locale set to you preferences, pcmanfm-qt ignores them....

This is what `date` shows:

```
$ date
2025-01-12 10:59:53 CET
```

So it's also the ISO standard...

**Comment by tsujan** [comment]
> But it seems pcmanfm-qt ignores this setting altogether.

Neither pcmanfm-qt nor libfm-qt has anything to do with it directly. libfm-qt uses [`QLocale::system()`](https://doc.qt.io/qt-6/qlocale.html#system). After you change the locale, you need to log out and log in.

**Comment by morfikov** [comment]
I've set this locale years ago, so I'm pretty sure I've been rebooting my system since then a lot of times. :smile:

**Comment by tsujan** [comment]
If so, Qt ignores it, for some reason.

**Comment by morfikov** [comment]
Here's some example:

```
$ env | grep LC_TIME
LC_TIME=en_US_custom.UTF-8

$ date
2025-01-12 12:21:16 CET

$ LC_TIME=en_US.UTF-8 date
Sun Jan 12 12:21:31 PM CET 2025

$ LC_TIME=pl_PL.UTF-8 date
nie, 12 sty 2025, 12:21:50 CET
```

So it changes with the locale change. Maybe pcmanfm-qt (or whatever it user) has issues with the `custom` name in the locale name?

**Comment by tsujan** [comment]
It's possible that Qt doesn't validate that `custom` in the name, but if you're curious, you'll need to read Qt's codes to make sure; the doc is silent about it.

**Comment by tsujan** [comment]
Actually, there may be an easier way: check if it appears in LXQt Locale Configuration, because that app [uses](https://doc.qt.io/qt-6/qlocale.html#matchingLocales)

```c++
QLocale::matchingLocales(QLocale::AnyLanguage, QLocale::AnyScript, QLocale::AnyCountry);
```

If it doesn't show up there, Qt definitely doesn't validate it; if it does, you could select it.

**Comment by morfikov** [comment]
This is a nice example why apps should support the ISO date/time standard independently of the locale set in the system. I mean not in place of, but in addition to, so users could simply switch between the system locale and the ISO format. We have a situation where the system has the ISO date/time format defined and the terminal apps like `date` use it properly, but something between the system and the GUI app has issues with the settings and uses the wrong format.

**Comment by tsujan** [comment]
OK, I thought you were really curious.

**Comment by morfikov** [comment]
I am, but I think I don't have the right tools or knowledge to achieve that. Sooner or later I'm going to find out how to force GUI apps to use the ISO standard,  but for now I have no idea what, but I'm pretty sure I'll figure it out... :smile:

**Comment by tsujan** [comment]
You need to be patient; if `zz` is recognized as a country by the United Nations, then Qt will surely validate it after a while.

**Comment by tsujan** [comment]
`en_001`:

![en_001](https://github.com/user-attachments/assets/21944880-ea0a-41b9-b3d6-e985b6fbeda4)

**Comment by morfikov** [comment]
@tsujan how did you do it?

**Comment by tsujan** [comment]
Saw a few "world" items in LXQt Locale Configuration, and used `world - English (en_001)` only for "Time:".

Actually, I might continue to use it — have never liked the US way of date writing.

**Comment by tsujan** [comment]
I tested on my old laptop, which has an old version of everything. On my work laptop, with the latest upgrades, it's different but still good:

![recent](https://github.com/user-attachments/assets/85e9b919-e7c8-4def-bc23-bf47e2d01621)

The difference is only in how Qt 6.8 shows it — perhaps they thought this way it's cooler — otherwise, our code hasn't changed in this regard.

**Comment by morfikov** [comment]
Still, there's no way to determine looking at it whether it's dd-mm-yyyy or mm-dd-yyyy, and you have 12h time format.

I was trying to change the en_US locale by rewriting it's date/time formats in place, but this didn't change the date format in pcmanfm-qt (it changes for the `date` command). So I have no idea how to change the date in the app. Most apps in my system follow the locale settings or they have their own time/date format configuration. It's really weird that QT apps behave in such unexpected way.

**Comment by tsujan** [comment]
I'm not here to defend Qt. We just use it, because it's superior to GTK.

**Comment by morfikov** [comment]
So why not to implement ISO/locale date/time option for users to choose between the two? There's no need to support all the possible date/time formats (printed by `date`), just the two.

**Comment by tsujan** [comment]
→ https://github.com/lxqt/pcmanfm-qt/issues/1927#issuecomment-2245982666

Please stop this.

**Comment by tsujan** [comment]
Search and find this one yourself:

![001](https://github.com/user-attachments/assets/3acf91db-033e-4c01-ae40-53e001a590e6)

**Comment by morfikov** [comment]
I think you don't know what you are referring to. Se this [en_001](https://www.localeplanet.com/icu/en-001/index.html). There's no such format in this whole `en_001` locale..., not to mention there's no info how to set this in any linux system -- grep'ed a few locale manuals for this phrase, and I found none. So I have no idea what this whole `en_001` is and how to deal with it.

**Comment by tsujan** [comment]
![tooltip](https://github.com/user-attachments/assets/6259f1a2-dfe0-4439-8c6a-a6a127b94e76)

**Comment by morfikov** [comment]
I don't know how to put it...

You have your system and other people have theirs. What works for you not necessarily works for others. You gave me the `en_001` locale. In the description we can see 4 date formats. None of the formats is `yyyy-mm-dd` . If this works for you, fine -- how? I don't know, because there's no such data format in this locale... Maybe can you explain this? Where does this ISO date format come from in you case? Because not from this `en_001` locale...  So either there's some bug somewhere, or you have something in your system that affects the locale or display config. 

I try to configure my system to follow some standards, because I know they always will be working in a predictable way, i.e. the way they should. To sum up -- there's no way in my system to force this app to display the ISO date format, all other apps either follow the system locale settings or have their own date/time settings allowing to change the date to ISO format. Can I count on implementing the date/time ISO format option in pcmanfm-qt? This option is crucial to me. If there's strong NO to this option, I just move on to search other projects and maybe I find the one I look for. So Yes/No, just give me the clear answer.

**Comment by tsujan** [comment]
Added [Wiki → Setting Locale](https://github.com/lxqt/lxqt/wiki/SettingLocale).
