### ISSUE TITLE
[Feature request] Customizable menu in v2.0.0

### ISSUE THREAD

**Issue by artofit** [lxqt/pcmanfm-qt#1928]
**Is your feature request related to a problem? Please describe.**
don't see any customizable menu for either files or folder

**Describe the solution you'd like**
Create personalized menu with right click mouse event; for example give the hash signature of the selected file, execute some script, etc.

Thanks

**Comment by stefonarch** [comment]
https://github.com/lxqt/pcmanfm-qt/wiki#custom-actions
