### ISSUE TITLE
[Feature request] no keyboard shortcuts customization in v2.0.0

### ISSUE THREAD

**Issue by artofit** [lxqt/pcmanfm-qt#1929]
**Is your feature request related to a problem? Please describe.**
v2.0.0
no keyboard shortcut manual or customization

**Describe the solution you'd like**
e.g. have keyboard shortcut to go to the parent folder and able to customize that shortcut.

Thanks

**Comment by stefonarch** [comment]
> have keyboard shortcut to go to the parent folder

Alt+ arrows as in most filemanager. See also:
Help → Hidden shortcuts

![immagine](https://github.com/user-attachments/assets/fcf0950c-f3a0-4e9c-82c4-6e27d7824510)

**Comment by artofit** [comment]
Why not naming it "keyboard shortcuts" instead of "hidden shortcuts" ?

**Comment by stefonarch** [comment]
Because most shortcuts are show besides the menu items:

![immagine](https://github.com/user-attachments/assets/52135651-faa2-4cc6-b5bc-bab53a6dfa92)
