### ISSUE TITLE
--desktop not working on labwc 

### ISSUE THREAD

**Issue by garlett** [lxqt/pcmanfm-qt#1932]
pcmanfm-qt --desktop not working on labwc and sway
But the the file manager and --desktop-pref opens normally

##### Expected Behavior

Show bg color and ~/desktop icons

##### Current Behavior

Outputs on stdout:
isPrimaryInstance
Operation finished: 0x63860a19f5f0
Delete mountoperation

##### Possible Solution

An  --debug angument

##### Steps to Reproduce (for bugs)

1.
2.
3.
4.

##### System Information

* PcManFm-qt version: 2.0.0
* Distribution & Version: arch 
* Qt Version: 
* liblxqt Version: 2.0.0-1
* labwc: 0.7.4
* wlroots: 0.17.3-2

**Comment by stefonarch** [comment]
Not reproducible on both compositors. An issue with external drive? Do you see a coredump in `/var/lib/systemd/coredump/` ? 

```
Operation finished: 0x63860a19f5f0
Delete mountoperation
```

**Comment by tsujan** [comment]
> --desktop not working on labwc

Actually, we give priority to LabWC and Wayfire when testing/using Wayland codes.

**Comment by stefonarch** [comment]
Just to mention: I've also sway, hyprland, kwin_wayland and river and nowhere the desktop isn't working. Actually on Hyprland it creates a workspace for itself aka the "showdesktop" feature. Se there has to be some hidden factor on your side. Which would be good to find out about.

**Comment by tsujan** [comment]
> there has to be some hidden factor on your side. Which would be good to find out about.

Yes. https://github.com/lxqt/lxqt/discussions would be the best place for it.

**Comment by garlett** [comment]
Thanks for help, it worked by removing the secondary vga(gf6200)
