### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by dhlocker** [lxqt/pcmanfm-qt#1937]
**Is your feature request related to a problem? Please describe.**
"Menu->File->Move..." seems to have gone away. Even that action requires mousing all over the window and takes too much farbling about for a simple "Move a file" operation. (And now I don't even see it; I just recently updated to 1.4.1 from 1.3.2.)

**Describe the solution you'd like**
Provide a context menu item "Move ..." or a keyboard shortcut for same.

**Describe eventual alternatives you've considered**
No real alterantives exist - move is such a basic function of a file manager. Accessing it through a single click or keystroke is essential.

**Comment by tsujan** [comment]
Move = cut + paste
