### ISSUE TITLE
"Keep terminal window after command execution" not respected (integration with kitty)

### ISSUE THREAD

**Issue by belkka** [lxqt/pcmanfm-qt#1942]
##### Expected Behavior
I **expected** that the terminal window is kept open after command execution, so that I can read the output, then close window manually.

##### Current Behavior
**Instead**, I see some black window (assumably, kitty) appears for a brief moment, then disappears.

##### Steps to Reproduce (for bugs)

1. Right click any file in pcmanfm
2. Select "Open with..."
3. Open "Custom Command Line" tab
4. Write some command in "Command line to execute", e.g., `file %f`
5. Enable checkboxes "Execute in terminal emulator" and "Keep terminal window open after command execution"
6. Press "OK"

##### Context
I use PCManFM 1.3.2 as my file manager, and I've set kitty as a "Terminal Emulator" in pcmanfm settings.
![screenshot 1, pcmanfm settings](https://github.com/user-attachments/assets/ce3e2e69-5886-415d-8667-10c60ebc4195)
![open with...](https://github.com/user-attachments/assets/b50e068a-a11b-4518-88a7-856848a1cf90)

##### System Information

* PcManFm-qt version: 1.3.2
* Distribution & Version: Archlinux

**Comment by stefonarch** [comment]
You're on the wrong issue tracker: this here is pcmanfm-qt and in Arch its version is 2.0.
