### ISSUE TITLE
Weird wallpaper rendering in different screen layout

### ISSUE THREAD

**Issue by pjw91** [lxqt/pcmanfm-qt#1943]
##### Expected Behavior
Given dual-head (different size), mode=zoom, perScreenWallpaper=true, the wallpaper should correctly zoomed and covers each screen.

##### Current Behavior
However, on some layout, it does not.

##### Steps to Reproduce (for bugs)

1. Given the "good" layout, the wallpaper image is zoomed properly respect to each screen, and covers each screen correctly. (the wallpaper is not depicted in this example)
![good](https://github.com/user-attachments/assets/d45bea58-ea35-488c-b05c-a104b21f98ca)
2. However, given the "bad" layout, the wallpaper (yellow part) was drawn at a weird position (0, 0), and left the uncovered part of screens white.
![bad](https://github.com/user-attachments/assets/110f0fe8-2045-497c-960f-c18c7ab170ae)
3. In both configurations, eDP-1(2560x1600) is the laptop display, and is always the "primary" display; while the DP-1 (3840x2160) is the secondary display.

##### System Information

* PcManFm-qt version: both master and 2.0.0
* Distribution & Version: archlinux, x11
* Qt Version:6.7.2-2
* liblxqt Version: 2.0.0-1

##### Tests
I add some code to DesktopWindow::updateWallpaper,
the wallpaper image is 3840x2160.

With the following config, I use `pcmanfm-qt --desktop-off` and `pcmanfm-qt --desktop -p lxqt` to capture stderr.
```
[currentConfig]
settings\1\connected=true
settings\1\currentMode=71
settings\1\currentModeHeight=1600
settings\1\currentModeRate=59.99392318725586
settings\1\currentModeWidth=2560
settings\1\enabled=true
settings\1\hash=4dd9964bf554467e5bfbcdd4210ba27c
settings\1\name=eDP-1
settings\1\primary=true
settings\1\rotation=1
settings\1\xPos=0
settings\1\yPos=0
settings\2\connected=false
settings\2\hash=
settings\2\name=HDMI-1
settings\3\connected=true
settings\3\currentMode=170
settings\3\currentModeHeight=2160
settings\3\currentModeRate=59.99662399291992
settings\3\currentModeWidth=3840
settings\3\enabled=true
settings\3\hash=1fe61ba2faca95fd6ad4c8c514a72daa
settings\3\name=DP-1
settings\3\primary=false
settings\3\rotation=1
settings\3\xPos=0
settings\3\yPos=1600
settings\4\connected=false
settings\4\hash=
settings\4\name=DP-2
settings\size=4
```
```
pixmapRect:  QRect(0,0 0x0)  # initial
        | QRect(0,0 2560x1600)  # screen1 (eDP-1)
pixmapRect:  QRect(0,0 2560x1600)
        | QRect(0,1600 3840x2160)  # screen2 (DP-1)
pixmapRect:  QRect(0,0 3840x3760) # final result

# start calc each scaled wallpaper image and qpaint:
scr:  QSize(2560, 1600)
        w/ratio:  0.666667    h/ratio:  0.740741
        scaled: QSize(2844, 1600) x_gap: 142
        painter.drawImage:  QSize(2560, 1600)  @  (0,  0)   # => seemed correct
scr:  QSize(3840, 2160)
        w/ratio:  1   hratio/:  1
        scaled: QSize(3840, 2160) xgap: 0
        painter.drawImage:  QSize(3840, 2160)  @  (0 ,  1600)   # => seemed correct
```
but the wallpaper result is depict in the above image, which is incorrect

**Comment by tsujan** [comment]
Which window manager do you use? If it's Openbox, please use another WM, like KWin

**Comment by pjw91** [comment]
In deed, it was openbox.
Unfortunately, changing to kwin_x11 does not help. :(

**Comment by tsujan** [comment]
I don't think the problem can be in pcmanfm-qt's code but will check it when I find the time.

**Comment by tsujan** [comment]
After a quick look at the code, I think there may be a serious issue in the cases of fitting and zooming (the 3rd and 6th options) when "Individual wallpaper for each monitor" is enabled. But I need to check it completely.

For now, I mark this as a bug. Thanks for reporting!

**Comment by stefonarch** [comment]
I've similar monitors from size, but couldn't reproduce with kwin.

**Comment by tsujan** [comment]
> I've similar monitors from size, but couldn't reproduce with kwin.

Not even with the second arrangement, where the greater monitor is below the smaller one?

**Comment by stefonarch** [comment]
> > I've similar monitors from size, but couldn't reproduce with kwin.
> 
> Not even with the second arrangement, where the greater monitor is below the smaller one?

No, tested both option in the settings and both positions. Got me some time as never found my mouse as I'm not used to vertical setups.

**Comment by tsujan** [comment]
Thanks!

I should check the code closely. Maybe what I saw by a glance was a false positive.

**Comment by tsujan** [comment]
OK, what I saw by a glance was a false alarm — I wanted to see an issue, and my brain made up one ;)

I double checked the codes of zooming as well as fitting, especially by considering the dimensions mentioned in the report, but I didn't find any problem. So, the issue should have another cause, outside pcmanfm-qt.

@pjw91
Your report was written very well, and you seem quite capable of checking codes. If you find any problem in this part of the code, please tell us to reopen the report (comments can be added to a closed report).
