### ISSUE TITLE
Get warnings by compilling of PCManFM-QT

### ISSUE THREAD

**Issue by kellerleicheorig** [lxqt/pcmanfm-qt#1945]
Hello,
i can compile the pcmanfm-qt without errors, but when i install it it hangs and in xsession-errors i found this;
""qt.core.qobject.connect: QObject::connect: signal not found in Fm::Folder
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::Folder
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::ProxyFolderModel
   qt.core.qobject.connect: QObject::connect: signal not found in PCManFM::DesktopWindow
   qt.core.qobject.connect: QObject::connect: signal not found in PCManFM::DesktopWindow
   qt.core.qobject.connect: QObject::disconnect: signal not found in Fm::FolderModel
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::Folder
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::Folder
   qt.core.qobject.connect: QObject::disconnect: signal not found in Fm::FolderModel""

When i create a logfile from compilling i find this:
""Parsing file /home/daniel/src/r/home/daniel/src/rpm/BUILD/pcmanfm-qt-2.0.0/pcmanfm/application.h:56: warning: Compound PCManFM::Application is not documented.
....
Generating code for file /home/daniel/src/rpm/BUILD/pcmanfm-qt-2.0.0/pcmanfm/xdgdir.h:27: warning: Member readDesktopDir() (function) of class XdgDir is not documented.""

I searched in web for some informations, but found nothing. I'm not sure what there goes wrong. May I'm a silly idiot, or simple i missing something, but what?

Sorry for my terrible English...

##### System Information
  LXQt Version:           2.0.0
  Qt:                     6.7.2
  Build type:             Release
Kernel: 6.1.109
 
How can i solved this issues?
Thanks for helping
Daniel

**Comment by tsujan** [comment]
It would be much better if you used https://github.com/lxqt/lxqt/discussions for your question.

Anyway, please do as follows:
* Make sure you've installed libfm-qt 2.0.2.
 * Download the source of pcmanfm-qt 2.0.0 and extract it.
 * Open a terminal inside the extracted folder and do `mkdir build && cd build`, then `cmake ..`, then `make`. After the compilation is finished, keep the terminal open.
 * Stop pcmanfm-qt from LXQt Session Settings and *make sure that its process isn't running*.
 * In the terminal type `cd pcmanfm` and then `./pcmanfm-qt`.

Is pcmanfm-qt started without problem?

**Comment by kellerleicheorig** [comment]
No, I get the same errors...
""./pcmanfm-qt
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::SidePane
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::SidePane
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::SidePane
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::SidePane
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::SidePane
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::SidePane
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::SidePane
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::Bookmarks
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::ProxyFolderModel
   qt.core.qobject.connect: QObject::connect: signal not found in PCManFM::View
   qt.core.qobject.connect: QObject::connect: signal not found in PCManFM::View
   qt.core.qobject.connect: QObject::connect: signal not found in PCManFM::View
   qt.core.qobject.connect: QObject::connect: signal not found in PCManFM::View
   qt.core.qobject.connect: QObject::connect: signal not found in PCManFM::View
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::Folder
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::Folder
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::Folder
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::Folder
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::Folder
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::Folder
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::Folder
   qt.core.qobject.connect: QObject::disconnect: signal not found in Fm::CachedFolderModel
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::PathBar
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::PathBar
   qt.core.qobject.connect: QObject::connect: signal not found in Fm::PathBar
""

**Comment by tsujan** [comment]
Supposing that you have libfm-qt 2.0.2, I think there may be a problem in its build/package.

Which distro do you have? Does it provide you with libfm-qt and pcmanfm-qt packages? If yes, which versions?

**Comment by kellerleicheorig** [comment]
I build libfm-qt as well for PCLinuxOS. And I build since 2017 all package for PCLinuxOS without any issues. So what can be wrong goes by building the libfm-qt?

**Comment by tsujan** [comment]
> So what can be wrong goes by building the libfm-qt?

No one can answer this question without more information about your installed libfm-qt. These are only wild guesses: building against different versions of Qt, having mixed installations of Qt5 and Qt6 based libfm-qt, a general problem with Qt6, ...?

I close this because it can't be about an issue in pcmanfm-qt, but feel free to add comments if you want to provide more info.

**Comment by kellerleicheorig** [comment]
Okay, I think you are right. Seems I missing something here, i read following by building libfm-qt
""Could NOT find XCB_XEVIE (missing: XCB_XEVIE_LIBRARY) (found version "")
   Could NOT find XCB_XPRINT (missing: XCB_XPRINT_LIBRARY) (found version "")

   AutoMoc: Generating "SRC:/build/src/fm-qt6_autogen/EWIEGA46WW/moc_utilities_p.cpp", because it doesn't exist, from "SRC:/src/utilities_p.h"
   AutoMoc: Generating "SRC:/build/src/fm-qt6_autogen/EWIEGA46WW/moc_renamedialog.cpp", because it doesn't exist, from "SRC:/src/renamedialog.h"
""

This is strange...

**Comment by tsujan** [comment]
> This is strange...

Yes, indeed.

Again, just a wild guess: are you sure that the process of package building was done correctly?

You could compile libfm-qt 2.0.2 from its source *without installing it* (`mkdir build && cd build` → `cmake ..` → `make`) and see whether you get similar messages in the terminal. If you don't get them, there should have been something wrong with package building; if you do, the issue should be deeper.

**Comment by tsujan** [comment]
And make sure you have `lxqt-build-tools ` 2.0.0 installed.

**Comment by jsm222** [comment]
Is your qt6-base build with  QT_FEATURE_reduce_relocations OFF? what happens if you set SYMBOLIC_FLAGS to "" at  https://github.com/lxqt/lxqt-build-tools/blob/1708c068b3e03f06215c0e2a9423e0a9d7cf6589/cmake/modules/LXQtCompilerSettings.cmake#L167

**Comment by jsm222** [comment]
https://qt-project.atlassian.net/browse/QTBUG-115731
