### ISSUE TITLE
[Feature request] Hide Status Bar & Path Bar

### ISSUE THREAD

**Issue by pfr-dev** [lxqt/pcmanfm-qt#1946]
It would be nice to be able to hide the status and path bar for a minimal appearance/aesthetic. 

The main attraction for this feature is space saving on small screens. I will hide all bars/panels I can if possible. I do believe this is possible in original `PCManFM`

Cheers,

**Comment by tsujan** [comment]
You can already hide the menu-bar.

I really doubt that hiding the tool and status bars too would make sense. We want an app that can be used easily, not a minimalist GUI like those of GNOME. There should be a limit to hiding widgets.

**Comment by pfr-dev** [comment]
> EDIT: This seems to me minimal enough

I agree, yours looks nice, what theme are you using? My toolbar is thick and ugly, perhaps I just need a better theme. 

As for the Status bar, we'll have to agree to disagree there. Plenty of applications allow it to be toggled on/off, and for me it's entirely useless, but I'll live :)

**Comment by tsujan** [comment]
> My toolbar is thick

LXQt 2.1.0 will have this option (it's already in git):

![toolbar](https://github.com/user-attachments/assets/4108819b-2eec-472d-a880-4b412453a3c5)

The general appearance of Qt apps mostly depend on the active Qt style. The default Qt style  is Fusion and has a clean design, but there are also other styles.
