### ISSUE TITLE
Inhibit/reserve translations of desktop categories

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#1951]
Stumbled upon this in the last PR: 
![image](https://github.com/user-attachments/assets/768fcbc9-87bc-4f36-a134-083636063de2)

And checked:
https://translate.lxqt-project.org/search/lxqt-desktop/pcmanfm-qt/?offset=1&q=Video&sort_by=-priority%2Cposition&checksum=

There are quite some translations which will never work, Afaik it's in an `*.ui` file, no idea translation can be disabled.

If not I'll try to remove them in weblate and make an announcement/warning.

ar, cr, fr, he, da, he, ko,no_BO, po, pt, se, tr, uk have it translated.

**Comment by tsujan** [comment]
Nothing can be done in pcmanfm-qt. That's the translator's mistake; he should have considered the context.

**Comment by stefonarch** [comment]
I fixed it already manually and made a warning in weblate.
https://github.com/lxqt/pcmanfm-qt/commit/963feab165aa17eb16754003c766ea00ee69a539
