### ISSUE TITLE
Echoes heif-thumbnailer commands to stderr.

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/pcmanfm-qt#1953]
##### Expected Behavior

No non-error messages.

##### Current Behavior

`heif-thumbnailer -s 128 '[file]' '[thumbnail]'` on stderr for every encountered HEIF image.
Also other diagnostic messages, like:
```
[thumb_buffer @ 0x56536d4ed400] Changing video frame properties on the fly is not supported by all filters.
[thumb_buffer @ 0x56536d4ed400] filter context - w: 1920 h: 1080 fmt: 62 csp: unknown range: unknown, incoming frame - w: 1920 h: 1080 fmt: 62 csp: bt2020nc range: tv pts_time: 0
```

##### Possible Solution

Put this (and other non-error) output  under a `--debug` option.

##### Steps to Reproduce (for bugs)

1. open pcmanfm-qt
2. navigate to a dir full of HEIF images
3.
4.

##### Context

Getting journal stuffed with lots of noise while pcmanfm-qt is running as a user unit.

##### System Information

* PcManFm-qt version: 2.0.0
* Distribution & Version: Debian sid
* Qt Version: 6.7.2
* liblxqt Version: 1.4.0

**Comment by tsujan** [comment]
Those errors don't belong to pcmanfm-qt. A google search shows that they belong to ffmpeg: https://trac.ffmpeg.org/ticket/10823

Anyway, pcmanfm-qt already supports HEIC/HEIF internally if qt6-imageformats and [kimageformats](https://api.kde.org/frameworks/kimageformats/html/index.html) are installed (see https://github.com/lxqt/lximage-qt → README).

**Comment by tsujan** [comment]
Those messages are most probably from your video thumbnailer, not `heif-thumbnailer`, which isn't used when the internal thumbnailer supports HEIF.
