### ISSUE TITLE
[Feature request] Option to point new tabs to workdir.

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/pcmanfm-qt#1955]
**Is your feature request related to a problem? Please describe.**

Currently new tab opens the same dir as current tab.

**Describe the solution you'd like**

An option to always open workdir of pcmanfm-qt process in a new tab. In most cases this would be homedir, but if user specifically opened pcmanfm-qt in a different dir, new tabs would point there. It is a workdir after all.

**Describe eventual alternatives you've considered**

**Comment by tsujan** [comment]
Why?!

> It is a workdir after all.

On the contrary, it's *just* a wokdir after all, and the app isn't a terminal emulator.

1000 new options could be added to the app, but as it has been mentioned repeatedly here and there, we don't add options just because we can add them.

**Comment by Vladimir-csp** [comment]
Is it unreasonable to want to start new tabs in homedir?

**Comment by Vladimir-csp** [comment]
It's just two birds with one stone solution. Usually filemanager is launched by compositor/launcher/systemd in homedir, so when such option is enabled, tabs will open in homedir.
