### ISSUE TITLE
Requiring layer-shell-qt pulls in Wayland dependencies

### ISSUE THREAD

**Issue by nathanzachary** [lxqt/pcmanfm-qt#1961]
##### Expected Behavior
As pcmanfm-qt is supposed to be an independent file manager:

"PCManFM-Qt is used by LXQt for handling the desktop. Nevertheless, it can also be used
independently of LXQt and with any desktop environment, whether under X11 or under Wayland"

it should be possible to build it without pulling in any Wayland dependencies.

##### Current Behavior
The 'layer-shell-qt' package itself requires Wayland development libraries and QtWayland.

##### Possible Solution
Adding logic to check whether the target environment is X11 or Wayland based.

##### Context
I was hoping to switch from pcmanfm to pcmanfm-qt, but use X11 without any desktop environment (just the Openbox Window Manager).  Attempting to switch to pcmanfm-qt, I saw that it requires 'layer-shell-qt', which subsequently requires Wayland libraries including QtWayland.

##### System Information
* PcManFm-qt version: 2.0.0 (1.4.0 is also available)
* Distribution & Version: Gentoo
* Qt Version: 6.7.3 (qtbase)
* liblxqt Version: 2.0.0 (1.4.0 is also available)

**Comment by Chiitoo** [comment]
There were probably other issues/discussions about this, but see for example:

https://github.com/lxqt/lxqt/issues/2579
