### ISSUE TITLE
[Feature request] option to disable wallpaper to allow use of swww or similar wallpaper managers

### ISSUE THREAD

**Issue by washikano** [lxqt/pcmanfm-qt#1967]
I use swww to manage my wallpapers in Hyprland; however, if I want to use `pcmanfm-qt --desktop` I have to set the wallpaper manually again

This isn't a problem with single monitor setups, where I can just use pcmanfm-qt and forego swww; however, in multi-monitor setups I can't use pcmanfm-qt to change the wallpaper in both monitors (or set one wallpaper for all monitors) because it only runs on the primary monitor, and apparently there's no option to run it in both monitors :(

An option to disable the wallpaper like `pcmanfm-qt --desktop --no-bg` and keep only the icons would allow users to use swww or other wallpaper managers, to set the wallpaper for all monitors

Another solution would be to make `pcmanfm-qt --desktop` run on all monitors

An option to see desktop icons on all outputs would be nice as well

I haven't tried lxqt yet, so I don't know if the features I want already work there, so this FR may only apply to Hyprland or other window managers in general (I tried sway as well, and the results were the same)

Thank you for your consideration ^^

**Comment by tsujan** [comment]
Already implemented in git. See https://github.com/lxqt/pcmanfm-qt/wiki#using-desktop-under-wayland

> because it only runs on the primary monitor

Already fixed in git.

All fixes and enhancement are in 2.1.0, which will be released tomorrow.
