### ISSUE TITLE
"Extract Here" does not work any more in LXQt 2.0.0

### ISSUE THREAD

**Issue by ralf3u** [lxqt/pcmanfm-qt#1968]
**Steps to reproduce**
1. mark a zip-file
2. right-click
3. select "Extract Here"

**Result**
Nothing happens.

**Expectation**
An extracted file should appear. 

**Remark**
I think that in LXQt 1.4.0 "Extract Here" worked.

**System**
Lubuntu 24.10
LXQt 2.0.0

**Comment by tsujan** [comment]
Please ask Lubuntu about it.

**Comment by stefonarch** [comment]
Make sure you have unzip installed.

**Comment by ralf3u** [comment]
>Make sure you have unzip installed.

Unzip is installed, because I did this command in the terminal and it worked: `unzip` ...

**Comment by tsujan** [comment]
Read https://github.com/lxqt/lxqt-archiver/pull/380. Actually Lubuntu should read it.

**Comment by ralf3u** [comment]
>Please ask Lubuntu about it.

Done:
https://discourse.lubuntu.me/t/extract-here-does-not-work-any-more-in-pcmanfm-qt-in-lubuntu-24-10/5173

**Comment by ralf3u** [comment]
The solution from Lubuntu:

Edit > Preferences > Advanced > Archiver integration:
instead of file-roller: lxqt-archiver
OK

I restarted PCManFM-Qt. Then "Extract Here" works.

**Comment by ralf3u** [comment]
What about the idea to publish the next release of PCManFM-Qt with "lxqt-archiver" as default, so that "Extract Here" will work right away?

**Comment by ralf3u** [comment]
>What about the idea to publish the next release of PCManFM-Qt with "lxqt-archiver" as default, so that "Extract Here" will work right away?

>2.1.0 is already released.

So, then maybe for the next release.

**Comment by tsujan** [comment]
Yes. I'll remove the string "file-roller" and put "lxqt-archiver" in its place. That makes more sense.
