### ISSUE TITLE
Improvement to Desktop icon positioning

### ISSUE THREAD

**Issue by isf63** [lxqt/pcmanfm-qt#1969]
If this is valid, given the time frame it should be for LXQt 2.2.0 obviously.

##### Possible Solution
If the DnD'd items are sticky and the non-sticky items don't get in the way, when all of the destination slots are empty do not move any other icons.

##### Steps to Reproduce (for bugs)

1. Align 7 sticky icons as so: 
![image1](https://github.com/user-attachments/assets/f1bcb9d3-5f3f-41c0-8281-e5745158ad81)

2. Select the top 3 icons and DnD them one slot over: 
![image2](https://github.com/user-attachments/assets/2996c8eb-d4e8-4ab4-8d1a-dc080eae840b)

3. As depicted in the image, one of the bottom-row icons erroneously shifts down.
4.

##### System Information

* PcManFm-qt version:
* Distribution & Version:
* Qt Version:
* liblxqt Version:

**Comment by tsujan** [comment]
> If this is valid,...

It's definitely valid. Thanks for reporting!

> ...  it should be for LXQt 2.2.0 obviously.

Unless I can magically find out why it's so before tomorrow. But magics never happen ;)

**Comment by tsujan** [comment]
Magic happened ;) I found out why it's so in this example. It's very logical but counterintuitive.

After the release is finished (a really boring job), I'll try to fix this (an exciting job). It needs making changes to the current logic, and it should be done with care...

**Comment by tsujan** [comment]
The PR: https://github.com/lxqt/pcmanfm-qt/pull/1970

I tested it quickly and will re-read its code. However it should be tested thoroughly, and your tests would be very appreciated. There's no haste though.

**Comment by isf63** [comment]
I'm testing it - the reproducible bug case above I happened to stumble upon, during normal use it would only happen very rarely.

**Comment by tsujan** [comment]
It was enough to make two rows of items, one above the other, and DND the upper row horizontally by one cell; then some items of the lower row moved downward — as they should, because of the original code. That doesn't happen anymore.

**Comment by isf63** [comment]
Seems to work, plus fix the bug case.
