### ISSUE TITLE
Icon no longer follows theme

### ISSUE THREAD

**Issue by es20490446e** [lxqt/pcmanfm-qt#1973]
In this [pull request](https://github.com/lxqt/pcmanfm-qt/commit/a291ad08988e728e059603852445729cebdf70bf), the desktop file icon has been changed from `system-file-manager` to `pcmanfm-qt`.

Most desktop themes don't have specific icons for specific file managers, but instead have a single `system-file-manager.svg`. As seen in [Breeze](https://invent.kde.org/frameworks/breeze-icons/-/tree/master/icons/apps/64?ref_type=heads).

If I have `pcmanfm-qt` pinned to the task manager, the icon looks weirdly different from the rest there.

Won't it just be better letting the desktop theme control which icon to show? Is there a reason for having a specific icon for `pcmanfm-qt`?

**Comment by tsujan** [comment]
So many apps have their own icons, whose styles may be different from that of Breeze, Oxygen, etc.

**Comment by es20490446e** [comment]
I have fixed it for Breeze at this [pull request](https://invent.kde.org/frameworks/breeze-icons/-/merge_requests/424).

**Comment by tsujan** [comment]
That's the correct way, although the author(s) of an icon set might want to make new icons with the style of their set.

**Comment by es20490446e** [comment]
I have made a more sophisticated version of the icon, in case you want it here:

![pcmanfm-qt](https://github.com/user-attachments/assets/3886c339-2d46-4e22-ad05-94fc010049d9)

**Comment by es20490446e** [comment]
To be honest even this icon doesn't work as well on Plasma, where the default icon follows tint, it's simpler, and it's the same as folders. So it's more meaningful.

I doubt this change will work well across other themes and desktops either, and I also doubt people are going to make a custom icon for `pcmanfm-qt`.

If they do something about it, they most likely will reuse the `system-file-manager` icon.

**Comment by palinek** [comment]
> put their own icons in the hicolor folder to be distinguished from similar apps. Then the creators of icon themes could make their own icons for well known apps. That's the usual practice.

Exactly. And blame on me, that I missed, we already do it ([`icons/pcmanfm-qt.svg`](https://github.com/lxqt/pcmanfm-qt/blob/master/CMakeLists.txt#L74-L77)). I was fooled as the referenced commit/PR in this issue doesn't contain addition of the icon itself.

Sorry for noise.

**Comment by tsujan** [comment]
> I have made a more sophisticated version of the icon, in case you want it here:

It looks good, but it should be compatible with the set you put it into — in this case Breeze. I can't judge because I don't use Breeze.

**Comment by es20490446e** [comment]
The question I have is if you prefer the new icon as default.

**Comment by tsujan** [comment]
IMO, it isn't OK to change an icon just to make it more compatible with a certain icon set.

If my preference was relevant, I'd say "no".

**Comment by es20490446e** [comment]
I just want it to look professionally made. The current one doesn't reach a bare minimum.

Last chance: decide if you want it here, or if I put it somewhere else.

![old](https://github.com/user-attachments/assets/654837bb-16de-4c9b-9e08-76edbd4248f9)

![new](https://github.com/user-attachments/assets/3d01dc3c-b0d2-4902-9840-7b46b3b29dc8)

**Comment by tsujan** [comment]
I made it so intentionally: simple and flat, not 3D or embellished. Whether that can be interpreted as "bare minimum" is a matter of personal taste.

**Comment by es20490446e** [comment]
### Too flat creates issues

If you see flat logos, you will notice they rarely have lines.

Because when they have they look amateuristic. As being drawn in Microsoft Paint.

But that kind of icons don't work well on UI, because they frequently mix with the background color.

Hence a middle ground usually works better across the spectrum. Having an almost flat icon but with subtle gradients, lines, and maybe 3D.

### Neutral colors shall have no tint

Also the color palette shall be the right one. In particular neutral colors like grey or brown shall not have a tint, or they will look Paint like and even distort the visual perception of surrounding elements.

### Icon and logo design are challenging

Finally drawing something visual simple but functional is much harder to get right than what is apparent.

To get a taste, this was my first serious logo for Ubuntu:

![One Hundred Papercuts banner](https://github.com/user-attachments/assets/2583b3e5-9d17-437b-bd96-8fc28d062316)

It took me about 30 hours to get it right.

**Comment by isf63** [comment]
FWIW here's the `file-manager` icon in various icon sets: (to base `pcmanfm-qt` off of)

- MATE `file-manger`
![file-manager](https://github.com/user-attachments/assets/c6bf7984-5ddd-49cb-b2ff-246d34a26983)

- Oxygen `system-file-manger`
![system-file-manager](https://github.com/user-attachments/assets/1e840ecc-7fe9-42f9-a693-11c1dc1abca0)

- Breeze `system-file-manager`
![system-file-manager](https://github.com/user-attachments/assets/e16c7c13-034d-4f52-9ffa-add9d43ed283)

I personally find MATE's, optionally with some color, to be the most agreeable.

**Comment by es20490446e** [comment]
You need to compare icons in the size you will see them.

Then note that having a color separates better with the background, and the less small details the more aesthetic and functional.

![1](https://github.com/user-attachments/assets/482242e6-e4fa-4457-bfc1-baf06c054312)

![2](https://github.com/user-attachments/assets/8e848584-7aaa-48cd-9a07-274e13d28ca1)

![3](https://github.com/user-attachments/assets/02784e1d-bd91-4bf5-82d3-73b370425f91)

![pcmanfm-qt](https://github.com/user-attachments/assets/569ddb01-ba31-4d7e-a990-cf9326eecbdd)

![new](https://github.com/user-attachments/assets/02fbfd9c-0dec-4620-bd3f-f647ce297e8b)

**Comment by es20490446e** [comment]
Sorry, maybe I have been a bit too demanding.

**Comment by es20490446e** [comment]
Final version for Breeze:

![pcmanfm-qt-192](https://github.com/user-attachments/assets/d626cf97-1964-466a-a0e7-c85e9ac30f39)

![pcmanfm-qt](https://github.com/user-attachments/assets/d23475d9-7d15-49a9-9ae6-dc201d195bf5)
