### ISSUE TITLE
The wallpaper goes off screen in labwc Wayland sessions

### ISSUE THREAD

**Issue by Reiddragon** [lxqt/pcmanfm-qt#1974]
##### Current Behavior

Setting the wallpaper causes the wallpaper to be set as if the screen is larger than it really is, eg: stretch/zoom to fill will cause the wallpaper to go off-screen to the right and bottom of the screen, or centering a small image would have it offset to the right/down of where it should be.

This only happens when setting the wallpaper mid-session, upon logging in, or after killing `pcmanfm-qt` (causing it to be restarted by LXQt) the wallpaper is set properly.

##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### System Information

* Distribution & Version: Arch Linux
* Kernel: 6.11.7-arch1-1
* Qt Version: 6.8.0
* liblxqt Version: 2.1.0
* Package version: 

Note: using a Wayland session with labwc 0.8.1, scaling set to 1.5 using kanshi and left to 1.0 in LXQt settings

**Comment by tsujan** [comment]
The workaround is here: https://github.com/lxqt/pcmanfm-qt/pull/1975. It passed my tests under Labwc.
