### ISSUE TITLE
[Feature request] Desktop: a configurable layer to avoid pcmanfm-qt from being covered.

### ISSUE THREAD

**Issue by Vescrity** [lxqt/pcmanfm-qt#1976]
**Is your feature request related to a problem? Please describe.**

With the ability to set transparent backgrounds, there is a situation where a wallpaper app starts after the desktop and covers it. I recently tried changing the desktop's layer to "Bottom," and it worked (on Hyprland).

**Describe the solution you'd like**

I would like to make the layer of the desktop window configurable.

##### Context

While ensuring that the desktop starts after the background app works, there are times when I want to start `mpvpaper` for a video background and then stop it, which leads to this issue.

I have also tried `swayfx`, which behaves differently. Starting the background first covers other windows that start later. Changing the layer of the background can also allows the desktop to remain visible.

**Comment by tsujan** [comment]
The layer shouldn't be other than what it is, i.e., the background layer.

> a wallpaper app starts after the desktop

Read https://github.com/lxqt/pcmanfm-qt/wiki#using-desktop-under-wayland for how to start your wallpaper app.

**Comment by tsujan** [comment]
Maybe there is a misunderstanding here. There are only 4 layers, with this order: background, bottom, top and overlay. Ordinary windows come between the bottom and top layers. Both Desktop and your wallpaper app go to the background layer, and their order is determined by how they start. We don't have an "upper/lower background" layer.

The bottom layer is for windows that should be above the background layer but below other windows, like Conky. So, it isn't an option for us.
