### ISSUE TITLE
Setting Terminal Emulator

### ISSUE THREAD

**Issue by nPHYN1T3** [lxqt/pcmanfm-qt#1979]
**Is your feature request related to a problem? Please describe.**
I would like to be able to differentiate a terminal launched from the filemanager to work in a specific directory from all my other open terminals in my panels or alttab lists.

**Describe the solution you'd like**
Right now if you set your terminal emulator it truncates the command. So for example I try to set
urxvt -iconFile $HOME/.local/share/icons/m0dw3rks/extra/128/folder-term.png
but it truncates the command to urxvt leaving any terminals opened from the filemanager with no icon.

**Describe eventual alternatives you've considered**
Going back to the GTK version of pcmanfm where this works?

##### Context

Well it's frustrating as GTK is broken by design for multiGPU machines. So I have been trying to migrate to Qt equivilents but feature pairity doesn't seem to be there, even when moving from the same application.

As for usefulness in the real world, well again, icons are there for a reason in modern UI but this truncation of the desired terminal command strips that away.

In theory I'd expect this to be a simple fix/change. However I've also noticed most terminal emulators do not allow you to set icons outside the generic one typically used in the .desktop file. It *might* be useful (but far more complex) to also allow users to set the icon (if it's possible) from pcmanfm-qt. This means selected terminal emulators won't need to support custom icon setting per-se but users could set a special icon to denote terms launched for explicit folder / directory work.

###########################################################################
# Update - Addendum

Thanks to @stefonarch I see pcmanfm-qt is pulling from an external file list. This however creates a few twists to this request.

I hadn't even noticed the input for the terminal emulator is also a dropdown. I was more or less on autopilot from years of using the GTK version. However the fact YOU CAN type in this box is misleading. While it does look to have possibly appended the terminals.list based on what I typed in there it also malformed things and doesn't work either way.

Below the Terminal Emulator input the Switch User Command has a nice little note/writeup about it. Something similar would be good under the dropdown for terms notifying users that this dropdown uses the terminals.list found in $HOME/.local/share/libfm-qt directory.

**Comment by stefonarch** [comment]
I don't find neither Wiki nor tooltips, but try `~/.local/share/libfm-qt/terminals.list`: here 
```
[myterminal]
open_arg=
```

**Comment by nPHYN1T3** [comment]
I just checked that and it was malformed from what I set in pcmanfm-qt but even cleaning it up it doesn't work. Anything special I should know about how to set the line in that file and why pcmanfm-qt doesn't just save the real command or at least SHOW the command linked to this file when you check the value?

**Comment by stefonarch** [comment]
Here `myterminal` is a script:
```
qterminal -p qterm.small
```

**Comment by nPHYN1T3** [comment]
That doesn't match the syntax of the terminals.list file, are you just making a wrapper? I was writing on just now to see if it would work around the issue.

**Comment by stefonarch** [comment]
>I tried a few more times and syntaxes to add the icon file bit to the terminals.list but I just can't get it to work with the open_arg line

Me neither, @tsujan has more insight about it.

**Comment by nPHYN1T3** [comment]
Well given he's rather against the whole setting an icon for a term somehow I feel this request is dead in the water heh. That said I've for a cheesy work around thanks to you letting me know it's pulling from a list rather than that input/dropdown.

**Comment by tsujan** [comment]
Use [Custom Actions](https://github.com/lxqt/pcmanfm-qt/wiki/custom_actions) for any other command.

**Comment by nPHYN1T3** [comment]
You should consider adding a note about this to the GUI. You've got a note for the feature/option below this but not the top and anyone accustom to the GTK version will have issues. Plus as you linked there was another post essentially about the same issue but depending on what search language you use you may not find previous discussions. Meaning the same thing is dredged up over and over when a little note on the GUI would help a lot and be simple to implement.

**Comment by tsujan** [comment]
Yes, the note should be changed. That `%s` should also be removed  (as I said elsewhere, I didn't do it only to save the current translations).

**Comment by tsujan** [comment]
Opened https://github.com/lxqt/pcmanfm-qt/issues/1980 as a reminder for the next version.

**Comment by tsujan** [comment]
Change the code, such that custom options could be added:
![custom](https://github.com/user-attachments/assets/767d03b7-63aa-45b6-be41-316cadb46fcf)
Will make two PRs for libfm-qt and pcmanfm-qt soon, after rereading the patches.

**Comment by nPHYN1T3** [comment]
Just a quick question. Discussions aren't enabled and opening a new issues seems innopropriate. Is there a way to set keybinds for things like the view? I've been digging around and can't find anything on this but in the GTK version ctrl+[1-4] changes your view.

**Comment by tsujan** [comment]
> Discussions aren't enabled

https://github.com/lxqt/lxqt/discussions is used for all LXQt.

> I've been digging around and can't find anything...

If you mean jumping to tabs, both Ctrl+Number and Alt+Number are supported. See Help → Hidden shortcuts.

**Comment by nPHYN1T3** [comment]
No I mean views, like thumbnail, detail, icon, compact.

**Comment by tsujan** [comment]
Oh, I think we had a discussion here a long time ago and couldn't find suitable shortcuts for them, because all good shortcuts were already used.

**Comment by nPHYN1T3** [comment]
Sacrebleu!

**Comment by tsujan** [comment]
If you know of proper shortcuts that don't interfere with the current ones, adding them will be a piece of cake (by proper, I mean with at most two modifiers and not used by most WMs).

**Comment by nPHYN1T3** [comment]
Well when I do ctrl + [1-4] it does nothing so I can't tell if that's actually used (it might be for something I don't have open or enabled atm) but that's what I'm used to in spacefm and pcmanfm (gtk).

**Comment by tsujan** [comment]
> Well when I do ctrl + [1-4] it does nothing

It jumps to 1st-4th tab — unless it's consumed by a global app (like your WM).

> I can't see anything in the menu's that denotes ctrl + numbers doing anything.

Again, Help → Hidden shortcuts.

**Comment by nPHYN1T3** [comment]
Ah yes I didn't recheck the hidden bits, but I only have a single tab open atm. I suppose ctrl + alt + [1-4] would work despite being strange heh. I don't think it really fits the bill though. I think this is all strange because I figured this was pcmanfm just using qt over gtk but it's very very different and really tosses muscle memory from the GTK (and other fm) out the window.

**Comment by tsujan** [comment]
> I suppose ctrl + alt + [1-4] would work

Usually used by WMs, unfortunately.

> I figured this was pcmanfm just using qt over gtk

A long time ago, yes — it was started as a Qt port of pcmanfm (hence the current similarities) — but it found its own way several years ago, such that pcmanfm and pcmanfm-qt are very different apps now.

Thanks for opening this report, without which I might forget about https://github.com/lxqt/libfm-qt/issues/954.
