### ISSUE TITLE
missing display of icons due to limitation in QIcon

### ISSUE THREAD

**Issue by pmattern** [lxqt/pcmanfm-qt#198]
PCManFM-Qt doesn't display icons located at some of the paths covered by the [Icon Theme Specification](http://www.freedesktop.org/wiki/Specifications/icon-theme-spec) due to a bug in QIcon.

This affects desktop entry files placed on the desktop (XDG_DESKTOP_DIR in terms of [xdg-user-dirs](http://www.freedesktop.org/wiki/Software/xdg-user-dirs), see #99 and lxde/lxqt#915), context menu `Open with...` in the file manager itself used to select applications to open files or directories as well as dialog `Choose an Application` invoked from the latter ("Other Applications") , see lxde/lxqt#814.
Regarding paths `/usr/share/pixmaps` is for sure wrongfully _un_considered, as for `~/.local/share/icons` there's an ongoing discussion in lxde/lxqt#915.

Maybe even more components are affected but panel's plugin-mainmenu is _not_, rather, the correct icon gets displayed in the respective submenu.
AFAIK `/usr/share/pixmaps` is more and more deprecated in favour of `/usr/share/icons/hicolor`. But it's still part of the [Icon Theme Specification](http://www.freedesktop.org/wiki/Specifications/icon-theme-spec) and a number of applications is still using it by default.

Latest Git versions of all LXQt components on Arch Linux x86_64.
A similar finding was posted in lxde/lxqt#389 but basically invalid as the stated SVG files' paths were violating the specs in several ways.

[EDIT
Adjust both title and this comment in an attempt to sum up the numerous issue addressing the problem that came up by now.]

**Comment by PCMan** [comment]
This is actually a limitation or bug of Qt.
The xdg support of QIcon does not handle /usr/share/pixmap directory AFAIK.

**Comment by pmattern** [comment]
Oops, [indeed](https://bugreports.qt.io/browse/QTBUG-33123). Any chance to handle this the same way as panel's plugin-mainmenu for now?

**Comment by luis-pereira** [comment]
@PCMan `XdgIcon` supports it. Check it [here](https://github.com/lxde/libqtxdg/blob/master/qiconfix/qiconloader.cpp#L390)

**Comment by alex3kov** [comment]
This is still happening on 0.11 - I'm not getting icons on .desktop files. Here's the Icon line from the file:  
`Icon=9219_goggame-1438332414.0`

**Comment by palinek** [comment]
> This is still happening on 0.11 - I'm not getting icons on .desktop files.

According to other (recent) issue thread, you're not using the lxqt qt-plugin (which provides own QIconEngine for Qt5 apps). It should be fixed there. If not, please, report it here.

**Comment by alex3kov** [comment]
> According to other (recent) issue thread, you're not using the lxqt qt-plugin (which provides own QIconEngine for Qt5 apps). It should be fixed there. If not, please, report it here.

Tried it with lxqt-qtplugin - it works after setting `QT_QPA_PLATFORMTHEME` to `lxqt`.  
For what it's worth - it also works with `qt5ct` (after setting `QT_QPA_PLATFORMTHEME` to `qt5ct`), with `lxqt-qtplugin` and `lxqt-config` uninstalled and `~/.config/lxqt/` directory removed.  
Just to be clear - pcmanfm-qt gets all the theming information from Qt5 settings (`QT_QPA_PLATFORMTHEME`), right?

**Comment by palinek** [comment]
> Just to be clear - pcmanfm-qt gets all the theming information from Qt5 settings (QT_QPA_PLATFORMTHEME), right?

Not exactly. The Qt5 provides mechanism for adjusting app behaviour/style via the platform theme ... one of those adjustions is the possibility to provide own icon engine (the way how icon files are found based on their symbolic names). Platform theme doesn't need to provide it's own icon engine.

doc: http://doc.qt.io/qt-5/qpa.html
