### ISSUE TITLE
[Feature request] Don't draw the desktop background

### ISSUE THREAD

**Issue by boffi** [lxqt/pcmanfm-qt#1992]
My problem is, `pcmanfm-qt` draws a single background for all the 4 workspaces that I manage with Compiz, while I'd like to differentiate the workspaces by their backgrounds (backgrounds that Compiz can set independently from the file manager).

What I'd like to have is a new configuration option, to tell `pcmanfm-qt` not to draw the desktop background.

---
PS I know that I can disable the "Desktop" module, I have disabled it already. I want to enable the "Desktop" module and have it leave my backgrounds alone…

**Comment by isf63** [comment]
I think you can persistently disable the "Desktop" module in Session Settings. Then launching PCManFM-Qt otherwise will act as a windowed file manager and not a desktop.

**Comment by boffi** [comment]
> I think you can persistently disable the "Desktop" module in Session Settings. Then launching PCManFM-Qt otherwise will act as a windowed file manager and not a desktop.

That is what I've done: I have disabled already the "Desktop" module because I want the different backgrounds, but I prefer to have the cake and eat it too oe, iow, tell `pcmanfm-qt --desktop` not to draw the background.

**Comment by stefonarch** [comment]
You can use a different wallpaper generator and set in pcmanfm-qt a complete transparent `.png` image. But unfortunately only under Wayland (where you could use wayfire, successor of Compiz...).

**Comment by tsujan** [comment]
Not planned for X11.

It was done for Wayland only because it didn't need extra codes. With X11, we'd need to check the existence of a compositor, and that would require X11-specific codes, which we started to avoid a long time ago.

**Comment by boffi** [comment]
Most enhacement requests are not planned, but some are however enacted.
I appreciated how deep and articulated the debate that led to closing has been.
> It could be done but I won't
```
$ killall pcmanfm-qt
$ 
```
