### ISSUE TITLE
`.tar.bz2` not recognized as a format that can be extracted

### ISSUE THREAD

**Issue by es20490446e** [lxqt/pcmanfm-qt#1993]
If you right click on such file, the "extract" option doesn't appear.

**Comment by stefonarch** [comment]
Not reproducible.
![immagine](https://github.com/user-attachments/assets/2baca8b7-28cc-43aa-a385-6de695dd7652)

There is some info  missing, I guess `tar` is installed?

**Comment by tsujan** [comment]
> There is some info missing,

Yes, all of "System Information", which is requested in the issue template.

**Comment by es20490446e** [comment]
I was waiting to see if it was only me, before putting the effort:

##### System
* `pcmanfm-qt` 2.1.0
* `Qt` 6.8.1
* `liblxqt` 2.1.0
* `tar` 1.35
* `bzip2` 1.0.8
* `file-roller` 44.4
* `shared-mime-info` 0.35
* Arch Linux

##### Steps
1. Compress a plain text file as `.tar.bz2`.
2. Right click on it.

##### Result
- You are offered to compress again, but not to decompress.
- The mime-type in the file properties is `application/x-bzip2-compressed-tar`. Maybe they changed it somehow.

**Comment by tsujan** [comment]
> file-roller 44.4

That may be a problem of file-roller. Use lxqt-archiver, especially in Preferences → Advanced → Archive integration.

**Comment by es20490446e** [comment]
It doesn't happen with `lxqt-archiver`, only with `file-roller`.

Is this an issue with `file-roller`integration into `pcmanfm-qt`? O is it an error of `file-roller` itself that I need to report upstream?

If I open the `.tar.bz2` archive on `file-roller` it gives no issue.

**Comment by tsujan** [comment]
> Is this an issue with file-roller integration into pcmanfm-qt? 

Will check it…

**Comment by tsujan** [comment]
OK, the problem is in file-roller 44.4: its desktop file, `org.gnome.FileRoller.desktop`, doesn't contain `application/x-bzip2-compressed-tar`.

Long story short, some mimetypes were changed several months ago, and I included them in lxqt-archiver (as well as Arqiver). `application/x-bzip2-compressed-tar` was among them.

Please tell us if the issue is fixed in a stable version of file-roller because, in that case, its entry will need to be updated in our `archivers.list`.

**Comment by es20490446e** [comment]
Not fixed in `file-roller`, can't know when it will be.

---

Building both the latest stable version and the git version generate the wrong mime-types for the desktop file:

`MimeType=application/bzip2;application/gzip;application/vnd.android.package-archive;application/vnd.ms-cab-compressed;application/vnd.debian.binary-package;application/vnd.rar;application/x-7z-compressed;application/x-7z-compressed-tar;application/x-ace;application/x-alz;application/x-apple-diskimage;application/x-ar;application/x-archive;application/x-arj;application/x-brotli;application/x-bzip-brotli-tar;application/x-bzip;application/x-bzip-compressed-tar;application/x-bzip1;application/x-bzip1-compressed-tar;application/x-bzip3;application/x-bzip3-compressed-tar;application/x-cabinet;application/x-cd-image;application/x-compress;application/x-compressed-tar;application/x-cpio;application/x-chrome-extension;application/x-deb;application/x-ear;application/x-ms-dos-executable;application/x-gtar;application/x-gzip;application/x-gzpostscript;application/x-java-archive;application/x-lha;application/x-lhz;application/x-lrzip;application/x-lrzip-compressed-tar;application/x-lz4;application/x-lzip;application/x-lzip-compressed-tar;application/x-lzma;application/x-lzma-compressed-tar;application/x-lzop;application/x-lz4-compressed-tar;application/x-ms-wim;application/x-rar;application/x-rar-compressed;application/x-rpm;application/x-source-rpm;application/x-rzip;application/x-rzip-compressed-tar;application/x-tar;application/x-tarz;application/x-tzo;application/x-stuffit;application/x-war;application/x-xar;application/x-xz;application/x-xz-compressed-tar;application/x-zip;application/x-zip-compressed;application/x-zstd-compressed-tar;application/x-zoo;application/zip;application/zstd;`

But the mimes at `/usr/share/mime/application` are the correct ones:
```
command: ls x-bzip2*
x-bzip2-compressed-tar.xml  x-bzip2.xml
```

I don't see how that list is generated, at [`data/meson.build`](https://gitlab.gnome.org/GNOME/file-roller/-/blob/master/data/meson.build):

```
desktop_in_file = custom_target(
  'org.gnome.FileRoller.desktop.in',
  input: [
    'supported-mime-types',
    'org.gnome.FileRoller.desktop.in.in',
  ],
  output: 'org.gnome.FileRoller.desktop.in',
  command: [
    find_program('python3'),
    files('set-mime-type-entry.py'),
    '@INPUT@',
  ],
  capture: true,
  install: false,
)
```

I don't see where that `@INPUT@` comes from. Definitely not hard-coded in the package recipe.

---

Sadly I cannot report this to GNOME. For my surprised they banned my account years ago.

Later I discovered that several other accounts were banned too. And that banning anyone critical, even if done respectfully, was common ([example](https://felipec.wordpress.com/2011/09/23/no-gnome-doesnt-want-user-feedback-how-i-argued-in-favor-of-voting-in-bugzilla-and-got-banned-as-a-result/)).

For instance I just read that they recently banned both the foundation director Sonny Piers, and the Manjaro Gnome maintainer Yonachan ([reference](https://lunduke.locals.com/post/5908516/gnome-bans-manjaro-core-team-member-for-uttering-lunduke)).

**Comment by tsujan** [comment]
> they banned my account years ago.

Haha… I was on the verge of getting banned too, but I said goodbye to GNOME and GTK altogether when its version became 3.6. I was thankful because, without what they did to GNOME, I wouldn't discover Qt.

Anyway, LXQt is impartial. If they fix their mimetypes, we'll put them into `archivers.list` — provided that someone tells us about it.

**Comment by es20490446e** [comment]
🤦😅
