### ISSUE TITLE
[Feature request] Open bookmars from the side panel in a new tab

### ISSUE THREAD

**Issue by morfikov** [lxqt/pcmanfm-qt#1994]
There's an option in the Preferences>Behavior concerning opening bookmarks (current tab, new tab, new window). It would be nice to have this setting applied to the bookmarks (and other entries) in the side panel.

**Comment by tsujan** [comment]
No redundant option.

**Comment by morfikov** [comment]
I wouldn't say it's a redundant option -- it's more like a consistent one. When you open the bookmark menu, you can also open a bookmark in a new tab using the middle click. So why does this option exist?
