### ISSUE TITLE
[Feature request] Allow choosing between unmount/eject 

### ISSUE THREAD

**Issue by morfikov** [lxqt/pcmanfm-qt#1995]
The purpose of the eject button near the entries in the side panel is (I think) for the drive to be physically removed from the system in a safe way. So you press the button and then you pull the pendrive/sd card/external drive out from the USB port. Currently the eject button tries to eject the drive when pressed. This is fine when you deal with a single partition drive. When you have a drive with multiple partitions, this action can cause unwanted behavior, i.e. ejecting the whole drive because obviously you can't just eject only one of its partitions. In my case, it always ends with a popup window with the following info:

`Error ejecting /dev/mmcblk0: Command-line "eject '/dev/mmcblk0'' exited with non-zero exit status 1: eject: unable to eject`

From what I've seen, there are cases when pressing the eject button unmounts a resource, for instance a SMB share. It would be really useful if the action assigned to the eject button be selected by the user, i.e. unmount or eject. Why eject is used when all that user needs is unmount?

**Comment by tsujan** [comment]
Check the right-click menu (a.k.a. context menu). If `GLib` allows separate ejection and unmount operations, they'll be there ­— and also in context menus of volumes inside Computer.

Please check the app before reporting.

**Comment by morfikov** [comment]
I know there's a separate option for unmounting and yes it works fine, but for the ... sake, right clicking all the time and selecting items from the menu in case of so obvious matters hurts user experience -- we're not living in the 80s anymore...
