### ISSUE TITLE
Safety remove drive

### ISSUE THREAD

**Issue by bruno50** [lxqt/pcmanfm-qt#208]
Can you add a "safety remove drive" command on pcmanfm for USB keys or USB drive
I'm newbee user of LXQT. It's not an issue but it will be better. Sorry for my English. I don't know if it is the correct way for this request. Thank-you
Best regards

**Comment by bruno50** [comment]
Sorry, i was not enough precis : 
for an USB key i have two functions : Umount and Eject
for an USB disk i have only the function Umount
Regards

**Comment by PCMan** [comment]
Would you please give me the output of the following command line to help debugging?
> gvfs-mount -l -i
This command is a utility provided by gvfs.
With its output, we can see what happens.
Thanks!

**Comment by bruno50** [comment]
Hello, thank you for your answer,
my PC : emachines EL 1352 with a SSD (drive(0) and dual boot archlinux with desktop mate and windows10
with mate i have "caja" for file manager but i like pcmanfm.
with caja i have the "safety remove drive" function for my Seagate Expansion Drive (USB drive)
Best regards
Bruno
the result of the command gvfs-mount -l -i
Drive(0): KINGSTON SV300S37A240G
  Type: GProxyDrive (GProxyVolumeMonitorUDisks2)
  ids:
   unix-device: '/dev/sda'
  themed icons:  [drive-harddisk-solidstate]  [drive-harddisk]  [drive]
  symbolic themed icons:  [drive-harddisk-solidstate-symbolic]  [drive-harddisk-symbolic]  [drive-symbolic]  [drive-harddisk-solidstate]  [drive-harddisk]  [drive]
  is_media_removable=0
  has_media=1
  is_media_check_automatic=1
  can_poll_for_media=0
  can_eject=0
  can_start=0
  can_stop=0
  start_stop_type=shutdown
  sort_key=00coldplug/00fixed/sd____a
  Volume(0): hnux
    Type: GProxyVolume (GProxyVolumeMonitorUDisks2)
    ids:
     class: 'device'
     unix-device: '/dev/sda8'
     uuid: '29fa7cca-b8c7-4934-87cd-02586b8a2ec0'
     label: 'hnux'
    themed icons:  [drive-harddisk-solidstate]  [drive-harddisk]  [drive]
    symbolic themed icons:  [drive-harddisk-solidstate-symbolic]  [drive-harddisk-symbolic]  [drive-symbolic]  [drive-harddisk-solidstate]  [drive-harddisk]  [drive]
    can_mount=1
    can_eject=0
    should_automount=0
    sort_key=gvfs.time_detected_usec.1442080502264697
  Volume(1): nux
    Type: GProxyVolume (GProxyVolumeMonitorUDisks2)
    ids:
     class: 'device'
     unix-device: '/dev/sda7'
     uuid: 'cafc1548-cca3-4efc-a846-54c22990fe4d'
     label: 'nux'
    themed icons:  [drive-harddisk-solidstate]  [drive-harddisk]  [drive]
    symbolic themed icons:  [drive-harddisk-solidstate-symbolic]  [drive-harddisk-symbolic]  [drive-symbolic]  [drive-harddisk-solidstate]  [drive-harddisk]  [drive]
    can_mount=1
    can_eject=0
    should_automount=0
    sort_key=gvfs.time_detected_usec.1442080502264855
  Volume(2): Volume de 135 GB
    Type: GProxyVolume (GProxyVolumeMonitorUDisks2)
    ids:
     class: 'device'
     unix-device: '/dev/sda1'
     uuid: 'C0A06570A0656DBA'
    themed icons:  [drive-harddisk-solidstate]  [drive-harddisk]  [drive]
    symbolic themed icons:  [drive-harddisk-solidstate-symbolic]  [drive-harddisk-symbolic]  [drive-symbolic]  [drive-harddisk-solidstate]  [drive-harddisk]  [drive]
    can_mount=1
    can_eject=0
    should_automount=0
    sort_key=gvfs.time_detected_usec.1442080502265018
Drive(1): ST3320820AS
  Type: GProxyDrive (GProxyVolumeMonitorUDisks2)
  ids:
   unix-device: '/dev/sdb'
  themed icons:  [drive-harddisk]  [drive]
  symbolic themed icons:  [drive-harddisk-symbolic]  [drive-symbolic]  [drive-harddisk]  [drive]
  is_media_removable=0
  has_media=1
  is_media_check_automatic=1
  can_poll_for_media=0
  can_eject=0
  can_start=0
  can_stop=0
  start_stop_type=shutdown
  sort_key=00coldplug/00fixed/sd____b
  Volume(0): Volume de 15 GB
    Type: GProxyVolume (GProxyVolumeMonitorUDisks2)
    ids:
     class: 'device'
     unix-device: '/dev/sdb7'
     uuid: '37cd897c-1dda-483f-8afe-4463125c3333'
    themed icons:  [drive-harddisk]  [drive]
    symbolic themed icons:  [drive-harddisk-symbolic]  [drive-symbolic]  [drive-harddisk]  [drive]
    can_mount=1
    can_eject=0
    should_automount=0
    sort_key=gvfs.time_detected_usec.1442080502264035
  Volume(1): Volume de 19 GB
    Type: GProxyVolume (GProxyVolumeMonitorUDisks2)
    ids:
     class: 'device'
     unix-device: '/dev/sdb5'
     uuid: 'b7513ff8-ee5c-4c2a-a3d6-4257ffc07b3f'
    themed icons:  [drive-harddisk]  [drive]
    symbolic themed icons:  [drive-harddisk-symbolic]  [drive-symbolic]  [drive-harddisk]  [drive]
    can_mount=1
    can_eject=0
    should_automount=0
    sort_key=gvfs.time_detected_usec.1442080502264230
  Volume(2): DATA
    Type: GProxyVolume (GProxyVolumeMonitorUDisks2)
    ids:
     class: 'device'
     unix-device: '/dev/sdb3'
     uuid: '54105AF4105ADC94'
     label: 'DATA'
    themed icons:  [drive-harddisk]  [drive]
    symbolic themed icons:  [drive-harddisk-symbolic]  [drive-symbolic]  [drive-harddisk]  [drive]
    can_mount=1
    can_eject=0
    should_automount=0
    sort_key=gvfs.time_detected_usec.1442080502264391
  Volume(3): eMachines
    Type: GProxyVolume (GProxyVolumeMonitorUDisks2)
    ids:
     class: 'device'
     unix-device: '/dev/sdb2'
     uuid: '664C80DC4C80A7FF'
     label: 'eMachines'
    themed icons:  [drive-harddisk]  [drive]
    symbolic themed icons:  [drive-harddisk-symbolic]  [drive-symbolic]  [drive-harddisk]  [drive]
    can_mount=1
    can_eject=0
    should_automount=0
    sort_key=gvfs.time_detected_usec.1442080502264544
Drive(2): Generic- Compact Flash
  Type: GProxyDrive (GProxyVolumeMonitorUDisks2)
  ids:
   unix-device: '/dev/sdc'
  themed icons:  [drive-removable-media-usb]  [drive-removable-media]  [drive-removable]  [drive]
  symbolic themed icons:  [drive-removable-media-usb-symbolic]  [drive-removable-media-symbolic]  [drive-removable-symbolic]  [drive-symbolic]  [drive-removable-media-usb]  [drive-removable-media]  [drive-removable]  [drive]
  is_media_removable=1
  has_media=0
  is_media_check_automatic=1
  can_poll_for_media=0
  can_eject=1
  can_start=0
  can_stop=0
  start_stop_type=shutdown
  sort_key=00coldplug/12removable/sd____c
Drive(3): Multiple Flash Reader
  Type: GProxyDrive (GProxyVolumeMonitorUDisks2)
  ids:
   unix-device: '/dev/sdd'
  themed icons:  [drive-removable-media-usb]  [drive-removable-media]  [drive-removable]  [drive]
  symbolic themed icons:  [drive-removable-media-usb-symbolic]  [drive-removable-media-symbolic]  [drive-removable-symbolic]  [drive-symbolic]  [drive-removable-media-usb]  [drive-removable-media]  [drive-removable]  [drive]
  is_media_removable=1
  has_media=0
  is_media_check_automatic=1
  can_poll_for_media=0
  can_eject=1
  can_start=0
  can_stop=0
  start_stop_type=shutdown
  sort_key=00coldplug/12removable/sd____d
Drive(4): Seagate Expansion
  Type: GProxyDrive (GProxyVolumeMonitorUDisks2)
  ids:
   unix-device: '/dev/sde'
  themed icons:  [drive-harddisk-usb]  [drive-harddisk]  [drive]
  symbolic themed icons:  [drive-harddisk-usb-symbolic]  [drive-harddisk-symbolic]  [drive-symbolic]  [drive-harddisk-usb]  [drive-harddisk]  [drive]
  is_media_removable=0
  has_media=1
  is_media_check_automatic=1
  can_poll_for_media=0
  can_eject=0
  can_start=0
  can_stop=1
  start_stop_type=shutdown
  sort_key=01hotplug/1442080570336426
  Volume(0): Seagate Expansion Drive
    Type: GProxyVolume (GProxyVolumeMonitorUDisks2)
    ids:
     class: 'device'
     unix-device: '/dev/sde1'
     uuid: 'D424856924854F82'
     label: 'Seagate Expansion Drive'
    themed icons:  [drive-harddisk-usb]  [drive-harddisk]  [drive]
    symbolic themed icons:  [drive-harddisk-usb-symbolic]  [drive-harddisk-symbolic]  [drive-symbolic]  [drive-harddisk-usb]  [drive-harddisk]  [drive]
    can_mount=1
    can_eject=0
    should_automount=1
    sort_key=gvfs.time_detected_usec.1442080570440501
    Mount(0): Seagate Expansion Drive -> file:///run/media/thomas/Seagate%20Expansion%20Drive
      Type: GProxyMount (GProxyVolumeMonitorUDisks2)
      default_location=file:///run/media/thomas/Seagate%20Expansion%20Drive
      themed icons:  [drive-harddisk-usb]  [drive-harddisk]  [drive]
      symbolic themed icons:  [drive-harddisk-usb-symbolic]  [drive-harddisk-symbolic]  [drive-symbolic]  [drive-harddisk-usb]  [drive-harddisk]  [drive]
      x_content_types: x-content/win32-software
      can_unmount=1
      can_eject=0
      is_shadowed=0
      sort_key=gvfs.time_detected_usec.1442080572010756
[thomas@archb ~]$

**Comment by bruno50** [comment]
sorry i have close but i would only do a comment
Bruno

**Comment by tsujan** [comment]
Devices can be easily and safely removed. I don't know why this issue wasn't closed sooner.
