### ISSUE TITLE
improvements regarding external applications

### ISSUE THREAD

**Issue by pmattern** [lxqt/pcmanfm-qt#226]
**The UIs to chose external applications should be consistent**
In `Preferences - Advanced` the terminal emulator can be chosen from a drop-down providing a hard-coded list or edited manually, the application to switch the user can be edited manually only, the archiver can be chosen from a hard-coded list only.
I think it would be better if this was consistent and those three choices were offered the same way, possibly the one from the terminal emulator as it's the most flexible.
(A lack to chose archivers manually has already been brought up in #98.)

**The way changes are applied should be the same regarding all applications**
Changes regarding terminal emulator or application to switch user are applied at once while a different archiver is used in a new session only.
This should be consistent, possibly by making the archiver behave like the other two kinds as this is how changes are currently handled by the various tools `lxqt-config-*` as well.

**Warnings regarding missing applications should cover all kinds and get extended a bit**
If a terminal emulator or an application to switch user in terms of the said `Advanced` settings doesn't exist a dialog displaying a corresponding warning comes up when `Open Terminal` or `Open as Root` is selected from menu "Tool" or `Open in Terminal` from a folder's context menu. But a similar warning lacks if `Compress` is chosen from FHS objects' context menus.
I think regarding the latter a warning should be added as well.

Also, I suppose the UX could be improved if those warnings wouldn't just tell that the application is missing but also provided some hints what to do, e. g. something like "You may want to install <Variable> or select a different application from Edit - Preferences - Advanced.".

**Comment by tsujan** [comment]
Nowadays, we don't process this kind of report. Every report should be about one specific issue/feature request. Keeping this open is confusing while reading issue titles.
