### ISSUE TITLE
Build instructions in README

### ISSUE THREAD

**Issue by vishesh** [lxqt/pcmanfm-qt#239]
Build instructions should be provided in README. A list of packages required at least, if not exact command for selected distros. On Ubuntu I had to install following -

```
# apt-get install qttools5-dev qttools5-dev-tools libfm-dev libmenu-cache-dev qt5-default cmake libqt5x11extras5-dev 
```

I would have created a pull request, but well I wanted to build a list of packages that would be needed in a minimal plausible environment.

**Comment by jleclanche** [comment]
Packages needed should be in cmakelists.txt if you'd like them for a PR.
