### ISSUE TITLE
In compact view, pressing the arrow down/up key does not change the column when last/first item of column is selected

### ISSUE THREAD

**Issue by DrTobe** [lxqt/pcmanfm-qt#240]
The compact view is a list, it is shown from top to bottom. Different from detailed list view, it does not allow scrolling down when the height is filled with items, but it starts new columns (when the width is filled, it will allow scrolling left/right). So when I select items with the arrow keys, I can go back and forth in the list with the up and down key. When I have reached the last item of a column, the next item in the list is the first item of the next column. By pressing arrow down again, I should reach that item. And that is what does not work. pcman-gtk supports that so I think that my expectations are right and the program should do so.

**Comment by tsujan** [comment]
> When I have reached the last item of a column, the next item in the list is the first item of the next column. By pressing arrow down again, I should reach that item.

No, you shouldn't -- down means down. Use PgUp/PgDn keys.
