### ISSUE TITLE
Changing display resolution doesn't resize desktop window

### ISSUE THREAD

**Issue by limadm** [lxqt/pcmanfm-qt#247]
Hello!

I'm using lxqt on virtualbox'ed archlinux for the first time, and I noticed that changing the display resolution doesn't trigger a resize in the pcmanfm-qt desktop window (which is lauched by lxqt-session with `pacman-qt --desktop --profile=lxqt`).
Restarting pcmanfm-qt with `pacman-qt --desktop-off; pacman-qt --desktop --profile=lxqt` fixed the problem. Shouldn't this desktop daemon launch after vboxclient by lxqt-session?

**Comment by pmattern** [comment]
First we need to know how LXQt was installed and which version you're hence running.

Next, what way are you trying to change the resolution in the session? Are you by any chance using dialog "Monitor Settings" (binary `lxqt-config-monitor`)?
If so, you may want to hit "Apply" twice (there seems to be an issue in recent VCS code enforcing this). Also, you could try and change resolutions from a Terminal Emulator like QTerminal with `xrandr`, e. g.
Run
`$ xrandr`
to figure out how your output is named which normally terms like `DVI-0`, `VGA-0` or `Virtual-0`. Next try to set the resolution by an invocation like
`$xrandr --output DVI-0 --mode 1920x1080`

**Comment by devsr** [comment]
Ran across this today trying to use LXQt inside VNC on CentOS 7  (Current version in EPEL 7 is LXQt 0.11.0).

Resizing the screen doesn't change the desktop size unless I toggle the desktop as mentioned above by @limadm . Changing the screen size with `lxqt-config-monitor` and `xrandr` exhibit the same issue.

**Comment by tsujan** [comment]
This should have been fixed after removing `QDesktopWidget` from the code -- in 0.14.
