### ISSUE TITLE
allow to hide sidebar categorys

### ISSUE THREAD

**Issue by ghost** [lxqt/pcmanfm-qt#260]
Hi,

It would be nice if I could hide some categorys(eg I don't use gvfs so the devices/network category is always empty)

**Comment by tsujan** [comment]
I agree. It would be nice to have a "Hide this item" on the right-click menu for each item and a "Show hidden items" on the context menu of the sidebar -- similar to what Dolphin has.

**Comment by tsujan** [comment]
Already implemented.
