### ISSUE TITLE
add missing menu icons

### ISSUE THREAD

**Issue by ghost** [lxqt/pcmanfm-qt#261]
the file manager would be much better to use if every menuitem would have a menu icon (my freedesktop icon naming suggestions):

FILE:
new tab:  actions/tab-new
create new: actions/list-add
file/folder properities: a settings icon eg actions/document-properties or categories/preferences-settings
close tab:  actions/tab-close
close window: actions/window-close

EDIT:
rename: actions/edit-rename
select all: actions/edit-select-all
invert selection: not sure but there is a kdeicon named actions/invert-filters
preferences:  categories/preferences-settings

VIEW:
sorting: actions/view-sort

GO:
network: places/folder-remote
applications/places/start-here

BOOKMARKS:
edit bookmarks:  actions/bookmarks-organize

TOOL:
open term:  apps/utilities-terminal
open as root: status/dialog-password
find files: actions/edit-find

**Comment by sixsixfive** [comment]
also the go button in the toolbar should be actions/go-jump;go-jump-rtl according to the naming spec

**Comment by tsujan** [comment]
I like icons but, nowadays, people search for ways of removing them from menus -- I dislike that but have implemented it in Kvantum. The current GUI is good for all; adding more icons might hurt some users' feelings ;)
