### ISSUE TITLE
Segfault when using `nvidia-libgl`

### ISSUE THREAD

**Issue by fenduru** [lxqt/pcmanfm-qt#284]
When I start my LXQt session, the desktop flashes a few times before displaying the error dialog "Desktop crashed too many times. Its autorestart has been disabled until next login."

Running `pcmanfm-qt` results in a segfault (which explains the desktop crashing)

This seems to only happen when using the `nvidia-libgl` package instead of the `mesa-libgl` (Arch Linux), and could possible be related to [this bug](https://bugs.archlinux.org/task/46064). Not positive that it is related though, so figured I'd file a bug here to be safe

**Comment by Ilya87** [comment]
1). Mentioned driver bug should be fixed in Nvidia driver version 361.18.
2). This bug appeared at application's exit, not start.
3). LXQt can work without pcmanfm-qt.
4). Paste log please.
