### ISSUE TITLE
polkit support?

### ISSUE THREAD

**Issue by ghost** [lxqt/pcmanfm-qt#286]
so I created a policy for pcmanfm (/usr/share/polkit-1/actions/org.lxqt.pkexec.pcmanfm.policy)

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC
 "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/PolicyKit/1/policyconfig.dtd">
<policyconfig>
  <action id="org.lxqt.pkexec.pcmanfm">
    <message>Authentication is required to run the PCMan File Manager</message>
    <icon_name>pcmanfm</icon_name>
    <defaults>
      <allow_any>auth_admin</allow_any>
      <allow_inactive>auth_admin</allow_inactive>
      <allow_active>auth_admin</allow_active>
    </defaults>
    <annotate key="org.freedesktop.policykit.exec.path">/usr/bin/pcmanfm-qt</annotate>
    <annotate key="org.freedesktop.policykit.exec.allow_gui">true</annotate>
  </action>
</policyconfig> 
```

this allows me to launch pcmanfm as root with pkexec from a terminal but it refuses to work if I use it in pcmanfms settings(replacing gksu %s with pkexec %s)

any chance to get this working without gksu/kdesu?

**Comment by PCMan** [comment]
Thank you for working on this. I always want to support that but I don't know how to use polkit. It will be cool if you can help.

**Comment by jbicha** [comment]
@PCMan gvfs 1.30 (available in Debian stretch, Ubuntu 17.04 Beta and generally in distros that provide GNOME 3.22) introduces a new admin backend.

Just prefix the path you want with `admin:///`

On Ubuntu, normal users cannot access `/root` but if you are an admin, you can navigate to `admin:///root/`

I don't have pcmanfm-qt installed so I haven't tried it there but it works in all the gtk3 apps I've tried.

**Comment by tsujan** [comment]
@jbicha 
Yes! With pcmanfm-qt,  `admin:///` wants the root password and provides the root access.

**Comment by tsujan** [comment]
We should add `admin:///` to the Places once pcmanfm-qt's development comes out of  its current hiatus. Thanks for the reminder!

**Comment by tsujan** [comment]
→ https://github.com/lxqt/pcmanfm-qt/issues/1265
