### ISSUE TITLE
Follow more system settings

### ISSUE THREAD

**Issue by goetzc** [lxqt/pcmanfm-qt#309]
PCManFM-qt should follow more system settings (I'm thinking about the LXQt ones), regarding:
- one or double mouse click
- default terminal

**Comment by tsujan** [comment]
I don't see this as an issue but a feature. LXQT is supposed to be modular as far as possible. PCManFM's settings are separate from those of LXQT for it to be usable outside LXQT too. The same is true for lximage-qt or any other app that comes under LXQT.

**Comment by goetzc** [comment]
Yes, sure, when pcmanfm-qt is running and a lxqt session is active, copy/use those settings. If not, the LXQt experience is confusing for the user.

**Comment by tsujan** [comment]
> when pcmanfm-qt is running and a lxqt session is active, copy/use those settings

I agree on this. A similar discussion started about setting wallpapers with lximage-qt under LXQT. The rule you mentioned is quite acceptable -- its implementation is another thing ;)

**Comment by palinek** [comment]
> The rule you mentioned is quite acceptable -- its implementation is another thing ;)

For singleclick, this should be quite easy: just to check if the `lxqt-qtplugin` is used and if so, don't handle the singleclick style hint by itself and for showing/storing the preference use *lxqt* settings file.

**Comment by pmattern** [comment]
Selecting FHS objects in a file manager by single click and next applying an action like moving by drag & drop or choosing a topic from a context menu is a pretty common approach. Considering the features to which the single click setting of lxqt-config-input applies it can hence very well make sense to have different settings in lxqt-config-input and PCManFM-Qt.
Thus I for one think the settings of lxqt-config-input should definitely not just inevitably get adopted by PCManFM-Qt.

How to eventually change the way the default terminal as well as default applications in general are dealt with is already discussed in lxde/lxqt#433.

**Comment by tsujan** [comment]
Having developed and used pcmanfm-qt for a long time, I think it's good that its has its own settings. Making it dependent on something else would clutter the code for no good reason.

**Comment by agaida** [comment]
@tsujan - it is not about depending on something - and with a grain of salt:
* Outside lxqt-session pcmanfm-qt need his own settings and an interface to set them
* Inside lxqt-session our settings should be used as far as possible, nearly perfect, but right now the part: "as far as possible" isn't reached yet.

**Comment by goetzc** [comment]
@tsujan from my point of view, it's not about having it's own settings, I find that great —like overwriting some global/general system settings— but about a consistent user experience as a whole, when using LXQt.

**Comment by tsujan** [comment]
I disagree. Consistency isn't sacred and shouldn't sacrifice practicality.

As a file manager, pcmanfm-qt doesn't need to follow any external settings for its icon size, spacings, double vs. single click, desktop font, etc. For example, item-view icon size has different and special meanings for a file manager. Or there is an auto-selection that doesn't have any meaning elsewhere. The default terminal doesn't make much sense outside pcmanfm-qt. And so on.

**Comment by tsujan** [comment]
More specifically:

You double click to open a folder and you double click to activate a view item in some Qt app: these are very different things and shouldn't follow the same rule. To a programmer, a "folder" shown by the view of a Qt file manager is a "view item" but technical terms are used only for technical purposes. I'm a programmer but, as a user, I never see a folder like a view-item.

What is requested here would be a bug to fix.

**Comment by goetzc** [comment]
> As a file manager, pcmanfm-qt doesn't need to follow any external settings

It's not about the FM, it's about the whole LXQt experience! When the FM runs inside the DE. 

Does LXQt have any official UX design guidelines? Do you follow/are inspired maybe by some parts of other DE, KDE, Gnome, macOS, Windows?

> I disagree. Consistency isn't sacred and shouldn't sacrifice practicality.

Practical for whom? I recommend you to read some UX design material, because you are also a user, however you don't think as one, but as a developer. The majority of people that are not computer-wise don't expect to change the same setting all over the place.

> What is requested here would be a bug to fix.

When I opened this, you didn't see this as a issue, but [as a feature](https://github.com/lxqt/pcmanfm-qt/issues/309#issuecomment-181117675), now your opinion changes and you close this?

It's not something personal for my benefit, I no longer use this, although I see some logical discrepancies, and discussion is something healthy for an F/OSS project. So why close this issue? Somebody might take it and draft a PR.

**Comment by tsujan** [comment]
> When I opened this, you didn't see this as a issue, but as a feature,

I intentionally started my comment by saying, "Having developed and used pcmanfm-qt *for a long time*." This issue was opened 3 years ago; so many things have changed since then.

> Do you follow/are inspired maybe by some parts of other DE, KDE, Gnome, macOS, Windows?

Get the good parts and ignore the bad parts. "Good" and "bad" don't have clear-cut definitions; our tastes are a determining factor. LXQt isn't a clone of any other DE, not even LXDE.

> I recommend you to read some UX design material,

You might not like this: **to me**, "UX design material" mostly consist of articles that reflect either the tastes of their writers or the "fashion". The hot anti-skeuomorphic "movement" is an example.

What's practical? We discuss it but not forever.

**Comment by tsujan** [comment]
For click, see https://github.com/lxqt/pcmanfm-qt/pull/1006.

For default terminal, read the last part of my comment [above](https://github.com/lxqt/pcmanfm-qt/issues/309#issuecomment-527669228) and also the first paragraph of https://github.com/lxqt/lxqt/issues/1382#issuecomment-342681920
