### ISSUE TITLE
Version number of libfm-qt CMake config file is incorrect

### ISSUE THREAD

**Issue by PCMan** [lxqt/pcmanfm-qt#321]
Currently, the version set in the cmake config file is 3.0.0.
However, this is the libtool-compatible ABI version info, not API version.
The API version is 0.11.0.

**Comment by PCMan** [comment]
@luis-pereira Would you please help fix this?
I know it looks weird, but I'm using libtool versioning for the ABI version (soname) here.
https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html
This version number is for ABI compatibility and is not related to API version.
Thank you.

**Comment by luis-pereira** [comment]
@PCMan I will try
CMake defines two properties for target: **VERSION** and **SOVERSION**.

> For shared libraries VERSION and SOVERSION can be used to specify the build version and API version respectively. When building or installing appropriate symlinks are created if the platform supports symlinks and the linker supports so-names. If only one of both is specified the missing is assumed to have the same version number. For executables VERSION can be used to specify the build version. When building or installing appropriate symlinks are created if the platform supports symlinks. For shared libraries and executables on Windows the VERSION attribute is parsed to extract a “major.minor” version number. These numbers are used as the image version of the binary.

On Linux it's mapped, by default, to a file and two symlinks:

libfoo.so.<VERSION>
libfoo.so.<SOVERSION> -> libfoo.so.<VERSION>
libfoo.so -> libfoo.so.<SOVERSION>

**Comment by agaida** [comment]
@pcman @luis-pereira - is this still an issue? If not please close
