### ISSUE TITLE
lxqt-panel menu and PCManFM menu:// are inconsistent

### ISSUE THREAD

**Issue by RalfJung** [lxqt/pcmanfm-qt#329]
These two screenshots pretty much say it all:

![screenshot from 2016-03-19 17-47-38](https://cloud.githubusercontent.com/assets/330628/13899968/43399072-edfb-11e5-8657-e125ef676115.png)

SuperMeatBoy is missing in PCManFM.

![screenshot from 2016-03-19 17-48-25](https://cloud.githubusercontent.com/assets/330628/13899970/475c1666-edfb-11e5-98d6-3f41cb66ba6b.png)

A lot of duplicate entries, Thunderbird, Audiosurf, Eclipse... are missing in PCManFM.

This is with LxQt 0.10 on Debian.

**Comment by hackbyte** [comment]
It is also still existing with pcmanfm v0.13.0 on rolling release funtoo.

**Comment by tsujan** [comment]
> It is also still existing with pcmanfm v0.13.0 on rolling release funtoo.

Although 0.13.0 is outdated, this difference might continue, as there's no plan for removing it. Panel and pcmanfm-qt have completely different codes and the latter can be used outside LXQt.

That being said, this report isn't closed.

**Comment by tsujan** [comment]
There has been no relation between panel and pcmanfm-qt in the first place, and no relation is supposed to be made — not by pcmanfm-qt/libfm-qt, at least. Hence closing.
