### ISSUE TITLE
Main Toolbar: approaches to toggle display should be improved

### ISSUE THREAD

**Issue by pmattern** [lxqt/pcmanfm-qt#337]
An item to toggle the display of "Main Toolbar" is missing in menu "View" and should be added, similar to the ones of the menu and filter bar at the menu's bottom.

The current handling to toggle the display of "Main Toolbar" seems questionable.
If I'm not mistaken the only way is from a context menu that can be opened over the menu bar (!) only and comprises that single topic only which is a bit confusing, IMO.
I think this context menu should also come up over the Toolbar itself as long as it's visible or, maybe better, just get dropped altogether. Assuming a topic gets added to menu "View" as suggested above this wouldn't do any harm but rather be consistent with the menu and filter bar, wouldn't it?

**Comment by tsujan** [comment]
> If I'm not mistaken the only way is from a context menu that can be opened over the menu bar

It's not in the code but added by Qt to every toolbar.

**Comment by npmiller** [comment]
As @tsujan said the menu, and the possibility of hiding the main toolbar actually comes from the way Qt deals with toolbars, I don't think it was purposefully put in there. I also can't think of a good use case for hiding the main toolbar, it seems particularly inconvenient and confusing.

So instead of improving this feature I'd rather just remove it altogether, what do you guys think?

**Comment by tsujan** [comment]
> I also can't think of a good use case for hiding the main toolbar

me neither.

> So instead of improving this feature I'd rather just remove it altogether, what do you guys think?

I agree, although, IMO, it's just a harmless little menu that can be left as it is.

**Comment by pmattern** [comment]
While I'll personally hardly ever hide the toolbar PCManFM (GTK flavour) does allow for hiding as well, albeit from its Menu "View" only. Qt web browsers Otter Browser and QupZilla allow for toggling the display of their counterpart, too, both from their menu "View" and a context menu of the menu bar which is a bit more sophisticated in these browsers.
Maybe omitting the toolbar on not so large displays could be an argument in favour of hiding.

So all in all I still think it should be possible to toggle the display of the "Main Toolbar" from menu "View" and am in fact wondering whether it wouldn't even make sense to extend the context menu of PCManFM-Qt's menu bar to be a bit more like the ones of Otter Browser and QupZilla.

**Comment by tsujan** [comment]
> ... and a context menu of the menu bar

That context menu is shared between their toolbar and menubar; right clicking on an empty space on the toolbar is just a little harder.

> wondering whether it wouldn't even make sense to extend the context menu of PCManFM-Qt's menu bar to be a bit more like the ones of Otter Browser and QupZilla.

Web browsers usually have multiple toolbars, hence it makes sense for them to have a context menu for hiding some of them. But who wants to hide PCManFM's toolbar with its location bar?

**Comment by tsujan** [comment]
The context menu has been removed for a long time.
