### ISSUE TITLE
Allow shell patterns to be set as filter text

### ISSUE THREAD

**Issue by sammoth** [lxqt/pcmanfm-qt#340]
In both gtk versions of pcmanfm, the filter feature supports shell patterns such as *.[^txt] to hide all text files, etc. In pcmanfm-qt the filter is a simple string match and is less useful. Would it be possible to support this feature?

**Comment by tsujan** [comment]
> Would it be possible to support this feature?

It's possible but not desirable. The purpose of filterbar is easily and quickly filtering actual filenames, regardless of capital or small letters. For other purposes, the search utility can be used, which supports regexp, among other advanced options.

**Comment by tsujan** [comment]
Oh, I found a problem in the search utility: In regexp, the string that filters *out* `.txt` files is `(?!.txt)` but it doesn't work -- while `(?=.txt)` works for *showing* `.txt` files.

**Comment by sammoth** [comment]
Thanks but that doesn't seem as useful. Before you could set a shell pattern filter and navigate through directories with a filtered view onto them that was maintained until you elected to change it. This is no longer possible using the filter bar or the search feature because the filter is not kept when changing directory and it does not support patterns.

**Comment by tsujan** [comment]
> Thanks but that doesn't seem as useful.

The usage you first wanted was filtering `.txt` files and, as I explained, it's possible with the search utility. What you say *now* is about another usage.

> Before you could ... This is no longer possible....

This is about two separate feature requests: (1) locking the filter string; and (2) shell pattern in the filter bar. IMO, the former could be a good feature but the latter would be a duplication, considering the fact that what you want is *too* specific.

**Comment by tsujan** [comment]
Not a good report to remain open. Locking the filter string may be good but this isn't about it -- I might open an issue about it later.
