### ISSUE TITLE
Adding menu entry for direct access to search

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#348]
What about a .desktop file nel menu for opening the search menu usually opened by F3? 
Tested and working:

[Desktop Entry]
Type=Application
Name=File search
GenericName=File search
Comment=Search for files and content
Exec=pcmanfm-qt %U -f
MimeType=inode/directory;
Icon=search
Categories=FileManager;Utility;Core;Qt;
StartupNotify=true

**Comment by tsujan** [comment]
`F3` adds the current directory for search. Moreover, the search dialog is integrated into file manager and is closed after search.
