### ISSUE TITLE
Add sorting by deletion date inside Trash

### ISSUE THREAD

**Issue by jimbo1qaz** [lxqt/pcmanfm-qt#367]
Ubuntu Studio 16.04 with Cinnamon and Lubuntu Daily PPA:

Right now, when I trash one or more files, pcmanfm does not record the "trashed" date.

When opening the trash, pcmanfm does not allow you to "sort by date trashed". Nemo's "sort by date trashed" also does not work. This suggests that Nemo touches the "modified" date when a file is trashed, then displays it as "date trashed".

Can you add functionality to store, display, and allow sorting by date trashed?

**Comment by pmattern** [comment]
Tbh. this seems like a rather weird idea to me as the only purpose I can figure is doing some kind of version control that way which should probably be some other means.
But maybe I'm missing something, so...

**Comment by tsujan** [comment]
@jimbo1qaz 
This would be possible with https://github.com/lxde/pcmanfm-qt/pull/343 and also by adding a sorting according to creation time, I guess. But what would its use be -- I mean a general use that wouldn't be specific to your personal needs?

**Comment by jimbo1qaz** [comment]
When I enter the trash can, I usually want to restore the last few files
I've been deleting. Right now, I don't know which files are recently
deleted, and which ones are ancient.

Also, both Windows and Nemo already supports this feature.

**Comment by tsujan** [comment]
> .... I usually want to restore the last few files I've been deleting...

That was already obvious but what could the benefit of restoring recently deleted files be when the user doesn't know exactly which file he/she wants to restore and, especially, *where*?

**Comment by jimbo1qaz** [comment]
Sometimes I delete a large number of files from one folder, and want to
restore them all. This is easiest with "sort by date deleted" and an
"original location" column.

**Comment by tsujan** [comment]
Info on the original location in the properties dialog and/or as a column in the detailed list view is a good idea but I'm not convinced by your argument about sorting. Let's wait for what others might say!

**Comment by tsujan** [comment]
There's no "record date" in Linux anyhow. Closing.

**Comment by jimbo1qaz** [comment]
KDE Dolphin's trash also has a deletion time column (I think it's not shown by default, but it exists). This is factually inaccurate, unless pcmanfm-qt doesn't record deletion time whereas other file managers store that as metadata.

Dolphin stores metadata in `~/.local/share/Trash/info/file.trashinfo`. It seems to be a XDG standard: https://askubuntu.com/a/102106

Note that I no longer use lxqt/pcmanfm-qt.

**Comment by tsujan** [comment]
> KDE Dolphin's trash also has a deletion time column (I think it's not shown by default, but it exists)

It doesn't.

**Comment by jimbo1qaz** [comment]
![image](https://user-images.githubusercontent.com/913957/53346580-2662be00-38cc-11e9-8a75-a385c8f28b95.png)
Dolphin hides the option well:
- Menu bar: "View/Additional Information/Other/Deletion Time"
- Right-click column headers, "Other/Deletion Time"

**Comment by tsujan** [comment]
Oh, yes -- it's very hidden.

It's specific to trash and isn't what you called "record date", which doesn't exist.

Reserving an additional column for trash and hiding it for other folders is possible but isn't worth the effort for just this special use case. I waited but no one wanted it since Jun 26, 2016.

**Comment by jimbo1qaz** [comment]
Dolphin and Windows allows me to enable per-folder sorting and column visibility, and manually "promote to global" if I feel like it. (Dolphin allows choosing between "current folder", "including all sub-folders", or "all folders", while I think Windows only? allows "current folder".)

![image](https://user-images.githubusercontent.com/913957/53347413-ddac0480-38cd-11e9-928d-acf5d5a4e18c.png)

But I'm no longer using pcmanfm-qt, and if nobody else wants this, you don't have to implement it.

**Comment by tsujan** [comment]
> Dolphin and Windows allow me to set per-folder sorting and column visibility,

pcmanfm-qt does so too but, since you don't use it, let's not waste your and my time with a futile discussion.

**Comment by tsujan** [comment]
I found a use case for this: when you trash more than 2 files/folders with the same name, you might want to untrash the last/first one.

It seems possible to do but with a little headache.

@agaida If you find the above-mentioned use case important, please reopen this! I can't say it's important or worth the hassle but a second opinion would be good.

**Comment by jimbo1qaz** [comment]
Not sure if I mentioned, but my use cases for this are:

- when I delete many (2-20+) files at once, sometimes I change my mind and want to restore them simultaneously.
- Sometimes when browsing through deleted items, I want to categorize the trash can into groups of "related files" deleted at the same time. When scrolling through history, if I deleted a few hundred similar files at once, I want to restore or skip them as a group, instead of them being possibly scattered by name or original date.
- I've also used "sort by date" to look through my older trash entries and delete everything older than a specific date (while checking for things I want to keep).

**Comment by tsujan** [comment]
> delete everything older than a specific date

This is a valid use case too. Reopening...

**Comment by tsujan** [comment]
OK, it is possible:

![deletion_time](https://user-images.githubusercontent.com/981076/56422367-355a6100-62bc-11e9-8764-bc91a816a355.png)

But there's a long way until it's completed:

(1) I should think of the best way of fetching the info (here, I added "trash::deletion-date" to attributes that our file info gets).
(2) It's column should be shown only inside Trash (otherwise, it'll be empty). That creates complications.
(3) If it's going to be also added to the right click Sorting submenu inside Trash (or to pcmanfm-qt's Sorting submenu), there will be more complications.

This will take time.

**Comment by tsujan** [comment]
Done, in a consistent way. Waiting for a conflicting PR to be merged.
