### ISSUE TITLE
Add "Show thumbnails" option to view menu

### ISSUE THREAD

**Issue by SafaAlfulaij** [lxqt/pcmanfm-qt#375]
Sometimes I don't need thumbnails to be shown for a particular folder (That is full with SVG pictures -> Waste CPU).
Maybe an option in the view menu with a shortcut be better than disabling/enabling thumbnails from settings everytime?

**Comment by tsujan** [comment]
This feature request from 2016 is practical, IMO. But its implementation needs several changes to libfm-qt and pcmanfm-qt. So, I'll try to implement it before 2061.

**Comment by tsujan** [comment]
My bad! it was as simple as https://github.com/lxqt/pcmanfm-qt/pull/988
