### ISSUE TITLE
Setting different wallpaper for different desktops?

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#384]
No idea if this is hard to code, but it's a feature many user would like, as shown in the [discussion/bug report ](https://bugs.kde.org/show_bug.cgi?id=343246) when KDE removed it.

**Comment by tsujan** [comment]
Practically, this isn't possible yet because virtual desktops are defined differently by X11 compositors and who knows what will happen with wayland.

**Comment by tsujan** [comment]
Since LXQt is independent of all compositors and WMs and because wayland is still so poor in features compared to X11, leaving this open wouldn't make sense.
