### ISSUE TITLE
pcmanfm-qt fails to unmount curlftpfs mounts 

### ISSUE THREAD

**Issue by alex3kov** [lxqt/pcmanfm-qt#411]
pcmanfm-qt 0.11.1 treats curlftpfs mounts as usual mounts and tries (I'm guessing) to unmount them with `umount` command, failing with "Permission denied". Curlftpfs mounts should be unmounted with `fusermount -u` command as regular user. This may be the case for other (fuse?) types of mounts as well, I don't know.  
_Proposed solution:_  
Make pcmanfm more adaptive - when "eject" icon is clicked pcmanfm should detect the type of the mount and issue appropriate command.
_Steps to reproduce:_  
1) Install curlftpfs, mount remote FTP directory to a local one like so:
```sh
$ curlftpfs -o user=USER:PASS ftp.server.com localdirectory
```
2) Confirm that it is mounted with "fuse" type:
```sh
$ mount | grep curlftpfs
curlftpfs#ftp://ftp.server.com/ on /home/username/localdirectory type fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=100)
```
3) Open pcmanfm-qt, see the FTP mount in "Places"
4) Try to unmount it by clicking "eject" icon, get "Permission denied" error message. Issue `fusermount -u /home/username/localdirectory` in terminal, successfully unmount curlftpfs mount as the same regular user that's running pcmanfm-qt.

**Comment by tsujan** [comment]
Definitely not a problem anymore.
