### ISSUE TITLE
Benchmark: Test performance of QMimeDatabase

### ISSUE THREAD

**Issue by PCMan** [lxqt/pcmanfm-qt#415]
Since Qt now provides some more xdg features which used to be supported by glib/gio only, it's good to evaluate its performance so we can know the performance impact if we replace some glib/C code with Qt/C++.

The test is simple. Enumerating a large directory recursively and try to detect the mime type of every file found. All directory enumerating code is written in plain POSIX APIs to avoid the overhead of QDir.
The directory tested is "android 5.0 source tree" which contains 496, 090 files and has a size of 30 GB.

Results:

* QMimeDatabase (cold start; after drop_caches)
 real	3m0.872s
 user	0m27.133s
 sys	0m7.617s
* QMimeDatabase (run again; already have filesystem cache)
 real	0m18.668s
 user	0m17.117s
 sys	0m1.537s
* glib/gio GFileInfo (cold start; after drop_caches)
 real	2m51.265s
 user	0m12.403s
 sys	0m8.823s
* glib/gio GFileInfo (run again; already have filesystem cache)
 real	0m8.421s
 user	0m6.420s
 sys	0m1.987s

Apparently, the Qt implementation is much slower than the gio one. Calling QMimeDatabase::mimeTypeForFile() with QMimeDatabase::MatchDefault which reads file content is even slower (Reading file content with POSIX open()/read() without using QIODevice already saved some time, but Qt is still slow. :-( So for now, it's a good idea to keep using glib/gio for this task.

The full source code tested.
```c++
#include <glib.h>
#include <gio/gio.h>

#include <QCoreApplication>
#include <QMimeDatabase>
#include <QMimeType>
#include <QDebug>

#include <sys/types.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/fcntl.h>
#include <unistd.h>
#include <dirent.h>
#include <string.h>

#define GIO

static QMimeDatabase mimeDB;

void detectMime(const char* dirPath) {
    DIR* dir = opendir(dirPath);
    if(dir) {
        while(struct dirent* ent = readdir(dir)) {
            if(strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
                continue;
            char* filePath = g_build_filename(dirPath, ent->d_name, nullptr);
#ifndef GIO
            auto mimeType = mimeDB.mimeTypeForFile(ent->d_name, QMimeDatabase::MatchExtension);
            if(mimeType.isDefault()) {
                char buf[4096];
                int fd = open(filePath, O_RDONLY);
                size_t len = read(fd, buf, 4096);
                close(fd);
                mimeType = mimeDB.mimeTypeForData(QByteArray::fromRawData(buf, len));
            }
            // qDebug() << ent->d_name << ": " << mimeType.name();
#else
            GFile* gf = g_file_new_for_path(filePath);
            GFileInfo* fi = g_file_query_info(gf, G_FILE_ATTRIBUTE_STANDARD_CONTENT_TYPE, G_FILE_QUERY_INFO_NONE, NULL, NULL);
            if(fi) {
                // qDebug() << g_file_info_get_attribute_string(fi, G_FILE_ATTRIBUTE_STANDARD_CONTENT_TYPE);
                g_object_unref(fi);
            }
            g_object_unref(gf);
#endif

            struct stat st;
            lstat(filePath, &st);
            if(S_ISDIR(st.st_mode))
                detectMime(filePath);
            g_free(filePath);
        }
        closedir(dir);
    }
}

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    if(argc < 2)
        return 1;
    detectMime(argv[1]);
    return 0;
}
```

**Comment by tsujan** [comment]
> So for now, it's a good idea to keep using glib/gio for this task.

I agree completely.

**Comment by PCMan** [comment]
More tests by also getting the descriptions and the icons of the mime-types at the same time, which is the use case of file managers. So unfortunate that Qt is even much slower in this case.
While Qt lovers tend to use Qt for everything whenever possible, I prefer use it for UI only and handle other parts with other libraries.

The glib/gio version:
* Cold start
 real	2m57.181s
 user	0m16.137s
 sys	0m9.097s
* Run again
 real	0m10.851s
 user	0m8.737s
 sys	0m2.073s

The Qt version:
* Cold start:
 real	4m27.334s
 user	1m47.030s
 sys	0m12.487s
* Run again:
 real	1m26.842s
 user	1m21.620s
 sys	0m5.190s

The full code for the tests:
```
#include <glib.h>
#include <gio/gio.h>

#include <QCoreApplication>
#include <QMimeDatabase>
#include <QMimeType>
#include <QDebug>

#include <sys/types.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/fcntl.h>
#include <unistd.h>
#include <dirent.h>
#include <string.h>

// #define GIO

static QMimeDatabase mimeDB;

void detectMime(const char* dirPath) {
    DIR* dir = opendir(dirPath);
    if(dir) {
        while(struct dirent* ent = readdir(dir)) {
            if(strcmp(ent->d_name, ".") == 0 || strcmp(ent->d_name, "..") == 0)
                continue;
            char* filePath = g_build_filename(dirPath, ent->d_name, nullptr);
#ifndef GIO
            auto mimeType = mimeDB.mimeTypeForFile(ent->d_name, QMimeDatabase::MatchExtension);
            if(mimeType.isDefault()) {
                char buf[4096];
                int fd = open(filePath, O_RDONLY);
                size_t len = read(fd, buf, 4096);
                close(fd);
                mimeType = mimeDB.mimeTypeForData(QByteArray::fromRawData(buf, len));
            }
            QString iconName = mimeType.iconName();
            QString comment = mimeType.comment();
            // qDebug() << ent->d_name << ": " << mimeType.name();
#else
            GFile* gf = g_file_new_for_path(filePath);
            GFileInfo* fi = g_file_query_info(gf, G_FILE_ATTRIBUTE_STANDARD_CONTENT_TYPE, G_FILE_QUERY_INFO_NONE, NULL, NULL);
            if(fi) {
                const char* mimeType = g_file_info_get_attribute_string(fi, G_FILE_ATTRIBUTE_STANDARD_CONTENT_TYPE);
                char* comment = g_content_type_get_description(mimeType);
                g_free(comment);
                GIcon* icon = g_content_type_get_icon(mimeType);
                g_object_unref(icon);
                g_object_unref(fi);
            }
            g_object_unref(gf);
#endif

            struct stat st;
            lstat(filePath, &st);
            if(S_ISDIR(st.st_mode))
                detectMime(filePath);
            g_free(filePath);
        }
        closedir(dir);
    }
}

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);
    if(argc < 2)
        return 1;
    detectMime(argv[1]);
    return 0;
}
```

**Comment by palinek** [comment]
I'm not able to make any tests now, but just looking at the code...
Is the provided benchmark code ok? IMO here you don't provide the the full filename to the `QMimeDatabase::mimeTypeForFile()`
```c++
            auto mimeType = mimeDB.mimeTypeForFile(ent->d_name, QMimeDatabase::MatchExtension);
```

Or do I miss/mess something?

**Comment by palinek** [comment]
Note: @PCMan I've updated your posts to use markdown for syntax highlighting _\`\`\`c++_

**Comment by PCMan** [comment]
@palinek I tried full file path first and it's painfully slow. (using QMimeDatabase::MatchDefault)
So I split it into two parts.
1. Try matching filename pattern first (with the QMimeDatabase::MatchExtension flag)
2. If the mime-type cannot be determined with filename only, read the first block of the file content and do further detection.

**Comment by palinek** [comment]
I see...

**Comment by tsujan** [comment]
Nothing to do here.
