### ISSUE TITLE
Remove the Advanced tab of Desktop Preferences

### ISSUE THREAD

**Issue by scootergrisen** [lxqt/pcmanfm-qt#425]
Seems "Show menus provided by window managers when desktop is clicked" does the opposit of what the string says.

**Comment by tsujan** [comment]
Could you be more specific please?

**Comment by scootergrisen** [comment]
Right click desktop and select desktop preferences and advanced tab.

**Comment by tsujan** [comment]
It shows OpenBox's menu and it isn't supposed to work with all WMs.

So, I click on the "Close and comment" button.

**Comment by scootergrisen** [comment]
I don't know what OpenBox is but it works when i select/deselect the checkbox. Just the opposit way.

**Comment by tsujan** [comment]
OpenBox is the window manager recommended by LXQt. KWin is another recommended WM.

Which WM do you use and what do yo mean by "the opposite way"? With Openbox, when it's unchecked, pcmanfm-qt's menu will be shown on right clicking the desktop; when it's checked, Openbox's menu will pop up. Logically, when you use the word "opposite", "checked" and "unchecked" should be interchanged with each other in the previous statement. Is it so?

Without you being specific, your report wouldn't be of much help.

**Comment by scootergrisen** [comment]
I don't know what i use so i guess the default.
Using Debian testing.

If "Show menus provided by window managers when desktop is clicked" is **checked** nothing happens when right clicking the desktop.

If "Show menus provided by window managers when desktop is clicked" is **unchecked** i get the context if i right click the desktop.

**Comment by tsujan** [comment]
> If "Show menus provided by window managers when desktop is clicked" is unchecked i get the context menu if i right click the desktop.

That menu belongs to pcmanfm-qt (the file manager), *not to the window manager*. So, the checkbox works as expected. When you *check* it, nothing happens on right clicking the desktop because you don't have OpenBox. As I said above, it doesn't work with all WMs and, IMO, it isn't useful with OpenBox either. Just ignore it!

**Comment by scootergrisen** [comment]
Ok.
Its a bit confusing for a new user that don't know all this stuff.
Maybe there should not be advanced settings there to confuse new users, maybe move it some place with other advanced settings. Just an idea.

**Comment by tsujan** [comment]
> Its a bit confusing for a new user that don't know all this stuff.

I agree. As I said above, it's not useful with OpenBox either. However, we have to know the opinions of others too. So, I reopen this issue but change its title.

**Comment by pmattern** [comment]
As pointed out above the checkbox is basically exactly behaving as expected. The confusing part is that not all window managers are providing context menus within LXQt sessions, e. g. Xfwm even besides it does provide context menus if run within an Xfce session.
Maybe we should make this checkbox available only when a window manager is in use which does provide context menus. Not sure whether this would be worth the effort, though.

A tab providing a single item only is rather pointless. So I'd also vote for moving this item to tab "General". (As discussed in #423 this would not mean a single tab only is left, which would make using tabs pointless in the first place.)

Right now the Openbox menu which comes up on middle-click is the only means I'm aware of to get an overview of all applications running on the various virtual desktops, see lxde/lxqt#469.
So the context menus of Openbox are pretty much useful, IMO.

**Comment by agaida** [comment]
@tsujan - i would merge Diashow and  Advanced into Advanced

**Comment by tsujan** [comment]
@agaida The Advanced tab is very different from the others and has no practical value. The other settings -- slide-show included -- aren't related to the concept of "advanced". IMO, it's better to remove the Advanced tab altogether. Really, what's its use?

**Comment by tsujan** [comment]
If the Advanced tab should be kept (for future), putting the slide-show and WM menu under the same tab is wrong, IMO. Moreover, tabs don't waste space.

For now, showing the LXQt menu as the right-click menu seems far from possible.

**Comment by agaida** [comment]
ok, we will not remove, used for desktop icons

**Comment by tsujan** [comment]
> ok, we will not remove, used for desktop icons

Oh, I forgot to close this. Thanks!
