### ISSUE TITLE
Filterbar undo history is lost on changing tabs

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#455]
As the title says, Ctrl+Z won't have effect for the filterbar if there is history but the tab is changed. The reason is simple:  `QLineEdit::setText()` clears the undo/redo history.

While working on Dolphin, I saw that it kept its filterbar history. So, this can be seen as a (minor) bug in pcmanfm-qt.

EDIT: The true reason is the structure of the main window; there's a single filterbar shared by all tabs.

**Comment by pmattern** [comment]
This makes me wonder whether the expected effect of `Ctrl+Z` is explained somewhere in the GUI in the first place?

**Comment by tsujan** [comment]
`Ctrl+Z` and `Ctrl+Shift+Z` are always enabled by default in line-edits of any app.

Compared to https://github.com/lxde/pcmanfm-qt/issues/456, this is a very minor issue in a file manager and can be safely ignored, IMO.
