### ISSUE TITLE
Add an option for showing filenames of desktop files

### ISSUE THREAD

**Issue by dglent** [lxqt/pcmanfm-qt#472]
If i have 5 different desktop files in a folder with the same name in the NAME section of the file, i cannot know which file is what.
Is there any way to show somehow the filename instead of the application's name?

**Comment by MggMuggins** [comment]
This is not only an issue with PCManFM, and it happens in just about every other manager. I think it's probably a Linux thing, and I don't know how much it can be helped. Although there may be something...

**Comment by AcarBurak** [comment]
@MggMuggins No, some show filenames; spacefm, for instance, I guess.

**Comment by tsujan** [comment]
@dglent 

Your case is very special. Usually, either icons or names are different, unless those desktop files aren't supposed to be used inside a folder but as menu items or "open with" items.

Doing this in pcmanfm-qt will be easy once it's made independent of libfm. However, I don't think there's an agreement about it. Dolphin does it but many file managers don't. Personally, I don't like the way Dolphin shows desktop files.

As for the security, a patch was made after the discussion at https://github.com/lxde/pcmanfm-qt/issues/449 but it won't be needed when pcmanfm-qt becomes independent of libfm.

**Comment by dglent** [comment]
The need comes when developing/packaging you may need different desktop files for each platform/environments .... 
When you have them in the same folder you cannot work with them in pcmanfm.
I used to use konqueror and i could see the filenames in desktop files.
Now i saw also the issue #449 and it confirms that there is a need to add this on the future versions (especially when pacmanfm will become independent). 

I left KDE for the simplicity of LXQt but i don't like the user oriented things, things which supposed to help but in reality they hide the real life from the people (even for the simple users is not good)

**Comment by tsujan** [comment]
> Now i saw also the issue #449 and it confirms that there is a need to add this on the future versions 

https://github.com/lxde/pcmanfm-qt/issues/449 isn't about this but about a prompt, which is implemented, although not released yet.

**Comment by dglent** [comment]
> #449 isn't about this but about a prompt, which is implemented, although not released yet.

#449 is strongly related and linked with this. You click on a file Image.png because you suppose that the filemanager is reliable and shows you the real filename.

**Comment by palinek** [comment]
I also don't like showing the `Name=` of .desktop files in file managers. I mean the file manager isn't a applications-start-menu and I expect to know/see the real name of each item I see in FM.
Of course there are users which thinks the other way round and want to honor the XDG spec.

So this should be configurable, IMO.

**Comment by tsujan** [comment]
> #449 is strongly related and linked with this. You click on a file Image.png because you suppose that the filemanager is reliable and shows you the real filename.

I don't follow; when there's a prompt (as there will be), there's no danger: you could open it in a text editor by clicking on it. And why do you insist on *executing* several desktop files with the same name and the same icon? You could open them instead.

> So this should be configurable, IMO.

@palinek, I agree. Such things could be implemented more easily after @PCMan's PR's are merged. At least, I won't need to wait with a libfm PR for years :)

**Comment by dglent** [comment]
> I don't follow; when there's a prompt (as there will be), there's no danger: you could open it in a text editor by clicking on it. And why do you insist on executing several desktop files with the same name and the same icon? You could open them instead.

Imagine that you work on a project with multiple desktop file names.
FOR_WINDOWS_project.desktop
FOR_MAC_project.desktop
FOR_QT_project.desktop

And i want to edit a file. It is impossible to know which file i'm working on even with right click on it.

**Comment by tsujan** [comment]
@dglent 
As I said above, I'm not against this as an option.

**Comment by MggMuggins** [comment]
I wonder if this could be configurable for different directories. For example, /usr/share/applications and ~/.local/share/applications (the default locations for .desktop files) would show the name of the file instead of the Name field in the file. However, anywhere other than these directories, it would show the name field. That way you could do some kind of application launcher, while also being able to do the things that you need to do with desktop files.

**Comment by tsujan** [comment]
@MggMuggins 
Technically, this is about a GLib function, namely `g_file_info_get_display_name()`. pcmanfm-qt uses GLib (IMO, this is one of its advantages over Dolphin) and inherits the display name, in contrast to the real name, for desktop files. It is possible to use `g_file_info_get_name()` everywhere. How this can be implemented as an option is another problem.

Using display name somewhere and real name elsewhere isn't an option.

**Comment by tsujan** [comment]
Let's do this by adding an option to Preferences → Display → User Interface.

BTW, "User Interface" is repeated in Preferences; something should also be done about that.

**Comment by tsujan** [comment]
Done in https://github.com/lxqt/libfm-qt/pull/194 and https://github.com/lxqt/pcmanfm-qt/pull/680 , in this order.
