### ISSUE TITLE
Some files should NOT be executed at all

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#492]
When a JPG image, for example, is made executable, pcmanfm-qt doesn't try to execute it when it's clicked but opens it in the default image viewer. That's the correct behavior. However, for some file types -- m3u (audio/x-mpegurl), for example -- pcmanfm-qt does try to execute them.

The expected behavior is that pcmanfm-qt should never try to execute file types whose execution is meaningless.

**Comment by fulalas** [comment]
We can also add to this list subrip (.srt) file. If you execute it a weird thing happens: a lot of new text files are generated, and, of course, it isn't opened.

**Comment by tsujan** [comment]
@fulalas Thanks! With that, the bug can be considered to be more serious.

**Comment by tsujan** [comment]
This should wait until the related code is completely in `libfm-qt` instead of `libm`.

**Comment by tsujan** [comment]
This was fixed a long time ago, as a result of other changes.
