### ISSUE TITLE
Default settings/visual improvements

### ISSUE THREAD

**Issue by fulalas** [lxqt/pcmanfm-qt#493]
1- Put a small '+' icon besides/over the file icon when dragging it with CTRL pressed, indicating that we're copying rather than moving;
2- If you press the keyboard key equivalent to mouse right click, the context menu appears aligned to the mouse cursor current position instead of where the file selection is;
3- Make search case insensitive and recursive by default;
4- Add 'open destination' on search results dialog;
5- When removing a single file, show its path and name on the confirmation dialog;
6- When removing multiple files, show the amount on the confirmation dialog;

**Comment by tsujan** [comment]
No comment...
