### ISSUE TITLE
Rarely shows nonexistent files or doesn't show existing ones

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#508]
Although very rarely, the latest git version of pcmanfm-qt sometimes doesn't update the folder contents properly and shows files that don't exist. Reloading the folder fixes the issue.

A "change" signal may still be missing.

**Comment by tsujan** [comment]
Although pcmanfm-qt has become quite stable, this still happens but so rarely that I can't track it. Maybe the code should be reread line by line.

**Comment by tsujan** [comment]
OK, this is more serious than I thought (but not too much). After 2 months I encountered 2 cases of it, the second one was very weird because I made a folder that wasn't shown even after reloading; changing the directory twice was needed for it to be visible.

Will try to find the cause(s).

**Comment by tsujan** [comment]
New info: Items that correspond to nonexistent files are selectable!

**Comment by tsujan** [comment]
Attacked this again. I think it'll be fixed by preventing files from being queued for changes when they're already queued for deletion; will test that for a month.

**Comment by agaida** [comment]
GTM

**Comment by tsujan** [comment]
The bitter (or ridiculous) truth is that, although https://github.com/lxde/libfm-qt/pull/135 is OK, the problem of nonexistent files isn't fixed completely. A visual proof:

![nonexistent](https://user-images.githubusercontent.com/981076/33236501-2a7970b0-d26b-11e7-893d-87e07598c6a2.png)

In the above screenshot, "glib2.0_2.54.2.orig.tar.xz" is completely downloaded by QupZilla and "glib2.0_2.54.2.orig.tar.xz.download" does NOT exist anymore -- it'll disappear by a simple reloading.

Maybe, we should also handle `G_FILE_MONITOR_EVENT_MOVED` in `glib` → `gio` → `kqueue` → `kqueue-helper.c`. Contrary to Qt doc, GLib documentation is terrible...

**Comment by tsujan** [comment]
Yesterday, I examined `folder.c` several times. Today, I did other examinations and tests. My conclusion is that `folder.c` is OK: all file monitor events are handled correctly. If that's true, this should be about a bug in `GFileMonitor` itself -- on rare occasions, `G_FILE_MONITOR_EVENT_DELETED` may be missing -- but if not, something should be in front of my eyes and I can't see it.

**Comment by tsujan** [comment]
Found a tiny thing in `folder.cpp`, which may be the cause. I'll try a fix for 3 weeks and, if successful, will make a PR because this seems like a heisenbug: when I add `qDebug()` to check the file monitor events, the issue doesn't show up.

**Comment by tsujan** [comment]
It works! The current logic of deleting files is deeply incorrect but results in correct deletions most of the time just because the probability of multiple queues before info processing is low... will make a PR soon.

**Comment by agaida** [comment]
Nice. GTM

**Comment by tsujan** [comment]
Maybe no one is more sorry than I am now ;) This started to happen again: I edit and save a file with Qt Designer, while its containing folder is opened in pcmanfm-qt, and XXX.ui.bak is visible sometimes, although it doesn't exist.

It should be a regression.
