### ISSUE TITLE
Shift+Delete takes a while to delete heavy folders

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#539]
##### Expected Behavior
`Shift+Delete` works fast in Dolphin so it's reasonable to expect the same thing from pcmanfm-qt.

##### Current Behavior
If a folder is heavy and contains many files, `Shift+Delete` shows a dialog and takes a while to delete that folder.

##### Possible Solution
I should look into the code first.

##### Steps to Reproduce

1. Choose a heavy folder (> 200Mb) with many files.
2. Use `Shift+Delete` while it's selected.
3. A dialog will pop up, showing the process and the folder will be deleted after a while but Dolphin does the same thing fast. Moreover, pcmanfm-qt deletes the contents of Trash almost instantly.

##### System Information

* Everything latest git.

**Comment by tsujan** [comment]
Probably this isn't specific to file deletion but happens anywhere a progress dialog is shown -- for example, while overwriting files.

**Comment by tsujan** [comment]
To delete a directory (with `g_file_delete()`), first its contents should be deleted. In other words, `Shift+Delete` should do the job recursively; hence the delay for heavy folders.

As far as I know, there's no other way (in GLib).

**Comment by es20490446e** [comment]
Then don't use GLib for that particular operation. Even calling "rm -r" or "mv -r" directly would be better.

The only thing you would be giving up is listing, at the expense of tenths of times of speed gain.

**Comment by tsujan** [comment]
> The only thing you would be giving up is listing...

It isn't that simple at all.
