### ISSUE TITLE
Crash on copying file to USB stick -- and more

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#555]
When I try to copy a file with `:` in its name (like `test:1`) to a USB stick, pcmanfm-qt crashes with this backtrace:
```
#0  0x00007f99b8044280 in QIcon::isNull() const () at /usr/lib/libQt5Gui.so.5
#1  0x00007f99b90def31 in Fm::IconInfo::qicon() const () at /usr/lib/libfm-qt.so.3
#2  0x00007f99b9141c5c in Fm::RenameDialog::RenameDialog(_FmFileInfo*, _FmFileInfo*, QWidget*, QFlags<Qt::WindowType>) () at /usr/lib/libfm-qt.so.3
#3  0x00007f99b914079a in Fm::FileOperationDialog::askRename(_FmFileInfo*, _FmFileInfo*, QString&) ()
    at /usr/lib/libfm-qt.so.3
#4  0x00007f99b913ed52 in Fm::FileOperation::onFileOpsJobAskRename(_FmFileOpsJob*, _FmFileInfo*, _FmFileInfo*, char**, Fm::FileOperation*) () at /usr/lib/libfm-qt.so.3
#5  0x00007f99b759f973 in fm_marshal_INT__POINTER_POINTER_POINTER () at /usr/lib/libfm.so.4
#6  0x00007f99b6fa3ead in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#7  0x00007f99b6fb64ae in  () at /usr/lib/libgobject-2.0.so.0
#8  0x00007f99b6fbe61f in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#9  0x00007f99b6fbf69f in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#10 0x00007f99b75aa6c3 in  () at /usr/lib/libfm.so.4
#11 0x00007f99b75ae86e in  () at /usr/lib/libfm.so.4
#12 0x00007f99b75a7d2b in  () at /usr/lib/libfm.so.4
#13 0x00007f99b6ccb8c5 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#14 0x00007f99b6ccbc88 in  () at /usr/lib/libglib-2.0.so.0
#15 0x00007f99b6ccbd1c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#16 0x00007f99b7ab2061 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#17 0x00007f99b7a55ffb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt5Core.so.5
#18 0x00007f99b7a5f048 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#19 0x000000cb19aecd38 in  ()
#20 0x00007f99b634a4ca in __libc_start_main () at /usr/lib/libc.so.6
#21 0x000000cb19aecd9a in _start ()
```

Moreover, when I fix the crash with a simple patch, the rename dialog stubbornly asks for an overwrite, which is wrong because there's no file with that name to be overwritten.

Of course, after fixing the crash, if I change the name in the rename dialog, the file will be copied.

**Comment by tsujan** [comment]
Edited the report and made it more precise. Always reproducible.

**Comment by tsujan** [comment]
For the reference:

There are 2 problems in the file operation dialogs, at least:

(1) Write failure (the main issue in this report) isn't seen as an error by libfm sometimes;
(2) Error dialog should have a "Skip all" button (the issue reported at https://github.com/lxde/pcmanfm-qt/issues/512).

(1) is a problem in libfm and can't be fixed until the related functionality comes into libfm-qt (which might fix it automatically). A workaround may be possible though.

(2) may be completely in libfm-qt, in which case, a fix should be possible.

**Comment by FrederikLauber** [comment]
Some more information added.
If i select all files with CTRL+A in a folder, the number of files selected as well as their size is a factor of 4 to high.

**Comment by tsujan** [comment]
Fixed after https://github.com/lxqt/libfm-qt/commit/2a6f344271e883e326a326ba89e48566a3a8c857

**Comment by ipstone** [comment]
Hello, I am having this issue again with PCManFM-Qt 0.14.1 version again on arch linux - suggestions to fix this bug?

Thanks!

**Comment by tsujan** [comment]
> suggestions to fix this bug?

Use the latest git libfm-qt and pcmanfm-qt. All these problems are already fixed in git.

**Comment by tsujan** [comment]
@ipstone 
BTW, you cannot have *this* problem. It was related to libfm, which we don't use anymore.
