### ISSUE TITLE
Can't drop files in Place Panel

### ISSUE THREAD

**Issue by fulalas** [lxqt/pcmanfm-qt#566]
Currently I can't drop files in any of the Places Panel entries:

https://site1-fixmynix.rhcloud.com/wp-content/uploads/2016/01/pcmanfm.jpg

It would be nice if we could drop files directly to there instead of having to open a new window/tab or copy/cut.

**Comment by tsujan** [comment]
Superceded by https://github.com/lxqt/pcmanfm-qt/issues/987
