### ISSUE TITLE
Problem with keyboard navigation on desktop

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#577]
##### Expected Behavior
Arrow keys should work on desktop as they work in the main window of pcmanfm-qt.

##### Current Behavior
Right and left keys select the next and previous items instead of the right and left ones, respectively. Moreover, their behavior is not predictable with those items that have custom positions.

##### Possible Solution
This may be tricky because of custom positions... Should look into the code.

##### System Information

Everything is that latest git, on Manjaro.

**Comment by keysemble** [comment]
This sounds like a fun challenge. I'll look into this.

**Comment by tsujan** [comment]
> This sounds like a fun challenge.

Oh, yes! I didn't start to think about it ;) The problem may have 2 parts: desktop icons can be moved by the user; and there may be big horizontal/vertical gaps between them.

**Comment by keysemble** [comment]
Part of the problem is knowing which line(s) or code are the true problem. After spending an hour with tinkering and not getting any results, I decided to look into debugging with GDB. Unfortunately, since pcmanfm-qt is multi-threaded, it's more challenging to find the source of the bug, since the keyboard navigation poll is probably listening for events on a separate thread.

I need to learn to debug Qt applications more effectively.

**Comment by keysemble** [comment]
That said, I'm not leaving this issue. I just need to develop a new skill is all.

**Comment by tsujan** [comment]
> After spending an hour with tinkering and not getting any results, I decided to look into debugging with GDB.

There's nothing to debug. This isn't about a bug but a feature that's not implemented yet.

> That said, I'm not leaving this issue.

Take your time. The code is quite complex (it includes libfm-qt's codes too). The more you wrestle with it, the more familiar you'll get with it.

**Comment by keysemble** [comment]
I appreciate your care and assistance @tsujan. :smile_cat:

**Comment by tsujan** [comment]
I found some time to work on this and implemented it. Will make a PR after code cleanup and testing.
