### ISSUE TITLE
Operation dialog width may grow with file name

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#578]
##### Expected Behavior
The text should be elided if too long; it shouldn't change the dialog size.

##### Current Behavior
If the file name (in front of "Processing:") is too long, it'll widen the dialog.

##### Steps to Reproduce (for bugs)

1. Copy 2 big files, the first one with a short name and the second one with a very long name.
2. When the second file starts to be processed, the operation dialog widens to include the whole name.

##### Context

This can become a real problem when the file name is very long.

##### System Information

Latest git.

**Comment by MggMuggins** [comment]
Any way that Qt will let you break the string?

**Comment by tsujan** [comment]
> Any way that Qt will let you break the string?

`QFontMetrics::elidedText()` does it. This should be easy to fix in the paint event or...; I'll look into it as soon as I find some free time.

**Comment by tsujan** [comment]
Oh, I did a similar thing recently: https://github.com/lxde/pcmanfm-qt/blob/9a9152e081172e56c893c8f7c723005a2fd5e863/pcmanfm/statusbar.cpp#L35 So, it's mostly a matter of copy/paste.

**Comment by tsujan** [comment]
An example of (middle) eliding of the PR to prevent an annoying automatic resize:

![eliding](https://user-images.githubusercontent.com/981076/37783657-aa86b318-2e13-11e8-88d9-f8741f4ab5e9.png)

**Comment by MggMuggins** [comment]
I'd make sure you don't break (use a ellipsis) where directories begin/end (where there is a `/`). That way users don't get confused:

"What is `/home/user/big long path name/...r stuff/my stuff`"

That would probably require writing your own function to elide paths, but the behavior would be better.

Btw, is PCManFM still waiting on big PR's from PCMan to land for serious development to continue or not? I could write the path elision function if you'd like.

**Comment by tsujan** [comment]
> What is /home/user/big long path name/...r stuff/my stuff

There's no magic to it; it's like everywhere else, where eliding is done. The user could resize the dialog to see the full text, although that usually wouldn't be needed.

> My other thought would be to simply truncate the path

No! Middle eliding is the best according to my experience because it shows the start and the end.

That being said, in the last analysis, such things are about differences in tastes and we'll waste our times if we start a long discussion about them. Let's not do that!

> Btw, is PCManFM still waiting on big PR's from PCMan to land for serious development to continue or not?

Yes, we're waiting for that -- more specifically, for libfm-qt to be fully independent of libfm.

**Comment by MggMuggins** [comment]
What I was suggesting is basically to remove leading a trailing slashes on the ellipsis:
`/home/user/etc...hi/my stuff` instead of `/home/user/etc/...hi/my stuff`

It's fine if you don't want to discuss, I just wanted to make sure that I was clear enough...

**Comment by tsujan** [comment]
Oh, I came to this page again and saw that my last comment could create a misunderstanding!

Contributions are very welcome! @MggMuggins, if you have patches that make `libfm-qt/pcmanfm-qt` better, you're welcome to make PRs. Our waiting for a big commit by PCMan isn't related to that. Sorry if my words implied otherwise; it wasn't intentional at all.
