### ISSUE TITLE
Opening folders in new tabs from outside pcmanfm-qt

### ISSUE THREAD

**Issue by ghost** [lxqt/pcmanfm-qt#584]
In pcmanfm (GTK), opening a new folder (e.g. xdg-open ~/) will open it as a new tab in the existing pcmanfm instance. pcmanfm-qt will open it as a new window. This probably comes down to preference, but it would be nice to have an option to switch this.

**Comment by tsujan** [comment]
> pcmanfm-qt will open it as a new window

Only if the folder in question is opened outside that window.

It's possible to always open folders inside the instance of pcmanfm-qt that's running on the current desktop but that would need more X11 code, which isn't good because of wayland.

**Comment by tsujan** [comment]
At some point, I'll add tab DND, with which windows could be unified or divided.

**Comment by tsujan** [comment]
@palinek Does `kwindowsystem` have functions for knowing which window is on which virtual desktop? I can make `pcmanfm-qt` aware of virtual desktops by using X11 functions but I don't think it would be good to add more X11 dependencies.

**Comment by palinek** [comment]
> Does kwindowsystem have functions for knowing which window is on which virtual desktop?

Yes, it does -> e.g. https://api.kde.org/frameworks/kwindowsystem/html/classKWindowInfo.html#ae83c045a6ff50902756f57886c343604

**Comment by tsujan** [comment]
@palinek Thanks a lot!

**Comment by tsujan** [comment]
FYI

Having got familiar with `KWindowSystem`, I can say that the implementation of this feature is quite possible without an X11 dependency.

However, IMO, adding `KWindowSystem` as another dependency *just to implement this feature* isn't a good idea at all.

That being said, I leave this report open because who knows what will happen later?

**Comment by tsujan** [comment]
This is now possible with the new "single window" mode in git. pcmanfm-qt 0.15.0 will be released soon.
