### ISSUE TITLE
SMB share support

### ISSUE THREAD

**Issue by jleclanche** [lxqt/pcmanfm-qt#61]
https://github.com/lxde/lxde-qt/issues/147

**Comment by headbank** [comment]
If this were bugzilla, I'd vote for this ;)

Out of interest, do you anticipate staying with gvfs/gio for this, or using kio? Coming from KDE I recognise that kio probably brings heavier KDE-specific dependencies than gvfs does for GNOME, but AFAIK kio supports more protocols.

**Comment by Atalanttore** [comment]
GVFS is much more reliable than KIO. I would replace KIO with GVFS in KDE if I could.

**Comment by jleclanche** [comment]
We'll probably use gvfs. pcmanfm-qt uses gvfs already.

**Comment by agaida** [comment]
@tsujan - i guess we can close this - we support smb, sshfs, dav etc

**Comment by tsujan** [comment]
Yes, it's very old.
