### ISSUE TITLE
View mode icons depend on style plugin

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#618]
As far as I remember, this is the only place, where icons are determined by the Qt style plugin -- I mean the icons used for the view modes. That was PCMan's choice in the file dialog and I copied it for the mode buttons of pcmanfm-qt for the sake of consistency.

##### Expected Behavior
Icons shouldn't depend on the style engine. Or could they? I don't know. Please tell me your opinions!

##### Current Behavior
The view mode icons depend on the active style engine. `QStyle` sets some icons and different style engines can define them differently. Some of them -- Fusion and gtk, for example -- use (ugly) hard-coded Qt icons.

##### Possible Solution
We can make use of theme icons instead of style icons, as we do in other places.

**Comment by AcarBurak** [comment]
Yes, why this ugliness?
![icons](https://user-images.githubusercontent.com/1426842/40519577-e6aae350-5fc8-11e8-8b36-dfad4be189fa.jpg)

**Comment by tsujan** [comment]
Yes, in your screenshot, the icons for icon view and thumbnail view belong to Qt, not to the system icon set. In the following screenshot, all of them belong to the system theme because the style engine does so:

![icons](https://user-images.githubusercontent.com/981076/40538031-bbe11736-6025-11e8-8a54-c54c8bdf2d98.png)

**Comment by AcarBurak** [comment]
PCMan, I guess, is the only programme I use that behave like that.
> …the icons for icon view and thumbnail view belong to Qt

Surprising, so ugly and so un-Qt.

**Comment by tsujan** [comment]
Those 4 icons appear in the LXQt file dialog too.

> Surprising, so ugly and so un-Qt.

Qt isn't elegant *by default* ;)

**Comment by Kzinux** [comment]
Thank you, tsujan. 
Icons should follow the system theme.
![pcmanfm](https://user-images.githubusercontent.com/7030257/41088457-2d5ee7d4-6a72-11e8-8f78-6bd90e96cab2.png)
