### ISSUE TITLE
Can't select application from Open With... -> "Other Applications"

### ISSUE THREAD

**Issue by pooka109** [lxqt/pcmanfm-qt#63]
I'm using Slackware 14.1, Qt 4.8.5, and PCManFM-qt 0.7.0.

If I open the file browser, right-click on a file, select the "Open With..." option from the resulting menu, and select "Other Applications" from the "Open With..." submenu, I get the "Choose Application" menu as expected.  However, the "Installed Applications" tab refuses to select any application.

For example, if I'm trying to select an application to open plain text files (and I have Kate from KDE installed), I can open the "Accessories" tree entry and click on the Kate entry inside it, but, regardless of whether I single-click or double-click, the "Ok" button remains greyed out.

If I haven't provided enough information, let me know.  Thanks in advance.

**Comment by PCMan** [comment]
Is issue still valid? Does the bug still exist? I'm not able to reproduce it with the latest code.
