### ISSUE TITLE
Feature: Select newly created files

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#638]
This is a feature I use since the second month I started to work on `pcmanfm-qt` -- which was a very long time ago. I've modified the patch twice: once after PCMan ported `libfm` functionalities into C++11 and the other time, when I added a timer to it.

A description of the feature in question:

(1) Newly created files are selected, whether they are created by `pcmanfm-qt` or in any other way -- for example, when an archive is extracted by any archive manager (PCMan didn't like this years ago but, IMO, it's really handy).

(2) Newly created files are also scrolled to. That means, if many files are continuously being created inside an open folder -- for example, when a heavy compilation is done inside it -- the scrollbar (if any) will also be moving until the job is finished.

(3) There's a timer that selects newly created files only when they're new enough. When FILE1 is created, it'll be selected but if FILE2 is also created after > 200 ms since the creation of FILE1, then only FILE2 will be selected. I found this property necessary in practice.

I get a little angry when a file manager doesn't have the above-mentioned feature ;) Please tell me if you find it useful too!

**Comment by aramazano** [comment]
I can't think of a use case where newly created files being selected would be a useful feature for me. This can even be confusing in certain cases.

Think of an already very populated directory, where new files are continuously being added into (not necessarily in alphanumerical order). Say, detiled view covers 30 files at most (the rest is scrolled) and the directory already contains 100 or so files. Every other second a new file pops up in a random place in the listing - sometimes close to top, sometimes bottom, sometimes in the middle. In such a case, if selection jumps to each newly created file, then file selection/highlighting activity would go crazy. This moment jumping to top, next moment to bottom... and main view would be hardly usable as long as new files are kept popping up at random places.

What is wrong with not selecting at all a newly created file?

I would humbly vote for being totally indifferent to newly created files. Let the user expressly select whichever file he wants to address.

**Comment by aramazano** [comment]
Another case where auto selection would get in the way:

Auto selection presupposes that the user is focused on the file creation activity currently taking place. It would be so, for instance, when he is opening a tarball into a directory. But there can be other cases, where the user might be focused on some other work while new files are being added into the directory by some asynchronous process. This can be a background job, or I might have started a decompression and then turned back to my -other- work in the same directory. Or any other scenario in which I'm not necessarily focused on the files being newly added.

In such cases auto-selection would step on my asynchronous use of the file manager.

**Comment by tsujan** [comment]
> What is wrong with not selecting at all a newly created file?

Logically, nothing. It depends on the user; for me, everything ;) I want to create an empty file/folder and open it with just an `Enter`; I want to see quickly and easily where an archive is extracted or where a file is pasted; and so on, and so forth.

> Think of an already very populated directory,...

I intentionally described such a case above. Nothing disastrous will happen because a folder that's being populated continuously isn't usually a folder with whose individual files we want to work *before* the populating job is finished. In 2 years of using this feature, I've encountered no problem.

On the other hand, when this is an *option*, the user could enable/disable it. Again, no disaster ;)

> Another case where auto selection would get in the way...

My answer is as above: No disaster (according to experience) + being an optional feature

**Comment by tsujan** [comment]
> Another case :)

When I open a folder and then, without my "permission", a file is created in it, I really want to get informed about that, instead of doing my previous job and remaining negligent about the "conspiracy" ;)

None of your examples is a problem in real life. In some cases, what you see as a problem seems like a good thing to me. And yes, it'll be optional. However, who said that I'll implement it without more votes?! I opened this tracker exactly for that. Until now, 2 users like it; one user doesn't.

**Comment by agaida** [comment]
And i guess i would like such an option a lot :)

**Comment by tsujan** [comment]
> And i guess i would like such an option a lot :)

That's 10 more votes ;)

**Comment by agaida** [comment]
And i will be happy to merge all things - even if there is only a use case for one user - if it is promised that nobody suggest things like this:
> https://phabricator.kde.org/R40:9adcebd3c2e476c8a32e9b455cc99f46b0e12a7e#change-eBPQf5ohe0nO

**Comment by tsujan** [comment]
> if it is promised that nobody suggest things like this:

Completely agree. That was a silly decision; an artificial obstacle.

Yet another condition: no feature should compromise lightness.

**Comment by agaida** [comment]
Right

**Comment by tsujan** [comment]
The PRs are [here](https://github.com/lxde/libfm-qt/pull/170) and [here](https://github.com/lxde/pcmanfm-qt/pull/652). The lightness of pcmanfm-qt is intact. Other FMs may not have it in this form.

Please test it for a while before discussing about how useful it may be or not.
