### ISSUE TITLE
compress not work on Fedora 28

### ISSUE THREAD

**Issue by catafest** [lxqt/pcmanfm-qt#655]
##### 

##### Steps to Reproduce (for bugs)

1. try to compress file with right click menu Compress
2. nothing happend
3. 
4. 

##### System Information

* Distribution & Version: Fedora 28
* Kernel: 4.16.0-300.fc28.x86_64
* Qt Version: ?
* lxqt-build-tools Version: ?
* libqtxdg Version: ?
* libfm-qt Version: ?
* Package version: ?

**Comment by tsujan** [comment]
pcmanfm-qt → Preferences → Advanced → Archiver Integration

**Comment by tsujan** [comment]
Compressing works only when you introduce your archiver to pcmanfm-qt in the above-mentioned setting. In addition, more advanced archiving operations can be added as custom actions. Closing this.
