### ISSUE TITLE
Last accessed/modified: use app locale instead of system locale

### ISSUE THREAD

**Issue by Svinto** [lxqt/pcmanfm-qt#656]
Can be seen in:
* Timestamps in the Modified column in Detailed List View
* Last modified/accessed timestamps in file/folder properties

Screenshot: https://imgur.com/a/vu7h2

##### Expected Behavior
The syntax of the timestamps are displayed according to my locale settings.

##### Current Behavior
The syntax of the timestamps are always `%d/%m/%Y %H.%M` (Ex: 25/10/2015 21.00).

##### Possible Solution
Use the timestamp format: `%x %X` (see date manual for more info: https://linux.die.net/man/1/date)
Print the timestamps using std::put_time().
Example (UNTESTED): `std::put_time(std::localtime(&st_mtime), L"%x %X")`

##### System Information
* Distribution & Version: Arch Linux (up-to-date as of 12 April 2018)
* Kernel: 4.15.15-1-ARCH
* Qt Version: 5.10.1
* libqtxdg Version: 3.1.0-4
* libfm-qt Version: 0.12.0-2
* Package version: ???

**Comment by tsujan** [comment]
The current format is the system's locale (`Qt::SystemLocaleShortDate`). It can be changed to app's locale (`Qt::DefaultLocaleShortDate`), which looks like a better choice.

**Comment by tsujan** [comment]
> The syntax of the timestamps are always %d/%m/%Y %H.%M (Ex: 25/10/2015 21.00).

Not everywhere. Here, it is `M/d/yy h:m A`

**Comment by Svinto** [comment]
Do you have any idea where LocaleShortDate is taken from? How can I troubleshoot this?

I checked /usr/share/i18n/locales/en_DK (which is the one my system uses) but the format I see in PCManFM-Qt can't be found there.

**Comment by tsujan** [comment]
It's `QDateTime::toString(Qt::DateFormat format)`. In libfm-qt, `Qt::SystemLocaleShortDate` is used for the format, which means system's locale. It might be replace by `Qt::DefaultLocaleShortDate` later.

However, that isn't related to your report -- your report just reminded me of it. If the date/time format shown in that dialog doesn't follow your system's locale, the problem should be outside pcmanfm-qt. Please also note that the format is chosen to be short intentionally.

**Comment by Svinto** [comment]
I wrote my own test code to verify and the problem lies indeed in Qt.

`qt-date-locale-test.cpp`
```cpp
#include <QCoreApplication>
#include <QDebug>
#include <QDateTime>

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    auto time = QDateTime::currentDateTime();
    qDebug() << time.toString(Qt::DefaultLocaleShortDate);

    return a.exec();
}
```

The problem is that the order of year, month and date is all wrong for en_DK, since en_DK should follow [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601).

As seen below, Qt5 doesn't seem to distinguish between da_DK (danish Denmark) and en_DK (english Denmark). en_US and en_GB is included here so it is clear by watching the results that changing the locale is recognized by Qt.

Qt5: `g++ $(pkg-config --cflags --libs Qt5Widgets) -fPIC -o qt-date-locale-test qt-date-locale-test.cpp`
```bash
$ LC_TIME=en_DK.UTF-8 ./qt-date-locale-test  # "13/04/2018 09.59"
$ LC_TIME=da_DK.UTF-8 ./qt-date-locale-test  # "13/04/2018 09.59"
$ LC_TIME=en_US.UTF-8 ./qt-date-locale-test  # "4/13/18 9:59 AM"
$ LC_TIME=en_GB.UTF-8 ./qt-date-locale-test  # "13/04/2018 10:15"
```

Linux date (for comparison):
```bash
$ LC_TIME=en_DK.UTF-8 date +'%x %X'          # 2018-04-13 10:11:14
$ LC_TIME=da_DK.UTF-8 date +'%x %X'          # 13-04-2018 10:11:21
$ LC_TIME=en_US.UTF-8 date +'%x %X'          # 04/13/2018 10:11:08 AM
$ LC_TIME=en_GB.UTF-8 date +'%x %X'          # 13/04/18 10:19:35
```

So this is definitely not a bug in PCManFM-Qt.
You can close the bug report.

**Comment by tsujan** [comment]
If you're sure that Qt is wrong in this case, please report it to its bug tracker with a test code attached. They may have no other way of knowing it.

**Comment by Svinto** [comment]
Not wrong per say.

en_DK in Linux is a weird locale since Denmark doesn't have English as a official language. But it is the only way for Linux users to get an English locale with ISO-8601 timestamps.

Qt5 today uses the [CLDR](https://en.wikipedia.org/wiki/Common_Locale_Data_Repository) database for locales which doesn't include en_DK (which is understandable, since it's kind of a hack).

Qt is fully aware of the [problem](https://wiki.qt.io/index.php?title=Locale_Support_in_Qt_5&oldid=31479#User_Customization_on_Linux), but the problem scope is much much [larger](https://wiki.qt.io/Locale_Support_in_Qt_5).
