### ISSUE TITLE
On app startup, "hide close button on tab" not respected

### ISSUE THREAD

**Issue by fenugrec** [lxqt/pcmanfm-qt#658]
When the UI preferences are set such that "Show close button on tabs" is disabled, this option is ignored and all new tabs have the close button. The workaround is to go back to preferences, enable then disable the option again.
This has to be redone every time the application is restarted, I'm guessing that setting isn't loaded at startup ?

**Comment by tsujan** [comment]
Confirmed. May be about a typo somewhere.

**Comment by fenugrec** [comment]
Would it be this line
https://github.com/lxqt/pcmanfm-qt/blob/19b31474a8aa442127e7c66d5704c6ee72941476/pcmanfm/mainwindow.cpp#L95

is it possible to use the value set in preferences at that moment ?

**Comment by tsujan** [comment]
> Would it be this line

Probably.

@fenugrec The fix should be a piece of cake; I've been very busy but will do it soon.

**Comment by fenugrec** [comment]
great, thanks

> welcome to make PRs
yes, sometimes I do, but in this case I wasn't sure it was the right fix; also pretty busy making PRs for other projects  !

**Comment by tsujan** [comment]
> Also I'm more of a C guy, this C++/Qt stuff is sometimes strange

When you know C, you'll learn C++ fast because you could focus on its object-oriented aspect. As for Qt, it has a comprehensive doc.
