### ISSUE TITLE
Change "Delete" to "Move to Trash" according to settings

### ISSUE THREAD

**Issue by aramazano** [lxqt/pcmanfm-qt#662]
* Minor: [Shift]+[Delete] shortcut is not shown across the "Delete" entry in Edit menu, though the shortcut works fine. I think it should be added to the Delete entry in Edit menu.
* Major: There is no entry for "move to trash" in Edit menu. Also, the usual [Delete] shortcut for trash doesn't work in main view, though right-click context menu provides an entry for that. I think Edit menu should have a "trash" entry, along with a -working- [Delete] shortcut.

#### System Information
* Distribution & Version: LXQt [experimental-snapshots](https://lxqt.debian.net/) on top of Debian Testing (Buster)
* Kernel: 4.9.0-4-amd64
* Qt Version: 5.10.1
* lxqt-build-tools Version: Not installed
* libqtxdg Version: libqt5xdg3 / 3.1.1~14-g01f283b-1
* libfm-qt Version: libfm-qt5 / 0.12.1~41-ga88d6db-4
* pcmanfm-qt version: 0.12.1~37-gebd961d-1

**Comment by tsujan** [comment]
Actually, that "Delete" mean "Move to Trash" and should be changed accordingly.

Here, `Del` works for "Move to Trash" and `Shift+Del` for real deletion. Although the version I have includes new PCMan's patches (for testing), I know that it was so previously too.

**Comment by tsujan** [comment]
I also think that real "Delete" (`Shift+Del`) is not included in the GUI intentionally -- for more safety.

**Comment by aramazano** [comment]
I have tried the "Delete" entry in Edit menu and indeed it moves to trash instead. I agree that "Delete" entry in Edit menu should be renamed to "Trash" or "Move to trash" for clarity.

I also agree that Shift+Del is better excluded from Edit menu, but shown in the right-click context menu. Currently "real delete" it is neither in the context menu, so the user has to "guess" how to really delete a file. :)

**Comment by tsujan** [comment]
> Currently "real delete" it is neither in the context menu, so the user has to "guess" how to really delete a file. :)

Most users are familiar with it.

That being said, pcmanfm-qt has several "secrets" (= functionalities) that can't be found in its GUI. Previously (in another issue), I reached the conclusion that we should add a concise help. I haven't had time to add it yet but it's the must.

**Comment by tsujan** [comment]
Oh, I'd opened this after a discussion: https://github.com/lxqt/pcmanfm-qt/issues/550

**Comment by tsujan** [comment]
> but shown in the right-click context menu. 

Right-click menu is more "dangerous". Let's have the shortcut without a visible item!

**Comment by aramazano** [comment]
> pcmanfm-qt has several "secrets" (= functionalities) that can't be found in its GUI. 

I think exposing those functionalities would make an instantly richer and fuller file manager for free. It's a good thing, IMHO.

Perhaps if those functionalities are not final (may change or be revoked in future), then it is sensible to hide them, of course.

> Right-click menu is more "dangerous". Let's have the shortcut without a visible item!

It is OK for a normal user. But what if the user is novice (to computers and all)? There should be somehow an accesible viaduct for every function a software provides. Also, few users read documentation. I can imagine a novice user fiddling with menus etc. to -what he thinks- "shred" an important file, and being unable to do it without first moving to and then emptying the trash, getting frustrated.

BTW I just tried to empty my Trash folder, but there is no obvious way to do that. The only way I have found so far is going to "Places" and right-clicking on "Trash". I believe this function (empty trash) should also be exposed a bit more.

-------
While writing this, it occured to me that it might be a good idea to add "shred" and "undelete" functions to pcmanfm-qt. Well, particularly undelete is a bit of a stretch for a file manager, but being able to do it from within a file manager would be very cool, and raise user attention/satisfaction level, I think. This is a whole different topic anyway. Sorry that I again mixed apples and pears. I just wanted to note it FWIW before I forgot about it again.

**Comment by tsujan** [comment]
> But what if the user is novice...

Then, he/she should start to learn something -- `Shift+Del` is somehow universal -- and if he doesn't want to read a doc, nothing could be done for him ;)

> ...there is no obvious way to do that. The only way I have found...

And that's a very obvious way, IMO. If a user has only used Gnome, he'll learn that he's allowed to right-click at last ;)

> While writing this, it occured to me that it might be a good idea to add "shred" and "undelete" functions to pcmanfm-qt.

I don't think Linux users do so -- I've never tried to. Anyhow, even if possible, it should be the job of a separate and not so popular app, IMO.

**Comment by tsujan** [comment]
> Perhaps if those functionalities are not final...

All of them are (custom actions, tab DND, hiding side-items,...).

**Comment by aramazano** [comment]
> And that's a very obvious way, IMO.

My workflow for emptying the trash was like:

* Menu/Go -> Trash
* Right-click on items; no context menu entry to "permanently delete this item"
* Right-click on emty space; no context menu item to "empty trash"
* Skimp over top menu bar items; nothing appropriate

As I always work in Directory Tree mode in side pane, it wasn't immediately obvious for me to switch into Places mode to accesss more Trash functions.

Possibly "scrap this item" and/or "empty trash" functions could be included in Trash context menus?

**Comment by tsujan** [comment]
@aramazano That design isn't mine but I agree with PCMan's decision. IMHO, emptying trash isn't so urgent that not finding its menu item in 3 seconds *only the first time* can be considered an issue. If several users were dissatisfied with it, I'd see at least one complaint in 2 years.

**Comment by aramazano** [comment]
Sorry if I sounded complaining. I am all fine with it - no complaints. I was just trying to bring up ideas for a more polished UI, though I do accept that too much polish may spoil beauty of simplicity. It was just a minor detail, let's forget about it. :)

**Comment by ralphkw1** [comment]
I'm new to LXQt/pcmanfm-qt via lubuntu and was looking for a true delete option and found this open issue. So thought I would comment if that's ok. Coming from Thunar, I really miss this functionality. The following is a description "https://arcolinux.com/thunar-update-gives-an-extra-option-in-settings-to-permanently-delete-data/". One thing I appreciate about linux distros is allowing the user the ability to do dangerous things.

**Comment by tsujan** [comment]
> One thing I appreciate about linux distros is allowing the user the ability to do dangerous things.

And pcmanfm-qt doesn't prevent you from doing that. Press `Shift+Delete`.

This report is just about naming, not about a missing functionality.
