### ISSUE TITLE
Existing item-to-item copy/move/symlink not possible

### ISSUE THREAD

**Issue by aramazano** [lxqt/pcmanfm-qt#663]
Consider these operations in a terminal session:
```
~$ ls
dir1/ dir2/ file1.txt file2.txt
~$ cp file1.txt file2.txt
~$ cp file1.txt dir1/
~$ ln -sf file2.txt file1.txt
~$ lin -s ../file1.txt dir1/
~$ ln -s ../dir1 dir2/
~$ mv file1.txt file2.txt
~$ mv dir2 dir1
```
In pcmanfm-qt these operations are not possible. Dragging a file/dir on top of another file/dir behaves as if the item is dragged over to an empty space, i.e. it offers to create a new entry. 

Instead, it should have worked as an intrusive copy/move/symlink operation (selected via pop-up context menu) on top of the target item.

#### System Information
* Distribution & Version: LXQt [experimental-snapshots](https://lxqt.debian.net/) on top of Debian Testing (Buster)
* Kernel: 4.9.0-4-amd64
* Qt Version: 5.10.1
* libqtxdg Version: libqt5xdg3 / 3.1.1~14-g01f283b-1
* libfm-qt Version: libfm-qt5 / 0.12.1~41-ga88d6db-4
* pcmanfm-qt version: 0.12.1~37-gebd961d-1

**Comment by tsujan** [comment]
All of the operation you mentioned are possible. For example, to copy X as Y, use DND. And so on.

**Comment by aramazano** [comment]
Hmm you are right in that "to directory" operations work as expected with DND. I have been quick to generalize file and symlink DND behavior. My bad.

As for "to file" or "to symlink" operations:

In order to copy file1 to file2;
* DND file1 to file2
* Choose "copy": It behaves as if I DND file1 to empty space to copy file1 over to itself (doesn't detect that I have DND it on top file2)
* So the overwrite dialog (wrongly) pops for file1 -> file1 copy, with an option to rename destination.
* Rename the destination as "file2". Only then it understands that I actually want to copy file1 over to file2. So this first "overwrite dialog" was unnecessary.
* Now another overwrite dialog (rightly) pops up for file1 -> file2 copy, with an option to rename file2.
* Choose "overwrite" and file1 is now copied on to file2.

The first overwrite dialog was unnecessary, and it was because pcmanfm-qt didn't understand item-to-item DND.

Item-to item move via DND behaves the same.

Similar things happen for symlink copying and moving.

**Comment by tsujan** [comment]
DNDing a file over a file has no meaning and that's shown visually too: when you DND a file onto a folder, a temporary rectangle shows up, showing a "DND-over", while no rectangle will appear otherwise, showing that you aren't dropping "over" any file -- you're just dropping the file.

That DND menu -- which a user was wrongly annoyed about and I hope I've closed his report -- is there for such jobs.

**Comment by tsujan** [comment]
In short, all file operations are done easily and in an elegant, minimalistic way; you just have to change your habits. That's the case with all apps you start to use, whether they are buggy or not.

**Comment by aramazano** [comment]
> DNDing a file over a file has no meaning

Copying, moving and linking a file over an existing file has no meaning?

> when you DND a file onto a folder, a temporary rectangle shows up, showing a "DND-over", while no rectangle will appear otherwise, showing that you aren't dropping "over" any file -- you're just dropping the file.

Both cases of file->folder and file->file DND show up exactly the same rectangle here.

**Comment by tsujan** [comment]
> Copying, moving and linking a file over an existing file has no meaning?

Who said that?! Quoting myself: "DNDing a file over a file has no meaning."

**Comment by tsujan** [comment]
> Both cases of file->folder and file->file DND show up exactly the same rectangle here.

Not true. Actually, if true, your pcmanfm-qt/libfm-qt/libfm installation should have a problem.

**Comment by aramazano** [comment]
I am not sure I get this. OK, then how am I supposed to copy/move file-to-file through GUI, if file-to-file DND is not to be used?

**Comment by aramazano** [comment]
file->file DND works ditto file->dir DND, because pcmanfm-qt is ignoring file->file DND and taking it as a file->dir (current directory) DND. So there is no file->file DND. If you do that, it is taken as file->current_directory DND.

**Comment by tsujan** [comment]
I took the following screenshot with Fusion (because I think you use Fusion) to show you the drop rectangle:

![screengrab-20180506-022604](https://user-images.githubusercontent.com/981076/39667887-f16cee94-50d4-11e8-9967-f675e97a110e.png)

> how am I supposed to copy/move file-to-file through GUI

I'm sure you'll find the way if you trust pcmanfm-qt. And believe it or not, we do that a lot ;)

**Comment by aramazano** [comment]
Could you be more specific about that please?

I've looked at it again, but the shortest path I have found so far for file1->file2 copying is the one I mentioned here: https://github.com/lxqt/pcmanfm-qt/issues/663#issuecomment-386836760

**Comment by tsujan** [comment]
So, you know the way. Quoting from you:

> Choose "copy":

Or another item, depending on what you want to do.

> Only then it understands that I actually want to copy file1 over to file2

People don't have telepathy, let alone computer programs.

> So this first "overwrite dialog" was unnecessary.

No it wasn't, for the above-mentioned reason (telepathy).

**Comment by tsujan** [comment]
Wow! I'd forgotten https://github.com/lxqt/pcmanfm-qt/issues/319#issuecomment-354675153. So, I told you about that 3 times ;) And I added a screenshot to this page too. I really don't understand the source of your misunderstanding.

**Comment by aramazano** [comment]
> I told you (twice) that there's no dropping-over in pcmanfm-qt.

I do understand what you say, and I see that it is a deliberate design decision. So I was not reporting a "bug" here, I was suggesting a design change.

> You could have asked why and I'd tell you because it would cause hassles for the user when there's no easily accessible empty space

I would have accepted this as a good reason why file-to-file DND should not work. But then suppose you are in a directory with lots of subdirectories (think of /etc for instance) so all your window is filled up with directory entries. Then the same hassle would pop up again, wouldn't it? So, blocking file->file DND is not an ultimate solution for this problem, I think.

At the end of the day, it boils down to clumsy file-to-file operations.

Anyway, I don't want to argue about this. I simply don't agree with how it works. But if it will work this way, it will work this way. :)

**Comment by tsujan** [comment]
> Then the same hassle would pop up again, wouldn't it?

No, it wouldn't because (1) you could drop the file in question "on itself" and (2) files-after-folder is the sorting mode most people use.

Anyhow, the point is that we drop files only into folders -- not "into files" -- and pcmanfm-qt shows that by showing/not showing the drop rectangle.

**Comment by agaida** [comment]
same here - make a screencast and we can discuss it
