### ISSUE TITLE
No warning for dup names at 'Create new file/dir' context menu function

### ISSUE THREAD

**Issue by aramazano** [lxqt/pcmanfm-qt#665]
Attempting to create a new file/dir with the same name as an already existing item, doesn't get any error messages, the name entry dialog is simply redisplayed again.

It should display some error message explaining the error, prior to displaying name entry dialog again.

#### System Information
* Distribution & Version: LXQt [experimental-snapshots](https://lxqt.debian.net/) on top of Debian Testing (Buster)
* Kernel: 4.9.0-4-amd64
* Qt Version: 5.10.1
* libqtxdg Version: libqt5xdg3 / 3.1.1~14-g01f283b-1
* libfm-qt Version: libfm-qt5 / 0.12.1~41-ga88d6db-4
* pcmanfm-qt version: 0.12.1~37-gebd961d-1

**Comment by tsujan** [comment]
> It should display some error message explaining the error, prior to displaying name entry dialog again.

Why should we annoy users by an extra dialog?!

**Comment by aramazano** [comment]
Because there can potentially more than one reason for not responding to a request.
* Duplicate name
* Invalid char in file name
* Reserved name
* Permission issues
* Disk full
* File manager not working
* Etc.

(Granted, lack of permission is reported appropriately.)

Without a feedback, the user is left guessing why the operation is not being carried out. In a crowded directory, duplicate naming may not be immediately obvious. This is not a big deal, but a -smooth- usability issue nevertheless.

**Comment by tsujan** [comment]
Exceptions are correctly reported. Please test before saying that something is a bug!

**Comment by aramazano** [comment]
One of the exceptions I cited were "file manager not working". So the user is still left guessing. :)

**Comment by tsujan** [comment]
"file manager not working" means there is a bug. Report a real bug and it'll be investigated --  as has always been the case.

**Comment by agaida** [comment]
hmm - i have a suggestion - make a screencast - i can't reproduce the "wrong" behaviour.

**Comment by aramazano** [comment]
It is simple to reproduce:
1. Go into any directory
2. Right-click empty space
3. Choose: Create -> Empty file (or directory)
4. A name entry dialog will pop up: Enter any name that is already existing in that directory.
5. Goto 4 : Your entry will be replaced by an empty dialog again. (no explanation, no messages, no blink, nothing)

**Comment by tsujan** [comment]
NO EXPLANATION IS NEEDED!

You mean pcmanfm-qt may hide a bug behind its dialogs -- don't say, "no, I don't mean that;" we're speaking plain English. Although I don't understand your mistrust -- especially when none of your reports are neglected -- the only thing I can say is: OK, if anyone finds and reports that supposed bug, it'll be investigated.

The fact is that, today, a lot of time is wasted on speaking about NOTHING.

**Comment by aramazano** [comment]
> You mean pcmanfm-qt may hide a bug behind its dialogs -- don't say, "no, I don't mean that;"

Beyond that, I can't even understand how such a meaning can be inferred from this report. I have reread it assuming the most negative meaning possible, still I can't derive such a message from what I have written so far.

I simply suggested informing the user as to why the operation will not be carried out, so that
he will not be left guessing. What can possibly be wrong with this? I have no idea.

Anyway, I don't want to talk about it further. Thank you for your time.

**Comment by tsujan** [comment]
> how such a meaning can be inferred from this report.

Logically, by really reading what people write. Your words:  "I said that the user has no way of telling whether it won't work because the FM is broken," The word "broken" means there may be a bug; it needs no interpretation, unless you write what you don't mean.
