### ISSUE TITLE
No right-click menu on Desktop

### ISSUE THREAD

**Issue by agaida** [lxqt/pcmanfm-qt#666]
Latest Git - expected: normal things like in every other Folder (New, insert and so on)

**Comment by tsujan** [comment]
Not reproducible here, although I compiled and installed libfm-qt and pcmanfm-qt 3-4 times for some (unimportant) reason.

**Comment by tsujan** [comment]
FYI: As far as I know, none of PCMan's patches treats the desktop separately.

**Comment by agaida** [comment]
Strange

**Comment by agaida** [comment]
forget it - or maybe not. Solution: Remove the hook from Desktop-Settings Use menu from Window Manager - ok, xfwm4 don't provide such menu - but i'm dead sure that i don't set this settig :)
