### ISSUE TITLE
Separate prompt options for desktop entries and executables

### ISSUE THREAD

**Issue by agaida** [lxqt/pcmanfm-qt#668]
Follow up for https://github.com/lxqt/lxqt/issues/1486

It's fine that the option is in the pcmanfm-qt settings - they should be in the Desktop settings too as a first step. Maybe the option should be refined later.

**Comment by agaida** [comment]
that would be great - i'm more or less fine with the pcmanfm-qt behaviour (ok, @LStranger was not a fan ;) ) - but the Desktop behaviour itself and the handling of .desktop-files, menu:// links and otheres could be improved (if possible) - so a second option for Desktop handling is the right way

**Comment by tsujan** [comment]
Agreed. I'll try to separate executable and desktop-file quick launches from each other after PCMan's PRs are merged. For now, a few things should be fixed in the PR for pcmanfm-qt and, IMO, it's better no to make the PRs more complex than they already are.

**Comment by agaida** [comment]
Full ACK

**Comment by tsujan** [comment]
@agaida The "trust" flag and the separation in question were both your ideas but I think, with the first one (implemented now -- and better than the second one, IMO), there may be no need to the second anymore. Also, see https://github.com/lxqt/pcmanfm-qt/issues/751#issuecomment-412376799

**Comment by agaida** [comment]
The "trust" flag should be  enough imho
