### ISSUE TITLE
Disable "Create New" when it's impossible

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#669]
Exactly like what was done with "Cut", "Paste", "Move to Trash", etc. before, it's better to enable the "Create New" (context) menu-item only when such an action is possible.

**Comment by gustavoefeiche** [comment]
I would like to work on this! @tsujan

**Comment by tsujan** [comment]
OK.

**Comment by tsujan** [comment]
I'll do it myself.

**Comment by the-loudspeaker** [comment]
@tsujan can you hint on how to go about this? I have forked the repo and ready to make changes. :)

**Comment by tsujan** [comment]
I have the patch for 2 years. I'm a little busy now; will make a PR soon.
