### ISSUE TITLE
Can not copy directory contents from other PC with Active Directory

### ISSUE THREAD

**Issue by sigurupo** [lxqt/pcmanfm-qt#686]
##### Current Behavior
I want to copy midi files.

other PC: bob-pc(windows10)
1. Connect to smb://bob-pc.local/d/
2. Copy smb://bob-pc.local/d/midi directory
3. Paste to ~/downloads/
Succeeded in pasting midi directory. But smb://d/midi/*.mid are not.
Normally, midi files should be copied.

When I choose all midi files, all midi files are copied.
When I copy directories from system drive to system drive, all files are copied. 
When I use pcman-fm(gtk3), midi files are copied.

##### System Information
I installed lxqt package in arch linux.

* Distribution & Version: ?
* Kernel: 4.16.12-ARCH
* Qt Version: 5.11.0
* lxqt-build-tools Version: ? 
* libqtxdg Version: ?
* libfm-qt Version: 0.13.0
* Package version: ?

**Comment by shamatic** [comment]
I have this bug too. However, Pcmanfm-qt not only fails to recursively copy/move to/from gvfs mounted smb shares, but mtp too (tried on multiple Android phones). This happens even if I bypass the vfs, and navigate to /run/[username]/1000/gvfs/[mountpoint]. Any other fm (like mc) works just fine in this regard.

System info: Debian sid, Qt 5.10.1, Lxqt 13.0 (distro shipped build)

**Comment by tsujan** [comment]
Unfortunately, even with the latest git, pcmanfm-qt may have problems with smb. A developer who has access to smb is needed.

@agaida, could you guide me through all smb issues in a step-by-step way? I might be able to fix them "blindly" with your help.

**Comment by agaida** [comment]
s/may// - and not only smb, the whole networking things over gvfs have some glitches. So we should test and fixe the whole stack step by step - asap.

**Comment by tsujan** [comment]
I completely agree; it's very important to fix networking before the next release.

**Comment by agaida** [comment]
i guess i will start a semi public sandboxed smb - we can integrate the other needed services in that vm too - if we don't need it we can just stop the VM - so i don't see any security problems doing so. Secured unprivileged containers are really cool :sunglasses:

**Comment by tsujan** [comment]
SSH works fine. Files are pasted correctly.

**Comment by agaida** [comment]
davs:// work fine too - the very problem is not that the connections don't work - the problem is that the clickable path to these connections don't work

So: Where to start? I guess we should start with something thats work

**Comment by agaida** [comment]
![](https://i.imgur.com/ivVJ8JK.png)

So - in pcmanfm the network items are displayed as Links - in pcmanfm-qt as real files or folders - this might be the first hint

**Comment by tsujan** [comment]
@agaida, I'll attack the problem a few days later, being busy with life problems now. In the meanwhile, please keep telling about your findings!

**Comment by agaida** [comment]
will test right when i'm home - in the office right now

**Comment by agaida** [comment]
nope - see nothing like that

**Comment by tsujan** [comment]
> nope - see nothing like that

OK. I'll try not to waste your time but without guarantee ;)

This change (in the branch "smb_fix" and for the latest git libfm-qt) is logical: https://github.com/lxqt/libfm-qt/commit/e30b01858760d2c045d66764d62711889ba979d4 . Could you test it to see whether it makes a difference in using SMB?

**Comment by tsujan** [comment]
@agaida After I uncomment [this qDebug](https://github.com/lxqt/libfm-qt/blob/5b937cf9c5a0e7486cd929ffc3dd8e56a55a4a32/src/core/basicfilelauncher.cpp#L33) and recompile libfm-qt, if I click `Network → Windows Network`, I'll get these messages:
```
path: network:///smb-root, type: inode/directory, target: smb:///, isDir: 1, isShortcut: 1, isMountable: 0, isDesktopEntry: 0
shortcut is dir: smb:///
...
```
Would you tell me what you'll get if you click one of your SMB items (NOT Windows Network)?

**Comment by agaida** [comment]
```
path: network:///smb-server-IDEFIX, type: inode/directory, target: smb://IDEFIX/, isDir: 1, isShortcut: 1, isMountable: 0, isDesktopEntry: 0
shortcut is dir: smb://IDEFIX/
path: /, type: inode/directory, target: , isDir: 1, isShortcut: 0, isMountable: 0, isDesktopEntry: 0
```
please note that if i try `smb://IDEFIX/` in pcmanfm it switch to `smb:://idefix/` and show the possible shares as folders - if i click onto one it prints out
```
path: smb://idefix/._photos, type: inode/directory, target: smb://idefix/photos, isDir: 1, isShortcut: 0, isMountable: 1, isDesktopEntry: 0
path: /, type: inode/directory, target: , isDir: 1, isShortcut: 0, isMountable: 0, isDesktopEntry: 0
file monitor cannot be created: Vorgang wird vom Backend nicht unterst?tzt
```
the share is now mounted, but the content of `/` is displayed

**Comment by tsujan** [comment]
Very interesting and, at the same time, annoying! So, at first, it *is* a shortcut directory (`isDir: 1, isShortcut: 1, isMountable: 0` and also `shortcut is dir: smb://IDEFIX/`) but, afterward, it changes to the root directory.

That means, after you click on it, your root directory is shown; am I right?

**Comment by agaida** [comment]
https://youtu.be/DFTXjxHf1jA - little screencast

**Comment by tsujan** [comment]
The cause may be in front of my eyes but I don't see it yet :(

**Comment by tsujan** [comment]
@agaida, does it make any difference if you *middle* click those SMB items?

**Comment by agaida** [comment]
yes, it does https://i.imgur.com/qMx5sTK.jpg

**Comment by tsujan** [comment]
@agaida Bad news: I'm out of ideas. Wherever I searched for a problem, I found correct codes! What you see is this:

`BasicFileLauncher::launchFiles` is called and the SMB item is found to be a shortcut (which is correct). Then, `BasicFileLauncher::launchPaths` is called and the file info job inside it returns the root info -- that's the magic I don't understand: it should return the SMB info.

Can we call @PCMan?

**Comment by agaida** [comment]
We should

**Comment by tsujan** [comment]
@shamatic, mtp works fine here, with the latest git pcmanfm-qt, which is very different from the latest release. I copied 2 folders and all of their contents were copied too.

**Comment by tsujan** [comment]
I think this problem is fixed now. Reopen if you still encounter it **with the latest git libfm-qt and pcmanfm-qt**.
