### ISSUE TITLE
Feature request: Animated wallpaper support

### ISSUE THREAD

**Issue by snorkellingcactus** [lxqt/pcmanfm-qt#710]
Hi.
    Only as a personal interest I would like to have the possibility of setting a animated image (gif, or even a video or a video fragment) as a desktop background.

I wonder if it would be a long term, nice to have feature for lxqt developers/users or if i should do my own qt wallpaper setter.

I think i may implement it. I'm not really taking a compromise just now, only doing the first part of trying to know what do you think about.

That's all.

Thanks for this great and fast desktop.

**Comment by tsujan** [comment]
Frankly, this will never be done by us; so, having an open issue for it is pointless.

If someone makes a PR that does it without extra usage of resources and with a maintainable code, it'll be reviewed and probably merged. However, that's very unlikely.
