### ISSUE TITLE
Translation import from PCManFM

### ISSUE THREAD

**Issue by yarons** [lxqt/pcmanfm-qt#719]
Hey guys,
I've already translated PCManFM into Hebrew and I think there are many similar strings, is it OK to import these? Is there a reason why those strings were not imported automatically?

Thanks!

**Comment by agaida** [comment]
How can you import similar strings?

**Comment by yarons** [comment]
I can import all the strings and the matching ones will just fit right in, all the others I'll just have to make some adjustments.

**Comment by agaida** [comment]
ok
