### ISSUE TITLE
Drop indicator/rectangle is broken on Desktop

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#722]
To see the problem, do as follows:

(1) Drag a desktop item on a folder that's on the desktop. No drop rectangle will be shown.

(2) First, open a pcmanfm-qt window and drag an item from there on a folder that's on the desktop. The drop rectangle will be shown. Then, just drag a desktop item on another desktop folder. The previous drop rectangle will be shown and won't be updated. It won't make any difference how many times you drag desktop items.

This issue is old and started after we painted desktop ourself (as a workaround for a Qt bug). It's good to paint desktop but, in that case, we should draw the drop indicator too.

I'll make a single PR to fix this and https://github.com/lxqt/pcmanfm-qt/issues/706 because they're interrelated.

**Comment by tsujan** [comment]
Closed in https://github.com/lxqt/pcmanfm-qt/commit/8bcd8b936c5c65264fd79123248d806432b77b92

**Comment by tsimonq2** [comment]
I see one more problem after just sitting and messing with it for a while.

When I drag an icon to the lower part of another icon, it should move the icon I'm hovering over up, not down.

**Comment by tsimonq2** [comment]
Ah, I just realized the issue I reopened... should I file a different one or is this fine? :)
