### ISSUE TITLE
"Copy as Path" as context menu option like old PCManFM.

### ISSUE THREAD

**Issue by sys2kdev** [lxqt/pcmanfm-qt#730]
##### Expected Behavior
Secondary click over a file or folder should show "Copy as Path" option.

##### Current Behavior
 "Copy as Path" is not present in the context menu, Its currently present in the GTK version.

##### Context
This option is very useful when I need to use the name of the file/folder in a terminal.

##### System Information
ArchLinux full updated (with pacman -Syu) on 7/16/2018

**Comment by tsujan** [comment]
The path and name can be copied in various ways.

pcmanfm-qt isn't supposed to be a clone of pcmanfm. Think of it as another file manager with its own ways of doing things.

**Comment by tsujan** [comment]
Clicking into the pathbar copies the path to the selection clipboard -- the pathbar can be changed to a location bar too. Imitating MS Windows not only would give the user no advantage but also would clutter the GUI.

**Comment by sys2kdev** [comment]
Imitating MS Windows? I'm talking about a option that was in pcmanfm (gtk). With your method, I have to to press CTRL+L to copy the address in the top bar, and then I have press F2 in the file to I'm able to copy the file name, and I have to concatenate that in leafpad.

**Comment by sys2kdev** [comment]
Imitating MS Windows? I'm talking about a option that was in pcmanfm (gtk). With your method, I have to to press CTRL+L to copy the address in the top bar, and then I have press F2 in the file so I'm able to copy the file name, and I have to concatenate that in leafpad.

I really don't want to adopt pcmanfm-qt, but I'm a Lubuntu user, and they are planning to switch to LXQt.

**Comment by tsujan** [comment]
> With your method, I have to to press CTRL+L to copy the address in the top bar

You shouldn't; please pay more attention to the GUI.

> I really don't want to adopt pcmanfm-qt....

That's up to you.

**Comment by sys2kdev** [comment]
Is not up to me, I don't have control over the Lubuntu project.

**Comment by sys2kdev** [comment]
I'm a Lubuntu user, but I use ArchLinux to see the current state of some software. In this case LXQt that is suppose to be included in future Lubuntu releases.

I don't have big problems with LXQt, I just wanted the "Copy path" option that has been always available in PCManFM. A honest answer will be "we don't feel like doing it", but don' try to rationalize that. Until this moment I don't see any technical reason to not include this option.
