### ISSUE TITLE
An option for trusting executables/desktop entries

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#737]
We have an option for showing a prompt message on clicking executables or desktop entries. It's enabled by default but the user can disable it. The problem is that some users don't want the prompt but, when it's disabled, there will be a security risk.

Instead, the above-mentioned option can be removed, a check-box can be added to the prompt message, saying "Trust this executable", and the trusted files can be remembered.

@agaida and I agree on the concept of "trusted files". The above sketch may seem simple but the real implementation may not be so easy.

**Comment by tsujan** [comment]
Also, it's better to have a way of removing the "trusted" state, for example, by right clicking a single executable file.

**Comment by agaida** [comment]
think different - we will have a button for truting a file - this button can change to "remove trust" once it is trusted - and if we go the hash way somewhere in gvfs - we will know the location of the file to delete to remove the trust.

**Comment by tsujan** [comment]
Or easier to use: a "trust" check-box on the right-click menu of executables/desktop entries.

**Comment by agaida** [comment]
also possible

**Comment by tsujan** [comment]
I should see how to remember the file. That's the main thing in all this.

**Comment by tsujan** [comment]
The good GLib (GIO) has all we need: string-type metadata attributes are kept with the file when it's moved/copied (I tested that with `gio set` and `gio info` in command-line). A powerful tool is there; it remains to find the best way of using it :)

**Comment by tsujan** [comment]
I did it here in 10 minutes and it worked fine with executables and desktop entries:

![trust](https://user-images.githubusercontent.com/981076/43129881-94caceb8-8f4a-11e8-958e-e65e01bd792a.png)

However, it was too easy and that makes me worry. More importantly, I used `g_file_set_attributes_from_info` instead of `g_file_set_attributes_async` to test the idea quickly. I think the second function should be used. Will try to make it less easy ;)

**Comment by tsujan** [comment]
Another thing: If the file is moved, its "trust" state will be preserved but not when it's copied. I still don't know why.

**Comment by tsujan** [comment]
OK, at the risk of showing my GLib ignorance (which exist), I'll make a PR today because, apparently, it works fine.

**Comment by Mabenan** [comment]
Hi,

sorry for open this issue again. But I think this is related to this. When I use the option mentioned above it works fine but it forgets that i trusted the executable after restart.

Linux kernel: 5.0.8-arch1-1-ARCH
LXQt Version | 0.14.1
Qt | 5.12.3

**Comment by tsujan** [comment]
> When I use the option mentioned above it works fine but it forgets that i trusted the executable after restart.

Probably, you haven't installed a gvfs package. Install gvfs, gvfs-gphoto2, gvfs-mtp, gvfs-nfs and, if you want smb, gvfs-smb. Then restart pcmanfm-qt's desktop process or log out and log in.

**Comment by Mabenan** [comment]
Ah thank you problem solved

**Comment by tsujan** [comment]
You're welcome.

With LXQt, always install optional dependencies. Actually, it's a good practice do so with all packages.

**Comment by xerostomus** [comment]
> Probably, you haven't installed a gvfs package. Install gvfs, gvfs-gphoto2, gvfs-mtp, gvfs-nfs and, if you want smb, gvfs-smb. Then restart pcmanfm-qt's desktop process or log out and log in.

Is there any way how to run pcmanfm-qt completely without gvfs*? It is not part of pcmanfm-qt and I do not want to have it on my Lubuntu. Metadata is question of gvfs and not having it is source of these unnecessary problems.

**Comment by tsujan** [comment]
> Is there any way how to run pcmanfm-qt completely without gvfs*?

The code doesn't depend on it — so, yes, GVFS is "optional" — but important functionalities (trash/MTP/fuse... support) would be missing without it.

**Comment by xerostomus** [comment]
>The code doesn't depend on it — so, yes, GVFS is "optional" — but important functionalities (trash/MTP/fuse... support) would be missing without it.

Well, yes and no. Exclamation marks are annoying and they require GVFS. I do not use these advanced functionalities, so an uninstall of GVFS is usually the first thing I do after a fresh system install (GVFS is greedy of memory and processor time - daemons. PC is faster without it.). So I would appreciate if it were possible to go without these remnants of GVFS, say as the exclamation marks are.

**Comment by tsujan** [comment]
> PC is faster without it

The less functionalities your system has, the faster it is.

> so an uninstall of GVFS is usually the first thing I do

You can do so but please don't report bugs about not being able to trash files, to transfer images from a digital camera, etc.

> So I would appreciate if it were possible to go without these remnants of GVFS

As I said, the code doesn't depend on GVFS. What more do you want? If you want us to do GVFS jobs (like trash) without GVFS, the answer is "No! That's impossible."

**Comment by xerostomus** [comment]
Dear Mr. Tsujan, 
Please do not be angry. I do not complain about missing functions of trash bin. I complain, that I cannot get rid of exclamation marks on my desktop (meta-data). They are back after each restart of my PC because of GVFS. If I dare to ask you, please solve this problem. I would like to have a pcmanfm-qt desktop without GVFS installed and without exclamation marks. I thought it was not a difficult task to accomplish.
With an apology 
Xerostomus

**Comment by tsujan** [comment]
> Please do not be angry

I don't know how you extracted "anger" from my words but I wasn't and am not angry.

> please solve this problem

You don't want GVFS, so you can't use it to trust executable files on your desktop. What's the problem to solve?

**Comment by xerostomus** [comment]
I am glad you are not angry. 
Well, the problem is annoying dialog whenever I click on a icon with executable file. That's why it is flagged executable to be executable. Why should I click each restart again and again, that I yes still consider it to be executable, I trust it, I trully want it to keep executable even for this session... Am I idiot? 

If it is not to be executable, then let's change the owner and make it non executable.

So if you can help me from this annoyance with metadata, I would be glad.

Thanks :-)

**Comment by tsujan** [comment]
> Well, the problem is annoying dialog whenever...

Preferences → Behavior → Launch executable files without prompt

> Why should I click each restart again and again, that I yes still consider it to be executable,

You already know the answer (lack of GVFS on your system); why asking again?!.

**Comment by xerostomus** [comment]
Yes, yes, yes. It is what I needed. 

> Preferences → Behavior → Launch executable files without prompt

I am a brave man, I can survive the exclamation mark that is still left there.   :-)

Thank you, Sir, for your kind cooperation!
Lot of luck!
X
