### ISSUE TITLE
Desktop dir not recognized

### ISSUE THREAD

**Issue by tigerjack** [lxqt/pcmanfm-qt#740]
##### Expected Behavior
In `.bashrc` I have the following line `export MDIR_LINUX_DATA="$HOME/LinuxData"`.
In `.config/user-dirs.dirs`, instead, I have the following definition `XDG_DESKTOP_DIR="$MDIR_LINUX_DATA/Desktop"`.

The variable is correctly recognized as the following command shows

   >xdg-user-dir DESKTOP
    /home/myuser/LinuxData/Desktop

So, I expected that there is no problem with `pcmanfm-qt`.

##### Current Behavior
When I click the `Desktop` link, I get the following

> Error when getting information for file "/home/myuser/$MDIR_LINUX_DATA/Desktop": No such file or directory.

##### Possible Solution
I think the main reason is that, instead of expanding the environment variable, it treats it as plain text. Also, because the definition of the `XDG_DESKTOP_DIR` doesn't start with a slash, it treats it as a path relative to the home dir.

##### System Information

* Distribution & Version: Ubuntu 18.04
* Kernel: 4.15.0.29
* Qt Version: 5.9.5
* lxqt-build-tools Version:  
* libqt5xdg3 Version: 3.1.0-5build2
* libfm-qt Version:  0.12.0-14build2
* Package version: ???

**Comment by agaida** [comment]
two remarks - that is to be expected - modify your desktop file, you will find useful informations in the freedesktop documentation. Maybe a hint - open a subshell in the desktopfile might help.

**Comment by tigerjack** [comment]
@agaida I don't understand what are you stating or suggesting. How should I modify the desktop file? 
I tried all the methods below

    Exec=sh -c "pcmanfm-qt"
    Exec=sh -e $(pcmanfm-qt)

The first one gives the same problem, the second one doesn't launch anything at all.
