### ISSUE TITLE
Filtering by typing into the view

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#744]
Qt's item selection by typing into the view isn't very usable because typing should be done fast. Instead, imagine this feature (not existing yet): If the user types into the view, the filter-bar will be shown (if it's hidden) and the text will be typed into it without losing the focus, so that the current files will be filtered.

Knowing that it isn't optional (there are already too many options), is it acceptable to you or do you see it as an annoyance?

**Comment by tsujan** [comment]
My thoughts after using this feature for several hours:

On the one hand, it makes filtering faster and easier -- I've seen that here. Since the view doesn't lose its focus, working with the filtered files is more comfortable without using mouse or extra shortcuts.

On the other hand, it requires removing Backspace as the extra shortcut for going up -- because Backspace is also used in typing -- but I don't want to remove anything from the original design of the app.

A solution may be making it optional and disabling the Backspace shortcut only if it's enabled but that feels too arbitrary to me.

Another solution can be disabling the Backspace shortcut only when there's text in the filter-bar *and* the view has focus. The problem with this approach is that, when the user removes the filter text, character by character, with Backspace, he might go to the parent directory inadvertently when no text remains.

Perhaps I should forget about PRing it.

**Comment by tsujan** [comment]
Solved all problems with "on-demand filter-bars":

* The GUI is simplified by removing filter-bar's setting and its menu-item -- they won't be needed anymore.
* The user sees no filter-bar when he/she hasn't applied a filter -- an empty filter-bar is never shown.
* Each tab page has its own filter-bar (this fixes https://github.com/lxqt/pcmanfm-qt/issues/455 too), which is shown only when the user starts to type inside the view and will be hidden again if it's cleared in any way.
* Typing inside the view keeps the view focused.
* The user could give the focus to a visible filter-bar with `Ctrl+I` and do more editing (for example, by using left/right arrrow keys, which were taken by the view when the bar wasn't focused).
* `Ctrl+K`, `Ctrl+Z` and `Ctrl+Shift+Z` (for filter-bar) also work when the view has focus.
* Backspace is passed only to a *visible* (= non-empty) filter-bar; otherwise, it'll  be the shortcut for going up, as before.

I'll test it for a while to see if it works smoothly. The code is very simple.

**Comment by tsujan** [comment]
>  When I'm using a graphical file manager, I tend to have only one hand at the keyboard, and the other one on the mouse....

Habits aside, what you described is easier with a transient filter-bar.
 * Qt's selection by hasty typing is kept (although, it isn't comfortable); filtering is just added to it. 
 * There's no haste anymore.
 * "morph" can be typed for "skeuomorphic", for example, and then arrow keys can be used.
 * All files will be shown again by a `Ctrl+K`.
 * And more.... For example, text can be pasted by `Shift+Insert` inside the view (a standard line-edit shortcut).

So, you could use your "mouse hand" for more productive jobs ;)

The permanent filter-bar is kept for backward compatibility in usge. I don't think seeing a permanent filter-bar is a big deal for those who don't like the transient one but if it *really* is, an check-box could be added for disabling the latter -- feel free to open an issue for us to see what others might say.

**Comment by Chiitoo** [comment]
I had tried setting the filter-bar to be always visible, but had not noticed that 'jumping to files' works like before then.

I might get used to that, though it does take away a bit of space.  I'm not sure yet if that will be too big of an deal though.  :]

I'll open up an issue if I still feel that strongly about this after a while.

Thanks!

**Comment by tsujan** [comment]
> I had tried setting the filter-bar to be always visible, but had not noticed that 'jumping to files' works like before then.

As mentioned above, Qt's behavior is kept with transient filter-bars too.

> I might get used to that,

Preferably, disable the permanent bar and try to get used to the transient one ;)

**Comment by manaskarekar** [comment]
Sorry to bring up this old topic, but can the transient bar be made to be dismissed with the `Escape` key?

If you want to exit the filter, you gotta `backspace` out of it. But, if you go one too far, you go to the previous folder/view. Is there a place to change this setting?

I, too, like the behavior of the old pcmanfm, where you jump to the files, but I do see the value in filtering. Showing the filter bar takes up too much space.

As an aside, thank you for the awesome work.

**Comment by tsujan** [comment]
> If you want to exit the filter, you gotta backspace out of it.

No, you don't need to. Use `Ctrl+K`. It's shown on the tooltip of the line-edit clear button.

**Comment by manaskarekar** [comment]
That helps! I'd still prefer the `escape` key to do this, but this is good to know!

**Comment by tsujan** [comment]
> I'd still prefer the escape key to do this

I agree but there may have been a reason for not using it. I don't remember now but will investigate that and if there's no good reason, will add Escape.

**Comment by manaskarekar** [comment]
Thank you so much, that would be perfect!

**Comment by tsujan** [comment]
You're welcome.

You're suggestion was so good that I opened this feature request for it: https://github.com/lxqt/pcmanfm-qt/issues/945. You could follow the progress there.

**Comment by Rivers47** [comment]
> Show the filter-bar with `Ctrl+B` and filtering won't be done in the view.

I was really annoyed that pcmanfm-qt won't automatically type into filter when I type all of a sudden. Turns out it's based on whether toggle the filter bar with Ctrl+B... Where can I learn about all these shortcuts?

**Comment by tsujan** [comment]
> Where can I learn about all these shortcuts?

On menus. `Ctrl+B` is shown in View → Toolbars → Permanent filter bar.

The shortcuts that can't be displayed anywhere are in the "Hidden shortcuts" dialog, as @stefonarch said. All in all, nothing is hidden.

**Comment by isf63** [comment]
Why not have a tiny search bar to the right of the path? 
![Unsaved Image 1](https://github.com/user-attachments/assets/5fcd671e-8295-4067-8069-c6ab586a293f)

**Comment by tsujan** [comment]
> Why not have a tiny search bar to the right of the path?

Terrible design, for a number of reasons ;) The filter string might not be completely visible; the space of path-buttons would become smaller; there can be a menu button at that position;...
