### ISSUE TITLE
Feature request: Intelligently extracting archives

### ISSUE THREAD

**Issue by Val6789** [lxqt/pcmanfm-qt#749]
When extracting a folder using the "Extract here" option, pcmanfm-qt will extract all the files in the archive to the current directory, but if the archive contains multiple files in its root, all these files will be extracted to the current directory. If the directory already contains many files, then the extracted files will be mixed with the already-present files, making it difficult to find the files that were extracted.

I suggest that, **should an archive with multiple files in its root be extracted using the "Extract here" command, that all these files be extracted in a new subdirectory** instead of the current folder so that the user may easily find all the extracted files together.

This behavior is the way xfce's Thunar extracts files when using its "Extract here" command and I think that having the same behavior in pcmanfm-qt would make the program more user-friendly.

**Comment by tsujan** [comment]
That's what an archiver may do; it isn't related pcmanfm-qt. For example, I made Arqiver ensure an appropriate extraction directory and will try to do the same thing in lxqt-archiver later.
