### ISSUE TITLE
Emblem for trusted executables?

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#751]
Now that executables can have a "trust" flag, the question arises as whether their icons should have a special emblem.

I don't think a "trust" emblem is necessary because the user clicks on the executable and sees what happens, without any side effect. However, provided that an emblem is easy to add, its code is simple, and it doesn't add to the app's weight, why not? The emblem can be "emblem-default", which exists in most icon sets.

**Comment by tsujan** [comment]
I intentionally didn't use emblems for marking trusted files for 2 reasons: (1) There's no need to a reload with the "trust" metadata; (2) More flexibility.

As for (2), we are free to do several things with emblems. For example, Dolphin's method may be acceptable: We might be able to add "dialog-warning" as an emblem to *user* desktop files that are *not* trusted by the user yet and leave the icons of other desktop files an executables as they are. Users could also trust root desktop files or executables, of course, but the usual usage is about a desktop file in home.

**Comment by agaida** [comment]
Marking not trusted desktop file seems do be a good idea - will prevent some bug reports

**Comment by tsujan** [comment]
Generalized it to all deletable untrusted desktop files -- not just those in the user's home -- as in Dolphin.
