### ISSUE TITLE
set/unset file trust from command line

### ISSUE THREAD

**Issue by agaida** [lxqt/pcmanfm-qt#754]
@tsujan - How to do thes?

**Comment by tsujan** [comment]
Oh, that's possible directly with `gio set` but the folder should be reloaded afterward. Let me find the correct command and tell you...

**Comment by tsujan** [comment]
OK, the "trust" attribute can be set by:
```sh
gio set $FILE_PATH -t string metadata::trust "true"
```
And it can be unset by:
```sh
gio set $FILE_PATH -t unset metadata::trust
```

Please note that if you want to set/unset the "trust" flag for multiple files, it's already possible by selecting and right-clicking them. Even if the selection contains non-executables, if you right click on an executable among the selected files and check "Trust selected executables", it'll be done correctly. The command-line is blind in this regard (although that's harmless).

**Comment by tsujan** [comment]
Don't forget to reload the folder if you use command-line (with `xte 'key F5'` and if the tab has focus, for example).

**Comment by agaida** [comment]
nah - i need it for iso builds - so the problem with the reload is not that relevant :D

**Comment by tsujan** [comment]
Reload is needed iin this case only when the folder is already open (loaded).

ISO? No metadata (emblem included) is preserved when copied. Each user should set them, either through an app (like pcmanfm-qt) or with command-line and by using custom actions of pcmanfm-qt. Two users could trust different desktop files or executables.

**Comment by agaida** [comment]
not nice :)

**Comment by tsujan** [comment]
Quite conversely, metadata are nice because they are user-specific.

**Comment by agaida** [comment]
ok, the informations are located in ~/.local/share/gvfs-metadata - should have a closer look how this can work for a installation - i really want some desktop items trusted in a fresh installed system. I think a calamares script should do the trick

**Comment by tsujan** [comment]
> ok, the informations are located in ~/.local/share/gvfs-metadata

Exactly.

Seen from another angle, if the such metadata ("trust" and "emblem") weren't user-specific, they couldn't be set on root files by users. I use emblems especially for marking files temporarily; another user might not want to see them marked.

As for desktop files that we might want to be trusted for all users, they should come in the code. For example, if we put a trash/computer/documents icon on Desktop in future, we should let users click on it without prompt by adding some code (not necessarily metadata) and we shouldn't trust other desktop files that supposedly do the same thing.... That needs some thought but, for now, *we* don't put any desktop file on Desktop and our Trash icon in pcmanfm-qt's side-pane isn't a desktop file.

**Comment by agaida** [comment]
i put some file to the Desktop of my live images - the installer, irc shortcut, manual :) - no problem, i can trust the files when i install them.
