### ISSUE TITLE
Switch focus to newly opened tab after clicking File > New Tab or New Tab icon

### ISSUE THREAD

**Issue by bignmllc** [lxqt/pcmanfm-qt#757]
Similar to how the File > New Window menu option automatically moves focus to the new window, it would be more convenient if the File > New Tab or New Tab icon would automatically move focus to the newly opened tab, instead of keep focus on the currently open tab. This would prevent having to click on the tab itself to correct the focus each time. It may be a small single-event convenience, but it happens many times a day in my work and becomes very annoying. If keeping with legacy behavior is needed, maybe this functionality can be added as an option in Edit > Preferences > Behavior as a checkbox option.

##### Expected Behavior
When clicking on the File > New Tab menu option, or on the New Tab icon in the iconbar, after the new tab is created, it automatically moves the display and focus to that tab.

##### Current Behavior
When the File > New Tab menu option or New Tab icon is clicked, the display and focus remains in the currently opened tab.

##### Possible Solution
Make it the new default behavior (simplest solution), or add an option to enable it in the Edit > Preferences > Behavior checkbox options.

##### Context
Many times when switching from one task to another, a file has been cut and pasted to the wrong folder, or even the wrong version of a file in a separate folder got modified by editing by mistake.

##### System Information

$ uname -a
Linux asusubuntu16 4.15.0-32-generic #35~16.04.1-Ubuntu SMP Fri Aug 10 21:54:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Distribution & Version: 
Ubuntu 16.04 64-bit
* Kernel: 
4.15.0-32-generic
* Qt Version: 
$ qmake --version
QMake version 2.01a
Using Qt version 4.8.7 in /usr/lib/x86_64-linux-gnu
* lxqt-build-tools Version: 
Unknown
* libqtxdg Version:
libqtxdg0 0.5.2-4build1 (from synaptic package manager)
* libfm-qt Version:
libfm-qt2 0.10.0-20151214-2 (from synaptic package manager)
* Package version: 
pcmanfm-qt 0.10.1-2 (from synaptic package manager)

**Comment by tsujan** [comment]
> it would be more convenient if the File > New Tab or New Tab icon would automatically move focus to the newly opened tab

It already does but the version of pcmanfm-qt you have is a relic from remote pasts.
