### ISSUE TITLE
Edit the Open with submenu in PCManFM-qt

### ISSUE THREAD

**Issue by hollysheep** [lxqt/pcmanfm-qt#758]
##### Expected Behavior
Edit the "Open with" Submenu so that only the desired applications are displayed and sort them.

##### Current Behavior
Many applicatiosn are displayed here with a confused sort order.

##### System Information
* Distribution & Version: Ubuntu 18.04
* Kernel: 4.15
* Qt Version: Qt5

I can't find a solution for edit the open with submenu in PCManFM. I want to delete some applications and sort the applications. how can i do this? i use PCManFM 0.13.1 on Xubuntu 18.04.

**Comment by tsujan** [comment]
That isn't related to pcmanfm-qt specifically and can be done by changing file associations in any way.

**Comment by tsujan** [comment]
Also see this: https://github.com/lxqt/lxqt/issues/1546

Until it's fixed, you could do it manually. There are many pages on the Internet that explain it.
