### ISSUE TITLE
Change icon name for thumbnails button

### ISSUE THREAD

**Issue by varlesh** [lxqt/pcmanfm-qt#771]
It's strange use icon `dialog-information` for thumbnails:
`ui.actionThumbnailView->setIcon(QIcon::fromTheme(QLatin1String("dialog-information"), style()->standardIcon(QStyle::SP_FileDialogInfoView)));`

![image](https://user-images.githubusercontent.com/8083855/45135283-957a1800-b1af-11e8-8e1f-b20bbebd77e4.png)

I think better use icon name `view-preview`

**Comment by varlesh** [comment]
with Breeze icon theme:
![image](https://user-images.githubusercontent.com/8083855/45135461-92cbf280-b1b0-11e8-8f2d-49159d6beb4f.png)

**Comment by tsujan** [comment]
Both are acceptable, IMO, but `view-preview` might be better.

**Comment by tsujan** [comment]
Back to this:

GTK icon sets usually don't have `view-preview`. However, they don't have `view-list-text`, `view-list-details`,... either. That's not our problem. After all, we also have Qt's fallback icons there.

So, I'll change that icon to `view-preview` soon, as is suggested here.
