### ISSUE TITLE
Root instance -- dbus-launch is needed sometimes

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#774]
Most probably, this isn't a bug but the fact is that, whether on Debian (years ago) or on Manajro (now), it has happened intermittently:

Sometimes `lxsudo %s` is enough for opening a root instance of pcmanfm-qt and sometimes `lxsudo dbus-launch %s` is needed.

Understandably, `lxsudo dbus-launch %s` always works but I have no idea why `lxsudo %s` stops and starts working other than that it's somehow related to system updates.

**Comment by lhorace** [comment]
Well, if you give me a few weeks, _real world usage_, to catch it when it's broken. And see if I can reliably reproduce it. I can help out and update this bug report.

**Comment by tsujan** [comment]
@lhorace If you want to test pcmanfm-qt, please use the latest git versions of libfm-qt and pcmanfm-qt because, most of the time, the latest releases are far behind them.

**Comment by lhorace** [comment]
@tsujan Would this work https://aur.archlinux.org/packages/pcmanfm-qt-git ?

**Comment by agaida** [comment]
yes

**Comment by lhorace** [comment]
```
[owner@owner-desktop]: ~>$ pcmanfm-qt --version
pcmanfm-qt 0.13.0
[owner@owner-desktop]: ~>$ pacman -Qs pcmanfm-qt
local/pcmanfm-qt-git 0.13.0.202.g7014a03-1
    The LXQt file manager, Qt port of PCManFM
```

If `lxsudo pcmanfm-qt` breaks during my testing, will update!

**Comment by lhorace** [comment]
I rebooted last night and now majority of my icons are missing, see https://github.com/lxqt/lxqt/issues/1587. I'm going to downgrade both packages and observe if that resolves it on my end.

**Comment by tsujan** [comment]
@lhorace If you upgrade one component of LXQt without others, you'll break it (like KDE, Gnome,....). Instead of downgrading, you could upgrade your whole LXQt installation to git.

**Comment by eirenicon** [comment]
lxsudo dbus-launch %s worked for me on manjaro.

**Comment by tsujan** [comment]
> lxsudo dbus-launch %s worked for me on manjaro.

I changes the `question` tag to `bug` because this confuses users and is serious. We shouldn't expect them to know about  `dbus-launch`. @agaida, any idea what we should do here?

**Comment by agaida** [comment]
Nothing i guess - there is no need to run pcmanfm-qt as root first hand - really.

I would really prefer it if user would open chosen folders as root - we could make this working functionality more visible by adding the option to the context menu

**Comment by agaida** [comment]
![grafik](https://user-images.githubusercontent.com/1162845/48233929-8f730400-e3b7-11e8-8909-2b2ba4d48d60.png)

**Comment by tsujan** [comment]
I know but that doesn't happen sometimes (for example, now), whether under Manjaro or under Debian (when I had it). Let's leave this open for now.

**Comment by tsujan** [comment]
No one's problem. Closing.

**Comment by dariusity** [comment]
Didn't work on Manjaro, worked on Lubuntu.

**Comment by tsujan** [comment]
I'll add a short explanation to the GUI of pcmanfm-qt to prevent confusions.

**Comment by tsujan** [comment]
Done in https://github.com/lxqt/pcmanfm-qt/pull/927
