### ISSUE TITLE
On 0.13.0 sorting is not working on detailed list view

### ISSUE THREAD

**Issue by drum445** [lxqt/pcmanfm-qt#775]
On version 0.13.0 - Lubuntu LXQt Daily Image
When using the detailed list view the default sort order appearing is descending and any changes are not preserved after close. This was not an issue in 0.12.0

##### Expected Behavior
When using detailed view the default sort should be file name in ascending order.
When switching between the sort orders the correct order should be applied

##### Current Behavior
Default sort order is descending which differs from 0.12.0
When changing the sort order the opposite is being applied, so if I apply an ascending sort to the file name Videos will appear before Documents for example (this is based on the arrow direction shown in the column header)

##### Possible Solution
Copy the behavior from 0.12.0 for the detailed list view, could be happening in other views but this is where I have noticed it

**Comment by drum445** [comment]
![image](https://user-images.githubusercontent.com/37041178/45360967-e1bac300-b5c8-11e8-94b8-e50954ed08c5.png)

**Comment by tsujan** [comment]
Thanks for taking time and reporting but it isn't the case with the latest git pcmanfm-qt. I suspect something may be wrong in Lubuntu's LXQt Daily Image.

**Comment by drum445** [comment]
Are we currently on 0.13.0?

**Comment by tsujan** [comment]
0.13.0 is is latest release so far but there are 191 commits after it.

**Comment by agaida** [comment]
@tsujan - nobody knows the version of Lubuntu LXQt - lots of wild backported upstream development, it make nearly no sense to waste time on trying to debug things - only for very obvious cases. And thats the reason why users should use their distribution bug tracker to file bugs. The maintainers have to triage bugs before they  file bugs here.

So: Nothing much we can and should do.

**Comment by tsujan** [comment]
@agaida Thanks!

Since I hunt for any kind of bug, sometimes I may pay attention to reports about suspicious versions too. When the reported issues don't exist in the latest git, I close the reports. So, almost no time is wasted -- just a check :)

**Comment by agaida** [comment]
i'm fine with :D

**Comment by tsujan** [comment]
> you never know

Correct.

**Comment by drum445** [comment]
Just to finish this, I found that if you sort via the View option in the menu bar then it will preserve the change. If you sort via context menu it does not

Thanks
