### ISSUE TITLE
Not show number selected all files/folders

### ISSUE THREAD

**Issue by varlesh** [lxqt/pcmanfm-qt#783]
##### Current Behavior

PCManFM with selected all files show text:
` %1 objects are highlighted`

![screenshot_20180926_093058](https://user-images.githubusercontent.com/8083855/46059179-320c5600-c16f-11e8-9d43-896bbf784dce.png)

##### Steps to Reproduce (for bugs)
1.  open PCManFM
2. selected all files (CTRL+A)
3. see satus on toolbar

##### System Information

* Distribution & Version: Manjaro KDE
* Kernel: 4.17.19-1-MANJARO
* KDE: 5.13.5
* Qt Version: 5.11.1
* lxqt-build-tools Version: 0.5.0-1
* libqtxdg Version: 3.2.0-3
* libfm-qt Version: 0.13.0-1
* pcmanfm-qt:  0.13.0

**Comment by tsujan** [comment]
That should be a problem in the Russian translation.

![correct](https://user-images.githubusercontent.com/981076/46080006-8fbb9500-c1a5-11e8-975e-bb3b66d85105.png)

It is out of out control. Could you correct it?

**Comment by palinek** [comment]
Note: https://github.com/lxqt/pcmanfm-qt/blob/master/pcmanfm/translations/pcmanfm-qt_ru.ts#L1295

**Comment by tsujan** [comment]
Anyone knowing Russian a little? @agaida, you had it in school.

**Comment by agaida** [comment]
That has nothing to do with knowledge about the language - btw, school was thirty years ago:
```
        <source>%n item(s) selected</source>
        <translation>
            <numerusform>%1 объект выделен</numerusform>
            <numerusform>%1 объекта выделено</numerusform>
<numerusform>%1 объектов выделено</numerusform>
```
Will fix it.

**Comment by tsujan** [comment]
Thanks :)

**Comment by agaida** [comment]
![](https://i.imgur.com/Pd46PIB.png)
