### ISSUE TITLE
search very slow

### ISSUE THREAD

**Issue by simplelinuxuser** [lxqt/pcmanfm-qt#795]
The search in pcman is very slow, when I search in nautilus it even searches inside text file content and immediately return result. pcman searches for minutes (even without checking the file content tick)

**Comment by agaida** [comment]
Thanks for providing this fine report as an example of "How to write meaning- and useless reports". And yes I'm serious about. Some hints:
* It isn't cool to delete the bug template first hand. If you do so we will close the bug without any processing.
* Please don't aswer to this no closed bug, it was not meant serious first hand, please don't wast more of our time. TIA.

**Comment by tsujan** [comment]
KDE and Gnome have "search daemons" (the name may not be correct). You may have seen high CPU usage or I/O without a "known" reason in them sometimes. In short, they've search before and just show the result to the user.

**Comment by tsujan** [comment]
@agaida Sorry! We commented at the same time and I was going to close it.

**Comment by agaida** [comment]
No problem, i forget to add some labels.
