### ISSUE TITLE
view settings need clean up

### ISSUE THREAD

**Issue by wxl** [lxqt/pcmanfm-qt#799]
Personally, I could live without the "Preserve Settings for this Folder" option. Global options are a requirement. We must have that first. Right now, we do, but only if we set it across a bunch of different places.

Once we have that fixed, the "Preserve Settings for this Folder" could be useful as an override to global settings, but as it stands, it doesn't do what it claims to do. Moreover, I see a reasonable concern about knowing which setting a particular folder has and where they're coming from.

Both of these things contribute to confusion about how to set all of the different settings. More specifically:

 1. "Preserve Settings for this Folder" does not preserve all settings. For example, hidden files.
 1. "Preserve Settings for this Folder" also needs a reset and a reset all button.
 1. The default view as set by the menu does not persist in new instances— one must set it in preferences.
 1. Changing the default view in preferences does not make a change in the current window.
 1. Hidden and sorting options are not exposed in preferences, though they do persist in new instances.
 1. There should be a clear indication that a folder is using overrides to the globals, which the checkbox for "Preserve Settings for this Folder" indicates, but making that more clear would be nice.
 1. Allowing an option to apply settings to a whole tree rather than just a folder might be a nice addition.

**Comment by tsujan** [comment]
IMO, only (2) and (4) are valid (although not urgent) -- didn't understand (7).

> "Preserve Settings for this Folder" does not preserve all settings. For example, hidden files.

It isn't supposed to. It preserves what's on its menu.

> The default view as set by the menu does not persist in new instances

That's PCMan's choice and shouldn't be changed. We had an old discussion and I said the same thing but agreed with his viewpoint at last. Its advantage is that the user may NOT want to change the view permanently -- if he wants, he could do so in Preferences . This is a real use case I enjoy a lot. Also see https://github.com/lxqt/pcmanfm-qt/issues/590#issuecomment-415830795

> Hidden and sorting options are not exposed in preferences

They don't need to. Duplicate settings can't be good.

> There should be a clear indication that a folder is using overrides to the globals, which the checkbox for "Preserve Settings for this Folder" indicates, but making that more clear would be nice.

The toolbar buttons tells about the view. After using this feature for years (even a year before it was officially implemented), I haven't seen any practical need for more than that.

> Allowing an option to apply settings to a whole tree rather than just a folder might be a nice addition.

I didn't understand what you meant by "whole tree".

**Comment by tsujan** [comment]
Oh, if by "whole tree" you mean "recursively" (a folder and all its subfolders), that could easily become CPU intensive.

However, there's one case that may not be CPU intensive: applying permissions recursively. It should be investigated and I think there's already a report about it.

**Comment by wxl** [comment]
> > "Preserve Settings for this Folder" does not preserve all settings. For example, hidden files.
> It isn't supposed to. It preserves what's on its menu.

But the option to show hidden files is on the menu.

> > The default view as set by the menu does not persist in new instances
> That's PCMan's choice and shouldn't be changed. 

The problem is that the settings scattered all over the place makes it really confusing as to how to actually use them. Also the fact that OTHER settings DO persist in new instances is inconsistent and thus confusing.

> > Hidden and sorting options are not exposed in preferences
> They don't need to. Duplicate settings can't be good.

Why not? Having more than one way to do things is ALWAYS good. And besides, we have duplicate settings for the view.

**Comment by wxl** [comment]
> Oh, if by "whole tree" you mean "recursively" (a folder and all its subfolders), that could easily become CPU intensive.

That's what I mean and I see your point, but it's certainly something that could be dealt with.

**Comment by tsujan** [comment]
> But the option to show hidden files is on the menu.

Oh, you're right!

But that's not the case for me ;) Years ago, I had a big disagreement with PCMan and made a personal patch that allowed to save views and other settings separately from 2 checkboxes on their corresponding submenus. I update and apply the patch every time I upgrade pcmanfm-qt. That's why I didn't get your point.

I really don't know how that can be done with the current GUI. Maybe, it should be tolerated. Practical suggestions are welcome.

> The problem is that the settings scattered all over the place makes it really confusing...

You'll get used to how things work in pcmanfm-qt after a while; then, it won't be confusing. PCMan told me that the same settings existed in the gtk version. Not all file managers should have the same properties. This property is very cool, IMO.

> Why not? Having more than one way to do things is ALWAYS good.

Bloating the GUI for no good reason isn't good. LXQt is neither like KDE nor like Gnome.

**Comment by wxl** [comment]
> You'll get used to how things work in pcmanfm-qt after a while; then, it won't be confusing. 

Except where it frustrates users and they move on to something else that isn't confusing.

> PCMan told me that the same settings existed in the gtk version. 

And so because something has always been such-and-such way, it should stay that way? That logic escapes me. 

> Not all file managers should have the same properties. This property is very cool, IMO.

Confusion is a terrible property.

> Bloating the GUI for no good reason isn't good.
> Practical suggestions are welcome.

Then let's simplify:

 1. Get rid of any view settings in preferences.
 1. Make all of the view settings from the menu apply globally.
 1. Ensure that the folder settings apply to all preferences.

That fixes the problems. At that point new features (2, 7 above) can be added.

**Comment by tsujan** [comment]
> And so because something has always been such-and-such way...

I mentioned that it's useful -- I even searched for and added a link (while I was busy with something else).

I'm afraid I disagree with your point of view -- it seems too personal to me -- except for the 2 (or 3) points mentioned above.

**Comment by wxl** [comment]
> I mentioned that it's useful 

What are you saying is actually useful?

> I was busy with something else

Maybe this is the reason why you seem to simply be dismissing it altogether without any good arguments except for "this is the way it is."

> it seems too personal to me

This was brought to my attention by a user. I asked @agaida and he agreed it's confusing. I think maybe your perspective is too personal and you should consider other users.

**Comment by tsimonq2** [comment]
I absolutely agree with @wxl. Both as a general LXQt suggestion and a Lubuntu suggestion I've seen it come up multiple times.

**Comment by agaida** [comment]
I guess there can be some improvements - and yes, the current behaviour can be/is a bit confusing - but as i wrote in the channel, the whole thing will need some thoughts, opinions, discussions, time and testing. Code too to do it right™ - so the situation right now is far from perfect, but we should take the needed time and all the other things. And please remember:

![](https://www.brainyquote.com/photos_tr/en/h/hlmencken/129796/hlmencken1-2x.jpg)

**Comment by tsujan** [comment]
> Then let's simplify: ...

I'm not good at simplification.

> Maybe this is the reason why you seem to simply be dismissing it altogether without any good arguments 

Quite possible.... I'm always busy with something.

> This has never been an issue for me...

I understand; you've never used it, so you see it better.

**Comment by agaida** [comment]
KISS has two meanings
a) Keep it simple, stupid.
b) Keep it stupid, simple.

We should chose a). And this will be a hard one and will need  lot of discussions and testing to do it right™,

**Comment by wxl** [comment]
Right, so let's not shut down the discussion before it started! ☺

**Comment by tsujan** [comment]
FYI,
I'll never remove a feature PCMan has put into pcmanfm-qt. The ability to have different views in different tabs or split views *temporarily* is one of those features, whether users start to use it or they get "confused" by it. It isn't rocket science to change one's perspective a little.

**Comment by wxl** [comment]
@tsujan having the option to both have a particular set of settings permanently AND a set that are temporary is exactly what this whole discussion is about. The problem is a lack of consistency. If the Preferences was used for global settings and the View menu for temporary settings, there would be no issue and no need to remove anything. Also not rocket science, but doesn't introduce confusion.

**Comment by tsujan** [comment]
> having the option to both have a particular set of settings permanently AND a set that are temporary is exactly what this whole discussion is about.

No, it isn't because it's already possible.

**Comment by wxl** [comment]
It's possible, but not in a way that is not confusing. That's the problem that needs fixing.

**Comment by tsujan** [comment]
> It's possible, but not in a way that is not confusing

Mentioning "rocket science" was about that "confusion", as if users are stupid and can never understand how an app works.

**Comment by wxl** [comment]
You're failing to accept the fact that despite your most ardent belief, folks don't just get it. This is not a theory. This has proven itself to be true.

**Comment by tsujan** [comment]
> folks don't just get it

Some may not; most do. Proof? It was so in PCManFM for years and no body was against it so "ardently".

**Comment by tsujan** [comment]
Pragmatically speaking:

If someone makes a PR that (1) doesn't sacrifice any feature to prevent "confusion", (2) isn't buggy, and (3) other devs -- especially PCMan -- approves of it, then it'll be merged, most probably. I'm not that someone.

**Comment by tsujan** [comment]
My "ardent belief" (found the link): https://github.com/lxqt/pcmanfm-qt/pull/391#issuecomment-242115734 (the last paragraph) and PCMan's reply, especially No 4. I quote him:

"Till now, we received no complaints from the users. Sometimes you only want to change the view of current tab temporarily, but this affect all new tabs, which can be annoying and confusing, too."

Now, if this is so confusing to a user that the confusion is never transformed to understanding, he/she won't use pcmanfm-qt.

**Comment by agaida** [comment]
/me whistle a bit - and say nothing bad about users and .... :sunglasses:

**Comment by tsujan** [comment]
> and say nothing bad about users

I see them intelligent, unless the opposite is proved. "Caring" too much for users results in Gnome.

**Comment by agaida** [comment]
bad bad tsujan - you stealing my joke - so, i see no problem, guess what the main ubuntu desktop is.

**Comment by tsujan** [comment]
> you stealing my joke

I have an old patent for it ;)

**Comment by wxl** [comment]
> It was so in PCManFM for years and no body was against it so "ardently".

Neither was anyone against speculative execution since, uh, what? 1995? Or what about the fact that the average Linux bug doesn't get noticed for [5 years](https://outflux.net/blog/archives/2016/10/18/security-bug-lifetime/). That's proof of nothing. It also assumes, erroneously, that everyone takes advantage of the feature.

> if this is so confusing to a user that the confusion is never transformed to understanding, he/she won't use pcmanfm-qt.

Agreed. And right now, it's confusing. You're arguing that some other solution which I'm not advocating for is also confusing. I don't disagree with that. Maybe we should move past that?

Right now we have a system where for one setting, you go to one place to affect it temporarily and in another place to affect it permanently, but for a different setting, you can only affect it permanently and it's in the place where the other setting is affected temporarily. That is anti-intuitive.

**Comment by tsujan** [comment]
> Neither was anyone against speculative execution sinc

Nor relevant, unless arbitrarily and without reading comments.

> Agreed. And right now, it's confusing.

Nothing can be just confusing; it may be confusing to *someone*.

> Right now we have a system... 

It isn't so. We don't have such a system. I started to doubt that you even don't use pcmanfm-qt.

**Comment by wxl** [comment]
> It isn't so. We don't have such a system. I started to doubt that you even don't use pcmanfm-qt.

I'm doubting the same from you. How do you temporarily change showing hidden settings? How do you permanently change it? Is it in the same place where you permanently change settings related to the view mode?

**Comment by tsujan** [comment]
We suppose that users have seen a computer before and know elementary things about what's senseless and what's not. If not, they'll learn.

**Comment by wxl** [comment]
> We suppose that users have seen a computer before and know elementary things about what's senseless and what's not. If not, they'll learn.

Then let's forget GUIs and just use the command line.

**Comment by tsujan** [comment]
> Then let's forget GUIs and just use the command line.

Or Gnome. I love Gnome; it's useful for such cases.

**Comment by teward** [comment]
@wxl @tsujan Please stop the bickering...

**Comment by wxl** [comment]
Since I'm bringing up something that's not even a problem, answer the questions I proposed.

 1. How do you temporarily change showing hidden settings? 
 1. How do you permanently change it? 
 1. Is it in the same place where you permanently change settings related to the view mode?

**Comment by tsujan** [comment]
> @wxl @tsujan Please stop the bickering...

It isn't important to me but, apparently, it is a big bug to the other party. Let me answer to him for the last time!

@wxl I've read your comments. Except for the point I mentioned near the beginning of this page, your opinion isn't practical to me -- it's just perfectionistic and several things are ignored in it. As I said in https://github.com/lxqt/pcmanfm-qt/issues/799#issuecomment-435429053, if someone is confused, they could make a clean PR or convince someone else to do it for them.

**Comment by wxl** [comment]
Striving towards perfection is bad? What's ignored?

**Comment by tsujan** [comment]
Some of the properties that have been changed, either recently or in the last 2 years:

 * When a view is customized, an icon is shown on its tab. The customization options appear in the tab's right-click menu too.
 * A customized view preserves the changes that are made to it. The hidden state is also preserved.
 * Now it's also possible to customize views recursively.
 * Changing the mode of a *non-customized* view will remain temporary, as it is now. Consider it as an old, useful "peculiarity" of pcmanfm-qt. The mode can be changed globally (for non-customized views) in Preferences. But sorting settings will be remembered.

If you have other feature requests in this regard, please report them separately.
