### ISSUE TITLE
Preferences dialogue doesn't has a selected row in the side list in the first run

### ISSUE THREAD

**Issue by micrococo** [lxqt/pcmanfm-qt#801]
When you open the Preferences dialogue for the first time, there row for the current settings page is not selected.

##### Expected Behavior
The row for the current settings page should be selected.

![pcmanfm-qt-preferences_good](https://user-images.githubusercontent.com/7717273/47859983-cb263080-ddef-11e8-804c-6e58245769a4.jpg)

##### Current Behavior
The row for the current settings page is not selected.

![pcmanfm-qt-preferences_bad](https://user-images.githubusercontent.com/7717273/47859988-ceb9b780-ddef-11e8-9e73-70ebf3e1a02a.jpg)

##### Possible Solution
Make the row for the current settings page selected on the first run.

##### Steps to Reproduce (for bugs)
1.  Just open the Preferences dialogue

##### Context
Always having a selected row in the list gives visual consistence to the application.

##### System Information
* Distribution & Version: openSUSE Tumbleweed
* Kernel: 4.18.15
* Qt Version: 5.11.2
* lxqt-build-tools Version: 0.5.0+git6.db12b99-26.1
* libqtxdg Version: 3.2.0+git12.7d7e6e7
* libfm-qt Version: 0.13.1+git276.ccd984f-275.2
* Package version: 0.13.0+git207.eda1e51

**Comment by tsujan** [comment]
Yes, it's better to select the first row.

**Comment by tsujan** [comment]
Fixed in https://github.com/lxqt/pcmanfm-qt/commit/ae3ddb9fbf0c86883a6e2d0b3226f24b3ec985a9

**Comment by micrococo** [comment]
Wow, that was fast! Thanks.
