### ISSUE TITLE
Trash should be not appear to be emty, if ...

### ISSUE THREAD

**Issue by agaida** [lxqt/pcmanfm-qt#817]
some deleted symbolic links are in trash:///

##### Expected Behavior
Icon should change

##### Current Behavior
It doesn't

##### Possible Solution
fix it

##### Steps to Reproduce (for bugs)
1. empty trash 
2. create a symlink on the desktop
3. delete the symlink

![](https://i.imgur.com/RDs4bAd.png)

##### Context
It's not so important. but the implementation should be complete

**Comment by tsujan** [comment]
Not reproducible here:

![trash](https://user-images.githubusercontent.com/981076/48491706-67fbbb80-e83d-11e8-9244-df9e294e04fd.png)

Do you use Lubuntu?  ;)

**Comment by agaida** [comment]
tststs - bad bad tsujan

**Comment by tsujan** [comment]
:D

Mysterious! I wonder how it's possible for Trash to be shown empty in your case; a symlink is a file.

**Comment by agaida** [comment]
maybe a glitch in my Installation - i just check this

**Comment by tsujan** [comment]
I don't think this can be an installation problem. *Please* don't lose that file! We should know what it is.

**Comment by agaida** [comment]
You really don't know my talent to mess up things ...

**Comment by tsujan** [comment]
Your or my talent aside, this may be a bug that I can't reproduce. I just want to know how a path with backslashes can be put into Trash as a name.

**Comment by tsujan** [comment]
Oh, unmounted USB drive? If it's about that, it's a gvfs peculiarity and isn't related to symlinks.

**Comment by agaida** [comment]
no - but i can reproduce the path-thing. Please don't beat me for that :) - btw, after rebuilding pcmanfm-qt again the trashbin conter works as expected, so it might be a wrong build of libfm-qt. Will make a little screencast.

Have found a little problem with the desktop icons handling too - we should start two new bugs and close this one as invalid and pebcak.

**Comment by tsujan** [comment]
> Have found a little problem with the desktop icons handling too - we should start two new bugs

Looking forward to those reports.

**Comment by agaida** [comment]
follow up # 1: https://github.com/lxqt/pcmanfm-qt/issues/818
