### ISSUE TITLE
path in undeleted files

### ISSUE THREAD

**Issue by agaida** [lxqt/pcmanfm-qt#818]
not much text, a screencast will make things clear.

####  Reproduce
1. create some files on the desktop
2. delete them - all things fine
3. undelete them - all things fine

#### Reproduce 2
1. delete the files
2. open the trashbin
3. drag and drop the deleted files to the desktop
4. use certain swearwords.

https://youtu.be/4O3FDM9Bqvc

**Comment by tsujan** [comment]
I did exactly as in your video, enjoyed especially step 4, *but nothing bad happened:* the file name didn't change, there was no trace of backslash, and both side-pane and desktop trash icons were correct -- in short, everything was normal.

Now, I think there's something wrong with Debian -- maybe, not LXQt deb packages.

**Comment by agaida** [comment]
ok, will test it now with arch :)

**Comment by tsujan** [comment]
I guess you believe me and there's no need for me to make a video.

**Comment by agaida** [comment]
no, i don't believe and has to see it myself :smile:  - And you are right. Strange.

**Comment by agaida** [comment]
i marked this one won't fix - because there is nothing that we can fix.

**Comment by tsujan** [comment]
OK. :) What can be the difference between Arch and Debian? gvfs packages are 1.38.1 here.

**Comment by tsujan** [comment]
They have the same version in sid :(

**Comment by agaida** [comment]
no clue
