### ISSUE TITLE
Preserve relative positions of (sticky) Desktop items with DND

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#821]
##### Expected Behavior

It'll be good if relative positions of dragged desktop items are preserved.
##### Current Behavior

Currently, if Desktop items are dragged and dropped, they'll be treated like other items and will be positioned from top to bottom and then, left to right.
##### Possible Solution

I think it's tricky. I have to idea about an implementation yet. Maybe, KDE's source can be consulted (but which source?).
##### Steps to Reproduce

Drag 2 sticky Desktop items and drop them to an empty position far from other items and near the middle of the screen. Then, one of them will be put below the other, regardless of the relative positions they had before (because there's nothing in the code to do otherwise).

**Comment by agaida** [comment]
+1

**Comment by tsujan** [comment]
I got an idea: theoretically, we know the positions of the selected items, the drag start position (?), and the drop position; so, we should be able to arrange dropped items accordingly if Qt remains friendly.

**Comment by agaida** [comment]
we have a set of icons and a constant delta for x and y - should be easy to iterate. and usual screen sizes limit the count of the item in a natural way - should be easy to iterate

**Comment by tsujan** [comment]
Yes, the logic is simple. We should know the previous positions of all dragged items, where the drag is started, and where the drop happens. Theoretically, we know all of it. If an item goes beyond the screen, its sticky state will be forgotten. 

A clean implementation will take time though.

**Comment by agaida** [comment]
not release critical, but really nice to have

**Comment by tsujan** [comment]
I'll start to work on it tomorrow. It shouldn't be harder than desktop Trash -- at least, I hope so.

**Comment by tsujan** [comment]
It was so easy: https://www.dropbox.com/s/qyrc3u7e8o45yhs/desktop_DND.mkv?dl=0

I should check if I've forgotten anything, clean the code and do some tests. It'll be definitely ready before the next release :)
