### ISSUE TITLE
if a removable drive is put in a usb port and pcmanfm-qt is clicked afterwards, it just shows operation pending.

### ISSUE THREAD

**Issue by shirishag75** [lxqt/pcmanfm-qt#824]
##### Expected Behavior

Whenever you put the removable drive in, you should get a notification to mount the removable drive . 

##### Current Behavior
If a removable drive is put in a usb port and pcmanfm-qt is clicked afterwards, it just shows operation pending. Even if I click on a mount option it says Operation is pending. Leaving the session and coming back nothing to alleviate the situation. 

There is another part to it as well, sometimes, it does mount the removable drive but gives no notification of the same, so there is no clue why it got mounted on one time and not the other time ?

The only workaround is to shut down the system, removed the removable drive,  Start the system, login to the lxqt session, click on pacmanqt-fm and ONLY then put the removable drive in. 

##### Possible Solution

Whenever you put the removable drive in, you should get a notification to mount the removable drive, 
irrespective of whether or not pcmanfm-qt is present on not. 

##### Steps to Reproduce (for bugs)

The easiest way to reproduce it is to put the removable drive once you are in session for sometime. 

##### System Information

-- System Information:
Debian Release: buster/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable-debug'), (500, 'testing-debug'), (500, 'unstable'), (1, 'experimental-debug'), (1, 'experimental')
Architecture: amd64 (x86_64)

Kernel: Linux 4.18.0-2-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages pcmanfm-qt depends on:
ii  dbus-user-session [default-dbus-session-bus]  1.12.10-1
ii  dbus-x11 [dbus-session-bus]                   1.12.10-1
ii  desktop-file-utils                            0.23-4
ii  libc6                                         2.27-8
ii  libfm-qt6                                     0.13.2~281-g9af4808-1
ii  libglib2.0-0                                  2.58.1-2
ii  libqt5core5a                                  5.11.2+dfsg-5+b1
ii  libqt5dbus5                                   5.11.2+dfsg-5+b1
ii  libqt5gui5                                    5.11.2+dfsg-5+b1
ii  libqt5widgets5                                5.11.2+dfsg-5+b1
ii  libqt5x11extras5                              5.11.2-2
ii  libstdc++6                                    8.2.0-9
ii  libxcb1                                       1.13.1-1
ii  lxqt-sudo                                     0.13.1~87-gabcfa04-1

Versions of packages pcmanfm-qt recommends:
ii  breeze-icon-theme  4:5.51.0-1
ii  eject              2.1.5+deb1+cvs20081104-13.2
ii  faenza-icon-theme  1.3.1-1
ii  ffmpegthumbnailer  2.1.1-0.2+b1
ii  gvfs-backends      1.38.1-1
ii  gvfs-fuse          1.38.1-1
ii  lximage-qt         0.14.0~155-gdaed6d3-1
ii  lxqt-policykit     0.13.1~52-g6485024-1
ii  lxqt-qtplugin      0.13.1~4-g7065c43-4
ii  oxygen-icon-theme  5:5.51.0-1
ii  pcmanfm-qt-l10n    0.13.1~224-gf059869-1

Versions of packages pcmanfm-qt suggests:
pn  cdtool       <none>
ii  libfm-tools  1.3.0.2-1

-- no debconf information

**Comment by tsujan** [comment]
> The easiest way to reproduce it is to put the removable drive once you are in session for sometime.

I'd see it if it happened just once because I use usb sticks a lot.

If you mean something else, please describe it in a step-by-step way and, if it's reproducible, I'll reopen this report.

**Comment by shirishag75** [comment]
It happens quite a lot on my end. I just don't know how to reliably reproduce it to get it fixed. I was thinking of using [strace](https://github.com/strace/strace)

**Comment by tsujan** [comment]
You said "pcmanfm-qt is clicked". What is clicked exactly? pcmanfm-qt is a window containing several widgets.

**Comment by shirishag75** [comment]
I meant clicking the shortcut which I have put in quicklaunch which in turn opens up the file-manager.
