### ISSUE TITLE
Cut items are not grayed out in list and compact modes

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#835]
This is an old problem and its fix is easy -- actually, I wanted to add a few lines of code after graying-out of cut files was implemented but, as usual, I for got it.

However, IMHO, it's better not to implement it before V0.14 is released because it should be tested for a while.

**Comment by agaida** [comment]
I'm fine with - such things can be deployed in a point release

**Comment by tsujan** [comment]
Oh, this isn't as simple as I thought: as far as the view isn't changed, everything seems OK with giving a translucent icon to `style->drawControl()` but, once the view is changed and toggled back to the detailed list/compact mode, a magic happens. A bug or an incomplete implementation? I still don't know.
