### ISSUE TITLE
pcmanfm-qt daemon uses 100%cpu

### ISSUE THREAD

**Issue by sobotkap** [lxqt/pcmanfm-qt#841]
Background process of pcmanfm-qt uses 100%cpu. 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                    
 7686 kf457     20   0  966980  47508  40712 R **106.7**   0.6   3:37.90 pcmanfm-qt  

##### Expected Behavior
Use less CPU for background process, which doesn't do anything useful. 

##### Current Behavior
Here is pstack 

Thread 8 (Thread 0x7f273bfff700 (LWP 7701)):
#0  0x00007f2767e45efd in syscall () at /lib64/libc.so.6
#1  0x00007f27686f3dcc in  () at /lib64/libQt5Core.so.5
#2  0x00007f27688b6319 in QMetaObject::activate(QObject*, int, int, void**) () at /lib64/libQt5Core.so.5
#3  0x00007f27686fe4bb in  () at /lib64/libQt5Core.so.5
#4  0x00007f2767d3458e in start_thread () at /lib64/libpthread.so.0
#5  0x00007f2767e4b6a3 in clone () at /lib64/libc.so.6
Thread 7 (Thread 0x7f2755435700 (LWP 7700)):
#0  0x00007f2767e45efd in syscall () at /lib64/libc.so.6
#1  0x00007f27686f3dcc in  () at /lib64/libQt5Core.so.5
#2  0x00007f27688b6319 in QMetaObject::activate(QObject*, int, int, void**) () at /lib64/libQt5Core.so.5
#3  0x00007f27686fe4bb in  () at /lib64/libQt5Core.so.5
#4  0x00007f2767d3458e in start_thread () at /lib64/libpthread.so.0
#5  0x00007f2767e4b6a3 in clone () at /lib64/libc.so.6
Thread 6 (Thread 0x7f2754c34700 (LWP 7699)):
#0  0x00007f2767e45efd in syscall () at /lib64/libc.so.6
#1  0x00007f27686f3dcc in  () at /lib64/libQt5Core.so.5
#2  0x00007f27688b6319 in QMetaObject::activate(QObject*, int, int, void**) () at /lib64/libQt5Core.so.5
#3  0x00007f27686fe4bb in  () at /lib64/libQt5Core.so.5
#4  0x00007f2767d3458e in start_thread () at /lib64/libpthread.so.0
#5  0x00007f2767e4b6a3 in clone () at /lib64/libc.so.6
Thread 5 (Thread 0x7f2757524700 (LWP 7691)):
#0  0x00007f2767e40421 in poll () at /lib64/libc.so.6
#1  0x00007f27685175a6 in  () at /lib64/libglib-2.0.so.0
#2  0x00007f2768517962 in g_main_loop_run () at /lib64/libglib-2.0.so.0
#3  0x00007f27683f379a in  () at /lib64/libgio-2.0.so.0
#4  0x00007f276854048a in  () at /lib64/libglib-2.0.so.0
#5  0x00007f2767d3458e in start_thread () at /lib64/libpthread.so.0
#6  0x00007f2767e4b6a3 in clone () at /lib64/libc.so.6
Thread 4 (Thread 0x7f2757d25700 (LWP 7690)):
#0  0x00007f2767e40421 in poll () at /lib64/libc.so.6
#1  0x00007f27685175a6 in  () at /lib64/libglib-2.0.so.0
#2  0x00007f27685176d0 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#3  0x00007f2768517721 in  () at /lib64/libglib-2.0.so.0
#4  0x00007f276854048a in  () at /lib64/libglib-2.0.so.0
#5  0x00007f2767d3458e in start_thread () at /lib64/libpthread.so.0
#6  0x00007f2767e4b6a3 in clone () at /lib64/libc.so.6
Thread 3 (Thread 0x7f275dcb6700 (LWP 7688)):
#0  0x00007f2767e40421 in poll () at /lib64/libc.so.6
#1  0x00007f27685175a6 in  () at /lib64/libglib-2.0.so.0
#2  0x00007f27685176d0 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#3  0x00007f27688de813 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#4  0x00007f276888d17b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#5  0x00007f27686f5046 in QThread::exec() () at /lib64/libQt5Core.so.5
#6  0x00007f27697a6f89 in  () at /lib64/libQt5DBus.so.5
#7  0x00007f27686fe4bb in  () at /lib64/libQt5Core.so.5
#8  0x00007f2767d3458e in start_thread () at /lib64/libpthread.so.0
#9  0x00007f2767e4b6a3 in clone () at /lib64/libc.so.6
Thread 2 (Thread 0x7f275e6b2700 (LWP 7687)):
#0  0x00007f2767e40421 in poll () at /lib64/libc.so.6
#1  0x00007f27682a139f in  () at /lib64/libxcb.so.1
#2  0x00007f27682a301a in xcb_wait_for_event () at /lib64/libxcb.so.1
#3  0x00007f275e8a3da9 in  () at /lib64/libQt5XcbQpa.so.5
#4  0x00007f27686fe4bb in  () at /lib64/libQt5Core.so.5
#5  0x00007f2767d3458e in start_thread () at /lib64/libpthread.so.0
#6  0x00007f2767e4b6a3 in clone () at /lib64/libc.so.6
Thread 1 (Thread 0x7f27654a5940 (LWP 7686)):
#0  0x00007f2768e29aa6 in QPainter::drawImage(QPointF const&, QImage const&) () at /lib64/libQt5Gui.so.5
#1  0x0000564c45137858 in  ()
#2  0x0000564c4513c631 in  ()
#3  0x0000564c4515a04d in  ()
#4  0x0000564c4515af7c in  ()
#5  0x0000564c4511f728 in  ()
#6  0x00007f2767d72413 in __libc_start_main () at /lib64/libc.so.6
#7  0x0000564c45120e8e in _start ()

##### Steps to Reproduce (for bugs)
1. Install Fedora 29 and LXQt 0.13.0
2. Login to LXQt

##### System Information

* Distribution & Version: Fedora 29
* Kernel: 4.19.6-300.fc29.x86_64
* Qt Version: 5.11.1
* lxqt-build-tools Version: 0.5.0
* libqtxdg Version:
* libfm-qt Version: 0.13.0
* Package version: 0.13.0 - Fedora package release 2.fc29

**Comment by tsujan** [comment]
Most probably, this is about a bad build (Fedora's). There's nothing about pcmanfm-qt or libfm-qt in the log and the problem is not reproducible.
