### ISSUE TITLE
Please, could you add an option to apply settings to a whole folder tree 

### ISSUE THREAD

**Issue by hhl** [lxqt/pcmanfm-qt#843]
Hi, it is annoying to configure the personal settings for every new folder, really!!!
I think one global setting dialogue in preferences would be enough, like dolphin (sorry i have no other pic) has, --> 
![2018-12-14_13-45](https://user-images.githubusercontent.com/194791/50022078-4e37ca80-ffdb-11e8-93d4-310cdf14022f.png)

**Comment by tsujan** [comment]
> Hi, it is annoying to ...

Not to me, who have used it from start.

> I think one global setting dialogue in preferences....

That means settings should be preserved for all folders, which isn't what this feature is about. There are are many differences between pcmanfm-qt and dolphin.

**Comment by hhl** [comment]
yeah, sorry, i had overseen that option in the dialogue.
talked to agaida and he has shown me where to find.
greetings
