### ISSUE TITLE
Add option to sort files by "Creation Date"

### ISSUE THREAD

**Issue by EarthlingX** [lxqt/pcmanfm-qt#852]
##### Feature Request

PCManFM-Qt provides several options to sort files in a folder within _"View"_ => _"Sorting"_ => _"By Blablabla"_.

Though there is an option available _"By Modification Time"_, this one is not enough in some cases. It would be great to have some further option to sort files _"By Creation Date"_.

Could you implement such a feature? :-) When owning a folder for example with pictures, the creation date could be taken out of the EXIF-data of the image files. I would appreciate it! :+1: 

I am happy to hear about your opinion!

##### System Information
* libfm-qt Version: not installed
* Package version: 0.11.3-2

**Comment by tsujan** [comment]
I have nothing against it other than a bloated right-click menu for a feature that doesn't seem to be useful to many.

BTW, V0.11.3 is prehistoric. In the whole world, there may be only a few users that have it.

**Comment by agaida** [comment]
And we should have a bug with - i wrote one times ago (more colums for pcmanfm-qt i guess) - not implemented yet because of other things to solve.  If implemented we should add the fields to sort (big but - extracting things from exif and sort is a no go, there are things like nomacs)

**Comment by EarthlingX** [comment]
Thanks a lot for your kind replies! :+1: 

The "Creation Date" is also heavily used by office documents etc. - it's not only a feature of images. :-)

> BTW, V0.11.3 is prehistoric. In the whole world, there may be only a few users that have it.

Yeah, I know. Unfortunately the current version of PCManFM-Qt is not yet available in the Debian Stable-repos, but only in Debian Testing or Experimental. Therefore I don't want to mess up my current stable packages with Testing or Experimental... :-) Or is there some other option available to update just the PCManFM-Qt package from different sources?

**Comment by tsujan** [comment]
More thoroughly:

GLib's `GFileInfo` has these definitions:
```
G_FILE_ATTRIBUTE_TIME_CHANGED = ctime (change time)
G_FILE_ATTRIBUTE_TIME_ACCESS = atime (access timee)
G_FILE_ATTRIBUTE_TIME_MODIFIED = mtime (modification time)
```
It also has  `G_FILE_ATTRIBUTE_TIME_CREATED` but it's NTFS ctime.

We get info about `ctime`, `atime` and `mtime`, aren't interested in NTFS ctime and, for obvious reasons, only see `mtime` interesting for sorting

**Comment by tsujan** [comment]
For reference and super thoroughness:

`QFileDevice::FileBirthTime` in Qt is, more or less, like `G_FILE_ATTRIBUTE_TIME_CREATED` in GLib, i.e., it may not be supported on UNIX.

At some point in future, creation time might be added to both for Linux (it's already supported on some Unix like OS's and, in a special case, on Linux). Then, we could think about getting it for our file info and putting it inside Properties dialog. But even then, sorting by it might not be desirable: an argument only for future.

**Comment by Myrddin-Wyllt** [comment]
https://www.phoronix.com/scan.php?page=news_item&px=KDE-Finally-File-Creation-Times

Thought that article might catch the attention of some here. This issue has irked me for too long to remain silent about it. The absence is noticed for people from the Windows world converting to Linux. I noticed it when I switched from using Windows XP to GNU+Linux; date modified works mostly for this, but there are instances (i.e., corporate accounts) where creation date is important.

**Comment by tsujan** [comment]
I told the story above. Until it's handled like other dates, we won't add workarounds for it. Your "feelings" about it won't change anything.

**Comment by tsujan** [comment]
People either forget or don't know that libfm-qt uses GLib. The best place to file a feature request for everyone who likes this feature is GLib's bug tracker. Developers of GLib are Gnome devs; they have a bad habit of not listening to users but, *maybe*, if many users want this, they'll listen.

Needless to say, we aren't responsible for GLib. Also see https://github.com/lxqt/libfm-qt/issues/391

**Comment by agaida** [comment]
https://www.phoronix.com/scan.php?page=news_item&px=Glibc-Statx-Support - maybe we have overseen something?

**Comment by agaida** [comment]
```

struct	statx {
 	__u32	 	stx_mask;	
/* Mask of bits indicating
filled fields */
 	__u32	 	stx_blksize;	
/* Block size for filesystem I/O */
 	__u64	 	stx_attributes;	
/* Extra file attribute indicators */
 	__u32	 	stx_nlink;	
/* Number of hard links */
 	__u32	 	stx_uid;	
/* User ID of owner */
 	__u32	 	stx_gid;	
/* Group ID of owner */
 	__u16	 	stx_mode;	
/* File type and mode */
 	__u64	 	stx_ino;	
/* Inode number */
 	__u64	 	stx_size;	
/* Total size in bytes */
 	__u64	 	stx_blocks;	
/* Number of 512B blocks allocated */
 	__u64	 	stx_attributes_mask;	
/* Mask to show what's supported
in stx_attributes */
/* The following fields are file timestamps */
 	struct statx_timestamp	 	stx_atime;	
/* Last access */
 	struct statx_timestamp	 	stx_btime;	
/* Creation */
 	struct statx_timestamp	 	stx_ctime;	
/* Last status change */
 	struct statx_timestamp	 	stx_mtime;	
/* Last modification */
/* If this file represents a device, then the next two
fields contain the ID of the device */
 	__u32	 	stx_rdev_major;	
/* Major ID */
 	__u32	 	stx_rdev_minor;	
/* Minor ID */
/* The next two fields contain the ID of the device
containing the filesystem where the file resides */
 	__u32	 	stx_dev_major;	
/* Major ID */
 	__u32	 	stx_dev_minor;	
/* Minor ID */
};
```

**Comment by tsujan** [comment]
> maybe we have overseen something?

No!

I knew about that. It isn't implemented in GLib yet.

**Comment by agaida** [comment]
damn :)

**Comment by agaida** [comment]
https://unix.stackexchange.com/questions/50177/birth-is-empty-on-ext4 ...

Today: 
```
% mkdir fucked 
t% ouch fucked/shit

% LANG=C stat fucked
  File: fucked
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 802h/2050d      Inode: 6165034     Links: 2
Access: (0755/drwxr-xr-x)  Uid: ( 1000/  agaida)   Gid: ( 1000/  agaida)
Access: 2019-04-15 01:36:23.239040995 +0200
Modify: 2019-04-15 01:36:23.239040995 +0200
Change: 2019-04-15 01:36:23.239040995 +0200
 Birth: -

% LANG=C stat fucked/shit
  File: fucked/shit
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 802h/2050d      Inode: 6165064     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/  agaida)   Gid: ( 1000/  agaida)
Access: 2019-04-15 01:37:35.068936534 +0200
Modify: 2019-04-15 01:37:35.068936534 +0200
Change: 2019-04-15 01:37:35.068936534 +0200
 Birth: -

rm -r fucked
```
So i guess we have to wait some time - event the current coreutils don't support it

**Comment by tsujan** [comment]
The cost of getting this info should also be considered.

The best place for it is `G_FILE_ATTRIBUTE_TIME_CREATED`. According to GLib's doc, "This corresponds to the NTFS ctime". Apparently, *BSD has no problem with creation time (haven't checked it first hand).

If I find time, I'll check `G_FILE_ATTRIBUTE_TIME_CREATED` to see what it gives us on ext4. Will tell about the result here.

**Comment by agaida** [comment]
http://moiseevigor.github.io/software/2015/01/30/get-file-creation-time-on-linux-with-ext4/

and i think going down that road isn't worth it  :)

**Comment by tsujan** [comment]
Linus Torvalds said "Let’s wait five years and see if there is actually any consensus on it ..." in 2015.

As I said from start, we'll use it whenever it's ready.

**Comment by agaida** [comment]
+ 1

**Comment by tsujan** [comment]
I did my test with `G_FILE_ATTRIBUTE_TIME_CREATED`. The result was surprising in a funny way:

![btime](https://user-images.githubusercontent.com/981076/56149349-9da9f980-5fc1-11e9-9963-538cdc8af9fe.jpg)

For all files, the creation time GLib reports on ext4 is 2070, 3:30 AM. Perhaps, that means it'll be fixed in half a century. We'll see.

On some other filesystems it may report the correct date though.

**Comment by agaida** [comment]
1970, 1. Jan was the time 0 - The begin of our shiny new time as we know it :D 

https://www.unixtimestamp.com/

**Comment by tsujan** [comment]
You're right.

**Comment by Myrddin-Wyllt** [comment]
agaida, are you saying stat isn't working currently to display the Birth field? Mine does (running Manjaro unstable, coreutils-8.31-1):
<pre>
$ mkdir Genesis
$ touch Genesis/Exodus
$ LANG=C stat Genesis
  File: Genesis
  Size: 4096            Blocks: 8          IO Block: 4096   directory
Device: 803h/2051d      Inode: 13244117    Links: 2
Access: (0755/drwxr-xr-x)  Uid: ( 1000/  miasma)   Gid: ( 1000/  miasma)
Access: 2019-04-16 12:04:20.308783697 -0500
Modify: 2019-04-16 12:05:05.661768419 -0500
Change: 2019-04-16 12:05:05.661768419 -0500
 Birth: 2019-04-16 12:04:20.308783697 -0500
$ LANG=C stat Genesis/Exodus
  File: Genesis/Exodus
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 803h/2051d      Inode: 13250829    Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/  miasma)   Gid: ( 1000/  miasma)
Access: 2019-04-16 12:05:05.661768419 -0500
Modify: 2019-04-16 12:05:05.661768419 -0500
Change: 2019-04-16 12:05:05.661768419 -0500
 Birth: 2019-04-16 12:05:05.661768419 -0500
</pre>

I just discovered that the update for coreutils came about a month ago:
https://www.phoronix.com/scan.php?page=news_item&px=Coreutils-8.31-Released

Granted, by the time Debian stable has support; it'll probably be next year so there's no rush. I'm just excited to see progress on something I'd largely given up on.

**Comment by tsujan** [comment]
It isn't what could use in our code. First, GLib should include it and, second, a cost estimation is needed because, whenever we load a folder, we should get it for all of its files. *The main problem is GLib*.

**Comment by tsujan** [comment]
Since KDE devs have done it, it should be doable in GLib too.

It feels weird that, although there are several discussions on Internet about why Nautilus and other GTK file managers don't support it, apparently, (apart from a very old page whose link I lost but it wasn't important), no one has made a new feature request at GLib -- or I couldn't find any; tell me if it exists.

The only remaining way is finding how KDE devs did it and adapting their method to libfm-qt. It's the hard way. But, again, a one-year wait for it doesn't seem unreasonable to me.

**Comment by tsujan** [comment]
Opened https://github.com/lxqt/libfm-qt/issues/397. Please add relevant info (new things, not what we already know) there.

**Comment by agaida** [comment]
@Myrddin-Wyllt  coreutils 8.30 don't do it - i don't care if arch or manjaro has 8.31, if we implement options they should work not only for bleeding edge - but it is a good sign, that it is implemented in coreutils now. So there is hope that glib will follow.

**Comment by tsujan** [comment]
In https://github.com/lxqt/libfm-qt/issues/397, my conclusion was that we should wait for GLib. coreutils's supporting it (yes, it does here) isn't for us.

**Comment by tsujan** [comment]
And even when it's supported by Glib, we should set conditions for it because people may use older versions of GLib and it's definitely not supported by all filesystems.

**Comment by agaida** [comment]
My point is only: coreutils support it **now** it will take some time to be generally available. So my guess is that glib developers has to implement it too since it is in coreutils. The only question that remain is: When it will be implemented and when it is generally available for distributions,

**Comment by tsujan** [comment]
> The only question that remain is: When it will be implemented and when it is generally available for distributions,

I think I should see it (https://github.com/lxqt/libfm-qt/issues/397#issuecomment-484165273) as soon as the support is added -- unless they add a separate function for it, in which case the news will be spread everywhere.
