### ISSUE TITLE
desktop icon won't move unless dropping perfectly into hidden grid

### ISSUE THREAD

**Issue by cubetronic** [lxqt/pcmanfm-qt#860]
##### Expected Behavior
i expect, when i move a desktop icon (file or folder), from one side of the screen to the other (custom positioning), that it should land where i drop it, or very close to where i drop it.

when a user moves a desktop icon, it should drop where they drop it, or as close as possible to where they drop it. it should align itself to a grid by default. (aligning to a grid is much less important than simply making sure icons move when dragged and dropped)

##### Current Behavior

what is currently happening is that if i move a desktop icon on the desktop (file or folder), it only stays where i drop it if:
1) i don't drop it very close to the edge of the screen
AND
2) i use the jedi force to estimate exactly where the grid is, and i drop it exactly in the perfect spot
OR
3) i watch it go all the way back to where it started, and try the whole process again and again until i finally get lucky.

i'm suggesting a bug fix, not an "improvement" or "feature" that makes it so that the user doesn't have to keep trying over and over again to move an icon. in reality, instead of mindlessly wasting my time trying to move icons, i've given up because it doesn't work right. and that means i can't really organize what i'm doing. and that means i don't feel like i can manage my files in LXQT, and that means i stop using LXQT. period.

##### Possible Solution

I don't know where the code is for this, why it works OK in LXDE, and why it doesn't in LXQT...

I browsed the bug list and I've seen lots of dropped bugs because people think it's a feature request or it's just "not possible" or something, and to that, I say... that perhaps that means that LXQT itself is just "not possible" as a viable desktop!

##### Steps to Reproduce (for bugs)

1. move an icon to the edge of the screen. that never works. it should though.
2. move an icon to a spot in between where you think the grid is aligned, and watch it go back.
3. 
4. 

##### Context
i can't organize my files! this is how i organize things, and it just doesn't work.

##### System Information

* Distribution & Version: artix-lxqt
* Kernel: 
* Qt Version: 0.13.0
* lxqt-build-tools Version: 
* libqtxdg Version:
* libfm-qt Version:
* Package version:

**Comment by tsujan** [comment]
Already fixed.

**Comment by cubetronic** [comment]
where? when? how?
