### ISSUE TITLE
desktop icons - right edge moves to upper-left 

### ISSUE THREAD

**Issue by cubetronic** [lxqt/pcmanfm-qt#861]
continuing issue of #500, etc., ALMOST FIXED in version 0.14.0

##### Expected Behavior

if i drag a file on the desktop over to the right edge of the screen, i expect it to relocate to that area of the desktop.

##### Current Behavior

if i drag/drop to right edge, it gets automatically sent to upper-left corner.

##### Possible Solution

could this have something to do with screen bumping to different desktops with openbox? or something like that? i don't know. i doubt it though because if i press a window to the left/right edge, it moves to another desktop. but this bug only happens on the right side. in version 0.13.0 it happened on the right, top, and left, and if not placed on the grid.

##### Steps to Reproduce (for bugs)

1. 1366x768 screen (does that matter?)
2. pcmanfm-qt 0.14.0 Latest commit cbf2090 3 days ago 
3. move file icon on desktop to right edge, or close to it.
4. file moves to upper-left corner

##### Context

trying to accomplish easy reliable drag & drop on desktop.

##### System Information

* Distribution & Version: artix-lxqt-openrc-20181008-x86_64.iso, upgraded to latest packages
* Kernel: 4.19.12-artix1-1-ARTIX #1 SMP PREEMPT Sat Dec 22 13:49:34 UTC 2018 x86_64 GNU/Linux
* Qt Version: world/qt5-base 5.12.0-1 (qt qt5) [installed]
* lxqt-build-tools Version: compiled & installed today from: Latest commit 4502c55 8 days ago 
* libqtxdg Version: community/libqtxdg 3.2.0-5 [installed]
* libfm-qt Version: compiled & installed today from: Latest commit 55275f3 9 days ago
* Package version: pcmanfm-qt compiled & installed today from: Latest commit cbf2090 3 days ago 
* 1366x768 screen

##### installation details
compiling and finding dependencies and all that was pretty straightforward, but i disregarded the instructions about configuring directories based on x64 differences, hoping that my system would be compatible with the scheme, but it wasn't and pcmanfm-qt failed to run which kinda broke my system until i opened a terminal, tried to run it, saw the error (not finding lifm-qt.so.6), and just plain copied:

/usr/local/lib64/libfm-qt.so.6
to
/usr/lib/libfm-qt.so.6

that may be a hacky solution or not, but i am indeed running commit cbf2090 of pcmanfm-qt 0.14.0

**Comment by cubetronic** [comment]
also, dropping near bottom throws icon up to top. this is un-intuitive.. i know nobody wants icons under their taskbar, but a drop at the bottom should be a drop at the bottom...

now playing around with this, i moved my taskbar to the top, and things got really weird...
things behaved like they would with the taskbar at the bottom, except....

if i held an icon near the bottom, the desktop would scroll down a bit.. not much.. and stop.. maybe this has something to do with a feature for people with 1000 desktop icons?.. i don't know, i've never seen that happen.... but it allowed me to place the icon low, but not other icons low.. weird stuff...

**Comment by cubetronic** [comment]
also, moving the taskbar seems to have broken it... the icons for my running programs are still there, but if i click normally on them then nothing happens (they don't appear/disappear) as expected... 

the buttons only work if i'm at the extreme bottom pixel of the button..

maybe not part of pcmanfm-qt; please forward as appropriate

**Comment by tsujan** [comment]
Yes, the right and bottom borders can cause unnatural movements; a problem to fix.

> also, moving the taskbar seems to have broken

Please report that at https://github.com/lxqt/lxqt/issues . The current issue tracker is for pcmanfm-qt.

**Comment by tsujan** [comment]
Back to this:

The problem reported here is only a special case (a single file case) of a more general issue. When multiple files are dropped on Desktop or multiple Desktop items are moved, bad things might happen -- the more files/items are dropped/moved, the more weird the result might be.

I think I've found a solution to all such problems. It seems to work here but I should do more tests and, probably, simplify the code before making a PR.

**Comment by cubetronic** [comment]
cool. also...

the grid should be **left-right justified**.
if i can't place icons on the far-right edge, as close to the edge as possible, then it's hard to access those icons when windows are open.
