### ISSUE TITLE
Archive option doesn' exist when more thn one files are chosen

### ISSUE THREAD

**Issue by zhaojingyits** [lxqt/pcmanfm-qt#867]
##### Expected Behavior
When more than one files are selected in PCManFM-Qt, there should be an option to archive them which is same as that on just one file. However, that one does not appear on PCManFM-Qt on my Lubuntu. This problem doesn't appear on the GTK+ version(PCManFM).

##### Current Behavior
Select one file and right click, then "Archive" option appears in right-click menu;
select more than one files, then it doesn't appear.

##### Possible Solution
Add the "Archive" option to right-click menu of the selection of multi-files.

##### System Information
* Distribution & Version: Lubuntu 18.10
* Kernel: 5.0
* Qt Version: 5.11.1
* libfm-qt Version:0.13.0
* Package version:

**Comment by tsujan** [comment]
Had been fixed ages ago. Use a distro with git LXQt packages!

**Comment by zhaojingyits** [comment]
> Had been fixed ages ago. Use a distro with git LXQt packages!

I use lubuntu 18.10 with the 0.13.0 version of this software. The problem really exists. It happens when different types of files are selected. If files with the same extensions are selected, the "Archive" option appears.

**Comment by tsujan** [comment]
You didn't read my reply.

**Comment by agaida** [comment]
and thats why the ubuntu policy is: Don't file bugs upstream, file bugs in launchpad - so the ubuntu maintainers can take care of after triaging.
