### ISSUE TITLE
About sticky item positioning on desktop

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#879]
The code of pcmanfm-qt's desktop is so that, every time the position of a desktop item is changed by DND, the whole list of custom positions is written to the config file (inside `~/.config/pcmanfm-qt`). I thinks that's also the case with KDE but haven't checked its code.

These writes block I/O for a short time but that depends on the hard drive. On SSD, they're very fast but on HDD, the blocking of I/O may be tangible. Please tell about your experience in this regard: do desktop items move swiftly for you? They don't for me.

To test this hypothesis, I made some changes to the code here, so that custom positions weren't written to the config file during the session but only before quitting. I saw a big difference: while, previously, the items moved with considerable delays, after that change, their movement became very smooth and fast. The custom positions were also remembered when I logged out and in.

There may be a drawback with this approach for some. If pcmanfm-qt doesn't quit appropriately, the custom positions won't be remembered. That never happens here and, IMO, it'll be a sign of a session problem otherwise.

Are item movements OK for you? Or is the jerkiness I see experienced by most users?

**Comment by tsujan** [comment]
OK, a timer that writes to the config file every 10 minutes *if needed* should work as a safeguard against rare exit problems.

**Comment by tsujan** [comment]
@agaida Desktop item movements were always jerky and lagging here and on my old laptop. I thought it was inevitable but, with the above-mentioned change, I see a very smooth movement for the first time. When RAM can be used efficiently, writing to hard so frequently may be seen as a bad design too -- like those spin-boxes/sliders of LXQt configuration that write to hard with every mouse wheel turn (I'll add Apply buttons soon)....

No one answered my question: are desktop item movements smooth for you on HDD?

**Comment by agaida** [comment]
i only have my brand new Laptop from 2008 (single core pentium 32) with HD - so i can't test it rigth now - it runs on debian stable

**Comment by tsujan** [comment]
Never mind! At last, I found a youtube video you'd made to show me another problem -- I'd saved it with youtube-dl -- the lagging item positioning is quite visible in it.

**Comment by tsujan** [comment]
This is what I call a smooth item positioning: https://www.dropbox.com/s/duavzupbc0gdwaq/smooth_movement.mkv?dl=0

**Comment by tsujan** [comment]
After more investigation, I found that the jerky movements weren't caused by writing to disk itself but by an *untimely* writing. Will make a PR and explain everything in its comment.

**Comment by tsujan** [comment]
OK, my conclusion:

The jerky movements don't happen with all HDDs -- they happen to me, perhaps, because of "write-read-verify" (the drive is healthy but hdparm can't disable its "write-read-verify") --  and so, a fix isn't needed for all.

There are at least two ways of guaranteeing swift movements. The config file should be read only once (at startup) and:

(1) Saved on quitting; or
(2) Saved continuously in a separate thread.

I use (1) but also tested (2) and it gave the same result, i,e, swift movements.

I'll close this after a while if there's no complaint about jerky movements of desktop items.

**Comment by tsujan** [comment]
Closing because it isn't an issue for anyone. I use saving on quitting.
