### ISSUE TITLE
Typo in search dialog checkbox

### ISSUE THREAD

**Issue by ianorlin** [lxqt/pcmanfm-qt#883]
##### Expected Behavior
I expected subdirectories to be one word towards the buttom of search dialog. 

##### Current Behavior
I sub directories appears as two words. 
![typoscreenshot](https://user-images.githubusercontent.com/7546640/51657243-e4ef9380-1f58-11e9-8745-e6e32c35bc9a.png)

##### Possible Solution
Remove the erronous space. 
##### Steps to Reproduce (for bugs)
1. Read the file search dialog and the checkbox search in sub directories.
##### Context
I was searching for files and noticed this was two words when it should be one. 

##### System Information

* Distribution & Version: Lubuntu 18.10 
* Kernel: Linux lyn-pc 4.18.0-13-generic #14-Ubuntu SMP Wed Dec 5 09:04:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Qt Version: Qt | 5.11.1

* lxqt-build-tools Version: 
* libqtxdg Version:
* libfm-qt Version: Installed: 0.13.1-5ubuntu7
* Package version:  0.13.0-2ubuntu2

**Comment by tsujan** [comment]
Wouldn't fixing it be easier than reporting it here?

**Comment by tsujan** [comment]
Merged as https://github.com/lxqt/libfm-qt/commit/cd7f0ce87d666d929fbbc498e22030e3a4ae38ab
