### ISSUE TITLE
PcManFm-qt doesn't mount other partition with sddm

### ISSUE THREAD

**Issue by ayhanyalcinsoy** [lxqt/pcmanfm-qt#892]
When I click the other partition on Pcmanfm-qt with SDDM, It says "Not authorized to perform operation". But with LXDM it mount the other partitions without any problem.

##### System Information

* Distribution & Version: Pisi Linux 2.1
* Kernel: 4.19.16 x86_64
* Qt Version: 5.12.1
* lxqt-build-tools Version: 0.6.0
* libqtxdg Version: 0.14.0
* libfm-qt Version: 0.14.0
* Package version: 0.14.0

**Comment by tsujan** [comment]
Your problem isn't caused by pcmanfm-q. You could seek help in the forums of your distro.

BTW, your problem can't be caused by SDDM either.
