### ISSUE TITLE
Request: option to disable automatic transient filter bar

### ISSUE THREAD

**Issue by tylerswagar** [lxqt/pcmanfm-qt#893]
Having recently upgraded to version 0.14.0, I have some mixed feelings about the filter bar always being triggered when I start typing while a folder is open, as someone who relies heavily on the keyboard.  Sometimes it's a quick and ideal way to find the file I'm after, but other times I just want a quick way to select or highlight a file without hiding the entire rest of the folder and its thumbnails until I clear the filter.  Is it possible to have a configurable option to restore the old behaviour of highlighting files instead of opening a search?  I can still trigger the filter bar with Ctrl+I if I so choose, and it would be nice to have both.

**Comment by tsujan** [comment]
I'm afraid a bug report can't be about feelings or tastes.

If you don't like transient filtering, simply disable it by using a permanent filter-bar.
