### ISSUE TITLE
Display the menu on the window border

### ISSUE THREAD

**Issue by GitDema** [lxqt/pcmanfm-qt#894]
It is possible to display the menu like in nautilus ?

![222](https://user-images.githubusercontent.com/8056071/52607435-dffa7180-2e7e-11e9-8457-cdf0749b9745.png)

**Comment by tsujan** [comment]
This is very unrelated to pcmanfm-qt -- or even Nautilus.

**Comment by tsujan** [comment]
More specifically, it's about a global menu plugin in lxqt-panel: https://github.com/lxqt/lxqt/issues/133 . I don't think it'll be implemented (soon) because no LXQt dev is interested in it and no contributor has started to work on it (despite promises).

**Comment by GitDema** [comment]
Thanks for the answer.
