### ISSUE TITLE
A probably redundant method in desktop code

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#899]
The method `DesktopWindow::onDataChanged` seems to do nothing and desktop shortcut items seem to be updated correctly without it when their names are changed (manually).

Probably, the above-mentioned method was needed a long time ago because the delegate code was wrong. Now that the code is correct, it may be removed. More tests are needed.

**Comment by tsujan** [comment]
The above-mentioned method is definitely redundant; I haven't used it since I opened this issue and have encountered no update problem. Will remove it after V0.15.0.

**Comment by shlyakpavel** [comment]
Any updates here?

**Comment by tsujan** [comment]
> Any updates here?

I removed it here since Feb 2019 but forgot to make a PR. Will do it soon. Thanks for the reminder.
