### ISSUE TITLE
"Could not connect to any X display" error

### ISSUE THREAD

**Issue by abacusit** [lxqt/pcmanfm-qt#905]
I installed pcmanfm-qt from epel-release on CentOS 7. The installation process went smoothly. But when I tried to start "pcmanfm-qt", I got this error:

qt.qpa.screen: QXcbConnection: Could not connect to a display
Could not connect to any X display

How can I solve this? Thanks!

**Comment by tsujan** [comment]
This is pcmanfm-qt's bug tracker. For distro specific issues or problems outside LXQt, please use the LXQt forum.
