### ISSUE TITLE
Don't touch extensions in bulk renaming

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#909]
Actually bulk rename (ctrl+F2) of selected files removes also the extension (unlike you retype it in the form), being not very user friendly.
##### Expected Behavior

It should keep the extension for  type of files, example foo1.jpg, foo2.jpg foo3.pdf ecc renaming only basenames.
##### Current Behavior

Bulk rename does by default rename to  foo1 foo2 foo3.

**Comment by tsujan** [comment]
That dialog is for you to change the name to `Name#.jpg`, or `haha#.haha`. There is no guarantee that all selected files should have the same extension and it isn't a good idea to check for that (would be CPU-intensive with a large amount of files).

**Comment by tsujan** [comment]
Oh, I misread this. It's a valid feature request.

**Comment by tsujan** [comment]
The only compact logic can be this: replace extensions if the user provides one (after # -- like `Name#.haha` or ``Name#blah.haha``); otherwise, keep them. No extra explanation will be needed in the GUI.

**Comment by stefonarch** [comment]
You're fast, had to rebuild most (v0.14.1) is here...) to test the commit,  and it works perfectly, with and without custom extension.

**Comment by tsujan** [comment]
Thanks for testing it!

There's only one scenario that can't be covered in this way, namely, when the user wants to remove all extensions. But that doesn't have a practical use case and can be ignored.
