### ISSUE TITLE
The Del Keyboard Touch doesn't work

### ISSUE THREAD

**Issue by BigFoot-Cldl** [lxqt/pcmanfm-qt#916]
##### System Information

* Distribution & Version: Calculate Linux LxQt, Manjaro LxQt & Archlinux LxQt
* Kernel: 4.19

**Comment by tsujan** [comment]
If by "Del Keyboard Touch" you mean the Delete key, it works fine here.

Do you use localization? If yes:

(1) Which language?
(2) Have you installed `qt5-translations`?

**Comment by yasarciv** [comment]
I am facing the same problem. Delete key on the keyboard does not work. I do not understand what the Delete key on the keyboard has to do with the qt5-translations pack. Will I not be able to use the Delete key if my language is not in qt5-translations or if I haven't installed this package?

**Comment by tsujan** [comment]
pcmanfm-qt version + answers to the above 3 questions.

**Comment by yasarciv** [comment]
Pcman version: 0.16.0
I use Turkish language
qt5-translations is installed but isn't work (there is another problem)

**Comment by tsujan** [comment]
Incorrect translations can disable shortcuts. We had a similar problem with the German translation and it's fixed now. The fact is that there's no problem with any shortcut in pcmanfm-qt and without translation.

A Turkish translator is needed in this case. We'd appreciate it if you could check the Turkish translation and correct it.

**Comment by tsujan** [comment]
OK, in the Turkish translation, the shortcut `Del` is translated to `Sil`, which is most probably incorrect. I think it should have been left as it was.

But again, I don't know about Turkish computer keys; a translator is needed.

**Comment by yasarciv** [comment]
I translated most of the Qt components into Turkish (qtbase, qtlinguist etc.).

**Comment by tsujan** [comment]
Nice!

**Comment by yasarciv** [comment]
> Incorrect translations can disable shortcuts. We had a similar problem with the German translation and it's fixed now. The fact is that there's no problem with any shortcut in pcmanfm-qt and without translation.
> 
> A Turkish translator is needed in this case. We'd appreciate it if you could check the Turkish translation and correct it.

Is the translation I need to fix in pcmanfm-qt or in qt?

**Comment by tsujan** [comment]
`pcmanfm-qt_tr.ts` in the source of pcmanfm-qt.

**Comment by stefonarch** [comment]
This remembers me of the `Alt+Enter` translation issue https://github.com/lxqt/pcmanfm-qt/issues?q=is%3Aissue+alt+enter
Could well be an issue in other languages too.

**Comment by tsujan** [comment]
> Could well be an issue in other languages too.

Yes. The translators are responsible for the quality of their translations. We can only check that the syntax is fine.

> Best would be removing (tr) from source?

Some languages may have their strings for it, like they do for `Shift` -- although I know of none.

**Comment by stefonarch** [comment]
Tested fr (suppr), it (canc) and turkish (sil): all are working fine, so in latest git this works, maybe the issue is another, in the release it was sil too.

**Comment by stefonarch** [comment]
But NOT working are: es (supr), dutch (Wis) and lithuanian: Del(Šal)
Mostly Del is translated as Del.
Will make an flag in weblate.

**Comment by tsujan** [comment]
@stefonarch, thanks! So, either @yasarciv's problem is fixed in git or it wasn't related to pcmanfm-qt in the first place.

**Comment by yasarciv** [comment]
> @stefonarch, thanks! So, either @yasarciv's problem is fixed in git or it wasn't related to pcmanfm-qt in the first place.

I could not work a fix on this issue.  I will take care of your suggestions again.

**Comment by stefonarch** [comment]
Just noticed that translating "Shift" in shortcuts probably will never work, at least not in italian. 
Not working shortcuts aren't displayed in the GUI  (but in "hidden shortcuts")
A research for `Shift` showed some existing translations in pcmanfm-qt.

**Comment by tsujan** [comment]
> Not working shortcuts aren't displayed in the GUI (but in "hidden shortcuts")

Yes, incorrectly translated shortcuts are disabled automatically under the target locale.

"Hidden shortcuts" only explains what some shortcuts do; it's pure text.

**Comment by stefonarch** [comment]
I noticed that "Shift" has an qt5-translation in german but not in italian.

I see this pattern after some tests:
*  if a shortcut is  not translated it's not shown in the GUI  menus
* if it's translated correctly or identical (Del as Del or Canc in italian) it will work and qt5-translations will eventually translate  it if its' identical as in source
* if it's translated to just something it just will not work

**Comment by yasarciv** [comment]
I deleted the translation of the Del string from the Turkish translation file and saved the .qm file in /usr/share/pcmanfm-qt/translations. This way the Delete key on the keyboard worked.

**Comment by yasarciv** [comment]
I also deleted the Turkish translation of the Del string in https://translate.lxqt-project.org.

**Comment by stefonarch** [comment]
> I also deleted the Turkish translation of the Del string in https://translate.lxqt-project.org.

Good, it's the safe way. Q5-translation will translate it (if working and if present  a translation).
