### ISSUE TITLE
SFTP Operation not supported

### ISSUE THREAD

**Issue by zajca** [lxqt/pcmanfm-qt#917]
When browsing sftp mounted folder dialog `Operation not supported` appears on each directory entry.

##### Expected Behavior
No error dialog is showing.

##### Current Behavior
Dialog `Operation not supported` appear on each directory change
In terminal `file monitor cannot be created: Operation not supported by backend` appear

##### Steps to Reproduce (for bugs)
1.  Mount folder with sftp
2. Open any folder. (dialog is not shown only when first time open destination with password setting)

##### System Information
* Distribution & Version:  Archlinux
* Kernel:  5.0.0-arch1-1-ARCH
* Qt Version: Qt 5.12.1
* Package version: 0.14.1

**Comment by tsujan** [comment]
Not reproducible.

**Comment by tsujan** [comment]
Are you sure you also updated libfm-qt to 0.14.1?

**Comment by zajca** [comment]
I would make screen capture, but non capture sw is working in sway :/

One more reason could be wayland.

libfm-qt
```
$ pacman -Q libfm-qt                                                       :
libfm-qt 0.14.1-1
```

**Comment by tsujan** [comment]
> One more reason could be wayland.

You mean xwayland -- pcmanfm-qt should run with it under wayland -- but I don't know how it could affect sftp.

The question is which "operation is not supported" in your case.

**Comment by tsujan** [comment]
Oh, it's about remote access under wayland. I'll test with pcmanfm-qt under Plasma wayland...

**Comment by tsujan** [comment]
OK, I tested with Plasma wayland minutes ago and could change dir without seeing any dialog -- exactly like under LXQt.

So, most probably the problem is in sway's wayland support.

In short, wayland is not mature enough (although KDE's wayland support has become the best, as far as I've seen).
