### ISSUE TITLE
Toggle display of modified/creation date

### ISSUE THREAD

**Issue by keith501** [lxqt/pcmanfm-qt#921]
A simple change to display the creation time instead of the modified time.
Add a toggle so that the file manager displays creation time instead of modified time.
As noted on #852 It was decided not to add the option to add creation time. My idea is to either display
modified OR creation time. We are swapping creation time for modified time. In the column options check  
"creation time" or "modified time". It is not possible to select both.
Perhaps add startup option --display-creation-times

**Comment by tsujan** [comment]
Please read https://github.com/lxqt/pcmanfm-qt/issues/852 and don't open another issue about the same topic.

**Comment by keith501** [comment]
You ask me to read #852, and yet I said I have already read it. You just
looked at the title?
As the changes are so simple I will fork and do the code myself.

**Comment by tsujan** [comment]
> As the changes are so simple...

All things are simple before one starts to learn about them.

**Comment by tsujan** [comment]
Creation time in Dolphin:

![dolphin](https://user-images.githubusercontent.com/981076/54484928-ebc5c300-4884-11e9-8df8-0dab9756ae37.png)

Why? Because `QFileInfo::birthTime()` is like GLib's `G_FILE_ATTRIBUTE_TIME_CREATED`, as explained in https://github.com/lxqt/pcmanfm-qt/issues/852.
