### ISSUE TITLE
segfault "error 4 in libQt5Core"

### ISSUE THREAD

**Issue by fenugrec** [lxqt/pcmanfm-qt#925]
##### Expected Behavior
Shouldn't segfault !

##### Current Behavior
When switching back to "console 7" which is running X, the screen flashes a few times (while pcmanfm-qt segfaults and kills X), then X restarts and shows me the lxdm login screen. Everything previously open is lost.

##### Steps to Reproduce (for bugs)
Doesn't happen 100% of the time, but very often.
1. Switch to console 1 (ctrl-alt-1)
2. close lid (suspend)
3. open lid (resume)
4. switch to console 7 (whichever had X running, alt-7)
5. X crashes and auto-restarts.

##### Context
described above. I'm not sure if suspending+resuming triggers a condition in the graphics drivers which makes Qt5 unhappy...

##### System Information
* Artix rolling* Distribution & Version: 
* kernel 4.19.28
* Qt 5.12.1
* libfm-qt 0.14.1
* libqtxdg Version:  3.3.1
* lxqt-build-tools Version: n/a
* Package version: 0.14.1

### dmesg logs
(two different events, note that only one of them was in lxqt-globalkeys)
```
[105588.837178] traps: Core[2504] general protection ip:7ffa2e2f1427 sp:7ffa254959c0 error:0 in
 libc-2.28.so[7ffa2e2d9000+14b000]
[105588.895045] pcmanfm-qt[2487]: segfault at 30 ip 00007f106fbf2186 sp 00007fffd6c370f0 error 
4 in libQt5Core.so.5.12.1[7f106f9fd000+30f000]
[105588.895056] Code: 53 48 83 ec 28 8b 05 11 d0 31 00 83 f8 ff 7c 16 0f b6 05 ad cf 31 00 84 c
0 0f 84 c5 00 00 00 4c 8d 35 be cf 31 00 4d 8d 7e 30 <41> 8b 2f 41 89 ec 41 89 ed 41 81 e4 ff f
f ff 00 41 81 e5 c0 ff ff
.......
[179483.652274] traps: lxqt-globalkeys[22947] general protection ip:7f0574cc7427 sp:7fff4b0c0de0 error:0 in libc-2.28.so[7f0574caf000+14b000]
[179483.789394] pcmanfm-qt[22946]: segfault at 30 ip 00007fc9de46f186 sp 00007ffe282965b0 error 4 in libQt5Core.so.5.12.1[7fc9de27a000+30f000]
[179483.789406] Code: 53 48 83 ec 28 8b 05 11 d0 31 00 83 f8 ff 7c 16 0f b6 05 ad cf 31 00 84 c0 0f 84 c5 00 00 00 4c 8d 35 be cf 31 00 4d 8d 7e 30 <41> 8b 2f 41 89 ec 41 89 ed 41 81 e4 ff ff ff 00 41 81 e5 c0 ff ff
```

I understand this problem might be caused outside of pcmanfm, but I could use some help in locating the issue.

**Comment by tsujan** [comment]
Make pcmafm-qt crash and attach only what comes after `where`:
```
coredumpctl gdb pcmanfm-qt
where
```

**Comment by fenugrec** [comment]
Thanks. My distro doesn't have coredumpctl, I'll try to find an equivalent...

**Comment by tsujan** [comment]
You could also stop pcmafm-qt process and do:
```
gdb pcmanfm-qt
```
type `run` at gdb and, after the crash happened, type `where`.

> My distro doesn't have coredumpctl

I saw at its site: "Simple. Fast. Systemd-free". But systemd isn't evil anymore.

**Comment by agaida** [comment]
Without having a closer look i would guess that the tags: Downstream, not-a-bug and pebcak would be rigth. And i bet that rebuilding the relevant parts in the right build order will fix it :dark_sunglasses:

**Comment by tsujan** [comment]
@agaida I like to know whether the new `QSreen` based desktop code can have any relation to this. Although I think that's highly unlikely, I prefer to wait a day or two for @fenugrec's backtrace before closing this.

**Comment by agaida** [comment]
given that Artix is arch based - i guess that the chosen init system don't should make Qt puke.

**Comment by tsujan** [comment]
OK, I did it 3 times with my other laptop: no crash at all.

The crash @fenugrec sees can be related to anything -- graphic driver, for example -- but not to pcmanfm-qt, especially, because X itself crashes for him.

**Comment by fenugrec** [comment]
deep in qt...
```
#0  0x00007ffff6e66186 in QAbstractEventDispatcherPrivate::allocateTimerId() () at /usr/lib/libQt5Core.so.5
#1  0x00007ffff6e6676a in QAbstractEventDispatcher::registerTimer(int, Qt::TimerType, QObject*) () at /usr/lib/libQt5Core.so.5
#2  0x00007ffff6e66f32 in QBasicTimer::start(int, QObject*) () at /usr/lib/libQt5Core.so.5
#3  0x00007ffff7af45bd in  () at /usr/lib/libQt5Widgets.so.5
#4  0x00007ffff6e9382c in QMetaObject::activate(QObject*, int, int, void**) () at /usr/lib/libQt5Core.so.5
#5  0x00007ffff6e93f00 in QObject::destroyed(QObject*) () at /usr/lib/libQt5Core.so.5
#6  0x00007ffff6e9aaa1 in QObject::~QObject() () at /usr/lib/libQt5Core.so.5
#7  0x00007ffff7e8907f in  () at /usr/lib/libfm-qt.so.6
#8  0x00007ffff6569997 in __cxa_finalize () at /usr/lib/libc.so.6
#9  0x00007ffff7e13548 in  () at /usr/lib/libfm-qt.so.6
#10 0x00007fffffffae10 in  ()
#11 0x00007ffff7fe38de in _dl_fini () at /lib64/ld-linux-x86-64.so.2
Continuing.
```

**Comment by tsujan** [comment]
IMO, it isn't Qt's fault. You should find what causes the crash in X because, when X crashes, other crashes could also follow.
