### ISSUE TITLE
Remove X11 WM menu code and option

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#931]
Reasons:

 * It can confuse users ("How can I configure desktop?");
 * Having no real use, it hides the more important context menu(s) of pcmanfm-qt; and
 * Although I prefer X11 to Wayland *for now*, X11 codes won't be maintainable sooner or later.

Any objection?

**Comment by jubalh** [comment]
> Although I prefer X11 to Wayland for now, X11 codes won't be maintainable sooner or later.

That will take quite some time :D

**Comment by tsujan** [comment]
> That will take quite some time :D

It will, probably.

The speed with which KDE/KWin devs improve their Wayland support is amazing -- selection clipboard should be added soon and what I hate about not being able to position windows might be worked around (I hope).

Our sticking with not so useful X11 codes for the sake of WMs that haven't been developed for years doesn't seem like a good idea to me. LXQt is a classic DE but "classic" doesn't mean a love for ancient things .

**Comment by agaida** [comment]
not every WM has a Menu system implemented - so, if it make our code cleaner and easier to maintain - lets drop it.

**Comment by tsujan** [comment]
> not every WM has a Menu system implemented

An additional reason I forgot to mention.

In old times, Openbox seemed to be "our" WM and we didn't think about running LXQt components under Wayland; hence that option. Now, that's changed.

**Comment by luis-pereira** [comment]
It as no real use, IMO.
No objection.
