### ISSUE TITLE
Feature request: show relative path for search results

### ISSUE THREAD

**Issue by stefonarch** [lxqt/pcmanfm-qt#932]
When doing a search in pcmanfm-qt including subfolders only the filenames are displayed in the results. 
It would be nice to see also immediately their locations. No idea how hard this would be to implement.

**Comment by tsujan** [comment]
> It would be nice to see also immediately their locations.

How? I mean a design suggestion, not the code, of course.

**Comment by tsujan** [comment]
pcmanfm-qt shows the item name as tooltip. That's good because the name can be long and so, elided. What about showing the full path as tooltip in the case of search (and not in other places)?

**Comment by stefonarch** [comment]
Cool would be an extra column "position", but I think that's hard.
Or tooltip or displaying 
```
foo/foo1/result1
foo/result2
result3
foo/foo2/foo3/result4
```

**Comment by tsujan** [comment]
> Cool would be an extra column "position"

That would complicate things a lot -- apart from being hard: The view may not be detailed list and even if it is, adding a column to detailed list that shows up only in search:// is a complication. Adding a "path column" for all locations may be possible but redundant because the usual paths are shown in path bar.

Showing the name as path may also be possible but the string will be elided and so, useless.

Among the suggested options, I think tooltip is the best.

**Comment by stefonarch** [comment]
> Among the suggested options, I think tooltip is the best.

It looks like  search results are always displayed in detailed view, but I agree for tooltips.

**Comment by tsujan** [comment]
Now that I think about it, I envy Krusader's tooltips:

![krusader](https://user-images.githubusercontent.com/981076/55748057-efe39b80-5a52-11e9-9c8e-86549ce092fd.png)

Dolphin's tooltips are too much but the above screenshot shows a practical tooltip, IMO. We can add the path to it.

**Comment by stefonarch** [comment]
So you think to improve all tooltips? 
The path is somehow obvious outside of the search results.

**Comment by tsujan** [comment]
We could add the path only for search:// because, as you said, it isn't needed elsewhere.

But this report made me think about tooltips in general. Our current tooltip has much room for improvement. Tooltips don't add to app's weight, while they can be informative.

**Comment by tsujan** [comment]
The meaning of "piece of cake":

![tooltip](https://user-images.githubusercontent.com/981076/55756380-9edda280-5a66-11e9-873b-2ba4a1fc5267.png)

I think including the path doesn't hurt. After all, the file name is also there.

I used existing strings (Location, File type,..) for the sake of translation.

**Comment by tsujan** [comment]
Final revision for more readability:

![final_revision](https://user-images.githubusercontent.com/981076/55758799-0e569080-5a6d-11e9-9164-66a4870f45a0.png)

**Comment by tsujan** [comment]
Having used the patch for 2 days, I can say Krusader's way is cool: no click in the icon view to see the info one needs.

**Comment by stefonarch** [comment]
Yep, working fine! Is it translatable? 
And what about supressing "location:" in not-search results views?

**Comment by tsujan** [comment]
> Is it translatable?

Yes, like everything in LXQt.

> And what about supressing "location:" in not-search results views?

It's good for lazy users like me who want all info inside a small area -- good for quick reading.

**Comment by tsujan** [comment]
Location is useful in lximage-qt too. This is for all libfm-qt apps.
