### ISSUE TITLE
Remote filesystems should be re-read after file operations

### ISSUE THREAD

**Issue by agaida** [lxqt/pcmanfm-qt#933]
##### Expected Behavior
If i copy or move something within pcmanfm-qt to a location without the ability of monitoring the content of the displayed directory should be re-read and actualized.

##### Current Behavior
The visual representation of this directory stays the same until i hit F5 - not that clever.
* just delete a dir, in that case on a smb share
  ![](https://i.imgur.com/YYPDBDR.png)
* have a look after the dir is deleted
  ![](https://i.imgur.com/yNq3tA3.png)

##### Possible Solution
in case gio monitoring is not possible, find a different way to display the current content.

##### Steps to Reproduce (for bugs)
trivial - just delete something in a share

##### Context
^^

##### System Information
Sid latest git

**Comment by agaida** [comment]
Reason why we should take care: Just double click onto the deleted folder in pcmanfm-qt ...

![](https://i.imgur.com/TamCdZ2.png)

bingo :grinning:

**Comment by tsujan** [comment]
This is like https://github.com/lxqt/libfm-qt/issues/280, IMO.

Now that I have SMB, I understand the pain. Maybe, we could reload the folder after we copy/move a file in it with libfm-qt in the case remote filesystems, and only in their case.

**Comment by agaida** [comment]
It is basically the same - i wouldn't mimic the monitoring, but in cases where things are done via libfm-qt (and we know that we don't have monitoring or any else signals emitted) just re-read. 

Stumbled over it again when i was testing the recursive copy patch for smb.

**Comment by tsujan** [comment]
I'll work on.

Please consider testing my libfm-qt/pcmanfm-qt PRs (although, I'm using them) and, if good, merging them. I know that it'll be boring but rebasing is a torture to me.

**Comment by agaida** [comment]
a) it isn't boring
b) i will do

Only had my priorities on RL and debian in the last two weeks, so LXQt was falling a bit short

**Comment by tsujan** [comment]
> Only had my priorities on RL and debian in the last two weeks

Which means I guessed right. No haste, at all; just need a clean foundation to start new works later.

**Comment by tsujan** [comment]
Good news: I found a way :) It seems to work here. It's actually for https://github.com/lxqt/libfm-qt/issues/280 but, as I suspected, these reports have the same solution.

Bad news: None ;)

**Comment by tsujan** [comment]
As far as I tested the patch with smb and sftp, only renaming isn't covered. If a workaround is possible for it too, It should be added separately later.

**Comment by tsujan** [comment]
Oh, I forgot one case: when a file is cut from a shared folder and pasted into another shared folder. It's easy to add though and it won't need recompilation of pcmanfm-qt.

**Comment by agaida** [comment]
ok, just add it

**Comment by tsujan** [comment]
Will do alongside a workaround for renaming inside shared folder. I have to test something because I think the renaming code was written when other parts of libfm-qt weren't ported to C++11; it can be made much simpler now.

**Comment by tsujan** [comment]
Ah, PCMan's code has potential, so that RENAME could be added to COPY, MOVE and LINK but that will need a little of code restructuring. A job for future; for now, I leave renaming as it is.
