### ISSUE TITLE
'show hidden files' state is not remembered.

### ISSUE THREAD

**Issue by hackbyte** [lxqt/pcmanfm-qt#934]
With PCManFM-Qt v0.13.0 freshly compiled using funtoo's portage/emerge system, i got a nicely working pcmanfm on my desk. Sadly, it does no longer remember that i always want to see hidden files.

##### Expected Behavior
I open a new pcmanfm window or even a tab within an open window and expect the last state of 'view hidden files' remembered. (Actually, i would like to change that as a global option for a user).

##### Current Behavior
When opening a new pcmanfm window or tab, the 'view hidden files' option in the view menu is always _deselected/deactivated_.

##### Steps to Reproduce (for bugs)
Open any pcmanfm directory window, try to see hidden files.

##### System Information
* Distribution & Version: Funtoo 1.3-kit, lxqt-meta pulling pcmanfm-qt
* Kernel: Linux sol 4.19.1-gentoo-sol-2019-04-08T23-46-50CEST #5 SMP Tue Apr 9 00:08:49 CEST 2019 x86_64
* Qt Version: dev-qt/qtgui 5.11.2-r1(5/5.11)^t(02:39:55 AM 04/04/2019)(dbus egl gif jpeg libinput png udev xcb -accessibility -debug -eglfs -evdev -gles2 -ibus -test -tslib -tuio -vnc)
* libfm-qt Version: x11-libs/libfm 1.2.5(0/4.5.0)(03:03:28 AM 04/04/2019)(automount exif -debug -doc -examples -gtk -udisks -vala)
* libqtxdg Version: dev-libs/libqtxdg 3.2.0(02:45:01 AM 04/04/2019)(-test)
* lxqt-build-tools Version: dev-util/lxqt-build-tools 0.5.0(01:55:39 AM 04/04/2019)
* Package version: n/a (rolling release)

**Comment by tsujan** [comment]
0.13.0 is outdated. The latest release is 0.14.1.
