### ISSUE TITLE
After set new wallpaper with pcmanfm-qt, wallpaper will not update without trigger

### ISSUE THREAD

**Issue by ncc-1701-a** [lxqt/pcmanfm-qt#935]
Hi.
I use the dynamic wallpaper (xplanetFX), which use the external script to update wallpaper.
I decide to test updating wallpaper with terminal:
pcmanfm-qt --set-wallpaper=/home/user/picture.jpg --wallpaper-mode=fit

##### Expected Behavior

Wallpaper should update immediately.

##### Current Behavior

When cursor remain over any window region, wallpaper will not update.
Wallpaper will update after mouse cursor move over free (unoccupied with any window) desktop space.

##### Steps to Reproduce (for bugs)

1. Use any terminal. Set the mouse cursor under any window region;
2. Use command: pcmanfm-qt --set-wallpaper=FILE --wallpaper-mode=MODE
3. Do not move the mouse cursor (wallpaper will not update)
4. Move the mouse cursor over free (unoccupied with any window) desktop space: wallpaper will update.

##### System Information

* Distribution & Version: Debian Buster (testing)
* Kernel: 4.19.04 (amd64)
* Qt Version: 5.11
* libfm-qt Version: 0.14.1-1
* libqtxdg Version: 
* lxqt-build-tools Version:  0.6.0-2
* Package version: 

Additional info:
Window manger: openbox or xfwm.

P.S. sorry for my bad English

**Comment by tsujan** [comment]
The problem was elementary; its fix is here: https://github.com/lxqt/pcmanfm-qt/pull/936

BTW, you don't need any external script to update wallpaper. pcmanfm-qt supports slide shows. But, of course, external scripts work too.

**Comment by ncc-1701-a** [comment]
Thanks for quick fixing this issue!

**Comment by ncc-1701-a** [comment]
Have I to close this issue?

**Comment by tsujan** [comment]
No. It'll be closed automatically when its corresponding fix is merged into the source.

**Comment by ncc-1701-a** [comment]
Copy that.
