### ISSUE TITLE
Copying files to DAVS-mount fails

### ISSUE THREAD

**Issue by EarthlingX** [lxqt/pcmanfm-qt#939]
When trying to copy files from my local Debian machine to a server which is mounted via DAVS I receive the following error: "Operation not supported by backend":

![test](https://user-images.githubusercontent.com/38689554/56066777-5e34a080-5d68-11e9-93c9-76cb6936725f.png)

However, in the previous PCManFM-Qt-version (0.13.x) of my old system this has worked completely fine. Also copying files to a SFTP-share works completely smooth without any errors.

##### Expected Behavior
Copy files to server via DAVS is possible without error message.

##### Current Behavior
Does NOT copy files to server via DAVS (see error message).

##### System Information
* Distribution & Version: Debian 10 (Buster)
* Qt Version: 5.11
* libfm-qt Version: not installed
* libqtxdg Version: not installed
* lxqt-build-tools Version: not installed
* Package version: 0.14.1-1

**Comment by tsujan** [comment]
If a single file can be copied, it should be the same as https://github.com/lxqt/libfm-qt/issues/385 (which is fixed).

**Comment by agaida** [comment]
@EarthlingX  - #926626 [G|  |☺] [libfm-qt6] libfm-qt6: Cannot copy dirs over smb - take the package from sid or wait for three days. It is unblocked and should hit buster soon.

**Comment by tsujan** [comment]
@EarthlingX Please don't forget to tell us to reopen this if the problem isn't fixed by the patch @agaida mentioned.

**Comment by EarthlingX** [comment]
Thank you very much for your kind answers! I really appreciate working with new LXQt - the new updates in comparison to Debian Stretch are awesome! :+1: 

@agaida: Does this soon coming update of _libfm-qt6_ affect my installation as well? Even if I didn't install _libfm-qt6_ yet? Or should I install it anyways? :-)

**Comment by agaida** [comment]
libfm-qt6 should be already installed if you are on buster :)

[Packages in Debian](https://qa.debian.org/developer.php?login=pkg-lxqt-devel%40lists.alioth.debian.org&set=yes&comaint=yes&description=0&bugs=3&version=stable&vcs=1&ubuntu=0&excuses=1&bin=1&buildd=2&lintian=1&problems=1&piuparts=1&ci=1&popc=1&watch=1&section=1&ordering=0&uploads=1&packages=connman+fswatch&uploader=)

**Comment by tsujan** [comment]
> libfm-qt6 should be already installed if you are on buster :)

But the patch isn't in it; is it?

**Comment by agaida** [comment]
Why not? :sunglasses: 
```
libfm-qt (0.14.1-4) unstable; urgency=medium

  * Fix recursive copy to smb shares (and possible other remote filesystems)
    (Closes: #926626)
````
The next thing will be the refresh thing - i hope that the release team consider this bug as worthy to fix.

**Comment by tsujan** [comment]
That means you're very fast.

> The next thing will be the refresh thing 

Yes, it's important too. Now that I have it, I wonder how I tolerated `sftp` without it ;)

**Comment by agaida** [comment]
To be honest, that was the question i asked myself very often. :) - And no, that means that the release team has done a good work. (accepting the fix + 5 days to hit testing)

**Comment by EarthlingX** [comment]
I fear you guys will punch me now... :-)

I have to confess something: On my machine _libfm-qt_ is not installed yet, because I installed the whole system without "recommended"-packages to keep it clean and slim. Perhaps _libfm-qt_ is responsible for function of DAVS also?

**Comment by agaida** [comment]
it is impossible to install a system that can be called LXQt without pcmanfm-qt and libfm-qt - if you have libfm and pcmanfm installed, please call it LXDE

**Comment by agaida** [comment]
or $WM + misc packages - but not LXQt.

**Comment by tsujan** [comment]
> I have to confess something: On my machine libfm-qt is not installed yet

LOL! Then, you don't have pcmanfm-qt (as @agaida said) because libfm-qt isn't a recommended package but a crucial dependency.

Fortunately, this report is closed.

**Comment by agaida** [comment]
and please don't file a bug in debian - i will close it without any processing

**Comment by EarthlingX** [comment]
Oh my gosh, shame on me!

I used `dpkg -s libfm-qt` when I checked which version of the package was installed on my machine. However, the correct package name is _libfm-qt**6**_, therefore `dpkg` throw me a "Package is not installed" error message that I took serious and posted it here. I am sorry for this misunderstanding!

Well yeah, _libfm-qt6_ is installed in version 0.14.1-4 for sure, I just checked it again. I would have wondered if the package is not listed as a dependency on packages.debian.org.

I am very sorry!

**Comment by tsujan** [comment]
We're all fallible human beings. Mistakes happen.

Anyhow, there's only 1% chance, at most, that the problem exists with the latest libfm-qt+pcmanfm-qt.

By the way, we've named it as libfm-qt here; its package name may be different in different distros (like in Debian).

**Comment by agaida** [comment]
dpkg -l libfm-qt* - and debians source package is libfm-qt, the binary now is libfm-qt6 (just have a look at the so-version)

**Comment by EarthlingX** [comment]
Yippiee, just updated the package and: It works! :-) Thank you so much (and for your great patience as well!)

**Comment by tsujan** [comment]
Good to know that.
