### ISSUE TITLE
Excessive margin with mounted devices (in left pane)

### ISSUE THREAD

**Issue by someguy2013** [lxqt/pcmanfm-qt#947]
I'm using Lubuntu 19.04 with LXQt desktop. 

When devices are mounted, they appear in PCManFM-Qt's left pane, "Devices" section. There is a left-justified upward-pointing icon (clicking provides choices to unmount, etc.). The way that icon is crowded leftward toward the label-text for the device, all my devices are "M... ^" and "R...^" 

If that up-arrow control/icon was justified right, there would be *a lot* of space for the label-text. 

**Part 2 (RELATED):** I would even say: the way all the items are indented beneath the section labels (places, devices, bookmarks) isn't necessary and makes the left-pane unnecessarily large (if you want to see all the text). All the items are prefixed with icons. They stand out from the headings that way. Indenting them doesn't add a lot of value that way -- but consumes space, requiring the pane to be wider (for the same visibility of the label-text).

Maybe that indentation could be configurable? Personally, I'd like the pane to be miniturize, space-saving. it's not my primary focus. The more configurable the left pane is, the better (IMO). Maybe font size could be a configurable item for the left-pane? 

**Part 3 (RELATED):** I don't think this warrants a separate report (it's related in the sense of conservation of space): The path is displayed in the top region of PCManFM. It is displayed in boxes. Those boxes seem large'ish to me.

It just feels like I'm looking at a lot of blank space than actual info. I feel like I'm looking at something with "accessibility mode" enabled (for the visually impaired). I don't mean that disparagingly. I know people have different aesthetic tastes. But, it seems a bit on the large, "lots of margin" side of things. And, no configurability that I can find. 

The mounted-device issue seems like just one part of something more in this regard.

**Comment by tsujan** [comment]
*Please fill in the template!* And one report for each topic. We don't have time to process this kind of report.

Although, please don't do that for this report because it's about your personal preferences.
