### ISSUE TITLE
Mouse scroll-wheel speed is being affected in a way other apps are not

### ISSUE THREAD

**Issue by someguy2013** [lxqt/pcmanfm-qt#948]
I am using Lubuntu 19.04 with LXQt desktop.

I'm new to LXQt desktop after using LXDE for 5 years or so. The first thing that struck me is how PCManFM-Qt treats the mouse scroll wheel with *levity* (or enertia). It's very different than DE. 

I found Preferences->LXQt Settings->Keyboard & Mouse (where the scroll wheel "number of lines" can be adjusted). It was 3 lines, I believe. I turned that down 1, and PCManFM seemed reasonable. But, then all the other apps (Featherpad, Google Chrome) seemed too stingy with the scroll wheel.

I don't think that's a good practice to make one application work differently. It's frustrating to have to constantly poise yourself for different behavior (of something so basic as an input device). If it's beneficial for PCManFM to have this "elegance" in movement, I wish it would be an option. I prefer everything to work relatively the same. PCManFM is really "out there" with it's scrolling compared to other apps. It's more than a minor difference. The scroll wheel is almost unuseable for me (in either PCManFM, or in other apps if I dial down the enthusiasm in Keyboard & Mouse).

[I apologize if I sound a little irked by this. I get this feeling when I visit web sites that tamper with the mouse too. There's no reason for it. It's just showing off. Maybe there's more reason for it with a desktop. But, it still feels disturbing to have something so basic function so differently, without me choosing it.). It feels like it crosses some line of mere decoration into actual usability.]

**Comment by tsujan** [comment]
Did you read my reply to some of your other reports? If not, please do!
