### ISSUE TITLE
Unnecessary labels in left-pane "Places."

### ISSUE THREAD

**Issue by someguy2013** [lxqt/pcmanfm-qt#949]
I'm using Lubuntu 19.04 with LXQt desktop.

The left-pane of PCManFM-QT has a menu choice for "Places" or "Directory." When "Places" is chosen, section heading appears beneath it saying "Places." The result is unnecessary consumption of space (Places, Places). 

The menu choice itself serves perfectly as the visual section heading for "places". I think it would be very elegant to not show a section heading (or that first section) when "places" is chosen. (The subsequent section headings could simply be treated as *sub* section headings. Devices and bookmarks are just other collections of "places").

**Comment by agaida** [comment]
@someguy2013 - some remarks
* you should respect the whish of our developers and fill out this damn form
* please consider using launchpad so the Lubuntu Maintainers can triage and bundle upstream requests

**Comment by tsujan** [comment]
@agaida He/she won't read it.

**Comment by agaida** [comment]
@tsujan - we will see :D
