### ISSUE TITLE
mouse scroll wheel advances by rows in the file list rather than lines

### ISSUE THREAD

**Issue by wxl** [lxqt/pcmanfm-qt#951]
LXQt has a a remarkable little advancement over LXDE: a global definition in `lxqt-config-input` for the amount the scroll wheel advances by. This works remarkably well but there is a quirk in in pcmanfm-qt: it takes "lines" to mean rows in the file list. This makes detailed list view scroll remarkably fast, while thumbnail view scrolls remarkably slow.

![dynamic scrolling](https://i.imgur.com/zNea8zt.gif)

##### Expected Behavior
pcmanfm-qt scrolls by the number of lines defined in `lxqt-config-input`, where a line is defined as the height of an item in the sidebar.

##### Current Behavior
pcmanfm-qt scrolls by the number of lines defined in `lxqt-config-input`, but where a line is defined as the height of an item in the file list.

##### Possible Solution
I suggest that we either define a line by the height of an item in the sidebar (and thus it's consistent with other programs), or we make an option in the preferences that allows one to toggle between defining it by the height of an item in the sidebar versus by the height of an item in the file list. We could potentially call it something fancy like "dynamic scrolling," where that defines the current behavior.

##### Steps to Reproduce (for bugs)
 1. Choose one of detailed, thumbnail, or icon view
 1. Using the mouse wheel, scroll the inside of the file list once 
 1. Make note how much the file list moves relative to the sidebar entries
 1. Repeat the above steps for the other views

##### Context
To some degree, I like the fact that the scrolling is efficient. I probably wouldn't change it personally. However, I can see why [other people find it unnerving](https://github.com/lxqt/pcmanfm-qt/issues/948) since it's inconsistent with everything else.

##### System Information
* Distribution & Version: Lubuntu 19.04
* Kernel: 5.0.0
* Qt Version: 5.12.2
* libfm-qt Version: 0.14.1
* libqtxdg Version: 3.3.1
* lxqt-build-tools Version: 0.6.0 
* Package version: 0.14.1

**Comment by tsujan** [comment]
In item views, line always means a row height; in text edits, it's a text line height. There's nothing we could change.

**Comment by wxl** [comment]
@tsujan you make it sound like it's impossible to do something different. Since that's not obviously not the case, let's try approaching this from the perspective of what the original `pcmanfm` does, which is most certainly not the same:

![pcmanfm scrolling](https://i.imgur.com/MtaJLUh.gif)

Part of the reason this gets brought up is because people have a natural tendency to compare things. People compare LXDE and LXQt. They compare the behavior of one application with another. These are not unjustifiable actions. I think it might be wise to take some careful consideration here. Don't forget the "user" in UI.

**Comment by tsujan** [comment]
The visible info of a row (= line of items) is vertically indivisible. Not scrolling by `n × row_height` would be a bug to fix, not a feature to add.

Please don't reopen this again! Thanks!

**Comment by tsujan** [comment]
Please also note that we're way past libfm, pcmanfm and their probable bugs. During the long transition, new bugs and regressions were inevitably introduced and fixed. We've also seen what's good in Dolphin, Nautilus or pcmanfm and tried to include them in pcmanfm-qt — when they haven't been like an overkill — and we'll continue to do so but duplicating bugs/issues isn't an option.

**Comment by wxl** [comment]
The problem is much less about the static information and more about the expectation one has about the ratio between screen movement and mouse wheel movement. Scroll around in the browser for a bit and you get a feel for how much you need to move the wheel to get to the bottom of the screen. Do that same thing in thumbnail view and you wonder where everything went.

As I said before, I am not suggesting we change the behavior, because, I, like you, like it the way it is. However, that is an opinion, in much the same way the perfect theme is an opinion. We allow the use of more than one theme to accommodate different opinions. My suggestion is to recognize the validity of other opinions and merely add an option to accommodate it.

**Comment by tsujan** [comment]
@wxl The distance of scrolling doesn't matter; what's important is *the number of indivisible visual info* (each of which is called a "line") that's scrolled. It's 3 by default and pcmanfm-qt is consistent with other Qt apps in this regard.

Scrolling by `(n+½)×row_height`, for example, would be a bug. pcmanfm-qt doesn't and won't have that bug.

**Comment by tsujan** [comment]
If I wanted to extract something good out of this misunderstanding, it would be a separate option for pcmanfm-qt to change the number of scrolled lines (1, 2, 3.... but *only a digit*). Although I like that idea, I don't do so because otherwise, we might receive another report, saying "why doesn't pcmanfm-qt obey wheel scroll lines I set in Keyboard Keyboard and Mouse Settings," and I'll have to explain, again and again, that pcmanfm-qt has its separate setting and...

Meeting all possible expectations of all users wouldn't be the goal here even if they were right.

**Comment by wxl** [comment]
@tsujan I appreciate your last comments here, as I was beginning to feel like you were not understanding the issue. I still think that if this option were added we would not make it the default. That makes this report you're concerned about a lot less likely, at least assuming you've never received another report like *this* one. Maybe it might not be a terrible idea to leave on a wishlist for a rainy day?

**Comment by tsujan** [comment]
> I was beginning to feel like you were not understanding the issue.

I understood the misunderstanding since your first comment. I explained the same thing three times; that won't happen again.

As for that option, I gave it some thought and found that it wasn't a good idea: When the user enables it, if he/she changes the wheel scroll lines in Keyboard and Mouse Settings, that value will override pcmanfm-qt's setting until he sets the latter again. That would mean inconsistency.

**Comment by wxl** [comment]
Understood. Thanks for considering it.

**Comment by tsujan** [comment]
You're welcome.

And, of course, my reply here was only related to this specific subject. Don't hesitate to share ideas that can enhance pcmanfm-qt!

**Comment by tsujan** [comment]
This implementation doesn't cause inconsistencies and is clean, IMO: https://github.com/lxqt/libfm-qt/pull/419

The only question is how users might find it. The answer is: by reading pcmanfm-qt's comprehensive help doc, which has never been written.

**Comment by agaida** [comment]
Usual answer - there is a documentation - it's called sources. Maybe one step up und write your mentioned documentation someday.

**Comment by tsujan** [comment]
> there is a documentation - it's called sources

:)

> Maybe one step up and write your mentioned documentation someday.

There are so many topics to be covered. I'll surely do it if I have nothing to code for two weeks — which means "never".

**Comment by wxl** [comment]
@tsujan that's super cool! Actually that reminds me of the different scrolling behavior when you're on the scrollbar itself. I would be happy to work up some help documentation, or at least find someone to do so. The person we have doing our documentation is an animal and I bet they would be into it. The only issue is how to find all the goodies, but if the code is as well commented as that commit seems to be, I'm sure it would be fairly trivial.

**Comment by tsujan** [comment]
> The only issue is how to find all the goodies

Good question. Those familiar with the code can't write the doc; those who can aren't familiar with the code. Code comments aren't enough at all for making a doc (they're for programmers).

I'll answer any question about functionalities. But, first, I should make a list of topics at https://github.com/lxqt/pcmanfm-qt/issues/550. Some functionalities may be completely hidden from average user while being very useful. Custom actions are an example; I guess many users don't know that they can add/remove emblems to/from items (I do that a lot); etc.
