### ISSUE TITLE
pcmanfm-qt crashing when menu-cache not available

### ISSUE THREAD

**Issue by jubalh** [lxqt/pcmanfm-qt#952]
I have one system where I compiled `libfm-qt` and `pcmanfm-qt` with `libmenu-cache` being present while compiling. But `menu-cache` was not installed on that system.
So the following happened:

##### Expected Behavior
* start pcmanfm-qt
* Right click on a file, say a .avi
* open with -> other application.
* opens file

##### Current Behavior
* start pcmanfm-qt
* Right click on a file, say a .avi
* open with -> other application.
* crashes with:

```
(process:7186): Menu-Cache-ERROR **: 09:51:26.766: failed to find menu-cached
[1]    7186 trace trap (core dumped)  pcmanfm-qt
```

##### Possible Solution
Of course I'll just install `menu-cache` to solve this. But I wanted to ask here:
Is menu-cache a hard requirement for pcmanfm-qt? Seems not to be the case, but seems to be the case for libfm-qt, right?
Should pcmanfm-qt handle menu-cache not being present and show an error message (not just on stdout) instead of crashing?

**Comment by tsujan** [comment]
Yes, menu-cache is still used by libfm-qt. I don't like that either.

What about closing this and opening a feature request about removing menu-cache dependency at https://github.com/lxqt/libfm-qt/issues?

**Comment by jubalh** [comment]
Yes of course, if this is the right way to go.

If we plan to remove it we don't have to catch the crash :-)

**Comment by tsujan** [comment]
> If we plan to remove it we don't have to catch the crash

Since men-cache still depends on libfm-extra, it should be replaced at some point. We also know that it may cause long delays in reboot/shutdown. But replacing it will need a lot of work, I think.
