### ISSUE TITLE
add tree view option to view modes 

### ISSUE THREAD

**Issue by archymedes** [lxqt/pcmanfm-qt#971]
It would be nice to add tree as a view mode option.
Tree view is so functional for daily work to explore several files from the same place

**Comment by tsujan** [comment]
Side pane → Directory Tree

**Comment by archymedes** [comment]
I would suggest to add this option to main panel. I know the existence of "Directory Tree" on "Side Panel"

**Comment by tsujan** [comment]
pcmanfm-qt and lxqt-panel are separate apps. For panel, please use  https://github.com/lxqt/lxqt-panel/issues

**Comment by archymedes** [comment]
I'm sorry. I refer as this type of view like are present in other file managers like dolphin, pcmanfm of LXDE...etc
![tree view](https://user-images.githubusercontent.com/6970897/58331918-79500100-7e3a-11e9-89ad-9b50ecf02f8e.png)

**Comment by tsujan** [comment]
So, by "main panel" you meant main view, not lxqt-panel.

We don't add duplicate functionalities to pcmanfm-qt just to make it like Dolphin or other FMs. The directory tree view is on the left and the contents of each directory can be seen inside the main view in 4 modes plus a split view.

**Comment by archymedes** [comment]
I don't think it is about to just to make pcmanfm-qt as other file managers. I consider this as a topic about pragmatism, like the split view addition
