### ISSUE TITLE
Option to limit the number of characters in the folder item name

### ISSUE THREAD

**Issue by Katarn** [lxqt/pcmanfm-qt#974]
It is feature request. I would like to have this setting. Because now, if use icons with 32x32 pixels size, the item names are larger than the icons. Subjectively, it seems that outputting 15 characters will be quite enough, but now 30 are output, which is 2 times larger.

**Comment by tsujan** [comment]
The width is the maximum of icon width and the average width of ~13 characters. The height is always 3 lines. According to the author of the app (PCMan), this was the best choice and I agree with him, considering possible font sizes, the intrinsic difference between the info conveyed by the text and by the icon and also the space that's taken.

**Comment by agaida** [comment]
nobody need more than 640k and 8+3 ... (ok, missed the sarcasm tags again)

**Comment by Katarn** [comment]
@tsujan you explained how it works now, but it is not clear from your answer why you closed my feature request. The count of characters displayed under the icon is hardcoded, I suggest putting it into an option customizable by the user. I can put it differently: add an option to change the number of lines, not characters.

**Comment by tsujan** [comment]
> but it is not clear from your answer why you closed my feature request.

It had no practical purpose. Item text can be larger or smaller than item icon, depending on various factors.
