### ISSUE TITLE
DND after scrolling by mouse wheel

### ISSUE THREAD

**Issue by tsujan** [lxqt/pcmanfm-qt#976]
This feature was implicitly requested at https://github.com/lxqt/lxqt/issues/1723

##### Expected Behavior

Press the left mouse button on an item, turn the mouse wheel while the left button is being pressed to scroll the view, and drop the item onto a folder that becomes visible after scrolling.
##### Current Behavior

When the left mouse button is pressed and the wheel is turned, DND starts. There's no way to scroll the view further.
##### Context

It seems that GTK+ has this property by default  (but I'm not sure).
##### System Information
Latest git LXQt

**Comment by tsujan** [comment]
To those who find this feature odd (like me, the first time): KDE devs have implemented it in Dolphin.

It isn't a very useful feature in practice because, if the mouse slightly moves while its left button is pressed, wheel scrolling will be impossible (in Nautilus and Dolphin alike). So, I give it a low priority.

**Comment by bongochong** [comment]
Thanks for keeping an eye on it. It's definitely narrow in scope as a feature (pretty much only relevant to file managers and database management UIs), but it can be very handy when you're in a directory with hundreds of other files and directories. I probably should have filed that issue under pcmanfm-qt too, sorry about that. LXQt is stellar BTW. Been watching it since the razor-qt days and it's great to have it in such a mature state after all these years.

**Comment by tsujan** [comment]
I got curious, implemented it here and, apparently, it works fine. The code was small but 2 private variables were needed.

I have second thoughts about making a PR though. Is it worth adding 2 variables or can it be done even more frugally? Let me use it for a while before making a decision!

**Comment by bongochong** [comment]
Like lightning. Many thanks again!

**Comment by tsujan** [comment]
You're welcome. The idea seemed interesting, especially after I found it in Dolphin too.

**Comment by tsujan** [comment]
OK, I made the PR: https://github.com/lxqt/libfm-qt/pull/435

I don't think it can be done more frugally; after all, it's just about 6-7 extra code lines that work with all libfm-qt based apps.

**Comment by bongochong** [comment]
Amazing! I switched over to LXQt as my sole and main DE a couple of weeks ago (after years of Xfce, followed by a brief stint with KDE, and a longer stint under Unity). This is honestly the only thing I was missing from other desktop environments. I love this project.
