### ISSUE TITLE
DND not working with ark

### ISSUE THREAD

**Issue by wxl** [lxqt/pcmanfm-qt#977]
It is not possible to drag and drop a file from ark to any pcmanfm-qt window, a folder therein, or the desktop.

##### Steps to Reproduce (for bugs)
 1. Open an archive in ark 
 1. Open a pcmanfm-qt window
 1. Drag and drop file from the archive to the pcmanfm-qt window 
 1. Ensure pcmanfm-qt is in control of the desktop
 1. Drag and drop file from the archive to the desktop

##### Current Behavior
Dragging and dropping fails. A general prohibition sign badge appears over the dragged icon when mousing over the areas managed by pcmanfm-qt.

##### Expected Behavior
Dragging and dropping succeeds as it does with other archivers such as:
 * engrampa
 * file-roller
 * xarchiver

##### Possible Solution
I had initially thought this to be an ark bug, but it looks like [according to upstream](https://bugs.kde.org/show_bug.cgi?id=408233), it's not. ark has a dbus API that can be used. As a reference, you can look at [what Dolphin does](https://cgit.kde.org/dolphin.git/tree/src/views/draganddrophelper.cpp). 

##### System Information
* Distribution & Version: Lubuntu 19.10 (development)
* Kernel: 5.0.0
* Qt Version: 5.12.2
* libfm-qt Version: 0.14.1
* libqtxdg Version: 3.3.1
* lxqt-build-tools Version: 0.6.0
* Package version: 0.14.1

**Comment by wxl** [comment]
Oh! I'll also add this: in the comment to my bug they said:

> I don't know how they handle the other archivers. Would be interesting to have a standard way to extract files, if possible.

If such a thing exists, perhaps we could push that to them and call this their bug after all :smile:

**Comment by tsujan** [comment]
lxqt-archiver will support DND to *everywhere* with https://github.com/lxqt/lxqt-archiver/pull/93, by using an unconventional but straightforward method.

ark is an elementary archive manager (I didn't use it under KDE either) and adding code to pcmanfm-qt just to support DND from it isn't something I'd have the slightest motivation to do ;) So, either this will remain open indefinitely or someone will like ark enough to implement it.

**Comment by wxl** [comment]
Yeah, I really want lxqt-archiver to be ready for prime time. I'm all for kicking ark to the curb. Meanwhile, for pure Qt options, it seems to be the one solution. 

I didn't expect there to be much motivation to make essentially hardcoded changes in pcmanfm-qt— it doesn't sit well with me, either. That said, the implementation looks fairly trivial. If lxqt-archiver takes too long to get up and running, maybe I'll find some motivation :wink: 

One question: what is the mechanism by which all the other archivers work? Is this the Direct Save Protocol (XDS) you mention in that pull request?

**Comment by tsujan** [comment]
I agree with you. However, motivation is a personal thing. I explain it with just one sentence: *I hate Ark* ;)

>  If lxqt-archiver takes too long to get up and running

It won't. I'm pretty sure it'll be ready for the next LXQt release (and, most probably, sooner).

> One question: what is the mechanism by which all the other archivers work? Is this the Direct Save Protocol (XDS) you mention in that pull request?

I don't know about all archivers but file-roller and engrampa use XDS. The downsides: (1) They don't work out of the box; and (2) The receiver doesn't decide about copying, overwriting, etc.

**Comment by tsujan** [comment]
To make things more clear:

With file-roller/engrampa, the decision about copying, overwriting, etc. is made by the archiver and *before* extraction; with the above-mentioned method, the decision is made by the receiving app and *after* extraction (in /tmp -- the extracted file(s) will be removed after closing lxqt-archiver or loading another archive).

**Comment by wxl** [comment]
Yeah I got that from the PR. I'm excited to see it in action!

**Comment by tsujan** [comment]
> I'm excited to see it in action!

It works -- I've used the same method in [Arqiver](https://github.com/tsujan/Arqiver) and have been quite happy with it. But users will tell if they like it or not.

After the PR is merged, I'll make another one for window size. Then, I'll search for hidden problems and, if there's still time, work on some features.

**Comment by tsujan** [comment]
We've released lxqt-archiver (a point release might come soon too). I really don't think we should change our code to support an alien app like ark ;)
