### ISSUE TITLE
Show full file name when icon has focus

### ISSUE THREAD

**Issue by Katarn** [lxqt/pcmanfm-qt#980]
Following the example of Windows Explorer. An icon that does not have focus is shown as usual. But when he gets the focus, I suggest that we always show the full file name, as in the attached screenshot.
![example](https://user-images.githubusercontent.com/6339978/59800823-3aee1a80-92f0-11e9-9da2-d1d03f346217.png)

**Comment by tsujan** [comment]
Are you sure you're using pcmanfm-qt?! Please fill in the issue template! It's not just a formality.

This report is very confusing; your screenshot is definitely not reproducible.

**Comment by tsujan** [comment]
Ah, if you mean we should follow the example of Windows Explorer (and the screenshot is from MS Windows), no, we don't and won't.
