### ISSUE TITLE
Pcmanfm-qt on ArcoLinux - set wallpaper per monitor

### ISSUE THREAD

**Issue by erikdubois** [lxqt/pcmanfm-qt#983]
Just a question really.

I have a dual monitor, which I can set easily to extend the desktop to monitor 1 and 2.

However it seems that I do not have the choice to set my wallpaper per monitor.

It will always be stretched over the two screens.

Is it possible to set the wallpaper per monitor?

pcmanfm-qt 0.14.1
ArcoLinux - based on Arch Linux

**Comment by agaida** [comment]
not implemented. known problem for years.

**Comment by agaida** [comment]
You can change the title as often you want to - right now it is not easy possible, It might be that there are solutions with third party software and openbox - at least i read something like that a year ago. But i forget where.

**Comment by tsujan** [comment]
https://github.com/lxqt/pcmanfm-qt/issues/103

Frankly, I've never thought about it -- there have always been more interesting things to do.

**Comment by jubalh** [comment]
>  It might be that there are solutions with third party software

I use `nitrogen` for that. See https://github.com/l3ib/nitrogen/issues/112

So one needs to disable the desktop functionality of pcmanfm-qt and then use nitrogen to set the wallpaper.

**Comment by tsujan** [comment]
Done in https://github.com/lxqt/pcmanfm-qt/commit/dfdf1fa0db00330d927e664c8e6829c0835adfa7

Also, see https://github.com/lxqt/pcmanfm-qt/issues/103#issuecomment-565489909
