### ISSUE TITLE
DND UI incosistency

### ISSUE THREAD

**Issue by spoononatable** [lxqt/pcmanfm-qt#986]
##### Expected Behavior

Left click DND performs default action (move within the disk; copy to another disk).
Right click DND brings up a context menu.

##### Current Behavior

Left click DND brings up a context menu.
Right click DND doesn't work at all.

##### Context

For decades now left click with a mouse performs the default action, while right click brings up a context menu to give you more options, therefor you would expect drag and drop to work the same way. And it does, at least in Windows and XFCE.

**Comment by tsujan** [comment]
There is no right-click DND but just right-click and there is no reason to add one -- Windows and XFCE aren't a good reason.
