### ISSUE TITLE
Wrong sort order for GiB size files

### ISSUE THREAD

**Issue by hollunder** [lxqt/pcmanfm-qt#992]
##### Expected Behavior
When sorting by file size descending I expect GiB size files to come before those with less than 1 GiB size.

##### Current Behavior
Some GiB sized files are sorted in with less than 1 GiB size files.
See attached screenshot for an example.
![wrong_sorting](https://user-images.githubusercontent.com/8207622/62611212-aae24f80-b8f4-11e9-8649-1948fa3102ad.png)

##### Possible Solution
I guess sorting should be done on the size in bytes.

##### Steps to Reproduce (for bugs)
1. Get some files of GiB and MiB sizes in a directory and sort as described.

##### Context
I can't reliably find files based on size due to this bug.
Works as expected in the PCManFM GTK builds.

##### System Information
* Distribution & Version: Arch Linux
* Kernel: 5.2.6-arch1-1-ARCH
* Qt Version: 5.13.0
* libfm-qt Version: 0.14.1
* libqtxdg Version: 3.3.1
* lxqt-build-tools Version: 0.6.0
* Package version: 0.14.1

**Comment by tsujan** [comment]
Thanks for reporting! I can also see the problem with sorting by size for GiB size files.

**Comment by tsujan** [comment]
The fix is here and will be in AUR's libfm-qt-git when merged: https://github.com/lxqt/libfm-qt/pull/452
