### ISSUE TITLE
Detailed List View cosmetics

### ISSUE THREAD

**Issue by mvoelk** [lxqt/pcmanfm-qt#999]
The size column should be right-aligned and the format of the modification date should be consistent with `/etc/locale.conf`. Or at least an option should be provided to set the format to ISO 8601.

I personally use the [en_XX](https://aur.archlinux.org/packages/locale-en_xx/) local for various reasons and most other file manager, including PCManFM support the ISO format in one way or another.

PCManFM-Qt: 0.14.1

**Comment by tsujan** [comment]
The size column is OK and the time format is that of the system locale.

**Comment by mvoelk** [comment]
Thank you for the response. 

The time issue is probably my issue and I will investigate this further.

Does it make any sense to you, that  almost all file managers, even ls -l, align numbers on the right?

**Comment by tsujan** [comment]
> Does it make any sense to you, that almost all...

Not interested in statistical arguments

**Comment by mvoelk** [comment]
Okay, I interpret your answer as a 'no'. It's just because it's easier for the human eye to compare the values.

**Comment by tsujan** [comment]
"Almost all" is misleading in almost all cases. That's why I'm not interested in it.

GTK3 file dialog shows that people may have different kinds of human eyes.

![left-justified](https://user-images.githubusercontent.com/981076/63655954-bc0bd700-c7a3-11e9-92d6-34ac9770c272.png)

**Comment by mvoelk** [comment]
It's clear to me that this is more the GTK3 file chooser dialog and not an application for scientific computing that is developed here. But it's a good example. I think GTK3 developers do not put much emphasis on performance or workflow. IMHO, they ruin the most basic feature and argue that it is too costly to support these. It's also clear to me that these are more political decision then practical. The discussion around the [recursive search](https://gitlab.gnome.org/GNOME/gtk/issues/839) in the GTK3 file chooser is also great examples for these behavior.

**Comment by tsujan** [comment]
The recursive search isn't an exception: Gnome codes are usually sadistic -- one of the reasons why I hate GTK3. But that doesn't mean that everything about GTK3 is absolutely wrong.

Pure numbers or numbers with a single unit *may* be better to be right justified (but no disaster will happen if they aren't, even in scientific apps). That's not the case when we can have `bytes`, `KiB` and `MiB` as units.

**Comment by mvoelk** [comment]
I admit, it's not optimal. In most cases, as in your example, the size of the files is in the same range and right justification is the lesser of the evils.

**Comment by mvoelk** [comment]
![Screenshot from 2019-09-21 10-37-25](https://user-images.githubusercontent.com/6323204/65370756-a67fb500-dc5c-11e9-993d-e28b093e4b5d.png)
K between G and M, honestly?

**Comment by tsujan** [comment]
> K between G and M, honestly?

You could take a look at commits or upgrade to the latest git and see that it was fixed
